### ISSUE TITLE
Suggestion: give everyone "triage" right on helpdesk repo

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#11]
> if someone incorrectly closes an issue, then someone else can reopen it.
> if someone incorrectly reopens an issue, you can reclose it.
> If it becomes a problem, then it can get addressed.
> Like I said, jenkins has always tried to be open and letting anyone that wants to contribute to help contribute.

Ref: https://issues.jenkins.io/browse/INFRA-3175?focusedCommentId=417701

**Comment by timja** [comment]
Not really do-able on GitHub, you can have a team of people that is 'everybody' in your org but you have to manage that and add people to the org.

imo this was just a feature that Jira had that isn't really needed. 
(Of course we can add more teams here with triage or setup a specific team for it)

**Comment by lemeurherve** [comment]
This is a general discussion I though it had to be open after seeing Gavin's comments in the linked Jira issue, nothing definitive, just throwing the idea.

> Not really do-able on GitHub via permissions, you can have a team of people that is 'everybody' in your org but you have to manage that and add people to the org.

Maybe via GHA? Idk, thinking out loud here.

I've also though about managing it via chatops like you suggested too.

**Comment by timja** [comment]
Yeah comment ops would be fine to add some things if we see a need.

But generally I don't really see it being a problem.
I've managed lots of projects on GitHub issues for years and hasn't been an issue. 😄

**Comment by lemeurherve** [comment]
Is this goal of allowing more open management of these issues a priority one in your opinion or can it be delayed a little bit?

**Comment by timja** [comment]
I think this one would be more useful: https://github.com/jenkins-infra/helpdesk/issues/12

**Comment by lemeurherve** [comment]
Closed in favor of https://github.com/jenkins-infra/helpdesk/issues/12
