### ISSUE TITLE
[INFRA-1363] Split package creation and publishing

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1110]
<p>This week was the first security release for which we staged the core releases in advance in a private Artifactory repository. It was a pretty big improvement for release day.</p>

<p>The next step would be to change the package creation and distribution script into two:</p>
<ul>
	<li>Create Package and possibly upload to the destination host, or make otherwise available</li>
	<li>Move the prepared packages to the destination directory and poke the mirrors</li>
</ul>

<p>Goals:</p>

<p>Allow the security officer full control over when the packages should be made available (the second step). Make that process from start to general package availability to users as quick as possible.</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1363" target="_blank">Split package creation and publishing</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as this is a legacy issue. Current release process implements this behavior.
