### ISSUE TITLE
[INFRA-1389] Monitor data volume on usage.j.io

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1135]
<p>Set up monitoring of the data volume that recently ran full in <a href="https://issues.jenkins.io/browse/INFRA-1383" title="usage.jenkins.io:/srv/usage disk is full" class="issue-link" data-issue-key="INFRA-1383"><del>INFRA-1383</del></a></p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1389" target="_blank">Monitor data volume on usage.j.io</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as we have access to this data in datadog already
