### ISSUE TITLE
[INFRA-1412] Automating release of Jenkins plugins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1153]
<p>As a plugin developer I want to release a new version of my plugin by merging into the release branch of my git repo.</p>

<p>From there I expect a jenkins job similar to <a href="https://ci.jenkins.io/job/Plugins/job/create-and-run-job-trigger-plugin/job/master/" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/job/Plugins/job/create-and-run-job-trigger-plugin/job/master/</a> to pick up the changes and release them.</p>

<p>Current state: <a href="https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkins-ci.org" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkins-ci.org</a></p>

<p>This has several drawbacks</p>
<ul>
	<li>it is manual -> error prone and not fun</li>
	<li>Keys / credentials leave jenkins.io infrastructure with all security implications</li>
	<li>It is not trivial as we can see from the <b>Working around common issues</b> section</li>
	<li>Involves SSH which is blocked in our corporate environment</li>
</ul>

<p>As of <a href="https://github.com/jenkins-infra/pipeline-library#pipeline-global-library" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/pipeline-library#pipeline-global-library</a> we guess that the necessary infrastructure is already available?</p>

---
<details><summary><i>Originally reported by <a title="Matthias Cullmann" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=culmat">culmat</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1412" target="_blank">Automating release of Jenkins plugins</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Done in JEP-229
