### ISSUE TITLE
[INFRA-1416] Published packages list is wrong for compressed formats in https://pkg.jenkins.io/debian-stable/ repo

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1158]
<p>The list of LTS packages to be retrieved by the apt(-get) is stored in the repo at <br/>
 <a href="https://pkg.jenkins.io/debian-stable/" class="external-link" target="_blank" rel="nofollow noopener">https://pkg.jenkins.io/debian-stable/</a> in the files<br/>
 Packages<br/>
 Packages.bz2<br/>
 Packages.gz<br/>
 Packages.lzma</p>

<p>It looks like the only uncompressed file Packages is correct, the rest have wrong/outdated packages list, for example missing the 1.651.3 version - package jenkins_1.651.3_all.deb.</p>

<p>By default apt(-get) will fetch compressed packages list. This means that by following the install instructions, after<br/>
 apt-get update<br/>
 apt-cache policy jenkins<br/>
 the user will not see correct package versions available, most notably 1.651.3, thus unable to install it the recommended way.</p>

---
<details><summary><i>Originally reported by <a title="Maksym Ruchko" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jenkins_rm">jenkins_rm</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1416" target="_blank">Published packages list is wrong for compressed formats in https://pkg.jenkins.io/debian-stable/ repo</a></i></summary>
<i><ul>
<li><b>status</b>: Reopened
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing this issue as it seems outdated ans as both the package generation system and infrastructure changed a lot.

Feel free to reopen if you still have the issue!
