### ISSUE TITLE
[INFRA-1429] Key expirations must be monitored

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1171]
<p>Currently we have no other solution than waiting for a key to expire before renewing it.<br/>
We should find a solution for following type of keys</p>
<ul>
	<li>Azure AD App Client Secrets</li>
	<li>jenkins-ci.org certificates</li>
	<li>update center signing certificates</li>
	<li>release gpg keys</li>
	<li>artifactory</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1429" target="_blank">Key expirations must be monitored</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
there's a team calendar now, @dduportal is that enough or do we want something else?

**Comment by dduportal** [comment]
Superseeded by #2922 

- Team calendar is a first great way, but automated monitoring is clearly an improvement.
