### ISSUE TITLE
Auto label issues based on service selected

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#12]
Extract text in some way and then label the issue based on the service that was selected.

Could then auto notify people based on service routing rules with something like:
https://github.com/marketplace/actions/issue-label-notifier

e.g. update center to daniel
triage to whomever is on 'triage' duty for the week etc

**Comment by lemeurherve** [comment]
I like the idea, will have to think about it, especially the labels part as it touches some improvements we're putting in place with updatecli, and more generally https://github.com/jenkins-infra/helpdesk/issues/6
