### ISSUE TITLE
[INFRA-1464] Correct jenkins-infra/azure brokeness which attempts to delete an active VNet

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1202]
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_network.public_prod: 1 error(s) occurred:

* azurerm_virtual_network.public_prod: network.VirtualNetworksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code=<span class="code-quote">"InUseSubnetCannotBeDeleted"</span> Message=<span class="code-quote">"Subnet dmz-tier is in use by /subscriptions<span class="code-comment">/****/</span>resourceGroups/infracijenkinsci/providers/Microsoft.Network/networkInterfaces/trusted-agent-1-nic/ipConfigurations/testconfiguration1 and cannot be deleted."</span> Details=[]

</pre>
</div></div>

---
<details><summary><i>Originally reported by <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1464" target="_blank">Correct jenkins-infra/azure brokeness which attempts to delete an active VNet</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Old issue, closing it.
