### ISSUE TITLE
[INFRA-1497] Allow non-admins to sign up users

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1230]
<p>Currently the processing of signup requests is limited to account app admins for no real reason: It's basically just bypassing the captcha and other spam checks, otherwise not a privileged operation (right <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">R. Tyler Croy</a>?)</p>

<p>So it should be possible for other users to process signup requests.</p>
<h2><a name="Possibleimplementation%3A"></a>Possible implementation:</h2>

<p>To not need to extend LDAP data with a flag on authorized accounts, we could include a secret signup-attempt-specific token in the links sent to the accounts mailing list. If someone with access to that list then uses the direct link and provides the correct token matching the attempted user name/email address/whatever, signup works (otherwise, it does not).</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1497" target="_blank">Allow non-admins to sign up users</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Don't fully understand this, guessing it's old and not needed now
