### ISSUE TITLE
[INFRA-1502] Insert new community update center root CA

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1236]
<p>The current UC root CA will expire in 2021. Since this key certificate is baked into jenkins.war, it needs a plenty of time to rotate. I think two years window would be sufficient, but since I looked, we might as well start now.</p>

<p>This would be an opportunity to upgrade the key used to sign it. Currently, the key strength is RSA/2048.</p>

<p>Beware of the export control restriction in JVM. I don't know if it's still in place, but if it is it places a limit to the key length we can use.</p>

---
<details><summary><i>Originally reported by <a title="Kohsuke Kawaguchi" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kohsuke">kohsuke</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1502" target="_blank">Insert new community update center root CA</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by MarkEWaite** [comment]
As far as I can tell, this is resolved
