### ISSUE TITLE
[INFRA-1507] Update JIRA linker bot to support the new JEP-3 workflow

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1241]
<p>Update JIRA linker bot to support the new workflow: <a href="https://github.com/cloudbees/java.net-scm-issue-link" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/cloudbees/java.net-scm-issue-link</a></p>

<ul>
	<li>“FIXED <a href="https://issues.jenkins.io/browse/JENKINS-123" title="Project relationship shows incorrect result when..." class="issue-link" data-issue-key="JENKINS-123"><del>JENKINS-123</del></a>” should now move the tickets to the “Fixed But Not Released” state in JIRA in the following components:
	<ul>
		<li>Jenkins core</li>
		<li>All modules and libraries bundled into the Jenkins core</li>
		<li>Remoting Library</li>
		<li>Winstone</li>
		<li>Extras Executable WAR</li>
	</ul>
	</li>
	<li>JIRA issue link bot documentation should describe a way to change flow in other components if needed</li>
</ul>

<p>Postponed action item: TBD: Automatically fill in the “Released as” field according to POM.xml (proposed by Ullrich Hafner)</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1507" target="_blank">Update JIRA linker bot to support the new JEP-3 workflow</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Bot is no longer in use
