### ISSUE TITLE
[INFRA-1514] Enable labels in HOSTING project

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1247]
<p>I see no reasons why the labels are disabled there. Wanted to link Kotlin STL to JEP-200 (<a href="https://issues.jenkins.io/browse/HOSTING-492" title="Kotlin Standard Library plugin" class="issue-link" data-issue-key="HOSTING-492"><del>HOSTING-492</del></a>), but it seems I cannot change labels.</p>

<p>CC <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix" class="user-hover" rel="slide_o_mix">Alex Earl</a></p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1514" target="_blank">Enable labels in HOSTING project</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Damien Duportal" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dduportal">dduportal</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as we're using Github issues for the project HOSTING now.

**Comment by dduportal** [comment]
This is about another Jira project: we have to keep it open until fixed.
