### ISSUE TITLE
[INFRA-1522] Create a Dockerized service for updating JIRA issues by listening to GitHub commits

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1255]
---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1522" target="_blank">Create a Dockerized service for updating JIRA issues by listening to GitHub commits</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
not planned
