### ISSUE TITLE
[INFRA-1523] Get the dockerized commit linking service hosted on Jenkins INFRA

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1256]
<p>Currently the service runs somewhere on KK's machine. We need to rework it and get hosted on Jenkins INFRA</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1523" target="_blank">Get the dockerized commit linking service hosted on Jenkins INFRA</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
not planned
