### ISSUE TITLE
Allow infra.ci.jenkins.io to build on VMs with Docker Engine

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#13]
### Service

infra.ci.jenkins.io

### Summary

The goal is to allow infra.ci to spawn VM to benefit of Docker Engine.

- Actual configuration of infra.ci for VMs (Windows VM and ARM Linux on AWS EC2): https://github.com/jenkins-infra/kubernetes-management/blob/main/config/ext_jenkins-infra.yaml#L310-L392
- Actual (working) config. for ci.jenkins.io (which is already using our packjer image 0.10.0 for Linux Docker VMs):
  - https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/azure.ci.jenkins.io.yaml
  - https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/common.yaml

Don't forget the updatecli manifest :)

**Comment by timja** [comment]
Could you add why / what for? Just for additional context 😄

**Comment by smerle33** [comment]
don't worry tim, it's more a task for me than anything else ... i am on the learning curve :) ...

**Comment by dduportal** [comment]
A bit more context: https://github.com/jenkins-infra/packer-images/pull/164 requires to have Docker Engines available on the agents.

Docker in Docker is not acceptable due to security, and packer is not able to use an img or a standalone mobykit daemon.

=> We need VMs.


Since infra.ci has a remnant of EC2 VM templates wor Windows and ARM Linux, the goal is to add the same template as in ci.jenkins for Intel (and update ARM + windows + keep track of this)
