### ISSUE TITLE
[INFRA-1601] Datadog doesn't detect when the accountapp is down

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1323]
<p>Even if we monitor <a href="https://accounts.jenkins.io" class="external-link" target="_blank" rel="nofollow noopener">https://accounts.jenkins.io</a>, it doesn't seem to detect failures</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1601" target="_blank">Datadog doesn't detect when the accountapp is down</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Gregory Zussa" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=gzussa">gzussa</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Discussing with @olblak we could also create a technical jenkins user, and use a synthetic monitor testing a complete login to check accountapp & ldap connection.

**Comment by lemeurherve** [comment]
Synthetic monitor in place and working.
