### ISSUE TITLE
[INFRA-1608] Deal with deprecation of GitHub Services

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1330]
<p>There is some sort of daemon which adds messages to JIRA issues when commits mentioning the issue ID are pushed to GitHub. I recently noticed these messages printing a warning that linked to <a href="https://developer.github.com/changes/2018-04-25-github-services-deprecation/" class="external-link" target="_blank" rel="nofollow noopener">Announcing the deprecation of GitHub Services</a>. Whatever we have set up will need to replaced or removed I suppose.</p>

---
<details><summary><i>Originally reported by <a title="Jesse Glick" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1608" target="_blank">Deal with deprecation of GitHub Services</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
this was removed
