### ISSUE TITLE
[INFRA-1625] Define a mechanism to automatically update ATH version in essentials.yml

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1347]
<p>As part of the essentials project, there is a new step in <a href="https://github.com/jenkins-infra/pipeline-library" class="external-link" target="_blank" rel="nofollow noopener">pipeline-library</a> to run the <a href="https://github.com/jenkinsci/acceptance-test-harness" class="external-link" target="_blank" rel="nofollow noopener">ATH</a> that is currently used at least by <tt>core</tt> and <tt>git-plugin</tt>.</p>

<p>This step requires the version of the ATH to use to be specified, so, for example, you can specify <tt>master</tt> to use the master branch of the ATH, or any concrete commit if you need something more specific.</p>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick" class="user-hover" rel="jglick">Jesse Glick</a> Has expressed some valid concerns about using non-deterministic versions of the ATH as  that could potentially introduce some entropy in the results even without changes in the tested code, on the other side if you set a fixed commit you are lacking updates and fixes in the ATH, for example, consider the following scenario:</p>

<ul>
	<li>Maintainer of plugin A implements some changes in the plugin that mean a change in the UI that break the ATH</li>
	<li>As plugin A run all relevant ATH tests the maintainer notices the problem and fixes the ATH, updating the corresponding metadata file to point to the new commit</li>
	<li>All other plugins are going to have failed tests unless they are advised to update their metadata file</li>
</ul>

<p>My proposed solution is a tool like the one defined in <a href="https://issues.jenkins-ci.org/browse/JENKINS-50953" class="external-link" target="_blank" rel="nofollow noopener">JENKINS-50953</a> that would detect any merge (or will run periodically, or manually  or in any other TBD way)  into ATH master and update automatically the ATH version in a deterministic way to the latest available, solving the problem of having the latest available changes and at the same way being deterministic enough</p>

<p>The purpose of this ticket (if considered worthy) is to provide a design for such a tool, further follow up tasks will implement it</p>

<p>WDYT <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev" class="user-hover" rel="oleg_nenashev">Oleg Nenashev</a> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick" class="user-hover" rel="jglick">Jesse Glick</a> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=batmat" class="user-hover" rel="batmat">Baptiste Mathus</a> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">R. Tyler Croy</a>  </p>

---
<details><summary><i>Originally reported by <a title="Raul Arabaolaza" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rarabaolaza">rarabaolaza</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1625" target="_blank">Define a mechanism to automatically update ATH version in essentials.yml</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as essential is not a thing anymore in 2023
