### ISSUE TITLE
[INFRA-1633] Stop building PR merges

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1355]
<p>I complained about this on Apr 26 but was told by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">R. Tyler Croy</a> and <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">Daniel Beck</a> it was not really an issue. It <em>is</em> an issue. My plugin PR build has now been sitting for 47m waiting for an executor, the build queue has 111 items (<a href="https://ci.jenkins.io/load-statistics?type=min" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/load-statistics?type=min</a> says it was up to >210 at one point), and all of our executors are rebuilding core PRs, one of which I see has not been touched since 2012. This is totally unreasonable. We really need to apply <a href="https://github.com/jenkinsci/basic-branch-build-strategies-plugin/blob/master/docs/user.adoc#change-requests" class="external-link" target="_blank" rel="nofollow noopener">this setting</a> at least to core builds, if not everywhere.</p>

---
<details><summary><i>Originally reported by <a title="Jesse Glick" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1633" target="_blank">Stop building PR merges</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Damien Duportal" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=dduportal">dduportal</a>
<li><b>status</b>: In Progress
<li><b>priority</b>: Critical
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as it should not be an issue anymore (or at least no one complained about it in the 3 past months :troll: ).

Feel free to reopen with details if needed.

**Comment by jglick** [comment]
This is still a problem in core. I am surprised to see it closed (https://github.com/jenkinsci/jenkins/pull/6780#issuecomment-1175547427). Please reopen.

**Comment by jglick** [comment]
https://groups.google.com/g/jenkinsci-dev/c/4fx00lI3DlE/m/djM3cmkOAgAJ

**Comment by NotMyFault** [comment]
Thanks for linking the issue, Jesse. I see this logic has logic has been applied to the Tools folder and therefore affecting bom only atm.
For the reasons outlined here and on the mailing thread I'd vouch to enable it on the Core folder or at least Core/jenkins.

**Comment by timja** [comment]
I've switched Tools and Core to pr-head

Let's monitor for a bit and we can easily switch back if it causes a problem
