### ISSUE TITLE
[INFRA-1656] Update Center on Azure: Design

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1375]
<p>The <a href="https://updates.jenkins.io" class="external-link" target="_blank" rel="nofollow noopener">Update Center</a> is a web service that provides information to jenkins instances in order for them to know if core/plugins need to be updated and where to find appropriated updates.<br/>
This service is currently running on the AWS account and need to be migrated to Azure.</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1656" target="_blank">Update Center on Azure: Design</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Ping @lemeurherve : with the CloudFlare's R2 proposal, this issue might be of help for you.

Don't forget to read https://github.com/jenkins-infra/iep/pull/16 in details.

**Comment by dduportal** [comment]
Superseded by https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1603074564
