### ISSUE TITLE
[INFRA-1662] JEP: Hosting Requirements for libraries and API plugins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1381]
<p>It is a follow-up to the discussion in <a href="https://github.com/jenkins-infra/repository-permissions-updater/pull/723" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/repository-permissions-updater/pull/723</a> . For Jenkins contributors it's unclear what can and what cannot be hosted in Jenkins project when it comes to shared libs and API plugins.</p>

<p>My proposal would be to create a JEP and define requirements there.</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1662" target="_blank">JEP: Hosting Requirements for libraries and API plugins</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Not a problem afaik, api plugins have been hosted many times
