### ISSUE TITLE
[INFRA-1665] Grant oleg_nenashev write permissions in jenkins-infra/java.net-scm-issue-link

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1384]
<p>Follow-up to <a href="https://issues.jenkins.io/browse/INFRA-1509" title="Get JIRA linker bot hosted on Jenkins insfrastructure" class="issue-link" data-issue-key="INFRA-1509"><del>INFRA-1509</del></a></p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1665" target="_blank">Grant oleg_nenashev write permissions in jenkins-infra/java.net-scm-issue-link</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Oleg is in the "contributor" team, which has write access to the repo https://github.com/jenkins-infra/java.net-scm-issue-link/
