### ISSUE TITLE
[INFRA-1694] Reconfigure DockerHub to build Java 11 experimental images from the master branch

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1412]
<p>Currently Java 10 and 11 branches are built from the feature branches.</p>

<p>Once all changes in <a href="https://issues.jenkins.io/browse/JENKINS-52012" title="Java 11 Preview Availability in Weekly Releases" class="issue-link" data-issue-key="JENKINS-52012"><del>JENKINS-52012</del></a> is upstreamed, it makes sense to switch the build to the master branch (if possible)</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1694" target="_blank">Reconfigure DockerHub to build Java 11 experimental images from the master branch</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
no longer needed
