### ISSUE TITLE
[INFRA-1698] repo.azure.jenkins.io return 504 , ReasonPhrase:Gateway Time-out

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1416]
<p>Sometimes repo.azure.jenkins.io return '504 , ReasonPhrase:Gateway Time-out' even if neither artifactory or  proxy is down.</p>

<p>The <a href="https://github.com/jenkins-infra/repo-proxy/blob/master/conf.d/default.conf" class="external-link" target="_blank" rel="nofollow noopener">nginx</a> configuration can probably be customized with following ideas:</p>
<ul>
	<li>Set proxy_
{read|send|connect}
<p>_timeout to 240 instead of 900 as anyway the azure loadbalancer drop keep alive connection after 4minutes.</p></li>
</ul>

<p>The nginx docker image is defined here <a href="https://github.com/jenkins-infra/repo-proxy" class="external-link" target="_blank" rel="nofollow noopener">here</a></p>

<p>~~~<br/>
  proxy_connect_timeout     240;<br/>
  proxy_send_timeout   240;<br/>
  proxy_read_timeout   240;<br/>
  send_timeout      240;<br/>
~~~</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1698" target="_blank">repo.azure.jenkins.io return 504 , ReasonPhrase:Gateway Time-out</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
this service is decommissioned
