### ISSUE TITLE
[INFRA-1724] Create dedicated job to run full ATH agains stable branches

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1441]
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick" class="user-hover" rel="jglick">Jesse Glick</a>,<a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">R. Tyler Croy</a>, please have a look as the 2 of you seem to have a different idea of how to do this.</p>

<p>There is the need for LTS officer to have an ability to execute full ATH testsuite against a stable branch before we approve it for the release. For reasons we ware not able to address in years, the suite is not always reliable in reporting problems.</p>

<p>Current approach crafted by Tyler and I back in March is using different Jenkinsfile for stable branches (or different handling of those branches in <a href="https://ci.jenkins.io/job/Core/job/jenkins/" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/job/Core/job/jenkins/</a>) so they execute the ATH whole (instead of <tt>SmokeTest</tt> category they run on master). Now if I understood Jesse<span class="error">&#91;1&#93;</span> correctly, the fact the testsuite is not stable prevent the incrementals to work as expected.</p>

<p>The alternative he suggests there is having a dedicated job on ci.jenkins.io for this purpose. Since both would work equally well for us, I am open to do this.</p>

<p><span class="error">&#91;1&#93;</span> <a href="https://github.com/jenkinsci/jenkins/pull/3468" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/3468</a></p>

---
<details><summary><i>Originally reported by <a title="Oliver Gondža" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olivergondza">olivergondza</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1724" target="_blank">Create dedicated job to run full ATH agains stable branches</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
No longer an issue
