### ISSUE TITLE
[INFRA-1730] set up new fallback host for mirrorbrain

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1447]
<p>We currently have the problem that the fallback host has extremely limited bandwidth, so that recently plugins, that aren't yet available on mirrors, may not be downloadable for most users.</p>

<p>(<a href="https://issues.jenkins.io/browse/INFRA-1302" title="Unable to download plugins" class="issue-link" data-issue-key="INFRA-1302"><del>INFRA-1302</del></a>)</p>

<p>To prevent this problem, I propose to set up a fallback mirror that is not file based, but rather just contains an htaccess file with redirects to the Artifactory maven repo.</p>

<p>update-center2 is being extended to generate the htaccess file in <a href="https://github.com/jenkins-infra/update-center2/pull/224" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/update-center2/pull/224</a></p>

<p>All we need is a new virtualhost or similar, and that to be configured as the fallback mirror in mirrorbrain. Then we regularly rsync the generated htaccess file from update-center2 builds, and done.</p>

<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler" class="user-hover" rel="rtyler">R. Tyler Croy</a> asked that Olivier take care of this, since he has no time.</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1730" target="_blank">set up new fallback host for mirrorbrain</a></i></summary>
<i><ul>
<li><b>status</b>: Reopened
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closed as done - https://github.com/jenkins-infra/documentation/blob/1769304a37bd16f84f1c1b8e67f71a6b9503f6e8/runbooks/fallback.get.jenkins.io.md
