### ISSUE TITLE
[INFRA-1752] Clean up write permission for the ec2 hosted plugin

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1465]
<p>I would like to reduce (cleanup) the list of the people able to release the hosted ec2-plugin, as reported by <a href="https://jenkins.io/doc/developer/publishing/source-code-hosting/" class="external-link" target="_blank" rel="nofollow noopener">https://jenkins.io/doc/developer/publishing/source-code-hosting/</a> today there are 11 person in the list.</p>

<p>I'd like to have only  two person :</p>

<p>thoulen</p>

<p><a href="https://github.com/francisu" class="external-link" target="_blank" rel="nofollow noopener">francisu</a></p>

<p> </p>

<p>Thanks</p>

---
<details><summary><i>Originally reported by <a title="FABRIZIO MANFREDI" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=thoulen">thoulen</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1752" target="_blank">Clean up write permission for the ec2 hosted plugin</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Maintainers have since changed, too late to action this
