### ISSUE TITLE
[INFRA-1821] Review jenkins-infra core team permission on github

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1527]
<p>They are 71 repositories under jenkins-infra organisation but only 42 in the core team.And several of them only have read or write permissions.<br/>
It would be nice that the core team would be able to configure all repositories </p>

<p>When I transfer a repository to the jenkins-infra organisation, I can define during transfert which teams have read access to them but then I have no way to modify them</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1821" target="_blank">Review jenkins-infra core team permission on github</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Will be taken in account with #6
