### ISSUE TITLE
[INFRA-1832] Setup triggers for Jenkins Images auto-release when upstream images are updated

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1538]
<p>Currently there is no automatic release flows for Docker images when upstream OpenJDK image gets updated. IMO we need to setup something so that upstream patches get propagated to "latest" images without delay</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1832" target="_blank">Setup triggers for Jenkins Images auto-release when upstream images are updated</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Duplicate of https://github.com/jenkinsci/docker/issues/576
