### ISSUE TITLE
[INFRA-1971] Setup org account on Chocolatey.org

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1625]
<p>The Platform SIG is working on getting an official Chocolatey package setup. This will require the ability to push nupkg files to the Chocolatey public feed, which requires an API Key. This is created when a user account is created. I would like a user account created on chocolatey.org for the official Jenkins packages. This API key would need to be available on trusted or wherever the Windows packages are going to be built. Once the user account is created, we can work on getting the current jenkins package moved over under the jenkins org account for maintenance.</p>

---
<details><summary><i>Originally reported by <a title="Alex Earl" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1971" target="_blank">Setup org account on Chocolatey.org</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing this issue due to its age. Please feel free to reopen it if there is still action required from the infra team.
