### ISSUE TITLE
[INFRA-2045] Delete jenkinsinfra01 RDS

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1692]
<p>It appears that we have an unused RDS database</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2045" target="_blank">Delete jenkinsinfra01 RDS</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
We still have "jenkinsinfra01" & "jenkinsinfra01-rr1" in AWS us-east-1, what are they for and should they be kept or deleted?

**Comment by dduportal** [comment]
The 2 AWS RDS databases `jenkinsinfra01` and `jenkinsinfra01-rr1` are used for the service rating.jenkins.io.

I'm closing this issue in favor of #1627: once rating is migrated to AKS, then we can delete these 2 RDS databases.
