### ISSUE TITLE
[INFRA-2049] yum repository is not GPG signed

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1695]
<p>jenkins | 2.9 kB 00:00:00<br/>
<a href="https://pkg.jenkins.io/redhat/repodata/repomd.xml.asc:" class="external-link" target="_blank" rel="nofollow noopener">https://pkg.jenkins.io/redhat/repodata/repomd.xml.asc:</a> <span class="error">&#91;Errno 14&#93;</span> HTTPS Error 404 - Not Found</p>

<p>see: <a href="https://access.redhat.com/solutions/2850911" class="external-link" target="_blank" rel="nofollow noopener">https://access.redhat.com/solutions/2850911</a></p>
<blockquote>
<h2><a name="RootCause"></a>Root Cause</h2>
<ul>
	<li>Yum was trying to download <tt>repomd.xml.asc</tt> as <tt>repo_gpgcheck</tt> was set to <tt>1</tt>.</li>
	<li>As yum was unable to locate <tt>repomd.xml.asc</tt> on the server due to GPG armor disabled, it was failing with <tt><span class="error">&#91;Errno 14&#93;</span> HTTPS Error 404 - Not Found</tt> error message.</li>
</ul>

<ul>
	<li>With RHEL 7.4, the stig-rhel7-disa profile will add "repo_gpgcheck=1" to /etc/yum.conf</li>
</ul>
</blockquote>
<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Jason Pyeron" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jpyeron">jpyeron</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2049" target="_blank">yum repository is not GPG signed</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as outdated.
