### ISSUE TITLE
[INFRA-2090] Monitor Azure Functions 

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1732]
<p>It's not clear how to do this right now but we should find a way to monitor our Azure functions </p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2090" target="_blank">Monitor Azure Functions </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
no longer using azure functions
