### ISSUE TITLE
[INFRA-2092] Puppet Enterprise - You have exceeded your license by X

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1734]
<p>It seems like we have too many nodes on the puppet master</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2092" target="_blank">Puppet Enterprise - You have exceeded your license by X</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Doesn't seem relevant any more.
