### ISSUE TITLE
[INFRA-2099] cert.ci master needs more RAM

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1741]
<p>I just oom-killed cert.ci's Jenkins master twice by checking for plugin updates.</p>

<p>Per <a href="https://github.com/jenkins-infra/jenkins-infra/blob/04e618e6cb95320ff1d2147981c0db7201a539d1/dist/profile/manifests/buildmaster.pp#L31" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/jenkins-infra/blob/04e618e6cb95320ff1d2147981c0db7201a539d1/dist/profile/manifests/buildmaster.pp#L31</a> it uses 8GB of Xmx, which means the machine should have 12-16 GB RAM at least. I would be surprised if that is the case.</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2099" target="_blank">cert.ci master needs more RAM</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Fixed afaik
