### ISSUE TITLE
[INFRA-2196] Enable GitHub comment based PR build/rebuild on ci.j.io

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1834]
<p>Many times when there is an intermittent issue with a build, someone needs to close and reopen a PR to get a new build. It would be nice if comment based PR rebuild could be enabled to bypass this requirement. There is at least one plugin that allows this.</p>

---
<details><summary><i>Originally reported by <a title="Alex Earl" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2196" target="_blank">Enable GitHub comment based PR build/rebuild on ci.j.io</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
GitHub checks does this
