### ISSUE TITLE
[INFRA-2231] runPCT() - support ACI inaddition to Docker images

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1865]
<p>Currently runPCT() from Pipeline Library runs in Docker images, but it is a precious resource ATM. We could improve the plugin compatibility testing throughput by using ACI.</p>

<p>Acceptance criteria:</p>
<ul>
	<li>Add a PCT image as one of the ACI configurations on ci.jenkins.io (with a new label). jenkins/pct latest image can be used for this purpose</li>
	<li>Update the Pipeline step to use the provisioned image instead of using Docker</li>
</ul>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2231" target="_blank">runPCT() - support ACI inaddition to Docker images</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Bom is generally used for this now
