### ISSUE TITLE
[INFRA-2232] Pipeline Library: add a "validateDependabotConfig()" step

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1866]
<p>Many components use Dependabot, and configuration mistakes become a common case, e.g. <a href="https://github.com/jenkinsci/configuration-as-code-plugin/pull/1020" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/configuration-as-code-plugin/pull/1020</a> by me. It would be great to have a library step for validation of DependaBot configs.</p>

<p> </p>

<p>It might make sense to make it a part of buildPlugin() pre-flight checks</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2232" target="_blank">Pipeline Library: add a "validateDependabotConfig()" step</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
dependabot v2 is validated by github
