### ISSUE TITLE
[INFRA-2233] Pipeline Library: add a "validateReleaseDrafterConfig()" step

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1867]
<p>Many components use Release Drafter, and configuration mistakes become a common case, e.g. <a href="https://github.com/jenkinsci/.github/pull/16" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/.github/pull/16</a> by me. It would be great to have a library step for validation of Release Drafter configs.</p>

<p>It might make sense to make it a part of buildPlugin() pre-flight checks later</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2233" target="_blank">Pipeline Library: add a "validateReleaseDrafterConfig()" step</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
everyone just uses the central one which has test coverage so I don't think it's worth it
