### ISSUE TITLE
[INFRA-2271] Crowd Integration library license

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1896]
<p>As I was working on <a href="https://issues.jenkins.io/browse/JENKINS-59301" title="Crowd 2 plugin not compatible with JDK11" class="issue-link" data-issue-key="JENKINS-59301">JENKINS-59301</a> to resolve a Java 11 related issue, I am stuck into the Crowd Integration library used by the crowd2 plugin.</p>

<p>Because I have no access to the source code of the library, I looked into its license: <a href="https://www.atlassian.com/legal/software-license-agreement" class="external-link" target="_blank" rel="nofollow noopener">https://www.atlassian.com/legal/software-license-agreement</a>. I have no background in legal / contracts / licenses so I want to understand it. </p>

<p>From what I read and my comprehension (not a English native speaker), the license is not open-source. And sadly, <a href="https://tldrlegal.com/license/atlassian-customer-agreement" class="external-link" target="_blank" rel="nofollow noopener">TLDRlegal.com</a> as no details either on it.</p>

<p>I understand that we have been using this for a long time, I might be over-thinking this, but I want to be sure. </p>

---
<details><summary><i>Originally reported by <a title="Adrien Lecharpentier" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=alecharp">alecharp</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2271" target="_blank">Crowd Integration library license</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
@DuMaM maybe you have more info on this?

**Comment by timja** [comment]
cc @daniel-beck

**Comment by KalleOlaviNiemitalo** [comment]
According to <https://issues.jenkins.io/browse/JENKINS-59301?focusedCommentId=376742&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-376742>, Atlassian provides a Crowd client library <https://bitbucket.org/atlassian/crowd-rest-client> under the Apache 2.0 license. If crowd2-plugin is ported to that, then I think it can be built with less license risk.

Can it be tested against embedded Crowd at <https://issues.jenkins.io/>? Maybe that wouldn't be secure enough.

**Comment by DuMaM** [comment]
@KalleOlaviNiemitalo There is already this rest client used in crowd plugin.
https://developer.atlassian.com/server/crowd/creating-a-crowd-client-using-crowd-integration-libraries/
https://github.com/jenkinsci/crowd2-plugin/blob/master/pom.xml#L102
I think it's integration-rest-client lib is better option then just plain rest-client.

Currently it's using v2.8.8 one and as far as I can tell it's 1v1 reflects server version releases.
I need to follow up with changes if upgrading to 3.7.1 for example do not introduce a breaking changes for users.

**Comment by KalleOlaviNiemitalo** [comment]
<https://bitbucket.org/atlassian/crowd-rest-client/src/master/pom.xml> says

```xml
<groupId>com.atlassian.crowd.client</groupId>
<artifactId>atlassian-crowd-rest-client</artifactId>
```

while <https://github.com/jenkinsci/crowd2-plugin/blob/master/pom.xml> has

```xml
        <dependency>
            <groupId>com.atlassian.crowd</groupId>
            <artifactId>crowd-integration-client-rest</artifactId>
```

Seems like a different library to me.

**Comment by DuMaM** [comment]
They are, but It's not what I meant.
According to Atlassian docs I also included, we should use  `crowd-integration-client-rest` not a `atlassian-crowd-rest-client`.

**Comment by DuMaM** [comment]
Ok I think i solved License problems.
https://developer.atlassian.com/platform/marketplace/timebomb-licenses-for-testing-server-apps/

**Comment by lemeurherve** [comment]
I'm not a bot but I can close this issue :)
