### ISSUE TITLE
[INFRA-174] Add a command to link JIRA issues with commits

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#191]
<p>This functionality would be useful to reference commits in JIRA if a committer forgets to reference a JIRA issue in the commit body.</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-174" target="_blank">Add a command to link JIRA issues with commits</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closed as we're using Github to host our issues now.
