### ISSUE TITLE
[INFRA-2318] Enable datadog processes monitoring

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1939]
<p>By default the datadog agent do not monitor processes and it would be a nice to have to enable this by default on every datadog agent </p>

<p><a href="https://docs.datadoghq.com/graphing/infrastructure/process/" class="external-link" target="_blank" rel="nofollow noopener">Doc</a></p>

<p>The configuration need to be defined on our puppet repository <a href="https://github.com/jenkins-infra/jenkins-infra/" class="external-link" target="_blank" rel="nofollow noopener">link</a> as we use the datadog puppet module from the puppet <a href="https://forge.puppet.com/datadog/datadog_agent" class="external-link" target="_blank" rel="nofollow noopener">forge</a></p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2318" target="_blank">Enable datadog processes monitoring</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing in favor of https://github.com/jenkins-infra/helpdesk/issues/2843
