### ISSUE TITLE
[INFRA-2375] update maven on build infra

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#1994]
<p>the version of maven in use on CI does not support wildcard exclusions on dependencies.</p>

<p> </p>

<p>This is a PITA and leads to things like <a href="https://github.com/jenkinsci/m2release-plugin/pull/35/commits/77fa752a52d1c227c4cf730b6e3ba6e8b4eb99a6" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/m2release-plugin/pull/35/commits/77fa752a52d1c227c4cf730b6e3ba6e8b4eb99a6</a></p>

<p> </p>

<p>Also some upcoming work for the plugin-pom may (or may not) want to use some recent maven improvements.</p>

---
<details><summary><i>Originally reported by <a title="James Nord" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=teilo">teilo</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2375" target="_blank">update maven on build infra</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
@jtnord do you happen to know if this issue is still a problem or if it can be closed?

**Comment by dduportal** [comment]
We can definitively close this (rotting) issue : the problems predates us (Maven 3.5.x line), while we are running 3.9.x nowadays ;)
