### ISSUE TITLE
Docker images are building on tags

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2]
### Service

trusted.ci.jenkins.io

### Summary

Old tags are currently getting triggered by organisation scans on for the Agents folder on trusted.ci.jenkins.io

@dduportal mentioned that this can be disabled.

We currently have the latest tag updated sometimes with an old image (we should probably add another change in the scripts to prevent that, but we shouldn't really be rebuilding old tags)

### Reproduction steps

1. Scan organisation for the Containers/Agents folder on trusted.ci.jenkins.io
2. Old tags trigger

**Comment by dduportal** [comment]
I'm not sure if someone did the configuration during the past 10 days.
BUT
the build strategy plugin is currently configured to NOT build tags older than 7 days, on the "Container -> Agent" Organization Scanning"

<img width="1508" alt="Capture d’écran 2022-01-14 à 19 39 51" src="https://user-images.githubusercontent.com/1522731/149568140-770ecac3-a147-43e7-b521-057bfc8e280f.png">

Just triggered a scan and did not see any old tag triggered.

**Comment by timja** [comment]
See:

https://github.com/jenkinsci/docker-agent/issues/229
https://trusted.ci.jenkins.io:1443/job/Containers/job/docker/job/docker-agent/view/tags/job/4.10-4/50/

Looks like it's the pipeline-library changes causing it

**Comment by timja** [comment]
and config update for the code: https://github.com/jenkins-infra/jenkins-infra/pull/2047

**Comment by dduportal** [comment]
Related: moving the global shared library setup for ci.jenkins.io and trusted.ci.jenkins.io from groovy script to JCasc: https://github.com/jenkins-infra/jenkins-infra/pull/2049#pullrequestreview-857047284

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/helpdesk/issues/2751

**Comment by dduportal** [comment]
Applied to trusted.ci. No more rebuild (unless there is something).

**Comment by timja** [comment]
see https://github.com/jenkinsci/docker-inbound-agent/issues/260

**Comment by dduportal** [comment]
Thanks @timja . We need help to solve this problem: we checked with @MarkEWaite and @lemeurherve on trusted.ci and we weren't able to understand why these tags were rebuilt despite the build policy + the jobs settings.

We tried differents traits, but the behvior was clearly different that what we see on infra.ci.

*thinking out loud*
Now that release.ci as the "Agent VM Linux/Windows" capability, do you think that it could be worth it to move the docker build/publish out of trusted into release ?

**Comment by timja** [comment]
yes it would be better to move it to release.ci so that we can trigger it after build and packaging complete

**Comment by timja** [comment]
Scanned docker agent multi branch pipeline today.

All these builds kicked off:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/21194782/157961131-f8fec372-2a8c-48ff-b185-4cf28b5c1dbb.png">
