### ISSUE TITLE
[INFRA-2399] Replace most Apache redirects with "redirect" layout pages on jenkins.io

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2016]
<p><a href="https://github.com/jenkins-infra/jenkins-infra/blob/58cdbe08f9871e543b22eccc1046da52a6469043/dist/profile/templates/kubernetes/resources/jenkinsio/configmap.yaml.erb#L59-L91" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/jenkins-infra/blob/58cdbe08f9871e543b22eccc1046da52a6469043/dist/profile/templates/kubernetes/resources/jenkinsio/configmap.yaml.erb#L59-L91</a></p>

<p><a href="https://github.com/jenkins-infra/jenkins-infra/blob/56f51f061efc02f33d123d92a4ac64bbd509e52b/dist/profile/manifests/catchall.pp#L70-L103" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/jenkins-infra/blob/56f51f061efc02f33d123d92a4ac64bbd509e52b/dist/profile/manifests/catchall.pp#L70-L103</a></p>

<p>Most of this is wrong or obsolete, and should be made regular pages on jenkins.io (like those in the <tt>/redirect</tt> folder).</p>

<p>E.g. <tt>/donate</tt> forwards to the wiki, which tells you to go to <tt>/donate/</tt> (facepalm here).</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2399" target="_blank">Replace most Apache redirects with "redirect" layout pages on jenkins.io</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>
<li><b>status</b>: In Progress
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as not valid anymore: the Kubernetes configuration moved 2 years ago to jenkins-infra/kubernetes-management
