### ISSUE TITLE
[INFRA-2401] Optimize ci.jenkins.io workload

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2018]
<p>Nowadays it is really hard to maintain Jenkins plugins and the core due to the non-stop instabilities on <a href="http://ci.jenkins.io/" class="external-link" target="_blank" rel="nofollow noopener">ci.jenkins.io</a>. It slows down contributions from being delivered quickly and impacts contributors and plugin maintainers. Some plugins switch to Travis/GitHub Actions/GitLlab CI just to stabilize their projects, and it is a really bad contributor experience and optics for the project. Root cause: numerous capacity and infrastructure issues which could be addressed by improving Jenkins Pipeline, libraries, documentation and the infrastructure.</p>

<p>There is a number of low-hanging fruit which could optimize the resource usage. By resolving them we can improve the contributor experience and reduce <a href="http://ci.jenkins.io/" class="external-link" target="_blank" rel="nofollow noopener">ci.jenkins.io</a> overheads at the same time. Goal of this EPIC is to aggregate such improvements and to get them delivered</p>

<p> </p>

<p>Documentation improvements are tracked separately in <a href="https://issues.jenkins.io/browse/INFRA-1205" title="Infra Documentation and Contributor Experience Update - 2019Q4" class="issue-link" data-issue-key="INFRA-1205"><del>INFRA-1205</del></a></p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2401" target="_blank">Optimize ci.jenkins.io workload</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
old EPIC: closing
