### ISSUE TITLE
[INFRA-2402] Optimize ci.jenkins.io workload: stop building useless PRs (doc updates and other stuff not covered by tests)

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2019]
<p>It would be great to add some content filters to ignore/fast-pass PRs which do not include testable changes (docs and co). It will likely require patches in Git plugin and in GitHub branch source</p>

<p>Idea: “.jenkinsignore” file in the repository OR conditional branches in Pipeline before any node is provisioned (no workspace checkout). We also need to avoid overusing REST API for that</p>

<p>It might be also possible to ignore some patterns by default (e.g. if a change focuses Markdown files only)</p>

<p>Atlassian open sourced the Clover in 2017.  It includes a "Test Optimization" facility which is claimed to select tests that execute affected code.  Idea is to:</p>

<ul>
	<li>Integrate clover reporting into a small plugin</li>
	<li>Explore the test optimization feature locally and on ci.jenkins.io</li>
	<li>Integrate clover reporting into a more widely used plugin</li>
	<li>Explore test optimization feature locally and on ci.jenkins.io</li>
	<li>Integrate clover reporting into Jenkins core</li>
	<li>Explore test optimization feature locally and on ci.jenkins.io</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2402" target="_blank">Optimize ci.jenkins.io workload: stop building useless PRs (doc updates and other stuff not covered by tests)</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Clsoing for the same reasons as https://github.com/jenkins-infra/helpdesk/issues/2020
