### ISSUE TITLE
[INFRA-2404] Add support of disabling stale builds

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2020]
<p>It would be great to add filters to prevent builds of stalled pull requests and branches on organization rescans. Filters could just ignore PRs by particular labels</p>

<p>Why? It hammers Jenkins builds every week. It likely requires patches in GitHub Branch Source or SCM API</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2404" target="_blank">Add support of disabling stale builds</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as:
- ci.jenkins.io is now able to handle this waves pretty fine
- The aformentionned plugins already provides everything to solve this issue today.
