### ISSUE TITLE
[INFRA-2405] Implement the ci.jenkins.io availability monitoring

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2021]
<p>Currently the monitoring is really limited. One can see the status on <a href="https://p.datadoghq.com/sb/0Igb9a-dca9738dbb5048025c005182a8f240c0" class="external-link" target="_blank" rel="nofollow noopener">https://p.datadoghq.com/sb/0Igb9a-dca9738dbb5048025c005182a8f240c0</a> , but there is no more info.</p>

<p>Acceptance criteria:</p>
<ul>
	<li>There is a new Datadog page with ci.jenkins.io status summary</li>
	<li>There is a number of metrics exposed on this page
	<ul>
		<li>General availability</li>
		<li>Queue size, including blocked jobs</li>
		<li>... // Full list of metrics TBD</li>
	</ul>
	</li>
	<li>The status is referenced</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2405" target="_blank">Implement the ci.jenkins.io availability monitoring</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing in favor of #2769
