### ISSUE TITLE
[INFRA-2428] Deprecated Evergreen Infrastructure

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2040]
<p>It was officially decided during the <a href="https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#" class="external-link" target="_blank" rel="nofollow noopener">governance meeting</a> to stop the evergreen experiment</p>

<p>&#8212;<br/>
18:49 <@rtyler> shutting down evergreen servers doesn't do anything but return their Jenkins <br/>
environments to what they otherwise are, stagnate and un-updating <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/tongue.png" height="16" width="16" align="absmiddle" alt="" border="0"/><br/>
18:49 <@Slide-O-Mix> I'm in favor of shutting it down<br/>
&#8212;</p>

<p>In order to do so: </p>
<ul>
	<li>Delete evergreen azure resources (<a href="https://github.com/jenkins-infra/azure/blob/master/plans/evergreen.tf" class="external-link" target="_blank" rel="nofollow noopener">link</a>)</li>
	<li>Delete dns record defined on <a href="https://github.com/jenkins-infra/azure/blob/master/plans/evergreen.tf" class="external-link" target="_blank" rel="nofollow noopener">jenkins-infra/azure</a></li>
</ul>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2428" target="_blank">Deprecated Evergreen Infrastructure</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
No trace of evergreen resources remaining, closing.

**Comment by dduportal** [comment]
There are some resources in Azure with evergreen name:
- A postgreSQL "classic" instance named `prod-evergreen-db`
- A resource group named `prod-evergreen`

Sounds like that https://github.com/jenkins-infra/azure/commit/a274a6911eb88dd622084eb434290e567f19e024 only removed the terraform config but did not destroy the resources in Azure.

**Comment by dduportal** [comment]
Resources deleted in Azure. \o/
