### ISSUE TITLE
[INFRA-2445] Announce the JAM Organizers Workspace deprecation, get it shut down

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2057]
<p>There is a Slack workspace for JAM organizers. We need to shut it down and to redirect members to the Advocacy&Outreach and CDF resources</p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2445" target="_blank">Announce the JAM Organizers Workspace deprecation, get it shut down</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as not in the infra scope
