### ISSUE TITLE
[INFRA-2448] trusted.ci self-signed cert is for different host name

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2059]
<p>It would be useful if the self-signed cert for trusted.ci were for the actual trusted.ci.jenkins.io host name, even if self-signed.</p>

<p>That would allow us to run <tt>curl --cacert</tt> with a local copy of the cert, without having to actually access the <tt>ec2.internal</tt> host name, and tie ourselves to that infra detail.</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2448" target="_blank">trusted.ci self-signed cert is for different host name</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Fixed by https://github.com/jenkins-infra/helpdesk/issues/3091
