### ISSUE TITLE
[INFRA-2460] Remove deprecated Wiki page, specifically Debugging Jenkins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2066]
<p>When you search for_ jenkins debug_ you land on <a href="https://wiki.jenkins.io/display/JENKINS/Building+Jenkins#BuildingJenkins-DebuggingJenkins" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins.io/display/JENKINS/Building+Jenkins#BuildingJenkins-DebuggingJenkins</a> which has* outdated information*. Specifically when talking about how to debug Jenkins core.<br/>
If you use mvn jenkins-dev:run you get:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@41aa667c{Jenkins v${project.version},/,file:<span class="code-comment">///.../jenkins/war/src/main/webapp/,UNAVAILABLE}{file:///.../jenkins/war/src/main/webapp/}
</span>java.lang.IllegalStateException: No LoginService <span class="code-keyword">for</span> org.eclipse.jetty.security.authentication.FormAuthenticator@15b62d1e in ConstraintSecurityHandler@622975d2{STARTING}
</pre>
</div></div>

<p>Whoever able to modify the wiki, please update the page with accurate information or just remove it. </p>

<p>In addition, the[ developer documentation|https://jenkins.io/doc/developer/] doesn't point you out to the page where the information is updated: </p>

<p><a href="https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md</a></p>

<p>I will file a PR on jenkins.io to point out to the previous link, but the outdated wiki pages need to be removed or updated to avoid people got mixed up.</p>

<p>Note: not sure if this ticket goes here or any other project.</p>

---
<details><summary><i>Originally reported by <a title="Ramon Leon" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mramonleon">mramonleon</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2460" target="_blank">Remove deprecated Wiki page, specifically Debugging Jenkins</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as unrelated and because https://www.jenkins.io/doc/developer/building/ exists
