### ISSUE TITLE
[INFRA-2486] Archive old analysis plugins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2088]
<p>Please archive the following deprecated plugin repositories:</p>

<ul class="alternate" type="square">
	<li><a href="https://github.com/jenkinsci/dry-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/dry-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/findbugs-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/findbugs-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/analysis-core-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/analysis-core-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/analysis-collector-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/analysis-collector-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/warnings-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/warnings-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/tasks-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/tasks-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/checkstyle-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/checkstyle-plugin</a></li>
</ul>

<p>See discussion in <a href="https://github.com/jenkins-infra/update-center2/pull/345" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/update-center2/pull/345</a></p>

---
<details><summary><i>Originally reported by <a title="Ulli Hafner" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2486" target="_blank">Archive old analysis plugins</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by uhafner** [comment]
The analysis plugins are still not archived when I click on them. 

But no other plugin uses them anymore, if that is the question.

**Comment by lemeurherve** [comment]
Thanks, gently pinging someone from @jenkins-infra/jenkinsci-admins

**Comment by timja** [comment]
done
