### ISSUE TITLE
[INFRA-2487] Remove deprecated analysis plugins from update center

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2089]
<p>The old static analysis plugins should be removed from the update center:<br/>
<a href="https://github.com/jenkins-infra/update-center2/blob/master/src/main/resources/artifact-ignores.properties" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/update-center2/blob/master/src/main/resources/artifact-ignores.properties</a></p>

<ul class="alternate" type="square">
	<li><a href="https://github.com/jenkinsci/pmd-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/pmd-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/dry-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/dry-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/findbugs-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/findbugs-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/analysis-core-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/analysis-core-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/analysis-collector-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/analysis-collector-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/warnings-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/warnings-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/tasks-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/tasks-plugin</a></li>
	<li><a href="https://github.com/jenkinsci/checkstyle-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/checkstyle-plugin</a></li>
</ul>

<p>See discussion in <a href="https://github.com/jenkins-infra/update-center2/pull/345" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/update-center2/pull/345</a></p>

---
<details><summary><i>Originally reported by <a title="Ulli Hafner" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2487" target="_blank">Remove deprecated analysis plugins from update center</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Ulli Hafner" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=drulli">drulli</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Minor
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2021-02-11T14:38:16+01:00
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dhruv070601** [comment]
fingbugs come under which plugin ?

**Comment by MarkEWaite** [comment]
> fingbugs come under which plugin ?

What was "findbugs" is now "spotbugs" and is included in the [Warnings plugin](https://plugins.jenkins.io/warnings-ng/).
