### ISSUE TITLE
[INFRA-2488] Add CODEOWNER on jenkinsci/packaging

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2090]
<p>Currently, PR created on that repository doesn't trigger notifications and it's neither clear who we should notify.<br/>
I would be happy to be notified by default.</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2488" target="_blank">Add CODEOWNER on jenkinsci/packaging</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Done, closing.
