### ISSUE TITLE
[INFRA-2490] Grant admin access to olblak on Pagerduty

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2092]
<p>I would like to be able to manage user on the Pagerduty account</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2490" target="_blank">Grant admin access to olblak on Pagerduty</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
No feedback, closing it, feel free to reopen it @olblak
