### ISSUE TITLE
[INFRA-2513] Stop using the "slaves" label on the plugin site and in the update center

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2108]
<p>Placeholder for <a href="https://github.com/jenkins-infra/update-center2/pull/353" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkins-infra/update-center2/pull/353</a> by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=teilo" class="user-hover" rel="teilo">James Nord</a></p>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2513" target="_blank">Stop using the "slaves" label on the plugin site and in the update center</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as there is already a pull request opened for it. (PR which should be merged or closed BTW)
