### ISSUE TITLE
[INFRA-2519] IBM Infrastructure

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2114]
<p>IBM offered to sponsor ppc64 and s390x infrastructure in order to test, build, publish Jenkins for those architectures.</p>

<p><b>2020-03-11</b>: We currently have access to temporary machines.</p>

<p>The goal of this epic is to have nodes available from ci.jenkins.io with label ppc64 and s390x</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2519" target="_blank">IBM Infrastructure</a></i></summary>
<i><ul>
<li><b>status</b>: Reopened
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as done
