### ISSUE TITLE
[INFRA-2520] Automate ppc64 agent configuration

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2115]
<p>We need a reproducible way to configure ppc64 agents, Puppet is not anymore supported<br/>
So we probably have to write ansible scripts and publish them on a new repository</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2520" target="_blank">Automate ppc64 agent configuration</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as we don't have ppc64 agent anymore
