### ISSUE TITLE
[INFRA-2523] Add ppc64 jenkins agent to trusted.ci.jenkins.io 

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2118]
---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2523" target="_blank">Add ppc64 jenkins agent to trusted.ci.jenkins.io </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as we don't have ppc64 agent anymore
