### ISSUE TITLE
[INFRA-2524] Add s390x jenkins agent to trusted.ci.jenkins.io 

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2119]
---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2524" target="_blank">Add s390x jenkins agent to trusted.ci.jenkins.io </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as we only have 1 s390x agent AND we have not met the need to have a native s390x on trusted.

Containers are built using qemu, and acceptance test can happen on ci.jenkins.io.
