### ISSUE TITLE
[INFRA-2525] Migrate Jenkins agents to AWS

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2120]
<p>AWS offered credits to run Jenkins agents on the Jenkins Infra AWS account.</p>

<p>This implies favorizing:</p>
<ul>
	<li>Jenkins ec2 plugin over <a href="https://plugins.jenkins.io/azure-vm-agents/" class="external-link" target="_blank" rel="nofollow noopener">Azure VM Agents</a></li>
	<li><a href="https://github.com/jenkinsci/amazon-ecs-plugin" class="external-link" target="_blank" rel="nofollow noopener">ECS</a> over ACS</li>
</ul>

<p>Remark: In the current state we are still planning to use azure infrastructure for specifics workload.</p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2525" target="_blank">Migrate Jenkins agents to AWS</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Already done since years:

- EKS cluster
- EC2 agents

But please note: https://github.com/jenkins-infra/helpdesk/issues/3421
