### ISSUE TITLE
[INFRA-2529] Configure trusted.ci to provision ec2 instances

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2124]
<p>Configure trusted.ci to provision ec2 instances.</p>

<p>Those instances need to be running in oregon to be closed to trusted.ci</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2529" target="_blank">Configure trusted.ci to provision ec2 instances</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
No feedback, closing it. Feel free to reopen it.
