### ISSUE TITLE
[INFRA-2542] Change redirect message or offer a way to change it

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2136]
<p>Steps:</p>
<ol>
	<li>Visit <a href="https://ci.jenkins.io/" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/</a></li>
	<li>Click <a href="https://jenkins.io/redirect/search-box" class="external-link" target="_blank" rel="nofollow noopener"><span class="image-wrap" style=""><img src="https://ci.jenkins.io/static/e3177cd5/images/16x16/help.png" style="border: 0px solid black" /></span></a> at the top right</li>
	<li>See it temporarily say: "This content has moved to <a href="https://wiki.jenkins.io/display/JENKINS/Search+Box" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins.io/display/JENKINS/Search+Box</a>"</li>
</ol>

<p>For integrated help elements, Jenkins should not act like this is a bug that needs fixing, and therefore the message should be more like "Redirecting to ..."</p>

<p>"has moved" feels like the message one sends to someone because "your link is out of date and we've moved it elsewhere".</p>

<p>Possible solutions:</p>
<ol>
	<li>Just change the message for all urls</li>
	<li>Add a ?foo hint to change the message</li>
	<li>Add a /redirect2/ with a new message</li>
</ol>

<p> </p>

---
<details><summary><i>Originally reported by <a title="Josh Soref" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jsoref">jsoref</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2542" target="_blank">Change redirect message or offer a way to change it</a></i></summary>
<i><ul>
<li><b>status</b>: Reopened
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
No "?" button at the top right any more, closing.
