### ISSUE TITLE
[INFRA-2559] Stop downloading tools from the Internet

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2152]
<p>I see that a default <tt>buildPlugin()</tt> downloads</p>

<ul>
	<li><a href="https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.zip" class="external-link" target="_blank" rel="nofollow noopener">https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.zip</a></li>
	<li><a href="https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz</a></li>
</ul>

<p>We should never be downloading large tool binaries like this from the Internet. Best is to have relevant tools prepackaged in container images or VMs; failing that, host tools in either Artifactory or in Jenkins itself (<tt>userContent/</tt>).</p>

---
<details><summary><i>Originally reported by <a title="Jesse Glick" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2559" target="_blank">Stop downloading tools from the Internet</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
> have relevant tools prepackaged in container images or VMs

That the current state, closing this issue.
