### ISSUE TITLE
[INFRA-2579] Timeouts running Kubernetes plugin tests

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2170]
<p>Kubernetes plugin tests use the docker node and spawn a <a href="https://github.com/kubernetes-sigs/kind" class="external-link" target="_blank" rel="nofollow noopener">kind</a> cluster for each run. Tests have been failing randomly lately with timeouts so I wonder whether the specs of the docker nodes have changed.</p>

---
<details><summary><i>Originally reported by <a title="Vincent Latombe" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=vlatombe">vlatombe</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2579" target="_blank">Timeouts running Kubernetes plugin tests</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Outdated issue
