### ISSUE TITLE
[INFRA-2600] Ldap need to be able to reload letsencrypt certificate

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2184]
<p>We recently switched LDAP certificate to Letsencrypt as defined in this <a href="https://github.com/jenkins-infra/charts/pull/198" class="external-link" target="_blank" rel="nofollow noopener">PR</a></p>

<p>Work needs to be done <a href="https://github.com/jenkins-infra/ldap" class="external-link" target="_blank" rel="nofollow noopener">here</a></p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2600" target="_blank">Ldap need to be able to reload letsencrypt certificate</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Critical
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as it does not have any practical application with current setup.
