### ISSUE TITLE
Docker build with `img` failing on infra.ci with `SYNC_USERMAP_ACK: got 255: Invalid argument`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2190]
### Service

infra.ci.jenkins.io

### Summary

All the Docker builds on infra.ci, which are using `img` , are failing with an error `SYNC_USERMAP_ACK: got 255: Invalid argument`, as caught by @smerle33.

The complete error is 

```shell
nsenter: failed to execv: No such file or directory
nsenter: failed to sync with parent: SYNC_USERMAP_ACK: got 255: Invalid argument
nsenter: failed to use newuidmap: Invalid argument
```

### Reproduction steps

- https://infra.ci.jenkins.io/blue/organizations/jenkins/Docker%20Builds%2Fdocker-jenkins-weekly/detail/PR-360/8/pipeline
- https://infra.ci.jenkins.io/blue/organizations/jenkins/Docker%20Builds%2Fdocker-hashicorp-tools/detail/main/7/pipeline

**Comment by dduportal** [comment]
We already had this error in the early phases of using `img`:

- https://github.com/genuinetools/img/issues/144
- That's the reason why we were copying the binaries `newuidmap` and `newguidmap` https://github.com/jenkins-infra/docker-builder/blob/1.2.8/Dockerfile#L68-L70

**Comment by dduportal** [comment]
- The error is present with the image `jenkinsciinfra/builder:2.0.4`, but is absent with the image `jenkinsciinfra/builder:1.2.8`
- It appeared after a batch of PRs that changed the version of the image on the pipeline-library used to build Docker images:
  - https://github.com/jenkins-infra/pipeline-library/pull/277
  - https://github.com/jenkins-infra/pipeline-library/pull/278
  - https://github.com/jenkins-infra/pipeline-library/pull/281

**Comment by dduportal** [comment]
Found it: we changed the based image from Alpine to Debian in https://github.com/jenkins-infra/docker-builder/pull/34 , which breaks `img`.

**Comment by dduportal** [comment]
Panel of upcoming solutions:

- Short term: revert back the pipeline library to `2.0.2`: only affect docker builds (not the plugin-site)
- Medium term: either find a way to fix this issue under a debian base image or split images and go back to alpine for `img`
- Long term: either full switch to Docker CE with #13 or use Docker in Docker pods with `sysbox`

**Comment by timja** [comment]
this helpful at all? https://github.com/genuinetools/img/issues/348#issuecomment-982473254

**Comment by dduportal** [comment]
> this helpful at all? [genuinetools/img#348 (comment)](https://github.com/genuinetools/img/issues/348#issuecomment-982473254)

That is *extremly* helpful ! I missed this one, thanks a lot

**Comment by dduportal** [comment]
At first sight, it seems feasible:

```
kubectl -n jenkins-agents exec -ti docker-builds-docker-jenkins-weekly-pr-360-10-d83kz-773jv-rpsc1 -- cat /proc/sys/kernel/unprivileged_userns_clone 
1
```

(required for rootless https://github.com/moby/buildkit/blob/master/docs/rootless.md)

**Comment by timja** [comment]
or this? https://github.com/genuinetools/img/issues/340#issuecomment-845308067

**Comment by halkeye** [comment]
Or https://github.com/genuinetools/img/blob/master/Dockerfile.dev#L69

**Comment by dduportal** [comment]
TBH, moving to buildkit sounds the most appealing part, since `img` is slowly dying (it was released before the buildkit  stuff)

**Comment by dduportal** [comment]
But mobykit is also using `alpine`: https://github.com/moby/buildkit/blob/master/Dockerfile#L277 :'(

Sounds like @halkeye solution with building the correct binaries is the closest one

**Comment by dduportal** [comment]
Short term PR: https://github.com/jenkins-infra/pipeline-library/pull/282

**Comment by dduportal** [comment]
With the version `2.0.4`, the problem is that the binaries `newuidmap` and `newgidmap` come from the `img` alpine image, so they cannot work at all under a debian distribution:

```
$ ldd /usr/bin/newuidmap
        linux-vdso.so.1 (0x00007ffdc2b4c000)
        libc.musl-x86_64.so.1 => not found
```

Let's try to keep the original debian binaries.

**Comment by dduportal** [comment]
Since https://github.com/jenkins-infra/pipeline-library/pull/311, you can set the attribute `useContainer` to true in the argument map of `buildDockerAndPublishImage()` to build using a valid Docker engine.

Gotta update `parallelDockerUpdatecli()` to support this attribute and use Docker by default so we would be able to proceed with this.
