### ISSUE TITLE
[INFRA-2677] Update Github contributors for usemango-runner-plugin

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2253]
<p>Please give the following Github users access to usemango-runner-plugin repository, <a href="https://github.com/jenkinsci/usemango-runner-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/usemango-runner-plugin</a>:</p>

<ul class="alternate" type="square">
	<li>jumpalongjim</li>
	<li>techtrash</li>
	<li>SubodhBorkar<br/>
 <br/>
Could you also please remove access for user - ianbisset<br/>
 <br/>
Thank you</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Paramjit Singh" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=psiingh">psiingh</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2677" target="_blank">Update Github contributors for usemango-runner-plugin</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Old issue, no feedback, closing it.
