### ISSUE TITLE
[INFRA-2679] jenkin.s.io/exportword in search results

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2255]
<p>When searching for a plugin (in this case, "jenkins metadata plugin", with DuckDuckGo). One of the results is the `/exportword` paths. Maybe it's worth finding a way to prevent indexing of this path structure, as clicking on a search result titled this and being prompted to download a Microsoft Word `.doc` file is a bit jarring.</p>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/51914/51914_image-2020-07-15-09-34-38-366.png" style="border: 0px solid black" /></span></p>

---
<details><summary><i>Originally reported by <a title="Kenneth Younger" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kyounger">kyounger</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2679" target="_blank">jenkin.s.io/exportword in search results</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by MarkEWaite** [comment]
The static site https://wiki.jenkins.io no longer offers to download a word file.
