### ISSUE TITLE
[INFRA-2683] Remove default assignee from ec2 plugin

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2259]
<p>Please remove the current default assignee for tickets created to EC2 plugin. Fabrizio Manfredi is not active and it gives a false expectation to reporters.</p>

<p>FYI: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=raihaan" class="user-hover" rel="raihaan">Raihaan Shouhell</a></p>

<p>Thanks.</p>

---
<details><summary><i>Originally reported by <a title="Ramon Leon" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mramonleon">mramonleon</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2683" target="_blank">Remove default assignee from ec2 plugin</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as we're using Github issues for the project INFRA now.

**Comment by dduportal** [comment]
@lemeurherve

**Comment by lemeurherve** [comment]
Good catch, my bad

**Comment by dduportal** [comment]
Closing as an outdated issue
