### ISSUE TITLE
[INFRA-2688] "Admin" access to HOSTING project in Jira

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2264]
<p>I would like to implement some of the improvements in the hosting process that have been discussed on the mailing list, e.g., allowing developers to specify Github Issues or Jira component creation and allowing users to specify users for the repository-permissions-updater PR. I don't know if someone can be given admin on just one project in Jira, if not, we can drop this request.</p>

<p>This would be so that I can add new fields to the hosting project issue template and so forth.</p>

<p>cc <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck" class="user-hover" rel="danielbeck">Daniel Beck</a> (who I have worked with on some of these types of things in the past) for his input.</p>

<p>Also, cc <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev" class="user-hover" rel="oleg_nenashev">Oleg Nenashev</a> for input.</p>

---
<details><summary><i>Originally reported by <a title="Alex Earl" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=slide_o_mix">slide_o_mix</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2688" target="_blank">"Admin" access to HOSTING project in Jira</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as we're using Github issues for the project INFRA now.

**Comment by dduportal** [comment]
It's for another Jira project: keeping it open

**Comment by lemeurherve** [comment]
I though it didn't matter anymore since https://github.com/jenkins-infra/helpdesk/issues/8

**Comment by timja** [comment]
Herve is right
