### ISSUE TITLE
[INFRA-2706] Share admin permissions with Akram for maintaining kubernetes-operator

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2281]
<p><a href="https://github.com/jenkinsci/kubernetes-operator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/kubernetes-operator</a> </p>

<p>Add Akram as the admin for the above repo. </p>

<p>github username: @akram</p>

---
<details><summary><i>Originally reported by <a title="Vibhav Bobade" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=waveywaves">waveywaves</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2706" target="_blank">Share admin permissions with Akram for maintaining kubernetes-operator</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Forgotten issue, closing it, @akram feel free to open a new issue if needed.
