### ISSUE TITLE
[INFRA-2735] trusted.ci web server configuration broken

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2303]
<p>Trusted CI no longer sends useful redirects as it believes the server name to be <tt><span class="error">&#91;trusted.ci.jenkins.io:1443&#93;</span></tt>.</p>

<p><tt>Location</tt> headers therefore look like this:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>location: https://[trusted.ci.jenkins.io:1443]:1443/job/update_center/329473/</pre>
</div></div>
<p>This might be related to the Jetty update in 2.235.4, unsure.</p>

<p>The following diagnostic script:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>println Jenkins.instance.rootUrlFromRequest
println org.kohsuke.stapler.Stapler.currentRequest.getHeader('X-Forwarded-For')
println org.kohsuke.stapler.Stapler.currentRequest.getHeader('X-Forwarded-Host')
println org.kohsuke.stapler.Stapler.currentRequest.getHeader('X-Forwarded-Proto')
println org.kohsuke.stapler.Stapler.currentRequest.getHeader('X-Forwarded-Port')
println org.kohsuke.stapler.Stapler.currentRequest.serverPort
println org.kohsuke.stapler.Stapler.currentRequest.serverName </pre>
</div></div>
<p>produces this output:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>https://trusted.ci.jenkins.io:1443/
(redacted IP address)
trusted.ci.jenkins.io:1443
https
1443
1443
[trusted.ci.jenkins.io:1443] </pre>
</div></div>
<p><a href="https://docs.oracle.com/javaee/5/api/javax/servlet/ServletRequest.html#getServerName()" class="external-link" target="_blank" rel="nofollow noopener">https://docs.oracle.com/javaee/5/api/javax/servlet/ServletRequest.html#getServerName()</a> is defined to NOT include the port.</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2735" target="_blank">trusted.ci web server configuration broken</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as not relevant (unless I misundertand) anymore.
