### ISSUE TITLE
[INFRA-2754] Realign repo.jenkins-ci.org mission

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2322]
<p>More context can be found <a href="https://groups.google.com/g/jenkins-infra/c/4B_jykZ2wi0/m/wrcszWE0BQAJ" class="external-link" target="_blank" rel="nofollow noopener">here</a></p>

<p>Folks at Jfrog are investigating how to reduce repo.jenkins-ci.org costs.</p>

<p>They are still interested to sponsor us but want to be sure that the repository is only used for Jenkins stuff and not as a proxy cache for other purposes.</p>

---
<details><summary><i>Originally reported by <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2754" target="_blank">Realign repo.jenkins-ci.org mission</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>
<li><b>status</b>: In Progress
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Updating this issue after we had recent outages on JFrog (#2864 #2949 and eventually #2904).

Problem: we have beetween 20 to 30 % of requests on repo.jenkins-ci.org that are HTTP/404, which is causing bandwitdh and performance issues as per JFrog's message in https://groups.google.com/g/jenkins-infra/c/ZdyYIhlNJQY/m/QCdT5OZIAAAJ .

We might want to check #2385 as a first step. Ping @daniel-beck we need your help as we don't know how to identify (and if we can without the help of JFrog) these "rogue" requests.

**Comment by daniel-beck** [comment]
These are unrelated.

We proxy repo1, and #2385 is about artifacts proxied from there but not used for a Jenkins purpose. Some folks probably just point their Maven at our Artifactory and do some ML bullshit, for which artifacts often exceed 1GB.

404 is when they set up Maven to query us for artifacts and they don't exist in our repos, _or_ Maven repo1, typically internal private-source stuff. There's tons of log spam related to this, so we know the paths, but since access is anonymous, we don't know who does that, so we cannot tell them to knock it off. Since we do not have a reverse proxy, we also cannot patch the responses and serve them "please go away" responses.

**Comment by dduportal** [comment]
Knowledge sharing from #3101 :

- https://github.com/jenkins-infra/helpdesk/issues/3101#issuecomment-1220826616
- https://github.com/jenkins-infra/helpdesk/issues/3101#issuecomment-1229883900

**Comment by MarkEWaite** [comment]
We've filed a [public abuse report](https://www.abuseipdb.com/check/39.107.36.205) for the IP address 39.107.36.205 .  Attempts to stop that abuse through private channels have failed.  We'll continuing reporting that abuse to the public location until the abuse stops or we find ways to block the IP address.

**Comment by timja** [comment]
can we just block it at artifactory / get jfrog to block it?

**Comment by MarkEWaite** [comment]
JFrog is investigating and hopes to be able to block the IP address.  We'll certainly keep people informed as we learn more from them.

**Comment by MarkEWaite** [comment]
As far as I can tell, this issue is resolved.  The Jenkins artifact repository no longer caches Maven central.  The artifact caching proxy provides artifact caching for agents connected to ci.jenkins.io
