### ISSUE TITLE
[INFRA-2771] Disable password expiry in azure tenant

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2338]
<p>Today I was made to change my password which is an annoying an outdated practice, almost nothing I use these days makes me do that...</p>

<p><a href="https://www.sans.org/security-awareness-training/blog/time-password-expiration-die" class="external-link" target="_blank" rel="nofollow noopener">https://www.sans.org/security-awareness-training/blog/time-password-expiration-die</a></p>

---
<details><summary><i>Originally reported by <a title="Tim Jacomb" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=timja">timja</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2771" target="_blank">Disable password expiry in azure tenant</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
@timja should we keep this issue open?

**Comment by timja** [comment]
please

**Comment by dduportal** [comment]
Make sense since MFA is enforced to all users 👍

**Comment by dduportal** [comment]
Rotation policy disabled (as requested, and as recommended by Microsoft):

<img width="475" alt="Capture d’écran 2022-12-06 à 09 41 42" src="https://user-images.githubusercontent.com/1522731/205862700-aaf86f87-91e2-4441-afdd-f43824594b07.png">

All users are already MFA-enforced:

<img width="411" alt="Capture d’écran 2022-12-06 à 09 44 01" src="https://user-images.githubusercontent.com/1522731/205862898-b766a642-7b85-4d66-97fb-6636c1b5ac39.png">
