### ISSUE TITLE
[INFRA-2785] Change email in my jenkins-ci.org account

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2339]
<p>How do you change the email in your jenkins-ci account?</p>

<p>Got a new email address and my current will expire very soon.</p>

<p>On top of that, i have got 2 accounts due to this.</p>

<p><b>kengra</b> where I tried to get a new pwd but failed due to yet another old email </p>

<p> <b>kengra1</b> the one I'm using right now but will change</p>

<p>I just cant find any way to do it ....</p>

---
<details><summary><i>Originally reported by <a title="Kent Granström" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=kengra1">kengra1</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2785" target="_blank">Change email in my jenkins-ci.org account</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: In Progress
<li><b>priority</b>: Critical
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Old issue, feel free to reopen it if needed.
