### ISSUE TITLE
[INFRA-2792] Switch all org folders to App credentials

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2358]
<p><a href="https://ci.jenkins.io/job/Stapler/computation/console" class="external-link" target="_blank" rel="nofollow noopener">https://ci.jenkins.io/job/Stapler/computation/console</a> shows that this is still using a GH access token.</p>

---
<details><summary><i>Originally reported by <a title="Jesse Glick" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=jglick">jglick</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2792" target="_blank">Switch all org folders to App credentials</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as it was done successully in 2021: we only have githubapp credentials on ci.jenkins.io
