### ISSUE TITLE
[INFRA-2833] Is the example in "In-process Script Approval" document valid?

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2397]
<p><a href="https://www.jenkins.io/doc/book/managing/script-approval/" class="external-link" target="_blank" rel="nofollow noopener">In-process Script Approval doc</a> says</p>

<p>'''</p>

<p>Consider a script which accesses the method <tt>hudson.model.AbstractItem.getParent()</tt>, which by itself is harmless and will return an object containing either the folder or root item which contains the currently executing Pipeline or Job. Following that method invocation, executing <tt>hudson.model.ItemGroup.getItems()</tt>, which will list items in the folder or root item, requires the <tt>Job/Read</tt> permission.</p>

<p>'''</p>

<p><tt>getParent()</tt> is a method in <tt>AbstractItem</tt> class. The only way to get an <tt>Item</tt> object that I know is through <tt>Jenkins.instance.getItemByFullName()</tt> which is of course <a href="https://github.com/jenkinsci/script-security-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/scriptsecurity/sandbox/whitelists/blacklist#L88" class="external-link" target="_blank" rel="nofollow noopener">blacklisted</a>.</p>

<p>Isn't it invalid to say <tt>getItems()</tt> is dangerous to run when the access to it already requires an access to <tt>Jenkins.instance</tt>? It's as if we're being told not to play with the dangerous scissors that's inside a burning house.</p>

<p>Or is there a way to get an <tt>Item</tt> safely?</p>

---
<details><summary><i>Originally reported by <a title="Calvin Park" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=calvinpark">calvinpark</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2833" target="_blank">Is the example in "In-process Script Approval" document valid?</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as this issue should not have been in the INFRA issue tracker. Moved in JIRA to https://issues.jenkins.io/browse/JENKINS-67601.
