### ISSUE TITLE
[INFRA-2840] need Maintainer access for qmetry-for-jira-test-management-plugin and qmetry-test-management-plugin

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2403]
<p>Hi,</p>

<p>the current we need immediate assistance form your as we are not able to summit new versions for qmetry's Jenkins plugins due our currently maintainer is no longer part of our organisation.</p>

<p>current maintainer: dharaghodasara</p>

<p>new maintainer</p>

<p>Jenkins.io user: priankashah </p>

<p>GitHub user: priyankashah1224, QMetryDev</p>

<p>Jenkins GitHub Repo :</p>

<p><a href="https://github.com/jenkinsci/qmetry-for-jira-test-management-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/qmetry-for-jira-test-management-plugin</a></p>

<p><a href="https://github.com/jenkinsci/qmetry-test-management-plugin" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/qmetry-test-management-plugin</a></p>

<p> </p>

---
<details><summary><i>Originally reported by <a title="priyanka shah" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=priankashah">priankashah</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-2840" target="_blank">need Maintainer access for qmetry-for-jira-test-management-plugin and qmetry-test-management-plugin</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Closing as it's so old
