### ISSUE TITLE
[INFRA-3116] Use https on mirrors.jenkins.io

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#2556]
<p>Due to last LetsEncrypt CA news about certificates, please renew one for your past releases page <a href="https://mirrors.jenkins.io/war-stable/" class="external-link" target="_blank" rel="nofollow noopener">https://mirrors.jenkins.io/war-stable/</a><br/>
 Currently my browser shows, that page is ot secure</p>

<p><b>UPD:</b> seems wrong CN for mirrors.jenkins.io domain.</p>

---
<details><summary><i>Originally reported by <a title="John Travolta" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=sentinel">sentinel</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-3116" target="_blank">Use https on mirrors.jenkins.io</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by MarkEWaite** [comment]
We won't update the SSL certificate on mirrors.jenkins.io.  That service is obsolete.  The current mirror service is https://get.jenkins.io/
