### ISSUE TITLE
Create a "jira-admin" team in the jenkins-infra organization

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2724]
So we can use it to assign or mention it on https://github.com/jenkins-infra/helpdesk issues related to Jira, for example #2707

**Comment by lemeurherve** [comment]
Team created: https://github.com/orgs/jenkins-infra/teams/jira-admins

I've put @timja as maintainer of it.

**Comment by timja** [comment]
Added everyone
