### ISSUE TITLE
Create "jenkinsci-admins" & "jenkins-infra-admins" teams in the jenkins-infra organization

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2725]
- [x] Create public teams
- [x] Add jenkinsci-admins members
- [x] Add jenkins-infra-admins members

Similar to https://github.com/jenkins-infra/helpdesk/issues/2724

**Comment by lemeurherve** [comment]
Teams created, with (for now)
- @timja as maintainer of https://github.com/orgs/jenkins-infra/teams/jenkinsci-admins
- @dduportal & @lemeurherve in https://github.com/orgs/jenkins-infra/teams/jenkins-infra-admins/

**Comment by timja** [comment]
added everyone (except KK)

**Comment by lemeurherve** [comment]
Same for jenkins-infra-admins.
