### ISSUE TITLE
Create "helpdesk" github project to be able to set custom fields

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2726]
Ref: https://github.com/jenkins-infra/helpdesk/issues/2707#issuecomment-1009849975

**Comment by lemeurherve** [comment]
https://github.com/orgs/jenkins-infra/projects/5

**Comment by timja** [comment]
I can't see the project, can you make it public / tweak the settings?

**Comment by lemeurherve** [comment]
Wanted to refine it a little bit so it was private.
I've put it as public & "read-only" (for now), will revise its settings later.

**Comment by timja** [comment]
Looks cool nice 😄
