### ISSUE TITLE
Correctly reimport epic issues relations

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2728]
Each epic related issue should have corresponding epic-id label.

Ex: https://issues.jenkins.io/browse/INFRA-3135 (#2680)

Related: #9

**Comment by dduportal** [comment]
WiP in https://github.com/jenkins-infra/helpdesk/milestones?with_issues=no

**Comment by lemeurherve** [comment]
@dduportal should we close this issue as "won't do"?
Not sure it concerns a lot of issues still opened, we won't miss a lot I think.

**Comment by dduportal** [comment]
Make sense, thanks for checking/cleaning up!
