### ISSUE TITLE
[ci.jenkins.io] Data disk for JENKINS_HOME is almost full

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2736]
### Service

ci.jenkins.io

### Summary

Message on the ci.jenkins.io, once logged in, that tells us the following:

```
 Your Jenkins data directory /var/jenkins_home (AKA JENKINS_HOME) is almost full. You should act on it before it gets completely full. 
 ```

**Comment by dduportal** [comment]
Only 7 Gb left of the 295gb of the partition:

```
/dev/sdb1       295G  273G  7.2G  98% /var/lib/jenkins
```

Not blocking, but should be investigated.

**Comment by MarkEWaite** [comment]
Fixed by removing old builds from several of the jobs and by cleaning the GitHub cache that the GitHub branch source seems to still not be cleaning.

**Comment by lemeurherve** [comment]
@MarkEWaite thanks for the resolution!

Do you mind detailing what's you've done? I searched in the runbooks for the snippet you've given in IRC but didn't found anything related.
