### ISSUE TITLE
`Jenkinsfile` not being run for `jenkinsci/packaging`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2739]
### Service

ci.jenkins.io

### Summary

In jenkinsci/packaging#228 I have added a `Jenkinsfile` for `jenkinsci/packaging`. Since I have write access to this repository, I should be able to test the `Jenkinsfile` before it is merged. However, the `Jenkinsfile` is not being run in my PR, so I'm guessing a new job needs to be created on `ci.jenkins.io`.

### Steps to reproduce

- Obtain write access to `jenkinsci/packaging`.
- Create a PR that adds or modifies a `Jenkinsfile`.
- Go to the Checks tab in the GitHub PR.

### Expected results

The `Jenkinsfile` changes should be running in CI for testing purposes.

### Actual results

No CI build was performed.

**Comment by timja** [comment]
I've modified the config, running a scan atm

**Comment by timja** [comment]
https://ci.jenkins.io/job/Packaging/job/packaging/view/change-requests/

**Comment by basil** [comment]
Many thanks!
