### ISSUE TITLE
Aborted jobs affect developer productivity

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2741]
### Service

AWS

### Summary

The following builds of jenkinsci/bom#837 and jenkinsci/bom#838 were aborted:

- https://ci.jenkins.io/job/Tools/job/bom/job/PR-838/3/
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-837/5/

I did not request that these builds be aborted, nor did any tests fail. They appear to have been aborted because a spot instance was terminated, as I have not seen aborted builds like this prior to November 2021.

Prior to the introduction of spot instances, builds would not be aborted in this manner. After the introduction of spot instances, builds are aborted in this manner, but the builds do not restart automatically, nor do I have a manual method of restarting them. As a result these PRs are now stuck, which is a regression in developer productivity.

Please resolve the regression in developer productivity by removing the use of spot instances, restarting the aborted builds automatically after they are aborted, or providing me with a means of restarting the aborted builds manually.

### Reproduction steps

- Obtain write access to a Jenkins repository.
- Run a build.
- Get unlucky and observe that the spot instance running your build has been terminated.
- Observe that you are now stuck without a way to restart the aborted build in the GitHub UI, despite having write access to the repository.

**Comment by dduportal** [comment]
Hello @basil thanks for reporting.

We won't be able to disable the spot instances for now, as the cost would not be sustainable without it: we have to keep AWS costs unders 8k€ per month, and the workload on ci.jenkins.io as never been so high (without spot we are above 14k€ due to only the BOM + PCT workloads).

Ref. #2646 .

We are working on adding capacity on other clouds such as Digital Ocean but it takes a bit of time, we are sorry for this delay.

I remember that @jglick had an idea (but I don't know if it is feasible, either technically or in term of contributor availability) around being able to restart automatically jobs/stages when an agent was removed, that would have helped.

**Comment by dduportal** [comment]
> providing me with a means of restarting the aborted builds manually.

Fair and important point! Could you try if https://github.com/jenkins-infra/helpdesk/issues/2738#issuecomment-1013696217 solves this issue for you please?

**Comment by timja** [comment]
> > providing me with a means of restarting the aborted builds manually.
> 
> Fair and important point! Could you try if [#2738 (comment)](https://github.com/jenkins-infra/helpdesk/issues/2738#issuecomment-1013696217) solves this issue for you please?

GitHub doesn’t let you re-run aborted builds

**Comment by dduportal** [comment]
> 

Oh my bad, did not know. That is really annoying 😱

**Comment by basil** [comment]
[This build](https://ci.jenkins.io/job/Tools/job/bom/job/PR-853/2/) of jenkinsci/bom#853 failed with

```
[Pipeline] sh
Cannot contact jnlp-maven-11-5svkn: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
[…]
Agent was removed
Agent was removed
Failed in branch pct-pipeline-graph-analysis-2.319.x
[GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.
Finished: ABORTED
```

presumably as a result of a spot instance being terminated. As a result, the PR is now stuck in limbo: I neither have the option to re-run the build, nor can the PR be merged without a passing build.

**Comment by MarkEWaite** [comment]
> presumably as a result of a spot instance being terminated. As a result, the PR is now stuck in limbo: I neither have the option to re-run the build, nor can the PR be merged without a passing build.

I've restarted that build.  I know that is not a long term solution, but it works for the moment.

**Comment by dduportal** [comment]
For info, AWS did not report any spot instances reclaimed since the 30th of december. 

Weird, it means there is something else killing the agents. Could it be an OOM/overallocation in the pipeline process ?

**Comment by basil** [comment]
An agent was disconnected in [PR build 1](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6246/1/) of jenkinsci/jenkins#6246 and I have no way of restarting the failed build.

**Comment by lemeurherve** [comment]
I've restarted it.

**Comment by basil** [comment]
An agent was disconnected in [PR build 1](https://ci.jenkins.io/job/Tools/job/bom/job/PR-875/1/) of jenkinsci/bom#875 and I have no way of restarting the failed build.

**Comment by dduportal** [comment]
Yes, we are aware of this, but there is not anything we can do for now.

**Comment by jglick** [comment]
`github-checks` could be made to report failed rather than interrupted status pending https://github.com/github/feedback/discussions/10255.

**Comment by basil** [comment]
An agent was disconnected in [PR build 1](https://ci.jenkins.io/job/Tools/job/bom/job/PR-917/1/) of https://github.com/jenkinsci/bom/pull/917 and I have no way of restarting the failed build. Therefore, I cannot merge the PR (which is otherwise ready for merge).

An agent was disconnected in [PR build 1](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/1/), [PR build 4](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/4/), [PR build 5](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/5/), and [PR build 7](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/7/) of jenkinsci/jenkins#6315. As of PR build 7, I have no way of restarting the failed build. Therefore, I cannot merge the PR (which is otherwise ready for merge).

**Comment by timja** [comment]
Re-triggered all

**Comment by basil** [comment]
Over the past week, the rate of job failure due to agents being removed has increased noticeably. Examples:

- https://ci.jenkins.io/job/Tools/job/bom/job/master/775/
- https://ci.jenkins.io/job/Tools/job/bom/job/master/779/
- https://ci.jenkins.io/job/Tools/job/bom/job/master/785/
- https://ci.jenkins.io/job/Tools/job/bom/job/master/789/
- https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/1/
- https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/4/
- https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/5/
- https://ci.jenkins.io/job/Core/job/jenkins/job/PR-6315/7/

All of these failures occurred over the past four (4) days. The increase in aborted jobs, though concerning, would not be a major hindrance in and of itself, but combined with the inability to restart said jobs, it becomes more of a hindrance.

**Comment by lemeurherve** [comment]
Thank for the references @basil, I'll check if they ran on doks or eks as a first analysis.

**Comment by dduportal** [comment]
For information, the version [1.0.18](https://github.com/jenkinsci/github-checks-plugin/releases/tag/v1.0.18) of the plugin "Github Checks", with https://github.com/jenkinsci/github-checks-plugin/pull/250, has been deployed to ci.jenkins.io (thanks @jglick !).

@basil let us know if it improves the developer experience on your side.

**Comment by basil** [comment]
Many thanks for deploying jenkinsci/github-checks-plugin#250! I now have a means of restarting aborted builds manually, so the problem as defined in the issue description is resolved.
