### ISSUE TITLE
add user to repo jenkinsci / spotinst-plugin, team : spotinst-plugin Developers  github user : Zivmessing

### ISSUE THREAD

**Issue by adivos** [jenkins-infra/helpdesk#2743]
### GitHub repositories

please add user to repo jenkinsci / spotinst-plugin, 
team : spotinst-plugin Developers  
github user : Zivmessing

### GitHub users to have permission

Zivmessing

### Permission level

Admin

### Justification

Ziv is managing the the repo

**Comment by adivos** [comment]
please note i already asked this before and it was resolved, but the user was never added

(https://issues.jenkins.io/browse/INFRA-3089)

**Comment by timja** [comment]
Done
