### ISSUE TITLE
[release.ci.jenkins.io] Allow VM agent capability

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2746]
### Service

release.ci.jenkins.io

### Summary

The goal of this issue is to allow release.ci.jenkins.io to spawn VM agents.

- Infra.ci is now able to do it (allowing to build docker images for windows and arm, not only intel + execute docker safely) since #13 
- ci.jenkins.io is able to do it on 2 different clouds for resilience reason
- All the VMs are using the same template as for today (built on jenkins-infra/packager-images).

It would give developers on ci.jenkins.io more choices.

Ping @timja @basil for information (after the different exchanges around jenkinsci/packaging)

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/kubernetes-management/pull/1949 works as expected: configuration is ok, now releasE.ci show the agent templates and is able to communicate with the AWS API.

But while trying to spawn a VM instance with the dropdown on the page https://release.ci.jenkins.io/computer/, I saw that I forgot to specify 1 element to be configured:

<img width="704" alt="Capture d’écran 2022-01-24 à 18 58 52" src="https://user-images.githubusercontent.com/1522731/150838428-b4a9f98e-8f02-42e0-b864-fceaeb1fb739.png">

When spawning AWS EC2 VM agents, Jenkins needs a SSH private key to allow connecting to the remote VM.
I forgot to specify that we have to create a credential for this one as well.

@smerle33 I think you can totally propose another PR to add this 2nd credential in release.ci:

- I've added the private key into the secrets, under the key `EC2_AGENTS_PRIVKEY` (https://github.com/jenkins-infra/charts-secrets/commit/40eddb372449ba7da0625acc0fee434d33ad1a21)
- You have to add this 2nd in https://github.com/jenkins-infra/kubernetes-management/blob/main/config/ext_jenkins-release.yaml, like you did with the [`ec2-agents-credentials`](https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L179-L184). 
  - You can reuse the same definition for infra.ci at https://github.com/jenkins-infra/kubernetes-management/blob/main/config/ext_jenkins-infra.yaml#L193-L200

**Comment by dduportal** [comment]
Another changes that I forgot (sorry):
- [ ] update the security group to be used from current value to `ec2_agents_release` (as per https://github.com/jenkins-infra/aws/blob/main/ec2-agents.tf#L146) on the following 3 lines:
  - https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L271
  - https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L307
  - https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L343
- [ ] Change references to `infra.ci.jenkins.io` to `release.ci.jenkins.io`:
  - https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L280
  - https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L316
  - https://github.com/jenkins-infra/kubernetes-management/blob/bd720cfc9a3e86ca0a55ed5f8390ca3074efb769/config/ext_jenkins-release.yaml#L352

**Comment by smerle33** [comment]
I think that this should be closed as by [#1949](https://github.com/jenkins-infra/kubernetes-management/pull/1949)
