### ISSUE TITLE
Jenkins.io Pull Request CI build failing with weird error

### ISSUE THREAD

**Issue by jmMeessen** [jenkins-infra/helpdesk#2748]
### Service

ci.jenkins.io

### Summary

Since two days (Monday 17 Jan) two of my PRs on `jenkins.io` fail with a weird error:

`java.nio.file.AccessDeniedException: /var/jenkins_home/caches/git-76cae672244381b7de8a1c64125f0212/.git/refs/remotes/origin/automated-weekly-changelog/2.331.lock`.

They have already compiled correctly.

- PR-4824: https://github.com/jenkins-infra/jenkins.io/pull/4824
- PR-4820: https://github.com/jenkins-infra/jenkins.io/pull/4820

Failing builds: 

- https://ci.jenkins.io/blue/organizations/jenkins/Websites%2Fjenkins.io/detail/PR-4824/6/pipeline/
- https://ci.jenkins.io/blue/organizations/jenkins/Websites%2Fjenkins.io/detail/PR-4820/6/pipeline

A working build: 

https://ci.jenkins.io/blue/organizations/jenkins/Websites%2Fjenkins.io/detail/PR-4820/5/pipeline

**Comment by jmMeessen** [comment]
Submitted a new commit on PR 4820 this morning  and still have the same problem.

**Comment by timja** [comment]
they aren't really responding to the support ticket, very slowly and infrequently

**Comment by jmMeessen** [comment]
It looks unlocked. Based on the file locked name, it might be related to the bogged down release.

**Comment by MarkEWaite** [comment]
> It looks unlocked. Based on the file locked name, it might be related to the bogged down release.

It was locked because there were files and directories on the controller that were owned by the root user instead of being owned by the user running the controller process.  The file ownership has been fixed.

**Comment by jmMeessen** [comment]
Thanks for the explanation. It is more logical than my wild guess.

**Comment by dduportal** [comment]
Thanks @MarkEWaite !
