### ISSUE TITLE
Cannot find where to turn off email notifications for Jira HOSTING project

### ISSUE THREAD

**Issue by slide** [jenkins-infra/helpdesk#2749]
### Service

Jira

### Summary

I keep getting notified when there is conversations/new issues/etc on the HOSTING project in Jira. I know that it is moving to GitHub issues, but I would like to know how I can turn off these notifications. I have looked in lots of different places and can't find it.

**Comment by slide** [comment]
Username on Jira is slide_o_mix

**Comment by timja** [comment]
I assume it was you having the developer role for the project, I've removed it.

There's only 2 open issues and new ones are blocked so if that wouldn't work I wouldn't worry to much, email rule?

**Comment by slide** [comment]
Thanks! It was driving me crazy trying to figure out where to turn it off 😃
