### ISSUE TITLE
Change default issue assignee for Robot Framework Plugin

### ISSUE THREAD

**Issue by asimell** [jenkins-infra/helpdesk#2750]
### Service

Jira

### Summary

Janne Piironen (`jpiironen`) is the default assignee for Robot Framework plugin (`robot`), but he's no longer actively maintaining the plugin, although we should still keep him in the loop for now. Can you please the default assignee to me (`aleksisimell`)?

**Comment by lemeurherve** [comment]
The default assignee has been changed.
