### ISSUE TITLE
Enable caching of shared libraries on Jenkins controllers

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2751]
### Service

ci.jenkins.io

### Summary

As underlined by @timja in:

- https://github.com/jenkins-infra/jenkins-infra/pull/2049#discussion_r787945092
- https://github.com/jenkins-infra/jenkins-infra/pull/2047

we would want to enable the shared library caching feature on ci.jenkins.io, and also trusted.ci.jenkins.io.

Initial proposal is a 180min valid cache.

Some questions to answer before applying it:

- How to identify when/how decaching?
- Is there any consideration around ignoring some branches?

**Comment by timja** [comment]
There’s a button in the system configuration to clear it

**Comment by dduportal** [comment]
> There’s a button in the system configuration to clear it

<img width="650" alt="Capture d’écran 2022-01-20 à 09 41 05" src="https://user-images.githubusercontent.com/1522731/150303402-f03d290e-bebf-4612-8813-e0853ace6617.png">

Nice, did not know about this cahing feature, that's really useful
