### ISSUE TITLE
Releases of `jenkinsci/bom` fail with 401 Unauthorized

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2754]
### Service

Artifactory

### Summary

[This release of `jenkinsci/bom`](https://github.com/jenkinsci/bom/runs/4886891958) failed with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project bom-weekly: Failed to deploy artifacts: Could not transfer artifact io.jenkins.tools.bom:bom-weekly:pom:1117.v62a_f6a_01de98 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/io/jenkins/tools/bom/bom-weekly/1117.v62a_f6a_01de98/bom-weekly-1117.v62a_f6a_01de98.pom, status: 401 Unauthorized -> [Help 1]
```

I read [the documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#the-upload-to-the-maven-repository-fails-with-401-unauthorized):

> Unauthorized means that the credentials were invalid, or not sent by Maven. This normally means that the secrets configured in the repository have expired, create an issue in the INFRA project on Jira, and let the team know in #jenkins-infra on Libera Chat.

Per the documentation, I am creating an infrastructure ticket to update the expired credentials.

Note: I selected the "Artifactory" service, but I think a more accurate choice would be "GitHub". However, no "GitHub" service is available in the drop-down service selection box, so I picked the next-closest match. If I could have made a better service selection choice when reporting this ticket, please let me know.

### Reproduction steps

Obtain write access to `jenkinsci/bom`, then go to https://github.com/jenkinsci/bom/actions/workflows/cd.yaml and click the "Run workflow" button.

**Comment by timja** [comment]
Resolved in https://github.com/jenkins-infra/repository-permissions-updater/pull/2327

**Comment by basil** [comment]
Thank you!
