### ISSUE TITLE
PR stuck on "continuous-integration/jenkins/pr-merge" requirement

### ISSUE THREAD

**Issue by c0d3m0nky** [jenkins-infra/helpdesk#2756]
### Service

Github

### Summary

We've been trying to merge new features from our fork into the main repo since Tues 1/18 and it's passing all checks except "continuous-integration/jenkins/pr-merge". We can't tell from any of the build logs what would be causing this. Another team in the company that has their own plugin has run into this before but remember getting past it by just making a superfluous commit to make it do a new build and checks. We've tried that and many other alternatives to get it past the check with no luck.

Can anyone help see what's wrong or suggest other ways we can try to push this through?

Attempted:
* Closing PR and reopening to trigger new build
* Adding commit to trigger new build
* Close PR and create a new one
* Make PR from branch in jenkinsci repo rather than directly from our fork

Latest PR that is stuck
[PR-125](https://github.com/jenkinsci/fortify-on-demand-uploader-plugin/pull/125)

![image](https://user-images.githubusercontent.com/4998029/150456865-55a45d53-7358-4a1e-9d29-3c0e987182f6.png)

Thanks

### Reproduction steps

1. Make PR from v7.0.0 to master in jenkinsci/fortify-on-demand-uploader-plugin repo

**Comment by timja** [comment]
That status has not been used for quite awhile it’s now ‘Jenkins’ 

I’ve updated the branch protection for you
