### ISSUE TITLE
SSH build agents repository maintainer permissions

### ISSUE THREAD

**Issue by kuisathaverat** [jenkins-infra/helpdesk#2757]
### GitHub repositories

https://github.com/jenkinsci/ssh-slaves-plugin

### GitHub users to have permission

@kuisathaverat

### Permission level

Admin

### Justification

I have different permissions on the plugins I maintain, in the SAML plugin(https://github.com/jenkinsci/saml-plugin) I have admin permissions, in the SSH Build agents(https://github.com/jenkinsci/ssh-slaves-plugin) I have write permissions on the GitHub repository. I have noticed it when I tried to rename the `master` branch of SSH Build agents to `main`.

I have checked the files in the repository-permissions-updater and looks equal 

https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-ssh-slaves.yml

https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-saml.yml

**Comment by timja** [comment]
Done
