### ISSUE TITLE
Build and test with JDK 8u322, JDK 11.0.14, test with JDK 17.0.2

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2758]
### Service

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

Oracle released Java 8u321, Java 11.0.14, and Java 17.0.2 per the [Java release schedule](https://www.java.com/releases/) and the [Oracle January 2022 critical patch update](https://www.oracle.com/security-alerts/cpujan2022.html).  

Eclipse Adoptium has stated on their site that they are preparing the releases for various platforms for 8u322, 11.0.14, and 17.0.2.  Status reporting is available on their [issue tracker](https://github.com/adoptium/adoptium/issues/109).

Once Adoptium has completed their releases, we should update our infrastructure to use the most recent Java versions for Java 8, Java 11, and Java 17.  We prefer to not update until Eclipse Adoptium builds are available for our key platforms, amd64, arm64, and s390x.  We've accepted in the past that we might need to wait a little longer for ppc64le builds to be available.

### Reproduction steps

1. Java 8 version reports 8u311 currently.  Want it to report 8u321
2. Java 11 version reports 11.0.13 currently, Want it to report 11.0.14
3. Java 17 version reports 17.0.1 currently.  Want it to report 17.0.2

**Comment by losmurfs** [comment]
Why do you want 17.0.3? Per schedule, should be 17.0.2

**Comment by MarkEWaite** [comment]
> Why do you want 17.0.3? Per schedule, should be 17.0.2

Thanks for catching that mistake!  I've updated it to use the correct correct 17.0.2.

**Comment by dduportal** [comment]
For info, as soon as the adoptium version will be available, the PRs on https://github.com/jenkins-infra/packer-images and https://github.com/jenkins-infra/jenkins-infra will be opened automatically by the updatecli process (worst case 7 days after the release) to update these 3 JDKs.

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/packer-images/pull/168 => JDK 11 upgrade for packer image

**Comment by MarkEWaite** [comment]
I've submitted 

* jenkins-infra/jenkins-infra#2060 
* jenkins-infra/packer-images#177

to extend the updatecli definition for newer versions of JDK 17

**Comment by dduportal** [comment]
Closing as these version are now used everywhere.
