### ISSUE TITLE
Remove the ci.jenkins.io ban on a specific IP address

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2759]
### Service

ci.jenkins.io

### Summary

Remove the iptables change that I made to ci.jenkins.io

### Reproduction steps

1. See the change with `sudo iptables -L | grep static`
2. Remove that change
3. See the change is removed with `sudo iptables -L | grep static`

**Comment by dduportal** [comment]
Closing as:

- ci.jenkins.io is not under attack anymore
- The VM kernel upgrades (implying reboots) cleared up the iptables rules
