### ISSUE TITLE
s390x and ppc64le JDK 11.0.14 tool download not available

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2760]
### Service

ci.jenkins.io

### Summary

The tool downloader definition for JDK 11 on ci.jenkins.io refers to JDK 11.0.14 from Eclipse Temurin for IBM s390x and IBM ppc64le.  Those versions are not yet available.  The [Eclipse Temurin JDK 11.0.14 project status page](https://github.com/adoptium/adoptium/issues/109) shows that the work has been completed for amd64 Linux, amd64 Windows, and aarch64 Linux.  The work is in progress for other platforms like s390x and ppc64le.

### Reproduction steps

1. Open the ["Global Tool Configuration"](https://ci.jenkins.io/configureTools/) page from ["Manage Jenkins"](https://ci.jenkins.io/manage)
2. Press the "JDK" button to expand the list of installed JDK tools
3. Confirm that ppc64le and s390x refer to JDK 11.0.14 and that the warning message appears that the download is not available

**Comment by dduportal** [comment]
I thought that these 2 machines had a tool override to ensure that they don’t use the global configuration. Could you check with @lemeurherve the puppet config for ci.j ?

**Comment by dduportal** [comment]
Closing as it was fixed manually in february. Thanks Mark!
