### ISSUE TITLE
Change default assignee of `jobconfighistory-plugin` on Jira

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2762]
### Service

Jira

### Summary

[Stefan Brausch](https://issues.jenkins.io/secure/ViewProfile.jspa?name=stefanbrausch) was one of the former developer of jobconfighistory. I adopted the plugin in late 2021, see my [PR](https://github.com/jenkins-infra/repository-permissions-updater/pull/2250) at the RPU, but newly created issues are still assigned to them.
I would like to ask if it possible to change the default assignee to me (same Jira name like on GitHub), or leave it unassigned. 
Thanks in advance!

**Comment by timja** [comment]
Either is possible do you have a preference?

**Comment by NotMyFault** [comment]
> Either is possible do you have a preference?

Can leave it unassigned then.

**Comment by timja** [comment]
Done
