### ISSUE TITLE
jarsigner not found when building weekly releases

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2763]
### Service

release.ci.jenkins.io

### Summary

The 2.331 and 2.332 weekly releases were halted early when the final verification stage in the build job was unable to find the `jarsigner` command to check that the war file is correctly signed.

### Reproduction steps

1. Open a VPN connection to the Jenkins infra VPN
2. Open https://release.ci.jenkins.io and navigate to the Core release job for the master branch
3. Review the log where it reports `jarsigner not found`

@dduportal and I attempted a fix in 2.331 but the fix either was not applied or was not complete.  2.332 reported the same message.

**Comment by dduportal** [comment]
I forgot to merge https://github.com/jenkins-infra/release/pull/214 : the release of the 25th was still using the version 2.1.4 of the `docker-packaging` image, while the version 2.1.5 was expected.

**Comment by dduportal** [comment]
Should be fixed by https://github.com/jenkins-infra/release/pull/214 (merged). Let's see for the weekly of the 1st
