### ISSUE TITLE
Add AWS EC2 templates to trusted.ci

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2764]
We could add AWS EC2 templates to trusted.ci:

- More resilient (if Azure breaks or if we reach azure quotas)
- Would allow to have jdk8 an jdk17 builds.

_Originally posted by @dduportal in https://github.com/jenkins-infra/helpdesk/issues/2732#issuecomment-1023464973_

**Comment by lemeurherve** [comment]
trusted needs HA

**Comment by dduportal** [comment]
Closing as we won't do it", as per https://github.com/jenkins-infra/helpdesk/issues/3421 and https://github.com/jenkins-infra/helpdesk/issues/3486
