### ISSUE TITLE
Adding permission to @smerle33 to cancel pipeline when new built coming in

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#2765]
### Service

infra.ci.jenkins.io

### Summary

As I am launching multiple push on the same pull request, I miss the ability to cancel older pipeline that are running and wasting time and capability for nothing ...

**Comment by timja** [comment]
You could also change the pipelines to cancel old builds? 

https://github.com/jenkinsci/jenkins/blob/master/Jenkinsfile#L19

**Comment by smerle33** [comment]
> 

not confident enough to apply this to a whole pipeline, I am more on demand during the starting period I think (hope) ....

**Comment by dduportal** [comment]
We just added Stephane to the group `jenkins-admin`. That is solving this.
