### ISSUE TITLE
Unable to log into Artifactory

### ISSUE THREAD

**Issue by KyleBarton** [jenkins-infra/helpdesk#2770]
### Service

Artifactory

### Summary

Hello, apologies if this is a case of me misunderstanding the documentation.

I have created a username on https://accounts.jenkins.io/ -- kybarton_amazon. I have confirmed that I can log into jenkins.io after logging out. When I attempt to log into Artifactory at https://repo.jenkins-ci.org/ui/ with those same credentials, however, I receive an error message on login:

```
Login has failed. Due to Incorrect username/password or locked user.
```

The README on https://github.com/jenkins-infra/repository-permissions-updater, under `Requesting Permissions`, has the following:

```
Prerequisite: You need to have logged in once to [Artifactory](https://repo.jenkins-ci.org/) with your Jenkins community account (this is the same as the account you would use to login to Jira) before you can be added to a permissions target.
```

This seems to imply that my jenkins.io credentials should work on Artifactory. Am I missing a setup step here? Or is there an issue with jenkins.io <-> Artifactory connectivity? Thanks in advance.

### Reproduction steps

1. Go to https://accounts.jenkins.io/
2. Create an account
3. Write down your created username/password
4. Go to https://repo.jenkins-ci.org/ui/
5. Attempt to log in with the username/password from step 3

**Expected Behavior**
Successful Login

**Actual Behavior**
Failed login with message `Login has failed. Due to Incorrect username/password or locked user.`

**Comment by timja** [comment]
cc @daniel-beck / @Wadeck

**Comment by MarkEWaite** [comment]
I just confirmed that I am able to logout from https://repo.jenkins-ci.org and login again with my account `markewaite`.  I've confirmed that there are other accounts that use '_' in the username (like oleg_nenashev) and other accounts that are longer than `kybarton_amazon` (like balaji_digital_ai and urbancode_velocity.  Unfortunately, all those details tell me is that I don't know what might be causing `kybarton_amazon` to be unable to login to https://repo.jenkins-ci.org

**Comment by KyleBarton** [comment]
Thanks for getting back. Is there any difference in password requirements between the two systems? I've tried resetting my Jenkins.io password to something alphanumeric only, in case special characters were disallowed, but this does not help.

Should the "forgot password" flow work on Artifactory's login page? I've tried this as well, but never received an email to reset my password at my associated email address.

**Comment by timja** [comment]
> Thanks for getting back. Is there any difference in password requirements between the two systems? I've tried resetting my Jenkins.io password to something shorter and alphanumeric only, in case special characters were disallowed, but this does not help.

Shouldn't be, they use the same system behind the scenes.

> Should the "forgot password" flow work on Artifactory's login page? I've tried this as well, but never received an email to reset my password at my associated email address.

No it won't work

**Comment by MarkEWaite** [comment]
Forgot password on the Artifactory page definitely does not work.

You won't ever receive an email with the reset password from accounts.jenkins.io because the email address on the kybarton_amazon jenkins.io account is not a valid email address.

**Comment by timja** [comment]
That'll be the issue, I have a vague memory of artifactory validating the email address

**Comment by KyleBarton** [comment]
Yep, looks like changing my email address from kybarton_amazon to kybarton@amazon.com solved the issue. Strange, Jenkins must have had my email address correct originally, since it sent me my initial password. Perhaps I inadvertantly overwrote while resetting my pw. Thanks for your help! Closing this issue.

**Comment by daniel-beck** [comment]
Yep this just happened a few weeks ago, Artifactory rejects logins of accounts with invalid email addreses.

**Comment by MarkEWaite** [comment]
> I faced the same issue. `accounts.jenkins.io` had changed my email to my username and I was not able to login to `repo.jenkins-ci.org`. Till I corrected my email again (which by the way requires me to update my password or put in the same password three times)

I'm not aware of any case where accounts.jenkins.io changes email values without a request from the user.  If you have such a case, please share it with us.

**Comment by ThisIsQasim** [comment]
That’s what happened with me. I signed up with my email. Got the confirmation email and then the email automatically changed to my username on `accounts.jenkins.io`
