### ISSUE TITLE
releases of workflow-basic-steps fails with "401 Unauthorized"

### ISSUE THREAD

**Issue by car-roll** [jenkins-infra/helpdesk#2772]
### Service

ci.jenkins.io

### Summary

cd fails in `workflow-basic-steps` with "401 Unauthorized"

https://github.com/jenkinsci/workflow-basic-steps-plugin/runs/5097911132?check_suite_focus=true

**Comment by timja** [comment]
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/2771
