### ISSUE TITLE
Need help configuring Jenkins CI for jenkinsci/JenkinsPipelineUnit

### ISSUE THREAD

**Issue by nre-ableton** [jenkins-infra/helpdesk#2776]
### Service

ci.jenkins.io

### Summary

[JenkinsPipelineUnit](https://github.com/jenkinsci/JenkinsPipelineUnit/issues) currently uses AppVeyor (and AppVeyor _only_) to run CI tests. That means we are not running tests on Mac or Linux (there is an open issue for this, see https://github.com/jenkinsci/JenkinsPipelineUnit/issues/424). As such, we've had a few pull requests ([1](https://github.com/jenkinsci/JenkinsPipelineUnit/pull/425), [2](https://github.com/jenkinsci/JenkinsPipelineUnit/pull/482#issuecomment-1033944934)) submitted to the repository that attempted to add these platforms to CI, namely by way of GitHub actions.

While I'm not opposed to GitHub actions per se, I think that running the tests on Jenkins makes the most logical sense given the nature of the project. This was also recommended by @dduportal, see https://github.com/jenkinsci/JenkinsPipelineUnit/pull/482#issuecomment-1033924604.

We already have a [Jenkinsfile](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/Jenkinsfile) in the repository, so it seems that Jenkins support was set up long ago. However, it seems that neither `push` nor `pull_request` events trigger builds, and when I [searched](https://ci.jenkins.io/search/?q=JenkinsPipelineUnit&Jenkins-Crumb=e298fd733fcd749d4bd4c9072d4e4f693e73a0ecd1ca3c9444941e26db7f04ec) ci.jenkins.io for `JenkinsPipelineUnit`, I found nothing.

Can someone please point me in the right direction for fixing/configuring Jenkins su

### Reproduction steps

N/A

**Comment by timja** [comment]
Should show up in https://ci.jenkins.io/job/jenkinsci-libraries/ soon

We currently offer linux and windows builds, no MacOS atm

**Comment by lemeurherve** [comment]
You can find additional doc on ci.jenkins.io here: https://github.com/jenkins-infra/documentation/blob/main/ci.adoc

Don't hesitate to ping us on https://www.jenkins.io/chat/#jenkins-infra if needed :)

**Comment by nre-ableton** [comment]
@timja Thanks for taking care of this so quickly! I will have a look at updating our Jenkinsfile. In the meantime, I noticed that all of the builds fail with this message:

```
[2022-02-09T16:58:48.277Z] + mkdir -p /home/jenkins/.gnupg
Could not find credentials entry with ID 'gpg-pubring'
```

How do we fix this? I didn't see anything about this in the above docs.

**Comment by timja** [comment]
Generally credentials aren't allowed on ci.jenkins.io, you are referring to something here:
https://github.com/jenkinsci/JenkinsPipelineUnit/blob/b380937f648bc1c15de5fb61361fe2c835fdbeff/Jenkinsfile#L16

You can probably use the `buildPluginWithGradle()`

https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildPluginWithGradle.groovy

We generally re-use the `buildPlugin` (maven specific step) even though it has plugin in the name it's pretty generic.
