### ISSUE TITLE
Changelog drafter on core fails with "string too long"

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2777]
### Service

ci.jenkins.io

### Summary

[Changelog drafter on Jenkins core](https://github.com/jenkinsci/jenkins/runs/5129240516?check_suite_focus=true) is failing with a message that a string is too long.

```
No PR found for 11a1c98f64f8bb12395eab3[29](https://github.com/jenkinsci/jenkins/runs/5129240516?check_suite_focus=true#step:4:29)963277a72f3b46d: <<<<<fix: Deduplicate help button question mark>>>>>
/jenkins-changelog-generator/bin/generate-jenkins-changelog:196:in `parse': string length (197) exceeds the limit 128 (ArgumentError)
	from /jenkins-changelog-generator/bin/generate-jenkins-changelog:196:in `writeYAML'
	from /jenkins-changelog-generator/bin/generate-jenkins-changelog:260:in `<main>'
```

I assume one of the recently merged pull requests has a string somewhere that is too long.

### Reproduction steps

1. Run the changelog drafter from the https://github.com/jenkinsci/jenkins/actions/workflows/changelog.yml view
2. View the generated pull request at https://github.com/jenkins-infra/jenkins.io/pull/4909, see that its content is empty

**Comment by MarkEWaite** [comment]
@timja any guesses on the best place to look for the string that is too long?

**Comment by timja** [comment]
Seems to be working now?

**Comment by MarkEWaite** [comment]
> Seems to be working now?

Sure is.  No idea what caused it to break, but it is working now and well-behaved.
