### ISSUE TITLE
maven-11 builds not working

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2780]
### Service

ci.jenkins.io

### Summary

https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-5901/50/pipeline/11

Waiting for an executor for 10 hours

170 in queue
https://ci.jenkins.io/

**Comment by MarkEWaite** [comment]
Same problem seems to exist for the `maven` label, based on the results of the [agent availability check job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/)

**Comment by dduportal** [comment]
We found the root cause (autoscaling component not working). Fix in progress.

**Comment by dduportal** [comment]
Status:
- Autoscaler components keeps crashing with a 403 error when contacting AWS API. We have a request ID but aren't able to find the errors messages associated (S3 cloudtrail policy)
- We recycled the worker node and fixed the kubernetes management errors related to this cluster to ensure all components are freshly deployed: this action killed some agents (and builds) on ci.jenkins around 14:00 -> 15:00 UTC today.
- We manually scaled-up the cluster to 50 worker nodes to handle the build queue + incoming BOM builds
- We are working on https://github.com/jenkins-infra/aws/pull/92

**Comment by dduportal** [comment]
Operation required to re-create the EKS cluster: planned monday at 08:00am UTC as per https://github.com/jenkins-infra/status/pull/129 (status.jenkins.io).
