### ISSUE TITLE
Change default assignee of "console-column-plugin" on Jira

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2782]
### Service

Jira

### Summary

Heyo,

I'd like to ask to leave the default assignee of the "console-column-plugin" on Jira on unassigned. Currently, Jira assigns one of the former contributors, and I get notifications for my filter anyway.

Thanks in advance!

**Comment by lemeurherve** [comment]
I've set the default assignee of "console-column-plugin" to "unassigned".

**Comment by lemeurherve** [comment]
BTW, wouldn't you want to be the default assignee since [you've adopted it](https://github.com/jenkins-infra/repository-permissions-updater/pull/2377)?

**Comment by NotMyFault** [comment]
> BTW, wouldn't you want to be the default assignee since [you've adopted it](https://github.com/jenkins-infra/repository-permissions-updater/pull/2377)?

I don't mind, I subscribed to the filter anyway, otherwise I don't get notifications for past issues.

**Comment by timja** [comment]
default assignee is confusing to users generally, and they'll keep pinging you even if you have no intention on working on it.

It sets the wrong expectation imo
