### ISSUE TITLE
JUnit 1.55 requires Jenkins (2.321) or higher which breaks Jenkins LTS installation

### ISSUE THREAD

**Issue by ayanamist** [jenkins-infra/helpdesk#2783]
### Service

Update center

### Summary

1. Install Jenkins 2.319.3 which is the latest LTS version
2. Through first init wizard, install JUnit plugin or any other plugin dependent on it
3. Want: Install success
Got: Install fail with
```
jenkins | 2022-02-16 10:08:43.840+0000 [id=95] SEVERE h.model.UpdateCenter$DownloadJob#run: Failed to install junit
jenkins | java.io.IOException: Failed to load: JUnit Plugin (1.55)
jenkins | - Jenkins (2.321) or higher required
jenkins | at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
jenkins | at hudson.PluginManager.dynamicLoad(PluginManager.java:917)
```

I see this break change happens on 1.55 only which bump dependency for only a small change. But init wizard won't use 1.54, so i must manually copy the hpi into plugin directory and restart the jenkins process and init wizard, which is quit annoying.

Reported to jenkinsci/junit-plugin#354 and be redirected here

**Comment by ayanamist** [comment]
I know the reason: i'm using a mirror but it does not response with correct data when version parameter is used

**Comment by dduportal** [comment]
Thanks a lot for reporting and for closing with an explanation !
