### ISSUE TITLE
Archive `parallel-test-executor-plugin-sample`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#2785]
### Service

Github

### Summary

Please archive https://github.com/jenkinsci/parallel-test-executor-plugin-sample which is obsolete as of https://github.com/jenkinsci/parallel-test-executor-plugin/pull/17.

**Comment by lemeurherve** [comment]
Ping @jenkins-infra/jenkinsci-admins

**Comment by dduportal** [comment]
Ping @timja @daniel-beck @wadeck (I'm not sure what would be the procedure for such a request)

**Comment by lemeurherve** [comment]
Same kind of issue as https://github.com/jenkins-infra/helpdesk/issues/2088, Tim took care of it as he's a Jenkinsci admin.

**Comment by dduportal** [comment]
> I could do it myself if I were a repo admin, but I am not.

Neither Herve and I are, hence the ping to others 😅
