### ISSUE TITLE
https://www.jenkins.io/doc/developer/publishing/source-code-hosting/ misses repositories

### ISSUE THREAD

**Issue by raul-arabaolaza** [jenkins-infra/helpdesk#2788]
### Service

Other

### Summary

https://www.jenkins.io/doc/developer/publishing/source-code-hosting/ provides a way to find repository permissions for jenkins plugins, specifically it states:

```
This table shows the permissions currently granted to contributors in the jenkinsci GitHub repositories, excluding organization owners with full permissions to every repository
```

However there are missing repositories listed there, like the one for `ant` [plugin](https://github.com/jenkinsci/ant-plugin), `caffeine-api` [plugin](https://github.com/jenkinsci/caffeine-api-plugin) or `plugin-compat-tester` [test suite](https://github.com/jenkinsci/plugin-compat-tester) 

Ultimately this page is feeded from https://reports.jenkins.io/github-jenkinsci-permissions-report.json which is the one lacking data and that file is generated from https://github.com/jenkins-infra/infra-reports.

I have run it with one of my personal tokens and I get the expected results for the repos where I have `push` permissions, like `plugin-compat-tester` and no results for repos where I do not have `push` permissions.

This makes me believe the token used on `trusted.ci.jenkins.io` to run this code may lack `push` permissions for the missing repos, resulting in an incomplete report

### Reproduction steps

1. Navigate to https://reports.jenkins.io/github-jenkinsci-permissions-report.json
2. Search for `ant`, `caffeine-api` or `plugin-compat-tester` permissions

**Comment by timja** [comment]
entirely possible that this report was using jenkins-admin which had it's permissions downgraded awhile back.

**Comment by dduportal** [comment]
@timja @daniel-beck I'ml not sure of the safest way to fix this quickly and I need an advise here:

- should we grant back more permissions to the `jenkins-admin` GitHub account used by `trusted.ci` to generate reports?
- Or should we create a separated GitHub account/ GitHub app for this usage (and update the credential in trusted.j)?
- Something else?

**Comment by daniel-beck** [comment]
No opinion. App is probably a cleaner solution long-term.

**Comment by dduportal** [comment]
👍🏼 As i do not have access to the jenkinsci gh org, may I ask any jenkinsci admin here to create the github app in jenkinsci for this ?

**Comment by lemeurherve** [comment]
That would be great, could you add me too?

**Comment by timja** [comment]
Done: https://github.com/organizations/jenkinsci/settings/apps

**Comment by timja** [comment]
Once we've swapped the reports over to something else we should remove jenkinsadmin from the org, it has admin on quite a few teams

**Comment by dduportal** [comment]
Bump for follow-up:

- Herve is working on the GH token -> GitHub App (root problem)
- I started working on migrating  this job to infra.ci

**Comment by lemeurherve** [comment]
@jenkins-infra/jenkinsci-admins I'm the author of the request to install jenkins-infra-reports on the @jenkinsci account, with one unique permission, "Metadata" as "Read-only".
Could one of you accept this request please?

**Comment by timja** [comment]
Approved

**Comment by lemeurherve** [comment]
The switch to a Github App is finished, the report is now complete and available, with the missing plugins.

> ### Reproduction steps
> 
>     1. Navigate to [reports.jenkins.io/github-jenkinsci-permissions-report.json](https://reports.jenkins.io/github-jenkinsci-permissions-report.json)
> 
>     2. Search for `ant`, `caffeine-api` or `plugin-compat-tester` permissions
