### ISSUE TITLE
Migrate infra-report from trusted.ci to infra.ci

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2789]
https://github.com/jenkins-infra/infra-reports is built on both ci.jenkins.io (to test the Dockerfile are building and that's all), and by  trusted.j (to generate the reports as this instance has the *sensitive* credentials to allow generating the report from JIRA/github APIs).

The pipeline has 4 branches: 2 are really quick, 2 are slow (really slow) and are keeping trusted.ci VM agent up for a long timen which costs $$$ and slows down other build on tursted.j.

The goal is to migrate this job out from ci.j/trusted.j and move it to infra.ci.

**Comment by dduportal** [comment]
> Should also fix #2788

Only partially: there is the matter of "which credential to use". A GitHub App would be ideal (organization managed) but might requires to update the shell script in order to use it for the Ruby GH client stuff.

**Comment by dduportal** [comment]
WiP on trying https://github.com/jenkinsci/configuration-as-code-plugin/issues/782#issuecomment-494406090 to ensure that we can create a folder with scoped credential using Sops (secrets) -> Casc -> job-dsl

**Comment by dduportal** [comment]
Status:

- [x] PR opened at https://github.com/jenkins-infra/infra-reports/pull/37 and waiting for review to finalize migration
- [ ] Disable the "github-report" job on trusted.ci (need the PR to be merged)

**Comment by lemeurherve** [comment]
There were some errors in maintainer-info-report, might worth taking a look at it: https://github.com/jenkins-infra/plugin-site/pull/1150

**Comment by lemeurherve** [comment]
Related issue: https://groups.google.com/g/jenkinsci-dev/c/M_EDzBePIRk/m/FZbbXQeiCgAJ

cc @MarkEWaite @abmohantyj

**Comment by lemeurherve** [comment]
PR closed until we fix it, sorry for the inconvenience!

**Comment by dduportal** [comment]
PR reopened with changes to avoid messing up with the actual trusted.ci generation

**Comment by dduportal** [comment]
Opened an issue in https://github.com/jenkins-infra/repository-permissions-updater/issues/2488 to notify RPU maintainers.

Proposed deadline: if the checks are all green on https://github.com/jenkins-infra/infra-reports/pull/37, then we'll proceed to merge and migrate after the easter week end.

**Comment by dduportal** [comment]
ETA: Monday 25 (to avoid breaking things for a full week-end)

**Comment by dduportal** [comment]
Gotta close as it is done:

- Compared the reports last friday (from the PR https://github.com/jenkins-infra/infra-reports/pull/37 *before* merging and monday 25 after merging) and they are now the same
  - Fixed a bug in the PR, before merging, related to jq still printing its version in the first ine of the report, resulting in bad JSON. That was a merge error this time, due to me being not careful last week.
  - Fixed a minor issues in the pipeline not related to the reports content (typo in pipeline syntax) after merging
- Enabled the builds on infra.ci + disabled on trusted the monday 25 april, morning (CST)
- The report looks fine as the 26th, 
- RPU is working fine: no syntax error introduced
- Checked the Azure bucket storage where the reports are uploaded:
  - All reports have been updated  in the past 24h, while job in trusted is disabled: it means that regular updates are working as expected
  - All reports are JSON valid (no more `jq` version on first line).
  - Size of the reports is roughly the same
  - All remnants reports from the PR jave been cleaned up

**Comment by dduportal** [comment]
Same issue also: https://github.com/jenkins-infra/core-taglibs-report-generator/issues/11
