### ISSUE TITLE
Jenkins service is terminating when trying to add Slaves when using Launch agent by connecting it to the controller

### ISSUE THREAD

**Issue by ShanmukhaGajula** [jenkins-infra/helpdesk#2791]
### Service

Other

### Summary

Jenkins service is terminating when trying to add Slaves when using Launch agent by connecting it to the controller
![image](https://user-images.githubusercontent.com/21192877/155331742-e7f2be19-c532-4adc-9343-c5c2ea124eaa.png)

below are the setup details

Jenkins: 2.319.3
OS: Windows Server 2016 - 10.0
—
ace-editor:1.1
ansicolor:1.0.1
ant:1.13
antisamy-markup-formatter:1.6
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
backup:1.6.1
bitbucket:214.v2fd4234d0554
bitbucket-oauth:0.12
block-build-final-project:1.0
blueocean:1.24.6
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.24.6
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.24.6
blueocean-git-pipeline:1.24.6
blueocean-github-pipeline:1.24.6
blueocean-i18n:1.25.2
blueocean-jira:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.24.6
blueocean-pipeline-editor:1.24.6
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-6
bouncycastle-api:2.25
branch-api:2.7.0
build-blocker-plugin:1.7.8
build-monitor-plugin:1.13+build.202202212113
build-timeout:1.20
build-timestamp:1.0.3
caffeine-api:2.9.2-29.v717aac953ff3
categorized-view:1.10
checks-api:1.7.2
cloudbees-bitbucket-branch-source:751.vda_24678a_f781
cloudbees-folder:6.708.ve61636eb_65a_5
command-launcher:1.6
conditional-buildstep:1.4.1
configurationslicing:1.52
copyartifact:1.46.2
credentials:1074.v60e6c29b_b_44b_
credentials-binding:1.27.1
cucumber-living-documentation:3.2
cucumber-reports:5.6.1
cucumber-testresult-plugin:0.10.1
dashboard-view:2.18
discard-old-build:1.05
display-url-api:2.3.5
docker-commons:1.19
docker-workflow:1.28
durable-task:493.v195aefbb0ff2
echarts-api:5.3.0-2
email-ext:2.87
external-monitor-job:191.v363d0d1efdf8
favorite:2.3.3
font-awesome-api:6.0.0-1
git:4.10.3
git-client:3.11.0
git-server:1.10
gitbucket:0.8
github:1.34.2
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
github-oauth:0.37
global-build-stats:1.5
gradle:1.38
groovy:2.4
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
hp-application-automation-tools-plugin:7.2
htmlpublisher:1.29
jackson2-api:2.13.1-246.va8a9f3eaf46a
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jdk-tool:1.5
jenkins-design-language:1.25.2
jenkinslint:0.14.0
jira:3.7
jjwt-api:0.11.2-9.c8b45b8bb173
jnr-posix-api:3.1.7-2
job-import-plugin:3.4
jobConfigHistory:1119.v509e1017356b_
join:1.22-SNAPSHOT (private-682cfed6-mwaite)
jqs-monitoring:1.4
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.54
ldap:2.8
lockable-resources:2.14
mail-watcher-plugin:1.16
mailer:408.vd726a_1130320
mapdb-api:1.0.9.0
matrix-auth:2.6.6
matrix-project:1.20
maven-plugin:3.16
mercurial:2.16
metrics:4.1.6.1
mock-security-realm:1.6
momentjs:1.1.1
monitoring:1.90.0
naginator:1.18.1
notification:1.15
oic-auth:1.8
okhttp-api:4.9.3-105.vb96869f8ac3a
ownership:0.13.0
pam-auth:1.7
parameterized-trigger:2.43
pipeline-build-step:2.16
pipeline-github-lib:36.v4c01db_ca_ed16
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:446.vf27b_0b_83500e
pipeline-milestone-step:100.v60a_03cd446e1
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.21
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.21
plain-credentials:1.8
plugin-usage-plugin:2.1
plugin-util-api:2.14.0
poll-mailbox-trigger-plugin:1.026
popper-api:1.16.1-2
popper2-api:2.11.2-1
postbuild-task:1.9
pubsub-light:1.16
purge-job-history:1.6
queue-cleanup:1.4
repository:1.10
resource-disposer:0.17
role-strategy:3.1.1
run-condition:1.5
scm-api:595.vd5a_df5eb_0e39
script-security:1138.v8e727069a_025
snakeyaml-api:1.29.1
sse-gateway:1.25
ssh-credentials:1.19
ssh-slaves:1.30.2
sshd:3.1.0
structs:308.v852b473a2b8c
subversion:2.15.2
support-core:2.80
testng-plugin:554.va4a552116332
thinBackup:1.10
timestamper:1.12
token-macro:277.v7c8f82a_d66b_3
trilead-api:1.0.13
variant:1.4
view-job-filters:2.3
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:1138.v619fd5201b_2f
workflow-basic-steps:2.23
workflow-cps:2659.v52d3de6044d0
workflow-cps-global-lib:564.ve62a_4eb_b_e039
workflow-durable-task-step:2.38
workflow-job:1145.v7f2433caa07f
workflow-multibranch:711.vdfef37cda_816
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
ws-cleanup:0.40

**Comment by lemeurherve** [comment]
Hello @ShanmukhaGajula, this help desk is dedicated to issues with Jenkins Infrastructure.

For issues about Jenkins itself, please open an issue here: https://issues.jenkins.io/projects/JENKINS/

**Comment by ShanmukhaGajula** [comment]
Thank you for the info @lemeurherve
