### ISSUE TITLE
request reset of password for my jenkins account

### ISSUE THREAD

**Issue by vimil** [jenkins-infra/helpdesk#2794]
### Service

Accounts

### Summary

Could you help me reset the passwird fir my jenkins account. my emailid is vimilsaju@yahoo.com

**Comment by dduportal** [comment]
Hello @vimil , you should be able to reset your password on the following page: https://accounts.jenkins.io.

**Comment by vimil** [comment]
Hi @dduportal I tried thst but did not recieve any password reset email.

**Comment by dduportal** [comment]
Hi @vimil ! No worry: could you send an email to jenkins-infra-team <at> googlegroups.com from the email of this account, to prove your identity to us, so we could reset your password?

**Comment by vimil** [comment]
> Hi @vimil ! No worry: could you send an email to jenkins-infra-team googlegroups.com from the email of this account, to prove your identity to us, so we could reset your password?

Thanks, I have sent an email just now

**Comment by vimil** [comment]
Thanks I was able to reset my password
