### ISSUE TITLE
Request from security team to add Windows agent on cert-ci

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#2795]
### Service

cert.ci.jenkins.io

### Summary

Request from security team to add Windows agent on cert-ci
    * cert-ci is puppet-managed: https://github.com/jenkins-infra/jenkins-infra/blob/production/manifests/site.pp#L144-L147
    * We have to update the hieradata for cert-ci (https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/cert-ci.yaml) to:
        * Add the azure-vm plugin
        * Add the same agent specification as trusted.ci to allow Windows VM agents (https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/trusted-ci.yaml#L31-L71)
        * Maybe factorizing the agent profiles from "hieradata specified" to "JCasc" so we don't need to specify it per Jenkins instance
    * We have to add the Azure credentials in cert-ci manually (as there is no credential management as code easily done)
        * Scope: only system, not in pipelines!
    * @smerle volunteers
        * Warning: additional VPN route need to access it

**Comment by dduportal** [comment]
Update:

- Stephane is working on the puppet configuration PR + a PR to add his SSH credentials to puppet (to allow him SSH-ing to our VMs)
- Damien makes sure that cert-ci's runbook is up to date (to let Stephane access) + adds the azure credential on cert-ci

**Comment by dduportal** [comment]
[Update] cert.ci already has:
- A (valid) Azure credential which ID is `azure-credentials` 🥳 
- A cloud configuration for Azure VMs, with 2 Linux templates (`ubuntu-cert` and `ubuntu-cert-jdk11`) .

@smerle33 for information, we need to export the actual JCasc configuration from cert-ci in order to not remove it when adding the new Windows one

**Comment by dduportal** [comment]
We finally implemented it:

- https://github.com/jenkins-infra/jenkins-infra/pull/2076
- https://github.com/jenkins-infra/jenkins-infra/pull/2077

There are 2 agent templates providing labels `linux` and `windows
Jenkins tools had been updated to use local installation or defaults to temurin ZIP download
