### ISSUE TITLE
Add the 2022 GSoC org admins to jenkins-infra/gsoc GitHub team

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2797]
### GitHub repositories

[Pull requests for www.jenkins.io](https://github.com/jenkins-infra/jenkins.io/pulls) that are [related to Google Summer of Code](https://github.com/jenkins-infra/jenkins.io/pulls?q=is%3Apr+label%3Agsoc+is%3Aclosed) are evaluated by members of the @jenkins-infra/gsoc team.  The organization administrators for this year's Google Summer of Code project in Jenkins are Alyssa Tong (@alyssat), Jean-Marc Meessen (@jmMeessen), and Kris Stern (@krisstern).  They are not yet members of the @jenkins-infra/gsoc team

### GitHub users to have permission

@alyssat
@jmMeessen
@krisstern

### Permission level

Permissions as defined for the existing team

### Justification

Organization administrators should be requested and allowed to approve pull request to the Google Summer of Code subproject in the Jenkins documentation repository.  Previous organization admins have been allowed to do that and the pattern has worked well in the past.

**Comment by lemeurherve** [comment]
@MarkEWaite I've added them to the existing members of the jenkins-infra/gsoc team.

Note that this team has currently the "write" right on the repository jenkins-infra/jenkins.io
Should I downgrade it to "triage" or should I keep it as it is?

**Comment by MarkEWaite** [comment]
> @MarkEWaite I've added them to the existing members of the jenkins-infra/gsoc team.
> 
> Note that this team has currently the "write" right on the repository jenkins-infra/jenkins.io Should I downgrade it to "triage" or should I keep it as it is?

I think that we should keep it "as is" for now.  I hesitate to change a permission model that has worked in the past.  The "triage" permission is usually not enough to do the work we need from org admins.

**Comment by MarkEWaite** [comment]
I reviewed the permissions granted with @alyssat and confirmed that she's comfortable with the permissions granted by this change.

**Comment by timja** [comment]
> Note that this team has currently the "write" right on the repository jenkins-infra/jenkins.io
> Should I downgrade it to "triage" or should I keep it as it is?

copyeditors is codeowners on most files so they can't merge without a review outside of gsoc areas generally
