### ISSUE TITLE
Missing CD credentials

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2799]
This is a follow up issue to https://github.com/jenkins-infra/repository-permissions-updater/pull/2416. 
It's been more than 4 hours now and no CD secrets have been added to the repositories. If I remember correctly, credentials are updated hourly or something, no?
Also, would someone mind to uninstall the release-drafter bot from these repositories? CD would use the action anyway.
Thanks in advance!

**Comment by dduportal** [comment]
It seems that the private Jenkins controller used for this (trusted.ci.jenkins.io) is under a big load (cc @timja another bunch of tag rebuilds :'( ).

Currently fixing the instance (cleaning up build queue, updating and rebooting VM to cleanup)

**Comment by NotMyFault** [comment]
Yup, can confirm secrets are provided by now. Thanks for taking care of it!

> Also, would someone mind to uninstall the release-drafter bot from these repositories? CD would use the action anyway.

Maybe someone can take care of this one too? The app is deprecated and I'm not too sure how it rules out if you use the workflow from CD alongside.

**Comment by dduportal** [comment]
> Maybe someone can take care of this one too? The app is deprecated and I'm not too sure how it rules out if you use the workflow from CD alongside.

I'm sorry, I'm not really at ease with the "how is it working for plugins process". Ping @timja @jglick can you help (I'm not sure where such request goes usually: JIRA?)

**Comment by NotMyFault** [comment]
Must be done by someone with admin access on the org, because these apps are managed by the org.
Just appended it at the RPU originally because I was at it 👀

**Comment by dduportal** [comment]
Alas, the infra-team is not admin on jenkinsci organization. But many thanks for the precision, it helps a lot!

**Comment by jglick** [comment]
> Must be done by someone with admin access on the org

Removing the RD App from a given _repository_ can be done by someone with admin access to that repo; you do not need to be a @jenkinsci admin. Go to: https://github.com/apps/release-drafter/installations/775283

Removing the RD App from all of @jenkinsci would be great, but someone would first need to go through the list of enabled repos and make sure every one is using the RD Action, either in a dedicated workflow or via JEP-229, filing a PR for the repo as needed. Seems there are currently 158 of them, so this would probably require some light scripting to be feasible.

**Comment by NotMyFault** [comment]
> Removing the RD App from a given repository can be done by someone with admin access to that repo; you do not need to be a https://github.com/jenkinsci admin. Go to: https://github.com/apps/release-drafter/installations/775283

I went to `/settings/installations` on the repository and the app didn't have the typical "Configure" button, therefore I didn't even try to go via the app installation tab. Weird that you can manage it that way but not thru your repository.

> emoving the RD App from all of https://github.com/jenkinsci would be great, but someone would first need to go through the list of enabled repos and make sure every one is using the RD Action, either in a dedicated workflow or via JEP-229, filing a PR for the repo as needed.

Yeah that would be nice, considering the app is deprecated since 2019 and new features are only available to the workflows.

> Seems there are currently 158 of them, so this would probably require some light scripting to be feasible.

Make it 155 :P
Wondering if that would justify another JEP or at least an Epic issue to move app users over to the workflow action.
The app installation itself has been removed from the CD docs recently too in favor of promoting the workflow.

**Comment by jglick** [comment]
Doubt this rises to the level of a JEP or Epic. Just need someone to gather a complete list of repos, then hack up a script to check each of them to see if it is already using the Action, and if not, file a PR to add the standard workflow.

**Comment by NotMyFault** [comment]
> Doubt this rises to the level of a JEP or Epic. Just need someone to gather a complete list of repos, then hack up a script to check each of them to see if it is already using the Action, and if not, file a PR to add the standard workflow.

Likely, though more of an obscure task. Afaik, app installations are not publicly available to non repo admins.

Anyway, I'll close this issue here, considering the original issue has been resolved.

**Comment by jglick** [comment]
> app installations are not publicly available to non repo admins

Right; maybe available to _org_ admins.

**Comment by dduportal** [comment]
Many thanks @jglick for the help!

thanks @NotMyFault for the contributions

**Comment by lemeurherve** [comment]
> Anyway, I'll close this issue here, considering the original issue has been resolved.

Thanks for the follow-up PRs @NotMyFault & @jglick!
