### ISSUE TITLE
Access to status repo to be able to merge in north america timezone

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#2808]
### GitHub repositories

https://github.com/jenkins-infra/status

### GitHub users to have permission

@halkeye

### Permission level

Write

### Justification

STAAAAAAAAAAAATUUUUUS

Artifactory outage happened, but nobody around with merge access.

**Comment by dduportal** [comment]
@halkeye done, you're admin :) Thanks for the help!
