### ISSUE TITLE
GC for azure resources group

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#2812]
### Service

Azure

### Summary

on the model of AWS create a script to cleanup Azure for residual resources group from packer processes

https://github.com/jenkins-infra/packer-images/blob/main/Jenkinsfile_k8s#L19-L36
last item of : https://www.packer.io/plugins/builders/azure/arm#defaults

expand to azure

from : https://github.com/jenkins-infra/packer-images/blob/2c4ec12823a2187921501fde2d6f87b8d721a8ca/cleanup/aws.sh

**Comment by dduportal** [comment]
Closing: work done :)
