### ISSUE TITLE
https://www.jenkins.io/doc/developer/publishing/source-code-hosting/ misses contributors in teams

### ISSUE THREAD

**Issue by raul-arabaolaza** [jenkins-infra/helpdesk#2814]
### Service

Other

### Summary

https://www.jenkins.io/doc/developer/publishing/source-code-hosting/ is missing members that are assigned permissions via teams, for example.

Github User `alecharp` is member of the `https://github.com/orgs/jenkinsci/teams/matrix-project-plugin-developers` team and as such he has write permissions on the repository. But he is not listed in https://www.jenkins.io/doc/developer/publishing/source-code-hosting/ 

probabvly the existing tooling is old enough to ignore teams, but today most of permissions are given via teams, so the tooling is lacking a lot of information

**Comment by daniel-beck** [comment]
> probabvly the existing tooling is old enough to ignore teams, but today most of permissions are given via teams, so the tooling is lacking a lot of information

I'm pretty sure this used to work. I'd make sure the token has sufficient permissions first.

**Comment by lemeurherve** [comment]
I've added the following "Members: Read-only" permission to the Github App, let's see if it will be enough:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/91831478/157301032-f9bf63e9-b91e-45b0-bec2-1c73e43efb8a.png">

**Comment by timja** [comment]
Approved

**Comment by lemeurherve** [comment]
Last report since the additional permission look complete:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/91831478/157505745-73daf813-476b-4b77-8ddc-0b08eb23ff53.png">

Don't hesitate to report otherwise!
