### ISSUE TITLE
Sign up issues for Jenkins JIRA

### ISSUE THREAD

**Issue by slim-patchy** [jenkins-infra/helpdesk#2815]
### Service

Accounts

### Summary

A few hours ago a potential GSoC contributor tried signing up for a Jenkins JIRA account using https://accounts.jenkins.io/login, but was unable to get a email confirmation and had to resort to using the "Forgot password" option to reset password. After successfully logging in, he/she was able to get a (partial) stack trace for the error. 

![image](https://user-images.githubusercontent.com/76486443/157394655-4a03c3e6-7804-4f87-bf1e-acdce5649548.png)

Could you please look into this matter and advise if there is a bug or some other underlying problem? 

### Reproduction steps

1. Signed up for a new Jenkins JIRA account
2. Could not get new account confirmation email
3. Had to resort to using Forgot Password option to get email for account activation

**Comment by lemeurherve** [comment]
I've reproduced the error when creating a new account, investigating.

**Comment by dduportal** [comment]
🤔 sounds like that LDAP is not reachable by the account app

**Comment by lemeurherve** [comment]
@slim-patchy I've rebooted the pods, and tested an account creation, it works.

Could you ask the contributor to try again please?

**Comment by lemeurherve** [comment]
Closing this issue assuming it will be good, don't hesitate to reopen it if it's not the case.
