### ISSUE TITLE
Update ci.jenkins.io to latest LTS version (2.332.1)

### ISSUE THREAD

**Issue by cathychan** [jenkins-infra/helpdesk#2816]
### Service

ci.jenkins.io

### Summary

Please update ci.jenkins.io to use the latest LTS version `2.332.1`.

**Comment by dduportal** [comment]
Also, trusted.ci, cert.ci and release.ci should be upgraded. Thanks for reporting the issue!

**Comment by dduportal** [comment]
- ci.jenkins.io is up to date
- trusted.ci is also up to date
- release.ci will be automatically updated in the upcoming hour
