### ISSUE TITLE
Archiving of core Jira components causes regression in LTS backport and project management workflows

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2819]
### Service

Jira

### Summary

At some point in the past, I was able to create new issues and assign them to the `packaging` core component. This provided me with two pieces of functionality:

- I could label such issues with `lts-candidate` in Jira, which is the only issue tracking system (ITS) supported by our official LTS backport process (see e.g. the references to Jira in jenkins-infra/release#223 or https://github.com/jenkins-infra/backend-commit-history-parser).
- I could include such issues in a high-level project whose scope includes both Jenkins core (which uses only Jira and not GitHub issues) and core components; in particular, I could create a Jira epic containing core issues and core component issues.

Recently, I tried to file a new issue ([JENKINS-68007](https://issues.jenkins.io/browse/JENKINS-68007)) and assign it to the `packaging` component. I got the error message: "Component with id 'packaging' does not exist." When editing the component of an old issue (e.g. [JENKINS-41218](https://issues.jenkins.io/browse/JENKINS-41218)), I get the message: "Archived Component/s: packaging."

The archiving of this component is a regression in functionality:

- Before, I could create a packaging issue in Jira that integrated with our official LTS backport process by adding the `lts-candidate` label. Now, I can create a GitHub issue in `jenkinsci/packaging`, but I cannot integrate that issue into our official LTS backport process (which only uses Jira labels).
- Before, I could create a high-level project (in particular, a Jira epic) whose issues included both core Jira issues and core component Jira issues. Now, I can create a GitHub project, I can add core component GitHub issues to it but not core issues (which are only in Jira). Conversely, I can create a Jira epic and add core Jira issues to it but not core component issues (because I cannot add GitHub issues to a Jira epic or create new core component Jira issues).

Please either restore the old functionality by unarchiving the recently-archived core components, or provide me with a way to achieve the same high-level LTS backport and project management use cases using GitHub issues that I could accomplish before in Jira.

### Reproduction steps

Create a new Jira issue and try to assign it to the `packaging` component. You get the error message: "Component with id 'packaging' does not exist." When editing the component of an old issue (e.g. [JENKINS-41218](https://issues.jenkins.io/browse/JENKINS-41218)), you get the message: "Archived Component/s: packaging."

**Comment by timja** [comment]
I think this is unnecessary.

see the release checklist https://github.com/jenkins-infra/release/blob/master/.github/ISSUE_TEMPLATE/1-lts-release-checklist.md

we will update the packaging branch anyway for the LTS line

if you really want to keep track of it on Jira I would suggest putting it in core component

**Comment by basil** [comment]
> I think this is unnecessary.

It _is_ necessary to do project management in a single view (Jira epic or GitHub project) that covers both core and core
components.

**Comment by basil** [comment]
[JENKINS-68600](https://issues.jenkins.io/browse/JENKINS-68600) was filed in the incorrect component (core). Prior to the archiving of the `packaging` component, I could easily move the issue to the correct component. Now, I cannot see a way to move the issue to the correct component. This inhibits proper bug triage and project management.

I provided a solution when I filed this ticket:

> Please […] restore the old functionality by unarchiving the recently-archived core components […]

Why has this action not yet been taken?

**Comment by timja** [comment]
Because those components are tracking their issues on GitHub.

Having users report issues in multiple places is not helpful and I see in that issue that you provided advice to the user on where to correctly report it


——

Doing project management in one place is different and I don’t believe we need to re-open the component for that.

We could use something like core, unsorted, or something more specific that means this is a tracking issue only for use in a larger project

**Comment by basil** [comment]
> Because those components are tracking their issues on GitHub.

But that does not make sense for core components, because core itself is not tracking issues on GitHub. Either core and all core components should be tracked on GitHub issues, or core and all core components should be tracked on Jira. It is the inconsistency that results in problems for end users and project management. Please eliminate the inconsistency by moving core components back to Jira.

**Comment by timja** [comment]
I've re-enabled Jira for the `packaging` component.

If you want more re-enabled then please provide a list and I'll take a look
