### ISSUE TITLE
Remove old azure credentials previously used for packer-images

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2821]
These string credentials aren't used elsewhere, they can be removed.

          PKR_VAR_azure_subscription_id = credentials('packer-azure-subscription-id')
          PKR_VAR_azure_client_id       = credentials('packer-azure-client-id')
          PKR_VAR_azure_client_secret   = credentials('packer-azure-client-secret')

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/packer-images/issues/190#issuecomment-1065309609_

**Comment by dduportal** [comment]
Be careful to NOT remove the secrets from sops: only remove the Jenkins credentials in the casc definition.
