### ISSUE TITLE
s390x agent is offline and not responding to ssh

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2823]
### Service

ci.jenkins.io

### Summary

The [s390x agent](https://ci.jenkins.io/computer/s390x-agent/) (Ubuntu 18 running on an IBM Z series mainframe) is disconnected from ci.jenkins.io and from the test environment that I was using.  It no longer responds to ssh requests.

### Reproduction steps

1. Confirm that http://mark-pc2.markwaite.net:8080/computer/ibm-s390-jagent/ is offline
2. Confirm that the IP address used by that machine is still not responding to ping or ssh requests

### Contact info

I've added the contact information to the ci.jenkins.io private runbook through jenkins-infra/runbooks#44

**Comment by dduportal** [comment]
Thanks @MarkEWaite for reaching out to the IBM team. It seems that https://ci.jenkins.io/computer/s390x%2Dagent/ is now online: I'm closing the issue.

Please feel free to reopen it if there are any task to run on it.
