### ISSUE TITLE
migrate Jenkins is the way

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#2824]
### GitHub repositories

https://github.com/halkeye/jenkins-is-the-way

### GitHub users to have permission

@halkeye
@MarkEWaite 

### Permission level

Admin

### Justification

Fork and setup pls

See https://community.jenkins.io/t/moving-jenkins-is-the-way-stories-and-case-studies-to-jenkins-io/1156/25

**Comment by timja** [comment]
Anyone can create a repo in jenkins-infra who is part of the org?

**Comment by timja** [comment]
Yes: https://github.com/organizations/jenkins-infra/repositories/new

If you do it via that you can setup the access yourself, yeah I noticed that with transfer =/

**Comment by halkeye** [comment]
\o/ https://github.com/jenkins-infra/jenkins-is-the-way
