### ISSUE TITLE
Add a DockerHub credential to avoid API rate limit in Kubernetes

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2830]
This issue is about adding a DockerHub credential as namespaced secrets in Kubernetes when we have API rate limit blocking pod startups.

Reference of "old" issues with this root problem:
- https://github.com/jenkins-infra/helpdesk/issues/2648
- https://github.com/jenkins-infra/helpdesk/issues/2589

The scope of this issue, for now, is the following:
- Kubernetes clusters where there is a lot of autoscaling (up and down) e.g. used for Jenkins agents for ci.jenkins.io
- With Docker images hosted on the DockerHub

=> It means the clusters [cik8s](https://github.com/jenkins-infra/kubernetes-management/blob/main/clusters/cik8s.yaml) and [doks](https://github.com/jenkins-infra/kubernetes-management/blob/main/clusters/doks.yaml)

=> Short term fix is already done, to manually define the credential for Jenkins agents. Alas we discovered that datadog helm charts are often failing due to API rate limit, because we use a [customized docker image](https://github.com/jenkins-infra/docker-datadog) hosted in the DockerHub under the name [jenkinsciinfra/datadog](https://hub.docker.com/r/jenkinsciinfra/datadog) as per the [current "common" datadog configuration for all clusters](https://github.com/jenkins-infra/kubernetes-management/blob/7b762e72eb0595b7b3d933f2796093e7537d50eb/config/ext_datadog.yaml.gotmpl#L32)

Task list:

- [x] Generate a DockerHub account (ensuring that any token leaks would not allow injecting content into `jenkinsciinfra/` or `jenkins/` DockerHub namespace)
  - Username is `cijenkinsioinfra`, the recovery email is the private jenkins-infra mailing list
- [x] Short term fix for Jenkins agents: manually create the credential, following https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/, in each namespace `jenkins-agents` of each cluster with pods failing to start due to API rate limit, under the name `dockerhub-credential`
- [x] Configure the ci.jenkins.io kubernetes agents to use this credential as an imagePullSecret: https://github.com/jenkins-infra/jenkins-infra/pull/2066/files
- [x] Create a Helm chart  to allow inserting the credential in a given namespace, from values: https://github.com/jenkins-infra/helm-charts/pull/97
- [x] Install the helm chart `docker-registry-secrets` on the namespaces `jenkins-agents` and `datadog` on the 2 clusters, with the credential defined once in SOPS and passed as a helm values through the `secrets:` directive of helmfile
- [x] Configure datadog chart to use this credentials (wip in https://github.com/jenkins-infra/kubernetes-management/pull/2018)

**Comment by smerle33** [comment]
- [ ] add the dockerhub account to VM agents as per #2837
