### ISSUE TITLE
Want CI job for syslog-java-client

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2832]
### Service(s)

ci.jenkins.io

### Summary

In jenkinsci/syslog-java-client#51 I have proposed some build updates to the newly-adopted `syslog-java-client`. I am not yet getting a CI build for that PR. I assume this is because a job needs to be created on `ci.jenkins.io`. The last time Mark and I did this for `extras-memory-monitor`, Mark manually created a job in https://ci.jenkins.io/job/jenkinsci-libraries/job/extras-memory-monitor/ I presume the same action (or similar) needs to be taken here.

### Reproduction steps

Go to jenkinsci/syslog-java-client#51 and observe no PR build has taken place. The expected result is for a PR build to complete.

**Comment by timja** [comment]
Added to the list

**Comment by basil** [comment]
Many thanks!
