### ISSUE TITLE
Upgrade to Maven 3.8.5 blocks Jenkins core development

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2835]
### Service(s)

ci.jenkins.io

### Summary

All Jenkins core PR builds are currently failing with Maven errors. As a result all Jenkins core development is blocked.

The cause of the problem is [MNG-7432](https://issues.apache.org/jira/browse/MNG-7432), a regression in Maven 3.8.5. A fix for this regression has been proposed in apache/maven#695. At the time of this writing, the fix has neither been merged nor released.

To unblock Jenkins core development, please revert to Maven 3.8.4.

### Reproduction steps

Build a Jenkins core PR and observe the Maven errors.

**Comment by dduportal** [comment]
The PR https://github.com/jenkins-infra/jenkins-infra/pull/2103 reverts both (Jenkins) tool and VM agent templates to ensure that Maven 3.8.4 is used.

**Comment by dduportal** [comment]
> The cause of the problem is [MNG-7432](https://issues.apache.org/jira/browse/MNG-7432), a regression in Maven 3.8.5. A fix for this regression has been proposed in https://github.com/apache/maven/pull/695. At the time of this writing, the fix has neither been merged nor released.

Thanks for informations @basil ! We'll check once Maven 3.8.6 is released if this regression is fixed.

**Comment by basil** [comment]
Thank you!
