### ISSUE TITLE
Remove publish-over-ssh-plugin Jira component

### ISSUE THREAD

**Issue by gmcdonald** [jenkins-infra/helpdesk#2836]
### Service(s)

Jira

### Summary

I have copied all publish-over-ssh-plugin Jira Issues over to Github, and commented on each ticket.
Please remove the component (15792)

**Comment by timja** [comment]
I've archived the component so it won't show up on the new issue screen and people can't add to it anymore.

If I deleted the component would need to move them somewhere.

**Comment by lemeurherve** [comment]
🎉

**Comment by lemeurherve** [comment]
@gmcdonald @timja on https://plugins.jenkins.io/publish-over-ssh/ there is still a link "open an issue (jira)", not sure where and how it could be changed.

**Comment by timja** [comment]
Needs updating here:
https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-publish-over-ssh.yml

e.g. https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-azure-sdk.yml
