### ISSUE TITLE
DockerHub credential for vm agents

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2837]
### Service(s)

ci.jenkins.io

### Summary

see https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1306/8/pipeline

```
[](https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1306/8/pipeline/#step-104-log-24)[2022-03-20T05:34:17.861Z] #6 [internal] load metadata for docker.io/library/almalinux:8.5

[2022-03-20T05:34:17.861Z] #6 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/almalinux/manifests/sha256:a21996e1faa92e26a48c7fe3ae5652efc4b0eacb4ead710f0cca9167251dd27e: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

(and a number of other PRs)

@MarkEWaite worked around it by combining the PRs manually in https://github.com/jenkinsci/docker/pull/1310

The rate limiting is still happening at least on ec2 machines.

relates to https://github.com/jenkins-infra/helpdesk/issues/2830

**Comment by smerle33** [comment]
Hi @timja 
What do you think about setting a dockerhub credential within the VMs definition, for them to use this account and then not trigger the rate limit ? 
or/and provide the credential from within jenkins but limited to the "Packaging/docker"  (https://ci.jenkins.io/job/Packaging/job/docker/) area ? I can't see more area involved from the logs I get/understand but maybe we can elaborate a better range.

**Comment by dduportal** [comment]
@timja we are reachinga new kind of limit:
- As per the researches from @lemeurherve and @smerle33 , it seems that the docker VM are using a credential: the pulls are not anonymous (hence it's not a matter of public IP / private IP for VMs like it used to be)
  - Pipeline logs clearly show the "withCredentials" being called in the pipeline
  - ci.jenkins.io has a credential for the Docker account `jenkins4eval` https://ci.jenkins.io/credentials/store/system/domain/_/credential/jenkins-dockerhub/ which is referenced to be used by the jobs for Docker images
  - The error message `toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.` leads to the page at https://docs.docker.com/docker-hub/download-rate-limit/

=> even authenticated, we are reaching the limit of 200 pull for the account `jenkins4eval` per 6 hour windows, as per https://docs.docker.com/docker-hub/download-rate-limit/#what-is-the-download-rate-limit-on-docker-hub 😭

**Comment by dduportal** [comment]
There is an improvement that could be done on the pipeline library to make it easier to understand (and specify) which account should be used though:

- The pull and push credentials should be different, to ensure that an API rate limit does not impact the ability to deploy images
- The current code is tedious to read with 3 controllers (ci.j, infra.ci.j and trusted.ci.j), and it's missing "release.ci.j" (proof : the 4 of us failed to immediatly understand it).
- The current code is not binding the jenkins organization and the associated credential


Proposal based on what @lemeurherve and @smerle33 discussed:

- Define 2 new methods in the "Infra.groovy"  object:
  - One for getting the "pull" credentials, the other for the "push" credentials
- Each of these methods:
  - Returns a tuple of 2 strings:
    - 1st string is the docker account to use
    - 2nd string is the credential ID to use
  - Is implemented with a clear "switch/case" that treat each Jenkins controller differently


Proposal for the credentials:

- infra.ci.jenkins.io:
  - push credential: account `jenkinsciinfra`, credentialId: `jenkins-dockerhub-push` (as per https://github.com/jenkins-infra/kubernetes-management/blob/main/config/ext_jenkins-infra.yaml#L115-L120)
  - pull credential: new account (to be created) `infracijenkinsioinfra`, credentialId: `jenkins-dockerhub-pull`
- trusted.ci.jenkins.io:
  - push credential: account `jenkinsci`, credentialId: `jenkins-dockerhub-push` 
  - pull credential: new account (to be created) `trustedcijenkinsioinfra`, credentialId: `jenkins-dockerhub-pull`
- ci.jenkins.io:
  - push credential: account `jenkins4eval`, credentialId: `jenkins-dockerhub-push`
  - pull credential: account `cijenkinsioinfra`, credentialId: `jenkins-dockerhub-pull`



Future improvements possible with these proposals:

- Adding release.ci.jenkins.io
- Using multiple accounts with a "modulo" formula on ci.jenkins.io to spread the rate limit (good idea from @lemeurherve )
- Using different account per agent kind: one credential for VMs, another for containers. Even better matrix of accounts: one account per EC2 VM, another for Azure VMs, another for Digital Ocean containers, etc.
- Contacting Docker to ask them for help in the sponsorship area

**Comment by lemeurherve** [comment]
LGTM

For the "modulo" formula, I'm thinking about making the "pull" method randomly returns one of the multiples accounts.

**Comment by timja** [comment]
sounds fine, spreading the account would likely help the best and yeah maybe contact docker as this is just a pain

**Comment by lemeurherve** [comment]
https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

**Comment by timja** [comment]
It's not our namespace that's the issue afaik, it's the official images we pull from

**Comment by smerle33** [comment]
- infra.ci is ongoing (https://github.com/jenkins-infra/kubernetes-management/pull/2135)
- ci.j and trusted.ci are delayed (weekly + sec advisory) : ETA 30th of march

**Comment by dduportal** [comment]
Closing as the pipeline-library has been updated (with tests on infra.ci, ci.j and trusted.ci).

Post-tasks:

- [x] Cleanup docker-404 that was used to test the pipeline library: https://github.com/jenkins-infra/docker-404/pull/22
- [x] Documented in https://github.com/jenkins-infra/docker-404/pull/22
