### ISSUE TITLE
Plugin download: inconsistent file length: expected xxx but only got yyy

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/helpdesk#2839]
### Service(s)

Update center

### Summary

I tried to download `Amazon Web Services SDK :: All`, but got an error about its file length.

<details>

<summary>Error screenshot</summary>

![Screenshot_2022-03-21_095703_001](https://user-images.githubusercontent.com/2662497/159230743-8911cfb1-38b8-4b19-846b-03e9e2ad4a72.png)

</details>

It was one of the dependencies of EC2-fleet if I remember correctly.

I restarted, and then downloaded it directly, it worked.

(IOW nothing blocking as it's working for me now, but could help others)

### Reproduction steps

Manage Jenkins > Manage Plugins > Available > EC2 Fleet > "Install without restart"

**Comment by dduportal** [comment]
Closing as it is an old issue.

Feel free to reopen if you still have the issue.
