### ISSUE TITLE
GC AWS Old Images (from packer)

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#2846]
### Service(s)

AWS

### Summary

handle a Garbage Collector to remove OLD AMI version 

Should be split in 3 steps :

- [x] dev (done by https://github.com/jenkins-infra/packer-images/pull/201 )
- [x] staging
- [ ] prod

**Comment by dduportal** [comment]
Reminder of the "rules" for the GC of AMIs (I can't find my previous comment so I'm adding it here as asked :) ).

Rule of thumb I propose is "1d, 1m, 1y":

- "Dev" images (e.g. created by a PR build or a developer local build): if an AMI tagged as "dev" is older than 24h, then 🗑️ 
  - Rationale: these images are short lived, only to demonstrate that a PR does not break the build and have the intented purpose.
- "Staging" images (e.g. created by a build of the `main` branch,  which purpose it to ensure that "it just works"): if an AMI tagged as "staging is older than 1 week, then 🗑️ 
  - Rationale: the principal branch is built once per week, hence no need to keep older versions
- "Production" images (e.g. created by a tag build and used in production): if an AMI tagged as "production" is older than 1 year, then 🗑️ 
  - Rationale: 1 year is a laaaaaareg margin to really ensure that we clean things up. I personnaly would try a "3 months" rules so if we do not update an AMI soemwhere, then we'll see it fail in 3 month, but given the low amount of tagged images, no need to worry.

**Comment by dduportal** [comment]
Addon: we **also** have to delete the snapshot along with AMI.

The AWS documentation at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/deregister-ami.html describe the process: when you want to "delete an AMI", it's a 4 steps task:

1. Get the AMI ID (already done by our script)
2. Get the snapshot ID associated with this AMI
3. Deregister the AMI (already done by our script)
4. Delete the snapshot

**Comment by dduportal** [comment]
- Result is promising. We are down to 512 AMIS (instead of more than 3000 before).
- Updating the "Rule of thumb" to:
  - `dev` => 1 day
  - `staging` => 1 week
  - `prod` => 2 months
- [ ] implement prod  cleanup - https://github.com/jenkins-infra/packer-images/pull/594
- [ ] change the snapshots threshold to 2 month instead of 1 year (and see the result before decreasing it to 1 week and then 1 day)

**Comment by dduportal** [comment]
Manually deregistered the folloiwng AMIs:

- Ubuntu 20.x (ref. https://github.com/jenkins-infra/helpdesk/issues/2982)
- AMIs in `us-east-2` with no tags at all
- AMIS oldere than 2 month

=> we're down to 72 AMIs (instead of 3000s).

Time to clean up the snapshots now!

**Comment by dduportal** [comment]
- Result of running https://github.com/jenkins-infra/packer-images/pull/595 in production: snapshots amount went from ~ 4300 to 1001 now 👍

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/packer-images/pull/597 result is: 85 snapshots left. That should help!
