### ISSUE TITLE
Feature: Add windows server 2022 support

### ISSUE THREAD

**Issue by khatrig** [jenkins-infra/helpdesk#2848]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io

### Summary

In lieu of https://github.com/jenkinsci/docker-agent/pull/238, Need support for windows server 2022.

**Comment by dduportal** [comment]
For information for the people of the infra (or any contributors) who might want to take this issue: the scope here is for the VM agent only, in https://github.com/jenkins-infra/packer-images

**Comment by timja** [comment]
This is what Azure VM agents uses:
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/0a97a847315ad69de4025442dfa050891d1520c0/src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java#L1442

**Comment by dduportal** [comment]
Closing as duplicate of #2629 :)
