### ISSUE TITLE
Builds are often failing with timeout due to JFrog's Artifactory service (repo.jenkins-ci.org) being slow

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2849]
### Service(s)

Artifactory

### Summary

We were alerted in parallel by some users and our monitoring that Artificatory is slow to answer to requests, leading to slowness when downloading artifacts, avdn eventually build failures due to timeout.

We are working on it.

### Monitoring Metrics

<img width="529" alt="Capture d’écran 2022-03-23 à 15 09 14" src="https://user-images.githubusercontent.com/1522731/159720534-ac987393-cd75-4deb-8780-eace777e643a.png">
<img width="1879" alt="Capture d’écran 2022-03-23 à 15 10 38" src="https://user-images.githubusercontent.com/1522731/159720547-56ae66a1-cd5b-458e-bb38-f3542acc7261.png">

### To Do List

- [x] Open incident on status.jenkins.io @lemeurherve 
- [x] Open an incident at Jfrog @dduportal 
- [x] Communicate to users on dev + infra mailing lists @dduportal

**Comment by lemeurherve** [comment]
For the record, they opened an incident status today: [Partial Outage and Service Degradation with Artifactory and Xray](https://status.jfrog.io/incidents/8hh7t43bs0xt)
