### ISSUE TITLE
What jenkins url should  we set in jenkins master when its running in a kubernetes cluster except the jenkins master pod ip.

### ISSUE THREAD

**Issue by siddhantika** [jenkins-infra/helpdesk#2850]
### Service(s)

infra.ci.jenkins.io

### Summary

Hi,

I am from Digit Insurance team and have below query:

We have setup Jenkins master and slave on kubernetes and in the kubernetes cloud section for Jenkins URL we are giving Jenkins master pod IP which keeps on changing very day because we are stopping the service every night and because of that every day the IP gets changed and we have to update the Jenkins URL  in the kubernetes cloud.

Please suggest some other approach.

![image](https://user-images.githubusercontent.com/40066833/159877351-d8b7ec97-ecb1-4962-bb57-de9ce0ca7d9e.png)

Thanks,
Siddhantika

**Comment by timja** [comment]
This is the issue tracker for the Jenkins project infrastructure itself.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/), [community forum](https://community.jenkins.io) or the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)

----

In regards to the question itself you should use the service DNS address not the pod IP.

normally something like http://jenkins.

The Jenkins helm chart will set that up for you https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins

---- 

(Please don't reply here, it's not the right place)
