### ISSUE TITLE
jenkins.io not being updated

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2851]
### Describe your use-case which is not covered by existing documentation.

I saw a few commits have been made to `jenkins-infra/jenkins.io` in the last day or so, but they are not visible to me when going to https://jenkins.io. For example my most recent change to the upgrade guide is not visible, even after refreshing the page with Control-Shift-R. Is the site not being updated or deployed?

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

PR: https://github.com/jenkins-infra/jenkins.io/pull/5020
Page with outdated text: https://www.jenkins.io/doc/upgrade-guide/2.332/#upgrading-to-jenkins-lts-2-332-1

**Comment by MarkEWaite** [comment]
@lemeurherve I see that the infra.ci.jenkins.io job is passing and has processed the most recent commit from the master branch of the jenkins.io repository.  I wonder if there is a configuration change in the fastly cache that might be causing unexpected delays in delivering the new pages.

**Comment by dduportal** [comment]
Few elements:
- jenkins.io has a preview build run on infra.ci.jenkins.io (this is the one suceeding as per @MarkEWaite comment above)
- jenkins.io website is built for a "CI" use case on ci.jenkins.io, with a publicly available output for end users
- The "CD" pendant is running on trusted.ci.jenkins.io, which is reponsible to deploy (has the credentials allowing so should not be available on a public instance such as trusted.ci.jenkins.io).

**Comment by dduportal** [comment]
The deployment build is failing on trusted.ci for jenkins.io, since 04:12am UTC the 25th as per https://trusted.ci.jenkins.io:1443/job/jenkins.io/98521/ (private controller).

**Comment by dduportal** [comment]
- Instruction that fails is https://github.com/jenkins-infra/jenkins.io/blob/master/Jenkinsfile#L57
- It appears that trusted.ci is not up to date with the last plugin (including security). Updating it now.

**Comment by dduportal** [comment]
- OK so the plugin `checkstyle` was not installed. Good news as it was deprecated in Oct. 2021 😅
- Installed `warning-ng` on trusted.ci (which is already installed on ci.j: there was a discrepancy between both)
- Build is back online

**Comment by dduportal** [comment]
https://trusted.ci.jenkins.io:1443/job/jenkins.io/98529/ is green.

**Comment by basil** [comment]
Thanks @dduportal. My changes to the [upgrade guide](https://www.jenkins.io/doc/upgrade-guide/2.332/) are now live. But my recent [blog post](https://www.jenkins.io/2022/03/25/systemd-migration/) (which is linked to from that upgrade guide) is still not live, despite being scheduled for publication on March 25. Is there anything else I need to do for my blog post to be published?

**Comment by lemeurherve** [comment]
@basil your blog post is available at https://www.jenkins.io/blog/2022/03/25/systemd-migration/
The link in your upgrade guide doesn't contain the "/blog/" part.

**Comment by basil** [comment]
Sorry for the oversight and thank you for the kind correction.
