### ISSUE TITLE
Try Infracost

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2852]
https://github.com/infracost/infracost

> Infracost shows cloud cost estimates for Terraform. It enables DevOps, SRE and engineers to see a cost breakdown and understand costs before making changes, either in the terminal or pull requests. This provides your team with a safety net as people can discuss costs as part of the workflow.

Not a priority nor an absolute report but could be nice to get this sort of feedback on our aws or azure terraform repos:
![image](https://user-images.githubusercontent.com/91831478/159908081-c800d952-4358-450d-be06-e40ca7750826.png)

https://www.infracost.io/docs/faq/#how-does-infracost-work
https://www.infracost.io/docs/faq/#whats-the-difference-between-infracost-and-terraform-clouds-cost-estimation (note the OPA compatible resources)

**Comment by lemeurherve** [comment]
Last PR for review: https://github.com/jenkins-infra/pipeline-library/pull/342

**Comment by dduportal** [comment]
Working (commenting PRs) but removing from back burner (milestones).

**Comment by dduportal** [comment]
Closing as per https://github.com/jenkins-infra/packer-images/pull/393#pullrequestreview-1160037235

We tested Infracost, but the result was not really useful in our use case.

**Comment by alikhajeh1** [comment]
@dduportal just FYI that the [Infracost GitHub App](https://www.infracost.io/docs/integrations/github_app/) is now free so you can add cost estimated directly into PRs without going through adding/updating the CLI into Jenkins. If you have any feedback on the Infracost results, I'd love to hear them too (ali.hosseini@infracost.io).

**Comment by dduportal** [comment]
> @dduportal just FYI that the [Infracost GitHub App](https://www.infracost.io/docs/integrations/github_app/) is now free so you can add cost estimated directly into PRs without going through adding/updating the CLI into Jenkins. If you have any feedback on the Infracost results, I'd love to hear them too ([ali.hosseini@infracost.io](mailto:ali.hosseini@infracost.io)).

Hi @alikhajeh1 thanks for pointing this out. I can't find the required permission for the GitHub App in your documentation: is there an exhaustivre list?

We don't really have feedbacks about InfraCost except maybe we need Digital Ocean support (https://github.com/infracost/infracost/issues/808).

Our costs usage is driven by outbound bandwidth (Jenkins Update Center), Packer builds and Jenkins builds (ephemeral containers) as per https://github.com/jenkins-infra/helpdesk/issues/3502.

Infracost (or any other tool) cannot anticipate how much requests or builds are going to happen. The informations about cost are, clearly, valuable on other use cases but clearly not in Jenkins Infra project.

**Comment by dduportal** [comment]
Ping @lemeurherve do you have other feedbacks since you used Infracost more than me?

**Comment by dduportal** [comment]
> @dduportal makes sense - thanks! Re permissions for the GH App, I'll update our docs to mention it, here's the list:
> 
> <img alt="gh-app-permissions" width="542" src="https://user-images.githubusercontent.com/638577/231470242-55846ed0-e6a3-4edb-a048-eabca7a3f12d.png">
> 
> Essentially read-only access to the code so the app can run the CLI against it, and write access to the PR so a comment can be posted back. We recently got our [SOC2 Type II audit](https://www.infracost.io/security/) done as well.

Nice, that would be a really usefull piece of documentation for users wondering the scope. Thanks for this tool and the work, and congrats for the SOC2 audit 👏
