### ISSUE TITLE
"Something went wrong" error when trying to log into accounts.jenkins.io

### ISSUE THREAD

**Issue by Tblue** [jenkins-infra/helpdesk#2854]
### Service(s)

Accounts

### Summary

For the past few months, I've been unable to log into my Jenkins project account on `accounts.jenkins.io`: I'm getting a "Something went wrong. Please try again later." error on every attempt. Resetting my password does not help.

**Error ID:** `15295654` (please let me know if you also need my email address)

It would be great if someone could have a look. :-)

Thanks!

(NB: The error message prompts me to report the error on [Jira](https://issues.jenkins.io/projects/INFRA/issues/) -- which is a bit pointless since I can't log into my account, and creating a new account just to report the error feels somewhat "wasteful". Maybe the error message could link to GitHub instead, or to the INFRA mailing list?)

### Reproduction steps

1. Go to https://accounts.jenkins.io/login
2. Try to log in.
3. Observe the "Something went wrong" error.

**Comment by Tblue** [comment]
All right, never mind, please.

It turns out I simply didn't read the log in form correctly: I tried to log in with my _email address_, even though the form says to use the _user ID_. I now realize that at some point, probably when last changing my password, 1Password saved the email address as the username instead of the user ID, and it has been filling out the login form wrong ever since.

**I can log in successfully with my user ID.** Now I feel a bit stupid. :-) I'm going to close this one...

(The error message can probably be improved, though.)

**Comment by timja** [comment]
The service needs replacing. Last time I tried to update it I couldn’t get it to build, and it was a lot of effort to update
