### ISSUE TITLE
weekly.ci.jenkins.io

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2855]
### Service(s)

ci.jenkins.io

### Summary

Create a service something like:
- weekly.ci.jenkins.io

Needs to have the design-library plugin installed

**Comment by lemeurherve** [comment]
Hitting [this issue](https://github.com/jenkinsci/helm-charts/issues/210), will look into it tomorrow.

**Comment by lemeurherve** [comment]
https://weekly.ci.jenkins.io/design-library/

Looks really nice!
Quite heavy on CPU though ^^

**Comment by NotMyFault** [comment]
Thanks for quick setup! I noticed that logging in via Jenkins ldap you're missing Overall/Read permissions. Anonymous access is fine, but the former locks you out.

On a different note, can we get a rid of the blue ocean suite? It's no longer actively developed by providing new content and the focus does now lay on modernizing the actual UI of Jenkins.

**Comment by lemeurherve** [comment]
I've made a PR to restore authenticated users rights, as Jenkins admin I didn't saw this issue.

> On a different note, can we get a rid of the blue ocean suite? It's no longer actively developed by providing new content and the focus does now lay on modernizing the actual UI of Jenkins.

We'll have to create a dedicated Docker image to remove Blue Ocean plugin.

On another note, for lack of redirection to /design-library, I tried to add a System message but it didn't showed up, so I've added a "description" (see screenshot below) but I don't know how to change its style to emphasis it, any tips?

<details>
<summary>screenshot</summary>

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/91831478/161958272-8ff3fda6-e618-4567-a5b6-595c61eb2760.png">

</details>

**Comment by NotMyFault** [comment]
> On another note, for lack of redirection to /design-library, I tried to add a System message but it didn't showed up, so I've added a "description" (see screenshot below) but I don't know how to change its style to emphasis it, any tips?

If we enable "Safe HTML", we can do the following, for example.:

```html
<div style="background-color: #fbfbfb; border-radius: 8px; padding: 16px 20px; border: 1px solid #eee;">
    <div style="text-align: center;">
        <p>
            <img alt="Design Library" src="https://raw.githubusercontent.com/jenkinsci/design-library-plugin/master/logo.svg" height="100" width="280" />
        </p>
    </div>
    <p style="font-size: 18px;"><a href="https://plugins.jenkins.io/design-library/" rel="nofollow">Design Library</a> makes it easy for developers to build complex and consistent interfaces using Jenkins UI components.</p>
    <p style="font-size: 18px;"><a href="/design-library/" rel="nofollow">Take a look</a> at the new design library.</p>
</div>
```
Renders as 
![](https://i.imgur.com/OI4SzH0.png)

**Comment by timja** [comment]
I think we can leave Blue Ocean in, not worth creating another image.

**Comment by timja** [comment]
I would maybe drop the second link (`[Take a look](https://weekly.ci.jenkins.io/design-library/) at the new design library.`) and just change the first link to point to the library?

**Comment by NotMyFault** [comment]
> I would maybe drop the second link (`[Take a look](https://weekly.ci.jenkins.io/design-library/) at the new design library.`) and just change the first link to point to the library?

Yeah, I've updated the sample.

**Comment by lemeurherve** [comment]
For testing purpose I've added manually a redirection to /design-library, WDYT?
https://weekly.ci.jenkins.io/

The obvious default with this method is the root URL can't be accessed now.

**Comment by NotMyFault** [comment]
Looks fine for now.

In the future, I'd go with the banner from your PR and changing it from time to time to highlight different components, if we want to show more than design library on the weekly instance.

**Comment by timja** [comment]
returns 503 now

**Comment by timja** [comment]
Can you remove the redirect, we may want to show other components / parts of Jenkins

**Comment by timja** [comment]
(stopped returning 503 now)

**Comment by lemeurherve** [comment]
The pod rebooted, that why there was a 503.

I've removed the redirection, here is how it looks with the banner from the PR:
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/91831478/161974452-7a947b7d-4fd3-456e-8381-7d801caf63d3.png">

**Comment by timja** [comment]
that's fine as long as it's in code we can PR changes anyway.
