### ISSUE TITLE
Unable to login to issues.jenkins.io 

### ISSUE THREAD

**Issue by thomas-dee** [jenkins-infra/helpdesk#2857]
### Service(s)

Accounts

### Summary

As stated in the infra-mailing list I‘m not able to login to issues.jenkins.io

My User-ID is thomas_dee and the corresponding mail address is thomas.dee@gmx.net

**Comment by dduportal** [comment]
Hi @thomas-dee , the account was not set up with any email, hence it was blocked automatically.

I've set it to the email you used to contact us on the mailing list. I'll let you update the password and then adapt to the email you would prefer.

Please feel free to reopen if it does not work as expected.

**Comment by thomas-dee** [comment]
Thank you. It worked!
