### ISSUE TITLE
Update reports.jenkins.io/maintainers-info-report entries

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2858]
### Service(s)

Other

### Summary

Heyo,

I'm wondering on which base https://reports.jenkins.io/maintainers-info-report.json is updated and possibly which data source it gathers the data from.
I changed my first and last name a few days ago on accounts.jenkins.io but I see no change within the `displayName` on the json file.
Am I in the wrong spot or does it just not update much frequently?

Thanks in advance!

**Comment by NotMyFault** [comment]
Ok it (magically) updated within the past few minutes, thanks nevertheless.

**Comment by dduportal** [comment]
Hello @NotMyFault , for informations, the job in charge of getting this reports was disabled last friday and enabled again tuesday on trusted.ci.jenkins.io to unstuck the plugin advisory release. That explains the delay.

We are working on https://github.com/jenkins-infra/helpdesk/issues/2789 that should drastically improve this behaviour in the near future.

**Comment by NotMyFault** [comment]
Thanks for the explanation!
