### ISSUE TITLE
Failed to push artifacts for second version of my plugin

### ISSUE THREAD

**Issue by chillaq** [jenkins-infra/helpdesk#2859]
### Service(s)

ci.jenkins.io

### Summary

Plugin repo: https://github.com/jenkinsci/split-admin-plugin

I already have the original plugin in Jenkins up and running, I am trying to push the second version (1.0.1), all commands run fine, until the last command to upload the artifacts:
mvn release:prepare release:perform

I get the error below:
[INFO] Executing: /bin/sh -c cd /Users/bilalal-shahwany/repos/split-admin-plugin && git tag -F /var/folders/22/l3f2m03s2833f3nfzsj1b09m0000gq/T/maven-scm-581263084.commit split-admin-1.0.1
[INFO] Working directory: /Users/bilalal-shahwany/repos/split-admin-plugin
[INFO] Executing: /bin/sh -c cd /Users/bilalal-shahwany/repos/split-admin-plugin && git push ssh:********@github.com/jenkinsci/plugin-pom.git/split-admin refs/tags/split-admin-1.0.1
[INFO] Working directory: /Users/bilalal-shahwany/repos/split-admin-plugin
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.930 s
[INFO] Finished at: 2022-03-30T17:05:27-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project split-admin: Unable to tag SCM
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] fatal: remote error: 
[ERROR]   jenkinsci/plugin-pom.git/split-admin is not a valid repository name
[ERROR]   Visit https://support.github.com/ for help

I already tested the git ssh auth and it runs fine, no idea what I am doing wrong ...

**Comment by dduportal** [comment]
This is the issue tracker for the Jenkins project infrastructure itself.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/), [community forum](https://community.jenkins.io) or the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io)

----

In regards to the question itself, the git command failed to execute the `git push`. 
It seems that your [git remotes](https://git-scm.com/docs/git-remote) aren't correctly configured and are not pointing to a valid git URL.

You might want to check the output of `git remote -v` from within the local repository and verify that you are not using the [deprecated `git://` protocol](https://github.blog/2021-09-01-improving-git-protocol-security-github/).

Should be something like `https://github.com/jenkinsci/split-admin-plugin.git` (or `git@github.com:jenkinsci/split-admin-plugin.git` if you are using SSH authentication to git).

---- 

(Please don't reply here, it's not the right place)

**Comment by timja** [comment]
> This is the issue tracker for the Jenkins project infrastructure itself.

This issue was for releasing a plugin?
https://github.com/jenkinsci/split-admin-plugin

Not sure what's wrong with raising it here?

----

The first place to look is this page for troubleshooting:
https://www.jenkins.io/doc/developer/publishing/releasing-manually/#troubleshooting

**Comment by dduportal** [comment]
> > This is the issue tracker for the Jenkins project infrastructure itself.
> 
> This issue was for releasing a plugin? https://github.com/jenkinsci/split-admin-plugin
> 
> Not sure what's wrong with raising it here?
> 
> The first place to look is this page for troubleshooting: https://www.jenkins.io/doc/developer/publishing/releasing-manually/#troubleshooting

My apologizes, not awaken today: I did not catch it was a jenkins plugin.
Reopening the issue, and waiting for a feedback from @chillaq about: 

> It seems that your [git remotes](https://git-scm.com/docs/git-remote) aren't correctly configured and are not pointing to a valid git URL.
>
> You might want to check the output of git remote -v from within the local repository and verify that you are not using the [deprecated git:// protocol](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
>
> Should be something like https://github.com/jenkinsci/split-admin-plugin.git (or git@github.com:jenkinsci/split-admin-plugin.git if you are using SSH authentication to git).

**Comment by chillaq** [comment]
Thanks @dduportal , the git URL was indeed the issue, I found the incorrect one in the remote git repo and reset it, that fixed the issue.
