### ISSUE TITLE
Error on Digital Ocean terraform job

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2861]
### Service(s)

infra.ci.jenkins.io, Digital Ocean

### Summary

Since `doctl kubernetes options versions` doesn't return anything if the minor k8s version isn't suported anymore by Digital Ocean, the builds of https://github.com/jenkins-infra/digitalocean were failing.

Until we switch to Kubernetes 1.21, I'm hardcoding Digital Ocean kubernetes version.

**Comment by dduportal** [comment]
Closing this issue as it was fixed in https://github.com/jenkins-infra/digitalocean/pull/24
