### ISSUE TITLE
 Builds are often failing with timeout due to JFrog's Artifactory service (repo.jenkins-ci.org) being slow

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2864]
### Service(s)

Artifactory

### Summary

We were alerted in parallel by some users and our monitoring that Artificatory is slow to answer to requests, leading to slowness when downloading artifacts, avdn eventually build failures due to timeout.

Incident starting today around 08:50 UTC.

We are working on it.

### Monitoring Metrics

<img width="1862" alt="Capture d’écran 2022-04-04 à 12 31 52" src="https://user-images.githubusercontent.com/1522731/161526739-26d1fdac-8054-4ec7-a2bd-7d79cb1e417a.png">

### To Do List

- [x] Open incident on status.jenkins.io @lemeurherve 
- [x] Open an incident at Jfrog @lemeurherve 
- [x] Communicate to users on dev + infra mailing lists @dduportal

**Comment by jglick** [comment]
linking to #2752 again

**Comment by dduportal** [comment]
The incident is resolved. We never received any answer from Jfrog sdupport except the usual automatic email.

Please find attached a screenshot of the datadog monitor that summarize the impact measured on our monitoring system, as a comparison point to the real impact for end users + felt impact by the community:

<img width="1872" alt="Capture d’écran 2022-04-05 à 11 54 40" src="https://user-images.githubusercontent.com/1522731/161729451-133882a3-19f6-46fd-90c6-fb037b6b3041.png">

The subject of #https://github.com/jenkins-infra/helpdesk/issues/2752 is going to be put on the next infra meeting agenda to ensure that impacts like this one would be limited in the future, as per @jglick recommendation (many thanks).
