### ISSUE TITLE
Jenkins parallel stages running incorrect commands intermittently 

### ISSUE THREAD

**Issue by ollieSayer** [jenkins-infra/helpdesk#2865]
### Service(s)

infra.ci.jenkins.io

### Summary

Hi, 

We currently are using Jenkins to run four different suites of our tests in parallel using four different Jenkins nodes. We have noticed that sometimes two of the stages run / report that they have run the same suite when they haven't been setup to.

I've attached the pipeline setup ([parallel.txt](https://github.com/jenkins-infra/helpdesk/files/8410712/parallel.txt)) for the parallel stages for reference but from what we can see is the following happens occasionally

Build 1
- **Stage 'Console'**
-    States it is going to run the 'console' suite
-    Runs the console suite
- **Stage 'Slowest'**
-    States it is going to run the 'slowest' suite
-    Runs the console suite, with the same command as the 'console' stage

Build 2 
- **Stage 'Console'**
-    States it is going to run the 'console' suite
-    Runs the slowest suite, with the same command as the 'slowest' stage
- **Stage 'Slowest'**
-    States it is going to run the 'slowest' suite
-    Runs the slowest suite

In the file the runTestsUnix does a echo of the inputted suite and then runs the suite.

Looking at the logs the two stages run on different Jenkins nodes. As the workspaces are wiped its hard to say if the correct suite was actually run but Jenkins is mixing up the commands of the stages and reporting the wrong command and logs for the stages.

Is this a known issue / bug?

**Comment by dduportal** [comment]
Hi @ollieSayer , this is the issue tracker for the Jenkins project infrastructure itself.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/), [community forum](https://community.jenkins.io/) or the [chat channels](https://www.jenkins.io/chat/) for questions or even create a bug on the [issues site](https://issues.jenkins.io/)
