### ISSUE TITLE
Request access to Jenkins project VPN

### ISSUE THREAD

**Issue by imonteroperez** [jenkins-infra/helpdesk#2867]
### Service(s)

VPN

### Summary

- Following https://github.com/jenkins-infra/docker-openvpn#howto-get-client-access
- PR: https://github.com/jenkins-infra/docker-openvpn/pull/152

**Comment by dduportal** [comment]
Todo list for infra people:

- [ ] Sign request for certificate (https://github.com/jenkins-infra/docker-openvpn/pull/152)
- [ ] Ensure that a new Docker image is released
- [ ] Deploy the new Docker image

**Comment by dduportal** [comment]
VPN is up to date. Gotta check the client side directly with you @imonteroperez .

**Comment by dduportal** [comment]
Closing as we confirmed that it worked on @imonteroperez machine + PR https://github.com/jenkins-infra/docker-openvpn/pull/154 opened to fix documentation.
