### ISSUE TITLE
Repository Permissions Updater not syncing logged in user from Artifactory

### ISSUE THREAD

**Issue by ThisIsQasim** [jenkins-infra/helpdesk#2868]
### Service(s)

Accounts, Artifactory

### Summary

Repository Permissions Updater is not syncing my username from Artifactory. I was able to login to Artifactory yesterday with my Jenkins community user but I am still getting `The following usernames in 'Jenkins project users to have release permission' need to log into Artifactory` on https://github.com/jenkins-infra/repository-permissions-updater/issues/2479 

### Reproduction steps

1. I requested hosting for a new plugin https://github.com/jenkins-infra/repository-permissions-updater/issues/2479
2. The hosting checker bot asked me to log in to Artifactory
3. I logged in to Artifactory with the same user that I use to login to Jira <img width="1280" alt="Screenshot 2022-04-06 at 3 48 36 PM" src="https://user-images.githubusercontent.com/18313886/161958573-a0b34608-6800-4749-a186-f98789c21e93.png">
4. I am still getting the same error after 16 hours

**Comment by dduportal** [comment]
Hi @ThisIsQasim , the authentication on JFrog is delegated to the community authentication system.

Could you try the following please?

- Reset your community's account password on accounts.jenkins.io
- Validate that this new password is valid by authenticating to JIRA (https://issues.jenkins.io)
- Once you are able to log-in on JIRA, then retry on Artifactory

**Comment by ThisIsQasim** [comment]
Hi @dduportal, I am able to login to Artifactory but my username is not being picked up by the `Repository Permissions Updater`

**Comment by ThisIsQasim** [comment]
The bot throws this error even though I had logged in. https://github.com/jenkins-infra/repository-permissions-updater/issues/2479#issuecomment-1090120136

> Hello from your friendly Jenkins Hosting Checker
> 
> It appears you have some issues with your hosting request. Please see the list below and correct all issues marked Required. Your hosting request will not be approved until these issues are corrected. Issues marked with Warning or Info are just recommendations and will not stall the hosting process.
> 
> * ⛔ Required: The following usernames in 'Jenkins project users to have release permission' need to log into [Artifactory](https://repo.jenkins-ci.org/): thisisqasim (reports are re-synced hourly, wait to re-check for a bit after logging in)
> 
> You can re-trigger a check by editing your hosting request or by commenting `/hosting re-check`

**Comment by dduportal** [comment]
Ping @timja @daniel-beck can you help on this? I have no idea how the hosting bot is working and why it's triggering this error

**Comment by daniel-beck** [comment]
@dduportal infra-reports needs to work for this.

**Comment by dduportal** [comment]
> Looks like the old job on trusted.ci was deleted before the new one on infra.ci is running? 🤨

Deleted no, but disabled yes as part of https://github.com/jenkins-infra/helpdesk/issues/2789 . It's my fault, sorry for that.
I'm enabling it again to fix this issue.

**Comment by dduportal** [comment]
- Artifactory users report ran again on trusted.ci ✅ 
- RPU triggered and running again: should be fixed in a few minutes

**Comment by ThisIsQasim** [comment]
I am able to proceed to the next step. Thanks for fixing everything.
