### ISSUE TITLE
Update services to latest LTS version (2.332.2)

### ISSUE THREAD

**Issue by imonteroperez** [jenkins-infra/helpdesk#2869]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

Please update the mentioned services to use the latest LTS version 2.332.2.

**Comment by lemeurherve** [comment]
Thanks @imonteroperez, no need to open issue for this though, our bot is automatically creating pull requests like this one: https://github.com/jenkins-infra/docker-jenkins-lts/pull/454, and as soon as our (infra) docker-jenkins-lts and docker-jenkins-weekly images are published, updatecli will open other PRs to update all instances as well.

**Comment by lemeurherve** [comment]
I see it's part of the LTS checlist.

Should it be removed from it @MarkEWaite @dduportal ?

**Comment by lemeurherve** [comment]
Nevermind my first message then @imonteroperez and thanks again for the release!

**Comment by dduportal** [comment]
- release.ci: https://github.com/jenkins-infra/kubernetes-management/pull/2187 ✅

**Comment by dduportal** [comment]
- trusted.ci:
  - Triggered manually (run weekly otherwise) ✅ 
  - PR opened and merged - https://github.com/jenkins-infra/jenkins-infra/pull/2116 ✅ 
  - Puppet applied the change to trusted.ci, currently restarting ✅

**Comment by dduportal** [comment]
- cert.ci: should be updated in the next 24h (ping @wadeck for info). If not let me know.
- ci.jenkins.io: Let's delay a few hours, has the BOM build kicked so I prefer avoid restarting it :)

**Comment by Wadeck** [comment]
fine with me :)

**Comment by dduportal** [comment]
- cert.ci.jenkins is know up to date (don't know who did it but it is :) ) ✅

**Comment by dduportal** [comment]
Closing as ci.jenkins.io has just been upgraded.
