### ISSUE TITLE
Jenkins Update Site for version 2.332 is not up-to-date

### ISSUE THREAD

**Issue by reinholdfuereder** [jenkins-infra/helpdesk#2870]
### Service(s)

Update center

### Summary

After updating Jenkins core to LTS 2.332.2 (from 2.319.3) and updating all Jenkins plugins via tool ("install-plugins.sh" in Docker) some of the plugins (e.g. "workflow-cps") still showed available updates: IMHO https://updates.jenkins.io/dynamic-2.332/update-center.actual.json is outdated

### Reproduction steps

Based upon Jenkins plugin "workflow-cps"
(But it also affects "display-url-api" or "pipeline-model-api"; the oldest release that is outdated is "display-url-api" 2.3.6 which was 17 days ago, so presumably the problem is there for 17+ days?)

1. Prepare "plugins.install.txt": `workflow-cps`
2. Try to update latest version of this plugin via "install-plugins.sh < plugins.install.txt" in Docker container for Jenkins core v2.332.2 (`FROM jenkins/jenkins:2.332.2-lts-jdk11`)
```
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
Using version-specific update center: https://updates.jenkins.io/dynamic-2.332/...
Downloading plugins...
Downloading plugin: workflow-cps from https://updates.jenkins.io/dynamic-2.332//latest/workflow-cps.hpi
 > workflow-cps depends on workflow-api:2.47,workflow-scm-step:2.13,workflow-step-api:2.24,workflow-support:3.8,scm-api:2.6.5,script-security:1.78,structs:1.23,support-core:2.43;resolution:=optional,ace-editor:1.1
Skipping already installed dependency workflow-api:2.47 (2.47 <= 1143.v2d42f1e9dea_5)
Skipping already installed dependency workflow-scm-step:2.13 (2.13 <= 2.13)
Skipping already installed dependency workflow-step-api:2.24 (2.24 <= 622.vb_8e7c15b_c95a_)
Skipping already installed dependency workflow-support:3.8 (3.8 <= 815.vd60466279fc8)
Skipping already installed dependency scm-api:2.6.5 (2.6.5 <= 595.vd5a_df5eb_0e39)
Skipping already installed dependency script-security:1.78 (1.78 <= 1145.vb_cf6cf6ed960)
Skipping already installed dependency structs:1.23 (1.23 <= 308.v852b473a2b8c)
Skipping optional dependency support-core
Skipping already installed dependency ace-editor:1.1 (1.1 <= 1.1)

WAR bundled plugins:

Installed plugins:
...
workflow-cps:2660.vb_c0412dc4e6d
...
```

Whereas (a) https://plugins.jenkins.io/workflow-cps/#releases shows several newer versions that IMHO are compatible with this version of Jenkins core AND (b) "<JENKINS URL>/pluginManager/" also shows 2683.vd0a_8f6a_1c263 (released 10 days ago) as an available update.

=> I think https://updates.jenkins.io/dynamic-2.332/update-center.actual.json is slightly outdated

**Comment by timja** [comment]
cc @daniel-beck

**Comment by daniel-beck** [comment]
2.332 < 2.332.x

**Comment by reinholdfuereder** [comment]
Sorry, I don't get it (**update:** initially):
* I did NOT specify the URL by myself, but used the "install-plugins.sh" (which should be: https://github.com/jenkinsci/docker/blob/master/install-plugins.sh)
* In the Docker container I see these Jenkins env variables:
  ```
  JENKINS_HOME=/var/jenkins_home
  JENKINS_INCREMENTALS_REPO_MIRROR=https://repo.jenkins-ci.org/incrementals
  JENKINS_SLAVE_AGENT_PORT=50000
  JENKINS_UC=https://updates.jenkins.io
  JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
  JENKINS_VERSION=2.332.2
  ```

**=> Oh, found the problem/bug (in the "install-plugins.sh" script): it only uses the Jenkins major + minor version, but not the micro version**
* https://github.com/jenkinsci/docker/blob/c7fec3c9375bb2e8541e86ed0f2348722075f896/install-plugins.sh#L207
* https://github.com/jenkinsci/docker/blob/c7fec3c9375bb2e8541e86ed0f2348722075f896/install-plugins.sh#L248
* https://github.com/jenkinsci/docker/blob/c7fec3c9375bb2e8541e86ed0f2348722075f896/install-plugins.sh#L250

When manipulating the script to use the full version (string) including micro version:
```
jenkins@c0fe81a0d9a7:~$ diff /usr/local/bin/install-plugins.sh MY_install-plugins.sh
207c207
<         echo "$major.$minor"
---
>         echo "$version"
248a249
>     echo "jenkinsVersion: ${jenkinsVersion}"
```

... I get the expected result:
```
WARN: install-plugins.sh is deprecated, please switch to jenkins-plugin-cli
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
jenkinsVersion: 2.332.2
Using version-specific update center: https://updates.jenkins.io/dynamic-stable-2.332.1/...
Downloading plugins...
Downloading plugin: workflow-cps from https://updates.jenkins.io/dynamic-stable-2.332.1//latest/workflow-cps.hpi
 > workflow-cps depends on workflow-api:1143.v2d42f1e9dea_5,workflow-scm-step:2.13,workflow-step-api:622.vb_8e7c15b_c95a_,workflow-support:815.vd60466279fc8,scm-api:595.vd5a_df5eb_0e39,script-security:1145.vb_cf6cf6ed960,st
ructs:308.v852b473a2b8c,support-core:2.43;resolution:=optional,ace-editor:1.1
Skipping already installed dependency workflow-api:1143.v2d42f1e9dea_5 (1143.v2d42f1e9dea_5 <= 1143.v2d42f1e9dea_5)
Skipping already installed dependency workflow-scm-step:2.13 (2.13 <= 2.13)
Skipping already installed dependency workflow-step-api:622.vb_8e7c15b_c95a_ (622.vb_8e7c15b_c95a_ <= 622.vb_8e7c15b_c95a_)
Skipping already installed dependency workflow-support:815.vd60466279fc8 (815.vd60466279fc8 <= 815.vd60466279fc8)
Skipping already installed dependency scm-api:595.vd5a_df5eb_0e39 (595.vd5a_df5eb_0e39 <= 595.vd5a_df5eb_0e39)
Skipping already installed dependency script-security:1145.vb_cf6cf6ed960 (1145.vb_cf6cf6ed960 <= 1145.vb_cf6cf6ed960)
Skipping already installed dependency structs:308.v852b473a2b8c (308.v852b473a2b8c <= 308.v852b473a2b8c)
Skipping optional dependency support-core
Skipping already installed dependency ace-editor:1.1 (1.1 <= 1.1)

WAR bundled plugins:

Installed plugins:
...
workflow-cps:2686.v7c37e0578401
```

=> I will try to make a little PR for this little bug

**Comment by timja** [comment]
@reinholdfuereder install-plugins.sh is deprecated for removal, please use the `jenkins-plugin-cli` in the image instead

**Comment by reinholdfuereder** [comment]
@timja Thanks for the hint, I will try again:
Please note that the last time I tried "jenkins-plugin-cli" (or in fact "plugin-installation-manager-tool") the "install-plugins.sh" was deprecated too already, but handled the (potentially temporary infrastructure?) problems (IIRC timeouts during downloads) in contrast to the new "jenkins-plugin-cli", because it did retries...
