### ISSUE TITLE
[issues.jenkins.io] Jira - "The End of Life health check has failed in your system."

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2872]
### Service(s)

Jira

### Summary

The Jira instance at issues.jenkins.io which hosts most of the Jenkins project issues show a message (when authenticated) `The End of Life health check has failed in your system`.

<img width="1237" alt="Capture d’écran 2022-04-07 à 14 21 59" src="https://user-images.githubusercontent.com/1522731/162197521-c0d873f4-1aea-4ea6-9298-9c9fbc49234e.png">

We are curently using the version 8.13 of Jira, which end of life is in october 2022.
8.13.x baseline is the "previous LTS" as per https://confluence.atlassian.com/enterprise/long-term-support-releases-948227420.html

<img width="691" alt="Capture d’écran 2022-04-07 à 14 23 32" src="https://user-images.githubusercontent.com/1522731/162197785-1dd67362-7b83-4ce8-aed5-3e38de44a1d9.png">

We should plan an upgrade to 8.20 (current LTS) which end of life is ocotber 2023 - https://confluence.atlassian.com/jirasoftware/jira-software-8-20-x-release-notes-1086411771.html.

This Jira instance is hosted by the Linux foundation : we have to 

- [x] Open a issue on their system to request the upgrade and decide, with them of a schedule
  - Usually morning in the US west coast (where their support/eng. team are), end of day in EU. But might be morning EU/afternoon Australia if they have a team there.
- [ ] Announce the maintenance to our users
  - [ ] On status.jenkins.io
  - [ ] On the mailing lists
  - [ ] On IRC/Gitter channels (#jenkins-infra , jenkins/jenkinsci at least)
  - [ ] On other social media (ping @jmMeessen @MarkEWaite )?
- [ ] Ensure the maintenance is performed by them and successful
- [ ] Close the maintenance windows

**Comment by MarkEWaite** [comment]
This needs to be reported to the Linux Foundation through the [Linux Foundation Service Desk](https://jira.linuxfoundation.org/plugins/servlet/theme/portals/category/4)

**Comment by timja** [comment]
`s/JIRA/Jira` 😉 , updated for you

**Comment by timja** [comment]
> This needs to be reported to the Linux Foundation through the [Linux Foundation Service Desk](https://jira.linuxfoundation.org/plugins/servlet/theme/portals/category/4). [Project services](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2) is the correct location to report it as a ["Get IT help"](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/37).
> 
> I have permissions to do that, but would love to have someone else confirm that they can also do it.

It's public anyone can create a ticket for it

**Comment by dduportal** [comment]
Thanks folks ❤️ 

Please note that the issue has been added to the milestone "infra-team-synx-next", which means we'll discuss this task and its allocation during the next infra meeting (would be 2022-04-12).

It means that there are no emergency to do it today (the EoL in 6 month).

**Comment by dduportal** [comment]
Issue opened at https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/IT-23874

**Comment by dduportal** [comment]
Issue is waiting from the LF teams:

> I'll provide more updates once I hear from the team


Removing milestone until we have more news.

**Comment by dduportal** [comment]
We just got a few dates. Friday 22th of April sounds the most interesting: waiting for timing confirmation before communciating in email/status.jenkins.io/etc.

**Comment by dduportal** [comment]
Changed due to logistical delays. Should be done the 26th of April, 02:00pm PST (09:00pm UTC). Gotta update status.jenkins.io.

**Comment by timja** [comment]
@dduportal it was already upgraded on Friday?

![image](https://user-images.githubusercontent.com/21194782/165090867-39b63054-ad25-482b-a51d-a016f789e658.png)

I had to click a button when I logged in on Saturday to confirm some post upgrade thing.

**Comment by dduportal** [comment]
OK, sounds like that the LF teams still proceeded last friday as per @timja comment (thanks!):

<img width="1243" alt="Capture d’écran 2022-04-25 à 14 45 20" src="https://user-images.githubusercontent.com/1522731/165092182-ea4d99de-a102-4773-b2d3-300ac890e0d9.png">


For the people involved next time: LF teams are using PST timezone.

**Comment by timja** [comment]
Yeah that's the screen I saw
