### ISSUE TITLE
recover account

### ISSUE THREAD

**Issue by huangsuoyuan** [jenkins-infra/helpdesk#2874]
### Service(s)

Accounts

### Summary

hi, I have been unavailable with the Internet for a while. 
When I get access the Internet again I found my jenkins account for https://repo.jenkins-ci.org/ blocked for some reason
My account name is huangsuoyuan

The plugin I want to release https://plugins.jenkins.io/list-git-branches-parameter/

Does anybody know what is wrong with my account?

### Reproduction steps

1. open https://repo.jenkins-ci.org/ui/login/
2. type in my account

**Comment by dduportal** [comment]
Hi @huangsuoyuan, as explained https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/ , you need to reset your Jenkins account at https://accounts.jenkins.io.

Once done, you can test by logging-in in JIRA at https://issues.jenkins.io.

Then, you should be able to login at https://repo.jenkins-ci.org if you are a plugin maintainer.

**Comment by huangsuoyuan** [comment]
@dduportal thank you!
I have my account back again
