### ISSUE TITLE
[Kubernetes Ingresses] Bump Nginx Chart to 4.0.18 + Cert-manager chart to 1.8.0

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2875]
Major changes that works around recent OpenSSL CVE, please read carefully the changelogs:

- [x] Nginx https://github.com/jenkins-infra/kubernetes-management/pull/2153
- [ ] Cert-manager https://github.com/jenkins-infra/kubernetes-management/pull/2180

Don't forget to add a note on status.jenkins.io before :)

**Comment by lemeurherve** [comment]
Cert-manager: https://github.com/cert-manager/cert-manager/releases/tag/v1.8.0
404 on their "upgrade from 1.7.0 to 1.8.0" page.

**Comment by dduportal** [comment]
> ## Cert-manager
> 
> https://github.com/cert-manager/cert-manager/releases/tag/v1.8.0 404 on their "upgrade from 1.7.0 to 1.8.0" page.
> 
> Breaking changes:
> ### Validation of the rotationPolicy field
> 
> We should be good as we aren't creating/updating our own certificate CRDs.
> ### Changed Container Layouts
> 
> Not concerned
> ### .exe Extension on Windows
> 
> Not concerned
> ### Changed Import Path
> 
> Not concerned

https://github.com/cert-manager/website/pull/878/files#diff-dd9030c51aa11c5179cfedbad257fe87d27a19283a076b4cf0876a0347c52149

**Comment by dduportal** [comment]
Status update: https://github.com/jenkins-infra/status/pull/145

**Comment by lemeurherve** [comment]
Their [update page](https://github.com/cert-manager/website/pull/878/files#diff-dd9030c51aa11c5179cfedbad257fe87d27a19283a076b4cf0876a0347c52149) has a command to verify our certificates:

```bash
$ kubectl get cert -A -ojson | jq -r \
  '.items[] | select(.spec.privateKey.rotationPolicy | . != "Always" and . != "Never") | "\(.metadata.name) in namespace \(.metadata.namespace) has rotationPolicy=\(.spec.privateKey.rotationPolicy)"'

accounts-tls in namespace accountapp has rotationPolicy=null
grafana-cert in namespace grafana has rotationPolicy=null
incrementals-tls in namespace incrementals-publisher has rotationPolicy=null
javadoc-tls in namespace javadoc has rotationPolicy=null
weekly.ci.jenkins.io-cert in namespace jenkins-weekly has rotationPolicy=null
jenkins-wiki-exporter-tls in namespace jenkins-wiki-exporter has rotationPolicy=null
jenkinsio-tls in namespace jenkinsio has rotationPolicy=null
keycloak-cert in namespace keycloak has rotationPolicy=null
ldap-tls in namespace ldap has rotationPolicy=null
mirrorbits-tls in namespace mirrorbits has rotationPolicy=null
plugin-site-issues-tls in namespace plugin-site has rotationPolicy=null
plugins-tls in namespace plugin-site has rotationPolicy=null
rating-tls in namespace rating has rotationPolicy=null
release.ci.jenkins.io-cert in namespace release has rotationPolicy=null
reports-tls in namespace reports has rotationPolicy=null
uplink-tls in namespace uplink has rotationPolicy=null
wiki-tls in namespace wiki has rotationPolicy=null
```

Patch to apply to our certificate CRDs:
```yaml
spec:
  privateKey:
	rotationPolicy: Always
```

**Comment by lemeurherve** [comment]
We also needed to patch the following CRDs to set `spec.preserveUnknownFields` from `true` to `false`:
- challenges.acme.cert-manager.io
- clusterissuers.cert-manager.io
- issuers.cert-manager.io

<details>
<summary>Error log indicating the need for this change</summary>

> Error: UPGRADE FAILED: release cert-manager failed, and has been rolled back due to atomic being set: cannot patch “[challenges.acme.cert-manager.io](http://challenges.acme.cert-manager.io/)” with kind CustomResourceDefinition: [CustomResourceDefinition.apiextensions.k8s.io](http://customresourcedefinition.apiextensions.k8s.io/) “[challenges.acme.cert-manager.io](http://challenges.acme.cert-manager.io/)” is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch “[clusterissuers.cert-manager.io](http://clusterissuers.cert-manager.io/)” with kind CustomResourceDefinition: [CustomResourceDefinition.apiextensions.k8s.io](http://customresourcedefinition.apiextensions.k8s.io/) “[clusterissuers.cert-manager.io](http://clusterissuers.cert-manager.io/)” is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema && cannot patch “[issuers.cert-manager.io](http://issuers.cert-manager.io/)” with kind CustomResourceDefinition: [CustomResourceDefinition.apiextensions.k8s.io](http://customresourcedefinition.apiextensions.k8s.io/) “[issuers.cert-manager.io](http://issuers.cert-manager.io/)” is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema


</details>
