### ISSUE TITLE
ci.jenkins.io is down for maintenance

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2878]
### Service(s)

ci.jenkins.io

### Summary

Heyo,

it appears that ci.jenkins.io is either offline or not accessible. My Jenkinsfile tasks are not firing up 👀 
https://isdown.me/ci.jenkins.io would confirm that.
I didn't find something on the infra or dev mailing list, hence I'm posting this here, is there a maintenance I'm not aware of?
Thanks in advance for investigating!

**Comment by lemeurherve** [comment]
Hello @NotMyFault yes it's normal, ci.jenkins.io is down for maintenance, announced on IRC only though.

**Comment by NotMyFault** [comment]
Oic, thanks for the clarification, I don't really check in there.

**Comment by lemeurherve** [comment]
@NotMyFault ci.jenkins.io is back online, closing this issue.

**Comment by NotMyFault** [comment]
On a different note, did you (the infra team) ever consider to bridge the IRC channels to matrix/gitter?
The jenkinsci org for example hosts and bridges [79 channels with almost ~10k members](https://gitter.im/jenkinsci/home), for a lot of different plugins, SIGs and topics,
where infra does only host [two](https://gitter.im/jenkins-infra) barely used ones.

These would likely draw more attention on recent events and announcements, considering the vast amount of people already using the regular channels on jenkinsci.

**Comment by dduportal** [comment]
> On a different note, did you (the infra team) ever consider to bridge the IRC channels to matrix/gitter? The jenkinsci org for example hosts and bridges [79 channels with almost ~10k members](https://gitter.im/jenkinsci/home), for a lot of different plugins, SIGs and topics, where infra does only host [two](https://gitter.im/jenkins-infra) barely used ones.
> 
> These would likely draw more attention on recent events and announcements, considering the vast amount of people already using the regular channels on jenkinsci.

@NotMyFault that sound a wonderful idea!
Would you be willing to open an helpdesk issue, so the team can track the work on it as a separate item?

**Comment by NotMyFault** [comment]
> Would you be willing to open an helpdesk issue, so the team can track the work on it as a separate item?

Can do so and elaborate a bit on it 👍🏻

**Comment by dduportal** [comment]
Sorry for the inconvenience: I 'm the culprit whom forgot to update status.jenkins.io + send an email to the mailing list earlier today.
