### ISSUE TITLE
Bridge IRC channels to matrix/gitter

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2879]
### Service(s)

Other

### Summary

(Picking up the conversation from https://github.com/jenkins-infra/helpdesk/issues/2878#issuecomment-1096705075)

The infra team does currently host three IRC channels on Libera according to the [documentation](https://www.jenkins.io/chat/#jenkins-infra).
I'd like to ask if it is possible to bridge these IRC channels to matrix/gitter.
The jenkinsci organization for example hosts and bridges [79 channels with almost ~10k members](https://gitter.im/jenkinsci/home), for a lot of different plugins, SIGs and topics, where infra does only host [two](https://gitter.im/jenkins-infra) barely used ones.

Having the infra channels on gitter, whether on jenkinsci or more appropriately, jenkins-infra, will likely draw more attention on recent events, announcements and more, considering the vast amount of people already using the regular channels on jenkinsci.

**Comment by halkeye** [comment]
you can use the irc bridge to connect to infra which is what most of us use, the other channel is pretty quiet. I kinda think infra should just move to gitter (gitter people can't join matrix rooms, but matrix people can join gitter rooms)

**Comment by dduportal** [comment]
> Not gitter for infra please it’s horrid, if we move would prefer matrix

through matrix, it is quite acceptable.

Gitter is practical because you can access it in "read" without requiring an account (not sure if IRC allows this?).

**Comment by NotMyFault** [comment]
> Not gitter for infra please it’s horrid, if we move would prefer matrix

Matrix bridged would work out, iirc https://gitter.im/jenkinsci/jenkins is bridged from matrix too?

> Gitter is practical because you can access it in "read" without requiring an account

Gitter-bridges are also practical, because you can use them on the fly without any prerequisites.

**Comment by halkeye** [comment]
> Matrix bridged would work out, iirc https://gitter.im/jenkinsci/jenkins is bridged from matrix too?

~Matrix users can join gitter rooms (Gitter is a matrix server now, just different ui). So no bridging there. ~

you can use the librechat appservice to join irc rooms, then its transparent to you. you can message `@appservice:libera.chat` `!join #jenkis-infra` but it might require creating a nickserv account.

~The problem is that gitter rooms are not true matrix rooms. My matrix user can't be added as a room admin (Also there's a concept of gitter community admins, and I have no idea who that might be, probably oleg, maybe rtyler). So a its not a~

Okay. i totally misundertood how things work, gitter rooms are not matrix rooms, that makes more sense.

![image](https://user-images.githubusercontent.com/110087/163244632-3984d5a6-e2af-4b73-9e9a-acede4b725c8.png)

I can take care of this, and get a new matrix room setup for jenkins-infra, but i'm not sure its worth bridging irc, how many people would still use irc over matrix?

**Comment by olblak** [comment]
> I can take care of this, and get a new matrix room setup for jenkins-infra, but i'm not sure its worth bridging irc, how many people would still use irc over matrix?

I guess if we get rid of jenkins-infra irc channel then what about the chatbot? 
I am not concerned that people would follow on Matrix or gitter

**Comment by halkeye** [comment]
Jenkins admin? Its in a dedicated jenkins-hosting channel, and I think we still want to find ways to get rid of it

**Comment by halkeye** [comment]
Or update the bot too speak matrix. It shouldn't be hard

**Comment by halkeye** [comment]
I've put in a request to gitter/matrix support about turning jenkins/jenkins-infra into a matrix channel. This way we can try out existing bridges and stuff.

**Comment by dduportal** [comment]
> > I can take care of this, and get a new matrix room setup for jenkins-infra, but i'm not sure its worth bridging irc, how many people would still use irc over matrix?
> 
> I guess if we get rid of jenkins-infra irc channel then what about the chatbot? I am not concerned that people would follow on Matrix or gitter

The bot is configured to use another IRC channel #jenkins-infra-notifications , no worries for #jenkins-infra to be migrated wherever it is needed. Two differents goals:

- One is for handling notifications (and the "bot" should be improved to provide different channels: RSS, Discourse, Gitter, etc.)
- One is for discussing and could easily be turned into a Gitter and/or a discourse room

**Comment by halkeye** [comment]
Re chatbot - Honestly if I can find the time to revisit https://community.jenkins.io/t/codify-github-access/799/4 it would pretty much remove the need for jenkins-admin from being around (I think). It would also mean i could start merging access requests when i'm not at a computer.

**Comment by NotMyFault** [comment]
Closing, as libera as discontinued their bridge services, and we've discouraged using IRC.
