### ISSUE TITLE
[plugin-site-issues] updatecli pls

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#2882]
### Service(s)

infra.ci.jenkins.io, Other

### Summary

Updatecli pls so i can tag a new release of the server, and it updates the chart, and deploys it via management.

semi related to 2880

### Reproduction steps

N/A

**Comment by dduportal** [comment]
- The PR https://github.com/jenkins-infra/kubernetes-management/pull/2228 was automatically triggered and bumped the helm chart to 0.1.3
- BUT this helm chart is not working: the default image tag is `0.2.0` while the current Docker image tag is `v0.2.0`.
- The PR https://github.com/jenkins-infra/helm-charts/pull/117 aims at fixing this issue by automatically tracking the docker image tag (and bump the chart) so full automation for you

**Comment by dduportal** [comment]
- PR for the helm-chart with fixed docker image tag: https://github.com/jenkins-infra/helm-charts/pull/118 (proof that automation is now working)

**Comment by dduportal** [comment]
- Should be fixed by https://github.com/jenkins-infra/kubernetes-management/pull/2235. Waiting for the deployment to happen to confirm that it is fixed and unblock.

**Comment by dduportal** [comment]
ok, the 2 last helm charts (0.1.3 and 0.1.4) are failing to install. Just disabled the kubernetes-management job and checking what is going wrong?

**Comment by halkeye** [comment]
Oh shoot I think I changed healthcheck url

Is it /info/healthcheck?

I started this project a year ago and did some upgrades 6 months ago

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/helm-charts/blob/main/charts/plugin-site-issues/templates/deployment.yaml#L42 needs to be updated if you can (or I will during day)

**Comment by dduportal** [comment]
Many thanks @lemeurherve  \o/

https://github.com/jenkins-infra/kubernetes-management/pull/2237 => should deploy to production (monitoring)
