### ISSUE TITLE
(April 2022) Update VPN CRL

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2885]
The Jenkins Infra calendar reminds us that the VPN CRL expires the 5th of May 2022 (ref. https://github.com/jenkins-infra/helpdesk/issues/2669#issuecomment-1009707057).

Todo list for the team member who will take this action:

- [x] Read https://github.com/jenkins-infra/docker-openvpn#howto-review-certificate-revocation-list and check that you have all the pre-requisites
- [x] Open a PR to jenkins-infra/docker-openvpn that updates the CRL
- [x] Once the PR is merged, ensures that there is a new version of the container automatically built and released
- [x] Run manually the GitHub workflow for updatecli in jenkins-infra/jenkins-infra to open a PR for deploying the new Docker image to production
- [x] Once deployed, connect to the VPN VM and ensure that the new CRL is present and updated
- [x] Create a new team calendar event to the date of the next expiration, with alerts 3 weeks before and 2 weeks before

**Comment by smerle33** [comment]
to get next update date : 
```console
openssl crl -in ./cert/pki/crl.pem -noout -text
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /CN=vpn.jenkins.io
        Last Update: Apr 25 14:44:13 2022 GMT
        Next Update: Oct 22 14:44:13 2022 GMT
```
