### ISSUE TITLE
ci.jenkins.io does no longer accept new builds

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2894]
### Service(s)

ci.jenkins.io

### Summary

Originally observed this in https://github.com/jenkinsci/jenkins/pull/6500, there are no new builds running on ci.jenkins.io, repository scanning didn't run either: https://ci.jenkins.io/job/Core/job/jenkins/view/change-requests/
Is there a maintenance I'm not aware of?
Thanks for investigating!

**Comment by dduportal** [comment]
Related to https://github.com/jenkins-infra/helpdesk/issues/2893 for info.

**Comment by dduportal** [comment]
ci.jenkins.io is in poor state :( 

Had to trigger manually a job to start the core PRs again. Le'ts see how it behaves.

For info, we will operate the Kubernetes configurations on this instance later today, that should help.

**Comment by dduportal** [comment]
@NotMyFault can you confirm that the core jobds are currently running as expected?

**Comment by NotMyFault** [comment]
> @NotMyFault can you confirm that the core jobds are currently running as expected?

Yes, PRs are currently building again

**Comment by dduportal** [comment]
Thanks for checking. Sorry for the inconvenience, we'll update the issues later after the operations.

**Comment by dduportal** [comment]
Closing: follows up in #2893 to ensure a single communication thread.

Please note that status.jenkins.io mentions is updated to mention the issue.
