### ISSUE TITLE
CNAME record for jenkins.crowdin.com

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2895]
### Service(s)

Other

### Summary

Crowdin is our new translation integration we've been experimenting with in past docs office hours.
Things are going to get settled now and Crowdin has sponsored the jenkinsci organization an open source license and hosts our enterprise instance on https://jenkins.crowdin.com.

I would like to ask if we can have a CNAME record for jenkins.io to use `crowdin.jenkins.io` pointing to `org.cname.crowdin.com` for our Crowdin instance?

![](https://i.imgur.com/dZ2j64G.png)

Thanks in advance!

**Comment by dduportal** [comment]
Hello @NotMyFault . The CNAME record has been created:

```console
$ dig crowdin.jenkins.io

; <<>> DiG 9.10.6 <<>> crowdin.jenkins.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5613
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;crowdin.jenkins.io.            IN      A

;; ANSWER SECTION:
crowdin.jenkins.io.     3600    IN      CNAME   org.cname.crowdin.com.
org.cname.crowdin.com.  300     IN      A       3.94.66.77

;; Query time: 72 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Fri Apr 22 11:14:52 CEST 2022
;; MSG SIZE  rcvd: 98
```


<img width="1413" alt="Capture d’écran 2022-04-22 à 11 14 42" src="https://user-images.githubusercontent.com/1522731/164676180-df6c8bc9-4f57-4b4e-8009-6340f1544d3b.png">


Let us know if it works as expected.

Many thanks for the contributions you are doing!

**Comment by NotMyFault** [comment]
Thanks very much, the record works 👏🏻
