### ISSUE TITLE
Jenkins Service failing to start with LSB error

### ISSUE THREAD

**Issue by thangarajbluescape** [jenkins-infra/helpdesk#2896]
### Service(s)

AWS

### Summary

Similar to this issue. https://issues.jenkins.io/browse/JENKINS-67487?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by dduportal** [comment]
Hi, thanks for opening an issue.

this issue tracker is only for the jenkins public infrastructure.

you should open a thread on the forum at community.jenkins.io and provide details on what you expect.
