### ISSUE TITLE
HTTP error 503 in pipeline steps reference

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkins-infra/helpdesk#2899]
### Service(s)

Other

### Summary

<https://www.jenkins.io/doc/pipeline/steps/> fails and responds "Error 503 No healthy IP available for the backend".

### Reproduction steps

1. Navigate to <https://www.jenkins.io/doc/pipeline/steps/> with a web browser.
2. See the Error 503 message.

**Comment by KalleOlaviNiemitalo** [comment]
Also happens with curl:

```
$ curl --include https://www.jenkins.io/doc/pipeline/steps/
HTTP/2 503
server: Varnish
retry-after: 0
content-type: text/html; charset=utf-8
accept-ranges: bytes
date: Mon, 25 Apr 2022 11:17:47 GMT
via: 1.1 varnish
x-served-by: cache-hel1410027-HEL
x-cache: MISS
x-cache-hits: 0
x-timer: S1650885468.636644,VS0,VE0
x-frame-options: DENY
strict-transport-security: max-age=86400; includeSubDomains; preload
x-content-type-options: nosniff
content-length: 514


<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 No healthy IP available for the backend</title>
  </head>
  <body>
    <h1>Error 503 No healthy IP available for the backend</h1>
    <p>No healthy IP available for the backend</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-hel1410021-HEL 1650885468 1826925335</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by dduportal** [comment]
Thanks for reporting!

On first sight, I can't reproduce (from a Belgium ISP, neither on my French coud provider).
The incident might be self-solved (since it has been an hour); can you tell us if it is still failing for you please?

We are currently going to check the fastly service (which is responsible of this error message) to see if something happenes or if their monitoring was able to catch this annoying problem.

**Comment by dduportal** [comment]
I confirm that there was some issues on Fastly's side:

<img width="1053" alt="Capture d’écran 2022-04-25 à 14 31 22" src="https://user-images.githubusercontent.com/1522731/165089480-47fa70f0-0ca3-471f-ae9b-911a50897102.png">
<img width="1063" alt="Capture d’écran 2022-04-25 à 14 31 28" src="https://user-images.githubusercontent.com/1522731/165089486-d5c9695a-1731-4cab-b1a3-2aac788fbb5b.png">

**Comment by timja** [comment]
FWIW our renovate PR had failures on update center json as well, may be the same issue:
https://github.com/hmcts/cnp-jenkins-docker/runs/6155537509?check_suite_focus=true

**Comment by KalleOlaviNiemitalo** [comment]
yes it's working now.

**Comment by dduportal** [comment]
Many thanks @KalleOlaviNiemitalo for confirming so fast!

On the Jenkins infrastructure side, I confirm that there was no server-side error, for the website jenkins.io, on the "reference origin" (which is only available to Fastly).

The healthcheck probes of our datadog where able to join the ("reference origin") website in this interval, so it looks more and more an issue on Fastly.

https://status.fastly.com/ does not show anything though.

**Comment by dduportal** [comment]
> If this ever recurs, then maybe I should try adding a [Fastly-Debug header](https://developer.fastly.com/reference/http/http-headers/Fastly-Debug/) to the request.

Awesome, did not kno about this. Yes, that would be a good pointer if it happens again, to ensure where is the issue coming from.

**Comment by dduportal** [comment]
Gotta close since it seems solved. Don't hesitate to reopen with timestamps if it happens again.

**Comment by KalleOlaviNiemitalo** [comment]
The `date` header field in the HTTP response shown by `curl` would be a sufficient timestamp, I hope.
