### ISSUE TITLE
Mirror in Singapore

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2901]
From https://groups.google.com/g/jenkins-infra/c/H4qs8TVQ0sY/m/zy8xOFXHAQAJ

> Hello
> I'm the admin of [mirror.freedif.org](http://mirror.freedif.org/), mirroring several opensources projects like LibreOffice, KDE, LinuxMint,...
> 
> I have some spare bandwidth and space in Singapore (1GBPS) and I would be pleased to offer support to Jenkins to serve Singapore and nearby countries (East Asia)
> 
> If this will support the project, please let me know
> 
> Thank you
> Kari

**Comment by dduportal** [comment]
Wrote a piece of runbook (private repo: https://github.com/jenkins-infra/runbooks/pull/55) to aggregate the information and requirements.

I'm gotta share these requirement in the email thread.

**Comment by dduportal** [comment]
requirements shared with them in the email thread. Let's wait for them.

**Comment by dduportal** [comment]
Closing as we never received any information back from requester.

Feel free to reopen if we got any.

**Comment by karibuTW** [comment]
Hello guys,
We have upgraded our mirror and are now able to take on new project and we would be glad to support Jenkins with a mirror in Singapore

https://mirror.freedif.org/jenkins/
rsync://mirror.freedif.org/jenkins/
Bandwidth: 10GBPS
Location: SG
Admin: karibu at freedif.org
The source is the TUNA mirror.

Let me know if you require additional information

Thank you

**Comment by karibuTW** [comment]
Thank you
I'm starting to receive some traffic, so I believe it is all good now.
Thanks

**Comment by MarkEWaite** [comment]
> Thank you I'm starting to receive some traffic, so I believe it is all good now. Thanks

Confirmed by https://get.jenkins.io/war/2.449/jenkins.war?mirrorlist as well.  It shows that freedif.org is physically within a few km of Servana.  That will provide a very nice load balancing to users in Asia.  Thanks very much!

**Comment by lemeurherve** [comment]
> I'm starting to receive some traffic, so I believe it is all good now.

Already half a tera since midnight indeed:

https://get.jenkins.io/index.html?mirrorstats
<img width="600" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/4998e231-a153-4486-ae6e-9c04ec1bfbe7">

Closing this issue, thanks again for providing a mirror!
