### ISSUE TITLE
Add contributor to jenkinsci/sideex-plugin

### ISSUE THREAD

**Issue by kiam123** [jenkins-infra/helpdesk#2902]
### GitHub repositories

https://github.com/jenkinsci/sideex-plugin

### GitHub users to have permission

@bobcode99

### Permission level

Maintain

### Justification

@bobcode99 is a new member of the team, he needs to join the project to fix a bug

**Comment by timja** [comment]
Done

**Comment by timja** [comment]
Make sure he accepts the invite at https://github.com/jenkinsci
