### ISSUE TITLE
[Datadog] Depreciation of @oncall-* handles in monitors

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2905]
@MarkEWaite and I receieved an email from Datadog about the depreciation of the "oncall" handles in datadog monitors:

> Hello,
> 
> We are reaching out to you because you are an admin user of the jenkins Datadog account and this account has monitors configured that are using the @oncall-* handles which will be deprecated soon.
> 
> **What is the change?**
> 
> A long time ago, the @oncall-* handles were introduced when proper on-call management tooling was still in the works. The existing tools at that time were not necessarily able to directly propagate an alert to whoever was on call at that time. This has changed in the past few years and we decided to deprecate the @oncall-* handles, as the exact functionality is now officially supported by PagerDuty's solution offering.
> 
> Moving forward, you will still be able to insert your on-call schedules in the PagerDuty configuration within Datadog in order to ingest on-call related events to your Events Stream, however, using any variation of the @oncall-* handle will have no more impact when your monitor alerts.
> 
> **List of impacted monitors**
> 
> The list of monitor IDs that are impacted by the change: <redacted>
> 
> **What you need to do**
> 
> There are two solutions you can use if you want to keep alerting individuals that are on call:
> 
> 1.Leverage the existing Datadog and PagerDuty integration and use PagerDuty Services to route alerts from Datadog to different responders. Refer to this [guide](https://www.pagerduty.com/docs/guides/datadog-integration-guide/) on how to get started! 
> 2.Another solution is to leverage PagerDuty Escalation Policies in order to automate incident assignment and connect services to individual users and/or schedules. Visit PagerDuty's [guide](https://support.pagerduty.com/docs/escalation-policies#escalation-targets) to get started with Escalation Policies.
> 
> **What the @oncall-* handle does in monitors**
> 
> Datadog provides a PagerDuty integration that, among others, allows its users to connect to their PagerDuty accounts and gain the ability to know who is currently on-call. You can add PagerDuty on-call schedules in the PagerDuty integration within Datadog:
> 
> Once the integration is configured, your event stream will receive events corresponding to your on-call schedules, including the name / email of the individuals currently attending on-call duty.
> 
> ![image](https://user-images.githubusercontent.com/91831478/168579986-30e82796-3b5c-4b31-ad86-f11d16454fd8.png)
> 
> When adding @ handles to your monitors, you will find these schedules with their respective names:
> 
> ![image](https://user-images.githubusercontent.com/91831478/168580056-207b9e17-6401-42f3-84c0-393b20f24d8e.png)
> 
> The shown handles correspond each to one of the listed schedules in the PagerDuty configuration. After selecting an @oncall-* handle, your monitor will either:
> 
> notify anyone who is currently doing an on-call duty (@oncall)
> 
> notify the person who is currently on-call for the given schedule (@oncall-scheduleName)
> 
> **What happens if you don’t do anything**
> 
> If you do not change anything by May 9th, the @oncall-* handles will have no more impact on the notification behavior of your monitors. This will affect you especially if the only handle that is used in your monitors are @oncall-* handles, as you will stop receiving any alerts for those monitors.
> 
If you have any questions, please respond to this email or reach out to our support team by visiting [help.datadoghq.com](http://help.datadoghq.com/).

We currently have the following references in the terraform-managed datadog configuration of ours:

- https://github.com/jenkins-infra/datadog/blob/eadde46cd74b9faa67f7abbf74f2e5940726bf8d/datadog-monitors.tf#L52 (monitor `jenkins_dns`)
- https://github.com/jenkins-infra/datadog/blob/eadde46cd74b9faa67f7abbf74f2e5940726bf8d/datadog-monitors.tf#L78 (monitor `ssl_certificate_expiration`)
- https://github.com/jenkins-infra/datadog/blob/eadde46cd74b9faa67f7abbf74f2e5940726bf8d/datadog-monitors.tf#L109 (monitors `weird_response_time`)

**Comment by lemeurherve** [comment]
There is a resource dedicated to the integration of PagerDuty and Datadog: https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/integration_pagerduty_service_object

@dduportal I'll need access to PagerDuty in order to setup this integration.

**Comment by lemeurherve** [comment]
PagerDuty access OK.

It seems the PageDuty/Datadog integration isn't free, cf "start free trial / request a demo" on https://www.pagerduty.com/integrations/datadog/

**Comment by lemeurherve** [comment]
On the Datadog side there already is an active PagerDuty integration, I need to check if we can use it as it is or not.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/91831478/168832530-115e3d9a-ddac-4377-87b6-d752dfbcfeb6.png">

**Comment by lemeurherve** [comment]
Removing the `@oncall` handles from Datadog, as the other existing `@pagerduty` handles seem to work as expected.

**Comment by dduportal** [comment]
Confirm that it works as expected 🥳
