### ISSUE TITLE
Plugin not released

### ISSUE THREAD

**Issue by ayushk048-Ajmera** [jenkins-infra/helpdesk#2906]
### Service(s)

release.ci.jenkins.io

### Summary

Our https://github.com/jenkins-infra/repository-permissions-updater/issues/2457 issue closed and the repository get cloned https://github.com/jenkinsci/pipeline-reporter-by-redpen-plugin by Jenkins 

But, As I asked questions in Community https://community.jenkins.io/t/our-plugin-code-has-been-forked-by-jenkinsci/2279/4
Our plugin release job is not showing in https://ci.jenkins.io/job/Plugins/ is there any remaining task left then let us know.

Note:
we have already done
- [Incrementals Enablement](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#incrementals-enablement)
- [Enable CD Permissions](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#enable-cd-permissions)
- [Update Maven POM and Config](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#update-maven-pom-and-config)

**Comment by timja** [comment]
I ran an organisation scan and it's now here:
https://ci.jenkins.io/job/Plugins/job/pipeline-reporter-by-redpen-plugin/
