### ISSUE TITLE
[Datadog] Add new monitoring probe for the WebUI of repo.jenkins-ci.org

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2907]
Ref. https://github.com/jenkins-infra/helpdesk/issues/2904

> Add new monitoring probe for the WebUI on datadog, because we missed this and we relied on end users to notify us. Only the "artifcats" downloads is monitored today

**Comment by smerle33** [comment]
The PR datadog #74 did create the test but this one stay in status = passed even with a 503 returned error code need to investigate ...

**Comment by dduportal** [comment]
While working on this, @smerle33 caught that the actual synthetics tests (with the type "browser") are not behaving as expected: while the [JFrog incident](#2923) was still happenning, the test was not failing (while it was when set to the type "api").

Opened the issue #2923, blocking this one, to fix all the monitors.
