### ISSUE TITLE
[release.ci.jenkins.io] failed weekly release 2.346 because of expired Azure SP

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2910]
### Service(s)

release.ci.jenkins.io

### Summary

The weekly release 2.346 initially failed because of an expired Azure service principal:

```
ERROR: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys for app **** are expired. Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: [https://aka.ms/certCreds.\r\nTrace](https://aka.ms/certCreds./r/nTrace) <... redacted...>
```

This service principal is used to retrieve the GPG key from the Azure vault: can not sign the release.

ToDO:

- [x] Create a new secret for this SP in azure (add it to terraform IaC?)
- [x] Load this secret in release.ci
- [x] Re-trigger the release

**Comment by dduportal** [comment]
- Added this SP under IaC terraform but in the private repo (instead of jenkins-infra/azure because it's sensitive) - https://github.com/jenkins-infra/terraform-states/commit/f18fecf36d96c6a23e47e7ce5d129f05bec8f233
- Rotated Credential
- Updated the kubernetes secret for release.ci
- Merged https://github.com/jenkins-infra/kubernetes-management/pull/2319 to ensure that credential is updated (to allow triggerring the release)

**Comment by dduportal** [comment]
@timja @MarkEWaite Can I let you take over to re-trigger the release?

**Comment by MarkEWaite** [comment]
Yes, I'll trigger the release.  Thanks @dduportal

**Comment by smerle33** [comment]
can be seen on docker hub : https://hub.docker.com/layers/jenkins/jenkins/jenkins/2.346-jdk11/images/sha256-f22ded8516f3876406ef34cbb5b6bd4ab82d224f01d47843c969fbc98ec3a985?context=explore

**Comment by dduportal** [comment]
Image is now available: https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=2.346

(Some tags were pushed 13 hours ago, some other 3 hours ago).
