### ISSUE TITLE
Grant access to Basil Crow (@basil) to ci.jenkins.io and associated resources

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2911]
After #2893 and #2908, and as discussed and acknowledged by vote during the infra weekly meetings,

we want to give @basil access to the ci.jenkins.io system to help us diagnosing issues causing the outages or performance problems.

ToDo list:

- [x] Add SSH public key to the `azure.ci.jenkins.io` machine. @basil can you open a PR to https://github.com/jenkins-infra/jenkins-infra/blob/6df5dbba8753de8ae1a6722d6d6cace432b50bab/hieradata/clients/azure.ci.jenkins.io.yaml#L1-L13 specifying an SSH RSA public key (4096)? Please note that the user ID must be the same one as your Jenkins account ID on accounts.jenkins.io or issues.jenkins.io - https://github.com/jenkins-infra/jenkins-infra/pull/2144
- [x] Add @basil to the "jenkins-admin" group on admin.accounts.jenkins.io (Keycloak private backend) to that he can access ci.jenkins.io as administrator
- [x] Add @basil to the (private) repository jenkins-infra/runbooks
- [x] VPN access: @basil can you follow the instruction at https://github.com/jenkins-infra/docker-openvpn#howto-get-client-access to request a VPN access please?  - https://github.com/jenkins-infra/docker-openvpn/pull/167

**Comment by timja** [comment]
and VPN? for SSH access to ci.jenkins.io

**Comment by dduportal** [comment]
> and VPN? for SSH access to ci.jenkins.io

Good catch, github did not took my edit in account 😱

**Comment by dduportal** [comment]
Access granted to ci.jenkins (SSH), VPN and the repository jenkins-infra/runbooks.

I'll add you to the LDAP group "jenkins-admin" tomorrow.

@basil you can try the SSH connection for ci.jenkins.io by following the runbook at https://github.com/jenkins-infra/runbooks/tree/main/ci#access-the-instance

**Comment by basil** [comment]
Thanks Damien, I logged on to the VPN successfully and can access the box at http://10.0.2.4:8080 over the VPN. I get `basil@10.0.2.4: Permission denied (publickey)` when trying to SSH in. I verified the permissions on my `.ssh` directory, private key, and public key are correct. I also verified that the public key matches what I submitted in https://github.com/jenkins-infra/jenkins-infra/pull/2144 and that `ssh -vvv` didn't have anything unusual. Is it possible https://github.com/jenkins-infra/jenkins-infra/pull/2144 has not yet been deployed?

**Comment by timja** [comment]
@basil it's been deployed

This is the contents of your `authorized_keys` file:

```
timja@ci:~$ sudo cat /home/basil/.ssh/authorized_keys
# HEADER: This file was autogenerated at 2022-05-03 16:11:33 +0000
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkR0yiRuFiY82o1IUyglIFAGLlkqXfuIv/zGU8x/BWvjHBUetM4LLdVTT21lagee85wSKEPEhwBHd0NpSKZQj/iXlhHt5IQQAt0ZKuJYNHtbIUXPEue4bpHssn58tNsbtIvgEKoLkbqkjRbSTceT9yB8FLS9fYleFtwxera/1S7L8U0if9idfCibJhmxI91K+lKT+PMvQ3SS/9KGlOae0t9UfN+TT2YKLWa74Pi4QYrATDny3F8+ad4xeW6Tzour9yVWEXbXab1u7yXZcBwpQpCPMc9xSuP8/gomRum5Cw2M1dKSGi7UX7K03hWPr7F68zIQ8CkD/NZyJDj9R4QxTEDRINYpAznig8GRklbECvBLE5nenQ7hT6vTv7cWf0JBotrpoGOJHcK2vcEjDPu9nhtsB+sZp/BvTiFLvZSmNDgkrNOHRZaI5dbREkgBJrYYsFnfJNf7/+6BrbKpBa4rRHl7OfYnlLrcw7xWR8XZeKA8y80521oPpm7XMDij/yNbAqxWpxJfukbHIM7ouUo2mV+FsuSpkDh8w9ab5F4HkJs3jlMRtrYy0IV0HKPFZ57ILGUpHTdod1rwvUnF7/MeX3I2lqS56YbzCYpnhBsJ41Hai07V7GVa7cFaRUNWgHRtu2GN/rg7RaFFdCBRSxY6B2qyyJEWt7mNj5mXSm37JO8Q basil-basil
```

**Comment by timja** [comment]
Auth logs just say your client closed the connection:

```
May  3 18:02:27 ci sshd[22549]: Connection closed by authenticating user basil 10.0.2.253 port 36320 [preauth]
May  3 18:04:33 ci sshd[23244]: Connection closed by authenticating user basil 10.0.2.253 port 36338 [preauth]
May  3 18:04:37 ci sshd[23257]: Connection closed by authenticating user basil 10.0.2.253 port 36340 [preauth]
```

**Comment by timja** [comment]
> I'll add you to the LDAP group "jenkins-admin" tomorrow.

I tried to do this via keycloak but it seems to be broken

**Comment by basil** [comment]
> This is the contents of your `authorized_keys` file

Thanks, I compared this to my local public key file and see that it is missing two equals signs at the end. I filed https://github.com/jenkins-infra/jenkins-infra/pull/2146 to fix that.

**Comment by timja** [comment]
Try now

**Comment by basil** [comment]
Thanks, I was able to SSH in successfully now.

**Comment by timja** [comment]
I've added you to the jenkins-admins group @basil

**Comment by dduportal** [comment]
Many thanks @timja for taking care of missing/not working elements (+ opening the issue about keycloak)!

Closing the issue as it seems ok on all sub tasks.
