### ISSUE TITLE
Missing permission on release.ci

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2913]
### Service(s)

release.ci.jenkins.io

### Summary

I'm preparing the release of 2.332.3 at the moment and was heading forward to trigger the release job on release.ci.
I'm logged in and can access the job fine, but I can't trigger a build, the build trigger icon isn't there. I'm likely lacking some permission, I guess?
Thanks in advance!

**Comment by timja** [comment]
I tried to update but keycloak is failing with:

```
Caused by: javax.naming.CommunicationException: ldap.jenkins.io:636 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
```

**Comment by timja** [comment]
I manually added `52.177.88.13/32` to the ldap service but that hasn't seemed to have helped it just hangs.

**Comment by timja** [comment]
@NotMyFault I've manually added you in temporarily to the release.ci config

**Comment by timja** [comment]
Keycloak responded eventually, but terribly slowly.

I've added you to the group and removed the manual entry in the Jenkins config

Can you please verify?

**Comment by NotMyFault** [comment]
> Can you please verify?

Yup, all there, thanks a lot.
