### ISSUE TITLE
Update ci instances to LTS 2.332.3

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2916]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

Heyo,

I triggered the release job a few hours ago everything is released fine so far. We're good to go to update to 2.332.3

**Comment by dduportal** [comment]
- Puppet configuration (trusted.ci and cert.ci):
  - [x] https://github.com/jenkins-infra/jenkins-infra/pull/2155#pullrequestreview-962210823
- [ ] Restart service `docker` on ci.jenkins.io to apply release
- Docker LTS image for release.ci: 
  - [x] PR to bump core version: https://github.com/jenkins-infra/docker-jenkins-lts/pull/478
  - [ ] Version release
  - [ ] PR for Kubernetes Management

**Comment by dduportal** [comment]
LTS deployed everywhere. Many thanks @NotMyFault for handling this!
