### ISSUE TITLE
[ci.jenkins.io] Digital Ocean sponsorship runs out of credits: stopping the cluster

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2917]
### Service(s)

ci.jenkins.io, Digital Ocean

### Summary

As underlined in the blog post https://www.jenkins.io/blog/2022/05/04/DigitalOcean/, Digital Ocean gaves 2760$ of credits as part of the sponsorship.

As for today, 05 of May 2022, only 178.62$ remains. It means that we are going to remove the cluster from ci.jenkins.io and we will contact Digital Ocean to see if they would be willing to reiterate the sponsorship or even grow it.

**Comment by dduportal** [comment]
PR https://github.com/jenkins-infra/jenkins-infra/pull/2159 to remove the cluster from ci.jenkins.io.

**Comment by dduportal** [comment]
As per the weekly meeting of the 10th of May: @lemeurherve to contact back Digital Ocean to give them a feedback, tell them that we consumed almost all the credit, and that we are asking if they want to continue and eventually increase the sponsoring.

**Comment by dduportal** [comment]
Email sent to DigitalOcean to ask if they are interested into renweing the sponsorship.

**Comment by dduportal** [comment]
Received an answer: we'll meet with them to discuss with them soon: goal is to evaluate what we need, what we would ask and what they want to hear from us.

**Comment by dduportal** [comment]
Meeting the 13th of June at 15h00 UTC with @lemeurherve , I and people at DigitalOcean \o/

**Comment by dduportal** [comment]
Meeting moved Tuesday the 14th of June, 16h30 UTC

**Comment by lemeurherve** [comment]
Preparation support for our meeting: https://hackmd.io/-MT_WwpbQkqVMyHK0qb_Pg?view

**Comment by dduportal** [comment]
- Digital Ocean agreed to renew the sponsor
- We have another wave of credits already done, which let us 2-3 month of nominal usage of the Kubernetes cluster again.
- @lemeurherve is now driving the sponsorship with DigitalOcean.

**Comment by dduportal** [comment]
Closing this issue as @lemeurherve already enable back the DOKS cluster on ci.jenkins.io in https://github.com/jenkins-infra/digitalocean/pull/47 + https://github.com/jenkins-infra/jenkins-infra/pull/2223.

**Comment by lemeurherve** [comment]
FTR, tested with a replay in ci.jenkins.io:
```
pipeline {
  agent {
    label 'doks'
  }
  stages {
    stage('hello') {
      steps {
          // test doks (@lemeurherve)
          echo "Hello world!"
      }
    }
  }
}

```
