### ISSUE TITLE
Manage new Crowdin projects through helpdesk

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2918]
### Service(s)

Other

### Summary

Heyo,

during today's docs office hours, we spoke about using helpdesk to manage the creation of translation projects on crowdin.jenkins.io, because the initial creation of a new project can only be performed by administrators of our crowdin instance.

The proposed workflow is:
1. The plugin maintainer creates an issue on helpdesk, listing the GH repositories they want to add and the project maintainer(s), which should have management permissions for their project on crowdin.jenkins.io
2. The initial triage assigns the issue to a crowdin administrator, which are Mark and me (@NotMyFault) at the moment.
3. The assignee creates the project, adds the project maintainers listed, reports the result to the issue submitter and closes the issue.

Feel free to assign these issues to me for now, I'll happily assist in the first period. Though this list may vary in the future, if more people get familiar with the setup process.

I hope, this is something we can do through the helpdesk repository. I'll file a PR to provide the necessary changes to the issue templates.

**Comment by dduportal** [comment]
Hello @NotMyFault , many thanks for opening the issue + the PR.

That sounds legit and doable: we'll put this topic on the agenda of the next infra team meeting (tuesday 10th of May).
If accepted, then we'll be able to quickly apply/start the process.

**Comment by lemeurherve** [comment]
I understand the need of these requests for existing plugins, and here seems appropriate.
In the long term, shouldn't these requests to add Crowdin support to plugins be managed in RPU like the permissions or CD requests?

(Not sure how you add support to Crowdin with the requested informations, manually?)

**Comment by NotMyFault** [comment]
> I understand the need of these requests for existing plugins, and here seems appropriate. In the long term, shouldn't these requests to add Crowdin support to plugins be managed in RPU like the permissions or CD requests?

Yeah, that would be the best approach in the long run. Crowdin provides an extensive [API](https://support.crowdin.com/enterprise/api/) to work with.

> (Not sure how you add support to Crowdin with the requested informations, manually?)

At the moment, yes.

**Comment by lemeurherve** [comment]
> But if you mean the latter, yes please create a team

I've added you and @MarkEWaite as maintainers of the team https://github.com/orgs/jenkins-infra/teams/crowdin-admins/

You should receive shortly an invitation to join jenkins-infra org and this team.

> Yeah, that would be the best approach in the long run. Crowdin provides an extensive [API](https://support.crowdin.com/enterprise/api/) to work with.

Great! Don't hesitate to ask if you'll need help.

**Comment by NotMyFault** [comment]
> I've added you and @MarkEWaite as maintainers of the team https://github.com/orgs/jenkins-infra/teams/crowdin-admins/
> 
> You should receive shortly an invitation to join jenkins-infra org and this team.

Thanks, I'm in the team.
> 
> > > shouldn't these requests to add Crowdin support to plugins be managed in RPU like the permissions or CD requests?
> > 
> > 
> > Yeah, that would be the best approach in the long run. Crowdin provides an extensive [API](https://support.crowdin.com/enterprise/api/) to work with.
> 
> Great! Don't hesitate to ask if you'll need help.

I'm currently a bit short on time to work on it, but considering there is already an extensive  [API](https://support.crowdin.com/enterprise/api/) and [Java library](https://github.com/crowdin/crowdin-api-client-java) we can feed the RPU with, this shouldn't be an impossible task at all.
I'll look forward to create a feature request on the RPU repository later, providing the steps the RPU has to perform to create new crowdin projects. Basically, what Mark and I do by hand at the moment.

**Comment by lemeurherve** [comment]
I've added the team with "triage" permission on this repository so you're able to deal with these issues, as tested in https://github.com/jenkins-infra/helpdesk/issues/2927

Closing this issue as it should be good, don't hesitate to reopen it if needed.
