### ISSUE TITLE
[repo.jenkins-ci.org] Instance is down (UI down, backend unhealty)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2920]
### Service(s)

Artifactory

### Summary

As reported bu users, the instance repo.jenkins-ci.org is down.

Thanks @Wadeck @MarkEWaite for notifications!

Task list for now

- [x] Open incident on status.jenkins.io - https://github.com/jenkins-infra/status/pull/155
- [x] Communicate on the mailing list - https://groups.google.com/g/jenkinsci-dev/c/CTUyb8qK16U
- [x] Open support case at JFrog - (private email thread - https://groups.google.com/g/jenkins-infra-team/c/c9JColj2MTw)

<img width="2048" alt="Capture d’écran 2022-05-06 à 14 31 02" src="https://user-images.githubusercontent.com/1522731/167131899-4a6a7d3b-e30f-4057-962c-1dacce6c2f78.png">

Task list once JFrog fixed the issue:

- [x] Confirm with JFrog support that it works as expected
- [x] Communicate end of incident to the jenkins-dev mailing list
- [x] Close incident on status.jenkins.io

**Comment by dduportal** [comment]
Addon: the [JFrog status website (https://status.jfrog.io/)](https://status.jfrog.io/) reports a GCP (Google Compute Platform, their cloud provider) incident.

<img width="2048" alt="Capture d’écran 2022-05-06 à 14 30 52" src="https://user-images.githubusercontent.com/1522731/167131830-65ec785f-3d8d-4489-85ff-86f5a0b92b85.png">

**Comment by timja** [comment]
JFrog response:
> I have redeployed the instance to fix the issue and I believe the Artifactory should be up and running now. 

It's back now
