### ISSUE TITLE
Separate terraform backends & repositories: "Azure Net" and "Azure"

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2924]
### Service(s)

Azure

### Summary

(edited)
This issue tracks the work to have a separate Terraform project to manage the Azure network systems that are critical.
The goal is to limit the scope of anything going wrong in the Terraform Azure project.

This task is also the opportunity to create a new set of networks to solve the 2 following critical issues:

- IPv6 support for public access - https://github.com/jenkins-infra/helpdesk/issues/3227
- IPv4 overlapping issues on the current `prod-public` network (https://github.com/jenkins-infra/helpdesk/issues/3221#issuecomment-1305403066)

### Notes

azure-net:
- dns
- parent vnets

azure:
- cluster
- subnets in parent azure-net vnets

Separate azure accounts (and segregate permissions)
Separate terraform backends
Separate repositories

**Comment by dduportal** [comment]
Closing as https://github.com/jenkins-infra/azure-net is created, with pipeline and works as expected.
