### ISSUE TITLE
Weekly release build does not resume

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2925]
### Service(s)

release.ci.jenkins.io

### Summary

The weekly release build of Jenkins 2.347 was in progress when the Jenkins controller was restarted.  It did not resume after the Jenkins controller restarted.  The job log reported  that it was waiting to restart.

### Reproduction steps

1. Start the weekly build
2. Restart the Jenkins controller
3. Confirm that the job does not resume, no matter how long you wait

## Expected result

3. Jenkins Pipeline job should resume after controller restart, even with cloud agents

**Comment by dduportal** [comment]
Status: https://github.com/jenkins-infra/release/pull/283 should solve this issue.

**Comment by dduportal** [comment]
Update: https://github.com/jenkins-infra/release/pull/283 removes uncessary agents allocations that, as far as we can tell from our memories, was not resuming or at least confusing us in thinking builds were not resumed.

Please note that the release itself should not be resumed when crashed as stated in the PR:

- A controller restart should continue the process (to be validated during the next weekly). We might have to wait for https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180 to be merged and shipped (durable-workflow plugin) to fully cover the case of a controller image upgrade in Kubernetes (case that happens the most to the release process: a merge of a PR in the jenkins-infra/kubernetes-management updating the Jenkins LTS image)

- If there is a crash of any type during the maven deploy phase, which is not idempotent, then we expect a manual human operation (and not resuming).
