### ISSUE TITLE
repository for reusable workflows

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/helpdesk#2926]
### Service(s)

Github

### Summary

I would suggest we keep reusable workflows in a separate repository inside jenkins-infra

https://github.com/jenkins-infra/jenkins-maven-cd-action/issues/10#issuecomment-1123182079

If I could get write permissions I would setup the repository.

**Comment by timja** [comment]
what name?

**Comment by lemeurherve** [comment]
@jetersen  I've created the repository, set branch protections, and you as maintainer, you should receive an invitation shortly.

Let me know if you need anything else.
