### ISSUE TITLE
Artifactory is down

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/helpdesk#2933]
### Service(s)

Artifactory

### Summary

Seems https://repo.jenkins-ci.org/ui/ is down

and https://status.jfrog.io/ says everything is fine

### Reproduction steps

NA

**Comment by timja** [comment]
I've contacted jfrog although apparently I'm not a support contact anymore which might slow it down -.-

**Comment by lemeurherve** [comment]
Unfortunatelly @dduportal (OoO today) is the only one of us registered in their support system AFAIK.

**Comment by timja** [comment]
Support ticket has been picked up

**Comment by timja** [comment]
Resolved
