### ISSUE TITLE
Autonotifier

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2937]
### Service(s)

Helpdesk

### Summary

Another test issue

**Comment by lemeurherve** [comment]
@jenkins-infra/test-team test ping team (manually)

**Comment by timja** [comment]
You can probably run an action to expand a team or even pick someone from a team manually

**Comment by lemeurherve** [comment]
@timja another problem I'm facing is the labels applied by the autolabeler GHA don't trigger the autonotifer one. Any suggestion?

**Comment by timja** [comment]
can you do a workflow call from the autonotifer? or just add this action after it's auto labelled?

**Comment by timja** [comment]
GitHub actions 'actions' don't trigger extra events I think to prevent loops

**Comment by lemeurherve** [comment]
> GitHub actions 'actions' don't trigger extra events I think to prevent loops

That's also my reasoning.

> can you do a workflow call from the autonotifer?

I'm concerned by the fact the labeler seems to use unique label as input from events of type `[labeled]` (I might be wrong), will take a look.

>  or just add this action after it's auto labelled?

[I've tried it](https://github.com/jenkins-infra/helpdesk/blob/273cab49ee77bb0c4669e5152799d3984d0f59a7/.github/workflows/autolabels-and-notifs.yaml), but got [this error](https://github.com/jenkins-infra/helpdesk/actions/runs/2318155137):
`The issue-label-notification-action action failed with TypeError: Cannot read property 'name' of undefined`

**Comment by timja** [comment]
interesting =/
