### ISSUE TITLE
[JENKINS-51820] Archive JavaWebStart-related repositories

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#2939]
Now that https://github.com/jenkinsci/jenkins/pull/6543 has been merged we can archive https://github.com/jenkinsci/netx which was a patch just used to test JWS mode. Also we can archive all the `*slave-installer-module` repos since they implemented a system which only works in the agent GUI mode, which has been removed as part of removing JWS.

**Comment by lemeurherve** [comment]
Ping @jenkins-infra/jenkinsci-admins

**Comment by daniel-beck** [comment]
Done
