### ISSUE TITLE
Add an HTTP permanent redirect from https://jenkinsistheway.io to https://stories.jenkins.io/

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2943]
### Service(s)

Other

### Summary

As per https://github.com/jenkins-infra/jenkins.io/issues/5152, the actual links to https://jenkinsistheway.io are broken and should be HTTP-redirected to their equivalent in https://stories.jenkins.io/.

Proposal:
- [x] Create an ingress rule, in its own namespeace, in the cluster `prodpublick8s` that would emit an HTTP/308 (Permanent redirection - https://datatracker.ietf.org/doc/draft-ietf-httpbis-semantics/) to https://stories.jenkins.io/ 
  - Hint: annotation https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect
- [x] Set a CNAME DNS record to `public.aks.jenkins.io` for `jenkinsistheway.io`
  - Who owns jenkinsistheway.io? What DNS system is it? Can we transfer it to our Azure system?

Validation: https://jenkinsistheway.io/user-story/to-tackle-any-challenge/ should redirect to https://stories.jenkins.io/user-story/to-tackle-any-challenge/

**Comment by alyssat** [comment]
Mark and I configured the GoDaddy DNS to redirect from https://jenkinsistheway.io to https://stories.jenkins.io

Will need to wait for the DNS change to propagate to confirm this is complete.

**Comment by halkeye** [comment]
By pointing it directly at the new site you'll have an alias. Both URLs will work.

@smerle33 has setup a new tiny server that will redirect anyone using the old URLs to the new URLs.

Its a subtle difference but helps updating search results and stuff

**Comment by MarkEWaite** [comment]
The GoDaddy configuration said that it was going to reploy with HTTP 301, permanent redirect.  Isn't that the same effect as what was done with the tiny server?

Ultimately, we'll want to transfer ownership of the domain from GoDaddy to the Jenkins infra account, but that can wait a while longer.

**Comment by alyssat** [comment]
It's been 6 hrs since the DNS change. Doesn't look like the change has propagated. These links in Damien's summary https://jenkinsistheway.io/user-story/to-tackle-any-challenge/  and https://jenkinsistheway.io/  resulted in 'Safari Can't Open the Page'

**Comment by halkeye** [comment]
I did some poking around, looks like jenkinsistheway.io/ redirects to stories.jenkins.io/
but jenkinsistheway.io/thing doesn't goto stories.jenkins.io/thing

I think the infra version is better than godady

**Comment by dduportal** [comment]
For info, we ensured that the infra redirector (if used) would keep the URI/query string: https://github.com/jenkins-infra/kubernetes-management/pull/2414

**Comment by timja** [comment]
@dduportal @smerle33 

@alyssat and I updated godaddy and Azure.

It's now pointing to `public.aks.jenkins.io` which is working (I tested various redirect scenarios) but the certificate is invalid, cert manager will need some configuration to work for the zone I think.

I manually created the zone and DNS record as I couldn't see any IaC for it currently but possibly I missed it.

_Note: It's not possible to use a CNAME record because it's an Apex of the zone so I used an alias resource which links an A record to a resource in Azure (public IP in this case)._

**Comment by dduportal** [comment]
> jenkinsistheway.io is now pointing to public.aks.jenkins.io and the redirect is working 

oooh many thanks @timja for handkling this!

> I manually created the zone and DNS record as I couldn't see any IaC for it currently but possibly I missed it.

You did correctly and did not missed anything. I've just opened https://github.com/jenkins-infra/helpdesk/issues/2981 about re-importing former terraform definitions for azure in the IaC project. That would have been there but it's not the case (yet).

> but the certificate is invalid, cert manager will need some configuration to work for the zone I think.

We (infra team) forgot about the CertManager configuration.
For (shared) information, the Certmanager is defined in https://github.com/jenkins-infra/kubernetes-management/blob/main/clusters/prodpublick8s.yaml#L62-L71.
In particular, its configuration for resolver is found in a private + SOPS-encrypted file as per https://github.com/jenkins-infra/kubernetes-management/blob/main/clusters/prodpublick8s.yaml#L71.

When writing these lines, there are only 2 resolvers of type DNS01 for `jenkins.io` and `jenkins-ci.org` DNS zones, which are Azure-managed.

For `jenkinsistheway.io`, what do you think if we add a TLS resolver (or HTTP as fallback) resolver to avoid the pain of DNS management (that would require adding godaddy api keys in Certmanager, painful).

**Comment by timja** [comment]
> For jenkinsistheway.io, what do you think if we add a TLS resolver (or HTTP as fallback) resolver to avoid the pain of DNS management (that would require adding godaddy api keys in Certmanager, painful).

I delegated the zone to Azure, just do the same as jenkins.io and jenkins-ci.org please :)

**Comment by dduportal** [comment]
Outcome of the team mob programming session earlier today:

- Added the DNS resolver configuration for the domain `jenkinsistheway.io`
  - (private repo) updated the SOPS secret configuration used for ACME: https://github.com/jenkins-infra/charts-secrets/commit/f57ab66126b6e217f66a44b1c976bf6da6007dc4
- Fixed the helm chart:
  - https://github.com/jenkins-infra/helm-charts/pull/151
  - https://github.com/jenkins-infra/helm-charts/releases/tag/httpredirector-0.3.0
- Applied the change to production: https://github.com/jenkins-infra/kubernetes-management/pull/2491

**Comment by lemeurherve** [comment]
I've also added the `DNS Zone Contributor` role for the `certmanager` member so it could update it:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/91831478/173114323-e251d148-ab47-4ce1-bd73-4e24e356f85d.png">

**Comment by dduportal** [comment]
> 

TIL today: you can apply 2 times the same role assignement in Azure (@smerle33 and I did the same 1 hour ago).
I guess it's idempotent \o/

Anyway, many thanks @lemeurherve for checking and fixing!

**Comment by lemeurherve** [comment]
The link https://jenkinsistheway.io/user-story/to-tackle-any-challenge/ correctly redirects to https://stories.jenkins.io/user-story/to-tackle-any-challenge/, I suppose we can close this issue.

**Comment by dduportal** [comment]
+1 for me: https://infra.ci.jenkins.io/blue/organizations/jenkins/kubernetes-jobs%2Fkubernetes-management/detail/main/325/pipeline succesfully ran so automation is back
