### ISSUE TITLE
Access to remoting releasing permission

### ISSUE THREAD

**Issue by Vlatombe** [jenkins-infra/helpdesk#2947]
### Service(s)

release.ci.jenkins.io

### Summary

I would like to be able to cut a release of remoting by myself. To do that I need access to release.ci.jenkins.io

**Comment by dduportal** [comment]
LGTM for me (discussed prior to this issue).

ToDo list:

- [ ] @Vlatombe follow instructions at https://github.com/jenkins-infra/docker-openvpn#howto-get-client-access (link this issue to the PR you'll have to open)
- [ ] Add @Vlatombe to the release-core group (cc @timja @MarkEWaite does it sounds good to you?) so he can authenticate to release.ci.j and trigger the remoting job?

**Comment by Vlatombe** [comment]
* https://github.com/jenkins-infra/docker-openvpn/pull/170

**Comment by timja** [comment]
hold on

**Comment by timja** [comment]
https://release.ci.jenkins.io is only used for backports of remoting to the existing LTS line.

If you are releasing to weekly please just use either your machine or enable CD on the repo.

**Comment by Vlatombe** [comment]
I'm releasing to weekly to I will leverage this to enable CD.

* https://github.com/jenkins-infra/repository-permissions-updater/pull/2555
* https://github.com/jenkinsci/remoting/pull/538/
