### ISSUE TITLE
Please add Crowd2 to Crowdin

### ISSUE THREAD

**Issue by DuMaM** [jenkins-infra/helpdesk#2948]
### GitHub repositories

https://github.com/jenkinsci/crowd2-plugin

### Crowdin users to have project management permission

[@DuMaM](https://github.com/DuMaM)
[@martinspielmann](https://github.com/martinspielmann)

**Comment by timja** [comment]
@jenkins-infra/crowdin

**Comment by NotMyFault** [comment]
Heyo,

the project has been created and is available on https://jenkins.crowdin.com/crowd2-plugin.
The project ID is 24.

I couldn't add @martinspielmann, because he didn't log in yet.

**Comment by DuMaM** [comment]
I fought that Martin got an account there as he have to Jenkins infra. He is old maintainer of this plugin.
If he is not added there that means we can close this ticket.
Thank you very much :)
