### ISSUE TITLE
Renew update center certificate (crawler and update-center builds failing on trusted.ci.jenkins.io)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2950]
### Service(s)

trusted.ci.jenkins.io
updates.jenkins.io

### Summary

The certificate of the update center expires soon (14th of June 2022) and must be renewed for 1 year.
It forbids updates of the update-center JSON and tools metadata ("crawler").

[initial message]
The pipeline job `crawler` on trusted.ci.jenkins.io is failing on its principal branch since 5 days, which means that the tools metadata are not published since these 5 days:

- Last successful build is https://trusted.ci.jenkins.io:1443/job/crawler/10129/ - the 15th of May 2022 - 08:24am UTC
- The error happens during the "Publish" stage: `cp: cannot stat 'target/*.html': No such file or directory` during the `sh 'cp <...>` step - https://github.com/jenkins-infra/crawler/blob/master/Jenkinsfile#L65

It seems that there are no HTML files generated in the `target/` directory while there should be.

**Comment by dduportal** [comment]
As underlined by @daniel-beck (thanks!) the error is caused by a safety mechanism in the groovy script executed by this pipeline, which fail when the certificate expiration is coming soon:

```
[2022-05-21T12:20:29.237Z] Caught: java.io.IOException: Failed to create one or more output files.
[2022-05-21T12:20:29.237Z] java.io.IOException: Failed to create one or more output files.
[2022-05-21T12:20:29.237Z] 	at dotnetSdk.addFailure(dotnetSdk.groovy:41)
[2022-05-21T12:20:29.237Z] 	at dotnetSdk.run(dotnetSdk.groovy:61)
[2022-05-21T12:20:29.237Z] 	at runner$_run_closure1.doCall(runner.groovy:13)
[2022-05-21T12:20:29.237Z] 	at runner.run(runner.groovy:10)
[2022-05-21T12:20:29.237Z] 	Suppressed: java.security.cert.CertificateExpiredException: NotAfter: Tue Jun 14 10:42:00 UTC 2022
```

**Comment by dduportal** [comment]
Hello @daniel-beck @olblak @timja could you help us understanding this whole "certificate almost expired to be rotated".
It *seems* that it is a certificate somewhere in the update center code, but it's not clear which/what/how?

Searched the following issues from the past, but I honestly understand nothing to the involved components:
- https://github.com/jenkins-infra/helpdesk/issues/793
- https://github.com/jenkins-infra/helpdesk/issues/765
- https://github.com/jenkins-infra/runbooks/tree/main/updates

I don't see anything related tp the certificate in https://github.com/jenkins-infra/crawler.


What did I miss?

**Comment by timja** [comment]
It’ll be the update center signing certificate

**Comment by smerle33** [comment]
this certificate impact also update-center within trusted-ci. This is now a TOP priority for the infra team.

**Comment by dduportal** [comment]
A bit more context to help us understand which certificate is which:

- https://issues.jenkins.io/browse/INFRA-1502
- https://github.com/jenkins-infra/update-center2/pull/507 which changed the name of the old UC to the `-2` new name
- https://github.com/jenkins-infra/update-center2/pull/379/files => https://github.com/jenkins-infra/update-center2/tree/master/resources/certificates

**Comment by dduportal** [comment]
- [ ] Close incident on status.jenkins.io @smerle33 
- [ ] Cleanup credentials on trusted.ci for both jobs @dduportal  (and check the file struct of the latest uploaded)
- [ ] Write a runbook about rotation @smerle33 @dduportal 
- [ ] Update the (private) README of jenkins-infra/update-center with the correct file struct @dduportal @smerle33 
- [ ] Add a calendar event for the next renewal in 1 year (notifications 2 month and 1 month before) @smerle33

**Comment by dduportal** [comment]
*Filling the "plugin releases gap"*

Following the (private link) procedure at https://github.com/jenkins-infra/runbooks/tree/main/updates, we got the list of plugins released since the past 72 hours (the update-center job fails since ~24 hours):

```json
{"releases":[{"name":"azure-vm-agents","version":"815.vf2f07da070ee"},{"name":"cas-plugin","version":"1.6.2"},{"name":"checkmarx-ast-scanner","version":"2.0.11-274.va_d38ce3e7a_35"},{"name":"codescene","version":"1.5.7"},{"name":"dark-theme","version":"185.v276b_5a_8966a_e"},{"name":"ecutest","version":"2.34"},{"name":"eggplant-runner","version":"0.0.1.108.v32f1564b_19d0"},{"name":"elastic-axis","version":"1.6.0"},{"name":"influxdb","version":"3.2.1"},{"name":"jenkins-multijob-plugin","version":"611.v9d3180d752e6"},{"name":"jenkinsci-appspider-plugin","version":"1.0.15"},{"name":"jobConfigHistory","version":"1146.v94c2521f9213"},{"name":"junit","version":"1119.va_a_5e9068da_d7"},{"name":"junit-attachments","version":"101.v82f494a_00e9e"},{"name":"kubernetes","version":"3600.v144b_cd192ca_a_"},{"name":"opentelemetry","version":"2.7.1-rc2"},{"name":"report-info","version":"1.2"},{"name":"rest-list-parameter","version":"1.6.0"},{"name":"robot","version":"3.2.0"},{"name":"role-strategy","version":"488.v0634ce149b_8c"},{"name":"saml","version":"2.298.vc7a_2b_3958628"},{"name":"schedule-build","version":"301.vfdc555a_b_cf81"},{"name":"theme-manager","version":"1.4"},{"name":"theme-manager","version":"1.3"}]}
```

Still following the runbook procedure, the "sync script" on the update center VM was executed to make sure that all of these plugin releases are synchronized to the reference mirror, and are available through the get.jenkins.io URL.

Sanity checking: https://get.jenkins.io/plugins/azure-vm-agents/815.vf2f07da070ee/azure-vm-agents.hpi was HTTP/404 right before this operation, and is now available.

Reason: the update-center job is succeeding since today 07:24am UTC, but it only covers the past few hours, hence the gap.

**Comment by dduportal** [comment]
Email + IRC notification done

**Comment by dduportal** [comment]
Old `secrets.zip` credential removed in trusted.ci (I got a local encrypted backup)

**Comment by dduportal** [comment]
- Updated the `update-center` readme (https://github.com/jenkins-infra/update-center/pull/5) additionnaly to the new runbook.
- Removed @smerle33 from the `update-center` private repo (as only admin members are allowed).

**Comment by dduportal** [comment]
- Added back @smerle33 to update-center private repo: I though I could add him to a group, but there isn't any

**Comment by dduportal** [comment]
Closing: the event is in the jenkins-infra-team calendar

**Comment by szjozsef** [comment]
Some files are still signed with the old (expired certificates):
```
signature check failed for http://updates.jenkins.io/updates/hudson.plugins.groovy.GroovyInstaller.json
ERROR: Signature verification failed in downloadable &#039;hudson.plugins.groovy.GroovyInstaller&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertificateExpiredException: NotAfter: Tue Jun 14 13:42:00 EEST 2022<br>
```
also
```
signature check failed for https://updates.jenkins.io/updates/org.jenkinsci.plugins.scriptler.CentralScriptJsonCatalog.json
ERROR: Signature verification failed in downloadable &#039;org.jenkinsci.plugins.scriptler.CentralScriptJsonCatalog&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertificateExpiredException: NotAfter: Tue Jun 14 13:42:00 EEST 2022<br>
```

**Comment by daniel-beck** [comment]
The problem there is that these haven't been updated in a while. Nothing to do with the cert, just a regular crawler failure.

Some stuff was last updated 2017 🤷

**Comment by dduportal** [comment]
> The problem there is that these haven't been updated in a while (3 and 11 months respectively). Nothing to do with the cert, just a regular crawler failure.
> 
> Some other stuff was last updated 2017 🤷

Would that be a problem if find a way to regenerate these?

**Comment by timja** [comment]
shouldn't be, often crawler depends on external websites which change their markup so it can get broken easily...

**Comment by dduportal** [comment]
🤔 can we, instead, re-sign them one time? (still a high level question, haven't checked how to do it technically yet)

**Comment by dduportal** [comment]
Thanks folks. Keeping this issue open, adding to the current milestone so we'll track it.

**Comment by timja** [comment]
FYI every Jenkins instance will be complaining about this when it tries to check for updates

![image](https://user-images.githubusercontent.com/21194782/174035222-de83829c-36bb-4015-acd5-8504b3c5c7b8.png)

**Comment by daniel-beck** [comment]
> every Jenkins instance

… with affected plugins installed?

**Comment by dduportal** [comment]
We split the work, the faster would win :)

- Root cause is the groovy tool metadata that are failing to be generated since... some time. (at least since Groovy 3.0.9). So no new signature is generated. @lemeurherve is working in fixing the groovy crawler (use correct URL thant changed, etc.).
- Working on a groovy script hack to allow us re-signing the existing JSON

**Comment by timja** [comment]
> … with affected plugins installed?

Not sure, weekly.ci.jenkins.io is affected and that doesn't have many plugins.

**Comment by lemeurherve** [comment]
> > every Jenkins instance
> 
> … with affected plugins installed?

By looking at the files dates in /var/www/updates.jenkins.io/updates, we can see the affected plugins:

```bash
root@ip-172-31-33-96:/var/www/updates.jenkins.io/updates# ls -ltr
total 14368
-rw-rw-r-- 1 www-data www-data    8940 Jun  2  2017 hudson.plugins.flyway.FlywayInstaller.json.html
-rw-rw-r-- 1 www-data www-data   21628 Jun 25  2018 org.jenkinsci.plugins.perlinstaller.PerlInstaller.json
-rw-rw-r-- 1 www-data www-data   25462 Jun 25  2018 org.jenkinsci.plugins.perlinstaller.PerlInstaller.json.html
-rw-rw-r-- 1 www-data www-data   16449 Jul  5  2021 hudson.plugins.groovy.GroovyInstaller.json
-rw-rw-r-- 1 www-data www-data   23641 Jul  5  2021 hudson.plugins.groovy.GroovyInstaller.json.html
-rw-rw-r-- 1 www-data www-data    2560 Jul 27  2021 io.jenkins.plugins.codeql.CodeQLInstaller.json
-rw-rw-r-- 1 www-data www-data    8752 Jul 27  2021 io.jenkins.plugins.codeql.CodeQLInstaller.json.html
-rw-rw-r-- 1 www-data www-data   27036 Mar 12 12:24 org.jenkinsci.plugins.scriptler.CentralScriptJsonCatalog.json
-rw-rw-r-- 1 www-data www-data   34669 Mar 12 12:24 org.jenkinsci.plugins.scriptler.CentralScriptJsonCatalog.json.html
```

@dduportal has prepared a signer.groovy script to sign them.

**Comment by lemeurherve** [comment]
Long term solution: fix all failing groovy scripts in https://github.com/jenkins-infra/crawler
