### ISSUE TITLE
Crowdin is making folder structure flat

### ISSUE THREAD

**Issue by DuMaM** [jenkins-infra/helpdesk#2951]
### Service(s)

Crowdin

### Summary

Hi,
I followed up with all setups for my plugin.
https://github.com/jenkinsci/crowd2-plugin/blob/master/crowdin.yml

Could you please tell me why every time I import my files with crowd in it ignores folder structure?
I saw this also happens with [Elastic Axis Plugin](https://github.com/jenkinsci/elastic-axis-plugin/tree/master/src/main/resources/org/jenkinsci/plugins/elasticaxisplugin), but not with [design lib](https://github.com/jenkinsci/design-library-plugin). 

Could you help me determine what's going on?

### Reproduction steps

Lunch actions for crowdin. 
Open one of mentioned projects.

**Comment by timja** [comment]
Cc @jenkins-infra/crowdin-admins

**Comment by DuMaM** [comment]
I have some news here.
So problem only applies only html files. 😕

**Comment by NotMyFault** [comment]
Hey,

that appears to be an issue with the web ui. I recreated your repository setup on my instance and can confirm, that approved content ends up in the appropriate directory, see https://github.com/NotMyFault/crowd2-plugin/pull/1/files.
I'll get in touch with Crowdin nevertheless, thanks for letting us know 👍🏻

**Comment by DuMaM** [comment]
I don't think it's a crowdin ui bug. It's more cli or github action one.
As you can see in github actions logs it uploads html files with flat path and ignores dir structure.
After this it creates such PR
https://github.com/jenkinsci/crowd2-plugin/pull/74

I do some comparison with EnvInject Plugin (where is worked) and i found that some `html` files got CRLF windows file style. 
I converted them to LF linux one, and finally it was able to places files in correct spot with dir tree detection.

I think it should be reported in Jenkins Crowdin Tutorial and also Crowdin Org. Otherwise It can hurt some user experience.

**Comment by DuMaM** [comment]
I moved this to be flat in UI, and it working now 😕 
In logs it still got flat paths though...
