### ISSUE TITLE
[Infra Docker Images] Deprecate `img` in favor of `docker`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2952]
### Service(s)

infra.ci.jenkins.io, Other

### Summary

- https://github.com/genuinetools/img hasn't been released since a lot of time
- Docker provides buildx, with the same feature as `img` (`img` was an early demonstrator)
- All of our Jenkins controller has a VM agent capability (with Docker) so no need to keep `img` (which was aimed at running in containers before having VM with a fully-fledged)

The goal of this issue is to track the work associated to updating the shared library to:
- [x] use `docker` by default (and build build/test docker images in VM instead of containers by default)
- [ ] #2963

**Comment by lemeurherve** [comment]
> eventually stop using img at all (removing code in the library and eventually cleanup docker-builder)

@dduportal  WDYT of creating another issue for the final cleanup, and leave this one for the deprecation only?
