### ISSUE TITLE
Request maintainer access for plasticscm-plugin

### ISSUE THREAD

**Issue by mig42** [jenkins-infra/helpdesk#2955]
### GitHub repositories

plasticscm-plugin

### GitHub users to have permission

@juliomaqueda
@jessica-gutierrez

### Permission level

Maintain

### Justification

There are new additions to the team that maintains the `plasticscm-plugin`. We'd like to grant access to the new developers.

Actually we just need them to be added to the `jenkinsci` organization. I can add them to the GitHub Team that has permissions over that repo.

Thanks!

**Comment by timja** [comment]
Done:

![image](https://user-images.githubusercontent.com/21194782/170457498-65fd75e2-3111-4013-b29d-0fba88e5699a.png)
