### ISSUE TITLE
Request access to Jenkins project VPN

### ISSUE THREAD

**Issue by yaroslavafenkin** [jenkins-infra/helpdesk#2956]
### Service(s)

VPN

### Summary

Docker openvpn PR: https://github.com/jenkins-infra/docker-openvpn/pull/171
Reason: member of JenSec team since recently

**Comment by dduportal** [comment]
Thanks for the issue @yaroslavafenkin ! You did everything correctly.

Ping @wadeck @daniel-beck could we get an approval from you before we proceed on this issue?

**Comment by Wadeck** [comment]
PR approved 👍

**Comment by dduportal** [comment]
Thanks! 

ToDO list for infra people:

- [x] PR updated approved and merged (request is signed)
- [ ] Ensure that a new Docker image for the VPN is built
- [ ] Ensure that the new Docker image for the VPN is deployed

**Comment by dduportal** [comment]
@yaroslavafenkin you should be able to access the VPN by continuing to follow steps at https://github.com/jenkins-infra/docker-openvpn#howto-get-client-access.

Please reopen the issue or reach us in the IRC libera#jenkins-infra if you have any issue.
