### ISSUE TITLE
Setup google domain verification for stories.jenkins.io

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#2958]
### Service(s)

Azure

### Summary

I quote from https://search.google.com/search-console
1. Sign in to your domain name provider (e.g. godaddy.com or namecheap.com)
2. Copy the TXT record below into the DNS configuration for stories.jenkins.io

`google-site-verification=3zy2hGWrfljpVGSr6mPfZArQdxjmp27_4_obRQrQQtY`

3. Press verify below
Note: DNS changes may take some time to apply. If Search Console doesn’t find the record immediately, wait a day and then try to verify again

**Comment by smerle33** [comment]
it seems that we cannot have both a CNAME and a TXT for the same subdomain in azure DNS.
I see 2 solutions for now, 

- change the CNAME to A but we will have to manage it by terraform in case of IP changes
- change the verification method to use a file hosted on the domain  for example, depending on what google offer as method.

**Comment by halkeye** [comment]
1 seems super odd. They are unrelated afaik

I'll do the file thingie

**Comment by smerle33** [comment]
> I'll do the file thingie

can you try to provide the google file from within the google console ? (or maybe they can provide new/others ways of verifications)

**Comment by halkeye** [comment]
Nah it's too prove you have control of the site, so they want you to update the site. I like DNS cause it doesn't mean you need to modify the site itself. Its super easy to add a meta tag though

**Comment by smerle33** [comment]
> They also support CNAME validation using a sub-domain: https://support.google.com/webmasters/answer/9008080#domain_name_verification&zippy=%2Cdomain-name-provider

This can be a solution, but I don't have access to the google interface to generate a cname key/value to add in the DNS.

**Comment by halkeye** [comment]
Apparently url ownership (which is what you do when you upload file / add metadata) only matches that url, so https://stories, not http://stories

That should be fine since we do redirects.

I've added the metadata, and added damien so he can give out additional access
