### ISSUE TITLE
Approve jenkins.io domain on the GH orgs

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2959]
### Service(s)

Azure, Github

### Summary

Approved domains show a neat little badge next to the URL on the GH organization overview:
![Bildschirmfoto 2022-05-29 um 20 21 00](https://user-images.githubusercontent.com/13383509/170885666-7dfbb5e5-8fb5-497c-b852-5402432ced70.png)

The process is quite simple and requires nothing more than a temporary TXT record on the DNS registrar obtained from https://github.com/organizations/(org)/settings/domains for the domain you want to verify.
This proposal affects the jenkinsci, jenkins-infra and jenkinsci-cert org, based on a quick glance over their organization URLs.

While this would be a truly cosmetical change, it adds a plus point for newbies checking in and people who aren't familiar with the organizations still be able to recognize them as "official" ones.

**Comment by lemeurherve** [comment]
We've enabled the verification of `www.jenkins.io` on jenkins-infra org, alas we won't get an "approved" badge next to the link as GitHub wants to also verify `googlegroups.com` domain.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/91831478/170954468-5dafdc38-ac3c-4edf-bec2-1b55ca035e39.png">

@jenkins-infra/jenkinsci-admins could one of you go to https://github.com/jenkinsci/settings/domains and check what are the domains requested to get approved?

**Comment by NotMyFault** [comment]
> alas we won't get an "approved" badge next to the link as GitHub wants to also verify googlegroups.com domain (as the org email is [jenkins-infra-team@googlegroups.com](mailto:jenkins-infra-team@googlegroups.com))

Understandable, just noticed that these are the actual mailing list mail addresses we can't verify.

**Comment by lemeurherve** [comment]
@timja TXT record added.

**Comment by timja** [comment]
![image](https://user-images.githubusercontent.com/21194782/171000741-fde4ae6b-753e-4c16-a608-120aa7a8d3fc.png)

**Comment by lemeurherve** [comment]
I've removed the public jenkins-infra org email so the domain is approved, will put it back in an org README.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/91831478/171002105-f5cbc27d-a3ce-4e43-aacd-98ef1cc41a9b.png">

**Comment by lemeurherve** [comment]
Note: I've might have closed this issue a little bit too fast, @jenkins-infra/security do you want to do the same for jenkinsci-cert?

**Comment by daniel-beck** [comment]
@lemeurherve Yes, please 👍 

```
1. Create a TXT record in your DNS configuration for the following hostname: _github-challenge-jenkinsci-cert-org.jenkins.io
2. Use this code for the value of the TXT record: a1975606e1. Please note that the code will expire in 7 days.
3. Wait until your DNS configuration changes. This could take up to 72 hours to propagate.

**Comment by lemeurherve** [comment]
@daniel-beck record added, can you check it in [the jenkinsci-cert domain settings](https://github.com/organizations/jenkins-infra/settings/domains) please?

**Comment by daniel-beck** [comment]
It shows up in the settings as Verified, but not on the org page. Anything I'm doing wrong?

**Comment by daniel-beck** [comment]
Ugh, the auto-suggested domain "jenkins.io" was different from "www.jenkins.io" that's actually used 😒

```

1. Create a TXT record in your DNS configuration for the following hostname: _github-challenge-jenkinsci-cert-org.www.jenkins.io
2. Use this code for the value of the TXT record: be04b613aa. Please note that the code will expire in 7 days.
3. Wait until your DNS configuration changes. This could take up to 72 hours to propagate.

**Comment by lemeurherve** [comment]
@daniel-beck new TXT record added, let me know if it worked.

**Comment by daniel-beck** [comment]
<img width="914" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/189831353-501afe07-3409-4030-aa75-4ca87ec36038.png">

🎉 Thanks @lemeurherve !
