### ISSUE TITLE
[ci.jenkins.io] Try the kubernetes-plugin PR#1167

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2964]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io

### Summary

As per https://github.com/jenkins-infra/helpdesk/issues/2893#issuecomment-1136852200, we might want to try the incremental builds for the PR https://github.com/jenkinsci/kubernetes-plugin/pull/1167 from @sbeaulie .

**Comment by dduportal** [comment]
https://github.com/jenkinsci/kubernetes-plugin/pull/1167 merged \o/ 

As soon as the release is available, we deploy it in ci.jenkins.io.

Shoutout to @sbeailie and @Vlatombe

**Comment by timja** [comment]
https://github.com/jenkinsci/kubernetes-plugin/releases/tag/3636.v84b_a_1dea_6240

**Comment by lemeurherve** [comment]
updatecli PRs merged on docker-jenkins-lts & docker-jenkins-weekly

**Comment by dduportal** [comment]
Gotta install it on ci.j and trusted.j

**Comment by dduportal** [comment]
Plugin installed on ci.jenkins.io. Let's see how it behaves!
