### ISSUE TITLE
Request IRC cloak for Libera

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2965]
### Service(s)

Other

### Summary

I'd like to request a cloak for my IRC user, as described on https://www.jenkins.io/chat/#cloaks.
Currently, I do not fulfill the second bullet point of the URL above for the channels #jenkins, #jenkins-infra, #jenkins-release and #jenkins-hosting. I'm not sure if there are additional steps I need to take on my end to obtain these flags.

My NickServ username is the same like on GitHub, NotMyFault.

Thanks in advance!

**Comment by timja** [comment]
requested

**Comment by timja** [comment]
jenkins/contributor/notmyfault assigned.

I think you may need to login / out dunno

**Comment by timja** [comment]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/21194782/171344527-6d9cf44f-753c-412e-9db6-0a1742076779.png">
