### ISSUE TITLE
release.ci.jenkins.io down

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2966]
### Service(s)

release.ci.jenkins.io

### Summary

I went to go check the status of the weekly release and https://release.ci.jenkins.io has a 503

<img width="869" alt="image" src="https://user-images.githubusercontent.com/21194782/171345893-3150254a-1c21-41ef-88aa-66442d091037.png">

**Comment by timja** [comment]
It's back now

**Comment by dduportal** [comment]
Sounds like because of https://github.com/jenkins-infra/kubernetes-management/pull/2428

**Comment by timja** [comment]
yeah, it was down for a few mins, I did wait a bit before raising

**Comment by dduportal** [comment]
> yeah, it was down for a few mins, I did wait a bit before raising

Sorry, I did not check that the weekly was finished when merging. As there was also an Helm chart update (https://github.com/jenkins-infra/kubernetes-management/pull/2421), I assume that the update triggered a new pod on another machine (gotta check)
