### ISSUE TITLE
bootstrat a terraform project for oracle

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#2973]
### Service(s)

Oracle / Terraform bootstrap state

### Summary

Boostrap a terraform project for oracle with a terraform-state hosted in an azure bucket.

The aim is to create the kernel with authentication user / api-token / principal object (bdd ?)
then to output the authentifications infos to pass within SOPS that will be consumed by the pipeline within the final oracle project based on this bootstrap.

the final project would then be used for : https://github.com/jenkins-infra/helpdesk/issues/2682 and https://github.com/jenkins-infra/helpdesk/issues/2649

work in progress : 
as per https://github.com/jenkins-infra/terraform-states/commit/eeb514512f7ece88067e6f6d68cc492d62895d51 for the skeleton

and https://github.com/jenkins-infra/terraform-states/commit/0679ee48048ab2a11441fa4590035016ebdf6de8

need to login the oracle cloud infra from the source computer that will terraform apply and then add the outputs.

**Comment by smerle33** [comment]
use this page to setup key pair for oci-cli : https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#Required_Keys_and_OCIDs

**Comment by smerle33** [comment]
lock at the upload public key as the user we used is a federated user link with the azureAD SSO, we need to synchronize users : 
https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/usingscim.htm

https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/oracle-cloud-infrastructure-console-provisioning-tutorial

**Comment by smerle33** [comment]
we decided to create a local user with 2FA to access the CLI

**Comment by smerle33** [comment]
complete the oracle project by setting based on the AWS one : 
version.tf
providers.tf
Jenkinsfile_k8s

**Comment by dduportal** [comment]
Job + credentials created in infra.ci by the following PRs:

- https://github.com/jenkins-infra/kubernetes-management/pull/2477
- https://github.com/jenkins-infra/kubernetes-management/pull/2482

**Comment by dduportal** [comment]
Opened a bug in https://github.com/jenkins-infra/helm-charts/issues/148 about the multiline string failing the job-dsl

**Comment by smerle33** [comment]
as per https://github.com/jenkins-infra/oracle/pull/2
the terraform skeleton is done,
lets set-up the updatecli update process

**Comment by smerle33** [comment]
the first updatecli run fail over a 
```
ERROR: 	Could not resolve to a PullRequest with the number of 4.

Pipeline "Bump Jenkinsfile_k8s for updatecli `hashicorp-tools` docker image version to lastest image release" failed

Skipping due to:

	pull Request stage:	"Could not resolve to a PullRequest with the number of 4."
```
