### ISSUE TITLE
[ci.jenkins.io] Provides both `powershell` and `pwsh` on all agent templates

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2974]
### Service(s)

ci.jenkins.io

### Summary

As per https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/203, it seems that `powershell` cannot be used on the Jenkins inbound images with nanoserver.

- Jenkins error (as per https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/203#issuecomment-1148794960):

```console
java.io.IOException: Cannot run program "powershell" (in directory "…"): CreateProcess error=2, The system cannot find the file specified
```

- Can be reproduced on a Windows Docker CE (ref. https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/203#issuecomment-1148886314):

```console
$ docker run --rm -ti --entrypoint=powershell jenkins/jnlp-agent-maven:windows-nanoserver
docker: Error response from daemon: container dd73e4c79e13c68fb1d113ddf0bb3ce966102591fb4d9fe0acd54e940caf83c7 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF7FC739F4B: (caller: 00007FF7FC6EE13A) Exception(6) tid(39c) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000].
```

- Since https://github.com/jenkins-infra/jenkins-infra/pull/2203, the infra team can quickly add a fix as we manage our own base images (time to have the fix integrated on the upstream community image).

- As per @jnord comment in https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/203#issuecomment-1148936806 

> https://docs.microsoft.com/en-us/windows-server/get-started/powershell-on-nano-server#differences-in-powershell-on-nano-server powershell (core) should be available by default?

it seems that there is an issue on the upstream image jenkins/jnlp-agent-maven:windows-nanoserver . 

Work is going on checking the base image of `jenkins/jnlp-agent-maven:windows-nanoserver` and check the status before trying to find a solution: Jesse was ablme to use "bat" instead of "powershell" for the tests so no blocker.

**Comment by lemeurherve** [comment]
```
docker run --rm -ti --entrypoint=powershell mcr.microsoft.com/powershell:nanoserver-1809
docker: Error response from daemon: container 2dde7b4e7fc5f0e6ac4a356971c71debe5c5aeab054d2a62497f57bc2a6ddf43 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2).
```
Same for the base Microsoft nanoserver image (?)

**Comment by lemeurherve** [comment]
Oh...
It's `pwsh` and not `powershell`: https://github.com/PowerShell/PowerShell-Docker/blob/master/release/7-2/nanoserver1809/docker/Dockerfile#L90

```
docker run --rm -ti --entrypoint=pwsh mcr.microsoft.com/powershell:nanoserver-1809
PowerShell 7.2.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.
```

**Comment by dduportal** [comment]
OK, I'm 200% confused by the pipeline steps:

- https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#powershell-windows-powershell-script 
- https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#pwsh-powershell-core-script

Ping @jnord if you have any pointer to explain the difference for mere mortals such as us 😅

**Comment by jtnord** [comment]
right.
powershell core is a cut down version and is more cross platform (this is what you [get with the linux distros](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2))  binary is `pwsh.exe` vs `powershell.exe`..
hence the 2 steps - we just forgot and used the wrong one...

**Comment by dduportal** [comment]
> right. powershell core is a cut down version and is more cross platform (this is what you [get with the linux distros](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-linux?view=powershell-7.2)) binary is `pwsh.exe` vs `powershell.exe`.. hence the 2 steps - we just forgot and used the wrong one...

Oh I see. I assume that jenkins is not able to "guess" based on what it discovers on its PATH, is that correct?

Would the proposal of @lemeurherve make sense (e.g. adding a `powershell` alias) to avoid end user to step in the same trap?

**Comment by lemeurherve** [comment]
I think I'll make sure `pwsh.exe` is available on all our agents, then update the shared pipeline to use `pwsh` instead of `powershell`

**Comment by lemeurherve** [comment]
I'll also intend to install [Windows Powershell 5.1 (`powershell.exe`) alongside Powershell 7 (`pwsh.exe`)](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/migrating-from-windows-powershell-51-to-powershell-7?view=powershell-7.2#using-powershell-7-side-by-side-with-windows-powershell-51) so either command could be used.

IMO favoring `pwsh` instad of `powershell` in pipelines should be emphasized in doc somehow (maybe on the pipeline syntax reference page?), at least [a note about their differences](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.2).
(last one I've noticed, the operator `||` isn't recognized with `powershell`)

**Comment by jglick** [comment]
> should be emphasized in doc somehow

Feel free to file a `documentation` PR to `workflow-durable-task-step-plugin`.

**Comment by lemeurherve** [comment]
After spending too much time trying to install Windows PowerShell in our nanoserver images, and PowerShell Core in our windowsserver images, I'm closing this issue since:
- [both powershell are installed in our VM images](https://github.com/jenkins-infra/packer-images/pull/260)
- [the doc has been updated](https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/240) to warn users to check which version is available before using `powershell` or `pwsh` in their pipeline
- our docker inbound agent images will be replaced by packer images in the long term
