### ISSUE TITLE
GSoC: Plugin Health Scoring system

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#2975]
For this Google Summer of Code 2022, the Plugins Health Scoring system has been selected (https://www.jenkins.io/projects/gsoc/2022/projects/plugin-health-scoring-system/).

As explained in https://groups.google.com/d/msgid/jenkins-infra/CAG%3D_Duu9eyZq0poc8JQHBbd0-0dAWRayxjpznPxPXdh1W9Giqg%40mail.gmail.com, we need a few things from infra for this project:
1. a Git repository to host the code of the project. Repository should be accessible with write / admin permissions to: 
    - [Aditya Srivastava](https://www.jenkins.io/blog/authors/adi10hero): `ADI10HERO`
    - [Adrien Lecharpentier](https://www.jenkins.io/blog/authors/alecharp): `alecharp`
    - [Dheeraj Singh Jodha](https://www.jenkins.io/blog/authors/dheerajodha): `dheerajodha`
    - [Jake Leon](https://www.jenkins.io/blog/authors/jleon): `jleon33`

2. some elements will live in the Jenkins infra: a database, a place to run the code hosted in `1.`, host a static file generated by the code
3. have the possibility to have a fork of plugins.jenkins.io to live somewhere in the infra to consume what the project will be producing.

Once hosted, we would love to see the code being built and deployed (to `2.`) by Jenkins.

**Comment by lemeurherve** [comment]
For 1), I suggest creating a team `plugins-health-scoring`

**Comment by alecharp** [comment]
It makes sense to me yes. Jake and Aditya are also mentor of the project. so maybe us three as maintainer of the team?

**Comment by jleon33** [comment]
More than ok with me!

Thank you Adrien!

Jake

**Comment by lemeurherve** [comment]
Team created: https://github.com/orgs/jenkins-infra/teams/plugin-health-scoring/members
@jleon33 @ADI10HERO you should have received an invitation to joing the jenkins-infra organisation and this new team.

**Comment by lemeurherve** [comment]
Repository created: https://github.com/jenkins-infra/plugin-health-scoring
I've activated "discussions" and "projects" on it.

**Comment by alecharp** [comment]
This is perfect @lemeurherve. I'm closing this ticket here, we will create others for the infra we might need and so on.
