### ISSUE TITLE
temp-privatek8s cluster backup

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2976]
### Service(s)

infra.ci.jenkins.io

### Summary

We should backup the data of infra.ci.jenkins.io in order to keep the builds and artifacts history in case the volume associated to this instance is lost, like what happened while trying to execute Windows pod agents
(We added a node pool of Windows type, and kubernetes tried to reschedule [infra.ci](http://infra.ci/), which led to failure in diskchk for the data volume)

To save it we could use a solution like [Velero](https://velero.io/), but nothing prevents using another tool.

**Comment by lemeurherve** [comment]
Create another issue for prodpublick8S after the completion of this one

**Comment by dduportal** [comment]
Closing the issue as both clusters have been replaced by new ones :)

https://github.com/jenkins-infra/helpdesk/issues/3656 for tracking backups of PVs
