### ISSUE TITLE
Deprecation warning in packaging pipeline

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2979]
### Service(s)

release.ci.jenkins.io

### Summary

can be seen in the first few lines of the packaging pipeline:

[WARNING] label option is deprecated. To use a static pod template, use the 'inheritFrom' option.
https://release.ci.jenkins.io/job/core/job/package/job/master/200/console

**Comment by dduportal** [comment]
We did that some times ago on 
https://github.com/jenkins-infra/kubernetes-management/pull/993 . Incoming PR.

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/release/pull/247
