### ISSUE TITLE
Replace s390x Ubuntu 18.04 agent with s390x Ubuntu 20.04 agent

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#2983]
### Service(s)

ci.jenkins.io

### Summary

The [s390x agent on ci.jenkins.io](https://ci.jenkins.io/computer/s390x-agent/) has been running Ubuntu 18.04.  IBM has provided a new agent that is running Ubuntu 20.04.  @MarkEWaite has connected the new agent to his test configuration and confirmed that it is working well.

Agent information (IP address, credentials, etc.) is available from @MarkEWaite 
### Resolution steps

1. [x] Confirm that the [current s390x agent](https://ci.jenkins.io/computer/s390x-agent/) is offline (agent virtual machine has been deleted)
2. [x] Update the s390x agent definition interactively with the new agent information, confirm it connects and is working
3. [x] Create a runbook entry that describes the agent management process for this special case agent - https://github.com/jenkins-infra/runbooks/pull/68
4. [x] Implement the configuration as code change to store the agent configuration  - https://github.com/jenkins-infra/jenkins-infra/pull/2580
5. [ ] Update ci.jenkins.io with the latest configuration as code and confirm the agent is connected and operational
6. [x] Update the [check-agent-availability acceptance test](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/) to confirm s390x agent labels are available as expected, confirm the test passes - working in [the job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/lastSuccessfulBuild/pipeline-graph/)

**Comment by dduportal** [comment]
SSH key shared with me. Thanks @MarkEWaite

**Comment by dduportal** [comment]
I'm closing as the 20.04 s390x agent:

- Works as expected since a few weeks now
- SSH private key encrypted in SOPS secrets (available to the whole team) and described in the runbooks
- Ubuntu upgraded to 22.04 (ref. https://github.com/jenkins-infra/helpdesk/issues/2982#issuecomment-1604546958)
- Automation (with Puppet, or other) is tracked in https://github.com/jenkins-infra/helpdesk/issues/2116
