### ISSUE TITLE
[JENKINS-49707] Evaluate `retry` conditions to improve the stability of the builds

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#2984]
### Service(s)

ci.jenkins.io

### Summary

https://github.com/jenkins-infra/pipeline-library/pull/405

**Comment by dduportal** [comment]
- First wave of incrementals for weekly image: https://github.com/jenkins-infra/docker-jenkins-weekly/pull/512#event-6801315430
- Installation on infra.ci: https://github.com/jenkins-infra/kubernetes-management/pull/2502

**Comment by dduportal** [comment]
Ping @jglick for info: this is the "parent" issue that we (infra-team) are using to track this subject.

**Comment by dduportal** [comment]
So far no issue for us on infra.ci. 

WDYT if we install the plugins on ci.jenkins last week, after the 22'th security release? @jglick

**Comment by jglick** [comment]
_Next_ week you mean? Sure, whenever seems convenient for you.

**Comment by jglick** [comment]
I am not available tomorrow (Fri) or Mon so better to wait until next week.

**Comment by dduportal** [comment]
Ping @jglick , if it is ok for you, we would want to install these experimental plugins to ci.jenkins.io wednesday (Kubernetes upgrades, Update center and pkg.jenkins.io finally working as expected)

Just wanted to checkpoint with you in here to see if we should keep the same version as in https://github.com/jenkins-infra/docker-jenkins-weekly/pull/512#event-6801315430 or if there are new "incremental" versions (since some time has passed, I assume that PR rebases with new incrementals might be required).

**Comment by jglick** [comment]
Tomorrow is fine. Up to you.

There are no new incremental versions currently. I _could_ produce some if you need some unrelated updates to the patched plugins.

**Comment by dduportal** [comment]
> Tomorrow is fine. Up to you.
> 
> There are no new incremental versions currently. I _could_ produce some if you need some unrelated updates to the patched plugins.

Did not tracked the detailled changelog of these plugins, so looks good. Thanks for the feedback!

**Comment by dduportal** [comment]
Self note: these 4 plugins have to be downloaded from the "incrementals" repository on repo.jenkin-ci.org (found documentation https://www.jenkins.io/doc/developer/plugin-development/incrementals/ which led to https://github.com/jenkinsci/incrementals-tools#enabling-consumption-of-incrementals where the URL of the repository https://repo.jenkins-ci.org/artifactory/incrementals/)

- https://repo.jenkins-ci.org/artifactory/incrementals/org/csanchez/jenkins/plugins/kubernetes/3650.ve6f9e42d64de/
- https://repo.jenkins-ci.org/artifactory/incrementals/org/jenkins-ci/plugins/workflow/workflow-basic-steps/962.v44eb_d807841a_/
- https://repo.jenkins-ci.org/artifactory/incrementals/org/jenkins-ci/plugins/workflow/workflow-api/1174.va_3d1b_702a_07b_/
- https://repo.jenkins-ci.org/artifactory/incrementals/org/jenkins-ci/plugins/workflow/workflow-durable-task-step/1151.v3d3a_91c77419/

**Comment by dduportal** [comment]
@jglick The 4 plugins had been installed to ci.jenkins.io (+ controller restart). We can start checking the behavior.

**Comment by dduportal** [comment]
For info, reported by @imontero 👍 

> it seems this is still failing, now I'm getting
> ```
> [2022-07-07T08:00:29.126Z] Cannot contact EC2 (aws-us-east-2) - High memory ubuntu 20.04 (i-0d6d4f71b7e22ea56): > hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@2da1b713:EC2 (aws-us-east-2) - High memory ubuntu 20.04 (i-0d6d4f71b7e22ea56)": Remote call on EC2 (aws-us-east-2) - High memory ubuntu 20.04 (i-0d6d4f71b7e22ea56) failed. The channel is closing down or has closed down
[2022-07-07T08:10:33.028Z] Could not connect to EC2 (aws-us-east-2) - High memory ubuntu 20.04 (i-0d6d4f71b7e22ea56) to send interrupt signal to process
> https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-793/8/pipeline/34/

**Comment by dduportal** [comment]
> Some sort of abort happened (can't see why)

That one is most probably a spot instance reclaimed

**Comment by jglick** [comment]
Looked for recent builds mentioning **Agent was removed** on the index page. Found https://ci.jenkins.io/job/Plugins/job/workflow-job-plugin/job/PR-274/10/ & https://ci.jenkins.io/job/Plugins/job/veracode-scan-plugin/job/dev/76/ neither of which retried, but these both spanned a controller restart (an hour ago?) and that scenario is handled only by https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180 which you are not yet running.

https://ci.jenkins.io/job/Tools/job/bom/job/master/1080/execution/node/2338/log/ failed without triggering a retry; seem to have been three failures there, one in `deleteDir()` (i.e., the agent was broken as soon as it was allocated, before we even got to run any workload on it):

```
java.io.IOException: Unable to create live FilePath for jnlp-maven-11-3rsmr
	at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:66)
	at org.jenkinsci.plugins.workflow.support.steps.FilePathDynamicContext.get(FilePathDynamicContext.java:48)
	at org.jenkinsci.plugins.workflow.steps.DynamicContext$Typed.get(DynamicContext.java:95)
	at org.jenkinsci.plugins.workflow.cps.ContextVariableSet.get(ContextVariableSet.java:139)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.getContextVariable(CpsThread.java:137)
	at org.jenkinsci.plugins.workflow.cps.CpsStepContext.doGet(CpsStepContext.java:298)
	at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:75)
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.checkContextAvailability(StepDescriptor.java:263)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:299)
	at …
```

which _might_ be addressed by https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/180 (cannot recall offhand).

https://ci.jenkins.io/job/Tools/job/bom/view/change-requests/job/PR-1250/2/execution/node/7754/log/ was successfully retried after

```
 Cannot contact jnlp-maven-11-jxm8b: hudson.remoting.RequestAbortedException: java.nio.channels.ClosedChannelException
 Could not connect to jnlp-maven-11-jxm8b to send interrupt signal to process
```

Despite lack of evidence from plugin builds, I think evidence from `acceptance-test-harness` and `bom` builds, combined with functional tests of course (and some interactive tests in K8s), is good enough for me to go ahead with releasing the first tranche of PRs.

**Comment by dduportal** [comment]
Last plugin (`kubernetes`) updated on ci.jenkins.io.

Many thanks @jglick !
