### ISSUE TITLE
Maven 3.8.6 upgrade campaign

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2986]
### Service(s)

ci.jenkins.io

### Background

In https://github.com/jenkins-infra/helpdesk/issues/2835 it was discovered that Maven 3.8.5 was susceptible to [MNG-7432](https://issues.apache.org/jira/browse/MNG-7432). At the time [that issue](https://github.com/jenkins-infra/helpdesk/issues/2835) was filed, the fix for MNG-7432 had been neither been merged nor released. At the time of this writing, the fix for MNG-7432 has been merged and released in Maven 3.8.6. I verified that Maven 3.8.6 is no longer susceptible to MNG-7432:

```bash
$ mvn -version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/maven
Java version: 1.8.0_312, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-37-generic", arch: "amd64", family: "unix"
$ mvn clean verify -Dset.changelist -DskipTests
[…]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:23 min
[INFO] Finished at: 2022-06-13T09:49:55-07:00
[INFO] ------------------------------------------------------------------------
```

### Problem

Our builds use Maven 3.8.4, which is out of date.

### Solution

Upgrade to the latest version of Maven. At the time of this writing, the latest version of Maven is 3.8.6.

### Reproduction steps

Search for the string "Apache Maven" in the console log of recent builds of https://ci.jenkins.io/job/Core/job/jenkins/job/master/ and observe that Maven 3.8.4 (which is not the latest version of Maven) is being used.

**Comment by lemeurherve** [comment]
The updatecli manifests we've setup to keep Maven version updated use https://github.com/apache/maven/releases as source for new versions. The 3.8.6 version hasn't been released there yet, which explain why the current blocked PRs haven't been updated.

Ex on jenkins-infra:
https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/buildmaster-tools-maven.yaml#L18-L23
https://github.com/jenkins-infra/jenkins-infra/pull/2165/files

**Comment by lemeurherve** [comment]
As the tag 3.8.6 exists, I've manually [updated the PR](https://github.com/jenkins-infra/jenkins-infra/pull/2165)

**Comment by dduportal** [comment]
We should let updatecli do it’s stuff. Reason is that it checks for the binary availability (otherwise no reason to trigger a PR). Given that this version was release in the past hours + the fact that there are securit releases being worked on + a weekly tomorrow, i propose that we wait for Wednesday (as it does not seem urgent).

anyway, many thanks @basil and @lemeurherve  for taking care of this !

**Comment by dduportal** [comment]
Hello @daniel-beck , as per https://github.com/jenkins-infra/jenkins-infra/pull/2165#issuecomment-1154223716, we are waiting for you "go" before working on this topic.

**Comment by lemeurherve** [comment]
Confirmed the presence of "Apache Maven 3.8.6" in core and plugins build logs, closing as completed.

**Comment by lemeurherve** [comment]
There were no master build today, [confirmed manually](https://ci.jenkins.io/job/Core/job/jenkins/job/master/3704/console) with a replay:
```
node('maven-11') {
  sh 'mvn -v'
}
```
