### ISSUE TITLE
Remove `basil` from plugins he is no longer maintaining

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2987]
### GitHub repositories

I have removed myself from several plugins in RPU; however, I continue to receive email notifications for these plugins, to be a member of the relevant teams, and to have the ability to approve and merge PRs.

Please remove me from the following GitHub teams:

https://github.com/orgs/jenkinsci/teams/aws-beanstalk-publisher-plugin-developers
https://github.com/orgs/jenkinsci/teams/emailext-template-plugin-developers
https://github.com/orgs/jenkinsci/teams/exclusion-plugin-developers
https://github.com/orgs/jenkinsci/teams/git-bisect-plugin-developers
https://github.com/orgs/jenkinsci/teams/jquery-plugin-developers
https://github.com/orgs/jenkinsci/teams/maven-repository-plugin-developers

Please remove any and all GitHub permissions that I have (including the ability to approve and merge PRs) to the following repositories:

https://github.com/jenkinsci/aws-beanstalk-publisher-plugin
https://github.com/jenkinsci/emailext-template-plugin
https://github.com/jenkinsci/exclusion-plugin
https://github.com/jenkinsci/git-bisect-plugin
https://github.com/jenkinsci/jquery-plugin
https://github.com/jenkinsci/maven-repository-plugin

### GitHub users to have permission

@basil

### Permission level

Read

### Justification

I no longer maintain these plugins.

**Comment by timja** [comment]
You can leave teams on your own, from the members page there’s a Leave team button

**Comment by basil** [comment]
Thanks, I left all the teams mentioned above.

**Comment by timja** [comment]
Anything left for this then?

**Comment by timja** [comment]
no other permissions present for you

**Comment by basil** [comment]
Thank you!
