### ISSUE TITLE
Build failure javadoc cannot reproduce locally

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/helpdesk#3012]
### Service(s)

ci.jenkins.io

### Summary

Not sure why this build is failing on javadoc and I cannot reproduce locally:
https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/193

**Comment by jetersen** [comment]
As I mentioned, I could not reproduce locally, so how is this not a Jenkins CI issue?

**Comment by basil** [comment]
As predicted, implementing my suggestion from https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/193#pullrequestreview-1013998343 in https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/193/commits/e01f2e815b880455af60dc482c5daeb6213611da fixed the build in [the next run](https://ci.jenkins.io/job/Plugins/job/gitlab-branch-source-plugin/job/PR-193/7/), confirming the infrastructure was not at fault, so I suggest this ticket be closed.

**Comment by jetersen** [comment]
> a different plausible theory would be that the relevant Javadoc error used to be a warning on Java 8 but is now an error on Java 11

Built locally with Java 11 😓

**Comment by basil** [comment]
Happy to help. I concur that Maven logs are particularly onerous, especially because they are full of harmless warnings with an occasional error that makes the entire Maven goal grind to a halt.
