### ISSUE TITLE
Consider removing embeddable-build-status plugin

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#3013]
### Service(s)

ci.jenkins.io

### Summary

https://plugins.jenkins.io/embeddable-build-status/ is not actively maintained. The Jenkins security team had to address multiple vulnerabilities in https://www.jenkins.io/security/advisory/2022-06-22/ to protect Jenkins project infrastructure. While the maintainer (thomas-dee) was happy to let us release the fixes we wrote, i.e. was responsive via email, he also told us he has no capacity to assist in any way. This is unsustainable. Consider removing the plugin from ci.jenkins.io.

**Comment by daniel-beck** [comment]
> all CI instances, including infra, release and weekly

It's unlikely to be a big problem inside the VPN, but yes, that never made sense to me. My guess: a leftover from extending `jenkins-infra/jenkins-infra` config to more than just ci.j.io.

**Comment by dduportal** [comment]
PR to remove it from the weekly and LTS images used on our Kubernetes-hosted controllers (weekly, infra and release): 
- https://github.com/jenkins-infra/docker-jenkins-weekly/pull/519
- https://github.com/jenkins-infra/docker-jenkins-lts/pull/521

For trusted and cert, a manual check is required

For ci.jenkins.io, we'll need to let developer knows on the mailing list. Reason is some plugins developers might have a badge on their `README.md|.adoc` and that would be a nice courtesy for them

**Comment by MarkEWaite** [comment]
Thanks for considering the impact on plugins @dduportal .  I find 169 plugin repositories that refer to embeddable build status from ci.jenkins.io.  The only harm from the removal is that the images will display as broken on the pages where they are referenced, but it would certainly be a nice gesture to plugin maintainers if we submitted pull requests that remove the embeddable build status references from those plugin pages.

**Comment by NotMyFault** [comment]
> but it would certainly be a nice gesture to plugin maintainers if we submitted pull requests that remove the embeddable build status references from those plugin pages.

If https://shields.io/ supports the use case of displaying a build status or code coverage for ci.jenkins, URLs could be updated to use that.
I know that @jetersen shared their workflow to update the maven cd action across a lot of repositories recently, unfortunately I don't have it at hand atm :(

**Comment by jetersen** [comment]
Check my gist profile 😃

**Comment by timja** [comment]
I came across this earlier could be useful:
https://github.com/lindell/multi-gitter

**Comment by jetersen** [comment]
multi gitter seems easier than whatever I was hacking away at.
Although I used code search to find the repos I needed to mess with.
There seems to be no filter options other than clone all repos in the org.

That is quite a few in jenkinsci org 😅

**Comment by lemeurherve** [comment]
multi-gitter is perfect for the job, thanks for the pointer @timja!

> There seems to be no filter options other than clone all repos in the org.

You can choose which repository you want to [include](https://github.com/lindell/multi-gitter/blob/master/README.md?plain=1#L199-L202) or [exclude](https://github.com/lindell/multi-gitter/blob/master/README.md?plain=1#L211-L213).

I've ran some tests, it doesn't take too long to run multi-gitter on all jenkinsci repositories, and there is a [concurrency parameter](https://github.com/lindell/multi-gitter/blob/master/README.md?plain=1#L124-L125) we can use if needed.

I've prepared the bulk PRs, ready to go, here is [the pull request](https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/34) I've generated as an example, WDYT?

**Comment by jetersen** [comment]
@lemeurherve couldn't you use shields.io? https://shields.io/category/build

**Comment by lemeurherve** [comment]
> couldn't you use shields.io? [shields.io/category/build](https://shields.io/category/build)

Damn, I should have checked it more thoroughly when @NotMyFault mentioned it, I'll look into it, thanks for the additional suggestion @jetersen 

> Also your commit shows up unsigned 😉

Yup, noticed that too, preparing a multi-gitter fix 🙂

**Comment by jetersen** [comment]
Seems like jenkins.io is not populating the json api anymore.
So shields.io won't work.

https://ci.jenkins.io/job/Plugins/job/scm-filter-branch-pr-plugin/job/master/api/json

Looking at the code for shields.io this the URL `https://ci.jenkins.io/job/Plugins/job/scm-filter-branch-pr-plugin/job/master` you would provide and it would append `/api/json` and look at the status field which is fairly innocent:

https://github.com/badges/shields/blob/c73072deed8eb6a5b9f51a06377f5f396ef21842/services/jenkins/jenkins-build.service.js#L72-L78

**Comment by lemeurherve** [comment]
> Seems like jenkins.io is not populating the json api anymore.

Do you/someone know where I can find more about this?

Their example instance is still providing the json: [`https://wso2.org/jenkins/view/All%20Builds/job/archetypes/api/json`](https://wso2.org/jenkins/view/All%20Builds/job/archetypes/api/json)

**Comment by dduportal** [comment]
Please note that blockign the APi on ci.jenkins.io is intentional alas (ref. https://github.com/jenkins-infra/helpdesk/issues/3042#issuecomment-1179682835 for details).

Is there a way to get the exhaustive list of IP from shields.io (assuming end users see an image from shields.io)? If each request to the shields.io label triggers an API request, then not sure how ci.jenkins.io will handle this (maybe we can cache the badges and clean it up hourly)?

**Comment by lemeurherve** [comment]
We can add a `cacheSeconds` parameter to the URL (from https://shields.io/endpoint/):
> cacheSeconds: (Default: 300, min 300.) Set the HTTP cache lifetime in seconds, which should be respected by the Shields' CDN and downstream users. Values below 300 will be ignored. This lets you tune performance and traffic vs. responsiveness. The value you specify can be overridden by the user via the query string, but only to a longer value

**Comment by lemeurherve** [comment]
@calebcartwright @chris48s is there a list of the IPs used by shield.io available somewhere so we could whitelist them to replace jenkinsci badges by shield.io ones?
I looked around but didn't found anything.

**Comment by lemeurherve** [comment]
Meanwhile, I managed to get PR with signed commit: https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/38

**Comment by dduportal** [comment]
> @calebcartwright @chris48s is there a list of the IPs used by shield.io available somewhere so we could whitelist them to replace jenkinsci badges by shield.io ones? ~I looked around but didn't found anything.~ Found [this page](https://github.com/badges/shields/blob/master/doc/production-hosting.md#badge-servers), will also ask on your discord server.
> 
> Also saw [badges/shields#4962](https://github.com/badges/shields/issues/4962) and [badges/shields#5346](https://github.com/badges/shields/pull/5346) I'm wondering if a similar token or a user/pwd pair could be added for ci.jenkins.io WDYT @dduportal ?

I'm not sure to understand: where would be store and use this user/password?

**Comment by lemeurherve** [comment]
IIUC, we could let shield.io requests pass with a token or a basic auth, which would be [stored as secrets server side](https://github.com/PyvesB/shields/blob/master/config/custom-environment-variables.yml#L74-L109).

**Comment by dduportal** [comment]
> IIUC, we could let shield.io requests pass with a token or a basic auth stored on our side as secret. On shield.io side, it would be [stored as secrets server side](https://github.com/PyvesB/shields/blob/master/config/custom-environment-variables.yml#L74-L109).

Can you dig a bit and lists here the procedure? The link you provided is a YAML file with a list of parameters referencing upper cases strings that I assume to be environment variables. 
But where are such token set up ? Is is a server managed by someone else ? A server to host on our own ? 

It seems a great feature but it really not clear what it does

**Comment by calebcartwright** [comment]
> @calebcartwright @chris48s is there a list of the IPs used by shield.io available somewhere so we could whitelist them to replace jenkinsci badges by shield.io ones?

As far as I know, we still do not view the the IP allowlist based approach for services to grant Shields.io an increased rate limit as being a viable strategy. We used to go this route with vendors/upstream services when our environment was deployed on lower level IaaS type services where we had more direct control over networking configuration, but our move to more PaaS/SaaS runtime environments largely obfuscates the networking specifics from us and is subject to change at any time beyond our control and without any warning nor notification.

As such, in cases where Shields.io would need to send more traffic to an upstream platform/service than their rate limits would permit, the path we've often taken is to collaborate with the upstream vendor/maintainers/etc. to obtain something Shields.io can then send in the request headers (most often auth related) whicht the upstream platform can then utilize to grant a higher rate limit to Shields.io specifically.

I confess I'm not fully up to date on the specifics of this thread and the various moving parts, but I believe/hope the above covers the Shields related questions. Let me know if not though, and/or if there's any other questions we can answer!

**Comment by dduportal** [comment]
> Now the question is: do we remove the existing embedabble badges or do we replace them with badges pointing to a self-hosted shield.io instance?

I vote we remove the plugin + badges (with the batch PR). But we mention the new issue https://github.com/jenkins-infra/helpdesk/issues/3044 to explain we are working on something else soon.

Reason of this "2 steps proposal": the origin of this issue is the security team asking to remove the plugin from ci.jenkins.io.

**Comment by daniel-beck** [comment]
> Reason of this "2 steps proposal": the origin of this issue is the security team asking to remove the plugin from ci.jenkins.io.

FTR we fixed what was wrong with the plugin in https://www.jenkins.io/security/advisory/2022-06-22/ with the maintainer's approval, but it's still not a well-maintained plugin, and fairly exposed. It is not urgent for us, but would be useful longer term.

**Comment by jglick** [comment]
https://github.com/jenkinsci/archetypes/pull/228 turned out to be prescient…

**Comment by jglick** [comment]
https://github.com/jenkinsci/embeddable-build-status-plugin/compare/embeddable-build-status-2.0.3...embeddable-build-status-2.0.4 FTR

**Comment by lemeurherve** [comment]
As @MarkEWaite and @darinpope [adopted the plugin](https://github.com/jenkins-infra/repository-permissions-updater/pull/2648), it doesn't have to be removed from ci.jenkins.io.

**Comment by lemeurherve** [comment]
Thanks for these links @jglick

**Comment by jetersen** [comment]
So no need to selfhost either? :)

**Comment by jetersen** [comment]
@lemeurherve perhaps you could write a gist or github repo for how you did the multi-gitter stuff :)

**Comment by lemeurherve** [comment]
@jetersen here is the corresponding gist: https://gist.github.com/lemeurherve/e2cd5d883ffa93ae21549dc78d4422ae

**Comment by jetersen** [comment]
@lemeurherve neat! I'll try and see what I can catch with multi-gitter.
