### ISSUE TITLE
Jenkins 2.346.1 still warns about Jenkins Security Advisory 2022-06-22

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkins-infra/helpdesk#3015]
### Service(s)

Update center

### Summary

I upgraded to Jenkins 2.346.1 but it still shows this warning about Jenkins Security Advisory 2022-06-22

> Warnings have been published for the following currently installed components:
>
> Jenkins 2.346.1 core and libraries
> [Multiple security vulnerabilities in Jenkins 2.355 and earlier, LTS 2.332.3 and earlier](https://www.jenkins.io/security/advisory/2022-06-22/)

Because the advisory itself says "Jenkins 2.356, LTS 2.332.4 and LTS 2.346.1 addresses these vulnerabilities", this warning should not be shown on Jenkins 2.346.1

### Reproduction steps

1. Install Jenkins 2.346.1.
2. Refresh the plugin listing in the update manager.
3. Observe the exclamation point shield icon in the page header.
4. Click the icon to display the warning.

**Comment by daniel-beck** [comment]
Thanks for letting us know! This should be fixed in ~5 minutes or so. Note that you need to re-request updated metadata (click "Check Now").

**Comment by dduportal** [comment]
Yep, the fix is not available because https://github.com/jenkins-infra/helpdesk/issues/3016. Should be fixed soon.

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/helpdesk/issues/3016 closed
- Just checked the update center on ci.jenkins.io + a local LTS container on the latest LTS: both stopped showing the warning.
