### ISSUE TITLE
Migrate doc from wiki to github for nutanix-calm plugin

### ISSUE THREAD

**Issue by HSDeshpande** [jenkins-infra/helpdesk#3018]
### Service(s)

Helpdesk

### Summary

Hello we have migrated our documentation to github readme 
https://github.com/jenkinsci/nutanix-calm-plugin/blob/master/pom.xml#L25 and made a release, but still the wiki page is not showing updated content.

**Comment by MarkEWaite** [comment]
https://plugins.jenkins.io/nutanix-calm/ shows the correct documentation for the plugin.  The heading ["Qualified Versions"](https://plugins.jenkins.io/nutanix-calm/#plugin-content-qualified-versions) is from the GitHub README, while on the wiki it uses a different heading.  The wiki is redirecting as well, so users cannot reach the old documentation any longer
