### ISSUE TITLE
CI setup for jenkins-infra/plugin-health-scoring

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3021]
Hello,

I need to setup the CI for the GSoC project Plugin Health Scoring project. (code: https://github.com/jenkins-infra/plugin-health-scoring).

There is nothing really fancy so far, so I'm not looking for a complete CD yet. Only a way to have:
 - build the jar file (don't even need to store it for now)
 - report static analyzes 
 - report test runs

I cannot find documentation on what I can do in the `Jenkinsfile` or what I'm not allowed to do. 

The project requires Java 17, it's using Maven Wrapper, so we don't really need Maven to be available in the VM / Container. We are working on building the Docker Image for the application, but as I said I don't need to build it now, this would be a problem for later.

**Comment by lemeurherve** [comment]
Let us know if you need anything else, closing this issue as the CI setup is done.

**Comment by alecharp** [comment]
I was just about to close it. Thank you @dduportal and @lemeurherve, the project has a CI build.
