### ISSUE TITLE
Grant kwhetstone merge permissions for 2 repositories

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3027]
### GitHub repositories

https://github.com/jenkins-infra/pipeline-metadata-utils
https://github.com/jenkins-infra/pipeline-steps-doc-generator

### GitHub users to have permission

@kwhetstone

### Permission level

Maintain

### Justification

Kristin is the original author of the Pipeline steps doc generator and is currently mentoring the Google Summer of Code 2022 project to improve the Pipeline steps doc generator.  These two repositories are crucial to the success of that GSoC project.

**Comment by timja** [comment]
Kristin was in the tools team originally and was moved to alumni as she was inactive at the time, she can take her access up again if someone can re-add her here:
https://github.com/orgs/jenkins-infra/teams/tools/members

**Comment by MarkEWaite** [comment]
> Kristin was in the tools team originally and was moved to alumni as she was inactive at the time

Thanks!  @dduportal , @lemeurherve , or @smerle33 do you have permission to add her?  Since she was already in the group before, I think it is reasonable to add her again without the full permission process.

**Comment by lemeurherve** [comment]
I've added back @kwhetstone to @jenkins-infra/tools

**Comment by MarkEWaite** [comment]
> Do the permissions of this team need to be changed to "maintain" on them?

Not as far as I know.  Thanks for handling this!
