### ISSUE TITLE
May JVM statistics not available

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3028]
### Service(s)

Other

### Summary

In https://stats.jenkins.io/plugin-installation-trend/jvms.json I see usage statistics all the way through to April 30, 2022. Since it is now June 28, I would expect to see at least the statistics for the month of May, but those statistics are not present.

### Reproduction steps

```
$ curl https://stats.jenkins.io/plugin-installation-trend/jvms.json | jq '.jvmStatsPerMonth | to_entries | last'    
{
  "key": "1651363200000",
  "value": {
    "1.5": 2,
    "1.6": 618,
    "1.7": 2165,
    "1.8": 185286,
    "10": 35,
    "11": 113628,
    "12": 44,
    "13": 55,
    "14": 61,
    "15": 130,
    "16": 63,
    "17": 485,
    "18": 187,
    "9": 35
  }
}
$ python -c 'import datetime; print(datetime.datetime.fromtimestamp(int("1651363200000") / 1000.0))'            
2022-04-30 17:00:00
```

**Comment by basil** [comment]
Applied by mistake, and then removed.

**Comment by abayer** [comment]
Ok, so I think this is just confusion - `1651363200000` isn't "data through this timestamp". For whatever reason (I didn't come up with the original structure), it's the _start_ time (in UTC) of the month. `1651363200000` is May 1, 2022, 00:00:00 UTC, identifying the data gathered in May.

**Comment by basil** [comment]
Got it, thanks for the clarification!

**Comment by basil** [comment]
Documentation update: https://github.com/jenkins-infra/jenkins-usage-stats/pull/4
