### ISSUE TITLE
Old password isn't accepted, reset email isn't sent

### ISSUE THREAD

**Issue by bagipro** [jenkins-infra/helpdesk#3030]
### Service(s)

Accounts

### Summary

Hello,

We have an account `oversecured`. The old password doesn't work on https://accounts.jenkins.io/login. Reset email isn't received too. Is there a problem?

Thanks!

**Comment by MarkEWaite** [comment]
@bagipro I've sent an email message to the email address registered to that account.  Once a response is received and I'm back at my desk, we'll generate a new password and share it with that account

**Comment by MarkEWaite** [comment]
I've confirmed that the account owner email address is responding and that the account owner email address has control of the @oversecured GitHub account.  New password has been sent
