### ISSUE TITLE
Grant permission to hpe-network-virtualization-plugin

### ISSUE THREAD

**Issue by itayka** [jenkins-infra/helpdesk#3033]
### GitHub repositories

https://github.com/jenkinsci/hpe-network-virtualization-plugin.git

### GitHub users to have permission

@itayka

### Permission level

Admin

### Justification

Hi,
My name is Itay Karo. I am the only contributor to the hpe-network-virtualization-plugin. I developed it 6 year ago while I was working in HP Enterprise company. This plugin added support for one of our products: Network Virtualization. Since then, the company merged with another company: Micro Focus. Now, I was asked to remove this plugin since the Network Virtualization product reached EOL. The plugin was not maintained for that last 6 years and currently has many security issues. Since it was decided to remove it, I can't login with my old user: itay.karo@hpe.com. I would like to be granted admin permissions since I am the developer of this plugin.

Regards,
Itay Karo

**Comment by timja** [comment]
Do you still have access to the Jira account [itay_karo_hpe](https://issues.jenkins.io/secure/ViewProfile.jspa?name=itay_karo_hpe) to verify your ownership?

If you do just update your name to include 3033 temporarily or create an issue pointing to this and comment it here.

**Comment by itayka** [comment]
I do not. Since my previous email, itay.karo@hpe.com, was decommissioned I can't reset the password.

**Comment by timja** [comment]
For https://github.com/jenkins-infra/update-center2#deprecations you can just use the web UI to edit the file, it will handle all the forking for you automatically.

----

I've granted you access given the situation, no one else has access to it, and it's not been touched in years.
