### ISSUE TITLE
Releases as infra meeting notes

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3040]

**Comment by lemeurherve** [comment]
Corresponding first (test) release: https://github.com/jenkins-infra/helpdesk/releases/tag/infra-team-sync-2022-07-08_1

**Comment by hervelemeur** [comment]
Possible improvments:
- update existing release if there is one
- create hackmd note with full template
- add automation on release events:
  - on publish:
    - create new milestone (could be on "current" milestone close)
    - add new milestone to readme
    - add release to readme

**Comment by dduportal** [comment]
> 

That is already a lot of usefull automation, thanks buddy!
