### ISSUE TITLE
Change request view hangs

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#3043]
### Service(s)

ci.jenkins.io

### Summary

I want to view the change requests for Jenkins core builds, however the page https://ci.jenkins.io/job/Core/job/jenkins/view/change-requests/ never finishes to load. Is this a Jenkins bug or a problem with our infrastructure?

### Reproduction steps

1. Open https://ci.jenkins.io/job/Core/job/jenkins/view/change-requests/
2. Nothing happens, the request times out with 
```
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server
```

**Comment by NotMyFault** [comment]
See https://github.com/jenkins-infra/helpdesk/issues/3029 for more info

**Comment by dduportal** [comment]
Thanks for reporting @uhafner ! 

Closing as duplicate of #3029 .
