### ISSUE TITLE
Remote access API on every non-ci.j.io instance

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#3045]
### Service(s)

cert.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

Could every private instance have the remote API accessible? 🥺

With authentication required on those instances, and Basic authenticated requests allowed by the reverse proxy rule, the only difference is interactive use, which I attempt occasionally. Not a blocker, but just one of those behaviors improperly applied to private instances because ci.j.io had it.

release.ci and infra.ci are unaffected (Kubernetes special?) but trusted.ci and cert.ci are.

**Comment by lemeurherve** [comment]
We'll disable ci.jenkins.io, trusted.ci.jenkins.io and cert.ci.jenkins.io for the next minutes in order to update their configurations.

**Comment by daniel-beck** [comment]
@lemeurherve Doesn't work for me. Going to https://cert.ci.jenkins.io/api/xml still redirects me to https://www.jenkins.io/infra/ci-redirects/

**Comment by lemeurherve** [comment]
Damn, there is another directive redirecting `api/xml` instead of "emptying" it: https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/manifests/jenkinscontroller.pp#L352-L353

Preparing a pull request to fix it.

**Comment by lemeurherve** [comment]
- https://cert.ci.jenkins.io/api/json ✅ 
- https://cert.ci.jenkins.io/api/xml ✅ 
- https://trusted.ci.jenkins.io:1443/api/json ✅ 
- https://trusted.ci.jenkins.io:1443/api/xml ✅ 
- https://ci.jenkins.io/api/json empty ✔️ 
- https://ci.jenkins.io/api/xml redirect ✔️

**Comment by daniel-beck** [comment]
Thanks! Used it today for a purpose other than testing already.
