### ISSUE TITLE
Remove my account

### ISSUE THREAD

**Issue by tobias-** [jenkins-infra/helpdesk#3046]
### Service(s)

Accounts

### Summary

Please remove my account. It seems I get security notifications about a project I'm no longer involved in and haven't been in almost a year.

My account on jenkins.io is `tobias_` and the github account for that account is this account (tobias-).

TIA
/Tobias

**Comment by tobias-** [comment]
FYI: I have blocked my noreply@jenkins.io because of unwanted emails, so iit will be hard to get automated confirmation of my intent.

**Comment by NotMyFault** [comment]
Hey,

I followed the convo on IRC a bit. You can file a PR on https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-lucene-search.yml#L11 and remove yourself from the plugin if you are no longer maintaining it.

**Comment by dduportal** [comment]
Thanks, I confirm that:
- we received an email from the same adresse specified on your Jenkins.io 's account
- we are able to link your GitHub account here with your jenkins.io account.

Proceeding to deletion...

**Comment by dduportal** [comment]
Account deleted on jenkins.io.

Many thanks for your past contributions on the Jenkins project!
