### ISSUE TITLE
Update analysis-model and warnings-ng on ci.j

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3051]
### Service(s)

ci.jenkins.io

### Summary

Hey,

could we update analysis-model-api to 10.13.0 and warnings-ng to 9.14.0 on ci.j please?
I added support for Stylelint as linter and I'm looking forward to use this functionality for core builds on ci.j

Thanks in advance!

**Comment by lemeurherve** [comment]
These plugins will be updated in time, it just need the time to be catched up [in pull requests like this one](https://github.com/jenkins-infra/docker-jenkins-lts/pull/533/files).
We usually review and merge these kind of PRs the day they're opened, closing this issue, let us know if it's really urgent.

**Comment by NotMyFault** [comment]
Oic, thanks for the clarification. Not urgent for sure, but dduportal let me know yesterday, that not all installed plugins and versions are managed by that, hence the issue raised.

**Comment by lemeurherve** [comment]
I discussed with @dduportal, I shouldn't have closed this issue indeed, sorry, let me take care of it.

**Comment by dduportal** [comment]
My aploogies to both of you: I did not share enough information so it mislead Herve.

But this issue is legit, and now knowledge had been shared with Herve so we can handle this request.
Thanks for reproting @NotMyFault and sorry for the delay!

**Comment by lemeurherve** [comment]
Updates OK:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/91831478/178483763-e14ddc50-817a-4981-ba10-42faa54a13ca.png">
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/91831478/178483814-03e5519a-8773-40bb-bbf7-36365cc150a4.png">
