### ISSUE TITLE
Update Jenkins to 2.346.2

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3055]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

It's LTS time again and 2.346.2 has been shipped for GA 🎉

**Comment by dduportal** [comment]
The 4 controller had been upgraded to the new LTS. Many thanks @NotMyFault
