### ISSUE TITLE
Install `github-comment-ops`

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3060]
### Service(s)

Other

### Summary

Hi

I've made a tool https://github.com/timja/github-comment-ops that can allow managing issues and pull requests by users without write access.

It has features like:
- label
- request reviews
- close / reopen
- transfer issues

See the [README](https://github.com/timja/github-comment-ops)  for all features and required permissions.

It is powered by GitHub apps and is multi-tenanted so will work for any organizations that it's installed to, (i.e. only one deployment is needed).

Could we deploy this please?

I've created a helm chart for it:
https://github.com/timja/github-comment-ops/tree/main/charts/github-comment-ops

Let me know of any issues / feedback, I'd be interested in someone else doing the setup to get any feedback from something I've missed

**Comment by timja** [comment]
FYI @basil / @jglick you may be interested

**Comment by lemeurherve** [comment]
Who can use these commands?

**Comment by timja** [comment]
Anyone

**Comment by jglick** [comment]
> close / reopen

Limited to issues for non-members, I would hope.

**Comment by NotMyFault** [comment]
Are you looking forward to enable that on the jenkinsci org?

**Comment by timja** [comment]
> > close / reopen
> 
> Limited to issues for non-members, I would hope, and not pull requests.

Yes I only implemented it for issues:
https://github.com/timja/github-comment-ops/blob/main/app/github.js#L367-L392

**Comment by timja** [comment]
Tested to make sure:
https://github.com/timja-org/test-product-infra/pull/31

<img width="936" alt="image" src="https://user-images.githubusercontent.com/21194782/180023082-1abbeea8-6de5-4111-9077-bd5c4f8b5b9a.png">

It's not handled properly as there's a stacktrace because it still tries to close it, but it only has the code for issues

**Comment by lemeurherve** [comment]
> https://github.com/timja-org/test-product-infra/pull/31

Private repo? Got a "page not found"

**Comment by lemeurherve** [comment]
Demo: https://www.youtube.com/watch?v=t1BSLRPNeQ4&t=2060s

**Comment by lemeurherve** [comment]
GHA created: https://github.com/apps/comment-ops-bot

Permissions:
- Issues: Read & Write
- Pull requests: Read & Write
- Organizations.Members: Read only

**Comment by lemeurherve** [comment]
DNS record added:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/91831478/180178049-3ee073b6-feb7-46c3-9644-f28b4e945801.png">

**Comment by lemeurherve** [comment]
GHA webhook configured to `https://webhook-github-comment-ops.jenkins.io/api/github/webhooks`

<img width="791" alt="image" src="https://user-images.githubusercontent.com/91831478/180189344-b79d2596-cdf1-43eb-89fd-efcaf8c1cdd7.png">

**Comment by lemeurherve** [comment]
Added missing subscription to "issue comment" and "issue" events in [the GitHub App settings](https://github.com/organizations/jenkinsci/settings/apps/comment-ops-bot/permissions):

<img width="783" alt="image" src="https://user-images.githubusercontent.com/91831478/180196955-8a193693-42ba-4309-9e37-ae8a47b16175.png">

**Comment by lemeurherve** [comment]
It works 🎉 

Example: https://github.com/jenkinsci/jenkins-infra-test-plugin/issues/42

<img width="936" alt="image" src="https://user-images.githubusercontent.com/91831478/180197304-fc67a7a3-8f7e-4a8e-b6b0-e5f3915be1eb.png">

**Comment by timja** [comment]
https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/40#issuecomment-1191373934

![image](https://user-images.githubusercontent.com/21194782/180204029-90eb8fb5-3598-4ef6-bfe6-8049e1e14976.png)

**Comment by timja** [comment]
@lemeurherve did you want to raise an issue with any confusion you had or improvements?  or PR the README directly?

**Comment by lemeurherve** [comment]
I'll prepare a PR later :)

**Comment by jglick** [comment]
There is a bit of a discoverability problem here. How are users supposed to remember the list of supported commands, or find out that the whole system exists to begin with?

**Comment by lemeurherve** [comment]
> How are users supposed to remember the list of supported commands

I've suggested https://github.com/timja/github-comment-ops/issues/36 as a first improvement.

> find out that the whole system exists to begin with?

Some suggestions:
- Announcement in the mailing list(s)
- Link/quick explanation in https://github.com/jenkinsci/.github/tree/master/profile

I fear some/most won't discover this functionality, but I think the curious/frequent contributors will quickly notice these comments and what they do.

**Comment by lemeurherve** [comment]
Also, a link/quick explanation could be added as comment in the issue and pull request templates
- of the jenkinsci/.github repo
- in the main jenkinsci repo

Another (noisy) possibility: make the GitHub App comments on every new issue/PR with an "help" message.

**Comment by timja** [comment]
I plan to announce, and update the core PR template.

I was planning to hold announcing till I fixed some of these issues that people have raised, but can also announce later on today if people prefer that

**Comment by jglick** [comment]
Oh a question about `/reviewer`. AFAIK GH actively blocks you from _requesting_ a review from someone who is not a member of the org. (Even if the repo is public, and their only permission is read, which is otherwise redundant. And even though anyone can review any public PR without write access, including “suggesting” rather than “requesting” changes.) So this could be used by someone with no role in @jenkinsci but only to request review from someone who _does_ have a role, not some other rando, right?

**Comment by timja** [comment]
Yes correct

**Comment by lemeurherve** [comment]
GitHub App installed on jenkins-infra org too 🙂

**Comment by timja** [comment]
and on https://github.com/timja/github-comment-ops

**Comment by timja** [comment]
At Daniel's request I've temporarily limited the repositories in the jenkinsci org to:

- jenkins
- design-library-plugin
- jenkins-infra-test-plugin
This is to gather feedback and in a couple of weeks if there's no objections we can enable globally.

There is a jenkinsci developer thread at: https://groups.google.com/g/jenkinsci-dev/c/sE7mH7hUZSY

**Comment by lemeurherve** [comment]
I've done the same on jenkins-infra organization, it's now activated only on https://github.com/jenkins-infra/helpdesk

I'll open an issue to gather the use cases for jenkins-infra and the repositories needing it.
