### ISSUE TITLE
JFrog repo.j.o does not let me in

### ISSUE THREAD

**Issue by jimklimov** [jenkins-infra/helpdesk#3061]
### Service(s)

Artifactory

### Summary

1. I go to https://repo.jenkins-ci.org/ui/login/
2. I enter my username (jimklimov) and password, which work for JIRA issues.j.o
3. Currently I get "Login has failed. Due to Incorrect username/password or locked user."

Initially the issue was hit as a failure to publish a maintained plugin build. I last published (I think) about 3 months ago.

**Comment by timja** [comment]
@daniel-beck you able to check this?

**Comment by MarkEWaite** [comment]
I'm able to logout and login from https://repo.jenkins-ci.org/  

I don't see anything on accounts.jenkins.io that would indicate @jimklimov is locked out from accounts.  I don't have admin access to repo.jenkins-ci.org, so can't answer if the account is locked out of that single service.

**Comment by daniel-beck** [comment]
Artifactory doesn't like it when you're email address is messed up. Fix it to be an actual email address, rather than `jimklimov`, in accounts.jenkins.io.

**Comment by jimklimov** [comment]
Cool, so that was it. Apparently, when I was changing the password recently from an Android browser, it "helpfully" substituted username and password, nuking field contents for mail, ssh key, etc.
