### ISSUE TITLE
ci.jenkins.io permissions for contributor

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/helpdesk#3065]
### Service(s)

ci.jenkins.io

### Summary

Perhaps I can ask for ci.jenkins.io build/rebuild permission?

I frequently contribute to plugins in regards to bom or when I feel like contributing to an open source plugin.

Sometimes plugins need their Jenkinsfile updated which requires write permissions. Though with rebuild you can replace the pipeline.

**Comment by dduportal** [comment]
Hello @jetersen thanks for raising this issue.

This request implies giving you administrator privileges on ci.jenkins.io. 
Could you send an email to the jenkinsci-dev mailing list , linking to this issue and asking the community and maintainer about this, along with adding the motivation?

The goal is to get enough board members and officers to validate this request (and no objection or solution that we missed there that would allow you to build/rebuild without requiring admin permissions).

As infra officer, I am all ok to give you this right given the work you did in the past and currently on the infra and project.

**Comment by daniel-beck** [comment]
Since you're maintainer of at least one plugin, you push the branch of whichever plugin you're working on into that other repo, and ci.j.io will pick that up and other than incrementals deployment (rejected) it should behave the same. It's a bit weird but it should work.

**Comment by dduportal** [comment]
As discussed during the last infra meeting: @jetersen can you ask on the mailing list to validate that we can give you additional permissions given your contributions on the infra + plugins?

Rationale is that the permission model of ci.jenkins.io makes mandatory to be maintainer of a repo to edit the `Jenkinsfile` and replay builds, unless you ar an admin (or elevated permissions) of the controller.

On short term, you should be able to use Daniel's trick.

**Comment by dduportal** [comment]
Closing this as it's an old issue and the solution was given (as maintainer)
