### ISSUE TITLE
A number of teams are historically secret preventing review requests

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/helpdesk#3066]
### Service(s)

GitHub

### Summary

Missing jenkinsci/metrics-plugin-developers team, cannot request for review on plugin: https://github.com/jenkinsci/metrics-plugin/pull/175#issuecomment-1193081012
Missing jenkinsci/ssh-credentials-plugin-developers team
Missing jenkinsci/variant-plugin-developers

**Comment by NotMyFault** [comment]
I can't verify that, but I assume the teams are private? That used to be the typical case when I'm adopting plugins.

**Comment by timja** [comment]
I've fixed the 3 in the request but there will be a lot more, I've made the title of this generic so we can fix all of them.

A script should be written to update them all

**Comment by jetersen** [comment]
@timja I could help with the script, if I got the appropriate access? 😅 🗡️

**Comment by jetersen** [comment]
I can also create a test in my `jetersen-cloud` org :)

**Comment by timja** [comment]
would be great :), testing in another org should be fine, just a list all teams and update them to be visible sort of thing

**Comment by jetersen** [comment]
@timja something like this should do with the github cli:

```bash
gh api --paginate orgs/jenkinsci/teams --jq '.[] | select(.privacy == "secret") | .slug | select(endswith("developers"))' | xargs -I % gh api -X POST orgs/jenkinsci/teams/% --input - <<< "{\"privacy\":\"closed\"}"
```

**Comment by jetersen** [comment]
You could use xargs into sh to put a sleep between each request 😅 depending on how many teams we are dealing with.

**Comment by timja** [comment]
The above didn't quite work, I modified it to:
```
gh api -X PATCH orgs/jenkinsci/teams/% --field privacy=closed
```

**Comment by jetersen** [comment]
Makes sense I didn't look to closely to API, I guess.

**Comment by NotMyFault** [comment]
More teams than repositories 👀

**Comment by timja** [comment]
It's completed, this returns nothing now:
```
gh api --paginate orgs/jenkinsci/teams --jq '.[] | select(.privacy == "secret") | .slug | select(endswith("developers"))'
```
