### ISSUE TITLE
Access to npm namespace

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3067]
https://www.npmjs.com/~jenkinsio - not claimed
https://www.npmjs.com/org/jenkins-cd - currently used by most of blueocean project as well as some other random modules.
https://www.npmjs.com/~jenkinsci - tom's account
https://www.npmjs.com/~jenkins - squatted on?

I want to be able to release https://www.npmjs.com/package/@halkeye/jenkins-io-react to a @jenkins namespace. Its going to be used on stories, hopefully plugins soon, and hopefully others.

**Comment by lemeurherve** [comment]
Status:
- Currently retrieving ~jenkinsci with @tfennelly
- Opened [a reclaim ticket](https://docs.npmjs.com/policies/disputes/) on npm for ~jenkins (#1745379)
- Trying to understand the diff between org (?) with a tilde or not in order to eventually create ~jenkinsio
- ~jenkins-cd is owned by @bwalding, I don't think it needs to be changed.

**Comment by lemeurherve** [comment]
Waiting for the dispute to be resolved to create/convert the user "jenkins" in an organisation.

**Comment by halkeye** [comment]
So whats the status here? Can I get access now? or should I still publish to my own namespace?

**Comment by lemeurherve** [comment]
I've asked for update on the support ticket to reclaim `jenkins` but still no response.

About the `jenkinsci` account, trying to follow their procedure with "forgot password" to retrieve it (as Tom configured the private infra mail on the account), I've got the following error:

> looks like something unexpected occurred!
> diagnostics id: 7482c4e2c9e8d4e5_28d3

Either:
- we wait a bit more
- I create a new "jenkinsio" org
- I open a ticket about the error trying to retrieve "jenkinsci" account
- you still publish under your own namespace

**Comment by halkeye** [comment]
What do we want to do here? I'd really like to see the web components official as I'm adding them to projects.

**Comment by NotMyFault** [comment]
> I open a ticket about the error trying to retrieve "jenkinsci" account

Personally, I'd like to go with this option, even if it's more work, I'd rather have an official namespace, but these are only my two cents.

**Comment by lemeurherve** [comment]
I've got a response from GitHub support, unfortunately they can't release the `jenkins` namespace as it contains private packages.
They also took a look at my other request about the `jenkinsci` account, I've just confirmed them we have access to the private infra email set to this account I'm waiting for the next steps, some progress at least 🙂

**Comment by halkeye** [comment]
okay thanks for keeping on it!

**Comment by lemeurherve** [comment]
With the help of @tfennelly I've finally retrieved the `jenkinsci` npm account 🎉

I've made a typo in the mail I initially gave him, it took some time to catch that.
Thanks Luca from GitHub support to have noticed it!

**Comment by halkeye** [comment]
Thats really exciting.

So whats next steps?

My vote is [convert it to an organization](https://docs.npmjs.com/converting-your-user-account-to-an-organization), then can I get access?

**Comment by lemeurherve** [comment]
> My vote is [convert it to an organization](https://docs.npmjs.com/converting-your-user-account-to-an-organization), then can I get access?

@halkeye I've converted it to an organisation and invited you :)

Let me know if it's enough for releasing https://www.npmjs.com/package/@halkeye/jenkins-io-react to the `jenkinsci` namespace so I can close this issue.

**Comment by halkeye** [comment]
can you re-invite me? I think my @halkeye.net domain which npm was using, is no longer getting emails. I've switched over to my primary domain.

**Comment by lemeurherve** [comment]
@halkeye I've re-invited you.

**Comment by halkeye** [comment]
Awesome I'm in. I'll update https://github.com/halkeye/jenkins-io-components to publish to the new org, then i think we can close this

**Comment by halkeye** [comment]
\o/ https://www.npmjs.com/package/@jenkinsci/jenkins-io-components works

I'm happy to close this now. I'm not sure if you want to leave it open for tracking progress of moving the github repo as well

**Comment by lemeurherve** [comment]
Let's close this issue and create another one for moving the repo.
