### ISSUE TITLE
Switch to JDK17 for Jenkins controllers and agents

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3072]
### Service(s)

infra.ci.jenkins.io

### Summary

As per https://community.jenkins.io/t/platform-sig-jun-17-2022/2779/6 , it would be a nice milestone for the infra team to start using JDK17:

- Supporting all the community members involved in the JDK17 support effort
- Start using it in real life ("eat our own dog food" as the adage says)
- Benefit from the huge performance improvements

There are 2 main steps:

- Switching the controller to JDK17 (infra.ci and weekly.ci as they use the same Docker image)
- Switching agents to JDK17 (https://github.com/jenkins-infra/packer-images/issues/282 would be a great 1st step for Linux container agents, while all VM agents already have JDK17 installed so only a matter of agent template config)

Ping @basil @MarkEWaite : do you know if a controller with JDK17 can work with JDK11 agents? Question is to be sure that we can accept a "transition" period with some agents already using JDK17, and some still in JDK11 time we track and fix them all.

**Comment by timja** [comment]
same experience, as long as you aren't using the maven plugin it generally works fine in practice.

**Comment by dduportal** [comment]
There is an issue on the `maven-11*` container agents on ci.jenkins.io with their default configuration:

```
mvn -v
14:31:33  Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
14:31:33  Maven home: /usr/share/apache-maven-3.9.4
14:31:33  Java version: 17.0.8, vendor: Eclipse Adoptium, runtime: /opt/jdk-17
14:31:33  Default locale: en_US, platform encoding: UTF-8
14:31:33  OS name: "linux", version: "5.10.179-168.710.amzn2.x86_64", arch: "amd64", family: "unix"
```

=> most of the builds (plugins, core) are using Jenkins "tool" or explicit JAVA_HOME but this need to be fixed

**Comment by dduportal** [comment]
> There is an issue on the `maven-11*` container agents on ci.jenkins.io with their default configuration:
> 
> ```
> mvn -v
> 14:31:33  Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
> 14:31:33  Maven home: /usr/share/apache-maven-3.9.4
> 14:31:33  Java version: 17.0.8, vendor: Eclipse Adoptium, runtime: /opt/jdk-17
> 14:31:33  Default locale: en_US, platform encoding: UTF-8
> 14:31:33  OS name: "linux", version: "5.10.179-168.710.amzn2.x86_64", arch: "amd64", family: "unix"
> ```
> 
> => most of the builds (plugins, core) are using Jenkins "tool" or explicit JAVA_HOME but this need to be fixed

- Fixed by https://github.com/jenkins-infra/jenkins-infra/commit/f5cade3f3c4c468ed4e5874f38413e0885ef5c0e for `maven-11`

**Comment by dduportal** [comment]
Problem still present for the maven-11 though:

```
17:18:47  C:\Jenkins\agent\workspace\e-tests_check-agent-availability>mvn -v 
17:18:47  Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
17:18:47  Maven home: C:\tools\apache-maven-3.9.4
17:18:47  Java version: 17.0.8, vendor: Eclipse Adoptium, runtime: C:\openjdk-17
17:18:47  Default locale: en_US, platform encoding: UTF-8
17:18:47  OS name: "windows server 2019", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by dduportal** [comment]
- All problems fixed in ci.jenkins.io
- Release process running JDK17 for agents and JDK11 for builds. We can close.
