### ISSUE TITLE
Jenkins 2.361 built with JDK 11.0.14 instead of 11.0.15 or 11.0.16

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3073]
### Service(s)

release.ci.jenkins.io

### Summary

The [Jenkins 2.361 weekly build log](https://release.ci.jenkins.io/job/core/job/weekly/job/release/job/master/150/console) on release.ci.jenkins.io reports that the build is being performed by JDK 11.0.14 rather than the more common 11.0.15 or the recently released 11.0.16.

It is not harmful that we built with a slightly older JDK, but it is surprising and may be worth investigating the configuration of the agents or the build job to understand why they are running a JDK that is older than most other agents in the Jenkins infrastructure.

### Reproduction steps

1. Open the [Jenkins 2.361 weekly build log](https://release.ci.jenkins.io/job/core/job/weekly/job/release/job/master/150/console) 
2. Search for 11.0.14 and confirm that is the version used
3. Open [ci.jenkins.io most recent successful build](https://ci.jenkins.io/job/Core/job/jenkins/job/master/lastSuccessfulBuild/console) and note that it is using 11.0.15 for most of its uses, though there are a few references to 11.0.13 in the log file as well

## Actual result

Weekly release is built with JDK 11.0.14

## Expected result

Weekly release is built with JDK 11.0.15 or JDK 11.0.16

**Comment by dduportal** [comment]
Quick diagnostics:

- The build was run in a container image `jenkinsciinfra/packaging:2.1.49` as per https://release.ci.jenkins.io/job/core/job/release/job/master/164/consoleFull
- This image uses parent agent image 4.13-2 as per https://github.com/jenkins-infra/docker-packaging/blob/2.1.49/Dockerfile#L1-L3

=> I assume that 4.13(.0)-2 is the image with the 11.0.14 JDK within. Another argument for the "all in one" definition (https://github.com/jenkins-infra/packer-images/issues/282 for Linux and https://github.com/jenkins-infra/packer-images/issues/285 for Windows)

**Comment by smerle33** [comment]
I did https://github.com/jenkins-infra/docker-packaging/commit/488a7c75e0097153b60f340295a1ed317a5675ad that provide an updatecli stream of update, and this PR https://github.com/jenkins-infra/docker-packaging/pull/46 should update the docker image and provide the correct JDK version.

**Comment by dduportal** [comment]
Thanks @smerle33 . Now that https://github.com/jenkins-infra/release/pull/276, the image is specified in the pipeline with the `2.1.54` tag.

And as expected:

```console
docker run --rm --entrypoint=java jenkinsciinfra/packaging:2.1.54 -ve
rsion
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```
