### ISSUE TITLE
Request to have maintainer access on mapdb-api-plugin

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3077]
### GitHub repositories

https://github.com/jenkinsci/mapdb-api-plugin

### GitHub users to have permission

@alecharp
@cloudbees-developpers

### Permission level

Maintain

### Justification

Based on RPU (https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-mapdb-api.yml) all members of `cloudbees-developers` are able to release the plugin, but based on https://github.com/orgs/jenkinsci/teams/mapdb-api-plugin-developers only @stephenc is able to merge pull requests on the repository.

**Comment by timja** [comment]
done
