### ISSUE TITLE
Some unexpected error occurred when executing shell script

### ISSUE THREAD

**Issue by LeoLuo21** [jenkins-infra/helpdesk#3079]
### Service(s)

release.ci.jenkins.io

### Summary

Build step 'Execute shell' marked build as failure

### Reproduction steps

1.New Item
2.Select Freestyle project
3.Click **Configure** of the left bar in newly created project
4.Find out the build area, choose add **execute shell**
5.paste the following content
```
#!/bin/bash -xe
pid=`lsof -t -i:10001`
echo "pid=$pid"
if [ -n "$pid" ]; then
	kill -9 $pid
	echo "$pid has been killed."
fi
```
6.Click **BuildNow**
7.In Console Output: You will see 
```
[jenkins-demo] $ /bin/bash -xe /tmp/jenkins6013219052354131704.sh
++ lsof -t -i:10001
+ pid=
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by dduportal** [comment]
Hi @LeoLuo21 , thanks for reporting.

This issue tracker is scoped to the Jenkins Infrastructure as stated in [README](https://github.com/jenkins-infra/helpdesk/blob/main/README.md), so I'm going to close this issue as "not planned".

It looks like that you have an issue with your Jenkins instance instead: you should open a topic on the community forum at community.jenkins.io to get a broader community help, or open an issue on the [officiale Jenkins bug tracker](https://issues.jenkins.io/projects/JENKINS) if it is a bug that you can describe with a reproduction case.
