### ISSUE TITLE
New Gradle Plugin Group ID requiring proof of `jenkins.io` domain ownership

### ISSUE THREAD

**Issue by steven-terrana** [jenkins-infra/helpdesk#3080]
### Service(s)

Other

### Summary

Hello, 

Per https://github.com/jenkins-infra/repository-permissions-updater/issues/2670, I am trying to host a Gradle Plugin under a new group id: `io.jenkins.tools`. 

Doing this will require proof of ownership of the `jenkins.io` domain through a DNS TXT record. 

From the Gradle Plugin Portal team:
> Please prove ownership of the "[jenkins.io](http://jenkins.io/)" domain by adding a TXT record with value "gradle-verification=QH6WADZ8BZPQXNH3VBM2TXX288R7P" to your DNS.

How can we go about this?

**Comment by smerle33** [comment]
DNS have been updated : 
![Capture d’écran 2022-08-02 à 16 47 31](https://user-images.githubusercontent.com/95630726/182403835-ca47d83e-cbed-4f70-b8a7-4f89176f5113.png)
