### ISSUE TITLE
Certificate Authority Authorization to secure certificate delivery

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3083]
### Service(s)

Other

### Summary

In order to add security to certificate delivery we should ensure that we got a domain CAA record as per https://letsencrypt.org/docs/caa/ 

### Reproduction steps

https://caatest.co.uk/jenkins.io

**Comment by timja** [comment]
Be careful with this and make sure all places that could issue certificates are covered.

i.e. repo.jenkins-ci.org (not sure if any others don't use let's encrypt

**Comment by dduportal** [comment]
As per https://sslmate.com/caa/ + https://www.certificate-transparency.org/:

- `jenkins.io` uses certificates delivered by "amazon.com", "globalsign.com" and "letsencrypt.org"
- `jenkins-ci.org` uses certificates delivered by "amazon.com", "godaddy.com" and "letsencrypt.org"
- `jenkinsistheway.io` uses certificates deliverez by "godaddy.com" and "letsencrypt.org"

The CAA records to be created (with a minimal TTL):


```console
| Name               | Type   | Value                       |
|--------------------|--------|-----------------------------|
| jenkins.io.        | CAA    | 0 issue "amazon.com"        |
|                    |        | 0 issue "globalsign.com"    |
|                    |        | 0 issue "letsencrypt.org"   |
|                    |        | 0 issue "godaddy.com"       |
| -------------      | ------ | --------------------------- |
| jenkins-ci.org.    | CAA    | 0 issue "amazon.com"        |
|                    |        | 0 issue "globalsign.com"    |
|                    |        | 0 issue "letsencrypt.org"   |
|                    |        | 0 issue "godaddy.com"       |
| -------------      | ------ | --------------------------- |
| jenkinsistheway.io | CAA    | 0 issue "amazon.com"        |
|                    |        | 0 issue "globalsign.com"    |
|                    |        | 0 issue "letsencrypt.org"   |
|                    |        | 0 issue "godaddy.com"       |
```

**Comment by dduportal** [comment]
Ping @Wadeck @daniel-beck @MarkEWaite @timja does it looks good to you?

**Comment by Wadeck** [comment]
Not enough DNS expert to reply :)

**Comment by dduportal** [comment]
Done:

- https://caatest.co.uk/jenkins.io:

```console
✔ All looks good
---
0 issue "amazon.com"
0 issue "globalsign.com"
0 issue "letsencrypt.org"
0 issue "godaddy.com"
```

- https://caatest.co.uk/jenkins-ci.org:

```console
✔ All looks good
---
0 issue "amazon.com"
0 issue "globalsign.com"
0 issue "letsencrypt.org"
0 issue "godaddy.com"
```

- https://caatest.co.uk/jenkinsistheway.io:

```console
✔ All looks good
---
0 issue "amazon.com"
0 issue "globalsign.com"
0 issue "letsencrypt.org"
0 issue "godaddy.com"
```
