### ISSUE TITLE
Publish `pipeline-steps-doc-generator` and `backend-extension-indexer` artifacts to some kind of storage

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3087]
### Service(s)

infra.ci.jenkins.io

### Summary

https://github.com/jenkins-infra/jenkins.io/blob/9addc32ac8d366e02a9ec49e07e81ab527547cf4/scripts/fetch-external-resources#L36
and
https://github.com/jenkins-infra/jenkins.io/blob/9addc32ac8d366e02a9ec49e07e81ab527547cf4/scripts/fetch-external-resources#L66

cause site publishing to be reliant on ci.jenkins.io being up.

Which makes ci.jenkins.io a critical path for publishing security advisories and for contributors developing local site builds.

We should decouple these by publishing to some kind of storage.
Either `reports.jenkins.io` or an Azure storage, these need to be published publicly somewhere that any contributors machine can download from

see also https://github.com/jenkins-infra/helpdesk/issues/3086#issuecomment-1206820973

**Comment by dduportal** [comment]
@timja @daniel-beck do you agree with the following proposal?

1. Migrating the job from ci.jenkins.io to infra.ci.jenkins.io, with the github checks enabled (e.g. build log shown in GitHub publicly)
2. Adding a deployment to `reports.jenkins.io` (like the other reports) with the pipeline method  `publishReports()`
3. Update the github.com/jenkins-infra/jenkins.io's shell script `fetch-external-resources.sh` to use reports.jenkins.io instead of ci.j
4. Once validated, then remove the job from ci.jenkins.io

**Comment by timja** [comment]
sounds good

**Comment by daniel-beck** [comment]
> do you agree with the following proposal?

Yes, absolutely, this has been terrible for a long time. We didn't have reports.j.io when this was set up, so this was a pragmatic way to do this.

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/jenkins.io/pull/5667 for the switch of jenkins.io.

next step will be to remove the 2 jobs from ci.jenkins.io.

**Comment by dduportal** [comment]
Both pipeline marked as archived in ci.jenkins.io (removed from the "include list" trait of the GH org scanning named `Infra`).

**Comment by daniel-beck** [comment]
> Both pipeline marked as archived in ci.jenkins.io

To clarify, there is no value in having a public CI there?

**Comment by timja** [comment]
They definitely should have public CI

**Comment by dduportal** [comment]
ack, reopening to enable again public CI then

**Comment by smerle33** [comment]
in the process of merging the pipeline files from ci and infra.ci (to provide a public output), I will try to take the process for : `pipeline-steps-doc-generator` and leave `backend-extension-indexer` to @dduportal

**Comment by dduportal** [comment]
Just added back the 2 repositories to ci.jenkins.io in https://ci.jenkins.io/job/Infra/ (updated the GH organization scanning job). Scanning in progress, that should add build checks for https://github.com/jenkins-infra/backend-extension-indexer/pull/46 and https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/241

**Comment by dduportal** [comment]
- The 2 pipelines had been unified succesfully (thanks @smerle33 !)
- 2 cleanup tasks left before closing:
  - [ ] Reconfigure infra.ci jobs to use `Jenkinsfile`
  - [ ] Remove the `Jenkinsfile.infra.ci.jenkins.io` symlinks from the 2 repos
