### ISSUE TITLE
Update Jenkins to 2.346.3

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3092]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

It's LTS time again and 2.346.3 has been shipped for GA 🎉

**Comment by dduportal** [comment]
- ci.jenkins.io ✅ after a batch VM restart to apply kernel upgrades
- release.ci.jenkins.io ✅ after https://github.com/jenkins-infra/kubernetes-management/pull/2690
- trusted.ci.jenkins.io ✅  after https://github.com/jenkins-infra/jenkins-infra/pull/2313
- cert.ci.jenkins.io ✅  after https://github.com/jenkins-infra/jenkins-infra/pull/2313
