### ISSUE TITLE
Granting "Triage" permission to jenkins-cert-app on RPU

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/helpdesk#3093]
### GitHub repositories

https://github.com/jenkins-infra/repository-permissions-updater

### GitHub users to have permission

@jenkins-cert-app

### Permission level

Triage

### Justification

The "bot" should be able to "Apply/dismiss labels" so that we have a smoother process for hosting requests.

Example of interactions: https://github.com/jenkins-infra/repository-permissions-updater/issues/2708#issuecomment-1209934878

btw the "Permission level" is not ordered correctly, it displays Read - Write - Triage, while Write is [more powerful](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role) than Triage.

**Comment by timja** [comment]
O I assumed it was a GitHub app, I can just add that now

**Comment by timja** [comment]
A GitHub app would probably be better as it's a true bot account.

I've sent an invite to this user account anyway

<img width="784" alt="image" src="https://user-images.githubusercontent.com/21194782/183898929-e31f76a2-13b2-4246-97bb-52061cafb5f1.png">
