### ISSUE TITLE
All maven-11 agents are unavailable

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3096]
### Service(s)

ci.jenkins.io

### Summary

Hey,

it appears that all `maven-11` agents are either offline or unresponsive? The [check-agent-availability](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/) job doesn't report anything since noon anymore, but jobs bound to `maven-11` agents, like the RPU, are stuck in queue for almost 2h: https://ci.jenkins.io/job/Infra/job/repository-permissions-updater/job/PR-2714/1/console.

For reference, highmem nodes and windows nodes execute builds fine.

**Comment by dduportal** [comment]
Thanks @NotMyFault . could be a side-effect of https://github.com/jenkins-infra/helpdesk/issues/3090#issuecomment-1211756945: I'm checking.

**Comment by dduportal** [comment]
I confirm that I see the maven-11 pods being started and failing immediatly.

- Disabling puppet on ci.jenkins.io
- Enabling retention for maven-11 pods on cik8s 

=> now debugging.

**Comment by dduportal** [comment]
This is definitively a side effect of #3090.

The error is `/usr/local/bin/jenkins-agent: 121: exec: /opt/jdk-11/bin/java: not found`.

Applying a hotfix to handle the build queue

**Comment by dduportal** [comment]
Had to monkey-patch the JCasc YAML on the ci.jenkins.io to be safe until tomorrow (that should have a fix):

- removed the `JENKINS_JAVA_BIN` variable for the maven-11 container templates (cik8s, doks and windows aci)
- Disabled + stopped puppet with a link to this issue
- Reloaded JCasc

=> builds are flowing now.

Thanks @NotMyFault for raising the issue

**Comment by dduportal** [comment]
- Configuration persisted on ci.jenkins.io as code (see attached PRs)
- Tested both Linux and Windows containers

=> looks good!
