### ISSUE TITLE
[accounts.jenkins.io] Fix instructions for spam unblock

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3098]
### Service(s)

Accounts

### Summary

The accounts.jenkins.io has a spam blocker system defined with the list from https://github.com/jenkins-infra/account-app/blob/8758b8e443476b67958591587f02a474d1ffe2ee/src/main/java/org/jenkinsci/account/Application.java#L672-L1442.

Sometime, legit users are blocked by the spam system but the instructions shown by the application are invalid:

- https://github.com/jenkins-infra/account-app/blob/8758b8e443476b67958591587f02a474d1ffe2ee/src/main/java/org/jenkinsci/account/Application.java#L1441-L1442 
- which points to https://wiki.jenkins-ci.org/display/JENKINS/User+Account+on+Jenkins 

=> we want to update instructions to point users to the jenkins-infra/helpdesk and add a specific kind of issue template for this.
=> Thanks @daniel-beck and @wadeck for pointing it to us!

**Comment by daniel-beck** [comment]
FTR https://github.com/jenkins-infra/account-app/pull/136 should remove some false positives.

**Comment by dduportal** [comment]
Opened https://github.com/jenkins-infra/account-app/pull/139/files, WDYT?

**Comment by dduportal** [comment]
> Opened [jenkins-infra/account-app#139](https://github.com/jenkins-infra/account-app/pull/139), WDYT?

Merged and deployed by https://github.com/jenkins-infra/kubernetes-management/pull/2729
