### ISSUE TITLE
UC doesn't offer release of new plugin

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3104]
### Service(s)

Update center

### Summary

Hey,

~16 hours ago I cut the initial release of [ionicons-api-plugin](https://github.com/jenkinsci/ionicons-api-plugin). Since then, it's available on artifactory: https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugins/ionicons-api/

It's not available at the UC still, https://updates.jenkins-ci.org/current/update-center.json, nor on plugins.jenkins.io

Is there a possible issue, or did I just hit a bad time and the UC job is about to run soonish again?

**Comment by dduportal** [comment]
Thanks for raising the issue. The job update_center on trusted.ci.jenkins was green earlier this morning.

But with your issue raised, we justd double-checked and it appears that the build agent is offline. Working on it.

Last update is marked (with success, hence the green overall status) today around 07:26am UTC.

**Comment by dduportal** [comment]
Caught the issue: the SSH host key was not the correct one. I'll update the issue there with the fixing PR, but I've already fixed it manually: updates are going to be done again.

**Comment by dduportal** [comment]
@NotMyFault the update center index has been successfully updated and now mentions the release `15.vc8f8c4502de5`.

Many thanks for raising the issue!

**Comment by NotMyFault** [comment]
Many thanks for the quick fix 👏🏻
