### ISSUE TITLE
Build plugins with JDK11 by default instead of JDK8 after the 7th of September LTS release

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3106]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io

### Summary

As the support for JDK8 will be dropped in the next LTS release, we shouldn't build plugins with it by default in [our shared pipeline library](https://github.com/jenkins-infra/pipeline-library).

**Comment by dduportal** [comment]
Can you open a discussion on the mailing list?

- We have to keep JDK8 available for some times: 
  - (at least 2 LTS away as per https://www.jenkins.io/download/lts/)
  - Some of our projects are still using JDK8 (accounts.jenkins.io, update_center, etc.)

**Comment by lemeurherve** [comment]
WDYT of rewording this issue as "Build plugins with JDK11 instead of JDK8 by default after the 7th of September LTS release"?

That would only need changing `8` to `11` here: https://github.com/jenkins-infra/pipeline-library/blob/3b64a2acb300720d5f5c61dbcd65a1c695f45dfc/vars/buildPlugin.groovy#L317

**Comment by dduportal** [comment]
Make sense, but still to be disucssed on the mailing list to broaden the audience outside the infra team :)

**Comment by MarkEWaite** [comment]
> As the support for JDK8 will be dropped in the next LTS release, we shouldn't build plugins with it by default in [our shared pipeline library](https://github.com/jenkins-infra/pipeline-library).

I disagree.  Plugins depend on a specific Jenkins version.  That specific Jenkins version may be much older than the most recent LTS.  If we drop Java 8 support from `buildPlugin`, we'll break those plugins unnecessarily.  I don't see enough benefit to removing Java 8 support from buildPlugin until most of its consumers are requiring Java 11.

**Comment by lemeurherve** [comment]
I didn't mean to drop JDK8 support, I propose to build plugins with JDK11 by default instead of JDK8 as it's the case today.

But you're right, changing this default would also means breaking some/many plugins, requiring to update their Jenkinsfile.

Closing this proposition.
