### ISSUE TITLE
Unable to login - wrong email in account.jenkins.io for password restore request

### ISSUE THREAD

**Issue by DuMaM** [jenkins-infra/helpdesk#3107]
### Service(s)

Accounts

### Summary

Hi,
I'm trying to restore my access to issues.jenkins.io
According to service admins I placed wrong email in my profile.
Could you help me update it?
batek.nowak@yahoo.pl
Thanks

### Reproduction steps

1. Go to account.jenkins.io
2. Reset password
3. Send mail with password reset request
4. No mail

**Comment by MarkEWaite** [comment]
Thanks for the request.  As far as I can tell, you are one of the maintainers of the [Crowd 2 integration plugin](https://plugins.jenkins.io/crowd2/).  Can you confirm that you are a maintainer of that plugin by making a change to the configuration of its [GitHub repository](https://github.com/jenkinsci/crowd2-plugin)?

For example, use the repository "Settings" to hide the "Packages".  Alternately, make a visible change to the "About" text in the top right corner of the repository web page.

## Before your change:

![screencapture-github-jenkinsci-crowd2-plugin-2022-08-23-15_50_27-edit](https://user-images.githubusercontent.com/156685/186273128-818a1ea8-4e58-4e40-86d0-1c0dac67bffd.png)

**Comment by DuMaM** [comment]
Yes, I'm a maintainer of this repo. 
Packages are hidden now.

**Comment by MarkEWaite** [comment]
> Yes, I'm a maintainer of this repo. Packages are hidden now.

Thanks.  I've set the email address on that user account to batek.nowak@yahoo.pl .  Could you try to perform a password reset on the account now?

If the password reset still does not deliver email to that address, please reply here and I'll do the password reset and send you the password through a single use URL.

**Comment by DuMaM** [comment]
It's working again 😉 
Thank you Mark for help here.

**Comment by DuMaM** [comment]
I will remove my email, to reduce spam from web crawlers
