### ISSUE TITLE
Mirror URL for org.opensaml and net.shibboleth needs to be updated

### ISSUE THREAD

**Issue by Riliane** [jenkins-infra/helpdesk#3108]
### Service(s)

Artifactory

### Summary

The URL for `org.opensaml` artifacts, that was https://build.shibboleth.net/nexus/content/groups/public/org/opensaml/ , is now https://build.shibboleth.net/maven/releases/org/opensaml/ .
For `net.shibboleth`, the URL that was https://build.shibboleth.net/nexus/content/repositories/releases/ is now https://build.shibboleth.net/maven/releases/ .
Please update the mirror URL in the artifactory.

### Reproduction steps

Try to `mvn install` the `saml-plugin`. This will throw an error that many `org.opensaml` and a `net.shibboleth` artifacts could not be found.
```
[ERROR] Failed to execute goal on project saml: Could not resolve dependencies for project org.jenkins-ci.plugins:saml:hpi:2.999999-SNAPSHOT: The following artifacts could not be resol
ved: org.opensaml:opensaml-core:jar:4.1.1, org.opensaml:opensaml-saml-api:jar:4.1.1, org.opensaml:opensaml-saml-impl:jar:4.1.1, org.opensaml:opensaml-soap-api:jar:4.1.1, org.opensaml:o
pensaml-xmlsec-api:jar:4.1.1, org.opensaml:opensaml-security-api:jar:4.1.1, org.opensaml:opensaml-security-impl:jar:4.1.1, org.opensaml:opensaml-profile-api:jar:4.1.1, org.opensaml:ope
nsaml-profile-impl:jar:4.1.1, org.opensaml:opensaml-messaging-api:jar:4.1.1, org.opensaml:opensaml-messaging-impl:jar:4.1.1, org.opensaml:opensaml-storage-impl:jar:4.1.1, org.opensaml:
opensaml-xmlsec-impl:jar:4.1.1, net.shibboleth.tool:xmlsectool:jar:3.0.0: Could not find artifact org.opensaml:opensaml-core:jar:4.1.1 in cloudbees-internal (https://nexus-internal.clo
udbees.com/content/groups/staged)
```

**Comment by jglick** [comment]
(follows up #2375)

**Comment by lemeurherve** [comment]
Ping @daniel-beck, can we let you take care of this please?

**Comment by daniel-beck** [comment]
I have replaced the remote repo URL with https://build.shibboleth.net/maven/releases/ (which the old repo URL redirects to), does it work now?

**Comment by Riliane** [comment]
Sorry for the delay - seems to work - I am having different, 99% surely unrelated, build issues, but it did download the artifacts.

**Comment by lemeurherve** [comment]
Thanks for the update @daniel-beck, and thanks for your confirmation @Riliane, closing this issue.

**Comment by basil** [comment]
I'd like a new mirror like this created for a new repository I'm consuming in Stapler tests. Should I file a new ticket like this?

**Comment by lemeurherve** [comment]
I suppose yes, @daniel-beck can you confirm?

**Comment by basil** [comment]
> I'm not sure how much we should still mirror.

I'll file a ticket with the problem, evaluation, proposed solution, and justification (in my usual style) and allow others to evaluate whether the rationale makes sense from the infrastructure team's perspective.

**Comment by basil** [comment]
Done in #3115. Thanks!
