### ISSUE TITLE
Help to register an account

### ISSUE THREAD

**Issue by skqist225** [jenkins-infra/helpdesk#3112]
### Service(s)

IRC

### Summary

Please help to take a look at creating new account

As i have filled wrong email into register form. I created another account, but this time it notified username have been registered, so i go back to the previous page to change to new username but it notified wrong submit code. I go back to refresh and get new submit code, and this time i was seen as a spammer.

My desired username: skqist2205
My desired email: thuan.leminhthuan.10.2@gmail.com

**Comment by lemeurherve** [comment]
I didn't found any `skqist2205` username or `thuan.leminhthuan.10.2@gmail.com`, could you retry an account creation please?

**Comment by skqist225** [comment]
Thanks. I use another browser to create account, so that it didn't see me as a spammer and successfully create new one.
