### ISSUE TITLE
Delete my account in accounts.jenkins.io

### ISSUE THREAD

**Issue by marco2704** [jenkins-infra/helpdesk#3118]
### Service(s)

Accounts

### Summary

Hi team,

Please delete my account marco2704 (marcodavalosmantilla@gmail.com) and all my data.

Thank you.

**Comment by lemeurherve** [comment]
@marco2704 in order to prove that you control the account (and your request is legit) could you send an email from this mailbox to jenkins-infra-team at googlegroups.com with a link to this issue in the email body please?

**Comment by lemeurherve** [comment]
@marco2704 could you comment on [this Jira issue](https://issues.jenkins.io/browse/JENKINS-69542) in order to verify that you control the account before deleting it please?

**Comment by marco2704** [comment]
> @marco2704 could you comment on [this Jira issue](https://issues.jenkins.io/browse/JENKINS-69542) in order to verify that you control the account before deleting it please?

Done!

**Comment by lemeurherve** [comment]
Thanks @marco2704, account verified and deleted.
