### ISSUE TITLE
Request to add permissions for new github users

### ISSUE THREAD

**Issue by nikita-bedmutha** [jenkins-infra/helpdesk#3120]
### GitHub repositories

https://github.com/jenkinsci/qualys-vm-plugin
https://github.com/jenkinsci/qualys-cs-plugin
https://github.com/jenkinsci/qualys-pc-plugin
https://github.com/jenkinsci/qualys-was-plugin

### GitHub users to have permission

mbachhav18
aditya-qualys
hgoyalqualys

### Permission level

Maintain

### Justification

Since I am moving on, need permissions for these new users in our org so that they can maintain the code for Qualys plugins.

**Comment by lemeurherve** [comment]
@nikita-bedmutha @mbachhav18 @aditya-qualys @hgoyalqualys the repositories permissions have been updated.

Note: keep in mind https://github.com/jenkins-infra/repository-permissions-updater haven't been changed.
