### ISSUE TITLE
Upgrade CI's to 2.361.1

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#3121]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

It's time for a new Jenkins LTS release 🚀

We would like to request the updating of ci.jenkins.io, trusted.ci, cert.ci and release.ci to the new LTS 2.361.1 release. Much appreciate your help! 

For info about this release please see https://github.com/jenkins-infra/release/issues/275. 

### Reproduction steps

N/A

**Comment by dduportal** [comment]
- release.ci.jenkins:
  - Bumped core (+ plugins compatible with this new core): 
  - Deployment PR: https://github.com/jenkins-infra/kubernetes-management/pull/2832
- ci.jenkins.io:
  - Service restarted with `systemctl restart docker-jenkins` which upgraded to latest image
  - Updated plugins for this new core version
- trusted.ci.jenkins.io:

**Comment by krisstern** [comment]
Thanks @dduportal
