### ISSUE TITLE
[Jira] Remove `jglick` as default assignee for `pipeline-groovy-lib-plugin`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3125]
### Service(s)

Jira

### Summary

I split this repo from `workflow-cps-global-lib-plugin` for architectural reasons that have nothing to do with maintainership and I do not wish to be a default assignee. New issues can be unassigned by default, as I think they are for other Pipeline-related plugins.

**Comment by MarkEWaite** [comment]
Done.  Thanks for the request.
