### ISSUE TITLE
Add user to keeper-secrets-manager-plugin Developers team

### ISSUE THREAD

**Issue by jsupun** [jenkins-infra/helpdesk#3131]
### GitHub repositories

jenkinsci/keeper-secrets-manager-plugin

### GitHub users to have permission

@maksimu

### Permission level

Admin

### Justification

Co-worker who gets to push the release button. :) SOX stuff.

**Comment by timja** [comment]
Done, your co-worker will need to accept the invite at https://github.com/jenkinsci first to get access
