### ISSUE TITLE
Requesting access to Jenkins project VPN as part of Jenkins security team

### ISSUE THREAD

**Issue by dwnusbaum** [jenkins-infra/helpdesk#3134]
### Service(s)

VPN

### Summary

Hi, I am on the Jenkins security team and would like VPN access so that I can review the CI build logs for private PRs in the `jenkinsci-cert` organization.

See https://github.com/jenkins-infra/docker-openvpn/pull/188.

CC @daniel-beck and @Wadeck for confirmation.

**Comment by dduportal** [comment]
PR merged: waiting to deploy it

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/2395 merged and deployed. You should be able to connect to the VPN now.

Can you close the issue when it is ok for you?

**Comment by dwnusbaum** [comment]
Sure, I will finish setting things up and check the connection in the next few hours, thanks!

**Comment by dwnusbaum** [comment]
Everything seems to be working, thanks!
