### ISSUE TITLE
Release of `jenkinsci/remoting` failing with 401 Unauthorized

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3135]
### Service(s)

Artifactory, GitHub

### Summary

[This release of `jenkinsci/remoting`](https://github.com/jenkinsci/remoting/actions/runs/3070711810/jobs/4960717762) failed with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project remoting: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.main:remoting:pom:3063.v26e24490f041 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/remoting/3063.v26e24490f041/remoting-3063.v26e24490f041.pom, status: 401 Unauthorized -> [Help 1]
```

I read [the documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#the-upload-to-the-maven-repository-fails-with-401-unauthorized):

> Unauthorized means that the credentials were invalid, or not sent by Maven. This normally means that the secrets configured in the repository have expired, create an issue in the INFRA helpdesk on [GitHub](https://github.com/jenkins-infra/helpdesk/issues/new/choose) […].

Per the documentation, I am creating an infrastructure ticket to update the expired credentials.

### Reproduction steps

Obtain write access to `jenkinsci/remoting`, then go to https://github.com/jenkinsci/remoting/actions/workflows/cd.yml and click the "Run workflow" button.

**Comment by timja** [comment]
Last updated 6 hours ago:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/21194782/190791579-475e6e13-4b51-4879-bf5a-44e264033cf5.png">

**Comment by timja** [comment]
The previous job is hanging with:
> 19:41:58  Cannot contact ubuntu-20-005cb0: java.lang.InterruptedException

next job started 10 mins ago.

Should be sorted in the next 8 mins or so.

**Comment by timja** [comment]
https://github.com/jenkinsci/remoting/releases/tag/3063.v26e24490f041

**Comment by basil** [comment]
Thank you!
