### ISSUE TITLE
Add `kmartens27` to `jenkins-infra/copy-editors` team

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3139]
### GitHub repositories

https://github.com/jenkins-infra/jenkins.io

### GitHub users to have permission

@kmartens27 

### Permission level

Maintain

### Justification

Based on the approvals received on the [Jenkins developer mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/VW-qV15bg3Y/m/qu-7WTMQAwAJ) and Kevin's contributions to the Jenkins documentation, I authorize him to be added to the [jenkins-infra/copy-editors team](https://github.com/orgs/jenkins-infra/teams/copy-editors).

The ["Joining the teams" section](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#joining-the-teams) notes that the documentation officer makes the decision to include new members in the copy editors team.

**Comment by kmartens27** [comment]
thanks so much @lemeurherve I'm so excited to be a part of the team and continuing to contribute to Jenkins!
