### ISSUE TITLE
`Jenkinsfile` not being run for `jenkinsci/winp`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3140]
### Service(s)

ci.jenkins.io

### Summary

In https://github.com/jenkinsci/winp/pull/71 I have added a `Jenkinsfile` for `jenkinsci/winp`. Since I have write access to this repository, I should be able to test the `Jenkinsfile` before it is merged. However, the `Jenkinsfile` is not being run in my PR, so I'm guessing a new job needs to be created on `ci.jenkins.io`.

### Steps to reproduce

- Obtain write access to `jenkinsci/winp`.
- Create a PR that adds or modifies a `Jenkinsfile`.
- Go to the Checks tab in the GitHub PR.

### Expected results

The `Jenkinsfile` changes should be running in CI for testing purposes.

### Actual results

No CI build was performed.

**Comment by timja** [comment]
I've added it to https://ci.jenkins.io/job/jenkinsci-libraries/

**Comment by basil** [comment]
Thank you!
