### ISSUE TITLE
junit-plugin component is archived in Jira

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/helpdesk#3141]
### Service(s)

Jira

### Summary

Is it expected that "junit-plugin" component is archived in Jira?

![Screenshot-2022-09-20_23-57-03](https://user-images.githubusercontent.com/2662497/191372369-db757383-f402-493a-8c1f-d6af3a1e28ad.png)

Due to the number of issues, I imagine it's either a mistake or a desired "project" to migrate them to something else, but not sure.
I don't want to change that without having the context of that decision.

For context, I wanted to add "junit-plugin" component to https://issues.jenkins.io/browse/JENKINS-69655, but had to go into the administration part to understand why it didn't show up.

**Comment by timja** [comment]
Yes it's expected to be archived.

They will be migrated at some point, but those are historical currently, all new issues are tracked in GitHub.

Multi component issues are not a good way of tracking issues that affect multiple areas.
