### ISSUE TITLE
Monitor RPU / CD secrets update time

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3146]
### Service(s)

trusted.ci.jenkins.io

### Summary

Multiple times recently CD credentials have expired.

e.g. https://github.com/jenkins-infra/helpdesk/issues/3145

Can this be monitored / alerted on so it doesn't cause downtime for developers please?

**Comment by dduportal** [comment]
Closing as it duplicates #2843 (monitoring private builds such as RPU).

It also relates to #2922 somehow.
