### ISSUE TITLE
Add more maintainers for the Gradle plugin

### ISSUE THREAD

**Issue by wolfs** [jenkins-infra/helpdesk#3147]
### GitHub repositories

https://github.com/jenkinsci/gradle-plugin

### GitHub users to have permission

@c00ler
@guylabs
@facewindu
@welandaz
@sorin-florea

### Permission level

Admin

### Justification

Those folks from Gradle want to help me developing the plugin going forward and are taking responsibility for the Gradle Enterprise injection part supported by the plugin. It makes things easier for me, if they can maintain the plugin as well.

I suppose they should be added to the Jenkinsci organization as well.

I suppose when they've been added on Github to the [gradle-plugin Developers](https://github.com/orgs/jenkinsci/teams/gradle-plugin-developers) groups, then I can open a PR to the https://github.com/jenkins-infra/repository-permissions-updater/ so they can also release new versions of the plugin.

**Comment by lemeurherve** [comment]
Hello @wolfs, I've added these GitHub users to the the [gradle-plugin Developers](https://github.com/orgs/jenkinsci/teams/gradle-plugin-developers) team.
They now need to join the jenkinsci GitHub org for the invitation to be effective if they haven't yet.

Closing this issue as completed, let me know if there is a problem.

**Comment by timja** [comment]
generally people file PRs directly at https://github.com/jenkins-infra/repository-permissions-updater/ and we add GitHub permissions as part of that :)
