### ISSUE TITLE
add datadog initialisation on windows vm 

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3149]
### Service(s)

AWS, Azure, ci.jenkins.io

### Summary

following https://github.com/jenkins-infra/helpdesk/issues/2980
we need to implement the same process than for linux for the windows ephemeral VM agent.

the same process could apply : Initialization Script
the azure documentation explain that the script will not be launched automatically (https://learn.microsoft.com/en-us/azure/virtual-machines/custom-data: _"Custom data is placed in %SYSTEMDRIVE%\AzureData\CustomData.bin as a binary file, but it isn't processed. If you want to process this file, you'll need to build a custom image and write code to process CustomData.bin."_ ) but the jenkins plugin help seem to  state the opposite and provide a sample : https://raw.githubusercontent.com/jenkinsci/azure-vm-agents-plugin/master/docs/init-scripts/windows-ssh.ps1

todo : 

- [x] create a test agent on ci.jenkins.io by casc with the same parameters than azure : win-2019 with a specific label
- [x] add a Initialization Script 
- [x] try to manually launch a pipeline with this agent to check whether or not the script is launched
- [x] modify the script to add a datadog.yaml at the correct path with the correct api-key
- [x] check that the VM appear on datadog host

same with amazon ....
- [x] create a test agent on ci.jenkins.io by casc with the same parameters than azure : win-2019 with a specific label
- [x] add a Initialization Script 
- [x] try to manually launch a pipeline with this agent to check whether or not the script is launched
- [x] modify the script to add a datadog.yaml at the correct path with the correct api-key
- [x] check that the VM appear on datadog host

and then :
- [x] add init script to old windows VM and remove test agent

**Comment by dduportal** [comment]
- Nitpick: could you point to the Azure-VM documentation about the feature?
- Important: we should not consider adding datadog to ACI.
- Next step: could you check with EC2 plugin how to do it? (smells like tricky because we use the SSH launcher on Windows machines)

**Comment by smerle33** [comment]
> * Nitpick: could you point to the Azure-VM documentation about the feature?
done
> 
>     * Important: we should not consider adding datadog to ACI.
ok
> 
>     * Next step: could you check with EC2 plugin how to do it? (smells like tricky because we use the SSH launcher on Windows machines)
https://github.com/jenkinsci/ec2-plugin
I will have to spend more time at this moment ... will first focus on azure.
