### ISSUE TITLE
jenkinsci account verification on Twitter

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3151]
### Service(s)

Other

### Summary

Hey,

the official [@jenkinsci](https://twitter.com/jenkinsci) account appears to be eligible to obtain the blue tick, according to Twitter's [account verification](https://help.twitter.com/en/managing-your-account/about-twitter-verified-accounts) guidelines.

I don't know whether the account applied for it in the past or not, but it would be fancy to get the blue tick 👀 

This issue may not be directed at the infrastructure team, but given the account is part of the overall infrastructure, I decided to raise the request here, to track progress.

**Comment by lemeurherve** [comment]
Now that this blue tick is costing $8/month, there is no way we'll pay for that.

Closing this issue.
