### ISSUE TITLE
Archive core-pr-tester and core-changelog-generator components

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3152]
### Service(s)

Jira

### Summary

Both, the [core-pr-tester](https://github.com/jenkinsci/core-pr-tester) and the [core-changelog-generator](https://github.com/jenkinsci/core-changelog-generator), use GitHub as issue tracker.

I always find it quite bothering to have those couple of components available, when none of those use Jira, if I want to select `core` only.

**Comment by timja** [comment]
done
