### ISSUE TITLE
Remove lockable-resources plugin from private infra

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3159]
### Service(s)

infra.ci.jenkins.io, release.ci.jenkins.io

### Summary

Based on a quick check, the plugin is unused and not configured on infra.ci and release.ci. If the same applies to trusted.ci and cert.ci, I'd vouch for uninstalling the plugin, given it's not needed at all.

I'm able to uninstall the plugin through the web UI, which implies this plugin is not a dependency of something else.

**Comment by dduportal** [comment]
Hello @NotMyFault could you clarify the reason why we should remove this plugin?

Side notes:

- The plugin is used on infra.ci (all the "*-reports" jobs). For instance https://github.com/jenkins-infra/infra-reports/blob/main/jira-users-report/Jenkinsfile#L13 . This is a hard requirement for these jobs.
  - Please note that these jobs were initially in trusted.ci.jenkins.io, and migrated a few month ago to infra.ci. 
- I would defer to @Wadeck / @dbeck or anyone else from the JenSec team for cert.ci.jenkins.io as they manage their own jobs (and we might not be able to see the associated pipelines)
- trusted.ci.jenkins.io is tricky: there are still freestyle jobs that could use the plugin: we can NOT rely on checking github for pipeline code.
- There is at least an occurence of the `lock` keyword in https://github.com/jenkins-infra/pipeline-library/blob/486ca41fde0b9b090612a537ed2e8b4b626c01ce/vars/runBenchmarks.groovy#L9 which makes mùe think that this plugin is expected to be installed on our controllers


=> the only realistic target is release.ci.jenkins.io (as per your PR on https://github.com/jenkins-infra/docker-jenkins-lts/pull/591). 
=> The risk is to break the next weekly once deployed. I don't mind if you can be there to help us watching potential errors.


WDYT?

**Comment by dduportal** [comment]
Thanks @NotMyFault for all of this work!
