### ISSUE TITLE
(October 2022) Update VPN CRL

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3162]
### Service(s)

VPN

### Summary

The Jenkins Infra calendar reminds us that the VPN CRL expires the 22th of October 2022.

Todo list for the team member who will take this action:

- [x] Read https://github.com/jenkins-infra/docker-openvpn#howto-review-certificate-revocation-list and check that you have all the pre-requisites
- [x] Open a PR to jenkins-infra/docker-openvpn that updates the CRL - https://github.com/jenkins-infra/docker-openvpn/pull/194
- [x] Once the PR is merged, ensures that there is a new version of the container automatically built and released
- [x] Run manually the GitHub workflow for updatecli in jenkins-infra/jenkins-infra to open a PR for deploying the new Docker image to production
- [x] Once deployed, connect to the VPN VM and ensure that the new CRL is present and updated
- [ ] Create a new team calendar event to the date of the next expiration, with alerts 3 weeks before and 2 weeks before

**Comment by smerle33** [comment]
I cannot do  some of those task as I am not yet part of the CORE team, so cannot merge those PR.
ex: https://github.com/jenkins-infra/jenkins-infra/pull/2409

**Comment by smerle33** [comment]
path to crl in docker image : `/etc/openvpn/server/crl.pem`

**Comment by smerle33** [comment]
Next Update: Apr  3 06:55:06 2023 GMT

events added to jenkins-infra-team calendar
