### ISSUE TITLE
Hosting team onboarding

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3163]
### GitHub repositories

https://github.com/jenkins-infra/repository-permissions-updater

### GitHub users to have permission

@NotMyFault 
@slide

### Permission level

Write

### Justification

For context: https://groups.google.com/g/jenkinsci-dev/c/4jjBc6-Bmwg/m/R1lQrWyHFgAJ

@halkeye would like to step down from his position handling and monitoring PRs towards the RPU.

slide and I would be interested in joining the @jenkins-infra/hosting team to take over Gavin's part.

**Comment by slide** [comment]
Thanks for submitting for me.

**Comment by lemeurherve** [comment]
@NotMyFault @slide I've added you to [the Hosting team](https://github.com/orgs/jenkins-infra/teams/hosting/) which has write permission on the RPU. Thanks for stepping in!

**Comment by halkeye** [comment]
Ping me when you've joined the Jenkins hosting IRC channel so you can get access to the bot commands for giving out GitHub permissions (maybe one day we'll get that codified)

**Comment by NotMyFault** [comment]
> Ping me when you've joined the Jenkins hosting IRC channel so you can get access to the bot commands for giving out GitHub permissions (maybe one day we'll get that codified)

Pinged you on IRC.

**Comment by NotMyFault** [comment]
> Ping me when you've joined the Jenkins hosting IRC channel so you can get access to the bot commands for giving out GitHub permissions (maybe one day we'll get that codified)

@halkeye Pinged you on IRC 👍🏻
