### ISSUE TITLE
Add petejax to helix-alm-test-management

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3164]
### GitHub repositories

https://github.com/jenkinsci/helix-alm-test-management-plugin

### GitHub users to have permission

@petejax

### Permission level

Admin

### Justification

The user mentioned needs to be added to https://github.com/orgs/jenkinsci/teams/helix-alm-test-management-plugin-developers as part of the hosting process in https://github.com/jenkins-infra/repository-permissions-updater/issues/2813.

The user specified needs an invitation to the jenkinsci organization, the hosting bot does not do that (afaik), therefore I'd like to ask someone to take care of this request, because I'm not able to invite users to the organization.
Preferably, we invite them directly into the team, to reduce further work required.

Thanks!

**Comment by lemeurherve** [comment]
Ping @jenkins-infra/jenkinsci-admins

**Comment by NotMyFault** [comment]
I took care of the issue myself, invite send.
