### ISSUE TITLE
Invite gounthar to jenkins-infra org

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3165]
### GitHub repositories

Please invite him directly to the team: https://github.com/orgs/jenkins-infra/teams/jenkins-hacktoberfest-stats/members

### GitHub users to have permission

@gounthar

### Permission level

Admin

### Justification

https://github.com/jenkins-infra/repository-permissions-updater/issues/2833

**Comment by lemeurherve** [comment]
I'm not sure these issues are useful: when a person is invited to a team of an org they aren't in yet, they receive a mail with an invite they can click on to join the org and the team.

**Comment by NotMyFault** [comment]
> they receive a mail with an invite they can click on to join the org and the team.

Indeed, although that applies to org owners and admins, because I am not able to invite users (example with a different user):
![Screenshot 2022-10-10 at 13 00 39](https://user-images.githubusercontent.com/13383509/194851631-e7d4b8be-c14b-4b9b-a1d6-f33407a71f54.png)
