### ISSUE TITLE
Add ircbot repo to infra org folder on ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3166]
### Service(s)

ci.jenkins.io

### Summary

Hey,

could we add the https://github.com/jenkins-infra/ircbot repo to https://ci.jenkins.io/job/Infra/ please?

Thanks!

(The jenkins-infra/hosting team would also be pleased to be added to the ircbot repository 😉)

**Comment by timja** [comment]
https://ci.jenkins.io/job/Infra/job/ircbot/job/main/

**Comment by NotMyFault** [comment]
Thanks for adding, Tim!

Minor fixes from my side, and the build builds again 🤞🏻
