### ISSUE TITLE
Created pods are purged without being used on ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3169]
### Service(s)

ci.jenkins.io

### Summary

I'm waiting for a PR build to pass, but newly created pods are purged quickly after creation, without starting builds: https://ci.jenkins.io/job/Packaging/job/packaging/job/PR-344/2/console

**Comment by dduportal** [comment]
Disabled cik8s for the night and started a new build that will spawn agents on digitalocean instead: https://ci.jenkins.io/job/Packaging/job/packaging/job/PR-344/

**Comment by dduportal** [comment]
Thanks for raising the issue.

Closing as the build/PRs looks ok.

**Comment by NotMyFault** [comment]
Thanks for investigating, especially at such late hours!
