### ISSUE TITLE
Update GitHub Users to Authorize as Committers to Atlassian Jira Software Cloud Plugin #2151

### ISSUE THREAD

**Issue by gxueatlassian** [jenkins-infra/helpdesk#3170]
### GitHub repositories

https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin

### GitHub users to have permission

@gxueatlassian

### Permission level

Write

### Justification

part of the dev team.

**Comment by thombergs** [comment]
I approve to give write permissions to @gxueatlassian.

**Comment by NotMyFault** [comment]
Hey @gxueatlassian,

I added you to the team associated with the repository mentioned.
Make sure you accept the organization invite sent. You can also accept it at https://github.com/jenkinsci if you can’t find the invite. Note that the invitation is valid for 7 days only.

Thanks!
