### ISSUE TITLE
Update GitHub Users to Authorize as Maintainers to Atlassian Jira Software Cloud Plugin

### ISSUE THREAD

**Issue by Harminder84** [jenkins-infra/helpdesk#3172]
### GitHub repositories

https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin

### GitHub users to have permission

@harminder84

### Permission level

Write

### Justification

Part of dev team

**Comment by thombergs** [comment]
I approve giving write permissions to @Harminder84, as he's part of the team working on the plugin.

**Comment by NotMyFault** [comment]
Hey @Harminder84,

I added you to the team associated with the repository mentioned.
Make sure you accept the organization invite sent. You can also accept it at https://github.com/jenkinsci if you can’t find the invite. Note that the invitation is valid for 7 days only.

Thanks!
