### ISSUE TITLE
Delete account on accounts.jenkins.io

### ISSUE THREAD

**Issue by rafalmyslek** [jenkins-infra/helpdesk#3175]
### Service(s)

Accounts

### Summary

I'd like to get my Jenkins account deleted (i.e. delete my account on https://accounts.jenkins.io/). 

My account username: rafalmyslek.

**Comment by rafalmyslek** [comment]
I believe that my account is set as the default assignee of the "atlassian-jira-software-cloud-plugin" component in issues.jenkins.io. 

Please update the default assignee to user: bgvozdev

**Comment by NotMyFault** [comment]
> Please update the default assignee to user: bgvozdev

I can change the default Jira assignee for you, could you approve this request please, @bgvozdev ?

**Comment by bgvozdev** [comment]
I approve

**Comment by NotMyFault** [comment]
Default assignee changed.

**Comment by dduportal** [comment]
Hi @rafalmyslek , to confirm deletion can you send an email, from the email used by the account, to jenkins-infra-team@googlegroups.com (private email of the infra team, the goal is to ensure the legitimacy of tour request).

as soon as we receive the email, we’ll delete the account.

Thanks for the contributions !

**Comment by dduportal** [comment]
@rafalmyslek thanks for the email. Your account has been deleted.

**Comment by rafalmyslek** [comment]
Hi, this issue needs to be re-opened. Turns out that I'm still the default assignee for the `atlassian-jira-software-cloud-plugin` project, for example this is a recently created issue: https://issues.jenkins.io/browse/JENKINS-73040
