### ISSUE TITLE
Upgrade our GHA using deprecated `set-output`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3176]
### Service(s)

GitHub

### Summary

The `set-output` command is deprecated and will be disabled soon. 
We have to upgrade [jenkins-infra](https://cs.github.com/?scope=org%3Ajenkins-infra&scopeName=jenkins-infra&q=set-output) & [jenkinsci](https://cs.github.com/?scope=org%3Ajenkinsci&scopeName=jenkinsci&q=set-output) concerned GitHub Actions to use Environment Files, as explained in the announcement: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by lemeurherve** [comment]
@NotMyFault many thanks for all these PRs ❤️ 

FTR, I had to [revert one of them](https://github.com/jenkins-infra/docker-jenkins-weekly/pull/640).
I found a potential fix to avoid error with multi-lines body, see [the code block of this comment](https://github.com/peter-evans/create-or-update-comment/pull/115#issuecomment-1281949841)

**Comment by NotMyFault** [comment]
I'll go ahead and close this issue. All PRs needed to upgrade have been created and are merged to a good extent, the CD actions have been released and will be picked up by dependabot to update the reusable workflow repository.

**Comment by lemeurherve** [comment]
https://github.com/jenkins-infra/github-reusable-workflows/releases/tag/v1.1.3 released with the fixes from @NotMyFault 👍
