### ISSUE TITLE
Remove `basil` from `adoptopenjdk-plugin-developers`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3179]
### GitHub repositories

https://github.com/jenkinsci/adoptopenjdk-plugin

### GitHub users to have permission

@basil

### Permission level

Read

### Justification

I am normally able to remove myself from these groups by going to https://github.com/orgs/jenkinsci/teams/adoptopenjdk-plugin-developers/members and clicking "Leave Team" (and in fact just did so successfully for `sloccount-plugin-developers`), but no such button exists for `adoptopenjdk-plugin-developers`.

**Comment by timja** [comment]
Because you are the only maintainer I think, if you make the other person the maintainer or remove your maintainer role you should be able to

**Comment by basil** [comment]
I was somehow able to select my username and click **Remove from Team** (which was a different UI from how I removed myself from `sloccount-plugin-developers).
