### ISSUE TITLE
Jenkins Mirror

### ISSUE THREAD

**Issue by tasssko** [jenkins-infra/helpdesk#3182]
### Service(s)

infra.ci.jenkins.io, Helpdesk

### Summary

I'm submitting this on behalf of Servana. We want to set up mirror/s in the Australian and India regions. Existing mirrors do not serve these regions well. I would like to create a plan to provide this functionality and understand how it works.

1. For the plan, I need to know the architectural requirements for a mirror. 
2. How much bandwidth do existing mirrors use? 

Thanks

**Comment by smerle33** [comment]
Hi  Tass, 

We would be really happy to have a mirror hosted by your services !

The procedure would be the following:
    
-     Disk space of 750 Gb (usage at the moment around 500Gb)
-     A public domain name to expose the mirror in HTTPS publicly (if there is HTTP, there must be a redirection to HTTPS). Implies a valid certificate for TLS.
-     It's hard to tell the bandwidth used by the existing mirror as we don't operate them, the only one we do, we pay if the bandwidth get over 5Tb and as we don't, it should stay under that for sure.
-     The data should be retrieved at least daily through rsync protocol from one of the rsync servers :

            - rsync://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/
            - rsync://mirrors.tuna.tsinghua.edu.cn/jenkins/
            - rsync://ftp.halifax.rwth-aachen.de/jenkins/
            - rsync://ftp-chi.osuosl.org/jenkins/
            - rsync://mirror.xmission.com/jenkins/
            - rsync://ftp-nyc.osuosl.org/jenkins/
            - rsync://esme.gruenehoelle.nl/mirror/jenkins/

    Eventually, you should provide:

-         An rsync service to allow future mirrors to retrieve data from your mirror with rsync (and further spread the load)
-         An FTP service to allow older download systems unable to use HTTP(S)

    
    
If it is ok for you, once you have done the initial data import + published one of the download services, can you communicate to use the URL of each the service(s) you provide, so we can add your mirror in our redirection database.

Many thanks!

Stéphane MERLE, for the Jenkins infra team.

**Comment by tasssko** [comment]
We are working on the mirror and should have it ready early next week. Shall we post the mirror details here for your to update?

**Comment by lemeurherve** [comment]
Yes please 🙂

**Comment by olblak** [comment]
Hello,

Regarding Mirror bandwiths, there are public traffic stats by mirror.
Just append `?mirrorstats` to the get.jenkins.io url such as https://get.jenkins.io/debian/jenkins_2.332_all.deb?mirrorstats
You can put your mouse on the blue line to get information
Keep in mind that the data is reset every day.

That being said it's difficult to estimate how much traffic goes to a specific mirror as users are redirected to the closest mirror.

**Comment by tasssko** [comment]
Hello,

The mirror is now available here; https://sg.mirror.servanamanaged.com/jenkins/

We are hoping Jenkins users in Asia will have a much better update experience. Any feedback is welcome. 

Best

**Comment by timja** [comment]
Nice, geoip data:

![image](https://user-images.githubusercontent.com/21194782/205048504-efd5a747-5b33-4d56-b237-81624d94d3c8.png)

**Comment by lemeurherve** [comment]
Mirror added to our infra, many many thanks @tasssko ❤️ 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/91831478/205644822-b14d3a1f-0139-46cf-976a-ed799c870ec8.png">

**Comment by ankitjoshi8518** [comment]
I am encountering issue with the mirror: 

https://sg.mirror.servanamanaged.com/jenkins/

Is anyone else encountering same issue?

Other mirrors are working fine from the same system. There's no restriction at proxy as well.

**Comment by MarkEWaite** [comment]
@ankitjoshi8518 commenting on a closed issue is much less likely to result in help than opening a new issue.  In this case, I just checked from my location in the U.S. and I'm able to download the most recent release of the git plugin from https://sg.mirror.servanamanaged.com/jenkins/plugins/git/5.2.1/git.hpi .

If you're still seeing the issue, you may want to open a new helpdesk issue with a detailed description of the configuration where you're seeing the problem and the detailed message that is being reported.

**Comment by dduportal** [comment]
Ping @tasssko , it looks like servana mirror is not syncing data anymore: https://github.com/jenkins-infra/helpdesk/issues/4670.

Since we do not have any email contact for you, without answer we will have to remove the Servana mirror from our systems without answer.
