### ISSUE TITLE
Modifications to the Developers group

### ISSUE THREAD

**Issue by avwsolutions** [jenkins-infra/helpdesk#3185]
### GitHub repositories

https://github.com/jenkinsci/venafi-codesigning-plugin
https://github.com/jenkinsci/venafi-vcert-plugin

### GitHub users to have permission

@sanhi

### Permission level

Admin

### Justification

@sanhi is a new developer on both projects that will help us update these plugins and introduce an additional feature. @FooBarWidget will leave both Developer groups.

Affected groups are:
- venafi-codesigning-plugin-developers
- venafi-vcert-plugin-developers

**Comment by NotMyFault** [comment]
Hey,

I added the user mentioned to the teams associated with the repositories linked.

Thanks!
