### ISSUE TITLE
Artifactory Log-in no longer working

### ISSUE THREAD

**Issue by gbigenios** [jenkins-infra/helpdesk#3191]
### Service(s)

Artifactory

### Summary

Hello,

I’m trying to release the Plugin I maintain (Managed Scripts) and it fails trying to upload to the artifactory:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project managed-scripts: Failed to deploy artifacts: Could not transfer artifact org.jenkinsci.plugins:managed-scripts:pom:1.5.5 from/to [maven.jenkins-ci.org](http://maven.jenkins-ci.org/) (https://repo.jenkins-ci.org/releases): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkinsci/plugins/managed-scripts/1.5.5/managed-scripts-1.`
`{
  "errors" : [ {
    "status" : 401,
    "message" : "Bad credentials"
 } ]
}`

I can no longer log in on https://repo.jenkins-ci.org/ui/packages with my user “gbigenios“
I tried hitting the “Forgot password” but then it says something like “this user is not allowed to reset the password”.

Thanks for your help,

Jonathan

### Reproduction steps

1. go to https://repo.jenkins-ci.org/ui/packages
2. select "log in"
3. try to log in

**Comment by timja** [comment]
can you try use https://accounts.jenkins.io to reset the password?

**Comment by gbigenios** [comment]
Thanks, that worked.
