### ISSUE TITLE
Archive a few Jira components of NotMyFault's plugins

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3192]
### Service(s)

Jira

### Summary

Hey,

I'd like to request the archive of the following components:
- console-column-plugin
- configure-job-column-plugin
- envinject-api-plugin
- purge-build-queue-plugin

Named plugins are currently maintained by me and have been moved on to GH issues.

Thanks!

**Comment by dduportal** [comment]
The 4 components have been archived.
