### ISSUE TITLE
Downloading Jenkings LTS (msi package) is too slow

### ISSUE THREAD

**Issue by satyasonu** [jenkins-infra/helpdesk#3196]
Problem with the [Thank you for downloading Windows Stable installer](https://www.jenkins.io/download/thank-you-downloading-windows-installer-stable/) page, [source file](https://github.com/jenkins-infra/jenkins.io/blob/master/content/download/thank-you-downloading-windows-installer-stable.html.haml)

TODO: I expected that when someone downloading the Jenkings, it is very slow than expected even my broadband connection is 100Mbps.

## Screenshots 
![Screenshot (1)](https://user-images.githubusercontent.com/64128421/197137656-eb531c51-7302-4bb1-a100-70da86dfad54.png)

 Screenshot added

## Possible Solution 

 

N/A

**Comment by dduportal** [comment]
Admin note: this issue was transfered from jenkins-infra/jenkins.io (issue tracker only for the content of the website jenkins.io and this issue is NOT related to the website).

This issue IS a legit issue for the Jenkins Infratstructure

**Comment by dduportal** [comment]
Hi @satyasonu thanks for raising this issue!

You have to know that the Jenkins downloads are using a system of mirrors across the world to avoid using a centralized (fragile and slow) web server.

It means that the "slow" download is from one of these mirrors.

In order to investigate, could you share the result (webpage) of https://get.jenkins.io/windows-stable/2.361.2/jenkins.msi?mirrorlist from your setup? This webpages show what is the mirror selected in your specific case.

**Comment by satyasonu** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/64128421/197174049-c934f20e-b6ba-4e06-8aff-2ba8531f87e5.png)

I have uploaded the Snapshot of webpage. It took 20 mins to download 95 MB. Please check and let me know if you need further input from my end.

**Comment by timja** [comment]
I think you are in an area not well served by mirrors.

also see https://github.com/jenkins-infra/helpdesk/issues/3182

**Comment by dduportal** [comment]
@satyasonu as @timja just said, it seems that the mirroring system redirects you to a chinese mirror (which is slow).

In short term, could you try the other links shown in the URL column in the "mirrorlist" page and compare if others are faster?

(for instance https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/windows-stable/2.361.2/jenkins.msi in Japan or https://archives.jenkins.io/windows-stable/2.361.2/jenkins.msi)

**Comment by satyasonu** [comment]
Yes, these two links are much faster than chinese mirror. These mirror links should replace chinese mirror to provide faster download service to everyone.

Thanks for all the above information. I appreciate your steps towards resolution.

**Comment by dduportal** [comment]
Hi @satyasonu  , as per https://github.com/jenkins-infra/helpdesk/issues/3182, there is a new Jenkins mirror in Asia : could you try again and let us know if you are redirected to this new mirror (which speed should be clearly higher)?
