### ISSUE TITLE
`loki` installation is broken since September 2022

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3197]
### Service(s)

Other

### Summary

Since https://github.com/jenkins-infra/kubernetes-management/pull/2818 (bump v2.x -> v3.x) , our installation of Loki is broken.

For later infra team mebers, you can "acceptance test" the Loki installation in the Grafan datasource section usually (https://grafana.publick8s.jenkins.io/datasources => Requires VPN + LDAP authentication), by clicking on the "Loki" datasource, and then the "Test" button (might require to fine tune settings but it was up to date when writing this issue).

It is not a critical service: it was an experiment by @olblak, added to the (Grafan + Prometheus) stack but we don't use it a lot.

- We can remove the installation
- We can fix the installation
  - Either we uninstall it an reinstall it from scratch,
  - Or we migrate the installation as per https://github.com/grafana/loki/tree/main/production/helm/loki#upgrading-from-v2x

=> depends if we plan to use it or not?

**Comment by olblak** [comment]
Honestly I like the tool but drop it if you don't use it, Datadog offers a similar feature.

**Comment by dduportal** [comment]
So I'm gonna proceed with the loki removal I tried to access the data and the Persistent Volume is full of empty  dirs: we don't have loki logs data since some time....

**Comment by dduportal** [comment]
Thanks @jplayout for the help in diagnosing the issues \o/

**Comment by dduportal** [comment]
Post-operation notes:

- The namespace `loki` was stuck in "deletion" state because of two pods stuck in "terminating state".
  - Found https://github.com/kubernetes/kubernetes/issues/97031. Fixed in [AKS 1.22.6](https://github.com/kubernetes/kubernetes/issues/97031#issuecomment-1029967524).
  - Upgraded `prodpublick8s` (was in 1.22.1) to latest available e.g. `1.22.15` (control plane + nodes). Triggered a LDAP restart (3 min) + an outage of ~2 min on accounts.jenkins.io.
  - Did the same upgrade to `temp-privatek8s` (was 1.22.4) while I was there :)
