### ISSUE TITLE
[From Platform SIG] Remove PPC64 mentions on ci.jenkins.io

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3198]
IBM does not provide us anymore a PPC64 machine:(as per last platform SIG meetings): we have to remove configurations and documentation in the infra:

- Remove the permanent agent and its credential in ci.jenkins.io (Puppet managed) in jenkins-infra/jenkins-infra
   - Also cleanup the `jdk` tool configuration for PPC64 and also the updatecli scripts
- Cleanup the ci.jenkins.io documentation in jenkins-infra/documentation
- Remove any other mention of PPC64

**Comment by smerle33** [comment]
as per https://github.com/jenkins-infra/jenkins-infra/pull/2451 I did remove the permanent agent from jcasc. I did see the change on puppet : 
```console
Notice: /Stage[main]/Profile::Jenkinscontroller/File[/var/lib/jenkins/casc.d/permanent-agents.yaml]/content: 
--- /var/lib/jenkins/casc.d/permanent-agents.yaml	2022-08-26 15:47:20.063279717 +0000
+++ /tmp/puppet-file20221028-4177-1pt2bma	2022-10-28 08:48:14.239966016 +0000
@@ -1,38 +1,6 @@
 jenkins:
   nodes:
   - permanent:
-      name: "ppc64le-agent"
```

but even after applying the puppet conf and even manually reload the jcasc, I still see the permanent agent on the ci.jenkins.io : 

<img width="1736" alt="Capture d’écran 2022-10-28 à 11 13 44" src="https://user-images.githubusercontent.com/95630726/198551310-604aec86-a8fb-4df4-b0e8-91a1e811d867.png">

what have I done wrong ? (@dduportal)

**Comment by dduportal** [comment]
>  was not an error from me but a puppet issue ... solved by @dduportal manually deleting agents.xml

`agents.yaml` :) it was a leftover fomr before using Casc.

**Comment by smerle33** [comment]
double checked with @poddingue for any mention of ppc64 to remove but none left.
