### ISSUE TITLE
jcroall unable to log in to artifactory - incorrect username/password or locked user

### ISSUE THREAD

**Issue by jcroall** [jenkins-infra/helpdesk#3199]
### Service(s)

Accounts

### Summary

I am unable to log in to Artifactory (https://repo.jenkins-ci.org/ui/login/) for the first time, it reports that login has failed due to incorrect username/password or locked user. I can login with the username and password to Jenkins Jira.

Trying to get https://github.com/jenkins-infra/repository-permissions-updater/pull/2895 in order to respond to a security ticket.

**Comment by dduportal** [comment]
Can you retry now? We had a LDAP unplanned operation yesterday and it *might* be related (or not).

**Comment by jcroall** [comment]
Am in! Thanks!

**Comment by dduportal** [comment]
Sorry for the inconvenience @jcroall . Thanks for your contribution to this project!
