### ISSUE TITLE
Artifact downloads failed on agent using repo cache

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3203]
### Service(s)

ci.jenkins.io

### Summary

https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/PR-123/1/console shows that the artifact download failed from the caching repository.

### Reproduction steps

1. Configure the repository to use the caching repository
2. Run a build with the caching repository
3. Confirm the build fails because it is unable to download the artifacts as in this [console](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/PR-123/1/console)

**Comment by lemeurherve** [comment]
We've got some issues restoring the service after the eks-public cluster upgrade to Kubernetes 1.23, [I'm removing the 'aws' provider for now](https://github.com/jenkins-infra/pipeline-library/pull/504), this should help while we're fixing it.

**Comment by dduportal** [comment]
So we did a loooot of fixes and improvements for this service and it is now back online:

- https://github.com/jenkins-infra/kubernetes-management/pull/3103
- https://github.com/jenkins-infra/kubernetes-management/pull/3116
- https://github.com/jenkins-infra/kubernetes-management/pull/3114
- https://github.com/jenkins-infra/kubernetes-management/pull/3111
- https://github.com/jenkins-infra/kubernetes-management/pull/3110
- https://github.com/jenkins-infra/kubernetes-management/pull/3107
- https://github.com/jenkins-infra/kubernetes-management/pull/3105

**Comment by dduportal** [comment]
Monitoring had been enabled in https://github.com/jenkins-infra/datadog/pull/113 (thanks a lot @lemeurherve @smerle33 !!).

Closing the issue as the next steps are tracked in https://github.com/jenkins-infra/helpdesk/issues/2752

**Comment by MarkEWaite** [comment]
I see a failure today in a [git client plugin pull request build](https://ci.jenkins.io/job/Plugins/job/git-client-plugin/job/PR-919/3/consoleFull) that reports an issue downloading from repo.jenkins-ci.org.  I believe that is unrelated to this failure and is actually a failure of repo.jenkins-ci.org . 

The message is:

```
07:40:24  [ERROR] Failed to execute goal on project git-client: 
Could not resolve dependencies for project org.jenkins-ci.plugins:git-client:hpi:3.12.2-rc3266.3615b_2e9568f: 
Failed to collect dependencies at org.jenkins-ci.main:jenkins-war:war:2.346.3 -> org.jenkins-ci.modules:launchd-slave-installer:jar:1.2: 
Failed to read artifact descriptor for org.jenkins-ci.modules:launchd-slave-installer:jar:1.2: 
Could not transfer artifact org.jenkins-ci:jenkins:pom:1.26 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): 
transfer failed for https://repo.jenkins-ci.org/public/org/jenkins-ci/jenkins/1.26/jenkins-1.26.pom: 
Connect to repo.jenkins-ci.org:443 [repo.jenkins-ci.org/35.243.130.159] failed: Connection timed out: connect -> [Help 1]
```
I've restarted that job to see if the problem is transient.

**Comment by lemeurherve** [comment]
Unrelated indeed, the artifact caching proxy isn't enabled on this repo.

Thanks for the report anyway, we'll still get occasional failures from repo.jenkins-ci.org, hope the proxy will alleviate some of them.

**Comment by lemeurherve** [comment]
With the latest [fallback](https://github.com/jenkins-infra/pipeline-library/pull/507) and [settings](https://github.com/jenkins-infra/pipeline-library/pull/505) improvements I've added to the pipeline library these builds shouldn't fail because of the artifact caching proxies anymore.

**Comment by lemeurherve** [comment]
@MarkEWaite As it seems the same case [as described here](https://github.com/jenkins-infra/helpdesk/issues/3221#issuecomment-1305403066), WDYT of (re)closing this issue and keep only [the other one](https://github.com/jenkins-infra/helpdesk/issues/2844) opened while I'm working on #2844?

**Comment by lemeurherve** [comment]
Thanks for the reports! I've renamed #3221 to be more explicit about the fact that's the Azure artifact caching proxy provider which is sometimes failing for now.
