### ISSUE TITLE
Not receiving reset account password email

### ISSUE THREAD

**Issue by galindro** [jenkins-infra/helpdesk#3207]
### Service(s)

Accounts

### Summary

I'm trying to reset my account's password but I'm not receiving the email to reset it. I already checked in my spam folder, etc... and couldn't find it.  My email is bruno.galindro@gmail.com and my username is galindro. This account exists.

### Reproduction steps

1. go to https://accounts.jenkins.io/passwordReset
2. write my email: bruno.galindro@gmail.com
3. Click on reset

Then I see this message:

![image](https://user-images.githubusercontent.com/4622097/198035440-6ca9c80d-b5e4-4ae6-a390-e75c44237ea9.png)

**Comment by timja** [comment]
Your email for some reason was just your account name, but in Jira it's correct and the one you specified

**Comment by timja** [comment]
you should get an email now

**Comment by dduportal** [comment]
It's in Keycloak @timja : I can take care of it if you want?

**Comment by timja** [comment]
> It's in Keycloak @timja : I can take care of it if you want?

I fixed it in the accountapp

**Comment by dduportal** [comment]
> > It's in Keycloak @timja : I can take care of it if you want?
> 
> I fixed it in the accountapp

There was a weird state but I can't tell if it is unsync between keycloak and account-app, or is it keycloak internal's state.

The account in Keycloak still reports the username as email, despite your change in account-app applied successfully to LDAP.
However, Keycloak reported that the account was in "Verify Email".

I fixed both in keycloak just in case.

@galindro can you confirm that it work for you?

**Comment by galindro** [comment]
It worked @dduportal !!

Ty for your quick reaction!
