### ISSUE TITLE
Crowdin localization for lockable-resources

### ISSUE THREAD

**Issue by mPokornyETM** [jenkins-infra/helpdesk#3208]
### GitHub repositories

https://github.com/jenkinsci/lockable-resources-plugin

thx

### Crowdin users to have project management permission

@mPokornyETM
@gounthar

**Comment by NotMyFault** [comment]
Hey @mPokornyETM,

the project has been created and is available on https://crowdin.jenkins.io/lockable-resources-plugin
The project ID is 26.

I wasn't able to add you, because you didn't log into Crowdin yet. Let me know once you're logged in, and I'll add you to the project.

**Comment by mPokornyETM** [comment]
thx, it I forgot to join. It shall works now.

**Comment by NotMyFault** [comment]
> thx, it I forgot to join. It shall works now.

Added.
