### ISSUE TITLE
Hosting team onboarding

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3210]
### GitHub repositories

https://github.com/jenkins-infra/repository-permissions-updater

### GitHub users to have permission

@NotMyFault
@slide
@alecharp 

### Permission level

Write

### Justification

I would like to help with the hosting process of new and existing plugins.

**Comment by lemeurherve** [comment]
As your contributions speak for themselves, I went ahead and added you to the @jenkins-infra/hosting team.

**Comment by lemeurherve** [comment]
@jenkins-infra/hosting sorry I've been too enthusiast adding Adrien to the team, I should have waited your decision.

**Comment by NotMyFault** [comment]
> @jenkins-infra/hosting sorry I've been too enthusiast adding Adrien to the team, it wasn't my decision to make I should have waited yours.

+1 for his addition and +1 for you adding yourself, if that applies still, given you were interested in the mailing list too.

**Comment by timja** [comment]
+1
