### ISSUE TITLE
Backlog of already built items in queue on ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3211]
### Service(s)

ci.jenkins.io

### Summary

ci.j has a massive backlog of jobs in queue, but the PRs and branches have already been built.

For example, 
![Screenshot 2022-10-28 at 10 53 14](https://user-images.githubusercontent.com/13383509/198546856-c4e5c54f-a1c6-419c-a7af-852613d6e908.png)
but that job has already been built: https://ci.jenkins.io/job/Plugins/job/maven-jellydoc-plugin/job/PR-7/7/, the item is stuck in queue.
The same applies to the bom PRs and updatecli a bit below in the queue.

**Comment by lemeurherve** [comment]
After some research it appears it's an edge case, Damien and Jessy are already working on it AFAIU.
Nothing really can be done apart emptying the builds queue. I'll take a look.

**Comment by MarkEWaite** [comment]
I've emptied the builds queue so that we can see if the problem arises again

**Comment by NotMyFault** [comment]
> After some research it appears it's an edge case, Damien, Jessy and Devin are already working on it AFAIU. Nothing really can be done apart emptying the builds queue. I'll take a look.

Thanks for taking a look, I didn't see it occurring again after Mark cleared the queue yesterday.

**Comment by lemeurherve** [comment]
I've installed [an incremental build of workflow-durable-task-step-plugin](https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/259#issuecomment-1295206097) on ci.jenkins.io which might prevent this situation.

**Comment by dduportal** [comment]
As discussed with @lemeurherve we have not seen "ghost" builds anymore since the installation of the plugin (compared to 1 "zombie" BOM build per day the 6 days before).

Continuing watching until ~the 15 of November (if ok for you @jglick?)

**Comment by jglick** [comment]
Sure, just remind me then to suggest releasing my change.

**Comment by dduportal** [comment]
> Sure, just remind me then to suggest releasing my change.

@jglick you can proceed to release:

- Despite upgrade of the whole LTS core, and then a set of plugins, still no more "ghost builds" on ci.jenkins.io ✅ 
- Multiple configurations updates involving full process restarts and no more "ghost builds" ✅

**Comment by jglick** [comment]
https://github.com/jenkinsci/workflow-durable-task-step-plugin/releases/tag/1217.v38306d8fa_b_5c

**Comment by lemeurherve** [comment]
I've deployed this release on ci.jenkins.io, closing this issue.
