### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by JuliaFerdus** [jenkins-infra/helpdesk#3215]
### Service(s)

Accounts

### Summary

I can'n login with my valid credentials .

**Comment by dduportal** [comment]
Hi @JuliaFerdus , you should be able to browse to accounts.jenkins.io and reset your credentials from here.

If it is not working as expected, you have to give us more information:

- What did you try? 
- On which URL?
- What is the expected account and its email?

**Comment by dduportal** [comment]
Closing as the issuer is unresponsive.

Please feel free to reopen with the required informations if need be.
