### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by rajuvadarevu** [jenkins-infra/helpdesk#3217]
### Service(s)

Accounts

### Summary

Not able to Sign Up
Got below error:
![image](https://user-images.githubusercontent.com/43061031/199710722-f388376b-f37f-49f5-8b56-f2ff0e569baf.png)

**Comment by dduportal** [comment]
Hi @rajuvadarevu , as explained in the message that you added in screenshot, could you provide us the userid and email you used for the account please?

**Comment by rajuvadarevu** [comment]
userid: rajuVadarevu
email: ***@***.***

**Comment by dduportal** [comment]
`email: ***@***.***`

🤔 that is not expected. Could you provide us your email please?

**Comment by rajuvadarevu** [comment]
***@***.***
This is the email id

Anything wrong in reading the mail?

**Comment by NotMyFault** [comment]
GitHub censors the email if you reply by mail, btw.

**Comment by lemeurherve** [comment]
Please tel us your email by commenting via the GitHub interface.

**Comment by rajuvadarevu** [comment]
rajuvadarevu@gmail.com

**Comment by dduportal** [comment]
@rajuvadarevu thanks a lot! I've created an account for you, you should receive an email with a temporary password.

Can you authenticate and change the password please?

**Comment by dduportal** [comment]
Closing as no more action required.

Please feel free to reopen with more details if need be.

**Comment by rajuvadarevu** [comment]
Thanks for your support.
