### ISSUE TITLE
Artifact caching proxy 504 Gateway time-out errors with the Azure provider

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3221]
### Service(s)

ci.jenkins.io

### Summary

The cloud stats plugin has recently been configured to use the artifact caching proxy.  [Build 71](https://ci.jenkins.io/job/Plugins/job/cloud-stats-plugin/job/master/71/) failed because it could not find git-changelist-maven-extension.

### Reproduction steps

1. Enable artifact caching proxy in a Jenkinsfile on ci.jenkins.io that has incremental builds enabled
2. Run the build, detect a failure because the git changelist maven extension can't be found

As similar failure was visible on [build 173](https://ci.jenkins.io/job/Plugins/job/schedule-build-plugin/job/master/173/console) of the schedule build plugin, though was not visible on builds done about the same time on the following plugins:

* [Elastic axis plugin build 234](https://ci.jenkins.io/job/Plugins/job/elastic-axis-plugin/job/master/234/) passed without issue
* [Embeddable build status plugin build 66](https://ci.jenkins.io/job/Plugins/job/embeddable-build-status-plugin/job/master/66/pipeline-graph/) passed without issue
* [Platform labeler plugin build 926](https://ci.jenkins.io/job/Plugins/job/platformlabeler-plugin/job/master/926/console) passed without issue
* [Implied labels plugin build 72](https://ci.jenkins.io/job/Plugins/job/implied-labels-plugin/job/master/72/console) passed without issue

**Comment by lemeurherve** [comment]
> The cloud stats plugin has recently been configured to use the artifact caching proxy. [Build 71](https://ci.jenkins.io/job/Plugins/job/cloud-stats-plugin/job/master/71/) failed because it could not find git-changelist-maven-extension.

As far as I can tell from the logs and if I'm not mistaken, the artifact caching proxy isn't responsible for this failure as `git-changelist-maven-extension` is retrieved from Maven Central and not repo.jenkins-ci.org or one of the proxies:

> Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.jenkins.tools.incrementals:git-changelist-maven-extension:pom:1.4 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/io/jenkins/tools/incrementals/git-changelist-maven-extension/1.4/git-changelist-maven-extension-1.4.pom

About the schedule build plugin,

> As similar failure was visible on [build 173](https://ci.jenkins.io/job/Plugins/job/schedule-build-plugin/job/master/173/console) of the schedule build plugin, though was not visible on builds done about the same time on the following plugins:

This one is due to the artifact caching proxy indeed:

> [ERROR] Failed to execute goal org.kohsuke:access-modifier-checker:1.27:enforce (default-enforce) on project schedule-build: Execution default-enforce of goal org.kohsuke:access-modifier-checker:1.27:enforce failed: Plugin org.kohsuke:access-modifier-checker:1.27 or one of its dependencies could not be resolved: Failed to collect dependencies at org.kohsuke:access-modifier-checker:jar:1.27 -> org.kohsuke:access-modifier-suppressions:jar:1.27: Failed to read artifact descriptor for org.kohsuke:access-modifier-suppressions:jar:1.27: Could not transfer artifact org.kohsuke:access-modifier-suppressions:pom:1.27 from/to azure-proxy (https://repo.azure.jenkins.io/public/): transfer failed for https://repo.azure.jenkins.io/public/org/kohsuke/access-modifier-suppressions/1.27/access-modifier-suppressions-1.27.pom, status: 504 Gateway Time-out -> [Help 1]

**Comment by lemeurherve** [comment]
Looking at datadog logs, I've noticed these 504 errors come only from the Azure provider (about 2/3 of the requests), I suspect the problem comes from the overlapping IP problem we have with our Azure prodpublic cluster.
Putting https://github.com/jenkins-infra/helpdesk/issues/2844 in motion to try to resolve this problem.

**Comment by dduportal** [comment]
> I suspect the problem comes from the overlapping IP problem we have with our Azure prodpublic cluster.
> Putting https://github.com/jenkins-infra/helpdesk/issues/2844 in motion to try to resolve this problem.

Moving back to "infra-team-sync-next" while the work is done in #2844

**Comment by jglick** [comment]
Stuff in `.mvn/extensions.xml` is special because it is loaded before the POM is even interpreted, so I think it always comes from Central.

**Comment by timja** [comment]
Not as far as I can tell our settings.xml just isn't telling it to mirror that.

It's doing:
```xml
  <mirror>
      <id>azure-proxy</id>
      <url>https://repo.azure.jenkins.io/public/</url>
      <mirrorOf>repo.jenkins-ci.org</mirrorOf>
  </mirror>
```

Whereas it should be:
```xml
<mirrorOf>central,repo.jenkins-ci.org</mirrorOf>
```

or (may fail in some niche cases, debatable on whether that should be fixed or not)
```xml
<mirrorOf>*</mirrorOf>
```

see also:
https://marc.info/?l=maven-user&m=152118449814870&w=2
https://stackoverflow.com/questions/49284462/failed-to-read-extensions-descriptor-could-not-find-artifact-in-central

**Comment by dduportal** [comment]
Blocked by https://github.com/jenkins-infra/helpdesk/issues/2924 and https://github.com/jenkins-infra/helpdesk/issues/2844

**Comment by dduportal** [comment]
Summary of the work done last week on this topic:

- Fixes to the ACP configuration (Nginx) to fix the HTTP/5xx errors:
  - https://github.com/jenkins-infra/helm-charts/pull/396
  - https://github.com/jenkins-infra/helm-charts/pull/405


Our tests shows that the Azure proxy is working without 5xx errors now, but performing slowly.

I'm closing the issue as we siwtched to AWS and DO: let's follow in https://github.com/jenkins-infra/helpdesk/issues/2752
