### ISSUE TITLE
forget password

### ISSUE THREAD

**Issue by kumarchk** [jenkins-infra/helpdesk#3225]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

how to recover my password

**Comment by timja** [comment]
Click forgot password on https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Closing as no answer and no details from the requester
