### ISSUE TITLE
Add AAAA records, support installs IPv6 only environments

### ISSUE THREAD

**Issue by BartjeD** [jenkins-infra/helpdesk#3227]
Per the title my use case is an IPv6 only environment. 
I'm attempting to install Jenkins bare metal on a Debian 11 environment.

The first issue I run into is that the mirror is unreachable because it doesn't have an AAAA record.

I've considered using the Docker IPv6 infrastructure and LTS container instead. 
But I really like the charm of simply using apt to update Jenkins and not having to use a container at all.

Given that countries like India are now IPv6 only, and that other countries are moving to IPv6 being a lot cheaper than having servers with IPv4 I'm wondering why the infrastructure of the world's most popular CI doesn't support this basic scenario (yet?) :D

Could these AAAA records be added?

And is my assumption correct that Jenkins will work on IPv6? 
I'm assuming I will have to set it to prefer IPv6 over IPv4 as a Java dual stack environmental configuration.

Thanks in advance!
B

**Comment by dduportal** [comment]
Hi @BartjeD , thanks for raising the issue.

For any issue with Jenkins itself, please open an issue on community.jenkins.io where you'll benefit from the help of the community.

Regarding the Jenkins public infrastructure, I'm not sure to understand the issue?
We do not have `AAAA` DNS record for a reason: we do not have public IPv6 for providing the services.
I'm not aware of IPv4 not being usable when your infrastructure is using IPv6: do you have more information on that topic? It seems quite a breaking change of the internet (I don't say we should not use IPv6, but it has a "cost" so if need it has to be planned). ?

**Comment by BartjeD** [comment]
IPv6 isn't compatible with IPv4 by design.

You can use a NAT64 gateway to map to IPv4 but then you still need a machine with an IPv4. Which you don't have in a IPv6 only situation. Like mine.

This is what docker writes: 
https://www.docker.com/blog/beta-ipv6-support-on-docker-hub-registry/

You can find more about it here,
https://www.zdnet.com/home-and-office/networking/five-ways-for-ipv6-and-ipv4-to-peacefully-co-exist/

**Comment by dduportal** [comment]
Thanks @BartjeD for the pointers.

For the team: we already got an (old) issue about IPv6: https://github.com/jenkins-infra/helpdesk/issues/62/

**Comment by dduportal** [comment]
For information, in order to solve this issue, we are working on the underlying networks of our infrastructure as described in https://github.com/jenkins-infra/helpdesk/issues/2924.

We'll update this issue once fixed.

**Comment by BartjeD** [comment]
:)

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by dduportal** [comment]
Hi @BartjeD , we just finished exposing https://get.jenkins.io through IPv6 in https://github.com/jenkins-infra/helpdesk/issues/3639 .

Other services might have to be exposed: do you have some examples that you are failing to use with IPv6?

We'll continue in this issue and close when all services will be reachable through both stacks.

**Comment by lemeurherve** [comment]
Since the addition of the dedicated IPv6 load balancer service for https://github.com/jenkins-infra/helpdesk/issues/3639 there is nothing more to do, every service hosted on `publick8s` cluster are accessible via IPv6 🎉
