### ISSUE TITLE
Not able to retrieve forgot password. New signup going for 500 error

### ISSUE THREAD

**Issue by Nibeditar333** [jenkins-infra/helpdesk#3228]
Hi,

I am not receiving my forgot password mail. From past 15days its the same issue. I initially thought it might be n/w issue. But its not as its consistent from a long time. Also, I tried signing up for a new user with a different email ids. Every time it's saying wrong captcha after providing all details and submitting the page. After providing the captcha for the second time and submitting the request again, it's going for 500 error. So now I am stuck and not able to  create a new user nor i am able to retrieve my old user credentials. 

Please help.

Thanks,
Nibedita 

> 

hi,
 Just now I tried forgot password link again and received the mail this time. I guess some update must have done from your end after I raising this ticket. thanks for the quick resolution. Anyways my user id is nibeditar333 which was not receiving the mail. Userid nibedita3006 didnt get created due to 500 servlet error.

**Comment by dduportal** [comment]
Hi @Nibeditar333 could you share with us the user id and email that you used so we can diagnose and solve please?

**Comment by dduportal** [comment]
Hi @Nibeditar333 , I see that you edited your message after my comment by adding your user id.

Just checked and there is a user account created with the user id  `nibedita3006`.

The email associated to this account has been used to reset the password: you should have receieved instructions for it.

**Comment by dduportal** [comment]
Closing as no answer and no details from the requester
