### ISSUE TITLE
Can't log into artifactory (https://repo.jenkins-ci.org/)

### ISSUE THREAD

**Issue by tdraebing** [jenkins-infra/helpdesk#3229]
### Reproduction steps

1. Open https://repo.jenkins-ci.org/ in the browser
2. click login
3. Enter credentials configured at https://accounts.jenkins.io/

### Expected Results

Login works.

### Actual Results

I get an Unauthorised response.

### Anything else?

My credentials work in Jira, so they are fine.
I also tried changing the password, but this didn't help.

**Comment by dduportal** [comment]
Hi @tdraebing , could you describe the use case (e.g. what is the reason why you have to log-in on repo.jenkins-ci.org)?

I'm asking because only plugins maintainers are, as for today, allowed to log in to repo.jenkins-ci.org. The use case is to allow maintainers to publish new content. Otherwise there is no need to log-in.
Account synchronization between accounts.jenkins.io and repo.jenkins-ci.org is driven by https://github.com/jenkins-infra/repository-permissions-updater which... only list plugin maintainers.

As I can't find your GitHub ID in https://github.com/jenkins-infra/repository-permissions-updater, I assume you're not a plugin maintainer but I could be wrong, hence my question to see what is your use case so we can help.

**Comment by tdraebing** [comment]
Hi @dduportal ,

I am indeed not a plugin maintainer yet, but I am trying to publish a new plugin (https://github.com/jenkins-infra/repository-permissions-updater/issues/2947). One of the prerequisites seems to be that I login once into the artifactory, which currently fails.

Did I miss a step to add myself to the list of plugin maintainers?

**Comment by NotMyFault** [comment]
> I'm asking because only plugins maintainers are, as for today, allowed to log in to repo.jenkins-ci.org. The use case is to allow maintainers to publish new content. Otherwise there is no need to log-in.
Account synchronization between accounts.jenkins.io and repo.jenkins-ci.org is driven by https://github.com/jenkins-infra/repository-permissions-updater which... only list plugin maintainers.

@dduportal I think we talk past each other. Logging into repo.j-ci is mandatory for new hosting requests managed through the RPU. At this state, future plugin developers have LDAP reference in RPU files yet, but should be able to log into artifactory nevertheless, like it was in the past.

**Comment by dduportal** [comment]
Thanks for the answers @tdraebing @NotMyFault . I was asking because I'm still trying to understand how the whole RPU/hosting/artifactory process works (even for the infra team) from end to end and clearly I still miss some pieces of knowledge :)

> like it was in the past.

I did not know it was posible before. i've always thought it was mandatory. Let me check with @daniel-beck to see what did I miss.

For information, allowing any LDAP user to log in on artifactory might be soon an infrastructure requirement so that would solve the issue here in long term.

**Comment by daniel-beck** [comment]
Copying here from IRC for posterity: Everyone with an account can log in to Artifactory. My guess was a bad email address on the account (but at least right now that doesn't seem to be the case by looking at the account app).

Unfortunately we have extremely short log retention in Artifactory (~30 minutes for the log that's relevant here) and no way to change it. We'd basically need to set an "appointment" for you to attempt to log in and us to check the logs to see what went wrong.

**Comment by timja** [comment]
Email address looks fine, ldap user account is `tdraebing`.

**Comment by tdraebing** [comment]
Some additional information:
I created my account already quite a while ago to have access to Jira, but never used it for artifactory.
The response I get from artifactory when trying to login is:

`{"anonAccessEnabled":true,"buildGlobalBasicReadAllowed":true,"buildGlobalBasicReadForAnonymous":true,"hideUnauthorizedResources":false,"passwordSettings":{"encryptionPolicy":"SUPPORTED","expirationPolicy":{"enabled":false,"passwordMaxAge":60,"notifyByEmail":true},"resetPolicy":{"enabled":true,"maxAttemptsPerAddress":3,"timeToBlockInMinutes":60}},"userLockPolicy":{"enabled":false,"loginAttempts":5},"basicAuthEnabled":true,"centralOAuthProviders":{"enabled":false,"enabledProviderNames":[]},"feedbackMsg":{"error":"Login has failed.\nDue to Incorrect username/password or locked user."}}`

@daniel-beck When would be a good time for you to have a look at the logs?

**Comment by dduportal** [comment]
On keycloak, the account `tdraebing` was not set to "user email verified". I've manually set it up.

@tdraebing can try commenting here with the message "go go" and then try to log in in artifactory? I'm watching the logs

**Comment by daniel-beck** [comment]
> When would be a good time for you to have a look at the logs?

How about 1 PM CET (~2 hrs from now)?

**Comment by daniel-beck** [comment]
> The response I get from artifactory when trying to login

To clarify, when you try to log in, it's through the UI at https://repo.jenkins-ci.org/ui/ ?

**Comment by daniel-beck** [comment]
FTR `tdraebing` does not currently exist in Artifactory (which is the normal situation before initial log-in).

**Comment by daniel-beck** [comment]
Adding the @tdraebing ping I forgot in all of my spam above, in case that makes a difference in notifications, given the time sensitivity.

**Comment by tdraebing** [comment]
Sorry, I am currently attending a conference and thus missed the notifications.

Yes, I am using https://repo.jenkins-ci.org/ui/login/.

@daniel-beck gogo :-)

I will also try again at 1PM CET just in case.

**Comment by dduportal** [comment]
I was able to find the error message in Artifactory. I see 2 attempts, bot are`LDAP authentication failed for user: 'tdraebing'`.

Checking the LDAP log but artifcatory only refuse the loggin because the couple user + password that it receieved were refused on the LDAP.

**Comment by tdraebing** [comment]
Strange. I checked the login on accounts.jenkins.io directly after I tried artifactory and it worked. I am using a password manager to fill in the credentials, so a typo can't be the cause. I also checked the request sent to artifactory and the password was correct.

**Comment by timja** [comment]
Any chance you have an on password saved or for something else? Artifactory is special in that it's on an old domain (jenkins-ci.org) so your password manager could be filling the wrong password instead of the jenkins.io one.

(just checking if its possible)
