### ISSUE TITLE
New maven-11 agents aren't spawning

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3230]
### Service(s)

ci.jenkins.io

### Summary

https://ci.jenkins.io/job/Infra/job/repository-permissions-updater/job/PR-2949/ is stuck in queue for 1h 30m by now waiting, that new maven-11 agents spawn, but nothing happens.

**Comment by dduportal** [comment]
I think we are hitting a concurency bug in the kubernetes plugin:

- We specify max/ 30 pod for DOKS and 150 to CIK8S
- BUT when we checked on DOKS:

  ```
  $ kubectl get -n jenkins-agents pod | grep jnlp-maven -c
  89
  ```

- While CIK8S had... 0 pods scheduled....

**Comment by dduportal** [comment]
We have to wait that the "build wave" finishes before DOKS can finish all its tasks.

**Comment by dduportal** [comment]
Had a discussion (in a private channel, sorry) with @jglick and @jnord whome provided differents clues and useful indications.

- First thing first: the Kubernetes plugins does not seem to follow the max pod limitation in a context like this one (a lot of request and multiple Kubernetes Clouds used in a "spread load" with the same pod templates and same labels).
  - It is a bug to be reported in the plugin in any cases
  - Mitigation is to split Kuberentes Clouds by "functional" requirements (Linux / Windows, or per label).
  - Ref. https://github.com/jenkinsci/kubernetes-plugin/pull/939 

- Second thing: we (infra team) should add [Kubernetes Resource Quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) in the clusters used by ci.jenkins.io to:
  - Ensure that the queue of tasks is not moved to the clusters, like it was last Tuesday, into the Kubernetes control plane of DigitalOcean -e.g. `doks`-  which had ~80 pod created, but only ~30 were running (the 50 other were "pending"). Better to refuse pod creation so Jenkins will not try to schedule more.

    > https://kubernetes.io/docs/concepts/policy/resource-quotas/ does say the API server will actually reject the pod creation with a 403. Really not sure what the kubernetes plugin will do with such a response currently. Maybe that KubernetesCloud will not succeed in provisioning agents to match the Queue’s request, and the next one in line will take over. Certainly not a commonplace scenario.


- Third thing: given the "edge case" we have for ci.jenkins.io (multiple Kubernetes Clouds used on different clouds for credits usages, in spreading mode) we study a paradigm change on how we handle this workload:
  - Use each cloud a certain percentage of the year (per day, week, month, whatever) but only use 1 (easier scheduling) and rotate on maintenance/issue (and regularly like backup/restores).
  - Spread workload using shared library (modulos, whatever solution)
  - Use a federated Kubernetes system such as https://github.com/karmada-io/karmada or Scaleway's https://www.scaleway.com/en/kubernetes-kosmos/

**Comment by dduportal** [comment]
Work in progress: @smerle33 is currently working to add resource quotas

**Comment by smerle33** [comment]
cleaning up the dangling pods on `doks` with the following command:  
```bash
kubectl get pods -n jenkins-agents | grep 3d | awk '{print $1}' | xargs -I{} kubectl -n jenkins-agents delete pod {}
```

(pods aged more than 3 days must be terminated)

**Comment by dduportal** [comment]
Quotas had been applied; and we triggered a new BOM (from a PR) build to see the new behavior: https://ci.jenkins.io/blue/organizations/jenkins/Tools%2Fbom/detail/PR-1435/6/pipeline

**Comment by dduportal** [comment]
- The resource quota seems to be an efficient workardound, thanks @jglick !

![Capture d’écran 2022-11-14 à 18 33 00](https://user-images.githubusercontent.com/1522731/201727363-7f2b0116-dd05-4c9c-bea2-b165bdf48412.png)

(you can see that the "cik8s" which has 120 pod max is behaving as expected now)

**Comment by dduportal** [comment]
> Not quite sure what I am looking at in the graph, but if you say it is working, 🎉

I've edited my message to give more context about the graph. Sorry it wasn't clear before

**Comment by dduportal** [comment]
A better graph to show the issue, which is the amount of scheduled pods (Pending *and* Running).

Blue is DigitalOcean (max 30 simultaneously), red is AWS (max 120):

![Capture d’écran 2022-11-14 à 18 59 57](https://user-images.githubusercontent.com/1522731/201732786-72f4573e-e89f-46b3-b372-48fe24dafb90.png)

**Comment by NotMyFault** [comment]
Thanks for investigating and fixing (and the fancy graphs)!

**Comment by dduportal** [comment]
> So would you say
> 
> > not sure what the `kubernetes` plugin will do with [a 403] response currently. Maybe that `KubernetesCloud` will not succeed in provisioning agents to match the `Queue`’s request, and the next one in line will take over.
> 
> has been demonstrated? Not sure if you observed an individual case directly, e.g. with Jenkins log messages. If it seems reliable, this would be worth mentioning in plugin docs as a viable configuration.

I can't be sure, but it looks like on a "single BOM" run. If it is ok for you, we'll try to run a lot more of these builds and restart ci.jenkins.io in the upcoming days along with checking the controller logs so we'll be able to confirm.
