### ISSUE TITLE
i forgot my jenkins login and password

### ISSUE THREAD

**Issue by ArtemChumachenko** [jenkins-infra/helpdesk#3232]
### Service(s)

Accounts

### Summary

i forgot my jenkins login and password

### Reproduction steps

          
i forgot my jenkins login and password

**Comment by dduportal** [comment]
Hi @ArtemChumachenko , you should be able to reset your password on accounts.jenkins.io by specifying the email you used to register.

**Comment by dduportal** [comment]
Closing as no answer and no details from the requester
