### ISSUE TITLE
Please install `pipeline-github` plugin

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3233]
### Service(s)

ci.jenkins.io

### Summary

To address https://github.com/jenkinsci/bom/issues/1581 we would need https://plugins.jenkins.io/pipeline-github/ to be installed on ci.jenkins.io, since the basic `github-branch-source` does not currently bind PR labels to an environment variable.

**Comment by smerle33** [comment]
plugin has been installed while working on #3234

**Comment by dduportal** [comment]
Reopening because we forgot to add the plugin to the list in Puppet hieradata for ci.jenkins.io

**Comment by lemeurherve** [comment]
Plugin added to the list in Puppet, closing this issue.
