### ISSUE TITLE
Update ci.jenkins.io to latest LTS version (2.361.4)

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3234]
### Service

trusted.ci, cert.ci and release.ci, ci.jenkins.io

### Summary

Please update ci.jenkins.io to use the latest LTS version `2.361.4`.

**Comment by smerle33** [comment]
trusted.ci is up to date

**Comment by dduportal** [comment]
cert.ci is up to date

**Comment by dduportal** [comment]
release.ci.jenkins.io is up to date as well (https://github.com/jenkins-infra/docker-jenkins-lts/pull/624 -> https://github.com/jenkins-infra/kubernetes-management/pull/3209)
