### ISSUE TITLE
forgot username and password

### ISSUE THREAD

**Issue by pj-phx** [jenkins-infra/helpdesk#3235]
### GitHub repositories

I can not log in as I have forgotten my username and password log in

### GitHub users to have permission

@MarkEWaite 
@

### Permission level

Admin

### Justification

![image](https://user-images.githubusercontent.com/66885175/201736530-68cc9f00-d2b2-4ae4-9ebc-8be37913143a.png)

**Comment by dduportal** [comment]
@pj-phx which service are you trying to log-in into?

**Comment by pj-phx** [comment]
Hi,  I am trying to log into Jenkins
________________________________

**Comment by MarkEWaite** [comment]
> Hi, I am trying to log into Jenkins

The Jenkins infrastructure project can't help you login to a Jenkins system that is not administered by the Jenkins project.  Contact the administrators of the Jenkins system that is rejecting your login.

**Comment by pj-phx** [comment]
Hi Mark,

Thanks! I thought it was weird as well but for some reason when I tried to reset it, it brought me here to GitHub.

I will try again.

P
________________________________

**Comment by MarkEWaite** [comment]
> Hi Mark, Thanks! I thought it was weird as well but for some reason when I tried to reset it, it brought me here to GitHub. I will try again. P

If the URL of the system you're trying to use ends in "jenkins.io", then the Jenkins infra team can help.  Some of those include:

* https://ci.jenkins.io/
* https://weekly.ci.jenkins.io/
* https://issues.jenkins.io/


If they end in "jenkins-ci.org", the infra team can also help.  Otherwise, not really.

**Comment by pj-phx** [comment]
HI Mark,

Thanks so much. I tried again and I got in! I finally got a reset email and it worked. It just took a few hours to come to me lol.

Thank you so much again,
Petra

________________________________
