### ISSUE TITLE
`Jenkinsfile` not being run for `jenkinsci/bridge-method-injector`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3240]
### Service(s)

ci.jenkins.io

### Summary

In https://github.com/jenkinsci/bridge-method-injector/pull/30 I have added a `Jenkinsfile` for `jenkinsci/bridge-method-injector`. However, the `Jenkinsfile` is not being run, so I am guessing a new job needs to be created on ci.jenkins.io.

### Steps to reproduce

1. Obtain write access to `jenkinsci/bridge-method-injector`.
2. Create a PR that adds or modifies a `Jenkinsfile`.
3. Go to the Checks tab in the GitHub PR.

### Expected results

The `Jenkinsfile` changes should be running in CI for testing purposes.

### Actual results

No CI build was performed.

**Comment by NotMyFault** [comment]
Typically, jobs spawn once the folder scan runs the next time, at least that's the case when forking repositories with `Jenkinsfile`s to the organization.
Unless you want the repository in a different folder, like "Tools", this task is performed automatically (although I don't have the exact periods in mind).

**Comment by basil** [comment]
No. This needs to be added to https://ci.jenkins.io/job/jenkinsci-libraries/

**Comment by lemeurherve** [comment]
Added to the jenkinsci-libraries jobs folder filter:

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/91831478/202560288-4deebbee-3421-4dab-a166-b7bc85af8f1b.png">

**Comment by basil** [comment]
It is working now so this ticket can be closed. Thanks!
