### ISSUE TITLE
add java19 support for developpers to pre-built and try

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3243]
### Service(s)

ci.jenkins.io

### Summary

Offer Java19 for developer to use it as preview and research and development

**Comment by dduportal** [comment]
(context: issue created following the Platform SIG meeting the 18 Nov. 2022)

**Comment by dduportal** [comment]
One last mile: let's annouce this to developer mailing list :)

**Comment by dduportal** [comment]
And documentation update in https://github.com/jenkins-infra/documentation/blob/main/ci.adoc
