### ISSUE TITLE
jenkins login access

### ISSUE THREAD

**Issue by 0sayed0** [jenkins-infra/helpdesk#3246]
### Type(s) of account issue

I've lost my password

### Summary

i forgot my password of jenkins so i want access my account help me

### jenkins.io account username

admin

### jenkins.io account email

go4sabeel@gmail.com

### Which URL are you trying to login at?

http://15.207.223.146:8080/

**Comment by lemeurherve** [comment]
Hello @0sayed0, this instance hosted on this IP isn't part of Jenkins Infrastructure, we can't do anything for you, you'll have to contact your local administrator.

Out of curiosity, where did you find the URL to open an issue here? Was it displayed somewhere or did you search for it?
