### ISSUE TITLE
Migrate halkeye/jenkins-io-components to jenkins-infra

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3250]
### Service(s)

GitHub

### Summary

As its already used on accounts, and wiki, and I'd like to use it on www, it should get moved into the official org.

I know I have permission to transfer orgs, but every time I've done so I've lost access, so this time I'm trying a ticket.

@dduportal and @lemeurherve access both should have access.

i do have github actions secrets for chromatic (meh so far) and publishing to github pages (yay) which would be nice to stay working.

**Comment by lemeurherve** [comment]
Could you give me admin access to your repository so I can initiate the migration?

**Comment by halkeye** [comment]
Ah, okay, that isn't a thing anymore - https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository

I'm working on publishing an alpha branch. When that's done, i'll transfer it to jenkins-infra, and let you take over?

**Comment by hervelemeur** [comment]
I can clone it to jenkins-infra and set back your permissions on it if you want, you'll be able to push your alpha branch on it after, WDYT?

**Comment by halkeye** [comment]
I have to goto bed anyways, figuring out semantic-release+github actions is harder than I thought :)

https://github.com/jenkins-infra/jenkins-io-components

It's transferred over. I think its using my NPM_TOKEN in secrets, but I don't know if that copies when it transfers over. If i can be made admin I can put it back, or we can create a service npm account.

**Comment by lemeurherve** [comment]
NPM automation token set in the repo secrets, first release on https://www.npmjs.com/package/@jenkinsci/jenkins-io-components/v/1.15.1 published 🚀 

Closing this issue, thanks @halkeye!
