### ISSUE TITLE
unable to log in to my jenkins account

### ISSUE THREAD

**Issue by tabrez067** [jenkins-infra/helpdesk#3253]
### Type(s) of account issue

I didn't receive any email, Other (please describe in the summary below)

### Summary

please recover my account

### jenkins.io account username

tabrez067

### jenkins.io account email

tabrezahmedr48@gmail.com

### Which URL are you trying to login at?

http://localhost:8080/login?from=%2F

**Comment by lemeurherve** [comment]
You're trying to log in your own instance running locally on your machine, nothing to do with Jenkins Infrastructure, closing this issue.
