### ISSUE TITLE
forgot username and password

### ISSUE THREAD

**Issue by hsnshn** [jenkins-infra/helpdesk#3254]
### Type(s) of account issue

I've lost my password

### jenkins.io account username

hsnshn

### jenkins.io account email

hasansahin14@hotmail.com

### Which URL are you trying to login at?

http://localhost:8080/loginError

**Comment by lemeurherve** [comment]
You're trying to log in your own instance running locally on your machine, nothing to do with Jenkins Infrastructure, closing this issue.
