### ISSUE TITLE
Slow download of Jenkins Windows Installer (`jenkins.msi`)

### ISSUE THREAD

**Issue by rajanrai2198** [jenkins-infra/helpdesk#3255]
Problem with the [Thank you for downloading Windows Stable installer](https://www.jenkins.io/download/thank-you-downloading-windows-installer-stable/) page, [source file](https://github.com/jenkins-infra/jenkins.io/blob/master/content/download/thank-you-downloading-windows-installer-stable.html.haml)

TODO: My internet speed is good but jenkins.msi is taking too much time to download.
## Screenshots 
![image](https://user-images.githubusercontent.com/84988130/203700401-9730bed0-894e-4f45-b5bd-4ff0af827b2a.png)TODO:

## Possible Solution 

 

N/A

**Comment by dduportal** [comment]
Hi @rajanrai2198 , you can find a short term solution in https://github.com/jenkins-infra/helpdesk/issues/3196.

We are searching for organisation in India willing to host a Jenkins mirror (ref. https://github.com/jenkins-infra/helpdesk/issues/3182 for instance) to avoid redirection to mirrors that are slow for Indian users. If you know any volunteer please let us know!

**Comment by dduportal** [comment]
The link https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/windows-stable/2.361.4/jenkins.msi should be faster for you!

**Comment by dduportal** [comment]
Hi @rajanrai2198 , as per https://github.com/jenkins-infra/helpdesk/issues/3182, there is a new Jenkins mirror in Asia : could you try again and let us know if you are redirected to this new mirror (which speed should be clearly higher)?
