### ISSUE TITLE
Host my new open-source plugin to Jenkins GitHub

### ISSUE THREAD

**Issue by kalpshekhar** [jenkins-infra/helpdesk#3256]
### GitHub repositories

I don't have a repository yet. Plugin name will be webmethods-is-package.

### GitHub users to have permission

@kalpshekhar

### Permission level

Admin

### Justification

Admin to manage my plugin repository.

**Comment by NotMyFault** [comment]
Hey,

if you want us to host your plugin, please follow the steps [in the hosting guide](https://www.jenkins.io/doc/developer/publishing/requesting-hosting/).

Thanks!
