### ISSUE TITLE
Azure: Re-create networks to fix overlap issues and support of IPv6

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3257]
Description WiP (I needed an initial link)

Blocked by https://github.com/jenkins-infra/helpdesk/issues/2924

(edited)
This issue tracks the work to have a separate Terraform project to manage the Azure network systems that are critical.
The goal is to limit the scope of anything going wrong in the Terraform Azure project.

This task is also the opportunity to create a new set of networks to solve the 2 following critical issues:

- IPv6 support for public access - https://github.com/jenkins-infra/helpdesk/issues/3227
- IPv4 overlapping issues on the current `prod-public` network (https://github.com/jenkins-infra/helpdesk/issues/3221#issuecomment-1305403066)

- Related to https://github.com/jenkins-infra/iep/tree/master/iep-002
- Private network:
  - https://github.com/jenkins-infra/azure-net/pull/4
  - https://github.com/jenkins-infra/azure-net/pull/5
  - VPN machine
- Public network: TBD

**Comment by dduportal** [comment]
Status:

- VPN machine (terraform managed) is up and running
- Puppet code cleanup is OK
- Next step: add VM under puppet management

**Comment by lemeurherve** [comment]
The new VPN VM is now under puppet management, and I've successfully got access to the VPN with OpenVPN, closing this issue as done.

**Comment by dduportal** [comment]
We still have the (new) public network (and its VPN) to do.

But private network (and its VPN) are ✅ Nice work!

**Comment by dduportal** [comment]
Closing as the required work was done.

Follows ups: #3306 and #3307
