### ISSUE TITLE
Azure: Cleanup of resource group `prod-communityfunctions`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3258]
Following https://github.com/jenkins-infra/helpdesk/issues/3249:

![image](https://user-images.githubusercontent.com/1522731/203829447-e6971bd0-b727-4a51-938c-2474b70947be.png)

**Comment by dduportal** [comment]
Searching for potential usage and definition of these elements:

- https://github.com/jenkins-infra/analytics-functions => code is archived
- https://github.com/jenkins-infra/community-functions => same
- Former Azure terraform management does not have traces of these elements: https://github.com/jenkins-infra/azure/tree/legacy-tf (also tried to grep locally)
  - Neither current: https://github.com/search?q=repo%3Ajenkins-infra%2Fazure%20functions&type=code
- No code on the organization either: https://github.com/search?q=org%3Ajenkins-infra+prod-community-functions&type=code (only the issue here)
- In the Azure Portal, all functions are marked as "SCM controlled" and both `jenkins-community-functions` and `jenkins-infra-functions` have the same subset of functions (which are defined in https://github.com/jenkins-infra/community-functions):

<img width="1192" alt="Capture d’écran 2022-12-06 à 12 24 24" src="https://user-images.githubusercontent.com/1522731/205899197-54ebcfbb-587e-4c40-a70d-1acee69daf8f.png">

<img width="953" alt="Capture d’écran 2022-12-06 à 12 24 17" src="https://user-images.githubusercontent.com/1522731/205899188-3b856737-f4fb-4b40-a36a-0d2a90018573.png">

**Comment by slide** [comment]
👍🏻

**Comment by dduportal** [comment]
As explained in https://groups.google.com/g/jenkinsci-dev/c/3Dv9J96hbOc, the resources had been deleted.
