### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by steephart** [jenkins-infra/helpdesk#3261]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account username

Alex

### jenkins.io account email

alexsteephart98@gmail.com 

### Which URL are you trying to login at?

https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Hi @steephart you don't seem to have any account on `*.jenkins.io`: is it expected?

**Comment by dduportal** [comment]
Closing as no answer received from the author.

Feel free to reopen with the requested informations.
