### ISSUE TITLE
Facing an issue while creating an account on Jenkins.

### ISSUE THREAD

**Issue by GargAnshu9468** [jenkins-infra/helpdesk#3263]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I was just trying to create an account on Jenkins. But It's troughing an error as mentioned below -

Oops!
The anti-spam system was triggered: we need your help to prove that you are human and not a robot (or a human spammer). Open an issue on the [Jenkins Infrastructure Help Desk](https://github.com/jenkins-infra/helpdesk/issues/new?template=2-account-issue.yml&labels=triage,accounts&url=account.jenkins.io/antispam) and provide the email and the userid you tried to register with, as well as the version of Jenkins you currently are running. Try to make your issue look legitimate and not like it's written by someone who doesn't know anything or just read the jenkins.io home page. If we don't think your signup request is legitimate, it won't be approved. We're a popular target of human spammers, i.e. actual people with actual web browsers trying to post their spam in our applications.

### jenkins.io account username

anshugarg

### jenkins.io account email

a.kgarg9050@gmail.com

### Which URL are you trying to login at?

[account.jenkins.io/antispam](https://accounts.jenkins.io/signup)

**Comment by dduportal** [comment]
Hi @GargAnshu9468 your account had been created manually + a password re-generated : you should receive 2 emails.

If you did not, please use the "Forgot password" link at https://accounts.jenkins.io/login to reset the password again.
