### ISSUE TITLE
Improve SEO of jenkins.io / docs on resetting passwords so we stop getting reset password requests here for non jenkins.io accounts

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3264]
### Service(s)

Accounts

### Summary

People googling how to reset their Jenkins password often end up on our infrastructure.

![image](https://user-images.githubusercontent.com/21194782/204155822-1bf17dcd-cd25-4bf9-9834-bd6e419fa776.png)

Maybe we should robots.txt the site and only link there from other places?

e.g. https://github.com/jenkins-infra/helpdesk/issues/3262 and many others

**Comment by NotMyFault** [comment]
> Maybe we should robots.txt the site and only link there from other places?

Absolutely, `/passwordReset` shouldn't be indexed by search engines at all.

**Comment by lemeurherve** [comment]
We should add a `noindex` meta instead of a robot.txt according to [Google doc](https://developers.google.com/search/docs/crawling-indexing/robots/intro): 

> Warning: Don't use a robots.txt file as a means to hide your web pages from Google search results.
> 
> If other pages point to your page with descriptive text, Google could still index the URL without visiting the page. If you want to block your page from search results, use another method such as password protection or [noindex](https://developers.google.com/search/docs/crawling-indexing/block-indexing).

**Comment by dduportal** [comment]
Thanks @NotMyFault @timja @lemeurherve for this!

The accountapp with the `noindex` is deployed in production since a few days and we are no more in the Google results:

<img width="1059" alt="Capture d’écran 2022-12-06 à 09 48 45" src="https://user-images.githubusercontent.com/1522731/205864062-218bc901-1cb8-4702-a326-1b06cfefcf2d.png">

**Comment by lemeurherve** [comment]
For the record, I've used Google Search Console's "Removal" tool to temporary remove all accounts.jenkins.io links (for 6 months), and cleared cached URLs so when they will be reindexed the `noindex` beta should be taken in account. (There were still accounts results in Google Search yesterday before doing that)

![image](https://user-images.githubusercontent.com/91831478/205870789-18b95273-4199-42d7-a342-5f0631381bfc.png)
