### ISSUE TITLE
Not able o recovery password

### ISSUE THREAD

**Issue by HarithaAnu** [jenkins-infra/helpdesk#3265]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I have been blocked by antisoam system

### jenkins.io account username

admin

### jenkins.io account email

tintooxavierseeroo@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by lemeurherve** [comment]
Hello @HarithaAnu, were you trying to log in or to create an account?
If it was a login, on which Jenkins instance/URL?
If it was creating an account, please try with another username.

**Comment by dduportal** [comment]
Closing as no answer (and probably wrong issue tracker).
