### ISSUE TITLE
Forgot username and password

### ISSUE THREAD

**Issue by tyui456** [jenkins-infra/helpdesk#3267]
### Type(s) of account issue

I've lost my password

### jenkins.io account email

sethyjasaswee0@gmail.com

### Which URL are you trying to login at?

localhost 8080

**Comment by NotMyFault** [comment]
Hey @tyui456,

this category of support tickets is only available for the jenkins.io infrastructure. If you need help with your local Jenkins instance, ask your administrator for support.
