### ISSUE TITLE
Running custom SQL request for Plugin Health Scoring project

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3269]
Until now, the Plugin Health Scoring application wasn't configured correctly to communicate with GitHub API. 
This result in false negative results on SCM validation probe. As this probe requires a release to be executed again, only plugins with new releases are updated. But, with the new configuration being valid, we need the probe to be executed on all the known plugins, regardless of a new release. 

To do so, I need to run a SQL request on the database used by the application.

```sql
UPDATE plugins
SET details = details::jsonb - 'scm';
```

Would you be able to help me do that?

**Comment by dduportal** [comment]
No problem! As we'll do this in async, you confirmed that the "sanity check", after running the request, will be to check http://plugin-health.jenkins.io/probes/results: the line with `scm` should be set to `0` until the next probe execution (at H/10).

**Comment by dduportal** [comment]
Before running the request:

<img width="1441" alt="Capture d’écran 2022-12-06 à 10 23 41" src="https://user-images.githubusercontent.com/1522731/205871818-4849e7ae-65dc-4d80-aa90-a2a1bbc8493c.png">
