### ISSUE TITLE
Update infrastructure to 2.375.1

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3273]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

It's LTS time again and 2.375.1 has been shipped for GA 🎉

By the way, are these issues of use for anyone, still? Updatecli and other automation tools do the work to keep charts and services up to date, no?

**Comment by dduportal** [comment]
- ci.jenkins.io done (restarted the controller from the machine which automatically pull the latest jdk11 image and also upgraded all plugins which triggered a second restart.
- I'm taking trusted.ci an cert.ci (puppet/updatecli job)
- @smerle33 is in charge of release.ci (docker image + kubernetes management) along with yesterday's weekly (for infra.ci/weekly.ci).

**Comment by dduportal** [comment]
- ci.jenkins.io, trusted.ci.jenkins.io and cert.ci.jenkins.io are ✅

**Comment by smerle33** [comment]
- [x] release.ci (docker image + kubernetes management) along with yesterday's weekly (for infra.ci/weekly.ci).
