### ISSUE TITLE
Regarding account information 

### ISSUE THREAD

**Issue by adityapratap12** [jenkins-infra/helpdesk#3275]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I am unable to open my acoount I can't figure out my username and passout lot of mess is there

My email address is singhadi4350@gmail.com
 
can you please help me figure it out

### jenkins.io account username

aditya4350

### jenkins.io account email

singhadi4350@hgmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by lemeurherve** [comment]
Hello @adityapratap12, did you tried to reset your password via https://accounts.jenkins.io/passwordReset?
