### ISSUE TITLE
Unable to deploy .hpi file in artifactory (even with accepted permissions/plugin-zos-devops.yml)

### ISSUE THREAD

**Issue by IBA-mainframe-dev** [jenkins-infra/helpdesk#3279]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hello! I wanted to finally place the plugin in the Jenkins-plugins hub by uploading the source code and the built .hpi file to the Jenkins JFrog artifactory.
**Jenkins JFrog URL, where I was going to deploy:** https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugins/zdevops/1.0.0/zdevops.hpi
![image](https://user-images.githubusercontent.com/74380470/205111470-bb3a9e4d-40e4-42b0-bb76-f09449b84e8c.png)

I managed to upload several files there (such as zdevops-1.0.0-sources.jar, zdevops-1.0.0-javadoc.jar and zdevops-1.0.0.jar), except for one - zdevops.hpi. For some reason, only for zdevops.hpi writes that: 
`"User iba_mainframe_dev is not permitted to deploy 'io/jenkins/plugins/zdevops/1.0.0/zdevops.hpi' into 'releases:io/jenkins/plugins/zdevops/1.0.0/zdevops.hpi'."`
![image](https://user-images.githubusercontent.com/74380470/205111278-658077f3-d241-48de-a95d-12b8c224c7aa.png)

Although the corresponding .yaml file with permissions has been created and lies in [repository-permissions-updater repo](https://github.com/jenkins-infra/repository-permissions-updater). 
Also **link to related permissions file:** https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-zos-devops.yml

Could you please take a look, maybe I'm doing something wrong or is there some other problem? (first time deploying a plugin, maybe I have missed something in the process)
Also **plugin original repo under jenkinsci:** https://github.com/jenkinsci/zos-devops-plugin
Thanks in advance!

### jenkins.io account username

IBA_mainframe_dev

### jenkins.io account email

IAbnitski@ibagroup.eu

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugins/zdevops/1.0.0/zdevops.hpi

**Comment by NotMyFault** [comment]
Take a look at https://www.jenkins.io/doc/developer/publishing/releasing/ how to perform a release of your plugin.

**Comment by dduportal** [comment]
> > [dduportal](https://github.com/dduportal) assigned [dduportal](https://github.com/dduportal) and [NotMyFault](https://github.com/NotMyFault)
> 
> I doubt I can be much of a help here. The plugin uses the gradle JPI plugin, which ultimately doesn't use the MRP, I'm also not aware of how to release Jenkins plugins using Gradle at all, aside from manually uploading files. Doesn't the JPI plugin have some sort of build-in release assistant?

My bad @NotMyFault , I added you by mistake

**Comment by dduportal** [comment]
Hi @IBA-mainframe-dev , what is the result if you follow the instructions at https://www.jenkins.io/doc/developer/publishing/releasing-manually/ (as pointed by @NotMyFault on previous comments)?

**Comment by IBA-mainframe-dev** [comment]
Hello @dduportal, previously, when trying to upload artifacts via CURL, it gave an error as shown in the second screenshot in the description of this issue (there is also an example of the issued CURL command). There was also an error like 403 when trying to download artifacts via the "Deploy" button in the web-ui JFrog interface.
However, I just tried to upload the .hpi file again via "Deploy" button in the artifactory web interface, and it loaded successfully (maybe you configured something - thanks!). Previously, I only managed to upload several files there (such as zdevops-1.0.0-sources.jar, zdevops-1.0.0-javadoc.jar and zdevops-1.0.0.jar).

1. And now the question is, in theory, all necessary files are now placed in:
 https://repo.jenkins-ci.org/ui/repos/tree/General/releases/io/jenkins/plugins/zdevops/1.0.0 
 and Jenkins will pull up the .hpi file that has appeared and the plugin will become available in https://plugins.jenkins.io/? 
2. Are there any additional steps required for the release? And how soon will the plugin become available?
3. And another question, while we are using Gradle, however, we have completed a few more features for the plugin, and when it needs to be updated - will there be access to overwrite files? Because at the moment it does not seem to exist, but while the plugin uses Gradle, CD automation is not available.

We will try to remake the project to use Maven in nearest time, but Gradle is still used - plugin needs to be updated somehow :)
Thanks in advance!

**Comment by dduportal** [comment]
Hi @IBA-mainframe-dev , thanks a lot for the feedback. Sorry I totally missed it is using Gradle: I'm only having a bit of knowledge around Maven (and either manual or CD processes from the doc). 
Maybe there is something missing for Gradle use case, but I can't help on this.

=> You might want to raise the topic on the developer mailing list to get help from maintainers who, for sure, would have the knowledge on that "Gradle/Maven" tooling area (that could also help if documentation on jenkins.io should be written or updated).


To answer your questions, I'm not sure how is the initial release process of new plugin working to be honest. But usually for other plugin releases, there is a regular (private) process which runs every 15 min to detect last plugin updates and update the update center's index + proceed to make the plugin binary available through the Jenkins mirror (so it would be available for download). Let's wait 1-2 hours in order to all processes to run and see if your initial release is picked up: otherwise we'll check what is missing.

**Comment by dduportal** [comment]
- The plugin is visible on the update center and (at least 5) download mirrors: https://get.jenkins.io/plugins/zdevops/1.0.0/zdevops.hpi?mirrorlist

<img width="1428" alt="Capture d’écran 2022-12-06 à 12 44 05" src="https://user-images.githubusercontent.com/1522731/205903009-86acf8c2-7e54-4f4e-a01b-e695a5c931d1.png">

- https://plugins.jenkins.io/zdevops is not picked (yet) by the plugin site

**Comment by dduportal** [comment]
Plugin site build manually triggered: the plugin is visible in https://plugins.jenkins.io/zdevops/.

Congratulations for the release, and thanks for the contribution!

I'm closing the issue, as it seem solved. Please do not hesitate to reopen if you need more details or still have an issue!

**Comment by IBA-mainframe-dev** [comment]
@dduportal @lemeurherve @NotMyFault , thank you so much for your help and advices!
I'll wait for the allotted time to check if everything turned out as planned (since the description from the [README.md](https://github.com/jenkinsci/zos-devops-plugin/blob/main/README.md) file has not yet been pulled up on the [plugin page](https://plugins.jenkins.io/zdevops/), I hope the plugin page will be displayed correctly after all the processes).
And once again, thanks a lot to all of you!

**Comment by basil** [comment]
+1 If you are using Gradle to do Jenkins plugin development, you are on your own. See https://github.com/jenkinsci/ivy-plugin/pull/49 for an example of how to switch to the supported Maven toolchain.

**Comment by NotMyFault** [comment]
> +1 If you are using Gradle to do Jenkins plugin development, you are on your own. See [jenkinsci/ivy-plugin#49](https://github.com/jenkinsci/ivy-plugin/pull/49) for an example of how to switch to the supported Maven toolchain.

Maybe we should officially deprecate the gradle toolchain, given it doesn't support major infra components and its plugin authors have made no attempt in years to support it 🤔
