### ISSUE TITLE
Spaces (or tabs?) are appent to a label, causing potential mismatch

### ISSUE THREAD

**Issue by AlterMellion** [jenkins-infra/helpdesk#3280]
### Service(s)

release.ci.jenkins.io

### Summary

Hi,

I'm using Jenkins Jenkins 2.380 to train myself, and currently I'm trying to use Cloud Agents.
When running a job, I have a message telling me this:
`(pending—All nodes of label ‘[DockerJenjinsAgent](http://localhost:8080/label/DockerJenkinsAgent)’ are offline)`
After the label, there are white spaces added, as we can see in the screen:
![PendingQueue](https://user-images.githubusercontent.com/115452735/205473840-124467ef-3d67-43c8-85fe-6b59b1f1225c.jpg)

And then the message becomes:
`(pending—There are no nodes with the label ‘[DockerJenkinsAgent](http://localhost:8080/label/DockerJenkinsAgent)’)`
![PendingQueue2](https://user-images.githubusercontent.com/115452735/205474015-cc27ccc0-a9eb-435f-8b3a-60b21e6c3b08.jpg)

As the label does exists, and without any space at the end, I was wondering if this is a bug and if it could explain why no agent is actually started.

### Reproduction steps

1. Create Cloud node that runs on Windows Docker
2. Give it a label
3. Use that label in a job, to restrict the usage
4. Trigger a new run and notice the issue

**Comment by AlterMellion** [comment]
I reinstall using Jenkins Jenkins 2.332.2 (it's the version used in the Tutorial I'm following), and doing the same actions work.
The label is also correct, now, without those extra blank space.

**Comment by lemeurherve** [comment]
This help desk is dedicated to [the Jenkins Infrastructure](https://www.jenkins.io/projects/infrastructure/), not Jenkins itself.

Please ask about this issue in the Jenkins community forum at https://community.jenkins.io/ or the Jenkins chat channels at https://gitter.im/jenkinsci/jenkins or the Jenkins user mailing list at https://groups.google.com/g/jenkinsci-users
