### ISSUE TITLE
Azure Windows 2019 VMs agent are failing when starting the agent process

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3283]
### Service(s)

ci.jenkins.io, trusted.ci.jenkins.io

### Summary

The agents of type "Azure Windows 2019 VM" are failing on ci.jenkins.io and trusted.ci.jenkins.io with the following error in jenkins logs:

```text
Dec 06, 2022 12:01:55 PM WARNING com.microsoft.azure.vmagent.AzureVMCloudVerificationTask verify
AzureVMCloudVerificationTask: verify: win-2019 could not be verified:
Error: Not a valid JVM Option. JVM options should start with a hyphen(-). e.g. -Xmx1500m
```

**Comment by dduportal** [comment]
Found the culprit in "Manage Jenkins" -> "Manage Node" -> "Configure Cloud" -> select the Azure VM template for Windows 2019 and click on the "Advanced" Button:

<img width="1501" alt="Capture d’écran 2022-12-06 à 15 06 40" src="https://user-images.githubusercontent.com/1522731/205933866-e9f35d09-7bc9-4130-89c5-d49340c4c350.png">

Removing the double quotes fixes the issues.

Cc @smerle33 it's an unexpected consequence of https://github.com/jenkins-infra/jenkins-infra/pull/2509.

We now have 2 cases to handle for Windows agents:

- Azure Container instances should have the quote around any JVM option (ref. #3274)
- Azure VM instances should NOT have the quote

**Comment by smerle33** [comment]
short term fix in place with https://github.com/jenkins-infra/jenkins-infra/pull/2521

**Comment by dduportal** [comment]
WiP long term fix in https://github.com/jenkins-infra/jenkins-infra/pull/2527

**Comment by dduportal** [comment]
Hotfi (I did a typo 😅): https://github.com/jenkins-infra/jenkins-infra/pull/2530

**Comment by dduportal** [comment]
Applied and verified on ci.jenkins.io
