### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by Puvijo3** [jenkins-infra/helpdesk#3285]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

kindly do help me to recovery my account

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @Puvijo3 , I'm closing the issue as there was no information provided: without knowing your username or email, we cannot find your account to reset the password.

Please note that this is only an account for the jenkins.io websites, not for Jenkins itself.
