### ISSUE TITLE
Planning for supported JDK versions in Jenkins Infrastructure

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3289]
### Service(s)

ci.jenkins.io

### Summary

as per this endoflife table https://endoflife.date/java, we (the infra team) propose to follow the same rule for the jdks within the agents. 
Meaning providing all LTS as long as they are existing and not EOL

- jdk8 until 31 Dec 2030
- jdk11 until 30 Sept 2026
- jdk17 until 30 sept 2029

and the latest : jdk19 for now until 21 Mars 2023 at that time we should have a jdk20

as there is no consensus (https://groups.google.com/g/jenkinsci-dev/c/YDs37rtfA1c) on a edge named version, we will use this end of life table as a table of truth if it's ok with you.

**Comment by dduportal** [comment]
Update:

- JDK19 installation was removed from the packer images (Linux VMs, Linux containers and Windows VMs) in https://github.com/jenkins-infra/packer-images/pull/835
- WiP: JDK19 is being removed from Windows container images in https://github.com/jenkins-infra/docker-inbound-agents/pull/125
- JDK support for the Jenkins project is being discussed in https://github.com/jenkinsci/jep/pull/400. Jenkins infra will follow the LTS support described in this JEP

TODO:
- Remove last references of JDK19

**Comment by dduportal** [comment]
Update:

- JDK19 removed from ci.jenkins.io (and all the Puppet code) in https://github.com/jenkins-infra/jenkins-infra/pull/3144
- No more remnants of JDK19 (except documentation and jenkins.io history) as per https://github.com/search?q=org%3Ajenkins-infra%20jdk19&type=code

TODO: 

- Update ci.jenkins.io documentation once https://github.com/jenkinsci/jep/pull/400 is agreed upon

**Comment by dduportal** [comment]
Closed by https://github.com/jenkins-infra/documentation/commit/cb7835ea8483bda4a7aa1f67c5d8c26f71682c1e
