### ISSUE TITLE
Netlify site for jenkins-io-components

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3296]
### Service(s)

Other

### Summary

Need a netlify site created for jenkins-io-components so we can get preview sites for PRs

### Reproduction steps

N/a

**Comment by halkeye** [comment]
https://app.netlify.com/sites/jenkins-io-components/overview has been setup, but needs the bot token on https://github.com/jenkins-infra/jenkins-io-components/settings/secrets/actions

For now i'm using my own token

**Comment by halkeye** [comment]
this has been done for a bit.

**Comment by lemeurherve** [comment]
@halkeye can you tell us what have been done?

**Comment by lemeurherve** [comment]
@halkeye can you tell us what have been done?

**Comment by lemeurherve** [comment]
Seeing [your new issue to replace GitHub Action by a Jenkinsfile](https://github.com/jenkins-infra/helpdesk/issues/3340) I suppose it doesn't matter anymore now.

**Comment by halkeye** [comment]
oh this ticket was for the token, yea i didn't actually do it, just used my own token, i thought it was for creating the site in the first place.

Yea, moving it is the right thing anyways.
