### ISSUE TITLE
CD failure on `scm-api-plugin`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3297]
### Service(s)

Artifactory, GitHub

### Summary

I am trying to release a bug fix in `scm-api-plugin` but `deploy` to Artifactory is consistently giving me a 401.

### Reproduction steps

https://github.com/jenkinsci/scm-api-plugin/actions/runs/3707571020/jobs/6284149792

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project scm-api: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:scm-api:pom:631.v9143df5b_e4a_a from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/scm-api/631.v9143df5b_e4a_a/scm-api-631.v9143df5b_e4a_a.pom, status: 401 Unauthorized -> [Help 1]
```

https://github.com/jenkinsci/scm-api-plugin/settings/secrets/actions does contain a `MAVEN_TOKEN` (5h old).

**Comment by daniel-beck** [comment]
Please try again, RPU failed earlier due to an HTTP 503 from GitHub, so the secret was outdated (it runs every 3 hours, and tokens are valid for 4).

**Comment by jglick** [comment]
I used **Re-run failed jobs**. Interestingly, this picked up the commit from the original run, even though trunk has since moved on. Good in a way, except that this confused Release Drafter, so I needed to manually fix up https://github.com/jenkinsci/scm-api-plugin/releases/tag/631.v9143df5b_e4a_a. Anyway yes, deployment is now fixed, thanks!
