### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by ShwetaMagar** [jenkins-infra/helpdesk#3300]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### jenkins.io account username

Shwetamagar12

### jenkins.io account email

shwetamagar1999@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by lemeurherve** [comment]
Hello @ShwetaMagar, there is no account registered with the usernam `Shwetamagar12` or this email.

You should be able to create one by signing up at https://accounts.jenkins.io/signup

Closing this issue, feel free to reopen it if you encounter any problem.
