### ISSUE TITLE
forgott username and password

### ISSUE THREAD

**Issue by Vrishabh55** [jenkins-infra/helpdesk#3301]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account email

vrish55@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @Vrishabh55 , there is no account with this email. It seems like you are trying to reset an account for a Jenkins instance? 
This issue tracker is only for the `jenkins.io` website accounts.
