### ISSUE TITLE
Install renovate on asciidoctor-jenkins-extensions

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3303]
### Service(s)

GitHub

### Summary

Hey,

I requested an installation of the mentioned repository, to keep gems up to date. A list of all repositories in this org renovate is currently installed on is listed here https://github.com/apps/renovate/installations/new -> jenkins-infra

Btw, would be nice to have issues enabled on https://github.com/jenkins-infra/asciidoctor-jenkins-extensions too.

cc @dduportal

**Comment by lemeurherve** [comment]
Issue created for the record, installation done, thanks @NotMyFault for taking care of this.

**Comment by NotMyFault** [comment]
Thanks!

Btw, would be nice to have issues enabled on https://github.com/jenkins-infra/asciidoctor-jenkins-extensions too.

**Comment by lemeurherve** [comment]
> Btw, would be nice to have issues enabled on [jenkins-infra/asciidoctor-jenkins-extensions](https://github.com/jenkins-infra/asciidoctor-jenkins-extensions) too.

Issues enabled.

**Comment by NotMyFault** [comment]
Same for https://github.com/jenkins-infra/awestruct-ibeams please 🙏🏻

**Comment by lemeurherve** [comment]
Approved 🙂

**Comment by lemeurherve** [comment]
Added to https://github.com/jenkins-infra/docker-plugin-site-issues too.
