### ISSUE TITLE
401 Unauthorized error while deploying a plugin

### ISSUE THREAD

**Issue by kalpshekhar** [jenkins-infra/helpdesk#3304]
### Service(s)

infra.ci.jenkins.io

### Summary

Hi,
I get the following error on executing mvn release:perform to deploy my plugin to the jFrog repository.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project deploy-integrationserver: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:deploy-integrationserver:pom:1.0 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/io/jenkins/plugins/deploy-integrationserver/1.0/deploy-integrationserver-1.0.pom, status: 401 Unauthorized -> [Help 1]

My settings.xml looks like
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">

	<servers>
		<server>
			<username>kalpshekhar</username>
			<password>*******I have got encrypted password here********</password>
			<id>central</id>
		</server>
		<server>
			<username>kalpshekhar</username>
			<password>*******I have got encrypted password here********</password>
			<id>snapshots</id>
		</server>
	</servers>

	<pluginGroups>
		<pluginGroup>org.jenkins-ci.tools</pluginGroup>
	</pluginGroups>

	<profiles>
		
		<profile>
			<id>jenkins</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<repository>
					<id>repo.jenkins-ci.org</id>
					<url>https://repo.jenkins-ci.org/public/</url>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<id>repo.jenkins-ci.org</id>
					<url>https://repo.jenkins-ci.org/public/</url>
				</pluginRepository>
			</pluginRepositories>
		</profile>
	</profiles>
	<mirrors>
		<mirror>
			<id>repo.jenkins-ci.org</id>
			<url>https://repo.jenkins-ci.org/public/</url>
			<mirrorOf>m.g.o-public</mirrorOf>
		</mirror>
	</mirrors>
</settings>

Thanks,
Kalpshekhar

**Comment by MarkEWaite** [comment]
Be sure that you have followed the exact steps as listed in ["Performing a Plugin Release Manually"](https://www.jenkins.io/doc/developer/publishing/releasing-manually/).  It is a common situation that a new plugin maintainer believes they have followed all the steps, but when they review the steps again, they detect one or more items that they had skipped.

**Comment by kalpshekhar** [comment]
@MarkEWaite thanks!
Adding following bit to my settings.xml solved it.
<server>
      <id>maven.jenkins-ci.org</id> 
      <username>your_user_name_here</username>
      <password>your_encrypted_password_here</password>
</server>
