### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by Susheel5445** [jenkins-infra/helpdesk#3308]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

not entering into jenkins

### jenkins.io account username

Tatuskar

### jenkins.io account email

tatuskarconstructions@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @Susheel5445 , the accounts.jenkins.io application is only for managing accounts on the https://jenkins.io website.

It looks like you are trying to recover an account from your Jenkins instance: please contact the administrators of this Jenkins instance.
