### ISSUE TITLE
[workflow-api-plugin] java.lang.RuntimeException: Unexpected exception while serving JSON

### ISSUE THREAD

**Issue by mrtaxi** [jenkins-infra/helpdesk#3310]
### Service(s)

plugins.jenkins.io

### Summary

exactly the same errors as in
[https://issues.jenkins.io/browse/JENKINS-38089](url)

Pipeline: API
Version1200.v8005c684b_a_c6
Jenkins 2.375.1

**Comment by lemeurherve** [comment]
This issue tracker is dedicated to Jenkins Infrastructure.

Please open an issue at the corresponding Jira tracker at https://issues.jenkins.io/ (select the "workflow-api-plugin" as Component), or (better IMO) post a comment on the existing Jira issue.

**Comment by mrtaxi** [comment]
thank you @lemeurherve
