### ISSUE TITLE
Unarchive unleash plugin long enough to deprecate it

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3311]
### GitHub repositories

https://github.com/jenkinsci/unleash-plugin needs to be unarchived long enough to set the 'deprecated' topic.  Once the 'deprecated' topic is set, it can be archived again.

### GitHub users to have permission

@MarkEWaite 

### Permission level

Admin

## Deprecate the unleash plugin

https://github.com/shillner/unleash-maven-plugin/ has been archived.  That is the unleash plugin for Apache Maven.  The Jenkins unleash maven plugin depends on the unleash plugin for Apache Maven.

https://github.com/jenkinsci/unleash-plugin has been archived.  That is the Jenkins unleash Maven plugin. The last release of the Jenkins unleash maven plugin was 3 years ago. Since the Jenkins plugin repository has been archived, we can expect no new releases of the plugin.

[JENKINS-70326](https://issues.jenkins.io/browse/JENKINS-70326) notes that the Jenkins unleash maven plugin does not work with Java 17.

Let's deprecate the Jenkins plugin so that it is clear to users that the Jenkins plugin is not being maintained and that the Apache Maven plugin is not being maintained.

https://www.jenkins.io/doc/developer/plugin-governance/deprecating-or-removing-plugin/ says that the preferred way to deprecate a plugin is to add the "deprecated" topic to the repository and to explain in the plugin documentation why it is being deprecated.  That would mean allowing writes to the repository again, just long enough to set the topic 'deprecated'.

https://github.com/jenkins-infra/repository-permissions-updater/pull/3042 is the request to remove all developers from the archived plugin repository.

https://github.com/jenkins-infra/plugins-wiki-docs/pull/6 is the documentation wiki pull request to deprecate the plugin.

https://github.com/jenkins-infra/update-center2/pull/668 is the recommendation from Daniel Beck to set the topic rather than use the alternative method (that is not recommended).

**Comment by NotMyFault** [comment]
I added you to the repository team, you should now be able to unarchive the repository.

**Comment by MarkEWaite** [comment]
Completed.  Thanks!
