### ISSUE TITLE
Received password reset that I didn't initiate, subsequest password reset attempts failing

### ISSUE THREAD

**Issue by Dispader** [jenkins-infra/helpdesk#3312]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I received a disturbing message this morning from admin@jenkins-ci.org to jake@umn.edu.

The message was a password reset, which I didn't initiate.

I tried to change the password myself with the "Forgot password" feature, but attempts to use newly sent temporary passwords are failing.

### jenkins.io account username

jake@umn.edu

### jenkins.io account email

jake@umn.edu

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Sorry to hear that someone else requested a password reset on your account.  That's one of the risks of having a password reset system.

Was the failed login attempt to https://accounts.jenkins.io , https://issues.jenkins.io , https://ci.jenkins.io , or https://repo.jenkins-ci.org ?  Those are the most frequently used locations for a jenkins.io account.

Would you like us to reset the password again and send the password reset email to jake@umn.edu ?

**Comment by Dispader** [comment]
Hey @MarkEWaite .  Thanks for the quick response!

The email mentioned https://accounts.jenkins.io/, and that's the address I used to make the subsequent reset attempts.

**Comment by MarkEWaite** [comment]
> Would you like us to reset the password again and send the password reset email to [jake@umn.edu](mailto:jake@umn.edu) ?

I can perform a password reset and then can confirm that the new password is working before I send it to [jake@umn.edu](mailto:jake@umn.edu).  That should then allow you to login to https://accounts.jenkins.io and configure a new password.  Does that work for you?

**Comment by dduportal** [comment]
Hi @Dispader , I'm currently resting your password through the administration system trying to verify if it works (we have an "impersonation" feature).

I'll then confirm if your account is reachable (e.g. if I can login) or not.
That will generate emails from admin -at- jenkins-ci.org that cna be safely ignored until my next comment in this issue.

**Comment by dduportal** [comment]
Hi @Dispader , I confirm that your account is unlocked.

I've reset your password one last time at 07:36 UTC: the last email you've received from admin -at- jenkins-ci.org is the correct one. Let us know if it is ok.

Please take care of disabling any password manager until you've changed your password yourself: I see in the applicatoon logs failed logging attempts with your account: it means that the typed password is not the correct one.

**Comment by MarkEWaite** [comment]
Closing after 2 weeks without a response
