### ISSUE TITLE
Sign Up link on https://issues.jenkins.io/ is not clickable. User has to type it again on new tab

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3313]
### Service(s)

Jira

### Summary

Hit https://issues.jenkins.io/ is not clickable.

Try to hit or copy https://accounts.jenkins.io/

User is not able to copy or hit link. 

![image](https://user-images.githubusercontent.com/21194782/209947307-f0d7b735-ce04-4668-aeb0-3d323d7e8ec8.png)

Refiled from https://issues.jenkins.io/browse/JENKINS-70337

**Comment by timja** [comment]
for some reason when I set this up originally I thought we could only use CSS but we can use JavaScript.

I followed this guide: https://mraddon.blog/2016/02/01/how-to-put-additional-info-in-the-jira-login-page/

and I've used this JavaScript to implement it:

```javascript
function updateHintText() {
  const pathname = window.location.pathname;

  const signupMessage = `<a href="https://accounts.jenkins.io/signup">Sign up</a>`;

  if (pathname === "/login.jsp") {
    document.getElementById('sign-up-hint').innerHTML = signupMessage
  }

  if (pathname === "/secure/Dashboard.jspa") {
    document.getElementById('publicmodeoffmsg').innerHTML = signupMessage
  }
}

setTimeout(function () {
  updateHintText();
}, 1);
```

System Dashboard:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/21194782/209947499-a7bf822a-9684-457a-a7d2-56ed432c9d53.png">

Login page:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/21194782/209947524-d7f5734c-74ce-4dc6-95c9-747a4254e9a1.png">

**Comment by MarkEWaite** [comment]
I see a different result when I open issues.jenkins.io without authenticating:

![issues-jenkins-io-not-a-member](https://user-images.githubusercontent.com/156685/209975939-28f9b9a6-eafe-4494-8bca-a039b02460a8.png)

**Comment by timja** [comment]
Any errors in your browser console? I just checked on my phone and it looks fine

**Comment by timja** [comment]
I can reproduce in Firefox, there's a console error:

> Uncaught TypeError: document.getElementById(...) is null

**Comment by timja** [comment]
All sorted now I added in a retry with more delay. I didn't increase the initial delay as that left a pretty big flash as the text was replaced.

Tested in:

- Safari
- Firefox
- Chrome

```javascript
function updateHintText() {
  const pathname = window.location.pathname;

  const signupMessage = `<a href="https://accounts.jenkins.io/signup">Sign up</a>`;

  function updateElement(elementId) {
    let text = document.getElementById(elementId)
    if (!text) {
      setTimeout(function () {
        text = document.getElementById(elementId)
        text.innerHTML = signupMessage
      }, 50)
    } else {
      text.innerHTML = signupMessage
    }
  }

  if (pathname === "/login.jsp") {
    updateElement('sign-up-hint');
  }

  if (pathname === "/secure/Dashboard.jspa") {
    updateElement('publicmodeoffmsg')
  }
}

setTimeout(function () {
  updateHintText();
}, 1);
```
