### ISSUE TITLE
Delete my account in accounts.jenkins.io

### ISSUE THREAD

**Issue by sebkraemer** [jenkins-infra/helpdesk#3314]
### Type(s) of account issue

I want my account to be deleted

### Summary

Hi, please delete my account `seb_kraemer`.

Thank you for your work on jenkins.

### jenkins.io account username

seb_kraemer

### jenkins.io account email

sebkraemer@posteo.org

### Which URL are you trying to login at?

https://accounts.jenkins.io

**Comment by MarkEWaite** [comment]
The account email listed in the issue is correct.  I sent a confirmation email to that account to assure that the user has control of that email address.

**Comment by MarkEWaite** [comment]
Account deleted after receiving reply to confirmation email.
