### ISSUE TITLE
recuperar contraseña

### ISSUE THREAD

**Issue by FYanTsoft** [jenkins-infra/helpdesk#3316]
### Type(s) of account issue

I didn't receive any email, I've been blocked by the anti-spam system

### Summary

usuario nuevo necesito logearme en jenkins para poder utilizarlo necesito aprender.5

### jenkins.io account email

fabian.yanez@tsoftglobal.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by smerle33** [comment]
Hello @FYanTsoft , there is no account registered with this email : [fabian.yanez@tsoftglobal.com]

You should be able to create one by signing up at https://accounts.jenkins.io/signup but be sure that you mean to use ci.jenkins.io jenkins controller, that is used by jenkins core/plugins developpers and not a controller from your own company.

Closing this issue, feel free to reopen it if you encounter any problem.

**Comment by MarkEWaite** [comment]
@smerle33 I see the account `fabianarturo` registered with that email address when I search accounts.jenkins.io.  I've sent an email message to that address asking the owner of the email address to confirm that they want the password reset.

**Comment by smerle33** [comment]
@Mark Waite ***@***.***> can we plan a visio to check what I did
wrong ?

**Comment by FYanTsoft** [comment]
estimados, se registró mi cuenta correctamente, gracias por la gestión.

**Comment by MarkEWaite** [comment]
> estimados, se registró mi cuenta correctamente, gracias por la gestión.

Unfortunately, you have not replied to my email that was sent to your account trying to confirm that you have control of that account.  Before we reset a password, we like to confirm that the individual requesting the reset has access to the email account that will receive the password reset.

**Comment by lemeurherve** [comment]
Hello @FYanTsoft, can you reply to the email sent by Mark? Without any response we'll have to close this issue otherwise.

**Comment by dduportal** [comment]
As discussed during weekly team meeting, closing as no answer from the user.

Feel free to reopen by answering to the aformentionned email.
