### ISSUE TITLE
Exclude non-numeric plugin versions from Update Center

### ISSUE THREAD

**Issue by zbynek** [jenkins-infra/helpdesk#3317]
### Service(s)

Update center

### Summary

The update center publishes some very non-semantic plugin versions:

```
alibabacloud-ecs@alibabacloud-ecs-1.11
alibabacloud-ecs@y
buildrotator@y
categorized-view@y
cctray-xml@-rc26.47a8c6264c6d
confluence-publisher@-rc125.6ba78c5ed4a2
discord-notifier@v1.4.8
durable-task@-rc492.27169c99ee95
jabber@unspecified
jobcacher@-rc197.ca_db_107d3a_13
jobcacher@-rc198.8b_b_34da_c7403
jucies@unspecified
junit-realtime-test-reporter@y
logstash@-rc203.c5e91b42cf67
openshift-sync@y
prometheus@Bn
relution-publisher@true
requests@requests-2.0.1
requests@requests-2.1.0
requests@requests-2.2
simpleclearcase@pppppppppppppppppppp
upload-build-to-sofy@-rc31.651ac4e06d9e
upload-build-to-sofy@-rc32.ca9d99f51810
usemango-runner@y
```
These are not sorted properly on the plugin site because the version comparison is done by JS and does not 100% follow the Maven algorithm. Maybe instead of fixing that on the plugin site these should be simply not published by the UC.

### Reproduction steps

Go to https://plugins.jenkins.io/requests/#releases -- the non-semantic versions should be at the bottom, like in https://updates.jenkins.io/download/plugins/requests/

To list all problematic versions you can go to
https://updates.jenkins.io/current/plugin-versions.json
and run this in console:

```
console.log([].concat(...Object.values(JSON.parse(document.body.innerText).plugins).map(x=>Object.values(x).filter(v=>!v.version.match(/^[0-9]+([-.].*)?$/)).map(v=>`${v.name}@${v.version}`)).filter(x=>x.length)).join("\n"));
```

**Comment by MarkEWaite** [comment]
@daniel-beck and @halkeye, do you have a preference for how this should be handled?

Rejecting incorrect version strings in update center seems consistent with its ability to suspend distribution of plugins, though deciding what is an incorrect version string may be more complicated than we want to include in the update center generator.

**Comment by daniel-beck** [comment]
> do you have a preference for how this should be handled?

No preference, but note that "non-numeric" isn't the problem _exactly_. Lots of versions aren't (fully) numeric, including all of https://www.jenkins.io/doc/developer/publishing/releasing-experimental-updates/ as well as all JEP-229 CD versions with non-numeric suffix.

```
$ curl --silent https://updates.jenkins.io/current/update-center.actual.json | jq --raw-output '.plugins[].version' | grep -E '[^0-9.-]+' | wc -l
     297
```

(Granted, excluding the usual JEP-229 convention leaves only ~15, of which ~8 are JEP-229(ish) or JEP-305, i.e., likely badly set up JEP-229.)

> Maven algorithm

FWIW it's likely actually https://github.com/jenkinsci/lib-version-number/

**Comment by zbynek** [comment]
>  Lots of versions aren't (fully) numeric

that's fine, my suggestion was just to remove plugin versions where the *major* version is not numeric. I believe that would not affect the latest version of any released plugin (full list of affected versions in issue description).

**Comment by daniel-beck** [comment]
A rule like "version needs to start with a digit" should be straightforward to implement (and document).
