### ISSUE TITLE
Jenkins Webhook auto-trigger issue

### ISSUE THREAD

**Issue by ashok-bezawada** [jenkins-infra/helpdesk#3319]
### Service(s)

ci.jenkins.io

### Summary

I am using Bitbucket as my version control tool. I am frequently facing issues with jenkins auto-triggering my job whenever any changes are done to my code. It is taking more than 30 minutes to trigger a job whenever webhook triggers. I had checked from Bitbucket end and found no issue from their end.
Please help with this issue. It is impacting my work a lot. Also there is nothing that i can do except to wait until jenkins triggers new build.
Thanks

**Comment by MarkEWaite** [comment]
This issue tracker is used to track issues with the Jenkins infrastructure.  Your request seems to be a request for help, not a report of a documentation issue or improvement.

Please use the [community forum](https://community.jenkins.io/c/using-jenkins/support/8), [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
