### ISSUE TITLE
Blocked from creating a new account in the anti-spam system

### ISSUE THREAD

**Issue by cromination** [jenkins-infra/helpdesk#3320]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I tried to sign up with the information below to report a bug and the system triggred a spam report

### jenkins.io account username

tbarnes

### jenkins.io account email

tbarnes@bostondigital.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by MarkEWaite** [comment]
There is no account registered for a user `tbarnes` or an email address tbarnes@bostondigital.com.  Try to register again through the ["Sign up" link](https://accounts.jenkins.io/signup) provided at https://issues.jenkins.io

**Comment by cromination** [comment]
Hello, I just tried again and got this:
![image](https://user-images.githubusercontent.com/7293503/210597415-14585dbf-fe6b-45f8-8938-1df4c6fb2acc.png)

**Comment by dduportal** [comment]
Hi @cromination , I wasn't able to reproduce the issue. Your account was created as `tbarnes` and your password was sent to the email you mentionned in this issue.

Can you try to log-in (and eventually change your password) on accounts.jenkins.io please?

I'm closing the issue as no further action is required by the Jenkins infrastructure team. Feel free to reopen if you have another problem.
