### ISSUE TITLE
renew the signer certificate for jenkins

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3323]
### Service(s)

Release certificates

### Summary

Has seen in the weekly build last week : "The signer certificate will expire on 2023-03-30." (code signing certificate)
we need to make sure to renew this.

https://release.ci.jenkins.io/job/core/job/release/job/master/190/consoleFull

**Comment by dduportal** [comment]
@MarkEWaite and I are going to pair on this one. We might need @olblak 's knowledge.

**Comment by olblak** [comment]
> @MarkEWaite and I are going to pair on this one. We might need @olblak 's knowledge.

Feel free to ping

**Comment by dduportal** [comment]
- Added 2 events with reminders in the jenkins-infra-team Google calendar
  - The day of expiration with reminder 4, 3 and 1 weeks before (limit of max 4 weeks before)
  - The 20 of January 2026, 4 months before the expiration, middle of the week
- Both releases went well
- Opened https://github.com/jenkins-infra/release/issues/362 for the password
- Post-mortem will happen in the Jenkins Board session the 10 of April: I'll let @MarkEWaite or myself commenting here any additional elements
- #3361 for the documentation update
