### ISSUE TITLE
accounts.jenkins.io admin access for smerle

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3324]
### Service(s)

Accounts

### Summary

As seen with @MarkEWaite, sometimes the keycloak administration pages don't show entries that can be seen on accounts.jenkins.io, I (@smerle33) would need an access to accounts to make sure that I can deal with helpdesk issues on account access.

https://github.com/jenkins-infra/helpdesk/issues/3316#issuecomment-1370624693
but now f...y....@ts....com is visible within keycloak ... it was not as the time.

**Comment by MarkEWaite** [comment]
+1 from me as well

**Comment by dduportal** [comment]
It's been done: @smerle33 is now admin (triggered by https://github.com/jenkins-infra/helpdesk/issues/4264)
