### ISSUE TITLE
Duplicate profile

### ISSUE THREAD

**Issue by ibidani** [jenkins-infra/helpdesk#3327]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

email: iplaman@gmail.com
Original username: iplaman
New username: idan
Hi,
When trying to login to https://issues.jenkins.io/ using my email and old account name "iplaman" I got error that password incorrect. I tried to use "Forgot my Password" but never received an email.
I thought my old profile got deleted so I created a new account with the same email.
Seems like the old profile still exists in Jira and I'd rather keep it if possible, both using the same email
Anyway to merge them? I don't mind to which username but would like to keep the history of the original account "iplaman"

Thanks,
Idan
https://issues.jenkins.io/secure/ViewProfile.jspa?name=iplaman
https://issues.jenkins.io/secure/ViewProfile.jspa?name=idan

### jenkins.io account username

iplaman

### jenkins.io account email

iplaman@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
The account `iplaman` has an invalid email address.  A password reset email will never reach you from that account because the email address value lacks a domain name.

I've sent a confirmation email and copied other members of the infra team.

**Comment by lemeurherve** [comment]
Issue resolved, last response to the confirmation email:

> Thank you for the quick fix, I logged in successfully.
> 
> Thanks and have a great day

**Comment by dduportal** [comment]
One last step: delete the older profile as discussed in infra weekly meeting

**Comment by MarkEWaite** [comment]
Previous account `idan` has been deleted.  Thanks!
