### ISSUE TITLE
HSTS blocks use of trusted.ci and cert.ci

### ISSUE THREAD

**Issue by yaroslavafenkin** [jenkins-infra/helpdesk#3328]
### Service(s)

cert.ci.jenkins.io

### Summary

I'm getting TLS certificate errors when trying to access CERT CI instance. Previously there used to be an option to proceed anyway AFAIR, now it's not there.

Last line says:
```
You cannot visit cert.ci.jenkins.io right now because the website uses HSTS. 
Network errors and attacks are usually temporary, so this page will probably work later.
```

### Reproduction steps

1. Connect to jenkins-infra VPN
2. Navigate to cert.ci.jenkins.io

**Comment by daniel-beck** [comment]
Same with trusted.ci on Chrome.

Don't know whether existing certificate exceptions are honored in Firefox or whether it's Chrome specific.

Proposed solution: Don't set the subdomain flag.

**Comment by timja** [comment]
I think it'll be from hitting the jenkins.io base domain which redirects to www.jenkins.io.

There's also:
https://github.com/jenkins-infra/helpdesk/issues/3091

**Comment by dduportal** [comment]
+1 with @timja : rolling back the HSTS setting would be painful, while we (infra team) can fix the root problem by providing a real life valid certificate to both controllers.

I do not have Chrome, but I confirm that I do not have the issue on my Firefox (if it helps on short term?)

**Comment by dduportal** [comment]
> > rolling back the HSTS setting would be painful
> 
> Does this include just not including subdomains?

I'm not sure to be honest. We need to check how much time it takes to the change to propagate (I remember HSTS settings having a loooong TTL making it not useful)

**Comment by dduportal** [comment]
@lemeurherve @smerle33 on short term, while checking HSTS settings, I'm going to generate manually an initial LE certificate and install it on the machines to unblock the JenSec team.

Renewal automation will come after once they're not blocked anymore

**Comment by daniel-beck** [comment]
> how much time it takes to the change to propagate

If this is a good solution that should not be a blocker IMO (assuming there's workarounds like clearing browser cache), given there's just a few people affected (only trusted.ci / cert.ci users).

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/2572 show the "short term but persistent" change I've applied to configure Apache to use manually-generated LE certificates for both server using DNS challenge.

@yaroslavafenkin @daniel-beck is it working for you now with Chrome? 

for the infra-team: we now have to configure renewal for both machines (e.g. setting up Azure API credential limited to the DNS zone, and set up the puppet letsencrypt module to automatically renew using Azure DNS and these credentials)

**Comment by dduportal** [comment]
Closing this issue as the Jenkins Security team confirmed they are unblocked.

Next steps:

- Automate LE certificate for trusted.ci.jenkins.io (outside of Azure) tracked in #3091
- Automate LE certificate for cert.ci.jenkins.io (inside Azure) tracked in #3337
