### ISSUE TITLE
Maven 3.8.7

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3333]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

Maven 3.8.7 is [available](https://maven.apache.org/docs/3.8.7/release-notes.html).

This issue tracks the coordinated deployment:

- Merge automated PRs to bump the version on:
  - Agent VM templates + Linux Container templates
  - Windows Container templates
  - Jenkins tools setup
- Release and deploy new images
- Communicate to developer on the mailing list

**Comment by smerle33** [comment]
email sent : https://groups.google.com/g/jenkinsci-dev/c/2dcjrIOUIcY
