### ISSUE TITLE
while sign up error

### ISSUE THREAD

**Issue by teja56789** [jenkins-infra/helpdesk#3335]
### Type(s) of account issue

I didn't receive any email, I've been blocked by the anti-spam system

### Summary

while signup error

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @teja56789 , if you do not specify a username or an email, then we won't be able to help you.

**Comment by lemeurherve** [comment]
No response in 5 days, closing this issue.

Feel free to reopen it with your username and/or email.
