### ISSUE TITLE
Can't access my account

### ISSUE THREAD

**Issue by YaelZav** [jenkins-infra/helpdesk#3339]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

Hello,
I can't access my account: when I click "forgot passord?" I don't receive any email.
My email is: yael260z@gmail.com. The name is Yael Zavedivker

### jenkins.io account email

yael260z@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset
https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Hi @YaelZav , please note that accouts.jenkins.io is only for account associated to the Jenkins.io websites (issues.jenkins.io, ci.jenkins.io, etc.).

It looks like you do not have any account on this system, which explain the behavior.

I'm closing the issue as no action is expected from the Jenkins infrastructure team: feel free to create an account here if you need it, or to reopen the issue with a proof that you had an account.
