### ISSUE TITLE
Add `jenkins-infra/jenkins-io-components` to ci.jenkins.io and infra.ci.jenkins.io

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3340]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io

### Summary

Github actions was nice when I was POCing, but I find them frustrating to debug, and hard on contributors.

I have a working Jenkinsfile now - https://github.com/jenkins-infra/jenkins-io-components/pull/55 - which should allow for jenkins to test and deploy.

**Comment by lemeurherve** [comment]
GitHub app created with [the semantic-release requirements](https://github.com/semantic-release/github#github-authentication):

<img width="576" alt="image" src="https://user-images.githubusercontent.com/91831478/212730866-9483ddcc-8c5a-4ad1-b2df-17e1c73cb818.png">

**Comment by lemeurherve** [comment]
As the jobs are created and running on ci.jenkins.io and infra.ci.jenkins.io, I'm closing this issue.
