### ISSUE TITLE
source index.html for get.jenkins.io

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3341]
### Service(s)

get.jenkins.io

### Summary

As per the comment on https://github.com/jenkins-infra/jenkins.io/pull/5668#issuecomment-1372084748 its requested to add the header and footer web components to get.jenkins.io

I did some digging into github and can't find index.html source anywhere.

the source on the file says its generated by puppet by doing `    erb < index.erb > index.html`

When i logged into the mirrorbits pod, I did find the file and the erb, which makes me think its only on azurefile, which isn't great.

I don't mind doing upgrades, but need to know where/how/etc

**Comment by NotMyFault** [comment]
The pages get.jenkins.io links to, are generated based on https://github.com/jenkinsci/packaging/tree/master/templates

Maybe we can move, wherever index.html is coming from currently, to packaging 🤔
