### ISSUE TITLE
Archive "foofoo" Jira component

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3344]
### Service(s)

Jira

### Summary

Hey,

Can we archive the `foofoo-plugin` component on Jira, please? The repository it belongs to is long archived: https://github.com/jenkinsci/foofoo

Thanks!

**Comment by dduportal** [comment]
<img width="1624" alt="Capture d’écran 2023-01-17 à 09 39 59" src="https://user-images.githubusercontent.com/1522731/212849566-b61b66ac-ac94-4dde-97eb-313369a2614d.png">

Component archived ✅
