### ISSUE TITLE
Archive lightstep-incident-response-plugin Jira component

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3346]
### Service(s)

Jira

### Summary

The repository has been archived, because the service shut down: https://github.com/jenkinsci/lightstep-incident-response-plugin

Towards https://github.com/jenkins-infra/repository-permissions-updater/issues/3022

**Comment by NotMyFault** [comment]
Hm, looks like I need to choose a more creative issue title next time to confuse the action 🤔

**Comment by dduportal** [comment]
<img width="1601" alt="Capture d’écran 2023-01-18 à 13 47 06" src="https://user-images.githubusercontent.com/1522731/213175286-4ea06bcc-f821-4b29-9eea-0ea93c485204.png">

Done 👍
