### ISSUE TITLE
Grant markewaite access to new vpn.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3347]
### Service(s)

VPN

### Summary

@MarkEWaite sometimes needs to help with infrastructure issues that may require access to infra.ci.jenkins.io.  The [change to a new cluster](https://groups.google.com/g/jenkins-infra/c/xdbfsBRCexE/m/w8f8gzFGCQAJ) needs a new virtual private network for that access.

### Pull request

Pull request to add certificate with open question about impact on existing VPN access for trusted.ci.jenkins.io.

* https://github.com/jenkins-infra/docker-openvpn/pull/236

**Comment by dduportal** [comment]
That should already be the case:
- https://github.com/jenkins-infra/docker-openvpn/pull/235 added you to the VPN image
- Released as https://github.com/jenkins-infra/docker-openvpn/releases/tag/1.2.0
- Deployed by https://github.com/jenkins-infra/jenkins-infra/pull/2598

=> you have to add a new OpenVPN client configuration as per https://groups.google.com/g/jenkins-infra/c/xdbfsBRCexE/m/w8f8gzFGCQAJ (should be a copy of the current one, except for the server URL that should be `private.vpn.jenkins.io`)

**Comment by dduportal** [comment]
Confirmed with @MarkEWaite in a private channel that it works for him. Closing.
