### ISSUE TITLE
jenkins Artifactory (https://repo.jenkins-ci.org/ui/) not accessible.

### ISSUE THREAD

**Issue by sumoanema** [jenkins-infra/helpdesk#3348]
### Service(s)

Artifactory

### Summary

 I have some changes which I have merged in [this](https://github.com/jenkinsci/sumologic-publisher-plugin/pull/21) PR. I want to publish these changes in jenkins artifactory.
As part of the changes done in this PR : https://github.com/jenkins-infra/repository-permissions-updater/pull/1209/files I see that there are three artifactory users which are eligible to upload the plugin to artifactory.

Users : "devennorton", "sour0205" have left our org.
User: "SumoApps" is a user which I wanted to use. But the credential I have are not working and when trying to recover the account by using forget password we keep getting this error which says : "The specified user is not permitted to reset his password."

Could you please let me know what could be done here to move forward.

**Comment by dduportal** [comment]
Hi @sumoanema , in order to recover your account credential, you have to use the centralized Jenkins system at accounts.jenkins.io (Artifactory does not manage the accounts itself).

Let us know

**Comment by sumoanema** [comment]
Thanks a lot @dduportal . I was able to recover the account.
Closing the issue.
