### ISSUE TITLE
Release of `jenkinsci/jenkins-test-harness-htmlunit` failing with 401 Unauthorized

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3349]
### Service(s)

Artifactory, GitHub

### Summary

[This release of `jenkinsci/jenkins-test-harness-htmlunit`](https://github.com/jenkinsci/jenkins-test-harness-htmlunit/actions/runs/3972062817/jobs/6809596015) failed with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project jenkins-test-harness-htmlunit: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.main:jenkins-test-harness-htmlunit:pom:132.v6a_b_911b_57286 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-test-harness-htmlunit/132.v6a_b_911b_57286/jenkins-test-harness-htmlunit-132.v6a_b_911b_57286.pom, status: 401 Unauthorized -> [Help 1]
```

I read [the documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#the-upload-to-the-maven-repository-fails-with-401-unauthorized):

> Unauthorized means that the credentials were invalid, or not sent by Maven. This normally means that the secrets configured in the repository have expired, create an issue in the INFRA helpdesk on [GitHub](https://github.com/jenkins-infra/helpdesk/issues/new/choose) […].

Per the documentation, I am creating an infrastructure ticket to update the expired credentials.

### Reproduction steps

Obtain write access to `jenkinsci/jenkins-test-harness-htmlunit`, then go to https://github.com/jenkinsci/jenkins-test-harness-htmlunit/actions/workflows/cd.yaml and click the "Run workflow" button.

**Comment by basil** [comment]
No response from the infrastructure team.

**Comment by dduportal** [comment]
We have not been able to process this issue. Is there any objection to reopen it  if the issue is still present?

**Comment by basil** [comment]
This issue is no longer present.
