### ISSUE TITLE
Request Jenkins Infra VPN Access for alecharp

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3352]
I would like to get access to the infra VPN so I could reach the database of the Plugin Health Project and try to debug issues with the application more easily.

**Comment by dduportal** [comment]
Work for the infra-team:

- [x] PR https://github.com/jenkins-infra/docker-openvpn/pull/237 signed, approved, merged
- [ ] New release of the Docker OpenVPN image (insert release link here)
- [ ] Deployment of the new release (insert PR link here)

**Comment by lemeurherve** [comment]
Access to the VPN confirmed, closing this issue.
