### ISSUE TITLE
IRC bot jenkins-admin is offline

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3354]
### Service(s)

IRC

### Summary

At least, I presume the bot is offline, likely because of the ongoing publick8s -> privatek8s migration?
The bot disconnected yesterday from the channels it's supposed to be in.

**Comment by dduportal** [comment]
New version deployed with: https://github.com/jenkins-infra/kubernetes-management/pull/3498 should be back in a few minutes (or we'll have interesting logs)

**Comment by lemeurherve** [comment]
Seems to be good now:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/91831478/214554154-b949f880-551f-4800-a5f5-12b2d3ea47e2.png">

Can you confirm it's OK for you @NotMyFault ?

**Comment by NotMyFault** [comment]
Back and running, thanks!
