### ISSUE TITLE
SQL queries to run on Plugin Health Scoring database

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3356]
While investigating https://github.com/jenkins-infra/plugin-health-scoring/issues/175, I might have found the culprit. 

However, in order to get out of the current situation, we might still need to clear the table of scores and reset the sequence for its id generation. 

To do so, could you please run the following SQL commands on the database of the projects?

```sql
DELETE FROM scores;
ALTER SEQUENCE "scores_seq" RESTART;
```

Thanks in advance.

**Comment by lemeurherve** [comment]
Done.
