### ISSUE TITLE
Remove Deprecated plugin "Handlebars" from our instances

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3357]
### Service(s)

ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, cert.ci.jenkins.io

### Summary

<img width="866" alt="Capture d’écran 2023-01-24 à 22 07 10" src="https://user-images.githubusercontent.com/1522731/215021377-22432535-7356-4746-b680-551fff633129.png">

We want to remove this plugins from our controllers

- [x] ci.jenkins.io (manually managed plugins: remove from UI and restart)
- [x] trusted.ci.jenkins.io (manually managed plugins: remove from UI and restart)
~- [] cert.ci.jenkins.io (manually managed plugins: remove from UI and restart)~
- [x] release.ci.jenkins.io (Remove from Docker image + remove from UI once deployed)
~- [ ] infra.ci.jenkins.io (not installed in docker-jenkins-weekly image)~
~- [ ] weekly.ci.jenkins.io (not installed in docker-jenkins-weekly image)~

**Comment by MarkEWaite** [comment]
Nice to have this excuse to test drive the plugin removal instructions proposed at 

* https://github.com/jenkinsci/docker/pull/1538

I believe that the multi-step process described by @dduportal is the most reliable, but I'd love to have a one step process that did it.  The process is:

* Remove plugin from the container definition and create a new container definition
* Stop the old container
* Start the new container
* Remove the plugin(s) using the "Manage Jenkins" page
* Complete the plugin removal by restarting the controller

**Comment by dduportal** [comment]
I forgot to close the issue but it's done everywhere \o/
