### ISSUE TITLE
Frequent PagerDuty Alerts `Disk space is below 1GB free win-xxx-yyyyyy`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3359]
### Service(s)

Other

### Summary

We receieves, since beginning of January (as far I can tell) PgaerDuty alerts about "Disk space is below 1GB free win-xxx-yyyyyy".

These alerts are triggered by the following Daatdog monitor on our system: https://github.com/jenkins-infra/datadog/blob/main/datadog-monitors.tf#L22-L42 .

There is no platform incident (so we should not receive PagerDuty) but the problem need to be assessed (and solved).

@lemeurherve @smerle33 and I discussed the different elements:

- The VMs which name follows the pattern `win-xxx-yyyyyy` are Azure Windows VM (2019 or 2022) managed Jenkins controllers with the [Azure VM](https://plugins.jenkins.io/azure-vm-agents/): either ci.jenkins.io, trusted.ci.jenkins.io or cert.ci.jenkins.io
  - These VMs are ephemeral, and created / deleted by Jenkins itself

- We could update the Datadog Monitor to exclude the hostname starting with `win-` to stop sending PagerDuty alerts 
  - As pointed by our discussion, doing this "quick fix" would hide the back problem, or we could split in 2 Datadog monitors: one "critical" sending pager duty alerts (with `win-*` hosts excluded) and a second one for "warnings" (that we should check some time to time).

- Root problem : we have to check if these machines are failing builds on the controller (due to missing disk space).

- First step: check the status of "agent reuse": the Windows VM agents are kept up to be reused until a certain point (amount of builds and/or timeout). 
  - The reasons of not setting these machines as ephemeral are mainly historical:
    - Stability of the builds (2020 and 2021 were rough for build stability. So we reused machines as much as posible with the law "if a build suceeded on it, chances are high that a second one would).
    - Naive cost reduction tentative: since a Winbdows VM is billed per hour (and nor per minute as the Linux VMs), then it made sense to let an Azure Windows VM up around 30 min max after the first build (since average builds were ~15 min).
    - Build performances: allocation of a Windows VM took around 10 min. it's now around 2-3 min usually.
  - The proposal is to switch to fully ephemeral agents. It would ensure that no build can accidentally gets content from a previous unrelated one AND would ensure that we know how much disk space a single build would use on these agents.

- Second step, once first step is done: locate build(s) using the machines mentionned in the alerts to check if it failed or not due to missing space.
  - If it does, then we should increase disk to fulfill the need.

**Comment by dduportal** [comment]
Update: 

- The alerts are only triggered by Azure VMs, which are Windows agents  on each case.
- All the VM agents on ci.jenkins.io are already ephemeral.
- The error is triggered when the `docker-inbound-agent` image is built on ci.jenkins.io for the following error used for diagnostic:
  - `
Disk space is below 1GB free win-201-05fb80
` on PagerDuty: (https://jenkins.pagerduty.com/incidents/Q1OQ51G4PETLB8)
  - Monitor on datadog (see screenshot below) https://jenkins.datadoghq.com/monitors/7375817?q=device%3Ac%3A%2Chost%3Awin-201-05fb80&from_ts=1676267297000&to_ts=1676268497000&eval_ts=1676268497000&live=15min 

<img width="1854" alt="Capture d’écran 2023-02-14 à 08 42 54" src="https://user-images.githubusercontent.com/1522731/218671223-c7926b8a-b784-4efa-9a19-e05a7f32ccf1.png">

  - Job associated (kept forever for deubgging purpose until the issue is closed): https://ci.jenkins.io/job/Packaging/job/docker-inbound-agents/job/master/250/consoleFull with the error `failed to register layer: re-exec error: exit status 1: output: write \\?\C:\ProgramData\docker\tmp\hcs536067995\Files\Program Files\PowerShell\clrjit.dll: There is not enough space on the disk.` when pulling base images

**Comment by dduportal** [comment]
Work in progress: 
- Increase the disk size from 128 Gb (current) to 150 Gb
- Switching VM disk to SSD as part of https://github.com/jenkins-infra/helpdesk/issues/3117

**Comment by dduportal** [comment]
Should be fixed by https://github.com/jenkins-infra/jenkins-infra/pull/2635

**Comment by dduportal** [comment]
No more issue despite the numerous builds: closing 🥳

**Comment by lemeurherve** [comment]
We still have frequent alerts about these VMS, reopening.

**Comment by lemeurherve** [comment]
No more issue since https://github.com/jenkins-infra/packer-images/pull/527, closing this issue hopefully for good this time.

**Comment by dduportal** [comment]
Deployed:
- ci.jenkins.io, trusted.jenkins.io cert.ci.jenkins.io => https://github.com/jenkins-infra/jenkins-infra/pull/2671
- infra.ci.jenkins.io, release.ci.jenkins.io => https://github.com/jenkins-infra/kubernetes-management/pull/3646
