### ISSUE TITLE
Uninstall deprecated momentjs plugin bundle

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3366]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

![Screenshot 2023-01-31 at 17 56 28](https://user-images.githubusercontent.com/13383509/215829965-a8a215b7-eb9f-485b-bf9b-30a6bf5e4aed.png)

(edit) Ref. https://github.com/jenkins-infra/update-center2/pull/679

- [x] ci.jenkins.io: Manually managed, to be checked
- [x] trusted & cert.ci: Nothing specific in hieradata, but trusted and cert are manually managed anyway, plugin wise.
- [ ] infra.ci: Can be uninstalled once the new docker image is deployed: https://github.com/jenkins-infra/docker-jenkins-weekly/pull/988
- [x] release.ci: Can be uninstalled once the new docker image is deployed: https://github.com/jenkins-infra/docker-jenkins-lts/pull/677
- [ ] weekly.ci: I have no perms to check anything, someone else needs to take a look.

**Comment by dduportal** [comment]
Update on ci.jenkins.io: 
- the plugin was marked for uninstallation (thanks!) but the controller wasn't restarted
- also removed the jquery bundle as per the warning message
- Updated plugins index, and upgraded all plugins
- Triggered a controller restart: no more warnings \o/

**Comment by dduportal** [comment]
- trusted.ci : same (manual) procedure as ci.jenkins.io
- cert.ci: was already done (thanks)!

**Comment by dduportal** [comment]
- release.ci done:
  - https://github.com/jenkins-infra/docker-jenkins-lts/pull/677
  - https://github.com/jenkins-infra/kubernetes-management/pull/3542

**Comment by dduportal** [comment]
- infra.ci and weekly.ci done (thanks @smerle33 @herverlemeur)
  - https://github.com/jenkins-infra/docker-jenkins-weekly/pull/988 
  - https://github.com/jenkins-infra/kubernetes-management/pull/3541

**Comment by basil** [comment]
The same should be done for `ace-editor` (soon to be deprecated) after upgrading to https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/3611.v201b_d9f9eb_f7 because it is in the same category as `momentjs` and `handlebars` (abandoned 7 years ago, no updates).

**Comment by dduportal** [comment]
> The same should be done for `ace-editor` (soon to be deprecated) after upgrading to https://github.com/jenkinsci/workflow-cps-plugin/releases/tag/3611.v201b_d9f9eb_f7 because it is in the same category as `momentjs` and `handlebars` (abandoned 7 years ago, no updates).

https://github.com/jenkins-infra/helpdesk/issues/3374 to track
