### ISSUE TITLE
forgot password and username

### ISSUE THREAD

**Issue by Neerajraj07** [jenkins-infra/helpdesk#3370]
### Type(s) of account issue

I've lost my password

### Summary

can you provide me link to reset my password 

### jenkins.io account email

raj920448@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Closing as it seems @Neerajraj07 mentions an account that does not exist on our systems (aka. `*.jenkins.io`): most probably their organization's internal system.
