### ISSUE TITLE
passwd

### ISSUE THREAD

**Issue by DkUzoukwu** [jenkins-infra/helpdesk#3371]
### Type(s) of account issue

I didn't receive any email

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by DkUzoukwu** [comment]
Jenkins dashboard
pls what is the meaning of passwd #3371?

**Comment by dduportal** [comment]
Hi @DkUzoukwu , thanks for opening this issue.

The website accounts.jenkins.io is only to manage your account for the `*.jenkins.io` websites.

You do not have any account on this system: it looks like you want to reset your password for a company internal Jenkins instance: please check with the administrtors of this Jenkins instance internally to your organization.
