### ISSUE TITLE
Uninstall deprecated `jquery` and `ace-editor` plugins bundles

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3374]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

Follow up of https://github.com/jenkins-infra/helpdesk/issues/3366 (as per https://github.com/jenkins-infra/helpdesk/issues/3366#issuecomment-1413970724).

Ref. https://github.com/jenkins-infra/update-center2/pull/681 and https://github.com/jenkins-infra/update-center2/pull/679

- [x] ci.jenkins.io: Uninstall from UI
- [x] trusted.ci.jenkins.io: Uninstall from UI
- [x] cert.ci.jenkins.io: Manually managed + puppet (https://github.com/jenkins-infra/jenkins-infra/pull/2623) + Uninstall from UI
- [x] infra.ci.jenkins.io: Docker image `docker-jenkins-weekly` + Uninstall from UI
- [ ] release.ci.jenkins.io: Docker image `docker-jenkins-lts` + Uninstall from UI
- [x] weekly.ci.jenkins.io: Docker image `docker-jenkins-weekly` + Uninstall from UI

**Comment by daniel-beck** [comment]
Note that https://plugins.jenkins.io/jquery/ ≠ https://plugins.jenkins.io/jquery-detached/

**Comment by dduportal** [comment]
ci.jenkins.io: done ✅

**Comment by dduportal** [comment]
trusted.ci.jenkins.io: done ✅

**Comment by dduportal** [comment]
infra.ci and weekly.ci ✅

**Comment by dduportal** [comment]
release.ci.jenkins.io ✅
