### ISSUE TITLE
Question about OS-level build dependencies

### ISSUE THREAD

**Issue by a-st** [jenkins-infra/helpdesk#3375]
### Service(s)

ci.jenkins.io

### Summary

I recently adopted https://github.com/jenkinsci/performance-plugin and I'm looking forward to build a proper CI/CD workflow w.r.t. https://www.jenkins.io/doc/developer/publishing/releasing-cd/.

In its current state the plugin requires python3, virtualenv and bzt to be installed in order to properly run the (unit) tests. Is there any way to get this set up to run on ci.jenkins.io as well (e.g. building in a container, etc.)?

This is how my current [Jenkinsfile](https://github.com/jenkinsci/performance-plugin/blob/0f63142e4c07fde98a31d3d17a0e16caa98afc9f/Jenkinsfile) looks like (with disabled tests).

This is how my properly working [GitHub CI Action](https://github.com/jenkinsci/performance-plugin/blob/0f63142e4c07fde98a31d3d17a0e16caa98afc9f/.github/workflows/ci.yml) looks like.

**Comment by lemeurherve** [comment]
Hello @a-st,

`python3` and `virtualenv` are already available in ci.jenkins.io linux agents image: https://github.com/jenkins-infra/packer-images/blob/af7a992a97f3a5a9f9c3d7687c0a31426788a948/provisioning/ubuntu-provision.sh#L227-L236

You should be able to install this `bzt` python plugin via the pom in the preparation hook.
I have to gather more information about it but here is the hint I've got and can already tell you.

**Comment by a-st** [comment]
Hello @lemeurherve,

thanks a lot, works like a charm! 👍
