### ISSUE TITLE
Access to Testcomplete plugin  for osamasalem

### ISSUE THREAD

**Issue by osamasalem** [jenkins-infra/helpdesk#3376]
### GitHub repositories

https://github.com/jenkinsci/testcomplete-plugin

### GitHub users to have permission

@osamasalem

### Permission level

Maintain

### Justification

Hello here,

I am Osama Salem .. working as a developer at SmartBear to maintain TestComplete software and related plugins ... and working recently on TestComplete Jenkins plugin ... and I am welling to join the TC Jenkins maintainers team at your repo so we can publish our fixes and patches for plugin's end users

**Comment by NotMyFault** [comment]
Feel free to add your GitHub username to https://github.com/jenkins-infra/repository-permissions-updater/pull/3114 where we track the adoption of this plugin.
