### ISSUE TITLE
cloud native sig mailing list is getting spammed

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3377]
### Service(s)

Mailing lists

### Summary

https://groups.google.com/g/jenkins-cloud-native-sig

![image](https://user-images.githubusercontent.com/21194782/217278144-6a85fe46-ad88-4cc5-9b71-5d0b974098b2.png)

@olblak / @rtyler are owners of the list.

We can probably archive the list but at minimum could that poster be blocked / moderation enabled please

**Comment by olblak** [comment]
@timja I deleted the message, ban the user and granted you manager access.
