### ISSUE TITLE
Add NotMyFault to trusted.ci

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3381]
### Service(s)

trusted.ci.jenkins.io

### Summary

This issue follows up the conversation I had with Damien. The key to add is on my GitHub profile: https://github.com/NotMyFault.keys
The ssh-rsa one is supposed to be used.

**Comment by dduportal** [comment]
- Adding the public key to the trusted.ci VM: https://github.com/jenkins-infra/jenkins-infra/pull/2649
- Added the Jenkins Board to the jenkins-infra/runbooks

**Comment by dduportal** [comment]
Hello @NotMyFault , your public key has been deployed.

You have to follow the instructions at https://github.com/jenkins-infra/runbooks/tree/main/trusted-ci#connecting (private page).

Can you confirm that you can reach trusted.ci.jenkins.io by closing the issue?

**Comment by NotMyFault** [comment]
Has my key been deployed yet? I'm unable to log in.

```
➜  ~ ssh trusted.ci.jenkins.io                  
notmyfault@52.87.139.201: Permission denied (publickey).
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```

**Comment by dduportal** [comment]
> I'm unable to log in:
> 
> ```
> ➜  ~ ssh trusted.ci.jenkins.io                  
> notmyfault@52.87.139.201: Permission denied (publickey).
> kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535
> ```

Can you share (privately to me) the verbose version?

Also, can you check that your ssh-agent has the RSA key loaded?

**Comment by NotMyFault** [comment]
> Can you share (privately to me) the verbose version?

See Matrix

**Comment by NotMyFault** [comment]
Ok, I'm in, looks like https://github.com/jenkins-infra/jenkins-infra/pull/2652 was the missing part.
Just need some perms now
![Screenshot 2023-02-22 at 13 09 19](https://user-images.githubusercontent.com/13383509/220615964-ac93af2c-e6c3-4ec3-980f-96e75532e48d.png)

**Comment by dduportal** [comment]
- You've been added to the trusted-admin groups ✅ 
- The `bounce` configuration had been applied

=> is it good now?

**Comment by NotMyFault** [comment]
Looks good, thanks!
