### ISSUE TITLE
Archive jenkinsci/domain-discovery-module

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3389]
### GitHub repositories

jenkinsci/domain-discovery-module

### GitHub users to have permission

@basil

### Permission level

Read

### Justification

This module was on February 23, 2016 in https://github.com/jenkinsci/jenkins/pull/1301 and reverted two days later, never to be reintroduced again. I confirmed through searching sources that there are no references to this code in the `jenkinsci`, `jenkins-infra`, or `cloudbees` GitHub organizations. Note that as of JEP 230 the old module system has been deprecated in favor of plugins.

**Comment by NotMyFault** [comment]
The repository has been archived.

**Comment by basil** [comment]
Thank you!
