### ISSUE TITLE
Container images jenkins/jenkins:2.391 not published

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3390]
### Service(s)

Docker Hub

### Summary

The container images for Jenkins 2.391 are not published to Dockerhub.  Earlier versions are published.

The publication script fails to detect that 2.391 has not been published.  The message in the log for the publish.sh script indicates that a shell script comparison that expects two integers is not getting valid integers.  It appears the left hand side of the expression is the empty string

### Reproduction steps

1. Connect to trusted.ci
2. Open the log in the containers folder for the master branch of the containers build
3. See the "not a valid integer" message

https://github.com/jenkinsci/docker/pull/1577 is my attempt to resolve the issue by adding one more test to the conditional.

**Comment by dduportal** [comment]
Thanks a lot @MarkEWaite ! Your PR on jenkinsci/docker has been merged, and 2.391 container images are being built (https://trusted.ci.jenkins.io:1443/job/Containers/job/Core%20Release%20Containers/job/master/8151/console)

**Comment by dduportal** [comment]
- https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=2.391 is now published (cc @smerle33 for the docker-jenkins-weekly image)
- Follow up of @MarkEWaite 's fixup in https://github.com/jenkinsci/docker/pull/1578 (same fix applied to other parts of the script + fix latest weekly)
