### ISSUE TITLE
(2023-02-15) Azure Credential for cert.ci.jenkins.io is expired

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3395]
### Service(s)

cert.ci.jenkins.io

### Summary

The Azure credential used by cert.ci.jenkins.io is expired since the 15th of february:

- No more VM agents are spawned (Azure VM only)
- The build queue is increasing

**Comment by dduportal** [comment]
Short term (e.g. unblocking the build queue):

- [ ] Disabling Puppet agent on ert.ci
- [ ] Regenerate a 1-month token in Azure Portal for cert.ci
- [ ] Insert manually this new token on cert.ci to unblock the build queue

**Comment by dduportal** [comment]
Short term done in pair with @smerle33 : the agents are spawned successfully and build queue is now handled (with a limit of 7 VMs max in parallel as usual).

**Comment by dduportal** [comment]
Medium term:

- [ ] Manage the credential with Terraform in jenkins-infra/azure instead of manually (define/import the terraform app and associated credential) with a new (a 3rd) credential with a 6 month validity (recommended by Azure) using `terraform output`
- [ ] Insert the new (3rd) credential in the puppet encrypted eyaml in jenkins-infra/jenkins-infra 
- [ ] Enable puppet and apply + validate the configuratioj with the new (3rd) credential
- [ ] Update the calendar invite for the 6 months (the title should NOT mention the "3rd week notification"

**Comment by dduportal** [comment]
Long term, if adding a managed identity does not require to re-create the VM (e.g. only a reboot), to avoid requiring having a certificate or a token, then:

- [ ] Import the cert.ci VM (and resources) in jenkins-infra/azure project
- [ ] Add a managed identity only for managing agents for cert.ci (because [another identity is needed for Let's Encrypt](https://github.com/jenkins-infra/helpdesk/issues/3337))
- [ ] Associate the "agents" identity to the VM
- [ ] Remove the credential token
- [ ] Validate it continue working

**Comment by timja** [comment]
> Long term, if adding a managed identity does not require to re-create the VM (e.g. only a reboot), to avoid requiring having a certificate or a token, then:

It doesn't even require a reboot you can do it live.

**Comment by dduportal** [comment]
Update: cert.ci's temp. credential is expired: work in progress to update it in a managed way, like trusted.ci. 
ETA later today

**Comment by dduportal** [comment]
cert.ci.jenkins.io is now able to spawn agent properly again, with a fully managed credential

**Comment by dduportal** [comment]
Closing as https://github.com/jenkins-infra/helpdesk/issues/3460 track the required work for using WiM.
