### ISSUE TITLE
Maven 3.9.0

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3396]
## Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

## Summary

Maven 3.9.0 is [available](https://maven.apache.org/docs/3.9.0/release-notes.html) and it looks like that the Jenkins Core developers started using it:

- https://github.com/jenkinsci/core-pr-tester/pull/29
- https://github.com/jenkins-infra/jenkins.io/pull/6045

This issue tracks the following (coordinated) deployments:

- Merge automated PRs to bump the version on:
  - Agent VM templates + Linux Container templates: https://github.com/jenkins-infra/packer-images/pull/513
  - Windows Container templates: https://github.com/jenkins-infra/docker-inbound-agents/pull/63
  - Jenkins tools setup: TBD.
- Release and deploy new images
- Communicate to developer on the mailing list

**Comment by dduportal** [comment]
- ci.jenkins.io: Linux VM agents and container agents + Windows VM agents
  - Packer agent template release 0.59.0: https://github.com/jenkins-infra/packer-images/releases/tag/0.59.0
  - Deployment of Packer template 0.59.0 to production: https://github.com/jenkins-infra/jenkins-infra/pull/2625
- ci.jenkins.io: Windows container agents: 
  - Bump Maven 3.9.0 on the images: https://github.com/jenkins-infra/docker-inbound-agents/pull/63
  - TBD: deployment to production
- ci.jenkins.io: "Jenkins tool" Maven bumped to 3.9.0: https://github.com/jenkins-infra/jenkins-infra/pull/2641

**Comment by smerle33** [comment]
email sent to developers mailing list

**Comment by lemeurherve** [comment]
The default maven version on infra.ci.jenkins.io is still 3.8.6, reopening the issue.
