### ISSUE TITLE
Jenkins Core Release: Unable to build the Linux Docker Images with `docker buildx create --use: unknown flag: --use`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3400]
### Service(s)

ci.jenkins.io, trusted.ci.jenkins.io

### Summary

As mentionned in the Gitter channel `#jenkins-releases`, the weekly release of Jenkins 2.392 is currently failing the Docker image packaging step in trusted.ci with the error below (on Linux only):

```console
$ docker buildx create --use
unknown flag: --use
```

### Reproduction steps

- The error can be reproduced on ci.jenkins.io: https://ci.jenkins.io/job/Packaging/job/docker/job/master/8682/console
- The error *might* be caused by the Docker-CE upgrade introduced in https://github.com/jenkins-infra/packer-images/releases/tag/0.58.0

**Comment by dduportal** [comment]
For info: https://github.com/jenkins-infra/jenkins-infra/pull/2646 until `0.60.0` is correctly published (missing AMD64 linux container image)

**Comment by dduportal** [comment]
Found the culprit: https://github.com/docker/docs/commit/72d3016e81b93c4ce4e6c8e7b3400ac042d16a26

**Comment by dduportal** [comment]
Opened https://github.com/jenkins-infra/packer-images/pull/520

**Comment by gounthar** [comment]
Nice job!

**Comment by dduportal** [comment]
Automated deployment: https://github.com/jenkins-infra/jenkins-infra/pull/2648

**Comment by dduportal** [comment]
Deployed, container build in progress

**Comment by dduportal** [comment]
https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=2.392 => release successful :party:
