### ISSUE TITLE
ci.jenkins.io isn't building fork PRs for jenkins-io-components

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3409]
### Service(s)

ci.jenkins.io

### Summary

https://ci.jenkins.io/job/Websites/job/jenkins-io-components/view/change-requests/ doesn't seem to have https://github.com/jenkins-infra/jenkins-io-components/pull/62 or https://github.com/jenkins-infra/jenkins-io-components/pull/63

**Comment by lemeurherve** [comment]
Confirmed not running for https://github.com/jenkins-infra/jenkins-io-components/pull/73, same error in the scan repo logs.

I've checked the job configuration by comparing it to the one I took as model (jenkins.io), but didn't find any difference.

**Comment by dduportal** [comment]
is the GH app is not allowed to check this repository ?

**Comment by lemeurherve** [comment]
> is the GH app is not allowed to check this repository ?

That was it, forgot about this permission, again ^^

Thanks @dduportal

> Checking pull request [#74](https://github.com/jenkins-infra/jenkins-io-components/pull/74)
>     (not from a trusted source)
>       ‘Jenkinsfile’ found
>     Met criteria
