### ISSUE TITLE
Global build discard not working

### ISSUE THREAD

**Issue by Tavisca-Ashish-Vaswani** [jenkins-infra/helpdesk#3412]
### Service(s)

Other

### Summary

global build discard setting is not being overridden by pipeline discard setting, if value > default setting.

**Comment by Tavisca-Ashish-Vaswani** [comment]
set default settings to 10
set local setting to 15 (log rotation)
run more than 5 builds
refresh page
you see that any builds over 10 are discarded

**Comment by lemeurherve** [comment]
Hello @Tavisca-Ashish-Vaswani,

This help desk is dedicated to Jenkins Infrastructure issues.

For Jenkins itself, I suggest you to search if your issue does not already exist in https://issues.jenkins.io, and open a new one there if needed.
