### ISSUE TITLE
Remove Docker build for `jenkinsci/plugin-compat-tester`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3417]
### Service(s)

Docker Hub

### Summary

In recent commits I have removed the `Dockerfile` from this repository. The codebase has been completely de-Dockerified.

https://hub.docker.com/r/jenkins/pct is no longer produced and should be archived.

In addition there is a GitHub check called "ci/dockercloud-stage" that says "Your image failed to build in Docker Hub", presumably because I (intentionally) deleted the `Dockerfile`. I could find no references to this in the source code so I cannot figure out how to turn it off.

**Comment by timja** [comment]
> I could find no references to this in the source code so I cannot figure out how to turn it off.

It was in a webhook of the repository settings (and also configured in Docker hub).

I've removed both and updated the README on dockerhub and the description to mark as archived

**Comment by basil** [comment]
Thank you!
