### ISSUE TITLE
(Puppet) Replace updatecli GitHub Action by a dedicated Jenkinsfile in jenkins-infra/jenkins-infra

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3419]
Related: https://github.com/jenkins-infra/helpdesk/issues/2778

**Comment by dduportal** [comment]
- The new Jenkins pipeline opened 2 PRs with success 👏 
  - https://github.com/jenkins-infra/jenkins-infra/pull/2682
  - https://github.com/jenkins-infra/jenkins-infra/pull/2681

- Next step: remove the GHA

**Comment by smerle33** [comment]
could be close
