### ISSUE TITLE
unable to login 

### ISSUE THREAD

**Issue by Pradnya2103** [jenkins-infra/helpdesk#3420]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @Pradnya2103 , it looks like you're expecting an account reset on your Jenkins instance.

This issue tracker is only for accounts related to *.jenkins.io websites. Thus I'm closing this issue.

If you were expecting a password resat for your jenkins.io account, please reopen by providing the required informations (username and associated email).
