### ISSUE TITLE
Attempt to skip artifact caching proxy failed

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3422]
### Service(s)

Artifact-caching-proxy

### Summary

I was having problems with the artifact caching proxy in a previous build, so I applied the `skip-artifact-caching-proxy` label to https://ci.jenkins.io/job/jenkinsci-libraries/job/plugin-compat-tester/job/PR-485/4/ which then failed with

```
[2023-03-05T21:44:37.909Z] java.io.FileNotFoundException: The specified user settings file does not exist: /home/jenkins/agent/workspace/ries_plugin-compat-tester_PR-485/null
```

Looks like the `skip-artifact-caching-proxy` code path is broken

### Reproduction steps

Run a build of to https://ci.jenkins.io/job/jenkinsci-libraries/job/plugin-compat-tester/job/PR-485/ with the `skip-artifact-caching-proxy` label.

**Comment by basil** [comment]
Latest build _with_ the artifact caching proxy https://ci.jenkins.io/job/jenkinsci-libraries/job/plugin-compat-tester/job/PR-485/5/ failed with `Could not transfer artifact org.apache.maven.shared:maven-shared-components:pom:34 from/to azure-proxy (https://repo.azure.jenkins.io/public/): status code: 502, reason phrase: Bad Gateway (502)`, so I am completely blocked

**Comment by timja** [comment]
You can also disable it in ci.jenkins.io system configuration:
`ARTIFACT_CACHING_PROXY_AVAILABLE_PROVIDERS`

I've removed `azure`

**Comment by dduportal** [comment]
For info: build https://ci.jenkins.io/job/jenkinsci-libraries/job/plugin-compat-tester/job/PR-485/5/ marked " keep forever" to ensure we have proper timestamp and logs to debug the root HTTP/502 in the ACP instance

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/helpdesk/issues/3425 closed (HTTP/502 errors looks gone now that we have increased the associated storage)
- Azure ACP is now enabled again (added manually to `ARTIFACT_CACHING_PROXY_AVAILABLE_PROVIDERS` in ci.jenkins.io's administration UI as a "revert" of https://github.com/jenkins-infra/helpdesk/issues/3422#issuecomment-1455227702)
- Triggered a new build (#8) of the PCT PR (https://ci.jenkins.io/job/jenkinsci-libraries/job/plugin-compat-tester/job/PR-485/8/) to check the ACP usage

**Comment by dduportal** [comment]
Looks like the last build succeeded. Closing the issue.

Thanks @basil for raising this issue which allowed us to catch the issue!

**Comment by basil** [comment]
Thank you very much!

**Comment by dduportal** [comment]
For info, https://github.com/jenkins-infra/helpdesk/issues/3432 created to track monitoring of the disk usage so this won't happen again.
