### ISSUE TITLE
Failed plugin builds due to missing Windows configuration file

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3424]
### Service(s)

ci.jenkins.io

### Summary

Multiple plugin builds failed on the Windows agents of ci.jenkins.io due to a missing system configuration file.

https://ci.jenkins.io/job/Plugins/job/apache-httpcomponents-client-4-api-plugin/job/PR-127/1/ is one example.

### Reproduction steps

1. Run a pull request build on ci.jenkins.io of a plugin that includes Windows in its Jenkinsfile configuration
2. Confirm that the build fails due to a missing settings file with the name `null`

**Comment by dduportal** [comment]
The error in the build you linked is `java.io.FileNotFoundException: The specified user settings file does not exist: C:\Jenkins\workspace\nents-client-4-api-plugin_PR-127\null`.

This path does not look to be a missing file, but an issue in the pipeline code.


More precisely: the `mvn` command is `mvn --batch-mode --show-version --errors --no-transfer-progress -s null --update-snapshots -Dmaven.repo.local=C:/Jenkins/workspace/nents-client-4-api-plugin_PR-127@tmp/m2repo -Dmaven.test.failure.ignore -Dspotbugs.failOnError=false -Dcheckstyle.failOnViolation=false -Dcheckstyle.failsOnError=false -Dset.changelist clean install `

=> the `-s null` is clearly the source of the problem, which looks like a jenkins-infra/pipeline-library problem. 

cc @lemeurherve

**Comment by dduportal** [comment]
Might be related to https://github.com/jenkins-infra/helpdesk/issues/3422

**Comment by dduportal** [comment]
Triggered a new build #2: https://ci.jenkins.io/job/Plugins/job/apache-httpcomponents-client-4-api-plugin/job/PR-127/2/ now that https://github.com/jenkins-infra/pipeline-library/pull/611 is merged (and applied following a pipeline-library cache clear)

**Comment by dduportal** [comment]
Last build (#2) ran succesfully the `windows-11` on Azure and used the Azure ACP as per the logs: I'm closing the issue
