### ISSUE TITLE
502 Bad Gateway error on Azure artifact caching proxy

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3425]
### Service(s)

Artifact-caching-proxy

### Summary

As noticed in https://github.com/jenkins-infra/helpdesk/issues/3422#issuecomment-1455217685, in https://github.com/jenkins-infra/helpdesk/issues/3424 and in another test while implementing the artifact caching proxy for jenkins-infra/javadoc, the Azure provider of the artifact caching proxy failed sometimes with a 502 bad gateway error, as seen for example in https://ci.jenkins.io/job/jenkinsci-libraries/job/plugin-compat-tester/job/PR-485/5/ (marked as "keep forever" for debug)

**Comment by smerle33** [comment]
found this in the logs : 
```
2023/03/05 21:47:50 [crit] 24#24: *337794 pwritev() "/data/nginx-cache/0/c56917035f95338f26a6f2c20b50a020.0000012056" failed (28: No space left on device) while reading upstream, client: ....., server: _, request: "GET /public/org/apache/maven/shared/maven-shared-components/34/maven-shared-components-34.pom HTTP/1.1", upstream: "https://.....:443/public/org/apache/maven/shared/maven-shared-components/34/maven-shared-components-34.pom", host: "repo.azure.jenkins.io"
```

**Comment by smerle33** [comment]
volume state : 
AZURE: 
    - instance 1 : `/dev/sdc                 48.9G     48.9G         0 100% /data/nginx-cache`
    - instance 2 : `/dev/sdd                 48.9G     48.9G         0 100% /data/nginx-cache`
AWS: 
    - instance 1 : `/dev/nvme1n1             49.0G     44.2G      4.8G  90% /data/nginx-cache`
    - instance 2 : `/dev/nvme1n1             49.0G     44.8G      4.2G  91% /data/nginx-cache`
DO: 
    - instance 1 : `/dev/disk/by-id/scsi-0DO_Volume_pvc-...  48.9G     11.3G     35.1G  24% /data/nginx-cache`
    - instance 2 : `/dev/disk/by-id/scsi-0DO_Volume_pvc-...  48.9G     10.8G     35.6G  23% /data/nginx-cache`

**Comment by smerle33** [comment]
https://learn.microsoft.com/en-us/azure/azure-arc/data/resize-persistent-volume-claim
for azure, the `storageclass` that we use has the `AllowVolumeExpansion` flag set to True property

**Comment by smerle33** [comment]
Procedure applied to digital ocean cluster to increase PV size: 
```
kubectl config use-context  do-fra1-jenkins-infra-doks-public-hkuxfyvb
kubectl cluster-info
kubectl --namespace artifact-caching-proxy get statefulset artifact-caching-proxy --output yaml > statefulset_azure.yaml
vim statefulset_azure.yaml
kubectl --namespace artifact-caching-proxy delete statefulset artifact-caching-proxy --cascade=orphan
kubectl --namespace artifact-caching-proxy delete pod artifact-caching-proxy-0
kubectl get -n artifact-caching-proxy pvc,pv,pod
kubectl --namespace artifact-caching-proxy patch pvc nginx-cache-artifact-caching-proxy-0 --patch '{"spec": {"resources": {"requests": {"storage": "100Gi"}}}}'
kubectl get -n artifact-caching-proxy pvc,pod,pv #PV size updated but NOT PVC size
kubectl --namespace artifact-caching-proxy apply -f statefulset_azure.yaml
kubectl get -n artifact-caching-proxy pvc,pod,pv #both PV and PVC size updated
kubectl --namespace artifact-caching-proxy exec artifact-caching-proxy-0 -- df -h /data/nginx-cache #sanity check new size, not full and not empty
kubectl --namespace artifact-caching-proxy scale statefulset artifact-caching-proxy --replicas=1
kubectl get -n artifact-caching-proxy pvc,pod,pv #check that only the first pod is running (with new size)
kubectl --namespace artifact-caching-proxy patch pvc nginx-cache-artifact-caching-proxy-1 --patch '{"spec": {"resources": {"requests": {"storage": "100Gi"}}}}'
kubectl --namespace artifact-caching-proxy exec artifact-caching-proxy-1 -- df -h /data/nginx-cache #sanity check new size, not full and not empty
kubectl --namespace artifact-caching-proxy scale statefulset artifact-caching-proxy --replicas=2
kubectl get -n artifact-caching-proxy pvc,pod,pv #check that all pods are now with the correct size
```

**Comment by smerle33** [comment]
We did azure with success

**Comment by smerle33** [comment]
amazon procedure seem a little different as the storage class in used refuse the resize for now

**Comment by smerle33** [comment]
addon for aws : 
kubectl patch storageclass ebs-sc-az1-retain -p '{"allowVolumeExpansion": true}'

**Comment by dduportal** [comment]
Kubernetes management job enabled again, last build applied succesfully

**Comment by dduportal** [comment]
Tried a local build of https://github.com/jenkinsci/plugin-compat-tester/pull/485 with a Maven `settings.xml` file pointing to the Azure Artifact Caching proxy: no more HTTP/502 on this test.
