### ISSUE TITLE
'mvn' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Kaushik-Iyer** [jenkins-infra/helpdesk#3427]
### Service(s)

plugins.jenkins.io

### Summary

When I try to run 'mvn package' on a maven project through a freestyle job, this is the error I get
![image](https://user-images.githubusercontent.com/84177184/223125949-925b9d56-767e-4294-beac-bc4259a928b7.png)

I have downloaded the Maven Integration Plugin as well as configured MAVEN_HOME

![image](https://user-images.githubusercontent.com/84177184/223126146-b2f03229-5945-4cfd-bb41-ae80620ecc0d.png)

![image](https://user-images.githubusercontent.com/84177184/223126684-26d5b58c-8f0a-4ede-8a8b-c5d5aef86311.png)

Using a Maven Job works, so why does mvn package not work when using a freestyle job

### Reproduction steps

1. Download Maven Integration Plugin and configure MAVEN_HOME
2. Create new Freestyle Job
3. Change Directory to maven project and try to run maven commands as windows batch command

**Comment by dduportal** [comment]
Hi @Kaushik-Iyer , this issue tracker is only about the `*.jenkins.io` infrastructure and sites.
I'm going to close this issue as it is unrelated to the infrastructure.

Your question is a Jenkins-related question: you should open a thread in the [Community Forums](https://community.jenkins.io) to get views and answers.
