### ISSUE TITLE
Jenkins Core Release: disable weekly release for 07th of March 2023

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3428]
### Service(s)

release.ci.jenkins.io

### Summary

As per https://groups.google.com/g/jenkinsci-advisories/c/RmkqB1wAY14, the JenSec security team request that the weekly release planned the 7th of March 2023 to be disabled (in favor of a weekly the 08th of March).

=> Approved by @timja (as release officer) and implemented in https://github.com/jenkins-infra/release/pull/336.

Additionnaly, the Jenkins infra team is asked to avoid any configuration change on release.ci.jenkins.io until @daniel-beck acknowledges that the JenSec work on release.ci.jenkins.io is finished.

**Comment by dduportal** [comment]
Side note for @daniel-beck : let us (jenkins-infra team) know when you're finished in order for us to deliver the fixes for https://github.com/jenkins-infra/helpdesk/issues/3426

**Comment by dduportal** [comment]
Closing as no weekly was released (as expected :) )

**Comment by lemeurherve** [comment]
Created https://github.com/jenkins-infra/release/pull/337 as draft for now, as reminder for restoring weekly releases after the 8th of March 2023.
