### ISSUE TITLE
jobcopy-builder plugin 1.5.0 release fails to download from updates.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3429]
### Service(s)

Update center

### Summary

[JENKINS-70286](https://issues.jenkins.io/browse/JENKINS-70286) describes the issue as follows:

The [GitHub repository](https://github.com/jenkinsci/jobcopy-builder-plugin/releases/tag/jobcopy-builder-1.5.0) and the [plugins site](https://plugins.jenkins.io/jobcopy-builder/#releases) show that jobcopy builder plugin 1.5.0 is released. The [1.5.0 plugin release](https://repo.jenkins-ci.org/artifactory/releases/jp/ikedam/jenkins/plugins/jobcopy-builder/1.5.0/jobcopy-builder-1.5.0.hpi) is available from the artifact repository.

The [update site](https://updates.jenkins.io/latest/) reports a URL of https://updates.jenkins.io/latest/jobcopy-builder.hpi but when I try to check the [mirrors](https://updates.jenkins.io/latest/jobcopy-builder.hpi?mirrorlist), it reports not found.

I think that means that the process that detects new plugin releases and makes them available through the update center has not done its job in this case. That is surprising since the [httpcomponents plugin update](https://get.jenkins.io/plugins/apache-httpcomponents-client-4-api/4.5.14-150.v7a_b_9d17134a_5/apache-httpcomponents-client-4-api.hpi?mirrorlist) that was released after jobcopy-builder 1.5.0 is available from the update center. We may need help from the infra team to understand this failure.

I've uploaded the 1.5.0 release as an attachment in case someone needs to install it with the plugin manager "advanced" page. See [jobcopy-builder.hpi](https://issues.jenkins.io/secure/attachment/60072/60072_jobcopy-builder.hpi)

### Reproduction steps

1. Attempt to download the most recent release of jobcopybuilder-plugin from https://updates.jenkins.io/latest/jobcopy-builder.hpi , note that the download fails

### Workaround

Simple workaround provided in [JENKINS-70286](https://issues.jenkins.io/browse/JENKINS-70286).  [Download the plugin](https://issues.jenkins.io/secure/attachment/60072/jobcopy-builder.hpi) and install it with the advanced page of the plugin manager.

**Comment by MarkEWaite** [comment]
Possibly related to:

* https://github.com/jenkins-infra/helpdesk/issues/3411

**Comment by dduportal** [comment]
> Possibly related to:
> 
>     * [Update center job is failing #3411](https://github.com/jenkins-infra/helpdesk/issues/3411)

Absolutely: It seems that https://github.com/jenkins-infra/helpdesk/issues/3411#issuecomment-1446101531 was not enough and missed the associated release. We are going to update this manually (ETA: tuesday 7th or March)

**Comment by lemeurherve** [comment]
> Attempt to download the most recent release of jobcopybuilder-plugin from [updates.jenkins.io/latest/jobcopy-builder.hpi](https://updates.jenkins.io/latest/jobcopy-builder.hpi) , note that the download fails

The download is now successful, closing this issue.
