### ISSUE TITLE
Migrate `jan-molak/jenkins-build-monitor-plugin` to `jenkinsci` GitHub organization

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3430]
### Service(s)

GitHub

### Summary

Per https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/656 we have agreed to move `jan-molak/jenkins-build-monitor-plugin` to `jenkinsci/build-monitor-plugin`. Once the repository is transferred, I will set up permissions in RPU matching the existing set of committers (currently @jan-molak and myself).

**Comment by NotMyFault** [comment]
Thanks for leading this effort! Once @jan-molak starts the [transfer](https://github.com/jan-molak/jenkins-build-monitor-plugin/transfer) on his side, let a @jenkins-infra/jenkinsci-admins accept it.

**Comment by timja** [comment]
I’m ready to accept the transfer

**Comment by jan-molak** [comment]
Hello @NotMyFault! It looks like to transfer a repository I'd need permissions to create public repos under the `jenkinsci` org
<img width="726" alt="Screenshot 2023-03-07 at 13 53 38" src="https://user-images.githubusercontent.com/1089173/223442496-2f0fa318-6c49-405f-8c5b-72be53e061dd.png">

**Comment by jan-molak** [comment]
Also, as per my conversation with @basil, here's the link to [Jenkins Governance Meeting regarding the transfer](https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#heading=h.86ehtrl3jc4g)

**Comment by NotMyFault** [comment]
> Hello @NotMyFault! Could you please add me to members of jenkinsci org so that I can complete the transfer?

Regular users have no permission to create repositories on their behalf. Best to invite @timja as admin to your repository, and he transfers it himself.

**Comment by jan-molak** [comment]
Thanks @NotMyFault - I've invited @timja

**Comment by timja** [comment]
I've invited you to https://github.com/jenkinsci-transfer2

You should be able to transfer it there.

(https://github.com/jenkinsci-transfer also exists but not sure who has access there)

Because this is in a personal account you can't delegate permissions in any way other than adding a collaborator that can merge PRs (but can't access settings)

**Comment by daniel-beck** [comment]
> (https://github.com/jenkinsci-transfer also exists but not sure who has access there)

Oleg and me.

**Comment by timja** [comment]
if you can add me as an owner i can delete jenkinsci-transfer2 after this

**Comment by NotMyFault** [comment]
> > (https://github.com/jenkinsci-transfer also exists but not sure who has access there)
> 
> Oleg and me.

TIL, maybe we should add some more people to this org 🤔

**Comment by daniel-beck** [comment]
Invited @timja and @NotMyFault

**Comment by timja** [comment]
re-invited @jan-molak to https://github.com/jenkinsci-transfer
and deleted the one I created

**Comment by NotMyFault** [comment]
> Invited timja and @NotMyFault

Thanks, although I can't seem to invite people there.

**Comment by jan-molak** [comment]
Over to you, @timja

**Comment by timja** [comment]
Transferred.
https://github.com/jenkinsci/build-monitor-plugin

@jan-molak please accept the invite at https://github.com/jenkinsci

**Comment by jan-molak** [comment]
Accepted, thank you!

**Comment by timja** [comment]
Thanks all done from hosting side

**Comment by basil** [comment]
Thank you!
