### ISSUE TITLE
Monitor the ACP disk usage

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3432]
### Service(s)

Artifact-caching-proxy

### Summary

The issue https://github.com/jenkins-infra/helpdesk/issues/3422 was caused by disk full for ACP on Azure.

We increased the disk usage to 100Gb (instead of the initial 50Gb) which fixed the issue.

But we need to monitor these disk usages to alert us when the 80% threshold is crossed.

**Comment by lemeurherve** [comment]
Fixed by https://github.com/jenkins-infra/datadog/pull/158
