### ISSUE TITLE
Maven central packages not found on build agent

### ISSUE THREAD

**Issue by ccHanibal** [jenkins-infra/helpdesk#3434]
### Service(s)

ci.jenkins.io

### Summary

Hi,

I filed a PR here: https://github.com/jenkinsci/confluence-publisher-plugin/pull/102

The build failed due to not finding org.codehaus.jackson:jackson-core-asl:jar:1.9.13-atlassian-6 and some other dependencies, but they are definitely there, see https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-core-asl/1.9.13-atlassian-6
Additionally I did not add those depednecies, they were already there before.

So something seems to be wrong with the azure-proxy maven source.

The full build log can be found here: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fconfluence-publisher-plugin/detail/PR-102/2/pipeline/28

Full error is

`[2023-03-02T09:18:54.616Z] [ERROR] Failed to execute goal on project confluence-publisher: Could not resolve dependencies for project org.jenkins-ci.plugins:confluence-publisher:hpi:150.v3526c59848ed: The following artifacts could not be resolved: org.codehaus.jackson:jackson-core-asl:jar:1.9.13-atlassian-6, org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13-atlassian-6, org.codehaus.jackson:jackson-jaxrs:jar:1.9.13-atlassian-6, org.codehaus.jackson:jackson-xc:jar:1.9.13-atlassian-6: Could not find artifact org.codehaus.jackson:jackson-core-asl:jar:1.9.13-atlassian-6 in azure-proxy (https://repo.azure.jenkins.io/public/) -> [Help 1]`

### Reproduction steps

Probably rerun the pipeline.

**Comment by lemeurherve** [comment]
The reason your build is failing is that with the artifact caching proxies we're mirroring (almost) every Maven repositories, and looking at the JFrog Artifactory https://repo.jenkins-ci.org/public/org/codehaus/jackson/jackson-mapper-asl/ (which is mirrored by the azure-proxy artifact caching proxy provider), I've noticed it contains `1.9.13-atlassian-2` as last release, but not the next ones.

Currently looking how it could be resolved.

**Comment by ccHanibal** [comment]
I can not rerun the pipeline myself (I am not the plugin maintainer @jetersen is), so I don't know.
But I will file a new PR in a few days, then we will see.

**Comment by ccHanibal** [comment]
Wait a second. I just saw that some one triggered the pipline and it ran without problems. See here: https://ci.jenkins.io/job/Plugins/job/confluence-publisher-plugin/view/change-requests/job/PR-102/3/console

So it probably is resolved. Otherwise I will reopen the issue.

**Comment by ccHanibal** [comment]
fyi, I will close the PR#102 and opened a new PR at https://github.com/jenkinsci/confluence-publisher-plugin/pull/103. You can test with that.

**Comment by jetersen** [comment]
@lemeurherve is there a way we can disable artifact caching proxy in our Jenkinsfile so we can get a release out?

**Comment by lemeurherve** [comment]
@ccHanibal @jetersen as soon as the two PRs I've opened to add an exception for the atlassian-public Maven repository are merged, the build should complete without issue (tested locally).

It's possible to disable the artifact caching proxy but it's not recommended.
By a replay or by a commit, you can add/modify the Jenkinsfile to set `useArtifactCachingProxy: false` as parameter of `buildPlugin`.

Ex: `buildPlugin(platforms: ['linux'], useArtifactCachingProxy: false)`

**Comment by jetersen** [comment]
If you have a PR ready, we can wait for that :)

**Comment by lemeurherve** [comment]
> fyi, I will close the PR#102 and opened a new PR at [jenkinsci/confluence-publisher-plugin#103](https://github.com/jenkinsci/confluence-publisher-plugin/pull/103). You can test with that.

@ccHanibal I've restarted this build: ✅ 

Sorry it took so long.
