### ISSUE TITLE
Add `gatsby-plugin-jenkins-layout` to ci.jenkins.io and infraci.jenkins.io

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3435]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io

### Summary

[gatsby-plugin-jenkins-layout](https://github.com/jenkins-infra/gatsby-plugin-jenkins-layout) is a npm plugin that will download and import the jenkins.io layout to import into gatsby/jsx

Was converted from a script in plugins repo to a plugin sometime in the past and deployed via github actions.

Sadly github actions doesn't seem to give the semantic-release plugin enough access to look at pr titles, so if a commit message doesnt have fix/feat, then no release happen.

I already commited the Jenkinsfile from io components, which was already pretty close to what the github actions were doing, just need it running and deploying so we can turn off the github actions.

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/kubernetes-management/pull/3662

**Comment by lemeurherve** [comment]
Added the repo to the GitHub app:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/91831478/223678025-b4b14eb6-0075-4008-a098-8b2c9ca40e0a.png">

**Comment by lemeurherve** [comment]
Added the job to ci.jenkins.io as well:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/91831478/223682369-b1c02ca6-b275-4f61-aaf9-fc95a2b7261d.png)

</details>

**Comment by lemeurherve** [comment]
Fixed the repo URL on ci.jenkins.io job configuration (was jenkins-io-components...), and added it to the ci.jenkins.io GitHub App allowed repositories:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/91831478/223789451-e83852c9-e885-444e-931f-f8cc9f48c424.png">

**Comment by halkeye** [comment]
From my point of view this is done and working, through from irc i hear a seperate app is going to be created

**Comment by dduportal** [comment]
Thanks! We can close this issue.

A not about the "tradeoff" here: we accept that we aggregate different repositories under the same GitHub App: the risk of one project going wild and trying to write on another project is acceptable for this one, compared to the complexity (and associated risks) of managing a GitHub App per repository and the associated credentials to be created/rotated, etc.
