### ISSUE TITLE
Update social links on GH organizations

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3441]
### Service(s)

GitHub

### Summary

A [recent](https://github.blog/changelog/2023-02-02-add-more-social-links-to-your-user-profile/) change allows adding up to four social links to profiles, including organizations, with a few predefined icons, similar to the twitter one.
I thought that this would be a nice addition for our organizations, given we're present on a few platforms, so I came up with this layout:
![Screenshot 2023-03-09 at 21 17 57](https://user-images.githubusercontent.com/13383509/224145454-e152cf13-babc-44d1-9383-7be84fd492cd.png)
The links used in order:
- https://twitter.com/jenkinsci
- https://www.linkedin.com/company/jenkins-project/
- https://www.youtube.com/@jenkinscicd
- https://community.jenkins.io/

I think these would make a nice addition and could draw some potential traffic to our other social media :)

**Comment by timja** [comment]
I've added it to https://github.com/jenkinsci/

**Comment by dduportal** [comment]
<img width="1448" alt="Capture d’écran 2023-04-01 à 13 06 58" src="https://user-images.githubusercontent.com/1522731/229285177-8dc9897f-803c-48d8-ba53-e2ba98abf51e.png">

Gotcha!
