### ISSUE TITLE
Can't login to https://issues.jenkins.io

### ISSUE THREAD

**Issue by ipleten** [jenkins-infra/helpdesk#3444]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I'm able to login to accounts and artifacts but not to Jira.
I tried to reset password but it doesn't help
### jenkins.io account username

tamerlaha

### jenkins.io account email

tamerlaha+jenkins.io@gmail.com

### Which URL are you trying to login at?

https://issues.jenkins.io/secure/Dashboard.jspa

**Comment by NotMyFault** [comment]
> jenkins.io account email
[tamerlaha+jenkins.io@gmail.com](mailto:tamerlaha+jenkins.io@gmail.com)

Are you confident this is the correct email address? The Jira account matching the username `tamerlaha` is registered to the email address `tamerlaha@gmail.com`.

**Comment by ipleten** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/6207156/224827762-2e13edd5-5372-42b5-b153-ef99a5daf4c4.png">
This is a screenshot from my accounts site

**Comment by NotMyFault** [comment]
I don't think accountapp supports that syntax out of the box. I recall similar issues like that before.

**Comment by ipleten** [comment]
I've changed email and now it works ¯\_(ツ)_/¯
