### ISSUE TITLE
Apply to Docker Open Source for the `jenkinsciinfra` and `jenkins4eval` organizations

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3452]
### Service(s)

Docker Hub

### Summary

As free teams will be discontinued, we need to make these orgs part of the Docker Open Source sponsorship, or put them under the `jenkins` Docker organization umbrella.

**Comment by timja** [comment]
jenkins4eval is where the images get pushed to on non trusted infra right?

**Comment by lemeurherve** [comment]
> jenkins4eval is where the images get pushed to on non trusted infra right?

Yes exactly.

**Comment by dduportal** [comment]
Email sent to Docker Open Source program's manager with the team (private) email in Cc.

For info, 1 year ago, they agreed to put `jenkinsciinfra` and `jenkins4eval` under the Open Source program umbrella : let's hope it's still the case.

**Comment by dduportal** [comment]
Closing because; https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

**Comment by lemeurherve** [comment]
For the record, we've got confirmation from Docker that both of these organisations are part of their Open Source program. It's just that they don't have the corresponding badge as they are dedicated to internal use.
