### ISSUE TITLE
Adding windows agents to the ATH test suite

### ISSUE THREAD

**Issue by rsandell** [jenkins-infra/helpdesk#3456]
### Service(s)

ci.jenkins.io

### Summary

I am in the process of contributing some [windows specific tests to the ATH](https://github.com/jenkinsci/acceptance-test-harness/pull/1064) and I don't know enough about the CI infrastruture to be able to add windows agents to the test suite myself and will need some help.

**Comment by timja** [comment]
Are you contributing others? because this PR has been recommended for close https://github.com/jenkinsci/acceptance-test-harness/pull/1064

**Comment by rsandell** [comment]
Not explicitly, some tests that we will be contributing have code to make the tests run on both win and *nix though. But that can be ignored I guess :)
