### ISSUE TITLE
 (2023-03-04) Azure Credential for ci.jenkins.io is expired

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3459]
### Service(s)

ci.jenkins.io

### Summary

The Azure credential used by ci.jenkins.io expired the 04th of march.

- No more Azure VM or ACI (Windows container) agents were spawned
- The build queue was increasing

(Note this is an issue written after 2 weeks after the incident to track the task done and to be done)

Last year's issue: https://github.com/jenkins-infra/helpdesk/issues/2801

**Comment by dduportal** [comment]
- A temporary comment had been generated, named `20230305-temp-ddu` to unblock, followed by a controller restart: builds were handled again.

**Comment by dduportal** [comment]
- ci.jenkins.io is unable to spin up VM agents since 14:08 UTC today. It was due to a human mistake: I was importing resource as part of this issue, and we had to run the terraform's Azure build (associated to the main branch of the jenkins-infra/azure repository) for today's weekly to apply https://github.com/jenkins-infra/azure-net/pull/55 to the node pools of the [`privatek8s`](#2844) cluster.

- The terraform job tried to destroy the imported resources: it almost deleted ci.jenkins.io VM but @lemeurherve reacted promptly and stopped the job.

Work in progress to fix this:

- Auditing which resources were deleted
- Importing the non-destroyed resources
- Opening the PR and merging it
- Updating ci.jenkins.io configuration


Post mortem:

- I should have removed the imports before being to complete 
- We might want to take snapshots of data disk to survive any potential VM destruction 
- https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/lock-resources?tabs=json could be useful (manageable as code as per @lemeurherve 's researches: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_lock)

**Comment by timja** [comment]
Resource locks are often better set outside of terraform so that they don’t get accidentally removed on a destroy

Example: https://github.com/hmcts/azure-resource-locks/blob/master/scripts/enable-resource-locking.sh

**Comment by dduportal** [comment]
More fixes:
- https://github.com/jenkins-infra/azure/pull/314
- https://github.com/jenkins-infra/azure/commit/f046ecbcff47a41ad0e63afd611c3f3d3a95e0bd

Restart: azure VM seems ok now.

**Comment by dduportal** [comment]
- Increased the VM limit to 40 max each (instead of 10/20) to handle the queue during the upcoming hours
- Cancelled some BOM builds cc @MarkEWaite @basil . 
- Ping @jglick The last restart seems to generate a lot of noise: some builds are still seen in the queue while showing a state of "aborted". I wonder if this could be related to the incremental pipeline plugin. Logs shows a LOT of lines like this one:

```
Mar 28 21:12:24 ci docker-jenkins[14133]: 2023-03-28 21:12:24.563+0000 [id=965]        WARNING        o.j.p.w.s.s.ExecutorStepExecution$PlaceholderTask#getCauseOfBlockage: Refusing to build ExecutorStepExecution.PlaceholderTask{runId=Tools/bom/PR-1911#2,label=jnlp-maven-11-rn9gw,context=CpsStepContext[1693:node]:Owner[Tools/bom/PR-1911/2:Tools/bom/PR-1911 #2],cookie=<redacted>,auth=null} and going to cancel it, even though it was supposedly stopped already, because associated build is complete
```

**Comment by jglick** [comment]
@dduportal if you mean https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/299, I do not _think_ so; that message is from the older https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/259 (#3211).

**Comment by dduportal** [comment]
Closing the issue as it is solved (credentials are managed as code for ci.jenkins.io).

The production incident is still present, but followed up in https://github.com/jenkins-infra/helpdesk/issues/3474 which happened at the same time and generated the thousand of builds.
