### ISSUE TITLE
[INFRA-384] Migrate jenkins-infra to beaker-based acceptance tests

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#346]
<p>The current <tt>vagrant-aws</tt> based serverspec tests are a bit outdated and beaker has definitely caught up in terms of maturity.</p>

<p>We need to look at migrating away from serverspec/vagrant-aws</p>

---
<details><summary><i>Originally reported by <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-384" target="_blank">Migrate jenkins-infra to beaker-based acceptance tests</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
Closing old issues that appear no longer relevant
