### ISSUE TITLE
401 when performing plugin release via CD workflow

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3462]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hi,

I need to create a release pipeline-npm-plugin via workflow dispatch 

Even if the automated release worked in the past (https://github.com/jenkinsci/pipeline-npm-plugin/releases) I receive now 401 from artifactory: https://github.com/jenkinsci/pipeline-npm-plugin/actions/runs/4475885021/jobs/7865715677

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.0:deploy (default-deploy) on project pipeline-npm: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:pipeline-npm:pom:49.v9c8598493533 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/pipeline-npm/49.v9c8598493533/pipeline-npm-49.v9c8598493533.pom, status: 401 Unauthorized -> [Help 1]
```

I'm not sure what is the issue, I've double check that the action secrets are correctly created : https://github.com/jenkinsci/pipeline-npm-plugin/settings/secrets/actions

![secrets_token](https://user-images.githubusercontent.com/825750/226527108-487192c3-8a33-4d69-8c81-b3c86a94d1c7.PNG)

Can you help ?

Thanks.

### jenkins.io account username

jonesbusy

### jenkins.io account email

jonesbusy@gmail.com

### Which URL are you trying to login at?

https://github.com/jenkinsci/pipeline-npm-plugin/actions/runs/4475885021/jobs/7865715677

**Comment by jonesbusy** [comment]
I ran the workflow again and work as expected : https://github.com/jenkinsci/pipeline-npm-plugin/actions/runs/4476525415

Looks secret were regenerated

![actions](https://user-images.githubusercontent.com/825750/226542261-22f07bdb-3315-4b5c-8f88-e6db31a7571a.PNG)

Was there any issue with token refresh ? (Or a maintenance  windows ?)

Thanks

**Comment by timja** [comment]
Secrets are only valid for a few hours (I think 4?)

Your first screenshot says 5 hours so they were renewed too slowly.

**Comment by jonesbusy** [comment]
Thanks good to know!

**Comment by dduportal** [comment]
Just checked the history of the job in charge of the token regenration (repository-permissions-updater on the private trusted.ci.jenkins.io controller): it failed the 21 of March 2023 at 03:29am UTC but then suceeded at 06:29am UTC.

It explains why your token was not up-to-date at 05:35am UTC, and why it worked when you re-tried.
Sorry for the inconvenience.

Note: the failure cause is because an HTTP/503 answer was received from the GitHub API.
Ping @daniel-beck would that make sense to add have this job to retry once when it fails during the "Run" stage to avoid this kind of issues?

**Comment by daniel-beck** [comment]
Probably.

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/3203 => here we are

**Comment by dduportal** [comment]
Closing the issue as the initial problem is gone. The RPU PR tracks the next steps: the answer might be "let's not change the process".

**Comment by daniel-beck** [comment]
Two executions of RPU failed with HTTP 503 when updating credentials (`https://api.github.com/repos/jenkinsci/*-plugin/actions/secrets/MAVEN_TOKEN`). This should probably be more robust.

**Comment by daniel-beck** [comment]
The latest execution was successful, so it should work now.
