### ISSUE TITLE
Could not create account

### ISSUE THREAD

**Issue by schiasileon** [jenkins-infra/helpdesk#3464]
### Type(s) of account issue

I didn't receive any email, I've been blocked by the anti-spam system

### Summary

Hi team, 

I recently tried to sign up on jenkins jira with the email given. I did not get a password via email so I tried using another email (my private one) for signing up but got blocked by the spam protection. 

I am trying to submit a bugreport for the bitbucket-branch-source-plugin that our team found on the latest version. 

### jenkins.io account username

leon_schiesswald

### jenkins.io account email

leon.schiesswald@dynatrace.com

### Which URL are you trying to login at?

https://issues.jenkins.io/login.jsp

**Comment by schiasileon** [comment]
Hi, i did not receive any email.

**Comment by dduportal** [comment]
> Hi, i did not receive any email.

Looks like there is some kind of grey/deny listing on the dynatrace email system.

I've just checked the accounts.jenkins.io application and there are no errors related to email sending (+ tested by resetting my dummy's account password with success). 

Could you send an email, from your private "alternate" email, to the (private) mailing list jenkins-infra-team@googlegroups.com with reference to this issue?

Once done, we'll be able to update your Jenkins accounts with this new email.

**Comment by dduportal** [comment]
Closing as no answer from the user.

@schiasileon Feel free to reopen with details if needed.

**Comment by aakash408** [comment]
Hi, i did not receive any email. for forgot password .
