### ISSUE TITLE
Action Required: Declare your JetBrains Marketplace vendor status

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3465]
### Service(s)

Other

### Summary

Received from Jetbrains for the `Jenkins project` organisation

https://plugins.jetbrains.com/docs/marketplace/trader-status.html#trader-and-non-trader-status

I assume `Non trader`, but just wanted a couple more eyes on it

cc @MarkEWaite @daniel-beck @duemir

-----

Dear developer,

Please declare whether your Organization on JetBrains Marketplace can be considered a trader or not according to the definition from the European Union. This will allow consumers from the EU to determine whether consumer protection regulations apply to them.

To do this, go to the My Organizations page, proceed to your organization’s profile, click the Edit icon in the top right-hand corner of the page, and set the vendor status in the settings.

Please note that it is your responsibility as a vendor to declare trader / non-trader status! Learn more about the requirements here.

Thank you,
The JetBrains Marketplace team

**Comment by daniel-beck** [comment]
No clue. Would ask CDF whether their ownership of Jenkins (TM) means the Jenkins project is somehow unexpectedly "part of" CDF. Otherwise

> If you create a plugin in cooperation with other individuals, you make the declaration as an individual vendor, i.e. the person uploading the plugin is the one making the declaration.

seems to apply.

**Comment by duemir** [comment]
I am the one uploading at the moment. 

> If you are a natural person (software developer) working for a company, but you develop plugins in your free time as a hobby and offer them for free and provide means for users to support your development on a voluntary basis (voluntary financial contribution), you may be qualified as a non-trader.

This is the one that seems to fit best because I configured the donation link to point to https://www.jenkins.io/donate/, but they still say "may".

**Comment by duemir** [comment]
Maybe 2 cents from Oleg as well. He created the Jenkins organization on the JetBrains marketplace and has some roles in CDF, if I remember correctly.

**Comment by timja** [comment]
cc @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Yes, we are not traders. It would be hilarious to be officially proclaimed a supplier of JetBrains, but I guess we don't want the overhead otherwise

**Comment by oleg-nenashev** [comment]
Also fyi @jglick

**Comment by MarkEWaite** [comment]
+1 from me that we are not traders.
