### ISSUE TITLE
Jenkins Jira Issue

### ISSUE THREAD

**Issue by FrankMathis** [jenkins-infra/helpdesk#3466]
### Service(s)

jenkins.io, Jira

### Summary

I made an entry in Jenkins Jira: https://issues.jenkins.io/browse/JENKINS-70854
 
Accidentally, I entered links to an internal system of our company. I removed the links but of course they are still visible in the issue’s history. Can you help me to remove that?

**Comment by timja** [comment]
We can delete the issue, can you confirm that's what you want?

**Comment by MarkEWaite** [comment]
Issue has been deleted.
