### ISSUE TITLE
The test execution runs in headless mode for the second user

### ISSUE THREAD

**Issue by sgogolev** [jenkins-infra/helpdesk#3467]
### Service(s)

Accounts, jenkins.io

### Summary

Hi!
We have one instance of Jenkins installed on the remote machine.
it's installed under another user's account (User 1). We both have admin rights to the machine, and we both can access Jenkins on that machine (under different accounts).
When the execution is in progress (no matter who triggered it) User 1 can see the actual execution (browser opens up and all the steps being executed). But User 2 (me) cannot see it. 
It's like for User 2 it's executing in headless mode.
We could not figure out why it works this way, and how we can make the execution visible for both users.

**Comment by sgogolev** [comment]
Also when User 2 (me) tried to start Jenkins from my user we got the attached error.
![jenkinsError](https://user-images.githubusercontent.com/100877499/227646536-0a17efec-70cf-49af-93a9-48aafe10f86b.jpg)

**Comment by dduportal** [comment]
Hi @sgogolev , this issue tracker is dedicated to the Jenkins public infrastructure (e.g. the websites `*.jenkins.io`).

Your question is related to a Jenkins setup on your own infrastructure: you should ask your question in the community.jenkins.io forum to get (broader) help, or join the Gitter `jenkins/jenkins` channel in https://www.jenkins.io/chat/.

I'm going to close this issue with the stayus "Not planned" for this reason.
