### ISSUE TITLE
Add additional maintainer for the Gradle plugin

### ISSUE THREAD

**Issue by welandaz** [jenkins-infra/helpdesk#3469]
### GitHub repositories

https://github.com/jenkinsci/gradle-plugin

### GitHub users to have permission

https://github.com/alextu

### Permission level

Admin

### Justification

We'd like to add one more person to help us develop and maintain the plugin (similar to the ones [added here](https://github.com/jenkins-infra/helpdesk/issues/3147))

Once they are added on Github to the [gradle-plugin Developers](https://github.com/orgs/jenkinsci/teams/gradle-plugin-developers) groups, I can open a PR to the https://github.com/jenkins-infra/repository-permissions-updater/ such that they can also release new versions of the plugin.

**Comment by NotMyFault** [comment]
I sent them an invitation to the repository team.
