### ISSUE TITLE
[trusted.ci,cert.ci] Add terraform roles and permission for azure on trusted.ci and cert.ci agent resources

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3470]
### Service(s)

cert.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

as done with https://github.com/jenkins-infra/azure/pull/308 for infra.ci and others ... cherry pick roles and permission on 

- [x] trusted.ci
- [x] cert.ci

**Comment by dduportal** [comment]
Reporting for trusted.ci.jenkins.io:

- Agent resource group imported in https://github.com/jenkins-infra/azure/pull/316. No more Azure resource to be imported for this service 👍 
- Permission restricted to cover only what is needed: existing role assignement imported in https://github.com/jenkins-infra/azure/pull/315/files and restricted in https://github.com/jenkins-infra/azure/pull/317

Great job!

Next step for completion: import missing cert.ci agent resources (ref. https://github.com/jenkins-infra/azure/blob/583ce0ee1910c6026e8a7bdb4583a8246bd349d0/cert.ci.jenkins.io.tf#L22-L23)

and this task will be done 👍

**Comment by smerle33** [comment]
Reporting for cert.ci.jenkins.io last agents resources imported: 

  - Storage Account imported https://github.com/jenkins-infra/azure/pull/320
  - Virtual Network AND Subnet imported https://github.com/jenkins-infra/azure-net/pull/57
