### ISSUE TITLE
Update changelog generator bot

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3472]
### Service(s)

GitHub

### Summary

Hey,

I made some modifications to the [core-changelog-generator](https://github.com/jenkinsci/core-changelog-generator) today, to address a proposal made by @kmartens27 to facilitate changelog generation.

Now I wonder where the bot operates from. I couldn't find helm charts or resource definitions within the k8s management repo.

I doubt cutting a release through GH does anything, given the repository itself doesn't have a Jenkinsfile, calls `buildDockerAndPublishImage` or distributes the Dockerfile in similar ways.

Does anyone know what to do to update the bot?

**Comment by timja** [comment]
It’s a GitHub action in the jenkinsci/Jenkins repo

**Comment by NotMyFault** [comment]
Oic, it runs the workflow runs the plain bash script.
