### ISSUE TITLE
Accounts shows locked status 

### ISSUE THREAD

**Issue by nikhil-dabhade** [jenkins-infra/helpdesk#3473]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

When trying to login to https://repo.jenkins-ci.org/ui/login/ with the credentials that we used last time (about 2 years ago), it shows the following error message 
"Login has failed. Due to Incorrect username/password or locked user."

The forgot password page shows the following message:
"The specified user is not permitted to reset his password."

It most likely might be the case that the account is locked due to inactivity in the past 2 years.
I did not find any link to unlock the account so I am raising this support case. 

User IDs: 
aws_device_farm_jenkins
and
nikdabn

Both these accounts are listed correctly in the repository permissions updater yaml file for AWS Device Farm plugin 
https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-aws-device-farm.yml 

Ask:
1. Can we get these accounts unlocked?
2. If these accounts are not locked, why are they not able to login?

### jenkins.io account username

aws_device_farm_jenkins

### jenkins.io account email

aws-device-farm-jenkins@amazon.com

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/ui/login/

**Comment by dduportal** [comment]
Hi @nikhil-dabhade , you have tto use accounts.jenkins.io to reset the account password.

Let us know if it works for you?

**Comment by dduportal** [comment]
Hi @nikhil-dabhade , were you able to use accounts.jenkins.io to reset the account password?

**Comment by nikhil-dabhade** [comment]
Hi @dduportal Sorry for the delay in my reply. Checking on this now.

**Comment by nikhil-dabhade** [comment]
That seemed to work. Thank you for the help :)

**Comment by dduportal** [comment]
Good to hear, thanks for the feedback! I’m gonna proceed and close this issue.

feel free to reopen if it does not work!
