### ISSUE TITLE
miss

### ISSUE THREAD

**Issue by sevoman-fbc** [jenkins-infra/helpdesk#3477]
### Type(s) of account issue

I've lost my password

### Summary

  Hi i can't access my Jenkins  account neither my password and  username nor working What could be the issue ?Can you help me to  figure out please 

Thanks!

Seval

### jenkins.io account username

Sevalim@yahoo.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @sevoman-fbc , there isn't any account associated with this email in our database (for jenkins.io public websites).

You might have used another email maybe?

**Comment by sevoman-fbc** [comment]
Hi there 
Thank you for quick respond i tried every possibility I have but didn’t work .I may need to open an account again ..
Thanks !Seval




 

 
 

    On Thursday, March 30, 2023 at 04:28:17 PM GMT+1, Damien Duportal ***@***.***> wrote:  
 
 


Hi @sevoman-fbc , there isn't any account associated with this email in our database (for jenkins.io public websites).

You might have used another email maybe?

**Comment by dduportal** [comment]
Hello @sevoman-fbc , were you able to fix your problem?

**Comment by sevoman-fbc** [comment]
Hi  there , 

Thank you for asking but no i couldn't fix it can you help to  me figure out i can not recover my password as well .

Thanks !





On Friday, March 31, 2023 at 06:33:15 PM GMT+1, Damien Duportal ***@***.***> wrote: 







Hello @sevoman-fbc , were you able to fix your problem?

**Comment by dduportal** [comment]
You have to create a new account with the yahoo email here and a new username, OR check the email you used when creating the current account (which is different than this one).

**Comment by sevoman-fbc** [comment]
Hi 
Thank you for your help I will do whichever one works.
Thanks!Seval



 

 
 

    On Friday, March 31, 2023 at 08:16:45 PM GMT+1, Damien Duportal ***@***.***> wrote:  
 
 


You have to create a new account with the yahoo email here and a new username, OR check the email you used when creating the current account (which is different than this one).

**Comment by dduportal** [comment]
Closing the issue as no more actions are required by the Jenkins infrastructure team: it's upt to you to create your account or access the correct email account.
