### ISSUE TITLE
Delete my demo account(s)

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3480]
### Type(s) of account issue

I want my account to be deleted

### Summary

My demo account called `dummynotmyfault` is no longer needed and can be deleted by now.

### jenkins.io account username

dummynotmyfault

### jenkins.io account email

The same one like on my GH profile

### Which URL are you trying to login at?

https://accounts.jenkins.io/

**Comment by lemeurherve** [comment]
Deleted!
