### ISSUE TITLE
Add https://github.com/jenkinsci/coverage-model to ci.jenkins.io

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#3483]
### Service(s)

ci.jenkins.io

### Summary

Can someone please add my project https://github.com/jenkinsci/coverage-model to ci.jenkins.io (plugins folder in a similar way to analysis-model)?

Since it does not end with suffix -plugin, it seems to be not be picked up by the repository scanner.

See also https://github.com/jenkins-infra/repository-permissions-updater/issues/3182

**Comment by dduportal** [comment]
- ci.jenkins.io set in "shutdown mode"
- starting the configuration update

**Comment by dduportal** [comment]
- Removed "shutdown mode"
- Scan in progress (will take some time)

**Comment by dduportal** [comment]
`17:32:08 Jenkins-Imposed API Limiter: Current quota for Github API usage has 624 remaining (1 over budget). Next quota of 12500 in 31 min. Sleeping until reset.`

**Comment by dduportal** [comment]
Finished with success (and a huge scanning queue :D ) : https://ci.jenkins.io/job/Plugins/job/coverage-model/
