### ISSUE TITLE
Add Launchable to agents

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3484]
Capturing the discussion from https://github.com/jenkins-infra/pipeline-library/pull/630#issuecomment-1489732588 for the backlog.

This is not a blocker for me at present, nor is it a high priority. The Launchable prototype may or may not become productized. This would only become a priority if it is productized. That having been said, the request is modest, so if it is convenient to add this package this while testing some other change, we would welcome it, even during the prototype phase.

To run Launchable, a PyPI package must be installed on agents. This is possible on current (container and VM-based) Linux agents with virtual environments, but it is not possible on current (container and VM-based) Windows agents because they do not have Python installed. Additionally, installing the package via a virtual environment adds some fragility (i.e., exposure to PyPI going down) and complexity (having to invoke the package from the virtual environment rather than merely running the command). Installing Python and the Launchable PyPI package on all agents would simplify consumers and enable the Launchable step recently added to `pipeline-library` to be drastically simplified (if not deleted entirely).

**Comment by basil** [comment]
Note that I will have an immediate use case for when Launchable is available on Windows container agents, as I intend to use Launchable to decrease the 6-hour long Windows core builds to a maximum of 90 minutes. I already have written the code to do this but I can't start testing it until Launchable is available on Windows container agents.

**Comment by lemeurherve** [comment]
Currently working on the installation of Launchable in the docker-inbound-agent Windows image, work in progress, I'll update this issue as soon as it's ready.

**Comment by lemeurherve** [comment]
With https://github.com/jenkins-infra/packer-images/pull/605 & https://github.com/jenkins-infra/docker-inbound-agents/pull/71 Launchable is intalled on all agents (Linux & Windows)

The pipeline library has been updated accordingly in https://github.com/jenkins-infra/pipeline-library/pull/653

**Comment by lemeurherve** [comment]
@basil would you like I open pull requests on core/bom/ath to remove `launchable.install` calls and activate it on Windows, or will you take care of it yourself?

**Comment by basil** [comment]
@lemeurherve This works for me:

```groovy
node('maven-17-windows') {
    withCredentials([string(credentialsId: 'launchable-jenkins-jenkins', variable: 'LAUNCHABLE_TOKEN')]) {
        bat 'python -m pip list && python -m launchable verify'
    }
}
```

This also works for me:

```groovy
node('maven-17-windows') {
    bat 'python -m venv launchable'
    bat 'launchable\\Scripts\\pip.exe --require-virtualenv --no-cache-dir install -U launchable'
    withCredentials([string(credentialsId: 'launchable-jenkins-jenkins', variable: 'LAUNCHABLE_TOKEN')]) {
        bat 'launchable\\Scripts\\launchable.exe verify'
    }
}
```

However, this does not work for me:

```
node('maven-17-windows') {
    withCredentials([string(credentialsId: 'launchable-jenkins-jenkins', variable: 'LAUNCHABLE_TOKEN')]) {
        bat 'python -m pip list && dir C:\\tools\\python\\Scripts && C:\\tools\\python\\Scripts\\launchable.exe verify'
    }
}
```

Rather, it exits 1 without printing any output. I wonder if the cause is that the `.exe` stubs are created in Windows Server rather than Nano Server when building the container image. The `pip` installation in the above example takes place on Nano Server and works, while the `pip` installation in https://github.com/jenkins-infra/docker-inbound-agents/blob/main/maven/jdk17/Dockerfile.nanoserver takes place in Windows Server and the resulting `.exe` stubs do not work on Nano Server. I wonder if this could be fixed by running `pip` a few lines later in the `Dockerfile`, inside the Nano Server image.

**Comment by lemeurherve** [comment]
@basil thanks for the suggestion about running launchable installation later, that was it!
Implemented in https://github.com/jenkins-infra/docker-inbound-agents/pull/83 and deployed with https://github.com/jenkins-infra/jenkins-infra/pull/2845

Confirmed in https://ci.jenkins.io/job/Plugins/job/text-finder-plugin/job/PR-172/25/console

<details>
<summary>Details</summary>

Pipeline:
```
node('maven-17-windows') {
    withCredentials([string(credentialsId: 'launchable-jenkins-jenkins', variable: 'LAUNCHABLE_TOKEN')]) {
        bat 'launchable.exe verify'
    }
}
```

Logs:
```
 C:\Jenkins\workspace\lugins_text-finder-plugin_PR-172>launchable.exe verify 
 Organization: 'jenkins'
 Workspace: 'jenkins'
 Proxy: None
 Platform: 'Windows-10-10.0.17763-SP0'
 Python version: '3.11.3'
 Java command: 'java'
 launchable version: '1.64.1'
 Your CLI configuration is successfully verified 🎉
```

</details>
