### ISSUE TITLE
Migrate trusted.ci.jenkins.io from AWS to Azure

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3486]
### Service(s)

trusted.ci.jenkins.io

### Summary

The service trusted.ci.jenkins.io should be migrated to Azure for centralized management and cost savings.

It's composed of 3 VMs in AWS EC2, managed by puppet:

- 1 "bounce" VM used an SSH bastion to reach the private network
- 1 "controller" VM hosting trusted.ci.jenkins.io in a private network
- 1 permanent agent with a 1 Tb data disk used to host the update center caching (to ensure fast builds of the index) with hard links support (also in the private network)

Migration plan to be defined more precisely as a first step:

- Which resource groups (alread have one for ephemeral Azure VM agents, need a separated one for the permanent agent, and another one for the controller and its network)
  - Why different resource groups? Because if we apply [locks](https://github.com/jenkins-infra/helpdesk/issues/3479) to the critical resource groups, then splitting make sense: the VM or data disk of trusted.ci controller should not be critical (we can rebuild a new VM with Terraform + Puppet, and the data of the datadisk should be backuped somewhere else), while the permanent agent is critical (caching) for update center performances.
- Which base OS (ubuntu 22.04)?
- Which migration order?

**Comment by smerle33** [comment]
To be completed and ordered : 

- [ ] create new resource groups as code for controller and another one for permanent agent (with cache)
- [ ] create 2 new VMs from 22.04 one in each group
- [ ] check if we need a bounce or if we can use the VPN
- [ ] install all tools as code on each VM
- [ ] rsync from source to destination (with timer)
- [ ] import jobs on the controller, but without the agents definition (test mode)
- [ ] add the permanent agent and try one job (need to prepare the possible impact on production)
- [ ] move the DNS to the new IP of the controller

**Comment by smerle33** [comment]
Network address plan proposal : 
one /24 per subnet within a dedicated virtual network :

vnet : 10.252.0.0/21 (meaning from 10.252.0.0 to 10.252.7.255)
  --> subnet 10.252.0.0/24 for controller (meaning from 10.252.0.0 to 10.252.0.255)
  --> subnet 10.252.1.0/24 for ephemeral agents (meaning from 10.252.1.0 to 10.252.1.255)
  --> subnet 10.252.2.0/24 for permanent agents (meaning from 10.252.2.0 to 10.252.2.255)

leaving 5 /24 to play with afterward

**Comment by lemeurherve** [comment]
Your plan looks good to me.

**Comment by smerle33** [comment]
- as [azurerm_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine)  has been superseded by `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine`, I plan to use azurerm_linux_virtual_machine : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine

- the new VMs will need an admin_ssh_key, differents from the ones that will be installed by puppet, this can be provided by the terraform resource tls_private_key or generated on our machine and statically set for the public part within terraform (the private key remaining within a secured vault).
  As terraform provide this warning : 
     `The private key generated by this resource will be stored unencrypted in your Terraform state file. Use of this resource for production deployments is not recommended. Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.`

      I propose to generate the keys myself and store it in a secure vault.

**Comment by timja** [comment]
Do we really need the bounce VM in Azure given we have a VPN?

**Comment by dduportal** [comment]
> Do we really need the bounce VM in Azure given we have a VPN?

The trusted.ci.jenkins.io is in another network (absolute separation) from the private or public networks, hence the bounce VM.
We could peer networks, but that mean less physical separation.

**Comment by smerle33** [comment]
we can use one RSA key pair for the 3 VMs or one by VM ... for my point of view, one is enough as if it get pawned each VM can reach the other 2 so same result.

**Comment by dduportal** [comment]
> we can use one RSA key pair for the 3 VMs or one by VM ... for my point of view, one is enough as if it get pawned each VM can reach the other 2 so same result.

+1 with this choice, but I disagree with your risk assessment:

- The (shared) private key allows to access the VMs with the initial technical administrator user for the initial bootstrap. It should **only** be used for this, and the private key should , then, be locked in vault and NOT be used at all by any administrator once bootstrapped
- If the (shared) private key is pwned, then it means the attacked was able to hijack it either on an admin machine or in the vault => in that case there is nothing we can do about this
- But the fact that VMs can reach each other is not a reason: there is RBAC in Linux :)

**Comment by smerle33** [comment]
reducing the PR scope to iterate more often. 
dealing with each VM at a time : https://github.com/jenkins-infra/azure/pull/333

**Comment by smerle33** [comment]
TODO : change the rule `"allow_ssh_from_admins_to_bounce"` or remove it as per https://github.com/jenkins-infra/azure/pull/334#discussion_r1179955821

**Comment by smerle33** [comment]
This PR https://github.com/jenkins-infra/azure/pull/337 have been merged but fail on main because of 
```
Error: creating Network Interface: (Name "trusted-ci-controller" / Resource Group "jenkinsinfra-trusted-ci-controller"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateIPAddressInReservedRange" Message="Private static IP address 10.252.0.1 falls within reserved IP range of subnet prefix 10.252.0.0/24." Details=[]
```

I will switch to dynamic IP with a DNS record to solve this tomorrow (May 3rd 2023)

**Comment by dduportal** [comment]
Updated the issue description to add the "why" of using different resource groups

**Comment by dduportal** [comment]
Update:

- Security groups are now all set up in the controller subnet: bounce is able to reach (with SSH) the controller and agents
- Puppet agent are enabled, bound and the VMs are under puppet management

Next steps:

- Security groups need to be restricted to frorbid access from the agent to the controller subnet machines
- The puppet agent run on controller fails with an error `Could not find a suitable provider for cron`
- Shell (bash) sessions in SSH shows the warning `-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)` (assess and fix if possible)
- Running an `apt update` command shows the warning `W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.` (assess and fix if possible)

**Comment by dduportal** [comment]
Update:

- The `cron` error is now fixed by https://github.com/jenkins-infra/jenkins-infra/pull/2842
- Security group for SSH are now ok: tested the following scenarii:
    - bounce -> controller ✅
    - bounce -> agent ✅
    - bounce -> ephemeral agent ✅
    - controller -> agent ✅
    - controller -> ephemeral agent ✅
    - agent - bounce 🔒
    - agent - controller 🔒
    - ephemeral agent - controller 🔒
    - ephemeral agent - bounce 🔒
    - controller - bounce 🔒

**Comment by dduportal** [comment]
Update:

Network accesses for bounce:

- `apt update` ✅
- puppet agent ✅
- HTTP to trusted ✅
- SSH to github.com 🔒

Network accesses for controller:

- `apt update` ✅
- puppet agent ✅
- SSH to github.com 🔒

Access to controller with the following SSH config ✅ 

```
Host bounce.trusted.ci.jenkins.io
    HostName <redacted>
    User dduportal

Host controller.trusted.ci.jenkins.io
    HostName trusted.ci.jenkins.io
    User dduportal
    ProxyCommand ssh -W %h:%p bounce.trusted.ci.jenkins.io
    ForwardAgent yes
    RequestTTY yes
    LocalForward 1443 127.0.0.1:443

Host agent.trusted.ci.jenkins.io
    HostName agent.trusted.ci.jenkins.io
    User dduportal
    ProxyCommand ssh -W %h:%p bounce.trusted.ci.jenkins.io
    ForwardAgent yes
    RequestTTY yes
```


Next step: restricitng rules for the permanent agent

**Comment by dduportal** [comment]
Update:

- Data disk mounted on both controller.trusted.ci.jenkins.io and agent.trusted.ci.jenkins.io
- Puppet agents stopped and disabled on both machines
- Data migration of `/var/lib/jenkins` started in a background `screen` from trusted.ci.jenkins.io to controller.trusted.ci.jenkins.io
- Data migration of `/home/jenkins` started in a background `screen` from trusted-agent-1 (with the `-H` option for hardlinks support) and agent.trusted.ci.jenkins.io

**Comment by dduportal** [comment]
Update:
- Data transfer done this week-end (4Mb/s for agent, 24 Mb/s for controller)
- Opened https://github.com/jenkins-infra/azure/pull/370 to cleanup namings and code: ready to taint VMs

Next steps: plan for effective next milestone

**Comment by dduportal** [comment]
- runbook updated: https://github.com/jenkins-infra/runbooks/commit/1e5a4b8971abaeac249b3ae4a9547a5747c52893
- Stopped AWS VMs
- DNS record for bounce: https://github.com/jenkins-infra/azure/pull/383
- Puppet fixups:
  - Correct Tests: https://github.com/jenkins-infra/jenkins-infra/pull/2886
  - Track Docker CE for the new Ubuntu Jammy: https://github.com/jenkins-infra/jenkins-infra/pull/2887 and https://github.com/jenkins-infra/jenkins-infra/pull/2888

**Comment by dduportal** [comment]
Next steps:

- Optimize the ephemeral agent instances (to use ephemeral disk, like we did for ci.jenkins.io)
- Fine tune the NSG in the agent subnets
