### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by swetumrug** [jenkins-infra/helpdesk#3493]
### Type(s) of account issue

I've been blocked by the anti-spam system

### jenkins.io account username

swetu

### jenkins.io account email

mahaswetathakkar@gmail.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/doSignup

**Comment by dduportal** [comment]
Hi @swetumrug , your account was created, you should have received an email with instructions to log-in.

I'm closing the issue: feel free to reopen if you do not receive any email.
