### ISSUE TITLE
Can't reset Jira account password

### ISSUE THREAD

**Issue by chorrell** [jenkins-infra/helpdesk#3499]
### Type(s) of account issue

I didn't receive any email

### Summary

Hi!

I'm trying to reset my jira password for the account chorrell. I seem to be lock out? I'm not getting the password reset emails. 

### jenkins.io account username

chorrell

### jenkins.io account email

christopher@horrell.ca

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @chorrell , your user account was marked as "locked" and the email field was reset.
I am not sure why, but it was unlocked and updated: you should be able to reset your password now: let us know

**Comment by chorrell** [comment]
Great, thank you!

I was able to reset my password :)
