### ISSUE TITLE
CodeSonar plugin Jira component lead reassignment

### ISSUE THREAD

**Issue by gt-dbechtold** [jenkins-infra/helpdesk#3503]
### Service(s)

Jira

### Summary

Development of the CodeSonar plugin for Jenkins has been transitioned to GrammaTech, Inc., and I am the new point of contact.  The previous developer, Eficode, is marked as the "lead" for the `codesonar-plugin` Jira component.  We would like to change the "lead" to `gt_dbechtold` (which is my Jenkins user account name).  `Eficode` should not be the default contact for issues related to the CodeSonar plugin.

Eficode still has permissions to modify the plugin, but most code updates and all support will be coming from myself or (eventually) other developers from GrammaTech.  In particular, when users report Jira issues with the CodeSonar plugin from plugins.jenkins.io/codesonar, the issues should be assigned to me by default.

### Reproduction steps

1. Go to https://plugins.jenkins.io/codesonar
2. Click the [Report an issue (Jira)](https://www.jenkins.io/participate/report-issue/redirect/#20630) hyperlink

**Comment by NotMyFault** [comment]
Changed.
