### ISSUE TITLE
Jira account locked

### ISSUE THREAD

**Issue by jhansche** [jenkins-infra/helpdesk#3504]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I've reset my password multiple times. I'm able to log in on accounts.jenkins.io when the password is initially reset, but then trying to login on issues.jenkins.io results in:

> Sorry, your userid is required to answer a CAPTCHA question correctly.

But no matter how many times I refresh the CAPTCHA or enter what I am 99% sure is the exact CAPTCHA text, it always shows the same error. This started within the past couple of days.

### jenkins.io account username

jhansche

### jenkins.io account email

jhansche@themeetgroup.com

### Which URL are you trying to login at?

https://issues.jenkins.io/secure/Dashboard.jspa

**Comment by dduportal** [comment]
- Your account was marked as "unverified email" in (admin.)accounts.jenkins.io. It looks like you changed your email.
- It's confirmed on JIRA: the email associated to your `jhansche` (local cached) account was different.

I've updated the fields: can you retry again?

**Comment by jhansche** [comment]
Yes, that lets me log in now.

Do I need to confirm my email address still? I tried searching my inbox for "jenkins.io" and "confirm" but I don't see any email asking me to do so.

I don't recall when I changed it here, but the domain was likely changed due to a corporate change (meetme -> themeetgroup). The old one still works by forwarding, which is why I didn't notice it.

**Comment by dduportal** [comment]
> Do I need to confirm my email address still? I tried searching my inbox for "jenkins.io" and "confirm" but I don't see any email asking me to do so.

No need, I set up your account to "verified".

**Comment by jhansche** [comment]
Great, thank you!
