### ISSUE TITLE
Official newer docker image manifest's incorrect due to missing manifest.v2

### ISSUE THREAD

**Issue by nichtprivat** [jenkins-infra/helpdesk#3505]
### Service(s)

Docker Hub

### Summary

Hi,

by running `docker manifest inspect on jenkins:2.361.3-lts-jdk11`, I got an 

> application/vnd.docker.distribution.manifest.v2+json

, which is correct.

For checking this with one of the latest images like 2.387.2-lts-jdk11:

> unsupported manifest media type and no default available: application/vnd.oci.image.manifest.v1+json

afaik oci/v1 has been removed by docker.

Why is this a problem?
By running for e.g. an RHEL7 LTS (which is supported until 2024+) it's not longer possible to pull the images:

`docker pull ...2.387.2-lts-jdk11` Error:   

> missing signature key

### Reproduction steps

1) Pull the image with a current docker version
`docker pull jenkins/jenkins:lts-jdk11`
2) Then inspect the image: `docker manifest inspect jenkins/jenkins:lts-jdk11`, receive 

> unsupported manifest media type and no default available: application/vnd.oci.image.manifest.v1+json

3) compare this with an older image like  `docker pull jenkins/jenkins:2.361.3-lts-jdk11`, by checking the image via `docker manifest inspect jenkins/jenkins:2.361.3-lts-jdk11`

4) Login to a RHEL 7 LTS server:
```
cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

```
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jan  7 13:15:46 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7_9.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Fri Jan  7 13:15:46 2022
 OS/Arch:         linux/amd64
 Experimental:    false
```

Try to pull the image, receive the error:

```
docker pull jenkins/jenkins:2.387.2-lts-jdk11
Trying to pull repository  docker.io/jenkins/jenkins ...
missing signature key

```

**Comment by dduportal** [comment]
Hi @nichtprivat , your issue is the same as https://github.com/jenkinsci/docker/issues/1565.

Docker 1.13 is so old that it's not even mentionned anymore in the usual EOL website (https://endoflife.date/docker-engine).
If you upgrade your Docker Engine (following the official supported way by Docker - https://docs.docker.com/engine/install/centos/ unkless you use `s390x` then it would be https://docs.docker.com/engine/install/rhel/).

**Comment by dduportal** [comment]
I'm closing this issue for the following reason:

This issue tracker is only related to the Jenkins infrastructure, not the Jenkins assets (such as Docker images) so it is out of scope:

Official issue tracker for Jenkins Docker image (controller) is at https://github.com/jenkinsci/docker/issues

**Comment by dduportal** [comment]
Please note that the `docker manifest inspect` only shows the manifest has stored in the local Docker engine: that's why switching to a recent Docker Engine will help.

Docker 18.06 introduced the support of OCI v1 inbter-operable manifests (ref. https://docs.docker.com/engine/release-notes/18.06/#18060-ce => section "Runtime" -> https://github.com/docker/engine/pull/4).

It is the manifest format used by [Docker Buildx](https://github.com/docker/buildx) when building multi-platform images (at least since 0.10.0).

**Comment by MarkEWaite** [comment]
As a further note, the Jenkins project only support operating systems that are also supported by the operating system provider.  That means that on or before June 30, 2024, the Jenkins project will stop supporting Red Hat Enterprise Linux 7 and its derivatives (like CentOS 7, Oracle Linux 7, Scientific Linux 7).  You're encouraged to plan your move away from Red Hat Enterprise Linux 7 as soon as you can.

**Comment by lbarnkow** [comment]
As it stands right now, the Red Hat maintained (and supported) from the Red Hat Repositories is not supported by Jenkins, although you claim you'll support RHEL7 (and its derivatives) until June 30, 2024. I understand that this docker version is ancient, but we'll get no commercial support from Red Hat when switching to the Docker Community Edition. It'd be nice to have clearer communication: either you support RHEL7 or you don't. Either way is fine, but we can't have both. :)

**Comment by dduportal** [comment]
You can absolutely execute Jenkins on RHEL7 and it will be supported until June 30 2024, using the official package for RHEL/CentOS: https://pkg.jenkins.io/redhat-stable/.

You can also run Jenkins inside podman, or any OCI container runtime, in RHEL7 as well.
So you have options officially supported options.

Supporting an OS does not always mean supporting every exotic kinds of combination in its ecosystem.

**Comment by MarkEWaite** [comment]
Thanks for the information @lbarnkow .  I'll be happy to use that in my proposal to end all support of RHEL 7 in the Jenkins project.  That proposal hasn't been written yet and probably won't accelerate the end of life to anything much sooner than late 2023, but the sooner we officially end support, the sooner we can remove the workarounds that are associated with it.

The `systemd` based rpm Jenkins install package does not support RHEL7 today.

Based on your report, the `docker` provided with RHEL 7 does not support the Jenkins container images today.
