### ISSUE TITLE
cant create account

### ISSUE THREAD

**Issue by camrdjow** [jenkins-infra/helpdesk#3506]
### Type(s) of account issue

I didn't receive any email

### Summary

Hi 

I have registered but I do not receive any email from you, to confirm my account and registration. Please help me with this, the email I used is camran.djoweini@tele2.com

### jenkins.io account email

camran.djoweini@tele2.com

### Which URL are you trying to login at?

account.jenkins.io/

**Comment by dduportal** [comment]
Hi @camrdjow , I've triggered a password reset, let us know if you received the email?

**Comment by dduportal** [comment]
Hi @camrdjow , we are looking into it. It sounds like the same kind of issue than https://github.com/jenkins-infra/helpdesk/issues/3478

**Comment by camrdjow** [comment]
Hi,

That's good to hear, thank you.

/Camran

**Comment by lemeurherve** [comment]
Hi @camrdjow, I've changed the mail provider and sent you a password reset mail, seen as "delivered" in the logs.

Could you check if you received it please?

**Comment by camrdjow** [comment]
Hi,
No, unfortunately I still have not received anything.

/Camran

**Comment by camrdjow** [comment]
Hi,

Still nothing.

/Camran

**Comment by camrdjow** [comment]
Hi,

I see now that several emails from Jenkins for account activation have been blocked. However, the latest one I see was sent on the 13th of April, so it has expired, and I cannot use it to activate my account.

Perhaps it's best if you delete my account and I try creating it again.

Best regards,
/Camran

**Comment by lemeurherve** [comment]
If that doesn't work I'll delete your account so you can recreate it.

**Comment by camrdjow** [comment]
Hi,

Yes please delete my account so I can recreate it.

/Camran

**Comment by lemeurherve** [comment]
@camrdjow were you able to recreate a Jenkins account?

**Comment by camrdjow** [comment]
Hi,

I recreated my account but unfortunately, I receive no email, not even in the spam filter folder.

Do you in your systems not have a copy of the email? If so, could you not manually forward it to me in this conversation?

BR,
/Camran

**Comment by lemeurherve** [comment]
@camrdjow I see your inscription email as delivered at 9h37m UTC

Do you mind checking again your mails?

Cf one of your previous comments:

> I see now that several emails from Jenkins for account activation have been blocked. However, the latest one I see was sent on the 13th of April, so it has expired, and I cannot use it to activate my account.

It might takes some time to be in your mailbox but there isn't any reason it wouldn't be there.

**Comment by camrdjow** [comment]
Hi,

Unfortunately I still have nothing ☹

My regular inbox has not received it, and here you can see in the ‘junk email’ folder where stuff gets stuck, the latest email from Jenkins I’ve received was on the 13th.

***@***.***
/Camran

**Comment by lemeurherve** [comment]
@camrdjow can you check with your mail administrator if our mails are blocked on your side?

Otherwise, I propose you to use another mail provider to register.

**Comment by dduportal** [comment]
Hello @camrdjow gentle ping: were you able to use another email or checking with your email domain administrators?

**Comment by dduportal** [comment]
I'm closing this issue as we get no answer back from the requester.

Please feel free to reopen if you have more informations or if you still have a problem.

**Comment by camrdjow** [comment]
Hello Damien,

Sorry for the late reply, I'm on vacation,

I just got back, and I saw the admin email I received on the 27th of April, with a temporary password, I tried using it now but it did not work. ***@***.***

Perhaps we could delete my account again, and you could try sending me another one of those emails?

This is the one I'm referring to. ***@***.***

**Comment by lemeurherve** [comment]
@camrdjow I've sent you another password reset email, please check and confirm when it's OK for you.

**Comment by camrdjow** [comment]
Hi,

No I have not received it.

/Camran

**Comment by dduportal** [comment]
Hello @camrdjow , you have to check with your email administrators as there is nothing else we can do on our own: we see the emails being sent to your email system.

Or you shall use another email domain instead if it is not a solution.

**Comment by dduportal** [comment]
Closing the issue as no answer back from user.

@camrdjow feel free to reopen if you have feedbacks from your email domain administrators
