### ISSUE TITLE
Add `NotMyFault` to Copy Editors team

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3511]
### GitHub repositories

https://github.com/orgs/jenkins-infra/teams/copy-editors

### GitHub users to have permission

@NotMyFault 

### Permission level

Maintain

### Justification

Based on the feedback and approvals in https://groups.google.com/g/jenkinsci-dev/c/HOelpsRwmz8, I'm creating this ticket to move the topic forward.

The ["Joining the teams" section](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#joining-the-teams) notes that the documentation officer chooses to include new members in the copy editors team, and Kevin approved it in the mail 🎉

**Comment by dduportal** [comment]
Done, welcome onboard ;)
