### ISSUE TITLE
Archive EOL js components

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3513]
### Service(s)

Jira

### Summary

`js-modules`, `js-builder` and `js-builder-jest` are EOL and unmaintained. We can safely archive these Jira components.

**Comment by dduportal** [comment]
<img width="1580" alt="Capture d’écran 2023-04-14 à 17 19 50" src="https://user-images.githubusercontent.com/1522731/232085682-3a0b0b20-bd81-41d6-babc-dbaddc8118ca.png">

Done ✅

**Comment by basil** [comment]
The `js-builder` component could be archived as well (same story as `js-modules`).

**Comment by NotMyFault** [comment]
> The `js-builder` component could be archived as well (same story as `js-modules`).

Oh, good catch, absolutely!

**Comment by dduportal** [comment]
`js-builder` is archived ✅ 

There is also a `js-builder-jest` component owned by Cliff Meyers with 0 issues: should I also archive it?

**Comment by NotMyFault** [comment]
> `js-builder` is archived ✅
> 
> There is also a `js-builder-jest` component owned by Cliff Meyers with 0 issues: should I also archive it?

It depends on "js-builder". Therefore, it would make sense.

**Comment by dduportal** [comment]
LGTM and done

![Capture d’écran 2023-04-14 à 19 25 54](https://user-images.githubusercontent.com/1522731/232114840-5b775ba8-c969-4e56-84da-7393eecefcae.png)
