### ISSUE TITLE
Jobs with tasks using azure upload are failing

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3516]
### Service(s)

ci.jenkins.io

### Summary

Various jobs using azure upload are failing, for example:
- https://ci.jenkins.io/job/Packaging/job/packaging/job/master/
- https://ci.jenkins.io/job/Infra/job/repository-permissions-updater/job/master/

**Comment by dduportal** [comment]
Removed the azure blob config temporarly: https://github.com/jenkins-infra/helpdesk/issues/3496#issuecomment-1509804474

**Comment by dduportal** [comment]
Closing in favor of #3496
