### ISSUE TITLE
`update_center` doesn't build because `agent-1` is offline

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3517]
### Service(s)

trusted.ci.jenkins.io

### Summary

The last time `update_center` was built successfully was April the 14th, 7:13 PM CEST. All newer builds failed because `agent-1` is offline.

**Comment by dduportal** [comment]
- The error is related to the SSH authentication, which is refused for `jenkins` user
- On the machine (trusted-agent-1), there are no `authorized_keys` (the file is empty, except the header stating it's puppet managed)
- Hotfix for the weekend:
  - Disabled puppet agent on the agent-1
  - Added manually the public key to the `jenkins` user
  - Launched a reconnection: job `update_center` is starting

**Comment by dduportal** [comment]
Fixed by https://github.com/jenkins-infra/jenkins-infra/pull/2769

Thanks for raising this @NotMyFault !
