### ISSUE TITLE
[INFRA-391] Rename automation accounts

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#352]
<p><a href="https://wiki.jenkins-ci.org/display/~ci_jenkinsci_org" class="external-link" target="_blank" rel="nofollow noopener">https://wiki.jenkins-ci.org/display/~ci_jenkinsci_org</a> <br/>
looks like Kohsuke modifying auto generated pages. Automation accounts should never be named with personal names as it confuses everybody.</p>

<p><a href="https://github.com/jenkinsci/jenkins/commit/65d02d1f6e3f89c14b542ff38639ac3a55ad09ef" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/commit/65d02d1f6e3f89c14b542ff38639ac3a55ad09ef</a><br/>
In the same way jenkins releases looks like manually released.</p>

<p>Please name bots accordingly and point their emails to infra maillist.</p>

---
<details><summary><i>Originally reported by <a title="Kanstantsin Shautsou" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=integer">integer</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-391" target="_blank">Rename automation accounts</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Bots don't have personal names any more.
