### ISSUE TITLE
Enable renovate for jenkins-infra/stories

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3522]
### Service(s)

GitHub

### Summary

renovate.json is already committed, a modification of plugin-site
Just needs it to be enabled on the app.

https://github.com/marketplace/renovate

**Comment by lemeurherve** [comment]
Renovate is already enabled for plugin-site: https://github.com/jenkins-infra/plugin-site/issues/860

Is there something else missing?

**Comment by halkeye** [comment]
![image](https://media0.giphy.com/media/a93jwI0wkWTQs/giphy.gif?cid=ecf05e47r13ptsd28uw7qhtb2wp4vg1gaekdhzq3rp6uthui&rid=giphy.gif&ct=g)
