### ISSUE TITLE
Update code-coverage plugin on ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3523]
### Service(s)

ci.jenkins.io

### Summary

Updating the code-coverage plugin to v4.3.0 unblocks https://github.com/jenkinsci/jenkins/pull/7831, see https://github.com/jenkinsci/jenkins/pull/7831#issuecomment-1511973414 for Ulli's comment.

**Comment by dduportal** [comment]
![Capture d’écran 2023-04-18 à 09 43 22](https://user-images.githubusercontent.com/1522731/232707323-cfb45d24-d789-4119-a143-2140589267da.png)

Check ✅

**Comment by lemeurherve** [comment]
FTR, this update was included in https://github.com/jenkins-infra/docker-jenkins-lts/pull/718

@dduportal's update is quicker though 😉

**Comment by dduportal** [comment]
> FTR, this update was included in https://github.com/jenkins-infra/docker-jenkins-lts/pull/718

Which is not used for ci.jenkins.io ;)

**Comment by lemeurherve** [comment]
![image](https://media0.giphy.com/media/a93jwI0wkWTQs/giphy.gif?cid=ecf05e47r13ptsd28uw7qhtb2wp4vg1gaekdhzq3rp6uthui&rid=giphy.gif&ct=g)
