### ISSUE TITLE
Install gitpod on `jenkins-infra/jenkins.io`

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3524]
### Service(s)

GitHub

### Summary

[Installing](https://github.com/apps/gitpod-io/installations/new) gitpod on the jenkins.io makes use of my changes in https://github.com/jenkins-infra/jenkins.io/commit/c23ef3e6ab6a12760c12edd786aa05bc9bc924de.
This is the setup we're already using in core for PRs, allowing the bot to add a badge to the PR to open it in gitpod.

I requested the installation on the repository through GitHub.

**Comment by dduportal** [comment]
Should be done :)
