### ISSUE TITLE
add @rsandell to the ldap plugin group

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#3531]
### GitHub repositories

https://github.com/jenkinsci/ldap-plugin

### GitHub users to have permission

@rsandell

### Permission level

Admin

### Justification

@rsandell is currently explicitly listed in the [permissions for the plugin](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-ldap.yml#L11) however @timja [notes](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-ldap.yml#L11) that group `@jenkinsci/ldap-plugin-developers` is empty.

whilst Bobby is a member via `cloudbees-company-developers` it is normal for explicitly listed users to be in the actual esp as this group normally has some higher permissions like admin.

(unrelated the CODEOWNERS needs to change too - and the cloudbees-company-devs does not have admin which is currently acceptable!)

**Comment by timja** [comment]
I've added Bobby to the ldap plugin developers group
