### ISSUE TITLE
Jobs failing due to `repo.maven.apache.org: Name or service not known`

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3532]
### Service(s)

ci.jenkins.io

### Summary

At 2023-04-20T02:04:24.834Z the master branch of the bom repository failed to build with the message:

```
Could not transfer artifact io.jenkins.tools.incrementals:git-changelist-maven-extension:pom:1.5 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known
```

The message happened when trying to resolve the maven extension `io.jenkins.tools.incrementals:git-changelist-maven-extension:1.5` as reported in the [bom#1628 console output](https://ci.jenkins.io/job/Tools/job/bom/job/master/1628/).  The console output is 27 MB, so you may want to [download it as text](https://ci.jenkins.io/job/Tools/job/bom/job/master/1628/consoleText) rather than viewing it in the browser.

### Reproduction steps

1. Run Jenkins bom build
2. Confirm the repository can be resolved

**Comment by dduportal** [comment]
Sounds like an issue (to be confirmed) happened on their DNS record: https://twitter.com/olamy/status/1648842893271109633 (cc @olamy for info)

**Comment by dduportal** [comment]
=> sounds related, at least on the timestamps (11 hours ago)

**Comment by dduportal** [comment]
=> Build https://ci.jenkins.io/job/Tools/job/bom/job/master/1629/ started to verify that everything is back to normal

**Comment by MarkEWaite** [comment]
Thanks very much!
