### ISSUE TITLE
Not able to create an account for jenkins

### ISSUE THREAD

**Issue by nikerathi1** [jenkins-infra/helpdesk#3533]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hi,

I would like to create an account for Jenkins, it's not creating one for me.

Preffered user name: nikerathi1
Email: nikerathi1@gmail.com

Thank You,
Nikhil Rathi

### jenkins.io account username

nikerathi1

### jenkins.io account email

nikerathi1@gmail.com

### Which URL are you trying to login at?

https://issues.jenkins.io/login.jsp

**Comment by dduportal** [comment]
Hi @nikerathi1 , you have to use https:/:accounts.jenkins.io to create your account for issues.jenkins.io.

**Comment by nikerathi1** [comment]
Thanks, it's working now!
