### ISSUE TITLE
org.tmatesoft.svn.core.SVNException: svn: E175002: Processing REPORT request response failed: XML document structures must start and end within the same entity. (/scm/svn/SCM_Tools/!svn/vcc/default)  svn: E175002: REPORT request failed on '/scm/svn/SCM_Tools/!svn/vcc/default'

### ISSUE THREAD

**Issue by saquibtmf** [jenkins-infra/helpdesk#3537]
### Service(s)

Other

### Summary

While performing an SVN checkout, I get the following error
org.tmatesoft.svn.core.SVNException: svn: E175002: Processing REPORT request response failed: XML document structures must start and end within the same entity. (/scm/svn/SCM_Tools/!svn/vcc/default)  svn: E175002: REPORT request failed on '/scm/svn/SCM_Tools/!svn/vcc/default'

And, yes I know that this is an old error and there are solutions available but I have tried everything and it is still the same error.

Here are the things I tried and failed

-Dsvnkit.http.methods=Basic
-Dsvnkit.http.spoolDirectory=/tmp/fisheye/spooldirectory
-Dsvnkit.http.sslProtocols=SSLv3
-Dsvnkit.http.sslProtocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2
-Dhudson.spool-svn=true

Updated the svn client on machine (TortoiseSvn->1.14.5)

All of these and still the error.

Jenkins version: 2.387.2 (Latest LTS)
subversion-plugin version: 2.17.1 (Latest Available)

I now have no ideas what else to do.

Anyone got any ideas?

### Reproduction steps

1. Add a svn repo to checkout using the subversion plugin
2. Build the job
3. Job build will present with these errors

**Comment by lemeurherve** [comment]
@saquibtmf this help desk is dedicated to Jenkins Infrastructure issue.

You should use community.jenkins.io or https://www.jenkins.io/chat/ to ask about general Jenkins issues.
