### ISSUE TITLE
Archive `branch-source-aged-refs-traits-plugin` Jira component

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3538]
### Service(s)

Jira

### Summary

Completes https://github.com/jenkins-infra/repository-permissions-updater/pull/3270. The maintainer moved from Jira to GitHub.

**Comment by dduportal** [comment]
👍 Components archived:

<img width="1397" alt="Capture d’écran 2023-04-24 à 13 13 47" src="https://user-images.githubusercontent.com/1522731/233980613-dd21d5d1-71c1-431f-bc59-dfbaa40b8316.png">
