### ISSUE TITLE
Migrate applications from systempool to linuxpool on privatek8s

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3540]
### Service(s)

infra.ci.jenkins.io

### Summary

as per the alert `Available disk space is below 19.753% free for aks-systempool-36786399-vmss000000-publick8s` we discovered 3 applications that need to migrate from systempool to linux pool on privatek8s: 

- [x] github-comment-ops
- [x] ircbot
- [x] rss2twitter

**Comment by lemeurherve** [comment]
The `nodeSelector` addition to these 3 bots helm chart values in https://github.com/jenkins-infra/kubernetes-management/pull/3917 rescheduled them on `linuxpool` nodes without the need for restarting them.

**Comment by dduportal** [comment]
> The `nodeSelector` addition to these 3 bots helm chart values in [jenkins-infra/kubernetes-management#3917](https://github.com/jenkins-infra/kubernetes-management/pull/3917) rescheduled them on `linuxpool` nodes without the need for restarting them.

If the pods were rescheduled, then the service were restarted ;)
