### ISSUE TITLE
Releases of cdevents plugin not published to update center

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3543]
### Service(s)

Update center

### Summary

The [cdevents plugin](https://github.com/jenkinsci/cdevents-plugin/) had its [first two releases](https://github.com/jenkinsci/cdevents-plugin/releases) April 25, 2023.  Unfortunately, those releases are not visible in the [Jenkins update center](https://updates.jenkins.io/latest/).  

The support-core plugin released after the first cdevents plugin release and before the second cdevents plugin release.  It is visible in the update center and on the [mirrors](https://updates.jenkins.io/latest/support-core.hpi?mirrorlist) as version [1274.v097a_073e7733](https://github.com/jenkinsci/support-core-plugin/releases/tag/1274.v097a_073e7733).

### Reproduction steps

1. Confirm that cdevents plugin releases have been generated as listed on the [GitHub releases page](https://github.com/jenkinsci/cdevents-plugin/releases)
2. Confirm that the cdevents plugin is not listed by its artifactId `cdevents` in the [latest update center](https://updates.jenkins.io/latest/)

**Comment by NotMyFault** [comment]
As I have pointed out in https://github.com/jenkinsci/cdevents-plugin/commit/22608f700c3e4ae7163497f31f5d4b62ee05cb70#comments before, the update center does not accept [malformed releases](https://github.com/jenkins-infra/update-center2/blob/master/src/main/java/io/jenkins/update_center/ArtifactCoordinates.java#L47-L49).

**Comment by GerMcMahon** [comment]
> As I have pointed out in [jenkinsci/cdevents-plugin@22608f7#comments](https://github.com/jenkinsci/cdevents-plugin/commit/22608f700c3e4ae7163497f31f5d4b62ee05cb70#comments) before, the update center does not accept [malformed releases](https://github.com/jenkins-infra/update-center2/blob/master/src/main/java/io/jenkins/update_center/ArtifactCoordinates.java#L47-L49).

@NotMyFault  just to confirm, the malformed release is why the plugin is not being pulled up. We can put in a fix for this

**Comment by NotMyFault** [comment]
> > As I have pointed out in [jenkinsci/cdevents-plugin@22608f7#comments](https://github.com/jenkinsci/cdevents-plugin/commit/22608f700c3e4ae7163497f31f5d4b62ee05cb70#comments) before, the update center does not accept [malformed releases](https://github.com/jenkins-infra/update-center2/blob/master/src/main/java/io/jenkins/update_center/ArtifactCoordinates.java#L47-L49).
> 
> @NotMyFault just to confirm, the malformed release is why the plugin is not being pulled up. We can put in a fix for this

Take a look at the link of "malformed releases" I put in place. This regex clause complies with our supported CD and manual release pattern, the update center picks up.

**Comment by GerMcMahon** [comment]
> > > As I have pointed out in [jenkinsci/cdevents-plugin@22608f7#comments](https://github.com/jenkinsci/cdevents-plugin/commit/22608f700c3e4ae7163497f31f5d4b62ee05cb70#comments) before, the update center does not accept [malformed releases](https://github.com/jenkins-infra/update-center2/blob/master/src/main/java/io/jenkins/update_center/ArtifactCoordinates.java#L47-L49).
> > 
> > 
> > @NotMyFault just to confirm, the malformed release is why the plugin is not being pulled up. We can put in a fix for this
> 
> Take a look at the link of "malformed releases" I put in place. This regex clause complies with our supported CD and manual release pattern, the update center picks up.
> 
> I recommend updating your release pattern to the documentation I linked before. The manually controlled prefix of `1` will work.

Hi @NotMyFault  we have pushed up a new release following the recommended version pattern. I see it now here https://updates.jenkins.io/latest/cdevents.hpi and can I assume that our changes resolved the issue? and we can expect it to be pushed out to plugins.jenkins.io in some amount of time?

**Comment by lemeurherve** [comment]
Closing this issue as resolved, thanks @NotMyFault for taking care of it!
