### ISSUE TITLE
assets.ci.jenkins.io HTTPS certificate expires 22 May 2023

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3544]
### Service(s)

ci.jenkins.io

### Summary

The SSL certificate for assets.ci.jenkins.io has a different expiration date than the SSL certificate for ci.jenkins.io.  That surprises me.

* ci.jenkins.io certificate expires July 10, 2023
* assets.ci.jenkins.io certificate expires May 21, 2023

I was not aware that we were serving content from assets.ci.jenkins.io, but if we are, then it seems important that we use a valid SSL certificate even after May 21, 2023.

### Reproduction steps

1. Open https://ci.jenkins.io in a web browser and confirm the SSL certificate expires July 10, 2023
2. Open https://assets.ci.jenkins.io in a web browser and confirm the SSL certificate expires May 21, 2023

**Comment by timja** [comment]
Assets is the resource root url, artefacts are served from there so it’s important it is renewed

**Comment by dduportal** [comment]
Renewal was successul:

```
certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/assets.ci.jenkins.io.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for assets.ci.jenkins.io

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/ci.jenkins.io.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The following certificates are not due for renewal yet:
  /etc/letsencrypt/live/ci.jenkins.io/fullchain.pem expires on 2023-07-10 (skipped)
Congratulations, all renewals succeeded: 
  /etc/letsencrypt/live/assets.ci.jenkins.io/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```


Reloaded Apache and the new expiration date is now `Tue, 25 Jul 2023 14:20:29 GMT`.

I have no clue what went wrong, I guess I messed up the renewal files the 11 of April when tinkering with certbo on machines.
Let's keep an eye on these: I'm closing (feel free to reopen if missing something orobjecting)

**Comment by MarkEWaite** [comment]
Thanks very much!  Confirmed from my side that the SSL certificate for assets.ci.jenkins.io both expire in July 2023.  

I was surprised to see that the ci.jenkins.io certificate expires July 10, 2023, while the assets.ci.jenkins.io certificate expires July 25, 2023.  I had assumed that they are the same machine and would have the same expiration date.  Maybe some caching on my computer?
