### ISSUE TITLE
The upload to the Maven repository fails with "401 Unauthorized"

### ISSUE THREAD

**Issue by lucas-im** [jenkins-infra/helpdesk#3545]
### Service(s)

Artifactory

### Summary

Plugin release fails with code 401. please help
https://github.com/jenkinsci/xcode-cloud-for-pipeline-plugin/actions/runs/4804165781/jobs/8549704490

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project xcode-cloud-for-pipeline: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:xcode-cloud-for-pipeline:pom:1.0-rc30.2627794428b_8 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/io/jenkins/plugins/xcode-cloud-for-pipeline/1.0-rc30.2627794428b_8/xcode-cloud-for-pipeline-1.0-rc30.2627794428b_8.pom, status: 401 Unauthorized -> [Help 1]

**Comment by NotMyFault** [comment]
Take a look at the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/). CD is not enabled for your plugin.
Once you enabled it, deployments will work.
