### ISSUE TITLE
Search on plugins.jenkins.io crashes on particular search strings 

### ISSUE THREAD

**Issue by GerMcMahon** [jenkins-infra/helpdesk#3547]
### Service(s)

plugins.jenkins.io

### Summary

We recently contributed a new plugin and I can see the plugin in the New Plugins and Recently Updated on https://plugins.jenkins.io/ and when i click i am successfully brought to the plugin page https://plugins.jenkins.io/cdevents/ 

But when i put say "CDEvents" or another search string related to it, in the search box on https://plugins.jenkins.io/ the search working screen displays briefly and then a black page is displayed. Is there an issue someplace, it takes time to propagate or something else? 

### Reproduction steps

1. Open https://plugins.jenkins.io/
2. Type 'CDEvents" in the search box and press enter enter or click search icon
3. The search working screen briefly displays
4. Then a blank screen is display (it looks like the search crashes)

**Comment by GerMcMahon** [comment]
Do we know how the health score is generated and propagated?

**Comment by lemeurherve** [comment]
It's from a cron job, I'll check if I can trigger it.

**Comment by Harsh3341** [comment]
> two things:
> 
> * Plugin Health Score ([1](https://github.com/jenkins-infra/plugin-health-scoring)) is not seeing the plugin. This is not normal as the released occurred a few hours ago and the application should have updated its list of plugins from the update-center since.
> * The plugin-site ([2](https://github.com/jenkins-infra/plugin-site)) seems to not survive and a plugin has no score to be displayed.

For such types of cases should I add value to 0 of such plugins which have no healthScore ?

**Comment by hervelemeur** [comment]
@GerMcMahon for the record the plugin got a score, the search doesn't result to a blank page anymore.

**Comment by Harsh3341** [comment]
Good to know🙌,
I think we can close this issue as it's been fixed in https://github.com/jenkins-infra/plugin-site/pull/1394
