### ISSUE TITLE
Having validation issue on PR

### ISSUE THREAD

**Issue by sairen-carbonetes** [jenkins-infra/helpdesk#3549]
### Service(s)

GitHub

### Summary

@jenkins-infra-bot created a pr and failed on validation, when I check the logs, it said that `sairen-carbonetes` should be logged on Jira and Artifactory. I currently access my account `sairen_carbonetes` but still when the validation check for the 2nd time it failed but the Jenkins workflow is still ongoing.
https://github.com/jenkins-infra/repository-permissions-updater/pull/3279/checks?check_run_id=13049453732

**Comment by lemeurherve** [comment]
The issue comes from the fact you specified `sairen-carbonetes` as Jenkins username in your request: https://github.com/jenkins-infra/repository-permissions-updater/issues/3259

I've fixed it in the PR.

**Comment by sairen-carbonetes** [comment]
Thank you @lemeurherve for fixing it. I really appreciate it. ❤️

**Comment by sairen-carbonetes** [comment]
@lemeurherve the PR failed on Jenkins - Archive: error in 'archiveArtifacts' step

![image](https://user-images.githubusercontent.com/122254250/234776023-197a2359-f6bc-435e-a8ff-5c7662eec60f.png)

**Comment by lemeurherve** [comment]
I've restarted a job, and @NotMyFault merged your PR.

Everything should be good now, closing this issue.
