### ISSUE TITLE
Cleanup and import unmanaged Datadog monitorings in terraform

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3558]
### Service(s)

Datadog

### Summary

Some Datadog monitorings are duplicated (accountapp), unused anymore (Confluence, Jenkins DNS), or not managed as code in https://github.com/jenkins-infra/datadog

We should deduplicate, cleanup and import as code all these monitorings.

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/helpdesk/issues/3539 is closed, all monitors are ✅ this issue can be started

**Comment by lemeurherve** [comment]
Cleanup done, all Datadog monitors are now managed as code via terraform in https://github.com/jenkins-infra/datadog
