### ISSUE TITLE
Temporary name resolution failures on plugin BOM builds

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3559]
### Service(s)

ci.jenkins.io

### Summary

The plugin bill of materials generates a new release when a maintainer (like me) runs the build on the master branch.  Unfortunately, the master branch has failed the last few builds with an agent message "Temporary failure in name resolution"

https://github.com/apache/airflow/discussions/22319#discussioncomment-3594158 suggests that we may need to configure the kubedns component with more replicas or we may need to configure it to autoscale when heavily loaded.  I don't know how to do that, but the Kubernetes documentation at https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/ may be helpful

### Reproduction steps

1. Open https://ci.jenkins.io/job/Tools/job/bom/job/master/1668/ or https://ci.jenkins.io/job/Tools/job/bom/job/master/1666/ and confirm that the job failed due to a temporary name resolution failure

**Comment by lemeurherve** [comment]
I've manually restarted a build with `withArtifactCachingProxy(false)` until I have the time to check this error, also noted by @dduportal in https://github.com/jenkins-infra/helpdesk/issues/3481#issuecomment-1531215099

**Comment by lemeurherve** [comment]
I've removed the artifact caching proxy label from this issue as it doesn't seem related since the restarted build failed with the same error without it:

> [ERROR]     Unresolveable build extension: Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.41 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jenkins-ci.tools:maven-hpi-plugin:jar:3.41: The following artifacts could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:pom:3.41 (absent): Could not transfer artifact org.jenkins-ci.tools:maven-hpi-plugin:pom:3.41 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): repo.jenkins-ci.org: Temporary failure in name resolution: Unknown host repo.jenkins-ci.org: Temporary failure in name resolution -> [Help 2]

**Comment by dduportal** [comment]
@lemeurherve can you check the logs of the `core-dns` application on the cluster `cik8s` ? Also check its metrics in datadog for this cluster.

Looks like the cluster's internal DNS is not robust

**Comment by dduportal** [comment]
As compensating measures:

- https://github.com/jenkins-infra/kubernetes-management/pull/3897 removed the "custom datadog probes" which were killing the CoreDNS service on `cik8s`
- https://github.com/jenkins-infra/kubernetes-management/pull/3920 does the same for `eks-public` (ACP for AWS)

**Comment by dduportal** [comment]
The builkds https://ci.jenkins.io/job/Tools/job/bom/job/master/1683/ and https://ci.jenkins.io/job/Tools/job/bom/job/master/1678/ ran without DNS errors: we can close this issue.
