### ISSUE TITLE
forgot username and password

### ISSUE THREAD

**Issue by bdivya3013** [jenkins-infra/helpdesk#3560]
### Type(s) of account issue

I didn't receive any email

### Summary

i forgot my username and password

### jenkins.io account username

divya b

### jenkins.io account email

bdivya3013@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by lemeurherve** [comment]
Hello @bdivya3013, there isn't any user registered with this email.

I invite you to create one from https://accounts.jenkins.io/signup

Closing this issue, let us know if you need anything else.

**Comment by bdivya3013** [comment]
want to change the password as i forgot the jenkins login password

**Comment by lemeurherve** [comment]
As I said in my previous comment, there isn't any user registered with this email, there isn't any password to reset.

I invite you to register an account at [accounts.jenkins.io/signup](https://accounts.jenkins.io/signup), you'll be able to chose a new password.
