### ISSUE TITLE
Debian packages starting with 2.387.2 are no longer published under https://pkg.jenkins.io/debian-stable/binary/

### ISSUE THREAD

**Issue by circa10a** [jenkins-infra/helpdesk#3562]
### Service(s)

pkg.jenkins.io

### Summary

Prior to Jenkins version `2.387.2`, LTS debian packages were published under `https://pkg.jenkins.io/debian-stable/binary/`, but now seem to be published under `https://pkg.jenkins.io/debian-stable/direct/` which doesn't contain a proper `Release` file. This breaks our internal Artifactory remote mirror configuration which results in only having the ability to install up to `2.387.1` available to us via our mirror.

- Is this intentional?
- Was this a miss?
- Why is there no `Release` file under the `direct/` path?

### Reproduction steps

1. Setup up debian mirror to `https://pkg.jenkins.io/debian-stable/binary` via Artifactory
2. Try to install LTS version `2.387.2`

**Comment by circa10a** [comment]
Also to clarify, we've seen newer weekly releases hit the `binary/` path but not LTS releases

**Comment by circa10a** [comment]
We were under the assumption that artifactory would automatically use the new GPG key, but it was actually failing silently.

**Comment by MarkEWaite** [comment]
As far as I know, we've never documented https://pkg.jenkins.io/debian-stable/direct or https://pkg.jenkins.io/debian-stable/binary as valid download locations.  If they worked in the past, it was a happy accident.

The Debian installation instructions create the jenkins.list file with the URL https://pkg.jenkins.io/debian

Can you share where you found a reference to the `/direct/` path so that we can correct that incorrect reference?

**Comment by SingulariteeSplunk** [comment]
> As far as I know, we've never documented https://pkg.jenkins.io/debian-stable/direct or https://pkg.jenkins.io/debian-stable/binary as valid download locations. If they worked in the past, it was a happy accident.
> 
> The Debian installation instructions create the jenkins.list file with the URL https://pkg.jenkins.io/debian
> 
> Can you share where you found a reference to the `/direct/` path so that we can correct that incorrect reference?

@MarkEWaite There was no specific reference anywhere in the docs. We are mirroring https://pkg.jenkins.io/debian-stable as a debian remote repository in Artifactory. When we view the tree for the repository we see both the `/binary/` dist which contains valid debian release files, as well as the `/direct/` path which contains a `FOOTER.html` and a different set of debian packages.

I suspect this may be unique to the package registry you're using and it's configuration, especially if that happens to be Artifactory as there could be some unique behavior there. If you have a Virtual repo and have a generic combined with a debian repo, for example, that could explain what we are seeing. 

Regarding the GPG key, I discovered that while Artifactory did not require any action to update the new key, the system which mirrors from it does (and subsequently populates a local cache of the remote repo), and the behavior is such that there are really no failures, just a lack of updates being pulled into Artifactory's local cache.
