### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by astill-monkeytech** [jenkins-infra/helpdesk#3566]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

Tried to create an account and somehow triggered the anti-spam system

### jenkins.io account username

astill_cyclelabs

### jenkins.io account email

allen.still@cyclelabs.io

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Closing unless there is an issue: in that case feel free to reopen
