### ISSUE TITLE
Jenkins job is failing to load the local jar from lib folder.

### ISSUE THREAD

**Issue by Bhagyashri-Sapnar** [jenkins-infra/helpdesk#3567]
### Service(s)

ci.jenkins.io

### Summary

Getting below error in jenkins job build for qualys-cs-plugin

 [ERROR] Failed to execute goal on project qualys-cs: Could not resolve dependencies for project com.qualys.plugins:qualys-cs:hpi:1.6.2.7-SNAPSHOT: The following artifacts could not be resolved: com.qualys:cs-plugin-common:jar:1.2.4 (absent): Could not find artifact com.qualys:cs-plugin-common:jar:1.2.4 in azure-proxy (https://repo.azure.jenkins.io/public/) -> [Help 1].

Job link:https://ci.jenkins.io/job/Plugins/job/qualys-cs-plugin/job/hotfix%252F1.6.2.7/3/console

stash repo link: https://github.com/jenkinsci/qualys-cs-plugin
branch:https://github.com/jenkinsci/qualys-cs-plugin/tree/hotfix/1.6.2.7.

### Reproduction steps

https://ci.jenkins.io/job/Plugins/job/qualys-cs-plugin/job/hotfix%252F1.6.2.7/

**Comment by dduportal** [comment]
Hi @Bhagyashri-Sapnar , the behavior is expected as there are no mention of a local JAR ("Maven External Dependency") in the `pom.xml`: https://github.com/jenkinsci/qualys-cs-plugin/blob/bee8efed185c1e062d01f49ee0a8e22433495b42/pom.xml#L115-L120 .

So Maven tries to retrieve the dependency based on its configuration (using the local "Artifact Caching Proxy") but this artefact does not exist on the Jenkins Artifiactory (https://repo.jenkins-ci.org/artifactory/public/com/qualys/).

You have to, **in short term**, fix your `pom.xml` to point the local JAR file as a ["Maven System dependency"](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#system-dependencies).

But please be aware it's a deprecated feature of Maven as per the documentation so you'll need a longer term solution: is there a Maven repository where these aretafcts are published?

**Comment by Bhagyashri-Sapnar** [comment]
@dduportal,
Thanks for your response.
with adding system dependency it is working fine but the jar we are referring is added in Project Repository, so using the 
below in project repository reference it should work. but it is not working.
https://github.com/jenkinsci/qualys-cs-plugin/blob/bee8efed185c1e062d01f49ee0a8e22433495b42/pom.xml#L93

**Comment by dduportal** [comment]
Oh I see, I missed this markup. It means an exception si to be added to the mirroring system we use for artifact caching, which should exlude (e.g. not trying to forward requests to the artifact caching proxy) any Maven repository which ID would be `in-project` (and eventually `local`).

**Comment by dduportal** [comment]
Testing manually with the caching proxy exception: https://ci.jenkins.io/job/Plugins/job/qualys-cs-plugin/job/hotfix%252F1.6.2.7/6/

**Comment by dduportal** [comment]
@Bhagyashri-Sapnar the PR I sent went fine, your problem should be solved. Can you confirm?

**Comment by Bhagyashri-Sapnar** [comment]
Hi @dduportal,
Thanks for your response.

Can you please confirm if below parameters needed to set in jenkinsfile. if we remove it from the jenkinsfile any impact on plugin will have?

_useArtifactCachingProxy: true, useContainerAgent: true._

**Comment by lemeurherve** [comment]
@Bhagyashri-Sapnar I've responded to your question here: https://github.com/jenkinsci/qualys-cs-plugin/pull/41#issuecomment-1541549713

**Comment by dduportal** [comment]
The PR was merged, and the build number 8 on the branch `hotfix-1.6.2.7` is now working as expected => this issue is solved.

Feel free to reopen if you see another issue.

**Comment by dduportal** [comment]
For info, a new update of the mirroring system was deployed: https://github.com/jenkins-infra/jenkins-infra/pull/3070. Currently checking the impact on ci.jenkins.io's build of your plugin (tried locally with the new setup and it looked good)
