### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by Ankur842** [jenkins-infra/helpdesk#3569]
### Type(s) of account issue

I've lost my password

### Summary

password reset

### jenkins.io account username

Ankur842

### jenkins.io account email

ankur842@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @Ankur842 , you have to reset your password on the page you mentionned: https://accounts.jenkins.io/passwordReset.

Instructions will then be sent to your email.


Is there any problem with this procedure?

**Comment by dduportal** [comment]
Closing as no answer from the requester
