### ISSUE TITLE
Registered with the wrong email

### ISSUE THREAD

**Issue by als12171** [jenkins-infra/helpdesk#3570]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I registered with the wrong email

I created an account in https://accounts.jenkins.io/signup.
The username i registered is **als12171**

But I used the wrong email when registering.
I typed **andre.l.sousa@gmail.com** but i wanted to type **sousa.l.andre@gmail.com**

I tried to register again with the correct email but I got the error "username already exists". 
Can you fix this, please.

Thanks

### jenkins.io account username

als12171

### jenkins.io account email

andre.l.sousa@gmail.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/signup

**Comment by dduportal** [comment]
Hi @als12171 , I've deleted the account since it was freshly created.

You should be able to re-create it with the email of your choice.

Can you confirm when it's done?

**Comment by als12171** [comment]
Hi

I recreated the account with the correct email.
Thanks

**Comment by dduportal** [comment]
Thanks for your answer. I'm closing the issue.
