### ISSUE TITLE
Jenkins CI failing for jenkins plugin after changes in jenkinsfile to update jenkins.version

### ISSUE THREAD

**Issue by sumoanema** [jenkins-infra/helpdesk#3572]
### Problem with this page

https://github.com/jenkinsci/sumologic-publisher-plugin/pull/26/checks?check_run_id=13309411162

### Expected behavior

Changes were made to pom.xml to upgrade the jenkins.version of the sumologic-publisher plugin. Same jenkins.version was updated to the JenkinsFile as well and since the upgraded jenkins.version works with java 11 changes were made in jenkinsfile to update the java version as well - https://github.com/jenkinsci/sumologic-publisher-plugin/pull/26/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8. 

Expected behaviour - Jenkins CI job for the plugin should pass when creating the PR to merge the respective changes with respective jenkins and java version provided in jenkins file.

### Actual behavior

Jenkins CI job are failing. This is because although in the JenkinsFile jenkins version is upgrade to 2.361.4, jenkins ci job is picking the older version of - 2.332.1 and later fails with this error : 
`Caused by: org.apache.maven.plugin.MojoExecutionException: This version of maven-hpi-plugin requires Jenkins 2.361 or later`

Thus the CI pipeline getting created for the PR is still referring the old jenkins file. I have already tried closing the PR and  recreating a new PR - after which the issue persists.

**Comment by dduportal** [comment]
Hi @sumoanema , as pointed out by @zbynek (thanks Zbynek!), the build on ci.jenkins.io is set up to only load Jenkinsfile from a trusted contributor (e.g. admin/maintainer of the repository) which you do not seem to be.

It's the same kind of security system as the GitHub Action "Approve and Run".

If you want to see the "real result", you have to ask a plugin maintainer or a ci.jenkins.io administrator to replay the build with the new Jenkinsfile (if they are OK with its new content).

**Comment by sumoanema** [comment]
@dduportal - I have created a new PR with the @sumo-apps-team which is the trusted contributor for the plugin..I am still facing the same issue : https://github.com/jenkinsci/sumologic-publisher-plugin/pull/27
Is there something which I am missing here ?

**Comment by dduportal** [comment]
> @dduportal - I have created a new PR with the @sumo-apps-team which is the trusted contributor for the plugin..I am still facing the same issue : [jenkinsci/sumologic-publisher-plugin#27](https://github.com/jenkinsci/sumologic-publisher-plugin/pull/27) Is there something which I am missing here ?

@sumoanema I'm sorry, I was not precise when I gave the explanation and misled you.

The commits on your pull request does not have an author whom is maintainer or admin, so Jenkins still consider the PR to be "untrusted".

I'm not sure if the Pull Request author (in the GItHub API) is checked by Jenkins, but the commit authors (in git) sure are.

You could add  @summo-apps-team  as co-author (or squash commits).

As it's good enough for me (if you can open a PR as @summo-app-teams, then your change is legit), I'll help you by replaying the build (to avoid wasting more of your time).

**Comment by sumoanema** [comment]
@dduportal thanks !! the ci job was now able to pick the correct changes in the respective jenkins file. Thus closing this issue

**Comment by sumoanema** [comment]
@dduportal - after your help, jenkins ci job did go through fine for this error. But later failed because spotBug job did not go fine. Did some research and got to know that spotJob does not fully support java 11. And my changes in the plugin is for upgrading the java version to 11. So I decided the drop the plugin triggering the spotBug job from pom.xml. After doing the same I ran into the same issue - https://github.com/jenkinsci/sumologic-publisher-plugin/pull/27 
. I also tried to add myself in developer in the pom.xml, replacing an old developer - https://github.com/jenkinsci/sumologic-publisher-plugin/commit/8e3aab35e648b5f895960ce95ecc3154cf7ca707 which also did not help. 

Then I also tried to commit the changes with "sumo-apps-team" as coauther - https://github.com/jenkinsci/sumologic-publisher-plugin/pull/28/commits/15ead71e3ddf6716a3b29b46b883ac17e5a53776 in a separate branch with all the changes and raised a fresh PR : https://github.com/jenkinsci/sumologic-publisher-plugin/pull/28 then also I am facing the same issue. 

I was hoping if you could replay the build like last time to let me move forward and suggest some way so that I dont face this error when I am contributing from my git account.

**Comment by dduportal** [comment]
Hi @sumoanema , there are multiple elements here:

1. About the commit / permissions: you need to add your personal GitHub as a co-maintainers. Please read carefully https://www.jenkins.io/doc/developer/plugin-governance/managing-permissions/ and follow the instructions. Please note that it requires one of the current Administrators of the GitHub repository https://github.com/jenkinsci/sumologic-publisher-plugin to add your account as a "Maintainer" or "Administrator" (both roles are considered trusted by Jenkins).
  - The author/maintainer changes in the Maven descriptor `pom.xml` are only metadatas used by plugins.jenkins.io. It's not a functionnal change.

2. SpotBug "issue"  you have with Java 11: you should open a thread in the section "Contributing" -> "Code" section of the community forum to get help (here: https://community.jenkins.io/c/contributing/code/21) or an email in the mailing list [jenkinsci-dev@googlegroups.com](https://groups.google.com/g/jenkinsci-dev). I'm asking because the issue tracker here is scoped to the Jenkins infrastructure and we do not have the skills to help you on this area (while the community forums or mailing list have other plugin developers, contributors and people with the correct skills to help you).

**Comment by sumoanema** [comment]
@dduportal - Thanks for the quick response. I referred to the page provided by you to add my account @sumoanema as administrator for the repo - https://github.com/jenkinsci/sumologic-publisher-plugin from the git hub web interface where I do see my name in the list of collaborators (screenshot attached for reference)
<img width="1374" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91047769/cbb2c9b3-d353-4960-98ab-0df4598cc9ac">

Please let me know if any other step is required from my side or if I am doing anything wrong.

**Comment by dduportal** [comment]
It looks good: let me trigger a Multibranch Job Organization Scan on ci.jenkins.io to let the job get your new permissions. I'll report back here once done.

**Comment by dduportal** [comment]
@sumoanema done: you now have to update your PRs to ensure that the authors of the commits on each PR is and Admin or a maintainer.
On both PR I see that @sumo-apps-team is either a commit co-author or a PR author.

I suggest you start a fresh PR only with your user @sumoanema for both commits and PR.

**Comment by dduportal** [comment]
Weirdn, the build keep saying 

```
13:08:57  Connecting to https://api.github.com to check permissions of obtain list of SumoLogic for jenkinsci/sumologic-publisher-plugin
13:08:57  Loading trusted files from base branch master at 8e3aab35e648b5f895960ce95ecc3154cf7ca707 rather than 5b31d08f9ba7a6159ab85f770b58f096facc290f
13:08:57  Obtained Jenkinsfile from 8e3aab35e648b5f895960ce95ecc3154cf7ca707
13:08:57  ‘Jenkinsfile’ has been modified in an untrusted revision
```

Let me check further

**Comment by dduportal** [comment]
Ping @timja can you help me here? I do not have enough permissions to the `jenkinsci` organization to check the state of the repository permissions:

```
$ curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GITHUB_TOKEN}"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/jenkinsci/sumologic-publisher-plugin/collaborators
{
  "message": "Must have push access to view repository collaborators.",
  "documentation_url": "https://docs.github.com/rest/collaborators/collaborators#list-repository-collaborators"
}
```

and I'm not sure what is wrong (it looks like the setup is fully ok now)

**Comment by timja** [comment]
@dduportal feel free to add yourself to the repo with the hosting bot for debugging

**Comment by timja** [comment]
```shell
$  curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/jenkinsci/sumologic-publisher-plugin/collaborators | jq -r '.[].login' | sort -f

boaglio
btm
capotej
cowboyd
cris
csamuel
darxriggs
davidt
domi
FooBarWidget
funkaoshi
headius
hsbt
jdamick
lsegal
lucaspanjer
masaki
me
michaelneale
mzehrer
mzp
nakula
nirvdrum
olhado
ronaldtse
scarytom
stigkj
tonetheman
trondn
vbehar

**Comment by sumoanema** [comment]
@dduportal - meanwhile you are looking into this issue, could you please replay the build for me, like you did here - https://github.com/jenkins-infra/helpdesk/issues/3572#issuecomment-1542176820 for me to move forward at least for now.

**Comment by sumoanema** [comment]
@dduportal - Hi.. if its possible for you, could you please replay the build like you did the last time, so that we can progress with the merge and this issue can be looked in separately ?

**Comment by dduportal** [comment]
Hello @sumoanema ! I've triggered a replay (build number 5) for the PR num. 29: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fsumologic-publisher-plugin/detail/PR-29/5/pipeline using the Jenkinsfile for the PR.


As per the comment from Tim above (https://github.com/jenkins-infra/helpdesk/issues/3572#issuecomment-1560109898) it looks like your account is not effectivley seen as collaborator of the repository, which explains why Jenkins does not take your Jenkinsfile change in account.

**Comment by dduportal** [comment]
@sumoanema The PR passed: you should be able to merge it (as you are Admin).

You properly configured the repository as I can tell, there is something I'm missing in the setup that led ci.jenkins.io to think you are not a "trusted" contributor.

Current working hypothesis:

- Jenkins might require your username to have already commited on the principal branch: we can validate this once you'll have merged the PR 29 and opening a new PR changing the Jenkins (adding a comment or an `echo` instruction)
- You might need not to be an outside contributor of the jenkinsci organization: worth asking your user to be added in the hosting system (I'm searching the proper doc for you to use in that matter)

**Comment by timja** [comment]
> You might need not to be an outside contributor of the jenkinsci organization: worth asking your user to be added in the hosting system (I'm searching the proper doc for you to use for that matter)

I've invited @sumoanema to the team.

> Jenkins might require your username to have already commited on the principal branch

It doesn't

**Comment by dduportal** [comment]
> > You might need not to be an outside contributor of the jenkinsci organization: worth asking your user to be added in the hosting system (I'm searching the proper doc for you to use for that matter)
> 
> I've invited @sumoanema to the team.
> 
> > Jenkins might require your username to have already commited on the principal branch
> 
> It doesn't
> 
> Once an untrusted PR has been created it can't be trusted, you need to create a new PR once your permissions are sorted.

Thanks @timja !

The weird thing is that the PR 29 was opened **after** the permission were set properly in the repository as per https://github.com/jenkins-infra/helpdesk/issues/3572#issuecomment-1558758507

=> that should have set them as trusted. I wonder if the "Member Outside Organization" couldn't be impacting?

**Comment by dduportal** [comment]
We are closing this issue as it seems no more actions are required by the Jenkins infra team.

Feel free to reopen if the problem still persists.
