### ISSUE TITLE
Install and configure Datadog plugin on ci.jenkins.io

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3573]
### Service(s)

ci.jenkins.io, Datadog

### Summary

Since https://github.com/jenkins-infra/helpdesk/issues/2844 the ELK stack has been removed, and the corresponding plugins have been removed from ci.jenkins.io

We should gather logs again from ci.jenkins.io, for that we have to:
- [x] Install Datadog plugin on ci.jenkins.io: https://plugins.jenkins.io/datadog/
- [x] Configure it without ingesting build logs at first: https://docs.datadoghq.com/continuous_integration/pipelines/jenkins/?tab=linux
- [x] Check if everything is OK then activate build logs ingestion

### Potential improvements
- [ ] Add custom tags to segment job types
- [ ] Correlate infrastructure metrics: https://docs.datadoghq.com/continuous_integration/pipelines/jenkins/?tab=linux#correlate-infrastructure-metrics

Related: https://github.com/jenkins-infra/helpdesk/issues/2769

**Comment by dduportal** [comment]
> The Datadog plugin is now installed and configured on ci.jenkins.io but nothing is shown on Datadog.
> 
> FTR, here is the result of `datadog-agent status` from ci.jenkins.io VM:
> Details

I realize that the default value for the agent hostname is `127.0.0.1` as per https://github.com/jenkins-infra/jenkins-infra/blob/84de1e8e1a716be95db783a19a3460ef890bd65a/dist/profile/templates/jenkinscontroller/casc/datadog.yaml.erb#L7 (because https://github.com/jenkins-infra/jenkins-infra/pull/2836/files does not set up the `targetHost` value).

But since the plugins runs in the ci.jenkins.io, it's inside the container, while the datadog agent runs on the host.
You can verify with a `curl -v localhost:8125` from within the container: it won't work at all.

+

What are the logs from the controller? For sure, if it does not work, Jenkins will prints some logs to guide you.

**Comment by lemeurherve** [comment]
> What are the logs from the controller?

Nothing related to Datadog in https://ci.jenkins.io/manage/log/all

**Comment by dduportal** [comment]
> > What are the logs from the controller?
> 
> Nothing related to Datadog in https://ci.jenkins.io/manage/log/all

I got the following in this page (required a reload/restart of the controller since this plugin is initialized at startup)

>  May 16, 2023 2:03:21 PM WARNING org.datadog.jenkins.plugins.datadog.traces.DatadogTraceBuildLogic finishBuildTrace
> May 16, 2023 2:03:21 PM SEVERE org.datadog.jenkins.plugins.datadog.DatadogUtilities severe
> Connection refused (Connection refused)
>
> May 16, 2023 2:03:21 PM INFO org.datadog.jenkins.plugins.datadog.DatadogUtilities severe
>
> Connection refused (Connection refused): java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:507)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:602)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:275)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:374)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:395)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at org.datadog.jenkins.plugins.datadog.transport.HttpSender.blockingSend(HttpSender.java:77)
	at org.datadog.jenkins.plugins.datadog.transport.HttpSender.run(HttpSender.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by dduportal** [comment]
Besides:

```
root@ci:~# grep -c 'use_dogstatsd' /etc/datadog-agent/datadog.yaml
0
root@ci:~# telnet 127.0.0.1 8125
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

so not only `localhost:8125` cannot work, but also the dogstatd agent is not exposed on the host itsefl (ref. https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent).

**Comment by lemeurherve** [comment]
While working on https://github.com/jenkins-infra/helpdesk/issues/3558 I've noticed that the `jenkins.package.available` metric used in https://github.com/jenkins-infra/datadog/blob/main/monitor-packages.tf isn't collecting any event, hence its "no data" current state.

I think this issue could resolve that, to be checked on completion.

**Comment by dduportal** [comment]
> While working on #3558 I've noticed that the `jenkins.package.available` metric used in https://github.com/jenkins-infra/datadog/blob/main/monitor-packages.tf isn't collecting any event, hence its "no data" current state.
> 
> I think this issue could resolve that, to be checked on completion.

What is the relationship with the ci.jenkins.io metric collection?

(the monitor you're pointing looks related to the PKG VM, hosting the packages and index)

**Comment by lemeurherve** [comment]
> What is the relationship with the ci.jenkins.io metric collection?

The fact that all `jenkins.*` metrics aren't collecting anything, and that their "last configured" value is empty made me think of this relation.

<img width="873" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/7325f94f-505e-4431-9a5d-7d1736db144c">

**Comment by dduportal** [comment]
> > What is the relationship with the ci.jenkins.io metric collection?
> 
> The fact that all `jenkins.*` metrics aren't collecting anything, and that their "last configured" value is empty made me think of this relation.
> <img alt="image" width="873" src="https://user-images.githubusercontent.com/91831478/240557575-7325f94f-505e-4431-9a5d-7d1736db144c.png">

🤔 fair, but `jenkins.package.available` looks like a custom metric. Not sure what it would mean in the context of the datadog plugin for Jenkins?

**Comment by lemeurherve** [comment]
You're right, this is a custom metric. It doesn't report anything though.

**Comment by lemeurherve** [comment]
Temporarily disabling Datadog plugin on ci.jenkins.io to avoid numerous connection error logs from it until we figure out how to enable communication between the Datadog agent on the VM host and the controller inside a container running on the VM host.

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/f84167c5-6721-455a-b7b8-43b98c91f4a4)

**Comment by lemeurherve** [comment]
It didn't went well, ci.jenkins.io was down for ~5 minutes (corresponding status incident: https://github.com/jenkins-infra/status/pull/315)

<details>
<summary>Error log:</summary>

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/96f9be34-6112-4d99-bfe5-98d66443f9bd)

</details>

Fixed by deleting `$JENKINS_HOME/plugins/datadog.jpi.disabled` file in ci.jenkins.io volume.

I'll comment out datadog JCasc then disable again the plugin on ci.jenkins.io

**Comment by lemeurherve** [comment]
Datadog plugin temporarily disabled.

**Comment by dduportal** [comment]
- From the ci.jenkins.io host, as root, we can see the datadog agent is reachable on its UDP/8125 port for the dogstasD protocol (https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent):

```
$ nc -u 127.0.0.1 8125 -z -v
Connection to 127.0.0.1 8125 port [udp/*] succeeded!
```

- From the container `jenkins`, same host, as root:

```
apt update
apt install netcat -y

## Fails as expected: No process is listening inside the container on the UDP/8125
# Neither on the container's loopback interface
nc -u 127.0.0.1 8125 -z -v
# OR on the container virtual ethernet interface
nc -u 172.17.0.2 8125 -z -v
```

- Confirming the behavior by checking the process listening on the UDP/8125 ports:

```
root@ci:~# netstat -alnp | grep udp | grep 8125
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           25918/agent         
udp        0      0 127.0.0.1:57636         127.0.0.1:8125          ESTABLISHED 25919/process-agent 
````

vs.

```
root@ci:~# docker exec -u root -ti  jenkins bash
root@e2d16f2ca5d3:/# netstat -alnp | grep udp | grep 8125
root@e2d16f2ca5d3:/#
```

- The datadog agent configuration need to be set up to allow incoming udp traffic:
  - https://github.com/DataDog/datadog-agent/blob/04300ae7b919f67d22c0a0a7634d12b5decb66d7/pkg/config/config_template.yaml#LL1947C3-L1947C30
  - Setting it to `true` (and `systemctl restart agent`) makes the agent to listen on all interfaces, all transports (IPv4/IPv6):
    
    ```
    $ docker exec -u root -ti  jenkins nc -u 172.17.0.1 8125 -z -v
    Connection to 172.17.0.1 8125 port [udp/*] succeeded!
    $ nc -u 127.0.0.1 8125 -z -v
    Connection to 127.0.0.1 8125 port [udp/*] succeeded!
    $ netstat -alnp | grep udp | grep 8125
    udp        0      0 127.0.0.1:50065         127.0.0.1:8125          ESTABLISHED 3649/process-agent  
    udp6       0      0 :::8125                 :::*                                3648/agent
    ```
  
  - But it is now available from the outside: we need a firewall rule

    ```
    ➜ nc -u 104.208.238.39 8125 -v -z
    Connection to 104.208.238.39 8125 port [udp/*] succeeded!
    ➜ nc -u 10.0.2.4 8125 -v -z      
    Connection to 10.0.2.4 8125 port [udp/*] succeeded!
    ```

**Comment by dduportal** [comment]
- As per https://forge.puppet.com/modules/datadog/datadog_agent/readme#configuration-variables, the `non_local_traffic` attribute is the goal
- Let's also add a firewall rule (puppet, azure, both?)

**Comment by timja** [comment]
Add an NSG only allowing port 80, 443 and the inbound agent port in?

**Comment by dduportal** [comment]
Update:

- The datadog agent can specify a custom bind_host (but only one). Easier to restrict to "0.0.0.0" (remove IPv6 at least). Avoid allowing the full external incoming requests and easier to block

> Add an NSG only allowing port 80, 443 and the inbound agent port in?
>
> i.e. not a firewall rule to block it but a firewall rule to only allow required traffic
>
> >    Let's also add a firewall rule (puppet, azure, both?)
>
> I would prefer just Azure, it's a lot easier to reason about and debug issues imo.

Both should be required as they protect against different threats:

- I agree with the NSG method, to ensure the virtual network takes care of requests
- But adding local iptable rules is clearly needed: we only want to restrict to the loopback and the docker0 interface (and nothing else: not even a locally bound veth or a local bridge).
  - Alas https://github.com/DataDog/datadog-agent/issues/1513 would avoid this but the agent does not alow specifying a list: it is either "all or nothing".

> it's a lot easier to reason about and debug issues imo

Yes but it would remove a layer of protection.

**Comment by dduportal** [comment]
- Datadog is now fully enabled and integrated with ci.jenkins.io
- Metrics, build logs and traces are collected and visible within Digital Ocean:

<img width="1920" alt="Capture d’écran 2023-06-22 à 19 22 55" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/e3677b1a-d1eb-4c95-a076-a6805218fdf3">


Handing over back to @lemeurherve to finish the work on this issue

**Comment by lemeurherve** [comment]
Closing, potential improvements:
- [ ] Add custom tags to segment job types
- [ ] Correlate infrastructure metrics: https://docs.datadoghq.com/continuous_integration/pipelines/jenkins/?tab=linux#correlate-infrastructure-metrics
