### ISSUE TITLE
Blocked by Spam Account

### ISSUE THREAD

**Issue by DJ-Watermelon** [jenkins-infra/helpdesk#3581]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I mistyped my email, so I resent the sign up sheet, and it marked me as spam.

### jenkins.io account username

jessica_4107

### jenkins.io account email

dingj4107@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
A password reset was triggered: you have an email on this email account.

Please let us know once you've confirmed you can log in.

**Comment by DJ-Watermelon** [comment]
I can login. Thank you!
