### ISSUE TITLE
Local build of Jenkins core fails with spotbugs issue, CI server build is green

### ISSUE THREAD

**Issue by Bananeweizen** [jenkins-infra/helpdesk#3586]
### Service(s)

ci.jenkins.io

### Summary

Build Jenkins HEAD locally by running "mvn -DskipTests verify". The build fails with a spotbugs error that seems correct. The same build triggered by the central CI server does not have any spotbugs errors and is green.
```
[INFO] --- spotbugs:4.7.3.4:check (spotbugs) @ cli ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[ERROR] Medium: Switch statement found in hudson.util.QuotedStringTokenizer.hasMoreTokens() where default case is missing [hudson.util.QuotedStringTokenizer] At QuotedStringTokenizer.java:[lines 156-271] SF_SWITCH_NO_DEFAULT
```
I'm building with Maven 3.9.2 on Windows. What else can we check to find the reason of this inconsistency between local build and CI build?
I'm aware that this might be _either_ an infrastructure issue (if something is missing/broken in the configuration of the server) or a Jenkins core issue (if something is missing in its pom.xml or other configuration files). However, I have no clue where to raise the issue when in doubt.
I've also checked by going back a week in git history, same results.

### Reproduction steps

mvn -DskipTests verify

**Comment by dduportal** [comment]
Hi @Bananeweizen at first glance, it looks like the following Maven options in the `Jenkinsfile` of Jenkins Core explains this difference of behavior: https://github.com/jenkinsci/jenkins/blob/master/Jenkinsfile#L92

**Comment by MarkEWaite** [comment]
I do not get any spotbugs errors when build the master branch on OpenJDK 11 (Eclipse Temurin) on my Windows desktop.  Probably best to open the issue in https://issues.jenkins.io and provide more details of the Java compiler that is being used to generate the bytecode.
