### ISSUE TITLE
Remove "Bootstrap 4 API" from our controllers

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3595]
### Service(s)

ci.jenkins.io, trusted.ci.jenkins.io

### Summary

<img width="856" alt="Capture d’écran 2023-05-24 à 20 31 41" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/3cebf348-050a-4e82-98e6-48954564ae89">

https://plugins.jenkins.io/bootstrap4-api/ was marked as deprecated and should be removed from the following controllers:

- [x] ci.jenkins.io
- [x] trusted.ci.jenkins.io

**Comment by smerle33** [comment]
manually removed from both controllers and restarted both
