### ISSUE TITLE
 Remove "Poppers JS **2**" from our controllers

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3597]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

https://plugins.jenkins.io/popper2-api/ was marked as deprecated and should be removed from the following controllers:

- [x] ci.jenkins.io
- [x] trusted.ci.jenkins.io
- [x] cert.ci.jenkins.io
- [x] infra.ci.jenkins.io
- [x] release.ci.jenkins.io
- [x] weekly.ci.jenkins.io

**Comment by smerle33** [comment]
PR for docker image for weekly/infra and LTS  : https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1251 and https://github.com/jenkins-infra/docker-jenkins-lts/pull/732

**Comment by smerle33** [comment]
removed manually on ci.jenkins.io, trusted.jenkins.io and cert.ci.jenkins.io 
all have been restarted also.
