### ISSUE TITLE
I created jenkins account few mounts ago, now I want to login but it doesn't login me and when I enter my email it doesn't respond I am stil waiting for the response.

### ISSUE THREAD

**Issue by Tayyab111** [jenkins-infra/helpdesk#3598]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I am entering accurate Username and Password but not logging in. it doesn't works for me.

### jenkins.io account username

Tayyab

### jenkins.io account email

tayyabafridi843@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @Tayyab111 , there is no user account with the username or the email provided.

If you need to access the jenkins.io websites, then you can create an account on accounts.jenkins.io.

But it looks like you want to access your organization Jenkins instance: you should contact your own administrators as it is unrelated to accounts.jenkins.io.
