### ISSUE TITLE
Invite Jagruti into the jenkins-infra organization

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3600]
### GitHub repositories

https://github.com/jenkins-infra/plugin-health-scoring/ (But I'll be able to manage that part once Jagruti is in the organization)

### GitHub users to have permission

@Jagrutiti

### Permission level

Read

### Justification

Jagruti has been selected to participate to the GSoC 2023 on the Plugin Health Scoring project (see https://www.jenkins.io/blog/2023/05/22/jagruti-introduction-blog-post).

As such and as mentor on the project, I need to grant Jagruti permissions on the repository. I can manage that part, once Jagruti has been invited to the organization.

**Comment by dduportal** [comment]
Hello 👋 

@Jagrutiti was added with the **Read** role in the jenkins-infra/plugin-health-scoring repository: an invitation was sent and need an answer from them

![Capture d’écran 2023-05-26 à 13 53 39](https://github.com/jenkins-infra/helpdesk/assets/1522731/1a74e7a3-4d15-4cc9-a2ee-131c2e3c3324)

**Comment by alecharp** [comment]
Thank you very much. This is all I needed as I can do the rest normally on my own.

**Comment by dduportal** [comment]
The invite is only for the repository. What would be the purpose of having them organization-wide?

The team make sense, but then the permission would be *Maintain* instead of *Read*.

What is the access requirement?

**Comment by alecharp** [comment]
I expect Jagruti to open, close and respond to issues and pull request as well as review some. Having her in the team would be perfect. Sadly I can add her myself as she's not in the organisation. Dheeraj was added to the organisation last year.

**Comment by alecharp** [comment]
This is perfect thank you.
