### ISSUE TITLE
Jenkins 

### ISSUE THREAD

**Issue by Tayyab111** [jenkins-infra/helpdesk#3603]
### Service(s)

jenkins.io

### Summary

I want to plugin java in Jenkins so I add the java HOME path  in jenkin's Global tool configuratin then I build, after build it shows me Error in console output:

ERROR: Failed to parse POMs
java.io.IOException: Cannot run program "/usr/share/doc/openjdk-11-jre-headless/JAVA_HOME/bin/java" (in directory "/var/lib/jenkins/workspace/Mymanvenproject"): error=20, Not a directory

Caused by: java.io.IOException: error=20, Not a directory

Finished: FAILURE

### Reproduction steps

![Screenshot from 2023-05-29 18-16-47](https://github.com/jenkins-infra/helpdesk/assets/100529078/5a3396ed-027b-43ee-b2fd-e5774ba2f546)

**Comment by Tayyab111** [comment]
please! help

**Comment by dduportal** [comment]
Hi @Tayyab111 this issue tracker is only related to jenkins.io website and infrastructure, it's not the right place to ask for general help about Jenkins, so we'll close this issue.

You should try to ask for help in the community forums at community.jenkins.io.


(PS: your error seems clear: Mavn tries to use the `java` binary specified to be in `/usr/share/doc/openjdk-11-jre-headless/JAVA_HOME/bin/java` but this path does not exist on your machine so it fails and reports the error)

**Comment by Tayyab111** [comment]
Thanks!
