### ISSUE TITLE
Update controllers to 2.401.1

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3607]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

2.401.1 has been released successfully.

**Comment by dduportal** [comment]
- LTS Docker image update: https://github.com/jenkins-infra/docker-jenkins-lts/pull/735

**Comment by dduportal** [comment]
cert.ci.jenkins.io && trusted.ci.jenkins.io: https://github.com/jenkins-infra/jenkins-infra/pull/2869

**Comment by dduportal** [comment]
It's done, thanks for the help @NotMyFault !
