### ISSUE TITLE
Package availability dashboard is empty

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3608]
### Service(s)

Datadog

### Summary

The public dashboard tracking package availability is empty: https://p.datadoghq.com/sb/0Igb9a-e6849e5e019250ef5aaea3589297fe8b

**Comment by lemeurherve** [comment]
> (probably related)

It was. Fixed in https://github.com/jenkins-infra/kubernetes-management/pull/4056, the dashboard isn't empty anymore.
