### ISSUE TITLE
Invite Mostafa into the jenkins-infra/plugin-health-scoring

### ISSUE THREAD

**Issue by Mostafa-ashraf19** [jenkins-infra/helpdesk#3610]
### GitHub repositories

https://github.com/jenkins-infra/plugin-health-scoring/

### GitHub users to have permission

@Mostafa-ashraf19

### Permission level

Read

### Justification

I'm mentor in this project, in Google summer of code 2023.

**Comment by alecharp** [comment]
I asked Mostafa to create this ticket. This is the equivalent of #3600. 
Having him in the team for GSoC 2023 will provide him access to the GitHub Project and he will have an impact on the pull request review.

**Comment by lemeurherve** [comment]
@Mostafa-ashraf19 I've added you to the [plugin-health-scoring team(]https://github.com/orgs/jenkins-infra/teams/plugin-health-scoring/) which now has the `Triage` role on the repository.

You should have received an email invitation to join the @jenkins-infra org and the team that you have to accept.

Let me know if there is any issue, closing as completed.

**Comment by Mostafa-ashraf19** [comment]
@lemeurherve, Thank you!
