### ISSUE TITLE
Can't login and password reset doesn't work

### ISSUE THREAD

**Issue by micschro** [jenkins-infra/helpdesk#3611]
### Problem with this page

[Error | Jenkins](https://accounts.jenkins.io/doLogin) page

### Expected behavior

Login should work

### Actual behavior

Login doesn't work. Password reset doesn't work either. The doLogin requests are answered with a status 500 response.

**Comment by dduportal** [comment]
Hi @micschro what are your username or email so we can check the status of your account in our admin backend?

**Comment by dduportal** [comment]
Closing as no answer back from the user.
