### ISSUE TITLE
Remove `translation` plugin from ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3612]
### Service(s)

ci.jenkins.io

### Summary

The server accepting these translations is long gone, and the plugin has been EOL feature-wise since 2016.
I recommend removing it because we don't work with local translations and rely on what the plugins provide installed on ci.j

If someone wants to do some cleanup, the submitted files are stored in `./contributed-localizations/`.

**Comment by lemeurherve** [comment]
There is no `contributed-localizations` folder in ci.jenkins.io, I suggest we proceed to the removal of the plugin anyway, WDYT?

**Comment by NotMyFault** [comment]
> There is no `contributed-localizations` folder in ci.jenkins.io, I suggest we proceed to the removal of the plugin anyway, WDYT?

Definitely, even better if it's not used.

**Comment by dduportal** [comment]
Plugins is removed from ci.jenkins: closing. Thanks!
