### ISSUE TITLE
Getting an Unauthorized with CD setup with codebuild-cloud plugin

### ISSUE THREAD

**Issue by carpnick** [jenkins-infra/helpdesk#3615]
### Service(s)

Artifactory

### Summary

Trying to do a release of a new plugin version, see GH Action run: https://github.com/jenkinsci/codebuild-cloud-plugin/actions/runs/5155755272/jobs/9285919297

### Reproduction steps

1. Attempt to do a release
2. Getting consistent authentication failures.

Shows that the secrets were updated 6 hours ago:
<img width="675" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/6966179/fb57ab23-b3b9-498a-bf6b-789deb41a77c">

**Comment by timja** [comment]
see https://status.jenkins.io/

**Comment by dduportal** [comment]
The operation is now finished (it was https://github.com/jenkins-infra/helpdesk/issues/3486) and you should be able to release your plugin again by selecting the "Re-Run Failed builds" on GHA.

Thanks for reporting!
