### ISSUE TITLE
Sync upload permissions with GitHub team members

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3618]
Hello,

a few weeks ago, I removed myself from a number of plugins in the [jenkins-infra/repository-permissions-updater](https://github.com/jenkins-infra/repository-permissions-updater/pull/2880).

However, it was brought to my attention that I was still having admin access to those repositories because I was still in the team managing those repositories. 

Is there a way to sync the two together? I know that in my case it's easy to match my ldap user to my github user, but I know it's not the case for everyone. 

My question is, is there a way to manage those permissions globally or are we blocked because of #6?

**Comment by NotMyFault** [comment]
The RPU acts independently of GH permissions, this is not a "as-code" approach.
It's not uncommon to find repositories, where only a few people have release permission, but more have repository access or vice versa. The RPU maintains release permission and provides a security contact, but that it's in terms of the user part.

To remove your GH permissions, you can leave the team on your own.

**Comment by timja** [comment]
@halkeye did some work awhile ago to try and codify GitHub permissions in the same file but didn't finish I believe.

**Comment by timja** [comment]
> When someone ask to get a permission on GH, once approved, is it granted manually by an admin?

By someone on the hosting team yes

**Comment by alecharp** [comment]
Alright, I see. So, at this moment there is no way to sync up the lists.
Thank you for your answers.

**Comment by halkeye** [comment]
https://community.jenkins.io/t/codify-github-access/799/10

From my tests manging teams not repo access seemed like the way to go, it could be done very quickly, while looping through repos was very slow.

But then it involved writing up proposals and I sorta fizzled out.
