### ISSUE TITLE
Proposal for application in publick8s to migrate to arm64

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3619]
### Service(s)

Azure

### Summary

Work in progress: determining candidates to migrate on the arm node pool

existing deployments on publick8s : 

  - accountapp
  - cert-manager
  - cert-manager-cainjector
  - cert-manager-webhook
  - coredns (kube-system)
  - coredns-autoscaler (kube-system)
  - datadog-cluster-agent
  - incrementals-publisher
  - javadoc
  - jenkinsio
  - jenkinsio-zh
  - konnectivity-agent (kube-system)
  - metrics-server (kube-system)
  - mirrorbits
  - mirrorbits-files
  - plugin-health-scoring 
  - plugin-site-backend
  - plugin-site-frontend
  - plugin-site-issues
  - private-nginx-ingress-ingress-nginx-controller
  - private-nginx-ingress-ingress-nginx-defaultbackend
  - public-nginx-ingress-ingress-nginx-controller
  - public-nginx-ingress-ingress-nginx-defaultbackend
  - rating
  - reports
  - uplink
  - wiki

### Progress

https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1713522131

**Comment by smerle33** [comment]
as per https://github.com/jenkins-infra/kubernetes-management/pull/4310 wiki is now on the ARM64 nodepool

**Comment by smerle33** [comment]
Definitive candidate list : (WIP)

- [ ] accountapp: https://github.com/jenkins-infra/account-app (using shared pipeline library)
- [ ] jetstack/cert-manager && acme : https://github.com/jenkins-infra/helm-charts/tree/main/charts/acme (already compatible with arm64: https://github.com/cert-manager/cert-manager/)
- [ ]  incrementals-publisher: https://github.com/jenkins-infra/incrementals-publisher (using shared pipeline library)
- [ ]

**Comment by smerle33** [comment]
working on https://github.com/jenkins-infra/helpdesk/issues/3719 before going further to avoid service interruption during migration

**Comment by smerle33** [comment]
rating as been migrated to ARM64 successfully

**Comment by smerle33** [comment]
private nginx ingress as been migrated to ARM64 successfully

**Comment by lemeurherve** [comment]
Update: (WIP)


### uplink:

The project hasn't been built since 2019, and isn't configured anymore on ci.jenkins.io, restoring it by adding it to the "infra" folder:

<img width="1185" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/e01fcf55-359e-45a5-bca5-1c4cefe4a74a">

**Comment by lemeurherve** [comment]
Update:

## uplink

The project is built again, on ci.jenkins.io and infra.ci.jenkins.io, with deterministic builds (`npm ci`), and deployed with success, cf https://github.com/jenkins-infra/kubernetes-management/pull/4607#issuecomment-1786905267

The arm64 image has been published cf https://hub.docker.com/layers/jenkinsciinfra/uplink/0.1.0/images/sha256-88605c3cfcb9018b270c340d8426955f13aa72708c01a25c75f99f8710af3729?context=explore, and a status incident has been opened to announce its migration: https://status.jenkins.io/issues/2023-10-31-uplink-arm64-migration/

**Comment by lemeurherve** [comment]
Update:

## uplink

After fixing the chart by using named tags instead of sha256 reference for the Docker image (preventing the deployment of arm64 architecture variant), uplink has been successfully migrated to arm64:
- https://github.com/jenkins-infra/helm-charts/pull/903
- https://github.com/jenkins-infra/kubernetes-management/pull/4612#issuecomment-1787346587

TODO: adapt uplink updatecli manifest in kubernetes-management, ref:
- https://github.com/jenkins-infra/helm-charts/pull/903#discussion_r1377664481

**Comment by lemeurherve** [comment]
Update: datadog-cluster-agent & cert-manager migrated to arm64.

**Comment by lemeurherve** [comment]
Update

## plugin-site-api

Migrate the container publication from trusted.ci.jenkins.io to infra.ci.jenkins.io:
- Add job in infra.ci.jenkins.io to obtain new semver tag
- Use `buildDockerAndPublishImage` in Jenkinsfile (https://github.com/jenkins-infra/plugin-site-api/pull/142)
- Remove job from trusted.ci.jenkins.io

**Comment by lemeurherve** [comment]
Update

## plugin-site-api
Arm64 image published from infra.ci.jenkins.io, chart updated, ready to migrate.

## plugin-site-issues
Arm64 image published, ready to migrate.

We can proceed to plugin-site components migration to arm64.

**Comment by lemeurherve** [comment]
Last plugin-site helm chart version including the tag with an arm64 variation deployed on publick8s cluster.
Only remain the helmfile release changes to migrate its components to arm64.

**Comment by smerle33** [comment]
`plugin-site` and `plugin-site-issues`  migration to arm64 done.

Migration plugin-site and plugin-site-issues post mortem:

I did forget to update the charts version in the PR : https://github.com/jenkins-infra/kubernetes-management/pull/4683
I created the PR https://github.com/jenkins-infra/kubernetes-management/pull/4684 to fix it but the helm engine locked the update with: `Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress`

The solution was to rollback : 
  first we list the releases : `helm ls --namespace plugin-site`
  then we revert: `helm rollback --namespace plugin-site plugin-site` and `helm rollback --namespace plugin-site plugin-site-issues`
  we can then launch a new kubernetes-management build in the infra.ci.jenkins.io
  
In order to avoid this kind of problem, I think that I need to first check the opened PR related to this release (we had https://github.com/jenkins-infra/kubernetes-management/pull/4671) and to better plan the migration to make sure that more than one can focus and check the PR.

This had no impact on production as kubernetes was able to hold the upgrade as it was not successful.

**Comment by dduportal** [comment]
Before closing this PR, the following services will have to be migrated to `arm64`:

- `httpd` (in both `mirrorbits` and `mirrorbits-parent` releases)
- `rsyncd` (in `mirrorbits-parent` release)
- `weekly.ci.jenkins.io` 

Next step after this issue (to be continued and detailed):

- https://github.com/jenkins-infra/helpdesk/issues/3823
- https://github.com/jenkins-infra/helpdesk/issues/3824

**Comment by smerle33** [comment]
mirrorbits-parent : httpd and rsyncd are now on arm64
<img width="2931" alt="Capture d’écran 2023-11-20 à 17 34 05" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/96c8b06f-1b49-4ff1-bd64-362a06ee294f">

**Comment by smerle33** [comment]
first attempt to move `WEEKLY.CI.JENKINS.IO` to arm64 was a failure, but probably due to my impatience
Next attempt will involved before merging the PR: 

- manual scaling +1 arm node
- manually change the statefulset to downsize to 0 to help the volume migration

**Comment by smerle33** [comment]
We created a new class : https://github.com/jenkins-infra/azure/pull/526/ to use ZRS storage.
and use a temporary PV/PVC on this volume in order to use it as a source for the migration
