### ISSUE TITLE
Making public the Plugin Health Scoring project for GSoC 2023

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3620]
Hello,

in the context of GSoC 2023, I created https://github.com/orgs/jenkins-infra/projects/8 to track the work done. 
However, this is currently a private project which makes it invisible to the community. 

As the work done during GSoC is public, could you make https://github.com/orgs/jenkins-infra/projects/8 public so anyone can `read` it? It would also display in https://github.com/jenkins-infra/plugin-health-scoring/issues which entries have been assigned to the project.

Only the members of the `jenkins-infra/plugin-health-scoring` should be able to move tickets around and I should still be the admin of the project.

I cannot make it public on my own, only admins of the organization can do that.

Thank you.

**Comment by lemeurherve** [comment]
The project is now public, with https://github.com/orgs/jenkins-infra/teams/plugin-health-scoring as writers and you & @jleon33 as admins.

**Comment by alecharp** [comment]
Thank you very much!
