### ISSUE TITLE
Documentation updates not rendering on jenkins.io

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/helpdesk#3622]
### Service(s)

jenkins.io

### Summary

There have been documentation updates to jenkins.io, but even as recently as today (June 12), there are merged documentation changes that are not rendered correctly on the production site.

[This merged PR](https://github.com/jenkins-infra/jenkins.io/pull/6456) shares the update that was performed, moving the "Pluggable Storage" documentation to the Using Jenkins section, which should be listed under the "Using JMeter with Jenkins" link in the navigation pain on the left hand side of the screen.

This is the local version of the site (with the section clearly visible in the navigation as expected): 
![local pluggable storage](https://github.com/jenkins-infra/helpdesk/assets/99040580/f855348f-4820-4f7d-925b-bac317436ece)

This is the live jenkins.io site version which does not contain the link as expected:
![production pluggable storage](https://github.com/jenkins-infra/helpdesk/assets/99040580/8f3b6d3a-4d5d-464d-b6db-18f7887ac000)

[Another example is](https://github.com/jenkins-infra/jenkins.io/pull/6459), where a bullet point and text should be removed.

This is the local version where the text & bullet point are removed:
![local theme text - removed](https://github.com/jenkins-infra/helpdesk/assets/99040580/170ac41a-3d65-4fcc-8393-0348cb589231)

This is the live jenkins.io site where the text & bullet point remain:
![production theme text - included](https://github.com/jenkins-infra/helpdesk/assets/99040580/a19044ec-9302-48ec-8c98-e383cdf24ad3)

### Reproduction steps

1. Navigate to [theming](https://www.jenkins.io/doc/book/managing/ui-themes/#information-for-theme-developers) or [Using Jenkins overview](https://www.jenkins.io/doc/book/using/)
2. Check left side navigation for Pluggable Storage link (non-existing)
3. Check theming page for removed bullet point (still exists)

**Comment by dduportal** [comment]
Thanks for raising the issue @kmartens27 , currently looking at the delivery process of the website on the (private) controller trusted.ci.jenkins.io.

**Comment by dduportal** [comment]
Issue found: trusted.ci is unhelathy since we migrated the LDAP server.

Update center updates and RPU are OK but not the jenkins.io/crawler/javadoc.

https://github.com/jenkins-infra/azure/pull/406 for fixing it, and then we'll re-trigger a new site update to check the changes you described.

**Comment by dduportal** [comment]
- I have been mistaken: trusted.ci.jenkins.io was performing the jobs properly. It was only a problem with human authentication.
- However, I had to decache with `curl -XPURGE <URL of the page>` a page to see the table of content being updated after reloading my page.

Usually, we would decache the jenkins.io on fastly globally one time to force the page to be updated.
However, given origin.www.jenkins.io's website (the one cached by fastly) is being migrated today (https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1588040182) + the upcoming weekly release which will decache the whole website again once packaged, let's wait a bit.

We'll check this issue after these operations to see if it is fixed.

**Comment by dduportal** [comment]
@kmartens27 all of our operation have been finished with success and the jenkins.io website was fully de-cached: it should be good for you. Can you confirm by closing the issue (or show us example where it is not working for you so we can continue diagnosing)?

**Comment by kmartens27** [comment]
Awesome, thank you so much @dduportal! It looks as though things are rendering correctly now, as the live site matches the local test.
<img width="230" alt="Screenshot 2023-06-13 at 10 27 55 AM" src="https://github.com/jenkins-infra/helpdesk/assets/99040580/b756b5e6-af1c-4aec-9b13-219c0a196517">
