### ISSUE TITLE
node tolerations and taint for nodepool arm

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3623]
### Service(s)

Other

### Summary

in publick8s, now that we use an arm64 nodepool, we need to set a taint to avoid wrong scheduling of pods for application that are not yet compatible with arm64.

we need to set a taint on the nodepool from kubernetes / azure 
but before, as we already use this nodepool, we need to :

1. lower the nodeselector for the already on arm64 application to be able to use the other nodepool, 
2. drain the arm64 nodepool
3. recreate the nodepool with the correct taint (os + cpu architecture)
4. make sure the arm64 compatible application (javadoc) are able to start on the new arm64 node pool (preferably but still able to start on the x86 nodepool)

**Comment by smerleCB** [comment]
Change in the process :  

1.  lower the node selector for arm64 (javadoc) to set only the arch to arm64 not to the nodepool name
2. limit the auto provisionning to 1 for the nodepool arm64small
3. create a new node pool named arm64small-20230629  in arm64 with a taint : small
4. add toleration on javadoc for the taint small
5. drain the old node of the arm64small node pool
6. check that the javadoc is correcly spawn on the new nodepool
7. remove the old nodepool

**Comment by smerle33** [comment]
to be continued, new node pool created need to :

**Comment by smerle33** [comment]
after adding toleration to datadog and falco to be able to use this new nodepool, we can close this issue as done
