### ISSUE TITLE
Username and password recovery 

### ISSUE THREAD

**Issue by vinayantony03** [jenkins-infra/helpdesk#3625]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

I want to recover my username and password of Jenkins 

### jenkins.io account email

vinayantony3@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
No user on accounts.jenkins.io with the email address listed
