### ISSUE TITLE
Cannot login to Jenkins

### ISSUE THREAD

**Issue by Katsiaryna-Ledak** [jenkins-infra/helpdesk#3628]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I have created an account. I can login with them in the web version, but cannot login locally in my Jenkins locally installed. Ichanged the password but still cannot login locally.
I tried to create another account, but got this antispam message

### jenkins.io account username

katerina_khud

### jenkins.io account email

ekaterina.ledak@gmail.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/login

**Comment by Katsiaryna-Ledak** [comment]
All these issues are related to mine but none can help. I changed the pswd, still can login on website, but cannot locally

**Comment by MarkEWaite** [comment]
There is no connection between a username / password created on accounts.jenkins.io and a locally installed Jenkins controller.  You'll need to define the user account and the password on the locally installed Jenkins controller, independent of whatever username and password you use for the jenkins.io account.
