### ISSUE TITLE
Unable to establish a connection to trusted.ci.jenkins.io

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3629]
### Service(s)

trusted.ci.jenkins.io

### Summary

Probably related to https://github.com/jenkins-infra/helpdesk/issues/3624

I've updated my configuration according to the runbook, but attempting to connect yields:
> ssh: connect to host trusted.ci.jenkins.io port 22: Connection refused

However, connecting to `controller.trusted.ci.jenkins.io` establishes a working connection, I can use to access it in the browser.

Is it supposed to be like this?

**Comment by dduportal** [comment]
Yes, the SSH connection is to controller.trusted.ci.jenkins.io (machine hostname with a private DNS record) while the web service is "trusted.ci.jenkins.io" on your webbrowser (using the etc hosts trick)

**Comment by dduportal** [comment]
@NotMyFault I might have updated the runbook a bit quickly: do not hesitate to propose an update (as you are the best person who "know  what you do not know" ;) )

**Comment by NotMyFault** [comment]
> NotMyFault I might have updated the runbook a bit quickly: do not hesitate to propose an update (as you are the best person who "know what you do not know" ;) )

Thanks for the confirmation! Either, I've been too used to the old address, or it was actually not obvious to me.

**Comment by dduportal** [comment]
No worries : i honestly have updated too quickly the runbook without thinking that much (and I keep doing the same connection to trusted instead of controller.trusted 😅).
