### ISSUE TITLE
Forget username and password not able to connect

### ISSUE THREAD

**Issue by kumarpul** [jenkins-infra/helpdesk#3630]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### jenkins.io account email

pvinodkumar885@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Password reset by administrator. An email was sent and acknoledged byt to the Google Mail servers: if you do not see it, then either you are not looking at the correct email box or it is in your spam
