### ISSUE TITLE
Account issue 

### ISSUE THREAD

**Issue by Ruchikumarisoni** [jenkins-infra/helpdesk#3631]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### jenkins.io account username

Ruchi_soni129

### jenkins.io account email

ruchisoni1218@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Your password was reset : can you check your spam folder please?

**Comment by dduportal** [comment]
Closing as no answer from requester

**Comment by Ruchikumarisoni** [comment]
Hii teams,
I install Jenkins and setup everything but after opening the dashboard i by
mistake close the app after that it's asking me username and password So, i
provided it but it's invalid and I don't remember the password so what
should I do now. Please let's me know how should I fix it .
The username is ruchi_soni129 and full name is Ruchi Kumari Soni

With Regards
RUCHI

**Comment by dduportal** [comment]
Hi @Ruchikumarisoni , the issue tracker here is only for the `*.jenkins.io` website and their account management.

The Jenkins instance you have setup is unrelated to the accounts.jenkins.io's account you created: it has its own account management with an auto-generated `admin` user with a unique password written in the logs or filesystem: https://www.jenkins.io/doc/book/installing/docker/#unlocking-jenkins

- If you are stuck with your Jenkins instance, please open a topic in the community forum at community.jenkins.io to get help from other users as the issue tracker in GitHub is **only** for the Jenkins Public infrastructure itself.
- If you still need your public Jenkins accounts to access the JIRA issues.jenkins.io of Jenkins core to report bug (but NOT for asking for help: that is what the community forum are for) then you are autonomous to reset your password through the accounts.jenkins.io webiste (but it looks like you don't need this account).
