### ISSUE TITLE
cpc1

### ISSUE THREAD

**Issue by kanchanamn** [jenkins-infra/helpdesk#3637]
### Type(s) of account issue

I've lost my password

### Summary

adminrole

### jenkins.io account username

priyadarshinijk@gmail.com

### jenkins.io account email

priyadarshinijk@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam
```[tasklist]
### Tasks
- [ ] https://github.com/jenkins-infra/helpdesk/issues/3535
```

**Comment by kanchanamn** [comment]
project any essus

**Comment by kanchanamn** [comment]
ok

**Comment by dduportal** [comment]
Hi @kanchanamn this project is for the public `*.jenkins.io`, not for individual Jenkins instances.

As so I'm going to close this issue. If you need help in setting up your Jenkins instance, you should check the community forums at community.jenkins.io.
