### ISSUE TITLE
cpc1

### ISSUE THREAD

**Issue by kanchanamn** [jenkins-infra/helpdesk#3638]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

admin role

### jenkins.io account username

priyadarshinijk@gmail.com

### jenkins.io account email

priyadarshinijk@gmail.com

### Which URL are you trying to login at?

overruncost

**Comment by dduportal** [comment]
Hi @kanchanamn , you already opened an illegitmate issue at https://github.com/jenkins-infra/helpdesk/issues/3637.

I'm closing the issue here for the same reason, please stop spaming us.
