### ISSUE TITLE
`javac` vanished from `docker-highmem` machines

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3641]
### Service(s)

ci.jenkins.io

### Summary

In Jenkins core, we're using the label `docker-highmem` to run a set of ATH tests for core PRs on highmem machines.

Since June the 26th, these builds are failing:

> [WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.

and a bit later

> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project websocket-spi: Fatal error compiling: Error while executing the external compiler. Error while executing process. Cannot run program "javac" (in directory "/home/jenkins/workspace/Core_jenkins_PR-8132/websocket/spi"): error=2, No such file or directory -> [Help 1]

Like seen in https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8132/6/consoleText

I have created https://github.com/jenkinsci/jenkins/pull/8203 running `javac -version` on a highmem machine, which is supposed to return the `javac` version, but it returns `script returned exit code 127`:

> [2023-06-28T19:31:13.555Z] + javac -version
[2023-06-28T19:31:13.556Z] /home/jenkins/workspace/Core_jenkins_PR-8203@tmp/durable-fe359bfb/script.sh: line 1: javac: command not found

I tend to suspect something changed on the infra's end because the timeline of the 26th of June lines up with infra's acceptance tests failing since the 26th of June, lacking the java_home variable set:

> 20:19:15  + echo 'ERROR: the '\''JAVA_HOME'\'' environment variable is undefined'
20:19:15  ERROR: the 'JAVA_HOME' environment variable is undefined

https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/

**Comment by dduportal** [comment]
The change which happened the 26 June on ci.jenkins.io's Azure VMs is [the switch from SSH to inbound method](https://github.com/jenkins-infra/jenkins-infra/pull/2925).

Given that the content of the VM did not change at all, it means the error here is caused by the `JAVA_HOME` variable. I guess with the different agent's process specified JDK and VM JDK, there might be behavioral differences. 

Gotta dig on this (cc @timja for info as it might be important to know for the Azure VM plugin)

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/packer-images/blob/9323f8719ba9183d77323d5788336f7fd8a593cf/provisioning/ubuntu-provision.sh#L330 shows that the `JAVA_HOME` variable is defined in the `/etc/environment`
- The ATH recently changed from JDK11 to JDK17: I guess it relies on the "raw" setup of the image
- But the change to Azure VM inbound changes the initial environment perceived by the agent process: I guess `/etc/environment` is not read anymore: I'm searching in that direction

=> It is another call for an RFE to the Azure VM agent to define environment variables in the cloud UI (or JCasc) like it's done for other plugins (EC2, Kubernetes, etc.)

**Comment by timja** [comment]
The process is now started by systemd rather than SSH.
When you use an inbound agent you pretty much take complete control of the agent outside of passing of variables.

**Comment by dduportal** [comment]
> The process is now started by systemd rather than SSH. So yeah that will likely have an impact on variables
> 
> https://unix.stackexchange.com/a/473035/194601
> 
> When you use an inbound agent you pretty much take complete control of the agent outside of passing of variables.

Gotcha, thanks Tim. I forgot that the systemd process from the script is not a `login` session: that is different than the EC2 or Kubernetees inbound process which launched "inline" by cloudinit or equivlanet (which are using login sessions).

Gotta update immediatly.


@NotMyFault short term, you can add yourself the `JAVA_HOME` in your ATH build if you have an emergency that cannot wait the agents to be fixed.

**Comment by dduportal** [comment]
Ok, I got something working in https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8203/5/console 👍 

I'm gonna update manually the ci.jenkins.io config for all Linux machines, and puppet config is due tomorrow

**Comment by dduportal** [comment]
Resuming operations: agent disabled on ci.jenkins.io + working on test configs for Windows machine (to avoid regression).

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/jenkins-infra/pull/2936 has been tested, approved, merged and deployed.
- The [(infra) Acceptance Tests Job](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/2611/) is now successful => I'll take care of checking this job next time I'll play with the agent setups on ci.jenkins.io (procedure improvement)
- The `javac` command is now on the path and defaults to JDK11 on all agents (it was the expected but implicit behavior):
  - If ATH need to use JDK17, then the `/opt/jdk-17` should be used instead (present on the machines)
  - Infra will start transisition to JDK17 soon but it's not the expected default today

**Comment by dduportal** [comment]
@NotMyFault can you close the issue if the incident is fixed from your point of view, or comment here with elements if it is not?

**Comment by NotMyFault** [comment]
> NotMyFault can you close the issue if the incident is fixed from your point of view, or comment here with elements if it is not?

Thanks, I replayed https://github.com/jenkinsci/jenkins/pull/8199 and the 7 ATH tests were successful.
