### ISSUE TITLE
Incrementals are no longer published

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3642]
### Service(s)

Incrementals

### Summary

Incrementals are no longer published on the default branch, separate branches and PRs.

I submitted https://github.com/jenkinsci/jenkins-infra-test-plugin/pull/94 attempting to create an incremental, fruitlessly.

For reference, incrementals were published properly 3 days ago, as seen on https://github.com/jenkinsci/dark-theme-plugin/runs/14543607017

**Comment by dduportal** [comment]
Finishing https://github.com/jenkins-infra/helpdesk/issues/3641 and then let's check this one.

**Comment by dduportal** [comment]
As per the build logs,n the incrementals.jenkins.io service is responding HTTP/400 with the following error:

```
HttpMethod: POST
 URL: https://incrementals.jenkins.io/
 Content-Type: application/json
 Authorization: *****
 Sending request to url: https://incrementals.jenkins.io/
 Response Code: HTTP/1.1 400 Bad Request
 Response: 
 invalid json response body at https://ci.jenkins.io/job/Plugins/job/jenkins-infra-test-plugin/job/PR-94/1/api/json?tree=actions[revision[hash,pullHash]] reason: Unexpected token < in JSON at position 0
 Success: Status code 400 is in the accepted range: 100:599
```

Gotta check on the service itself

**Comment by dduportal** [comment]
Ok, so the error is when the incrementals.jenkins.io application connects to ci.jenkins.io's JSON api to retrieve the list of artefacts:

```
2023-06-30T13:13:14.378Z info:  HTTP POST /
2023-06-30T13:48:04.521Z info:  Retrieving metadata from https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8205/2/api/json?tree=actions[revision[hash,pullHash]]
2023-06-30T13:48:04.593Z error:         Failed to fetch Pipeline build metadata
2023-06-30T13:48:04.593Z error:         FetchError: invalid json response body at https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8205/2/api/json?tree=actions[revision[hash,pullHash]] reason: Unexpected token < in JSON at position 0
    at /usr/src/app/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IncrementalsPlugin.main (/usr/src/app/IncrementalsPlugin.js:157:29)
    at async /usr/src/app/index.js:96:13
```

Ref. https://github.com/jenkins-infra/incrementals-publisher/blob/04a43d990699d11722eebf6fa9f01a87e73ab1d5/index.js#L96

**Comment by dduportal** [comment]
The technical user used by the incremental publisher is failing authentication. The password in the secrets of the incremental-publisher is incorrect. Gotta dig this one.

**Comment by dduportal** [comment]
Ref. https://github.com/jenkins-infra/helpdesk/issues/2444

**Comment by dduportal** [comment]
Manual operation trying to solve the issue:

- The user `releasebot` does not have any API token setup in ci.jenkins.io, and the secret is not its password
- Created an API token in ci.jenkins.io and manually added it to the secrets (+ pod re-creation)
- Triggered a manual build (https://ci.jenkins.io/job/Plugins/job/jenkins-infra-test-plugin/job/PR-94/2/console) while checking the logs

**Comment by dduportal** [comment]
- The test did not work: still the same HTTP/400 error in the incremental logs
- If I emit a curl request without any authentication, I got an HTTP/200.

Ping @timja I need help on this one: do you happen to remember why do we authenticate requests?

**Comment by dduportal** [comment]
Gotta stop for today, I'll try later in the week end unless someone else catch the problem

**Comment by timja** [comment]
> Ping @timja I need help on this one: do you happen to remember why do we authenticate requests?

I would say it's either to reduce spam ( / be able to identify it) at a guess but not sure

**Comment by dduportal** [comment]
The problem is now solved after updating the credential in the infra as code with (private link) https://github.com/jenkins-infra/charts-secrets/commit/7a8101831700945fac16fe4e6a707b4d38c598d9.

I guess my change on the configmap was not propagated.


=> incrementals builds have been working since the past 24 hours.

Thanks for the pointer folks!
