### ISSUE TITLE
Plugin continuous delivery (JEP-229) fails with artifactory permission denied

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3645]
### Service(s)

Artifactory

### Summary

When the plugin bill of materials attempted to upload a new release to artifactory, it was rejected with "permission denied".  The same message was reported when trying to release a new version of the embeddable build status plugin.

## Plugin BOM log file

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for parent 2220.vea_cea_f1a_35e4:
[INFO] 
[INFO] parent ............................................. SUCCESS [01:11 min]
[INFO] bom-weekly ......................................... FAILURE [  0.624 s]
[INFO] bom-2.401.x ........................................ SKIPPED
[INFO] bom-2.387.x ........................................ SKIPPED
[INFO] sample ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:40 min
[INFO] Finished at: [202](https://github.com/jenkinsci/bom/actions/runs/5433185076/jobs/9880712548#step:4:204)3-07-01T21:36:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project bom-weekly: Failed to deploy artifacts: Could not transfer artifact io.jenkins.tools.bom:bom-weekly:pom:2220.vea_cea_f1a_35e4 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/io/jenkins/tools/bom/bom-weekly/2220.vea_cea_f1a_35e4/bom-weekly-2220.vea_cea_f1a_35e4.pom, status: 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :bom-weekly
Error: Process completed with exit code 1.
```

Similar message was reported for embeddable build status plugin release.

### Reproduction steps

1. Attempt to release a new version of a plugin based on the merge of a labeled pull request (like embeddable build status), confirm that the output of the GitHub action is:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:56 min
[INFO] Finished at: 2023-07-01T21:35:37Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project embeddable-build-status: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:embeddable-build-status:pom:395.v96b_260870c38 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/embeddable-build-status/395.v96b_260870c38/embeddable-build-status-395.v96b_260870c38.pom, status: 401 Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

**Comment by NotMyFault** [comment]
`maven-11` agents fail to be provisioned, https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/.

The same agent label is used for various jobs on trusted.ci, the lack of available agents probably caused CD tokens to expire because the job to refresh them didn't run in time.

Agents using this template fail to launch on trusted.ci:
> init.sh: 17: Syntax error: "&" unexpected

**Comment by dduportal** [comment]
> The same agent label is used for various jobs on trusted.ci, the lack of available agents caused CD tokens to expire because the job to refresh them didn't run in time. Tokens haven't been refreshed for the past ~10h.

Good diagnostic 👍 The problem is also present on cert.ci.jenkins.io, but NOT on ci.jenkins.io.
It's a consequence of https://github.com/jenkins-infra/jenkins-infra/pull/2936 : in the case of trusted and cert, it only executes the datadog script, but it seems to fail.

As a temporary measure, I've disabled puppet on both machines anbd I've set it up to use the ubuntu VMs even if the init script fails.

 
> Agents using this template fail to launch on trusted.ci:
> 
> > init.sh: 17: Syntax error: "&" unexpected

@NotMyFault where did you see this error? I probably missed it somewhere obvious but I can't find it easily right now. That sounds like the failure reason on my script template.



> `maven-11` agents fail to be provisioned, https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/.

This one is unrelated: the acceptance test failure is because of Maven version: https://github.com/jenkins-infra/acceptance-tests/commit/3b72df53803d69e93d0820360f74d1eae0e14288 should fix it.

I'll watch this today. Thanks for reporting!

**Comment by NotMyFault** [comment]
> where did you see this error? I probably missed it somewhere obvious but I can't find it easily right now. That sounds like the failure reason on my script template.

The logs of the `ubuntu-22` agents attempting to launch on trusted.ci complained about it. That's all they had in their logs before shutting down again.

**Comment by dduportal** [comment]
Thanks for the pointer! It helps a lot. 

The line 17 of the script is the following:

```
) |& tee /var/log/agent-init-datadog.log
```

It's the same for the 3 controllers, but it only works on ci.jenkins.io with inbound agents.
I bet the script work differently: gotta check.

**Comment by dduportal** [comment]
Oh I see:  `sh` doesn't support `|&`, that could be a clue

**Comment by dduportal** [comment]
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/6dcc3c382d91365245862b5e7bd0314d3ce30176/src/main/java/com/microsoft/azure/vmagent/remote/AzureVMAgentSSHLauncher.java#L165 => despite the shebang, the could explain. Trying with the usual `2>&1 |` instead

**Comment by dduportal** [comment]
Applied on the 3 controller and scheduled agents with success.

Triggered a new agents availability job on ci.j (https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/2620) and on trusted.ci with success.

@MarkEWaite can you confirm that the CD is working again, now that the RPU job ran again properly?

**Comment by NotMyFault** [comment]
https://github.com/jenkinsci/embeddable-build-status-plugin/releases/tag/395.v96b_260870c38 has been released successfully ~6h ago.

**Comment by MarkEWaite** [comment]
Likewise for the release of the plugin bill of materials.  Thanks very much for making the fix!
