### ISSUE TITLE
Unable to download Jenkins in MacBook Pro m1

### ISSUE THREAD

**Issue by abumahfuz1** [jenkins-infra/helpdesk#3647]
### Problem with this page

[macOS Installers for Jenkins LTS](https://www.jenkins.io/download/lts/macos/) page[source file](https://github.com/jenkins-infra/jenkins.io/tree/master/content/download/lts/macos.html.haml)

### Expected behavior

download Jenkins

### Actual behavior

not installing

**Comment by lemeurherve** [comment]
Hello @abumahfuz1,

I've moved your issue from the website issue tracker to the infrastructure one.

I've just tried an installation and a startup of Jenkins on a MacBookPro M2 following instruction from https://www.jenkins.io/download/lts/macos/ but didn't encountered any issue.

Could you describe your problem with more details so we can try to reproduce it please?

**Comment by dduportal** [comment]
Closing a no answer from the user + no reproduction of the problem.
