### ISSUE TITLE
Add user to JenkinsCI team

### ISSUE THREAD

**Issue by crwd-etatarevic** [jenkins-infra/helpdesk#3651]
### GitHub repositories

https://github.com/jenkinsci/crowdstrike-security-plugin

### GitHub users to have permission

@crwdlemos

### Permission level

Admin

### Justification

We are adding a new admin user and they need to have all the required permissions. 

I would like to add the above user to jenkinsci team. We already completed the permission update as seen here (https://github.com/jenkins-infra/repository-permissions-updater/pull/3393)

**Comment by NotMyFault** [comment]
Added.
