### ISSUE TITLE
Release of `jenkinsci/build-monitor-plugin` failing with 401 Unauthorized

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3652]
### Service(s)

Artifactory, GitHub

### Summary

Releases of `jenkinsci/build-monitor-plugin` have been failing for 12 hours with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project build-monitor: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:build-monitor:pom:1.14-739.v15db_04e688ca_ from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor/1.14-739.v15db_04e688ca_/build-monitor-1.14-739.v15db_04e688ca_.pom, status: 401 Unauthorized -> [Help 1]
```

I read [the documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#the-upload-to-the-maven-repository-fails-with-401-unauthorized):

> Unauthorized means that the credentials were invalid, or not sent by Maven. This normally means that the secrets configured in the repository have expired, create an issue in the INFRA helpdesk on [GitHub](https://github.com/jenkins-infra/helpdesk/issues/new/choose) […].

Per the documentation, I am creating an infrastructure ticket to update the expired credentials.

### Reproduction steps

Obtain write access to `jenkinsci/build-monitor-plugin`, then go to https://github.com/jenkinsci/build-monitor-plugin/actions/workflows/cd.yaml and click the "Run workflow" button.

**Comment by basil** [comment]
Just tried again and it is now saying "403 Forbidden" rather than "401 Unauthorized":

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project build-monitor: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:build-monitor:pom:1.14-739.v15db_04e688ca_ from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authorization failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor/1.14-739.v15db_04e688ca_/build-monitor-1.14-739.v15db_04e688ca_.pom, status: 403 Forbidden -> [Help 1]

**Comment by dduportal** [comment]
Thanks for retrying @basil . We'll have to diagnose this deeper in the lights of the platform outage, sorry for the inconvenience

**Comment by basil** [comment]
I suspect there is likely a partially completed release already in Artifactory. I will make a dummy commit to the main branch to get a new Git hash, then try again in an hour or so.

**Comment by dduportal** [comment]
> I suspect there is likely a partially completed release already in Artifactory. I will make a dummy commit to the main branch to get a new Git hash, then try again in an hour or so.

Given the timestamps, that would be a valid explanation

**Comment by basil** [comment]
… and now the Jenkins build is failing with a spurious error

```
09:33:53  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 114ee8f9-3495-4f96-b274-a3848061ff78
09:33:53  java.lang.IllegalStateException: ID maven-warnings is already used by another action: io.jenkins.plugins.analysis.core.model.ResultAction for Maven
09:33:53  
09:33:53  	at io.jenkins.plugins.analysis.core.steps.IssuesPublisher.ensureThatIdIsUnique(IssuesPublisher.java:147)
09:33:53  	at io.jenkins.plugins.analysis.core.steps.IssuesPublisher.attachAction(IssuesPublisher.java:97)
09:33:53  	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.publishResult(IssuesRecorder.java:859)
09:33:53  	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.record(IssuesRecorder.java:779)
09:33:53  	at io.jenkins.plugins.analysis.core.steps.IssuesRecorder.perform(IssuesRecorder.java:741)
09:33:53  	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:1160)
09:33:53  	at io.jenkins.plugins.analysis.core.steps.RecordIssuesStep$Execution.run(RecordIssuesStep.java:1116)
09:33:53  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
09:33:53  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
09:33:53  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
09:33:53  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
09:33:53  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
09:33:53  	at java.base/java.lang.Thread.run(Thread.java:829)
09:33:54  [GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.
09:33:55  
09:33:55  GitHub has been notified of this commit’s build result
09:33:55  
09:33:55  Finished: FAILURE
```

**Comment by basil** [comment]
I was finally able to get https://github.com/jenkinsci/build-monitor-plugin/releases/tag/1.14-740.v1df20e5c64b_b_ released.

**Comment by dduportal** [comment]
Thanks @basil for taking care of this!
