### ISSUE TITLE
Update GitHub Users to Authorize as Committers to Atlassian Jira Software Cloud Plugin

### ISSUE THREAD

**Issue by rachellerathbone** [jenkins-infra/helpdesk#3654]
### GitHub repositories

https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin

### GitHub users to have permission

@rachellerathbone

### Permission level

Write

### Justification

part of the dev team.

**Comment by NotMyFault** [comment]
Added!

**Comment by rachellerathbone** [comment]
Hey @NotMyFault. I just tried to commit code but am getting `Permission to jenkinsci/atlassian-jira-software-cloud-plugin.git denied to rachellerathbone`

**Comment by NotMyFault** [comment]
> Hey @NotMyFault. I just tried to commit code but am getting `Permission to jenkinsci/atlassian-jira-software-cloud-plugin.git denied to rachellerathbone`

GH invitations are valid for 7 days only. I've sent out a new one.

**Comment by rachellerathbone** [comment]
Thanks!
