### ISSUE TITLE
[trusted.ci.jenkins.io] Add windows server 2022 agents

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3655]
### Service(s)

trusted.ci.jenkins.io

### Summary

Following #2629, the work required to add Windows Server 2022 Docker images to Jenkins has started.

https://github.com/jenkinsci/docker-agent/pull/441 is the first step for the `jenkins/agent` image.

As for today, ci.jenkins.io is able to spin up Windows Server 2022 machines with Docker CE in Windows mode: https://github.com/jenkins-infra/jenkins-infra/blob/6828a157001eaf2e0509c22fda3fd6d66f377ddc/hieradata/clients/controller.ci.jenkins.io.yaml#L534C15-L554

In order to build and publish these images, we need the same capability in trusted.ci.jenkins.io, the (private) controller in charge of publishing official images.

- Why not replacing Windows Server 2019 by 2022 instead?
  - As per https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-11#windows-server-host-os-compatibility, that might work (by switching container isolation level of the 2019 Docker images) but as for today, spinning up native host OS version is easier, like in ci.jenkins.io

- And what about other controllers such as cert.ci.jenkins.io, infra.ci.jenkins.io or release.ci.jenkins.io?
  - release.ci.jenkins.io: Only requires Windows containers for https://github.com/jenkins-infra/release/blob/master/PodTemplates.d/package-windows.yaml. If the Docker images publication is moved from trusted.ci to release.ci thoug, it will be required.
  - infra.ci.jenkins.io: might be needed as well for our packer images built eventually.
  - cert.ci.jenkins.io: no need for both 2019 and 2022 so opportunity to migrate 2019 to 2022 dirrectly, as only Maven + java builds are performed (but to be verifier with the JenSec team).

**Comment by lemeurherve** [comment]
Windows 2022 agent definition added to trusted.ci.jenkins.io and tested successfully, closing this issue.
