### ISSUE TITLE
Jira upgrade broke comment sort order remembering and implies an insane default

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#3658]
### Service(s)

Jira

### Summary

The Recent Jira upgrade has broken remembering the sort order a user chooses for comments.

As such every time I login and look at a Jira the sort order has been reset to "newest first" which is just insane, as you need the context to understand the reply so have to read comments from bottom up which in English is just plain crazy in a bottle.

### Reproduction steps

* Login to Jira
* browse to a jira with some comments
* click sort order on the comment so it is "Oldest first"
* logout of Jira
* Login to Jira
* browse to a different Jira with some comments (that you have not read before)

Notice the sort order has reset to "Newest first"

**Comment by jtnord** [comment]
https://support.atlassian.com/jira-cloud-administration/docs/change-the-default-order-for-comments/  possibly it is not possible to remember per user defaults and this is a system wide setting that needs to be changed.

**Comment by daniel-beck** [comment]
> fixed in [9.4.6](https://jira.atlassian.com/issues/?jql=project+%3D+JRASERVER+AND+fixVersion+%3D+9.4.6), [9.8.1](https://jira.atlassian.com/issues/?jql=project+%3D+JRASERVER+AND+fixVersion+%3D+9.8.1)

We're on 9.4.7 😦

**Comment by timja** [comment]
https://jira.atlassian.com/browse/JRASERVER-5443 is in progress, last updated yesterday.

**Comment by jtnord** [comment]
Do enough people think the server default (newest first) is sane?  if not can we just ask that the server default is changed until the above issue is fixed?

**Comment by timja** [comment]
i find it depends on case-by-case.

I think as a user I find newest first better as solutions are likely there.
As a developer it depends on the issue and how long the comments thread is.

at work where we often get long ones newest first is quite useful if you don't need the beginning of the thread but just the last x comments the new behaviour is nicer.

----

I wouldn't object to keeping the old behaviour temporarily, I barely use the Jenkins Jira anyway.

**Comment by daniel-beck** [comment]
Seems reasonable to restore the previous behavior while Atlassian work on making this a user-configurable option.

**Comment by MarkEWaite** [comment]
I much prefer the previous layout with oldest first.  I use Jira frequently and find it confusing to see the "Add comment" button at the bottom of the page when the most recent comment is at the top of the page.

Is there a global configuration setting that can be applied to switch back to oldest first?

**Comment by MarkEWaite** [comment]
> I've done the config change detailed here: https://jira.atlassian.com/browse/JRASERVER-74275?focusedId=3285929&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3285929
> 
> Look good?

Looks great.  Thanks very much for making that change!

**Comment by MarkEWaite** [comment]
My mistake for closing the issue.  @jtnord is the change made by @timja sufficient to address your concerns or do you want to keep this ticket open?

**Comment by jtnord** [comment]
Perfect, thanks @timja

**Comment by basil** [comment]
Thank you very much. This was driving me over the edge as well.
