### ISSUE TITLE
Forum enhancements

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3665]
### Service(s)

Other

### Summary

Here we go @dduportal :)

- Could you create me a "News" category please?
- And an API Key:
	- User Level: Single user and set to me (for now)
	- Scopes: Locally, I could achieve results with
![Screenshot 2023-07-13 at 18 41 27](https://github.com/jenkins-infra/helpdesk/assets/13383509/f0d773a2-312e-49ae-94fa-1659f8af5736)

Possibly more to come later :) ⬇️

Edit: I set up a local instance and played around with a list of items we can enhance our sponsored instance with, to get a bit more out of it.

**Comment by dduportal** [comment]
Category created: https://community.jenkins.io/c/news/27

**Comment by dduportal** [comment]
APi key created with the requested scope and shared with you in a private encrypted channel.

@NotMyFault I'll let you close the issue if it os for you!

**Comment by NotMyFault** [comment]
> APi key created with the requested scope and shared with you in a private encrypted channel.
> 
> NotMyFault I'll let you close the issue if it os for you!

Thanks! I received the key and validated it working in a private category for testing purposes.

Would you or the other discourse admins (cc @halkeye @timja) object to granting my account temporary admin permissions to facilitate enhancements I have in mind?
I'm a moderator already at trust level 4, but that doesn't suffice.

**Comment by halkeye** [comment]
i'm cool with another admin. I've been pretty hands off these days.

**Comment by timja** [comment]
go for it

**Comment by NotMyFault** [comment]
> i'm cool with another admin. I've been pretty hands off these days.

> go for it

Thanks for the positive feedback! Any objections to moving forward? I got some time this week, looking forward to it.

**Comment by MarkEWaite** [comment]
No objections from me.

**Comment by timja** [comment]
done

**Comment by dduportal** [comment]
Sorry, i’m not much online this week but it is a delayed +1 to grant @NotMyFault admin permissions !

**Comment by NotMyFault** [comment]
FTR, summed up in https://community.jenkins.io/t/updates-enhancements-to-the-community-forums/8554/ so far
