### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Ankit00110** [jenkins-infra/helpdesk#3666]
### Type(s) of account issue

I've lost my password

### Summary

Hi,

My username is Ankit00110, but I have lost password, please help me

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
The username `Ankit00110` does not exist on accounts.jenkins.io.  This looks like a request for help with a password on a Jenkins controller that is not managed by the Jenkins infrastructure team.  The Jenkins infrastructure team cannot help with Jenkins controllers that are not managed by the Jenkins infrastructure team.  Contact the people that administer that Jenkins controller.
