### ISSUE TITLE
Password forgot 

### ISSUE THREAD

**Issue by akashatre** [jenkins-infra/helpdesk#3667]
### Type(s) of account issue

I didn't receive any email

### Summary

Plz do something for password forgot or recovery

### jenkins.io account username

akash_01

### jenkins.io account email

akashatre123@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
The Jenkins infrastructure help desk is used to track issues and improvements for the Jenkins global infrastructure.  There is no user account on accounts.jenkins.io for `akash_01` or for the email address `akashatre123@gmail.com`.  That must be an account on a Jenkins controller that is administered by someone other than the Jenkins project.  Contact those administrators for help with your password reset.
