### ISSUE TITLE
Jenkins Account Creation issue

### ISSUE THREAD

**Issue by Hanuman1359** [jenkins-infra/helpdesk#3668]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I am facing an error when i was tried to create a jenkins account, for learning purpose.

### jenkins.io account username

Hanuman1359

### jenkins.io account email

hdasari@v2soft.com

### Which URL are you trying to login at?

[account.jenkins.io/antis](https://accounts.jenkins.io/)

**Comment by lemeurherve** [comment]
Hello @Hanuman1359,

> for learning purpose

You don't need an account.jenkins.io account to learn Jenkins, you can run it locally without any account, see https://www.jenkins.io/doc/pipeline/tour/getting-started/ and https://www.jenkins.io/doc/book/getting-started/.

Closing this issue, feel free to reopen it if needed.
