### ISSUE TITLE
Rename `pipeline-log-fluentd-cloudwatch-plugin-developers`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3669]
### GitHub repositories

https://github.com/jenkinsci/pipeline-cloudwatch-logs-plugin

### GitHub users to have permission

N/A

### Permission level

Admin

### Justification

https://github.com/orgs/jenkinsci/teams/pipeline-log-fluentd-cloudwatch-plugin-developers is still stuck on a very old plugin name. See https://github.com/jenkinsci/pipeline-cloudwatch-logs-plugin/pull/12 + https://github.com/jenkins-infra/repository-permissions-updater/pull/932. Please rename it to the standard format, `pipeline-cloudwatch-logs-plugin-developers`.

**Comment by NotMyFault** [comment]
Renamed
