### ISSUE TITLE
Disallow issue creation in 'EVENTS' project type

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3671]
### Service(s)

Jira

### Summary

The category is unused these days, and shouldn't be enabled for new issue creation.

ref https://issues.jenkins.io/browse/EVENTS-78

**Comment by lemeurherve** [comment]
Ping @jenkins-infra/jira-admins

**Comment by timja** [comment]
(tried but Jira is loading incredibly slow for me right now)

**Comment by daniel-beck** [comment]
Switched from "Hudson permissions" to "No create permissions scheme" which seems to exist for this purpose.

**Comment by dduportal** [comment]
Is this issue closable? it looks like it's been done

**Comment by NotMyFault** [comment]
> Is this issue closable? it looks like it's been done

Yep! Thanks Daniel
