### ISSUE TITLE
Jenkins account not able to access

### ISSUE THREAD

**Issue by HarishNetula** [jenkins-infra/helpdesk#3674]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account username

admin

### jenkins.io account email

harishnetula1999@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
The Jenkins infra help desk repository is used for the infrastructure that support the Jenkins project, including https://accounts.jenkins.io .  There is no account with the email address harishnetula1999@gmail.com on accounts.jenkins.io
