### ISSUE TITLE
Invalid certificate for https://public.publick8s.jenkins.io/

### ISSUE THREAD

**Issue by simonfelding** [jenkins-infra/helpdesk#3682]
### Service(s)

Other

### Summary

Hi, the https://public.publick8s.jenkins.io/ certificate is not valid.

### Reproduction steps

1. visit https://public.publick8s.jenkins.io/

**Comment by dduportal** [comment]
Hi @simonfelding , there is no service running behind this hostnam so there is not intent to publich a certificate.

What is the problem you are facing with this?

**Comment by dduportal** [comment]
Closing as no answer back from the reporter.

Feel free to reopen with an answer if needed!
