### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by pykler** [jenkins-infra/helpdesk#3684]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

I have an account with the username `pykler` but it doesnt seem like the email is working properly. I got a 500 error when trying to reset the password

### jenkins.io account username

pykler

### jenkins.io account email

pykler@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by lemeurherve** [comment]
> Perfect works, do you know how to change the password? I can't seem to find that screen.

https://accounts.jenkins.io/passwordReset ?

**Comment by pykler** [comment]
it creates a new temp password but then I cant figure out how to change it. Not a big deal though

**Comment by lemeurherve** [comment]
Oh, when you're logged in, you can change your password in your profile: https://accounts.jenkins.io/myself/
