### ISSUE TITLE
401 from repo.jenkins-ci.org

### ISSUE THREAD

**Issue by tomasbjerre** [jenkins-infra/helpdesk#3685]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I was unable to release my plugin:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/release.sh

[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project generic-webhook-trigger: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:generic-webhook-trigger:pom:1.86.6 from/to [maven.jenkins-ci.org](http://maven.jenkins-ci.org/) (https://repo.jenkins-ci.org/releases): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/generic-webhook-trigger/1.86.6/generic-webhook-trigger-1.86.6.pom, status: 401 Unauthorized -> [Help 1]

Tried the curl command, gave me 401:

curl -u "tomasbjerre:X" https://repo.jenkins-ci.org/setup/settings.xml
{
  "errors" : [ {
    "status" : 401,
    "message" : "Bad credentials"
  } ]

Logged on to https://accounts.jenkins.io/myself/ and changed the password, still same with the curl command.

Temporary problem?

### jenkins.io account username

tomasbjerre

### jenkins.io account email

tomas.bjerre85@gmail.com

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/setup/settings.xml

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/270

**Comment by dduportal** [comment]
First pass of diagnostics:

- With my "normal" (e.g. non admin) user `dduportal` , I confirm that the `curl` command  to https://repo.jenkins-ci.org/setup/settings.xml works for me => it is not a global problem on Artifactory.
- The fact that the `curl` commands answers HTTP/401 with your Jenkins Account username + password means that the problem does not seem to be around your setup in your environment.



We're going to check your account in both accounts.jenkins.io (which works fine for you as per your initial message) and in Artifactory to see what is happening.


@tomasbjerre can you remember when was the last time your password worked with Artifactory (repo.jenkins-ci.org)?

**Comment by dduportal** [comment]
It looks like (to be confirmed) that we are in the same case as #3680 .

Your account setup has been updated manually in Artifactory (ref. https://github.com/jenkins-infra/helpdesk/issues/3680#issuecomment-1651716208) : you should be able to log-in now .

Can you confirm by closing the issue or by commenting the result @tomasbjerre ?

**Comment by tomasbjerre** [comment]
I think latest was Jul 10 when I made this release:
https://github.com/jenkinsci/git-changelog-plugin/commit/ef412a43feb641b81ccf1f73a8ab6f61ddb72d85

**Comment by tomasbjerre** [comment]
Yes it works now, thanks.
