### ISSUE TITLE
Downgrade to HTTP when there is no trailing /

### ISSUE THREAD

**Issue by Wadeck** [jenkins-infra/helpdesk#3686]
### Service(s)

jenkins.io

### Summary

When we request a page on jenkins.io without a trailing slash, there is a redirection to HTTP, before another one to HTTPS.

**Expected behavior**
Stay with HTTPS

### Reproduction steps

When executing `curl -v https://www.jenkins.io 2>&1 | grep -i location:`, no output.
But when there is a path:
```
$ curl -v https://www.jenkins.io/doc 2>&1 | grep -i location:
$ < location: http://www.jenkins.io/doc/
```

When browsing, the page is then redirected back to HTTPS.

**Comment by dduportal** [comment]
At first quick glance, it sounds like a setting in fastly as the server triggering the redirect is Varnish (Jenkins infra uses Nginx for jenkins.io):

```
$ curl -v https://www.jenkins.io -o /dev/null 2>&1 | grep -i via
< via: 1.1 varnish
$ curl -v https://www.jenkins.io/doc -o /dev/null 2>&1 | grep -i via
< via: 1.1 varnish
```

I don't know if it is a setting we can change but this should help to properly diagnose

**Comment by dduportal** [comment]
Should be fixed by https://github.com/jenkins-infra/fastly/pull/86

**Comment by dduportal** [comment]
Ok, now that SSL is enforced on Fastly's side, the problem should be gone.

BUT it is not: the redirect is defined on the original website and was cached by fastly:

```
$ curl -v https://www.origin.jenkins.io/doc -H 'Host: www.jenkins.io' 2>&1 | grep -i location:
< location: http://www.jenkins.io/doc/
```

(`www.origin.jenkins.io` hostname bypasses fastly and directly hits our `publick8s` cluster)

**Comment by dduportal** [comment]
The culprit is https://github.com/jenkins-infra/kubernetes-management/blob/01984688ec75b9e90c79071b0714c14a1afe3290/config/jenkinsio.yaml#L6

Fix proposal here: https://github.com/jenkins-infra/kubernetes-management/pull/4220

**Comment by dduportal** [comment]
Fix applied, but it seems like it does not work 🤦 

Going through the rabbit hole and checking if the redirect isn't triggered internally inside the backend webserver (https://github.com/jenkins-infra/helm-charts/blob/main/charts/jenkinsio/templates/nginx-configmap.yaml)

**Comment by dduportal** [comment]
Found the issue: https://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect 

Incoming OR in the next hours

**Comment by dduportal** [comment]
Patch deployed: it works as expected!

```shell
$ curl -v https://www.jenkins.io/doc 2>&1 | grep -i location:
$ < /doc/
```
