### ISSUE TITLE
unable to auth to artifactory (via UI)

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#3691]
### Service(s)

Artifactory

### Summary

I am unable to login to artifactory (`teilo`) via the UI.

I am using the same username/password combo that works on issues.jenkins.io which should be correct.

(I do not know if my maven deployment token is still working or not as I have not attempted to publish anything recently)

### Reproduction steps

https://repo.jenkins-ci.org/ui/login/

<img width="384" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/494726/5152ff0d-f27c-4468-ae16-796aac920754">

**Comment by dduportal** [comment]
Can you retry? I've applied the same configuration change in Artifactory as we did for #3685 and #3680

**Comment by jtnord** [comment]
working now thanks @dduportal !
