### ISSUE TITLE
401 from repo.jenkins-ci.org

### ISSUE THREAD

**Issue by damianszczepanik** [jenkins-infra/helpdesk#3692]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

When publishing new release of the plugin I got
```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project build-name-setter: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:build-name-setter:pom:0.0-beta from/to maven.jenkins-ci.org (https://repo.jenins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-name-setter/0.0-beta/build-name-seter-0.0-beta.pom, status: 401 Unauthorized -> [Help 1]
```

Then I found that
- I'm not able to authorize to get https://repo.jenkins-ci.org/setup/settings.xml
- Logging to https://repo.jenkins-ci.org/ui/packages ends with `Login has failed. Due to Incorrect username/password or locked user.`
- I can login to https://issues.jenkins.io/
- I have changed my password but it did not help
- Last time I was able to publish new release https://github.com/jenkinsci/build-name-setter-plugin/releases/tag/build-name-setter-2.2.1
- I'm able to publish artifacts to [sonatype](https://oss.sonatype.org)

Looks like #3685

### jenkins.io account username

dszczepanik

### Which URL are you trying to login at?

repo.jenkins-ci.org

**Comment by dduportal** [comment]
Hi @damianszczepanik thanks for this carefully crafted issue report (that helps!).

> Looks like https://github.com/jenkins-infra/helpdesk/issues/3685

You're correct, the issue seems to be the same as #3685 .

I've updated the setup of your account in Artifactory, you should be able to log-in and release your plugin again.

**Comment by damianszczepanik** [comment]
I can login to repository.
Plugin is released https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-name-setter/2.3.0/
