### ISSUE TITLE
Plugin not found on marketplace

### ISSUE THREAD

**Issue by huytunguyenn** [jenkins-infra/helpdesk#3696]
### Service(s)

release.ci.jenkins.io, plugins.jenkins.io

### Summary

Summary: I cannot find the release of my plugin on the plugin site.

I have followed the steps in [Performing a Plugin Release](https://www.jenkins.io/doc/developer/publishing/releasing-cd/). These are merged PR:
- Hosting request: https://github.com/jenkins-infra/repository-permissions-updater/issues/3418
- Repository for plugin has been forked: https://github.com/jenkinsci/kobiton-integration-plugin
- Upload permissions request: https://github.com/jenkins-infra/repository-permissions-updater/pull/3459
- Enable CD permissions: https://github.com/jenkins-infra/repository-permissions-updater/pull/3460
- Enable CD in the repository: https://github.com/jenkinsci/kobiton-integration-plugin/pull/1

The release job here: https://ci.jenkins.io/job/Plugins/job/kobiton-integration-plugin is showing successfully. But the plugin does not appear on the [plugin site](https://plugins.jenkins.io). I expect it to be at: https://plugins.jenkins.io/kobiton-integration.

If there are any remaining tasks left or mistakes I've made, please let me know. 
Thank you.

**Comment by NotMyFault** [comment]
Initial indexing takes some time, given the artifact appeared in the release repository just an hour ago, I'd wait a bit.
I _think_ the plugin site builds every 3 or 4 hours.

**Comment by NotMyFault** [comment]
Edit: It's 3 hours: https://plugins.jenkins.io/kobiton-integration/

**Comment by NotMyFault** [comment]
ref https://github.com/jenkins-infra/helpdesk/issues/3697 why it didn't pick up the plugin the first time
