### ISSUE TITLE
Cannot log into JFrog Artifactory anymore

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3699]
### Service(s)

Artifactory

### Summary

My username / password that works for issues.jenkins.io and previously worked for repo.jenkins-ci.org is no longer working for repo.jenkins-ci.org.  Since we'll be using that username / password during the brownout test tomorrow, I need it enabled.

### Reproduction steps

1. `mvn clean deploy` fails from one of my plugins that previously passed

**Comment by dduportal** [comment]
Configuration updated in Artifactory: can you retry logging-in in repo.jenkins-ci.org?
