### ISSUE TITLE
no more access to https://github.com/jenkinsci/blueocean-plugin

### ISSUE THREAD

**Issue by olamy** [jenkins-infra/helpdesk#3701]
### GitHub repositories

for whatever reason it looks accout `olamy` doesn't have any more push access to https://github.com/jenkinsci/blueocean-plugin

### GitHub users to have permission

@olamy 

### Permission level

Admin

### Justification

I use to have it.

**Comment by timja** [comment]
you have direct admin access:

![image](https://github.com/jenkins-infra/helpdesk/assets/21194782/488a4225-9f57-4b56-a3c3-f64a9f719cfa)

check you can push to other things and verify your local setup

**Comment by olamy** [comment]
yes it works now again. sorry but it looks some `/block-release` has been activated which I had to de activate....
I didn't know anything about this process...
