### ISSUE TITLE
Unable to reset password for sdlc-coin account

### ISSUE THREAD

**Issue by shuyangfang** [jenkins-infra/helpdesk#3704]
### Type(s) of account issue

I didn't receive any email

### Summary

Hi,

I’m unable to get the password reset email for the sdlc-coin@twosigma.com Jenkins account with username sdlc-coin.

I was never able to fully set up this account, so it’s kind of stuck in purgatory atm. If it’s easier, could it just be deleted, and I can recreate it?

Thanks!

### jenkins.io account username

SDLC-Coin

### jenkins.io account email

sdlc-coin@twosigma.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Completed and confirmed by the recipient.
