### ISSUE TITLE
Unable to access JFrog

### ISSUE THREAD

**Issue by mig42** [jenkins-infra/helpdesk#3707]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hi,

I'm unable to access JFrog to publish a new release of the plugin I maintain, plasticscm-plugin, with my account 'mig42'. I'm able to log in to accounts.jenkins.io and issues.jenkins.io with that account and the password I use in accounts.jenkins.io, but I can't access repo.jenkins-ci.org - I always get a 401 Bad Credentials in response, or "Login has failed. Due to Incorrect username/password or locked user.".

If I go to https://repo.jenkins-ci.org/ui/login/forgot-password, I get "The specified user is not permitted to reset his password".

What should I do? Other maintainers for this plugin aren't experiencing the same issue. I tried changing my password in accounts.jenkins.io, and it doesn't change anything in repo.jenkins-ci.org.

Thanks for your help!

Cheers,
Miguel

### jenkins.io account username

mig42

### jenkins.io account email

miguel.gonzalez@unity3d.com

### Which URL are you trying to login at?

repo.jenkins-ci.org

**Comment by lemeurherve** [comment]
Hello @mig42, you're in the same case as #3700

I don't have the necessary permissions on the Artifactory to fix your issue but it will be taken care of quickly by someone who does.

**Comment by dduportal** [comment]
Hi @mig42 thanks for raising this issue.

Following #3700, I've manually updated your user account in Artifactory: can you retry logging-in?

By the way, any attempt to change your password should be done in accounts.jenkins.io where allour LDAP public users are centrally managed.

**Comment by mig42** [comment]
Hi @lemeurherve and @dduportal , thanks for answering so fast! 

@dduportal I'm able to access Artifactory both through the web portal and also the Maven settings snippet endpoint as well 
https://repo.jenkins-ci.org/setup/settings.xml

Thanks a lot! This was a massive help 🙂
