### ISSUE TITLE
Add JDK21 support for developers to pre-built and try

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3709]
### Service(s)

ci.jenkins.io

### Summary

Offer java 21 within agents for R & D

Todo list:

- [x] Add to packer images 
  - [x] https://github.com/jenkins-infra/packer-images/pull/769 -> https://github.com/jenkins-infra/packer-images/releases/tag/1.20.0
  - [x] https://github.com/jenkins-infra/jenkins-infra/pull/3006 
- [x] Add the "tool" JDK21 in ci.jenkins.io (as https://github.com/jenkins-infra/jenkins-infra/pull/3003)
- [x] Add the Windows container image:
  - [x] Implement the new JDK21 Windows image: https://github.com/jenkins-infra/docker-inbound-agents/pull/98
  - [x] Initial implementation on ci.jenkins.io: https://github.com/jenkins-infra/jenkins-infra/pull/3012
  - [x] Tracking the custom image on ci.jenkins.io: https://github.com/jenkins-infra/jenkins-infra/pull/3013
  - [x] Pin the ci.jenkins.io image to a digest (automated PR) - https://github.com/jenkins-infra/jenkins-infra/pull/3014
  - [x] Update acceptance test to also test spinning up a `maven-21-windows` agent - https://github.com/jenkins-infra/acceptance-tests/commit/80004602b8b34235891da3c9af2c05c5caf68aee
- ~[ ] Add the corresponding updatecli manifest (as https://github.com/jenkins-infra/jenkins-infra/pull/2503)~
- [x] Add to the documentation here https://github.com/jenkins-infra/documentation/blob/main/ci.adoc
- [x] Update check agent availability : https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability
- [x] Announce on the Developer Mailing List

**Comment by smerle33** [comment]
windows container image not available yet : https://github.com/jenkins-infra/docker-inbound-agents/pull/98

**Comment by smerle33** [comment]
the updatecli will have to wait the end of beta, as the naming and zip extract folder may change

**Comment by smerle33** [comment]
acceptance test should be ok https://github.com/jenkins-infra/acceptance-tests/pull/37
but still a weird error on the CPU stages

**Comment by dduportal** [comment]
Initial (partial) announcement https://groups.google.com/g/jenkinsci-dev/c/XjR48-1oVfw

**Comment by basil** [comment]
I handled the ATH portion in https://github.com/jenkinsci/acceptance-test-harness/pull/1321.
