### ISSUE TITLE
Please delete my account at "account.jenkins.io"

### ISSUE THREAD

**Issue by turbolocust** [jenkins-infra/helpdesk#3713]
### Type(s) of account issue

I want my account to be deleted

### Summary

I would like to ask you to delete my account with the username "mfubl". I registered it through a company e-mail-address, through which I never received any login details. As a result, I created another account with a private e-mail address. Please understand, that I am not going to publish my company e-mail address here, but do not hesitate to contact me there if you need any confirmation.

### jenkins.io account username

mfubl

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Thanks for the request.  I've sent an email message to your business email address requesting confirmation of the deletion.  After a reply to that confirmation email, we'll delete the account.

**Comment by MarkEWaite** [comment]
Acknowledgment received and account has been deleted.
