### ISSUE TITLE
CD releases failing (invalid token on trusted.ci.jenkins.io)

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3714]
### Service(s)

trusted.ci.jenkins.io

### Summary

Builds are passing but CD is failing to update:

https://trusted.ci.jenkins.io:1443/job/repository-permissions-updater/34639/console

```
16:33:23  2023-08-12 15:33:18.056+0000 [id=1]	INFO	o.c.g.r.c.PlainObjectMetaMethodSite#doInvoke: POST request to https://repo.jenkins-ci.org/access/api/v1/tokens returned error: HTTP 401 Unauthorized
16:33:23  2023-08-12 15:33:18.056+0000 [id=1]	WARNING	o.c.g.r.c.PlainObjectMetaMethodSite#doInvoke: Failed to generate token for jenkinsci/workflow-cps-global-lib-plugin
16:33:23  java.io.IOException: Server returned HTTP response code: 401 for URL: https://repo.jenkins-ci.org/access/api/v1/tokens
```

Happened on the last 3 builds today

**Comment by timja** [comment]
If I try generate an API token manually in artifactory I get this:

<img width="417" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/21194782/84349192-57a8-4d83-8978-e1591c6b375d">

**Comment by dduportal** [comment]
As the user used by the RPU job does not seem to have any identity token (I guess it was expired), I've generated a new one as admin and inserted it in trusted.ci.jenkins.io. New RPU build started to see if it can renew the API tokens.

----

Related or unrelated, the following message shows up in artifactory:

<img width="965" alt="Capture d’écran 2023-08-14 à 09 53 05" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/55774147-28c1-49e2-9703-83acedf5705d">

If the RPU user was using an API key then it explains the behavior.

**Comment by dduportal** [comment]
The build of the [RPU](jenkins-infra/repository-permissions-updater) is now in progress without the HTTP/401: the tokens should be updated for every contributor in the next hour.

I'll send an email to the mailing list once the build is successful and we are able to confirm a CD release worked properly.

As improvement measures:

- The expiration date of the new identity token is now added in its description in trusted.ci along with its tokenID
- The jenkins-infra-team calendar now has an event at the expiry date of the new token with 5 notifications (4w, 3w, 2w, 1w and 1d before) for next year
  - Note that only Artifcatory admins can renew this token , note all members of the jenkins-infra team
  - We did not have such an alert this year, which explain why we missed the expiry

**Comment by dduportal** [comment]
I confirm eveyrthing looks back to normal: 
- the [RPU](https://github.com/jenkins-infra/helpdesk/issues/jenkins-infra/repository-permissions-updater) job was successfull
- A CD release was done with success: https://github.com/jenkinsci/jenkins-infra-test-plugin/actions/runs/5853487727/job/15867596257


@timja Can I let you close this issue if ok for you?

**Comment by timja** [comment]
(I'd suggest leaving pinned for a day or so)

**Comment by daniel-beck** [comment]
> If the RPU user was using an API key then it explains the behavior.

When I checked the linked CSV about a week ago, no users were listed.

**Comment by daniel-beck** [comment]
> expired identity token

Would match the last login time of the user of August 12 last year. I wonder whether I defined an expiration and forgot about it, or whether it's the default. The docs are unclear, but trying to create an identity token for me (no configuration) results in one that is valid for a year.

**Comment by dduportal** [comment]
> > expired identity token
> 
> Would match the last login time of the user of August 12 last year. I wonder whether we defined an expiration and forgot about it, or whether it's the default. The docs are unclear, but trying to create an identity token for me (no configuration) results in one that is valid for a year, indicating the latter.

True, that is why i chose to define an explicit expiration (and add it to the calendar to be reminded) to avoid any bad surprise in 1 year 😅
