### ISSUE TITLE
The upload to the Maven repository fails with "401 Unauthorized"

### ISSUE THREAD

**Issue by balakine** [jenkins-infra/helpdesk#3715]
### Service(s)

Accounts

### Summary

Released global-build-stats plugin about 4 months ago, same action worked. This time it fails with 401. 

https://github.com/jenkinsci/global-build-stats-plugin/actions/runs/5842903838

**Comment by lemeurherve** [comment]
Hello @balakine, your issue is related to #3700.

I don't have the necessary permissions on the Artifactory to fix it but someone who does will take care of that soon.

**Comment by timja** [comment]
> Hello @balakine, your issue is related to #3700.

Unlikely, it will be https://github.com/jenkins-infra/helpdesk/issues/3714

Closing as a duplicate

**Comment by timja** [comment]
You can work around it by putting personal credentials into your GitHub secrets temporarily

**Comment by lemeurherve** [comment]
My mistake, thanks @timja.
