### ISSUE TITLE
Account creation mail was not sent

### ISSUE THREAD

**Issue by SHIBIKANTH** [jenkins-infra/helpdesk#3716]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I tried creating jenkins account but unable to receive jenkins confirmation mail.
Hence tried multiple times and got stuck in account spam issue.

### jenkins.io account username

shibikanth07_r

### jenkins.io account email

shibikanth07@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by MarkEWaite** [comment]
The account that you've attempted to create does not exist on accounts.jenkins.io.  The email address you referenced  does not exist on accounts.jenkins.io.  Please try again to create the account.

**Comment by dduportal** [comment]
Closing as no answer from the reporter.
