### ISSUE TITLE
username issue

### ISSUE THREAD

**Issue by ITsomesh** [jenkins-infra/helpdesk#3718]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @ITsomesh , could you fill the form correctly otherwise we won't be able to help.

We need your username and email for accounts.jenkins.io.

**Comment by dduportal** [comment]
Closing as no answers from the reporter
