### ISSUE TITLE
Add user to stashNotifier Developers group

### ISSUE THREAD

**Issue by sghill** [jenkins-infra/helpdesk#3720]
### GitHub repositories

https://github.com/jenkinsci/stashnotifier-plugin

### GitHub users to have permission

@sghill

### Permission level

Maintain

### Justification

Looking to help maintain this plugin (enable CD, create releases, merge PRs). Current maintainer @scaytrace has [approved](https://github.com/jenkinsci/stashnotifier-plugin/pull/340#issuecomment-1680856797) adding an additional maintainer.

**Comment by NotMyFault** [comment]
Added!
