### ISSUE TITLE
Unable to release plugin 401

### ISSUE THREAD

**Issue by accelq** [jenkins-infra/helpdesk#3723]
### Service(s)

ci.jenkins.io

### Summary

https://github.com/jenkinsci/accelq-ci-connect-plugin

401 error on below action
https://github.com/jenkinsci/accelq-ci-connect-plugin/actions/runs/5938161871/job/16102030554#step:9:169

**Comment by NotMyFault** [comment]
See https://www.jenkins.io/doc/developer/publishing/releasing-cd/#enable-cd-permissions. CD starts working once the next token refresh run was successful.

**Comment by accelq** [comment]
Could you please explain it? I did not understand
https://github.com/jenkins-infra/helpdesk/issues/3723 - Infra PR `merged`

**Comment by dduportal** [comment]
> Could you please explain it? I did not understand #3723 - Infra PR `merged`

The PR https://github.com/jenkins-infra/repository-permissions-updater/pull/3492 was merged ~24 min ago which triggered an automated process often referred as "RPU" (for Repository Permission Updater as the GitHub repository).

This job finished executing ~5 min ago and is responsible for generating the tokens used by the CD process to deploy releases from GitHub action to Artifactory (repo.jenkins-ci.org).

But as I can see in https://github.com/jenkinsci/accelq-ci-connect-plugin/actions/runs/5938161871/job/16102030554#step:4:160, the release of your plugin was attempted ~ 15 min ago: the token was not generated yet so empty token means no authentication (HTTP/401).

You may retry now, as the RPU seems to have successfully generated the token.

The usual pattern is that RPU runs every 3 hours to generate new tokens which are valid 4 or 5 hours: if it fails, better to wait 3 more houre for the next run.

**Comment by dduportal** [comment]
Closing as everything looks good on infrastructure side.

Feel free to reopen if it fails again: in that case we'll have to search for a problem (but everything looks good).
