### ISSUE TITLE
401 when publishing new version of HCL AppScan plugin

### ISSUE THREAD

**Issue by mattmurp** [jenkins-infra/helpdesk#3724]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hi,

I'm trying to publish a new version of the [HCL AppScan Jenkins plugin](https://plugins.jenkins.io/appscan/) using the Maven release plugin, which is what I have always done. However, I'm now getting the following error when publishing:

_**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project appscan: Failed to deploy artifacts: Could not transfer artifact com.hcl.security:appscan:hpi:1.2.0 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/com/hcl/security/appscan/1.2.0/appscan-1.2.0.hpi, status: 401 Unauthorized -> [Help 1]**_

My credentials are in the settings.xml file, so I'm not sure why this has suddenly stopped working. I tried going to https://repo.jenkins-ci.org , but I was unable to login. I then tried resetting my password using the "Forgot Password" link, but I get the error "**_The specified user is not permitted to reset his password._**".

### jenkins.io account username

mattmurp

### jenkins.io account email

matthew.murphy@hcl.com

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/releases/ during a deployment via Maven.

**Comment by MarkEWaite** [comment]
Sorry for the disruption @mattmurp.  There was an unexpected configuration change from the artifact repository hosting team that may be affecting you.  We'll need an Artifactory administrator to check your account on Artifactory.

**Comment by mattmurp** [comment]
Thanks @MarkEWaite.

**Comment by dduportal** [comment]
It looks like there is a new problem in JFrog's Artifactory: as explained in https://github.com/jenkins-infra/helpdesk/issues/3700, we (artifactory administrators) have to update each faulty user setup by enabling the "Disable Internal Password" option.

But today, any tentative at updating a userr profile through the JFrog UI leads to an error `encoded Password must be in format iterations$salt$hash`.

I'm sorry @mattmurp for the inconvenience, we're going to try with the Artifactory API: I'll update the issue here with a comment when it will be ok for your account.

**Comment by mattmurp** [comment]
Thanks for your help @dduportal .

**Comment by dduportal** [comment]
Hello @mattmurp , as explained in https://github.com/jenkins-infra/helpdesk/issues/3700#issuecomment-1691292723 I found a workaround (`curl` always wins in the end :trollface: ).

Can you retry as I successfully upgraded your account?

**Comment by mattmurp** [comment]
Thanks @dduportal. I was able to successfully deploy our plugin. I'll close this issue now. I appreciate your help.
