### ISSUE TITLE
plugins.jenkins.io does not show up new release

### ISSUE THREAD

**Issue by accelq** [jenkins-infra/helpdesk#3725]
### Service(s)

plugins.jenkins.io

### Summary

https://github.com/jenkinsci/accelq-ci-connect-plugin/actions/runs/5947704568/job/16130197723#step:4:41

This a successful build of `maven-cd/release` job, I expect it to show a new release build in https://plugins.jenkins.io/accelq-ci-connect/releases/

Is it correct?

**Comment by dduportal** [comment]
Hi @accelq , the plugin.jenkins.io deployment is driven by the following pipeline: https://github.com/jenkins-infra/plugin-site/blob/master/Jenkinsfile_k8s.

In particular, https://github.com/jenkins-infra/plugin-site/blob/master/Jenkinsfile_k8s#L55 tells us that it has a 3 hours cron trigger: it means you usually have to wait maximum 3 hours before checking plugins.jenkins.

I've triggererd manually a build to have a delivery for you: it is now delivered: https://plugins.jenkins.io/accelq-ci-connect/releases/

Thanks for contributing to the Jenkins ecosystem!
