### ISSUE TITLE
WIndows downloadd page not working

### ISSUE THREAD

**Issue by ATadBM** [jenkins-infra/helpdesk#3726]
### Problem with this page

[Jenkins download and deployment](https://www.jenkins.io/download/) page[source file](https://github.com/jenkins-infra/jenkins.io/tree/master/content/download/index.html.haml)

### Expected behavior

click the windows link under download (both releases) and be taken to an installer page

### Actual behavior

clicked on windows link (tried both releases) and a blank page with the text not found comes up

**Comment by lemeurherve** [comment]
Both https://get.jenkins.io/windows-stable/2.414.1/jenkins.msi and https://get.jenkins.io/windows/2.420/jenkins.msi return a 404 "Not found" page.

**Comment by smerle33** [comment]
2.414.1 is now available for windows
next : 2.420

**Comment by dduportal** [comment]
Both MSI files are now available. Sorry for the inconvenience, I mis-configured (twice) the release system when switching agents to JDK17 (#3072) but it is now fixed and working as expected.
