### ISSUE TITLE
Rajnneel

### ISSUE THREAD

**Issue by Denish-Sen** [jenkins-infra/helpdesk#3729]
### Type(s) of account issue

I've lost my password, I've been blocked by the anti-spam system

### Summary

I need to create a new accoungt coz my am not able to login to my current account

### jenkins.io account username

Rajneel

### jenkins.io account email

s222611779@deakin.edu.au

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
As I can see in the logs, you tried to create an account at least 4 times in the same web browser session which triggered the anti spam system.

Can you try to create your account only once inside a private browser session to avoid any kind of Cookie issue please?

**Comment by dduportal** [comment]
Closing as no answer back from the requester
