### ISSUE TITLE
forgot username and ppassword

### ISSUE THREAD

**Issue by vagdevi-123** [jenkins-infra/helpdesk#3732]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

I forgot my jenkins account username and password and while trying to reset using email, Iam not receiving any reset mail from jenkins.

### jenkins.io account email

boyivagdevi@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
There is no account on accounts.jenkins.io for the email address boyivagdevi@gmail.com .  

Maybe you're confusing the Jenkins account system that controls access to https://ci.jenkins.io and https://issues.jenkins.io and https://repo.jenkins-ci.org with an account system that controls access to a Jenkins controller in your organization.  

Maybe you're using the wrong email address?

I'm closing this issue on the assumption that there is nothing the Jenkins infrastructure team can do to help with the issue.
