### ISSUE TITLE
I didn't receive password reset email

### ISSUE THREAD

**Issue by hyma86** [jenkins-infra/helpdesk#3734]
### Type(s) of account issue

I've lost my password

### jenkins.io account username

hdommaraju

### jenkins.io account email

hdommaraju@iccsafe.org

### Which URL are you trying to login at?

account.jenkins.io/passwordReset
https://accounts.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @hyma86 there is no account with this username or email. It looks like you want to access a Jenkins instance which is unrelated to the accounts.jenkins.io directory (which is for ci.jenkins.io or issues.jenkins.io).

Closing as no action from the Jenkins infrastructure team: you need to contact your administrators.
