### ISSUE TITLE
JDK21: change from nightly builds to weekly `ea` builds in the infra

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/helpdesk#3736]
### Service(s)

ci.jenkins.io

### Summary

* EA builds are already used by Jenkins official images (for the `jdk21-preview`)
* Allow tracking JDK21 version with updatecli
* Should simplify the puppet configuration for our infra

**Comment by smerle33** [comment]
> 💡 As discussed together, we have to start with https://github.com/jenkins-infra/packer-images
> 
> A few details:
> 
> > EA builds are already used by Jenkins official images (for the jdk21-preview)
> 
> Example: https://github.com/jenkinsci/docker/blob/f31b562b7346db0e2176acc7ed687458f08baf9f/21/debian/bookworm/hotspot/Dockerfile#L4-L18
> 
> > Should simplify the puppet configuration for our infra
> 
> Files that might (or might not) need an update:
> 
>     * Puppet template which generates the temurin download URLs depending on the JDK version and platforms: https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/jdk-adoptium-url.erb
> 
>     * Puppet template which generates the JCasC configuration for JDK tool installation: ~https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/jdk-adoptium-url.erb~ https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/jenkinscontroller/casc/tools.yaml.erb
> 
>     * Puppet "common" hieradata configuration (e.g. values passed to the aforementioned templates) for JDK21 for all controllers: https://github.com/jenkins-infra/jenkins-infra/blob/7d9447958f77d0186f70e3e8c54fd09bdfbf431f/hieradata/common.yaml#L205-L217
> 
>     * Puppet "common" hieradata configuration (e.g. values passed to the aforementioned templates) for the usual JDK versions (that should be the only source of truth which `updatecli` should update): https://github.com/jenkins-infra/jenkins-infra/blob/7d9447958f77d0186f70e3e8c54fd09bdfbf431f/hieradata/common.yaml#L252-L257
> 
>     * Puppet "addition" hieradata configuration for `ci.jenkins.io` only (merged with the common hieradata config) for JDK21: https://github.com/jenkins-infra/jenkins-infra/blob/7d9447958f77d0186f70e3e8c54fd09bdfbf431f/hieradata/clients/controller.ci.jenkins.io.yaml#L113-L126
> 
> 
> > Allow tracking JDK21 version with updatecli
> 
> That one should be the last step of course :)

I would add the vagrant common.yaml in hieradata to test the tools installation of the jdk21 with vagrant.

**Comment by smerle33** [comment]
all set with `jdk21: 21+35-ea-beta` in puppet (`jenkins-infra`) and `kubernetes-management` with updatecli

**Comment by smerle33** [comment]
reopening because of missing updatecli within `packer-images` for jdk21

**Comment by smerle33** [comment]
can now be closed after https://github.com/jenkins-infra/packer-images/pull/805
