### ISSUE TITLE
forgot username, how to reset it?

### ISSUE THREAD

**Issue by luckloa** [jenkins-infra/helpdesk#3738]
### Service(s)

Accounts

### Summary

I forgot username, how to reset it?

**Comment by MarkEWaite** [comment]
The help desk is used to track issues with the Jenkins infrastructure.  Your request seems to be a request for help with a local Jenkins account or a request for help with something we cannot provide.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for questions.
