### ISSUE TITLE
SSL certificate for ci.jenkins.io expires in 23 days

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3740]
### Service(s)

ci.jenkins.io

### Summary

The SSL certificate for https://ci.jenkins.io expires 19 Sep 2023.  That is 23 days from today.  That is surprising, since the SSL certificate is usually renewed automatically once it is within 28 days of expiration.

### Reproduction steps

1. Open web browser to https://ci.jenkins.io
2. Check the SSL certificate for the site.  Mine shows the following:

![ssl-certificate-expiration-date](https://github.com/jenkins-infra/helpdesk/assets/156685/fbd236e9-f5a4-4423-b86d-b4b037650d2d)

**Comment by dduportal** [comment]
Checking the logs on the ci.jenkins.io VM shows the following error:

```
Failed to renew certificate ci.jenkins.io with error: Missing command line flag or config entry for this setting:
Please choose an account
Choices: [<redacted>...]
```

Continuing analysis...

**Comment by dduportal** [comment]
Checking:

- ci.jenkins.io did not indicate a new certificate
- But the renewal was successful as per the logs and certificates on the file system

After digging up a bit, it looks like the `certbot` command has been run long time ago on this VM with renewal hook specified in the command line option (or might be the old configuration of the puppet letsencrypt module).
This hook would have been persisted in the former "account" (see above) but we deleted it

Opened https://github.com/jenkins-infra/jenkins-infra/pull/3044 to fix this problem by specifying the renewal hook command `systemctl reload apache2` in the `cli.ini` so it is always run.

**Comment by dduportal** [comment]
Fix applied and deployed, the certificate was force-renewed with full success.

New expiration date: `Thu, 30 Nov 2023 05:04:51 GMT`
