### ISSUE TITLE
Unable to package jenkins plugin for local testing using mvn package

### ISSUE THREAD

**Issue by accelq** [jenkins-infra/helpdesk#3741]
### Service(s)

jenkins.io

### Summary

Hi, I'm trying to run the command `mvn package` to package my jenkins plugin and test on local environment, getting the below error

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.aq:accelq-ci-connect:999999-SNAPSHOT (C:\accelq\accelq-ci-connect-plugin\pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ com.aq:accelq-ci-connect:${changelist}, C:\accelq\accelq-ci-connect-plugin\pom.xml, line 15, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

### Reproduction steps

execute `mvn package` command under repo "https://github.com/jenkinsci/accelq-ci-connect-plugin"

**Comment by dduportal** [comment]
@accelq I assume you found a solution on this problem? I wasn't able to reproduce it (tried on a fresh new VM in a public cloud to ensure no cache and no Jenkins infra settings).
