### ISSUE TITLE
Add maven-plugin repository to maven-plugin-developers team?

### ISSUE THREAD

**Issue by sghill** [jenkins-infra/helpdesk#3743]
### Service(s)

GitHub

### Summary

`@jenkinsci/maven-plugin-developers` does not have access to `jenkinsci/maven-plugin`. Could it be added?

### Reproduction steps

1. View validation failure for the conventional team name on https://github.com/jenkinsci/maven-plugin/pull/317
2. Confirm [team exists](https://github.com/orgs/jenkinsci/teams/maven-plugin-developers/repositories), but does not have access to the repository

**Comment by NotMyFault** [comment]
I added the repository team.
