### ISSUE TITLE
IntelliJ plugin builds fail on Windows because Gradle cannot cleanup

### ISSUE THREAD

**Issue by duemir** [jenkins-infra/helpdesk#3744]
### Service(s)

ci.jenkins.io

### Summary

Builds of https://github.com/jenkinsci/idea-stapler-plugin seem to consistently fail on Windows agent.

For example https://ci.jenkins.io/job/Plugins/job/idea-stapler-plugin/job/PR-160/2/execution/node/43/log/

```
10:22:17  FAILURE: Build failed with an exception.
10:22:17  
10:22:17  * What went wrong:
10:22:17  Execution failed for task ':clean'.
10:22:17  > java.io.IOException: Unable to delete directory 'C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build'
10:22:17      Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
10:22:17      - C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build\tmp\.cache\expanded\expanded.lock
10:22:17      - C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build\tmp\.cache\expanded
10:22:17      - C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build\tmp\.cache
10:22:17      - C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build\tmp
```

### Reproduction steps

Re-run https://github.com/jenkinsci/idea-stapler-plugin/pull/160/checks

**Comment by dduportal** [comment]
Adding to the infra team milestone, but please note that we don't know anything about Gradle so that might take some time to investigate

**Comment by lemeurherve** [comment]
FTR, by removing the `clean` gradle task (not needed on ci.jenkins.io ephemeral agents) the build succeeded: https://ci.jenkins.io/job/Plugins/job/idea-stapler-plugin/job/PR-160/3/console
https://github.com/jenkinsci/idea-stapler-plugin/blob/fc066b9d0310dc20d0f225d83504b7bb6c51391f/Jenkinsfile#L32
```diff
-     String command = "gradlew ${gradleOptions.join ' '} clean check assemble"
+     String command = "gradlew ${gradleOptions.join ' '} check assemble"
```

Would you like me to open a PR on the plugin repo?
