### ISSUE TITLE
BOM release failed with Artifactory permission denied

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3754]
### Service(s)

Artifactory

### Summary

The [plugin bill of materials build job on the master branch](https://ci.jenkins.io/job/Tools/job/bom/job/master/2106/) was successful, so I started the release action.  The [first attempt of the release action](https://github.com/jenkinsci/bom/actions/runs/6213387310/job/16864391482) failed with the error message 

```
Could not transfer artifact io.jenkins.blueocean:blueocean-jwt:hpi:1.27.7 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): GET request of: io/jenkins/blueocean/blueocean-jwt/1.27.7/blueocean-jwt-1.27.7.hpi from repo.jenkins-ci.org failed: Connection reset -> [Help 1]
```
The [second attempt of the release action](https://github.com/jenkinsci/bom/actions/runs/6213571779/job/16864759157) failed with the error message:

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:37 min
[INFO] Finished at: 2023-09-17T12:35:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project bom-weekly: Failed to deploy artifacts: Could not transfer artifact io.jenkins.tools.bom:bom-weekly:pom:2445.vb_b_334b_cfb_a_08 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authorization failed for https://repo.jenkins-ci.org/releases/io/jenkins/tools/bom/bom-weekly/2445.vb_b_334b_cfb_a_08/bom-weekly-2445.vb_b_334b_cfb_a_08.pom, status: 403 Forbidden -> [Help 1]
```

### Reproduction steps

1. Run the ["cd" action](https://github.com/jenkinsci/bom/actions/workflows/cd.yaml) on the plugin bill of materials to release a new version of the plugin bill of materials
2. Monitor the log file to see the results

**Comment by MarkEWaite** [comment]
[Third attempt to release](https://github.com/jenkinsci/bom/actions/runs/6213683899/job/16864954426) also failed.  Failure was the same message as the second attempt.

**Comment by dduportal** [comment]
It looks like the first attempt failed due to a network issue in GHA.

it usually leads to partially deployed releases which cannot be overriden during the 2nd attempt.

to validate/invalidate this hypothesis, could you try to increment the release version and retry ?

**Comment by MarkEWaite** [comment]
> It looks like the first attempt failed due to a network issue in GHA.
> 
> it usually leads to partially deployed releases which cannot be overriden during the 2nd attempt.
> 
> to validate/invalidate this hypothesis, could you try to increment the release version and retry ?

I see in my email that there is a partially deployed release.  I think that confirms the hypothesis.  I've committed a new change to the master branch of the bom repository.  I'll launch a new build.  Roughly 6 hours from now we'll know if that was successful.  I'm assuming it will be successful and closing this issue.  If it fails, I will reopen it.
