### ISSUE TITLE
Builds of `jenkinsci/jenkins` are failing on ci.jenkins.io due to launchable update from 1.66.0 to 1.75.0

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3756]
### Service(s)

ci.jenkins.io

### Summary

All builds are failing with the following error:

> [2023-09-19T18:13:25.060Z] + launchable record build --name jenkins-Core-jenkins-PR-8508-1 --source jenkinsci/jenkins=.
[2023-09-19T18:13:29.675Z] Launchable recorded 1 commit from repository /home/jenkins/agent/workspace/Core_jenkins_PR-8508
[2023-09-19T18:13:29.777Z] Can't get commit hash. Do you run command under git-controlled directory? If not, please set a directory use by --source option.

Build: https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8508/1

I suspect this is caused by https://github.com/jenkins-infra/packer-images/pull/746, deployed to prod today in https://github.com/jenkins-infra/jenkins-infra/pull/3073 because older PRs built with the older launchable version are successful.

### Anything else?

Concerning the security release tomorrow, there should be no impact, given security releases are staged and built independently of ci.j, but commits pushed will fail to build.

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/packer-images/releases/tag/1.26.1 is being released (~1h of build and publish) and we'll deploy it to ci.jenkins.io to reverte launchable to 1.66.0 while keeping the other updates on agents.

**Comment by dduportal** [comment]
> Concerning the security release tomorrow, there should be no impact, given security releases are staged and built independently of ci.j, but commits pushed will fail to build.

We are monitoring the advisory today, we can always rollback to previous image version is it causes mayhem (but launchable is not expected to be used in the release process)

**Comment by dduportal** [comment]
https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8508/3/ is building without error as launchable 1.66 is back
