### ISSUE TITLE
`database-postgresql-plugin` doesn't show latest release on update-center

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3757]
### Service(s)

plugins.jenkins.io

### Summary

Hi,

While opening https://github.com/jenkinsci/database-postgresql-plugin/pull/101 I realized that the update-center doesn't show latest published version of `database-postgresql-plugin`

https://repo.jenkins-ci.org/artifactory/public/io/jenkins/plugins/postgresql-api/ Latest is `17.va_a_cfd7e514d4`
https://plugins.jenkins.io/postgresql-api/ Update center show `42.3.3`

Regards,

**Comment by MarkEWaite** [comment]
The concept of "latest" is determined by a version number sort, not by a date stamp sort, at least as far as I know.  The `17.xx` is considered "older" than the `42.3.3` release.  I think you'll need to submit enough commits to the repository to increase the count of commits beyond 42, then release a new version of the plugin.

**Comment by jonesbusy** [comment]
Thanks! I didn't realize was due to version comparison. I will check with maintainers what we can do

**Comment by jonesbusy** [comment]
Solved by https://github.com/jenkinsci/postgresql-api-plugin/pull/61
