### ISSUE TITLE
Remove Oracle Cloud project and tools

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3761]
Same reason as https://github.com/jenkins-infra/helpdesk/issues/3760.

The following elements need to be removed or archived:

- [x] Remove jenkins-infra/oracle terraform Job from infra.ci.jenkins.io
  - [x] Project from JobDSL/JCasc - https://github.com/jenkins-infra/kubernetes-management/pull/4441
  - [x] Remove credentials from sops - https://github.com/jenkins-infra/charts-secrets/commit/c2a87517598265a7f69283d1892a64b14f778e33
- [x] Remove remnants of Oracle VMs from jenkins-infra/jenkins-infra if any - https://github.com/jenkins-infra/jenkins-infra/pull/3085
- [x] Archive jenkins-infra/oracle terraform git project - https://github.com/jenkins-infra/oracle#jenkins-infra-on-oracle
- [x] Remove terraform-states related projects
  - Removed resources: https://github.com/jenkins-infra/terraform-states/commit/28bfbe860e88b93678ff3c9ca879168cf57ed1ff
  - Removed leftovers terraform outputs: https://github.com/jenkins-infra/terraform-states/commit/112825fa4ad8a110291036e14f34482bf0db50b0
  - Removed the project: https://github.com/jenkins-infra/terraform-states/commit/ad1006c8f45b1440bb3d0223fea8c7f3dcd888fb
- [x] Remove SSO integration resources between Azure and Oracle
- [x] Remove tokens and remaining cloud resources from Oracle Cloud
- [ ] Close the Oracle Cloud account (@MarKEWaite)
- [ ] Confirm Oracle Cloud account payments are complete (@MarkEWaite)

**Comment by dduportal** [comment]
Update (with the help of @MarkEWaite):

- We removed all last remaining resources
- We checked that we have "admin Oracle SSO" accounts for Mark and I (before removing Azure federation)
- The AzureAD Federation SAML was removed on Oracle Cloud side (todo: remove integration elements from azure)
- Mark is following the last billing steps before closing the account

**Comment by dduportal** [comment]
The "Azure Enterprise Application" named `Oracle Cloud Infrastructure` was deleted in Azure Cloud. It was the last remnant as far as I can tell.

This issue is now assigned to @MarkEWaite until the last Oracle Cloud bill is paid and the account is closed.

**Comment by MarkEWaite** [comment]
Oracle cloud bill for September has been paid.  Earlier invoices are still being discussed with the Oracle Cloud collections department.
