### ISSUE TITLE
I lost an access to publish my repo

### ISSUE THREAD

**Issue by DuMaM** [jenkins-infra/helpdesk#3765]
### Service(s)

Artifactory

### Summary

Hi,
I'm a maintainer of Crowd2 plugin.
Today i was trying to release it and sadly, there was an auth error.

I didn't change anything in config, so it should work.

```[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  19.863 s
[INFO] [INFO] Finished at: 2023-09-27T14:47:07+02:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [WARNING] The requested profile "consume-incrementals" could not be activated because it does not exist.
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project crowd2: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:crowd2:pom:4.1.0 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/crowd2/4.1.0/crowd2-4.1.0.pom, status: 401 Unauthorized -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException```

I'm also no more allowed to generate token to set up my mvn.

**Comment by dduportal** [comment]
Hi @DuMaM , the error `401 Unauthorized` is unrelated to permissions (that would be a 403).

Either:
- Your maven tooling does not use the user/password setup with with your `~/.m2/settings.xml` setup
- Or you changed your Jenkins LDAP password on accounts.jenkins.io and did not update your `~/.m2/settings.xml`
-  Or your account has been removed.

Can you check that you can authenticate to repo.jenkins-ci.org?

**Comment by DuMaM** [comment]
Hi,
Thanks for the fast replay.
Yes i'm able to login into repo.jenkins-ci.org.

I tried to click set me up, but i got a response:
<img width="1019" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/9051964/47875ce8-cebf-4184-b5be-8c15ab5035a0">
Even though I copy and paste my password from password manager.

**Comment by dduportal** [comment]
Thanks! So it means:

- Your LDAP account works as expected (accounts.jenkins.io) and you use the proper password
- Artifactory did not disable your account (as you can login). Did a quick check: your account has the proper permissions.

It means your Maven setup is most probably the reason why it is failing.


You have to follow the jenkins.io instructions: https://www.jenkins.io/doc/developer/publishing/releasing-manually/#artifactory-credentials-for-maven to set up your Maven settings.xml.

**Comment by DuMaM** [comment]
I did exactly what was written in link you shared.
I compared my settings with one returned by curl and they are the same.
Fun fact - it was updated due to my last issues. xD

I set up my env with this script.
https://github.com/jenkinsci/crowd2-plugin/blob/master/_init.sh

The question is why i cannot generate new token from UI?

**Comment by dduportal** [comment]
> The question is why i cannot generate new token from UI?

The identity token is a recent feature in Artifactory that we don't use (yet?). So the permission model template in jenkins-infra/repository-permissions-updater might not have taken in account this permission.

It is not needed at all for releasing a plugin manually like you are trying to.

> I set up my env with this script.
https://github.com/jenkinsci/crowd2-plugin/blob/master/_init.sh

Thanks for sharing! 

> I did exactly what was written in link you shared.
I compared my settings with one returned by curl and they are the same.

Ok, so it means there is a misconfiguration somewhere else (`pom.xml`? parent pom?) which makes Maven not using the coupld username/password when releasing.

The main attention point is that the `<id>` must map to the `<id> of the repository in the `pom.xml` defined by the`<distributionManagement>` (used to deploy) or the repository definition (to authenticate download requests).

In your case:

- The "dowload" repository id is `repo.jenkins-ci.org` as per https://github.com/jenkinsci/crowd2-plugin/blob/96ed3f73abf32ad92902168306b6b23459ef0abc/pom.xml#L75
- The "deploy" repository id is `maven.jenkins-ci.org` as per https://github.com/jenkinsci/plugin-pom/blob/e401ce1de3334bc971c879cc5bd141a7d438e92a/pom.xml#L47C11-L47C31 (pom parent 4.71 as per https://github.com/jenkinsci/crowd2-plugin/blob/96ed3f73abf32ad92902168306b6b23459ef0abc/pom.xml#L7)

Can you check the `settings.xml` file and eventually make sure that both repositories have a corresponding `server` section (same username/password for both) and retry?

> Fun fact - it was updated due to my last issues. xD

Heh, "Continuous Integration" 😄

**Comment by DuMaM** [comment]
I will check this today 👍 thanks

**Comment by DuMaM** [comment]
Thanks, this worked
