### ISSUE TITLE
rating.jenkins.io is down

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3767]
### Service(s)

Other

### Summary

https://rating.jenkins.io/rate/result.php gives 503

<img width="586" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/21194782/ccd8d2d0-5598-4900-ada9-fb7e4af51426">

Reported at https://www.reddit.com/r/jenkinsci/comments/16tzoi0/community_feedback_in_changelog/

**Comment by lemeurherve** [comment]
Looking on publick8s cluster for `rating`, I've noticed there is no pod in its namespace.

While checking for errors in kubernetes-management job logs, I've noticed this error:

> ERROR: Unable to pull Docker image "jenkinsciinfra/helmfile:3.0.17". Check if image tag name is spelled correctly.

Thus the PR to revert its version, but it didn't work, same error with `3.0.14`.

Testing a pull locally, I've got this error:

> Error response from daemon: Head "https://registry-1.docker.io/v2/jenkinsciinfra/helmfile/manifests/3.0.17": Get "https://auth.docker.io/token?account=hlemeur&scope=repository%3Ajenkinsciinfra%2Fhelmfile%3Apull&service=registry.docker.io": EOF

I think there is an issue with Docker Hub.

**Comment by lemeurherve** [comment]
> I think there is an issue with Docker Hub.

Confirmed: https://www.dockerstatus.com/pages/incident/533c6539221ae15e3f000031/6515dbc89fabff05350ae18d

> [Investigating] We received reports of time outs while authenticating or pulling from docker hub registry. We are working on identifying the cause and mitigating the issue.

**Comment by dduportal** [comment]
The root cause of this issue is the same as https://github.com/jenkins-infra/helpdesk/issues/3768:

- Helmfile reported last deployment was `Sat Sep 23 11:16:49 2023 UTC`.
- Problem caused by https://github.com/jenkins-infra/kubernetes-management/pull/4366

**Comment by dduportal** [comment]
Thanks @lemeurherve @timja for taking care of this!
