### ISSUE TITLE
Post-Mortem: Plugin Health Score was down

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3768]
### Service(s)

Other

### Summary

This issue is a post-mortem of an incident about "PHS" ("Plugin Health Score" - https://plugin-health.jenkins.io/probes) service.

Thanks @alecharp for driving it to our attention!

* Timeline: PHS was down from 23 2023-09-23 11:56:30 UTC (last deployment) until 2023-09-27 18:40:27 UTC (fixed up deployment)
* Root cause: https://github.com/jenkins-infra/kubernetes-management/pull/4405 deployed a new version of the helm chart which aimed at removing the service account. The pod never restarted and the associated deployment was marked as unavailable (`0/1`) because the service account was deleted *before* updating the deployment, leading to an unexpected state with no pod running.
* Fix: the 27 Sept. after being pointed by @alecharp that the service was down, we had to rollback the helm release and then trigger the deployment again
* Operation traces:

  ```shell
  $ kubectl -n plugin-health-scoring get deployments.apps 
  NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
  plugin-health-scoring   0/1     0            0           82d
  
  $ kubectl -n plugin-health-scoring describe deployments.apps plugin-health-scoring
  # ...
  Conditions:
    Type             Status  Reason
    ----             ------  ------
    Progressing      True    NewReplicaSetAvailable
    Available        False   MinimumReplicasUnavailable
    ReplicaFailure   True    FailedCreate
  OldReplicaSets:    plugin-health-scoring-65666c54d8 (0/0 replicas created), plugin-health-scoring-76b668ddcf (0/0 replicas created), plugin-health-scoring-5dc8b95c5d (0/0 replicas created)
  NewReplicaSet:     plugin-health-scoring-5698bb7d46 (0/1 replicas created)
  Events:            <none>
  
  $ helm -n plugin-health-scoring ls
  plugin-health-scoring   plugin-health-scoring   4               2023-09-23 11:56:30.432800478 +0000 UTC deployed plugin-health-scoring-2.2.0                
  
  $ helm -n plugin-health-scoring rollback plugin-health-scoring
  
  $ helm ls -n plugin-health-scoring                            
  NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                            APP VERSION
  plugin-health-scoring   plugin-health-scoring   5               2023-09-27 18:40:27.913823 +0200 CEST   deployed        plugin-health-scoring-2.1.11  
  ```

----

#### What should we do differently to avoid this problem next time?

* The service https://plugin-health.jenkins.io/probes is not monitored in datadog so we were not alerted. Action point: add a datadog synthetic alert
* I was not careful enough and only checked the result of the `helmfile` operation from the jenkins-infra/kubernetes-management job. A change such as removing resources of an helm chart requires paying attention to the whole set of deployments/statefulsets. 
* Next time we have an operation with helm charts consisting in remove resources linked to others, we must do it in 2 steps: 1. removing the link 2. removing resources

**Comment by dduportal** [comment]
Note: https://github.com/jenkins-infra/helpdesk/issues/3767 has the same root cause (and same improvements)

**Comment by dduportal** [comment]
Created https://github.com/jenkins-infra/datadog/pull/231

**Comment by lemeurherve** [comment]
We should also add a synthetic test for `incrementals-publisher` which had the same issue IIRC.

**Comment by dduportal** [comment]
Closing as monitoring was added 👍
