### ISSUE TITLE
not able to log in

### ISSUE THREAD

**Issue by junkhnn19** [jenkins-infra/helpdesk#3771]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Created an account, keeps saying account doesnt exist

### jenkins.io account username

khannaa

### jenkins.io account email

arjun.khannaa@paddypowerbetfair.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
An email for passord reset has been sent to your email, please follow the instructions on it.
