### ISSUE TITLE
plugin site backend OOM killed

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3774]
### Service(s)

plugins.jenkins.io

### Summary

while checking on deployments on our publick8s kubernetes instance, I noticed that the plugin-site backend pod was restarted for OOMKilled:

```
│ NAMESPACE↑                  NAME                                                                 PF     READY         RESTARTS STATUS           CPU      MEM     %CPU/R     %CPU/L     %MEM/R     %MEM/L IP                NODE                                     AGE          │
│ plugin-site                 plugin-site-backend-7fcb4c77c8-z294l                                 ●      1/1                277 Running            9     1940          1          0        189         94 10.100.13.24      aks-x86medium-20522204-vmss00000i        8d           │
│ plugin-site                 plugin-site-frontend-59bfb957c4-289cl                                ●      1/1                  0 Running            2       12          2          2         38         38 10.100.4.30       aks-x86medium-20522204-vmss000005        12d          │
│ plugin-site                 plugin-site-frontend-59bfb957c4-l6gl2                                ●      1/1                  0 Running            2       26          2          2         82         82 10.100.13.17      aks-x86medium-20522204-vmss00000i        8d           │
│ plugin-site                 plugin-site-issues-54f968bd64-7cszz                                  ●      1/1                  0 Running           20      123        n/a        n/a        n/a        n/a 10.100.13.18      aks-x86medium-20522204-vmss00000i        8d   
``` 

277 restart as for now.

**Comment by smerle33** [comment]
TLTR : incompatibility of the application image with `cgroup v2` and the problem has started after the kubernetes upgrade : `Cluster was recently upgraded to Kubernetes 1.25`

--------------
First step is to check on datadog and if we go back in time for 4 month, we can see that the memory issues and pod restart for the plugin-site-backend, are matching a specific date beginning of june (around june 8th) : 

<img width="716" alt="Capture d’écran 2023-10-06 à 08 55 06" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/c28a914e-e3c3-407a-8beb-072f0669d752">

<img width="693" alt="Capture d’écran 2023-10-06 à 08 55 23" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/bb7e1702-4d2a-41d2-aaf4-57d25e3499b7">

to confirm we can check in azure, within `Resource health` from the publick8s cluster in `diagnose and solve problems` and then node health : 

<img width="1148" alt="Capture d’écran 2023-10-06 à 09 06 21" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/ad20e867-ecf8-4d93-aedb-fc082fd61d5c">


<img width="1177" alt="Capture d’écran 2023-10-06 à 09 06 33" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/d1463131-5510-4f85-8094-7e4261f7ad24">


and the solution is explained here 

<img width="1155" alt="Capture d’écran 2023-10-06 à 09 06 41" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/172c294d-c212-4562-b88c-b8c1fc9a8a5f">


So we need to work on the image underlying the plugin-site-backend : https://github.com/jenkins-infra/plugin-site-api
to make sure it use a patched version of jdk that is compliant with cgroup v2 (https://github.com/jenkins-infra/plugin-site-api/blob/416279518ff3444904c28b1ef3aa56ca3ff7d38b/Dockerfile#L1) with a parent image like `jetty:9-jdk8` or more specific like `jetty:9.4.52-jdk8-eclipse-temurin` 

as a side work, we may also want to move the build of this image from trusted.ci to infra.ci

**Comment by smerle33** [comment]
locked by https://github.com/jenkins-infra/helpdesk/issues/3778

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/helpdesk/issues/3778 is fixed. The new plugin-site-api container image deployed is working as expected and keeps being OOM-killed: we need to deploy the latest version with the changes from https://github.com/jenkins-infra/plugin-site-api/pull/119

**Comment by dduportal** [comment]
Helm chart update with a successfull test of the new memory limit finally enforced: https://github.com/jenkins-infra/helm-charts/pull/855

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/kubernetes-management/pull/4527 deployed the new image to production. No service outage and the new pod seems to use the expected amount of memory:

<img width="1586" alt="Capture d’écran 2023-10-11 à 17 23 11" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/0314c923-4da5-4bf8-a90a-6c7601bc4faf">
