### ISSUE TITLE
Can not retrieve my Jenkins account

### ISSUE THREAD

**Issue by FrogDevelopper** [jenkins-infra/helpdesk#3775]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

Hello,

I'd like to adopt the plugin [multibranch-build-strategy-extension](https://plugins.jenkins.io/multibranch-build-strategy-extension/), and for this I would like to use my "old" account in Jenkins, but my password doesn't work anymore, I didn't receive the reset password mail and if I try to re-create my account, I got the error "account legall_benoit already exist"

### jenkins.io account username

legall_benoit

### jenkins.io account email

legall.benoit@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset
accounts.jenkins.io/signup

**Comment by MarkEWaite** [comment]
Thanks for your interest in adopting the plugin.  I'll send a separate authentication check and will then assist with your password reset.

**Comment by MarkEWaite** [comment]
Authentication check has been sent.

**Comment by FrogDevelopper** [comment]
Thank you
Fork has been created

**Comment by MarkEWaite** [comment]
Issue resolved.
