### ISSUE TITLE
Update machines to maven 3.9.5

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3776]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

Maven 3.9.5 has been released and our agents should be updated to it.

**Comment by MarkEWaite** [comment]
Thanks.  Automation will detect the new release of Apache Maven and start the deployment processes.

**Comment by dduportal** [comment]
Reminder of the process (for knowledge sharing):

- Automation on jenkins-infra/packer-images is the first milestone. Once a PR on this image is opened, we can work on validating, merging and triggering a new release of the image
- Once the packer image is released, automation open 2 PRs to both kubernetes-management and jenkins-infra/jenkins-infra (puppet) proposing to update base image
- Once new image is deployed to production, then automation will take care opening PRs for both jenkins-infra/docker-inbounds-agents (windows container images) and for the Jenkins tools version

**Comment by dduportal** [comment]
Updated:

>     * Automation on jenkins-infra/packer-images is the first milestone. Once a PR on this image is opened, we can work on validating, merging and triggering a new release of the image

Done:
- https://github.com/jenkins-infra/packer-images/pull/834
- https://github.com/jenkins-infra/packer-images/releases/tag/1.29.0

>     * Once the packer image is released, automation open 2 PRs to both kubernetes-management and jenkins-infra/jenkins-infra (puppet) proposing to update base image

- Tested on infra.ci with https://github.com/jenkins-infra/kubernetes-management/pull/4503 and subsequent https://github.com/jenkins-infra/kubernetes-management/pull/4509

>     * Once new image is deployed to production, then automation will take care opening PRs for both jenkins-infra/docker-inbounds-agents (windows container images) and for the Jenkins tools version

- Deployed to ci.jenkins.io with https://github.com/jenkins-infra/jenkins-infra/pull/3100 followed by:
  - Tools update: https://github.com/jenkins-infra/jenkins-infra/pull/3105
  - Windows container updates https://github.com/jenkins-infra/jenkins-infra/pull/3106

>     * Send an email to the mailing list to let user know

https://groups.google.com/g/jenkinsci-dev/c/vQWSRhQFIgA
