### ISSUE TITLE
Migrate to GitHub documentation on sonar plugin

### ISSUE THREAD

**Issue by ericg138** [jenkins-infra/helpdesk#3777]
### Service(s)

plugins.jenkins.io

### Summary

The documentation on the [sonar plugin](https://plugins.jenkins.io/sonar/) is pointing to the content on the wiki. According to the [migration documentation](https://www.jenkins.io/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github), everything should be configured correctly on the repository to get the documentation from GitHub.

Am I missing something? Or is some action needed on your side? Thanks.

**Comment by lemeurherve** [comment]
Hello @ericg138, I opened https://github.com/jenkins-infra/update-center2/pull/744 to remove the wiki override.

After its merge and the execution of the Update Center job, the plugins site should use the README as description for SonarQube.

Thanks for the link to the wiki migration by the way, it made me realize we should update it with additional instructions.

**Comment by lemeurherve** [comment]
All good:

<img width="894" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/955a5205-4b01-4319-b90a-07b3e4c7b73c">
