### ISSUE TITLE
Plugin Site API is not building since february

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3778]
### Service(s)

plugins.jenkins.io

### Summary

by trying to solve https://github.com/jenkins-infra/helpdesk/issues/3774
we openned a PR with @gounthar https://github.com/jenkins-infra/plugin-site-api/pull/119 but the build failed and we discovered that it was failing on main since a few month : https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/master/

```
19:17:39  + mvn -PgeneratePluginData
19:17:40  [ERROR] Could not create local repository at /.m2/repository -> [Help 1]
19:17:40  [ERROR] 
19:17:40  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
19:17:40  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
19:17:40  [ERROR] 
19:17:40  [ERROR] For more information about the errors and possible solutions, please read the following articles:
19:17:40  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
19:17:40  [Pipeline] }
```

**Comment by dduportal** [comment]
Update:

- https://github.com/jenkins-infra/plugin-site-api/pull/120 and https://github.com/jenkins-infra/plugin-site-api/pull/122 fixed the build
- trusted.ci.jenkins.io was able to deploy the new image to DockerHub

Next step: Update https://github.com/jenkins-infra/helm-charts/blob/4ef605b4c3cec8e2584963d66cb59e94586cfaa2/charts/plugin-site/values.yaml#L9 in the helm chart and deploy it (watching it carefully)

**Comment by dduportal** [comment]
Update: https://github.com/jenkins-infra/helm-charts/pull/848

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/kubernetes-management/pull/4520 was deployed to production, no error (we checked plugins.origin.jenkins.io home page, searched for a plugin and a plugin page, and re-checked 1 hour after on plugins.jenkins.io for decache).

**Comment by gounthar** [comment]
Well done, folks! 👏 
On to the next step. 😊
