### ISSUE TITLE
Please block spammer anikasharma8855@gmail.com

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#3780]
### Service(s)

Jira

### Summary

It seems a spammer has created or hijacked a Jira account:
"anikasharma8855@gmail.com (Jira)" <noreply@jenkins.io>

Last comment in:
https://issues.jenkins.io/browse/JENKINS-67521

### Reproduction steps

n/a

**Comment by MarkEWaite** [comment]
User blocked and offensive comment has been deleted
