### ISSUE TITLE
track the new jdk21 version from adoptium

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3783]
### Service(s)

Other

### Summary

stop tracking early available versions for jdk21 and prefer the official release from adoptium

**Comment by dduportal** [comment]
Update:

- Packer image: PR https://github.com/jenkins-infra/packer-images/pull/839 was merged. 
  - Note that it was required to also change the shell script code along updatecli with https://github.com/jenkins-infra/packer-images/pull/860
  - Released in https://github.com/jenkins-infra/packer-images/releases/tag/1.32.0
  - But not deployed to production yet (ref. https://github.com/jenkins-infra/jenkins-infra/pull/3126)

**Comment by dduportal** [comment]
Update:

- Packer image with 21+35 GA was deployed, followed by an update to 21.0.1+12 GA, deployed by https://github.com/jenkins-infra/jenkins-infra/pull/3149
- The PR for JDK21 (except GA) for puppet (controller and build agent) is ready: https://github.com/jenkins-infra/jenkins-infra/pull/3113

TODO:
- Kubernetes management (tool for infra.ci/release.ci)

**Comment by dduportal** [comment]
Update:

- https://github.com/jenkins-infra/jenkins-infra/pull/3113 merged and deployed with success
- 2 JDK21 updates PR opened and deployed with success: https://github.com/jenkins-infra/jenkins-infra/pull/3165/files and https://github.com/jenkins-infra/jenkins-infra/pull/3166/files

TODO:

    Kubernetes management (tool for infra.ci/release.ci)

**Comment by dduportal** [comment]
Update : infra.ci updated to have jdk21

todo: track jdk versions on infra.ci

**Comment by dduportal** [comment]
Last step before closing: https://github.com/jenkins-infra/kubernetes-management/pull/4634
