### ISSUE TITLE
Publishing Jenkins Security Scan rules as packages

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#3789]
### Service(s)

GitHub

### Summary

[Jenkins Security Scan](https://github.com/jenkins-infra/jenkins-security-scan) is a workflow for GH Actions that builds a Jenkins plugin and runs a CodeQL scan on it with [the Jenkins-specific rules](https://github.com/jenkins-infra/jenkins-codeql) only.

It's possible to [publish rules as a "CodeQL Pack"](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/publishing-and-using-codeql-packs) hosted as packages in a GH org. I'd like to do that to prepare for retiring the jenkins-security-scan workflow long term, as the same can be accomplished by the default CodeQL workflow with [minimal changes](https://github.com/daniel-beck-org/sample-plugin/blob/6eee2422ac1c67f324749c46db2a8f903a9d1a7d/.github/workflows/codeql.yml#L56-L59) and we would not need to support the other steps ourselves, instead relying on GH's action.

Is it OK for me to publish packages for this in `jenkins-infra`, or perhaps `jenkinsci`? It seems packages can be published to any org, but then they cannot be associated with a repo outside the org. Currently the rules reside in `jenkins-infra`, so that would be a natural location for them.

**Comment by timja** [comment]
Sounds good to me

**Comment by daniel-beck** [comment]
I cannot make the package I uploaded public:
> <img width="749" alt="Screenshot 2023-10-27 at 14 15 51" src="https://github.com/jenkins-infra/helpdesk/assets/1831569/37227a29-241a-4e89-bd08-134748d24b42">

**Comment by lemeurherve** [comment]
https://github.com/orgs/jenkins-infra/packages/container/package/jenkins-codeql-lib and https://github.com/orgs/jenkins-infra/packages/container/package/jenkins-codeql linked to jenkins-codeql GitHub repository.

To do that, I've scrolled down a bit and choose the repository to link. (As instructed by @daniel-beck on IRC)

**Comment by lemeurherve** [comment]
With the permission of @dduportal I've activated the public publication of packages on @jenkins-infra:

<img width="862" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/992f39fd-548f-4b4f-907a-4be4688dda10">

**Comment by daniel-beck** [comment]
I think I have all I need now, thanks!
