### ISSUE TITLE
Need Github permissions for Developers

### ISSUE THREAD

**Issue by kishorikumar** [jenkins-infra/helpdesk#3792]
### GitHub repositories

https://github.com/jenkinsci/synopsys-security-scan-plugin

### GitHub users to have permission

@zaman-akib
@jahid1209
@devmehtasynopsys
@blackduck-serv-builder
@sig-tithi

### Permission level

Maintain

### Justification

Co-workers need maintainer access.

**Comment by kishorikumar** [comment]
@NotMyFault Can you please help us with this issue for permission.

**Comment by NotMyFault** [comment]
Added.
