### ISSUE TITLE
Need Github repository permissions for Developers

### ISSUE THREAD

**Issue by kishorikumar** [jenkins-infra/helpdesk#3793]
### GitHub repositories

https://github.com/jenkinsci/synopsys-security-scan-plugin

### GitHub users to have permission

@spurohitsynopsys
@lsynopsys

### Permission level

Write

### Justification

Co-workers need write access.

**Comment by kishorikumar** [comment]
@NotMyFault Can you please help us with this issue for permission.

**Comment by NotMyFault** [comment]
Added.
