### ISSUE TITLE
Archive Jira component `extra-tool-installers-plugin`

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3794]
### Service(s)

Jira

### Summary

Hi,

Issues were migration to GitHub. Please archive component `extra-tool-installers-plugin`

https://github.com/jenkins-infra/repository-permissions-updater/pull/3578

Thanks

**Comment by dduportal** [comment]
It's done, the component has been archived:

<img width="550" alt="Capture d’écran 2023-10-21 à 19 19 48" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/ff5e1532-999a-4f93-a3ab-861e4d459c7c">
