### ISSUE TITLE
Need Github permissions for Developers

### ISSUE THREAD

**Issue by kishorikumar** [jenkins-infra/helpdesk#3796]
### GitHub repositories

https://github.com/jenkinsci/synopsys-security-scan-plugin

### GitHub users to have permission

@sadmananik
@maksudur-rahman-maruf

### Permission level

Maintain

### Justification

Co-workers need maintainer access.

**Comment by kishorikumar** [comment]
@NotMyFault Can you please help us with this issue for permission.

**Comment by NotMyFault** [comment]
Added, no need to ping me every time.
