### ISSUE TITLE
Lost write access to credentials-plugin

### ISSUE THREAD

**Issue by rsandell** [jenkins-infra/helpdesk#3797]
### GitHub repositories

https://github.com/jenkinsci/credentials-plugin 

### GitHub users to have permission

@rsandell

### Permission level

Admin

### Justification

For unknown reasons I've lost write access to credentials plugin. I am a member of all the relevant teams from what I can see.

**Comment by batmat** [comment]
Done. I gave Write access to the `company-cloudbees-developers` team.
(I pondered on giving them Admin like for the "credentials developer" group, but chose for now only "Write".

![image](https://github.com/jenkins-infra/helpdesk/assets/223853/d66b53ec-770c-4fcc-ac86-2776fd52189d)
`

**Comment by lemeurherve** [comment]
Thanks @batmat!
