### ISSUE TITLE
I forgot my Jenkins password please help me

### ISSUE THREAD

**Issue by MEL1902** [jenkins-infra/helpdesk#3800]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

when I register the Jenkins Id with MAC OS the password was automatically registered. when I login again the password didn't save in my computer and I don't understand I couldn't find any register email with Jenkins  please help me 
my user name is mel1902

thank you

### jenkins.io account username

mel1902

### jenkins.io account email

1902otamel@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by MarkEWaite** [comment]
There is no user account for mel1902 on https://accounts.jenkins.io .  Check with your local Jenkins administrator.
