### ISSUE TITLE
Branch protection exception on Jenkins Security Scan repos

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#3802]
### Service(s)

GitHub

### Summary

I'd like to be able to merge my own PRs in https://github.com/jenkins-infra/jenkins-codeql and https://github.com/jenkins-infra/jenkins-security-scan without reviews, as those repos have very little engagement from other contributors. A branch protection exception should do it, alternatively admin permissions.

**Comment by lemeurherve** [comment]
I've added the team @jenkins-infra/security as exception to these repo branch protections:

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/5319d967-fffc-4526-97a2-b7ab46b1c18b)

Could you confirm that you can merge your own pull requests on these repositories please?

**Comment by daniel-beck** [comment]
> Could you confirm that you can merge your own pull requests on these repositories please?

The UI changed to allow bypass 👍 Thanks!
