### ISSUE TITLE
Add Bruno Verachten to the GSoC team

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#3803]
### GitHub repositories

https://github.com/orgs/jenkins-infra/teams/gsoc

### GitHub users to have permission

@gounthar

### Permission level

Write

### Justification

GSoC org admins need the write permission level (as previously discussed) in order to make changes to the repo for the GSoC portions of jenkins.io.

**Comment by lemeurherve** [comment]
@gounthar I've invited to the team.
