### ISSUE TITLE
Reset/Disable 2FA for oleg-nenashev on community.jenkins.io

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/helpdesk#3804]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hello. My old phone died along with the 2FA generator for community.jenkins.io. The Discourse 2FA does not have recovery codes so I cannot log in anymore. I am an admin, so GitHub Auth does not work either

Since I do not really need admin access anymore, I suggest the following:

1. Remove the admin permissions from my account
2. Disable 2FA so that I could use GitHub authentication

### jenkins.io account username

oleg-nenashev

### Which URL are you trying to login at?

https://community.jenkins.io/

**Comment by NotMyFault** [comment]
Both actions done, you should be able to log in again 🤞
