### ISSUE TITLE
[Bug] No Retrieval method List.

### ISSUE THREAD

**Issue by freemankevin** [jenkins-infra/helpdesk#3805]
### Service(s)

ci.jenkins.io

### Summary

In the shared library, it cannot be retrieved normally.

Windows version is: `2016 Data Center`
Jenkins version is: `2.428`

![image](https://github.com/jenkins-infra/helpdesk/assets/71524776/e8f2e520-1939-4f1f-a1fe-7f328c3cb763)

![image](https://github.com/jenkins-infra/helpdesk/assets/71524776/022c7299-0f65-482e-b5f0-7cbbd3a06061)

The required plug -in is already.
![image](https://github.com/jenkins-infra/helpdesk/assets/71524776/c55169a5-306d-4fc7-89ca-41a9bae69ccd)

### Reproduction steps

Normal configuration sharing library will appear.

**Comment by freemankevin** [comment]
The required plug -in is already.
![image](https://github.com/jenkins-infra/helpdesk/assets/71524776/c55169a5-306d-4fc7-89ca-41a9bae69ccd)

**Comment by halkeye** [comment]
What does this have to do with ci.jenkins.io? It's not running a 8 year old version of Windows

**Comment by freemankevin** [comment]
So is it not compatible, or is it completely not supported in the 2016 version?

**Comment by halkeye** [comment]
I'm saying if I had the power i'd close this. This repo is for the infra that powers jenkins.io not your own install. And a shared library would be code you or your company created.

If you think it's a bug in jenkins, it needs to go-to the jenkins bug tracker. If it's a bug in the plugin then it should go-to that specific plugins bug tracker.

Since your screenshot says localhost it's definitely not jenkins.io

**Comment by freemankevin** [comment]
Okay, understand what you mean, if I want to submit this Jenkins wrong, where is the entrance location, I can't find it.

**Comment by MarkEWaite** [comment]
> Okay, understand what you mean, if I want to submit this Jenkins wrong, where is the entrance location, I can't find it.

Here's one path to find the exact component and location to report the issue:

## Help for the item with the issue

Open the help for the item that has the problem and click on the link to the plugin.

![001-help](https://github.com/jenkins-infra/helpdesk/assets/156685/d678a4cf-060d-49e0-b6c4-94fb63f0b1cd)

## Plugins site link to report an issue

Click the "Report an issue" link in the plugins page

![002-plugin-page](https://github.com/jenkins-infra/helpdesk/assets/156685/78d612c3-60f9-40f6-b32d-b095f0424dc6)

## Choose the issue type

![003-report-an-issue](https://github.com/jenkins-infra/helpdesk/assets/156685/7cc203f7-f5aa-45b8-beac-1a0d48de4278)
