### ISSUE TITLE
Update GitHub Users to Authorize as Committers to Atlassian Jira Software Cloud Plugin

### ISSUE THREAD

**Issue by rachellerathbone** [jenkins-infra/helpdesk#3806]
### GitHub repositories

https://github.com/jenkinsci/atlassian-jira-software-cloud-plugin

### GitHub users to have permission

@rachellerathbone
@joshkay10

### Permission level

Write

### Justification

We are both part of the dev team and will be working on this plugin this quarter.

**Comment by timja** [comment]
You already have permission, I've invited @joshkay10.

Please go to https://github.com/jenkinsci and accept the invite

**Comment by rachellerathbone** [comment]
Hey @timja. Where's the invite on the page you linked to?

**Comment by rachellerathbone** [comment]
Also, how does @joshkay10 accept permissions? Same link or an email? He said nothing has come through yet.

**Comment by timja** [comment]
> Hey @timja. Where's the invite on the page you linked to?

There should be a banner at the top of the page to accept the invite: https://github.com/jenkinsci.

Don't wait for an email they don't always come through spam protection or whatever, just do it in the GitHub UI

**Comment by rachellerathbone** [comment]
![Screenshot 2023-10-31 at 10 40 50 am](https://github.com/jenkins-infra/helpdesk/assets/37155488/422ce2a5-fd67-4060-b198-7725457c515d)

No banner 😭

**Comment by timja** [comment]
that's your GitHub profile not his, you already have access

**Comment by rachellerathbone** [comment]
Hmmm did you update something? I tried pushing to the repo last night and got permissions denied but now it's working...

**Comment by rachellerathbone** [comment]
> that's your GitHub profile not his,
Not exactly sure what you mean by this either. I clicked on the link you sent me and that's the page I land on?

**Comment by timja** [comment]
> Hmmm did you update something? I tried pushing to the repo last night and got permissions denied but now it's working...

When I opened this issue you already had access, I didn't touch your settings, I just invited @joshkay10

**Comment by rachellerathbone** [comment]
Weird. Oh well, it's working now 🤷‍♀️ 

Another question. In the pom file in the plugin there are a list of developers:

```
  <developers>
        <developer>
            <id>atrigueiro</id>
            <name>Amanda Trigueiro</name>
        </developer>
        <developer>
            <id>bgvozdev</id>
            <name>Boris Gvozdev</name>
        </developer>
        <developer>
            <id>gxueatlassian</id>
            <name>Gary Xue</name>
        </developer>
        <developer>
            <id>gxueatlassian</id>
            <name>Gary Xue</name>
        </developer>
    </developers>
```

What's the purpose of this? Is it just to make others aware of the core team? Should I manually add myself and Josh to this? And how do we get permissions removed from someone? Harminder is no longer on our team so it would be good to revoke his permissions if possible.
