### ISSUE TITLE
Merging core PRs doesn't cancel PR builds

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3807]
### Service(s)

ci.jenkins.io

### Summary

ref https://github.com/jenkinsci/jenkins/pull/8659#issuecomment-1784246731 and the couple of messaged below.

Apparently that's the case for plugins, but should be the case for core PRs too, especially when advancing a merge could save use a few hours of resources.

**Comment by dduportal** [comment]
Hello @NotMyFault , it is a pipeline setting (I believe a PR is needed on Core then) as the job configuration only (and already) enable the "Abort Build" option for "Orphan Item strategy".

For plugin, this is this property: https://github.com/jenkins-infra/pipeline-library/blob/ccc2b0a6ab573bb2381047aac9b495e8ad6257bb/vars/buildPlugin.groovy#L7

**Comment by dduportal** [comment]
It's weird: the behavior is already set on the `Jenkinsfile`: https://github.com/jenkinsci/jenkins/blob/01e30ea1df6dc87c0a891a7b42a4252bbce01f45/Jenkinsfile#L12

**Comment by dduportal** [comment]
And the configuration of https://ci.jenkins.io/job/Core/job/jenkins/ is below:

<img width="1285" alt="Capture d’écran 2023-11-01 à 11 02 56" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/077c87ec-6a8e-4507-aaae-50765d7f143d">

=> when a PR is merged, a webhook is sent to ci.jenkins.io, which triggers a "Scan Repository Now" detecting the PR's reference branch is gone and consider it as "Orphaned".

But there is something weird going on: I see Prs marked as "removed" but should be deleted:

<img width="1604" alt="Capture d’écran 2023-11-01 à 11 06 07" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/4143c512-fd59-493e-a3f5-71dea084ba6a">

For instance: https://github.com/jenkinsci/jenkins/pull/8669

Gotta check deeper

**Comment by dduportal** [comment]
After triggering a manual scanc, these PRs have been GC-ed.

I wonder if the GC of orphaned build isn't defered or async: that would explain.

**Comment by dduportal** [comment]
🤔 Checked in datadog: no error on the time when the PR as merged.

Last recorded log line is:

```
[2023-10-29T22:32:02.872Z] Commit message: "Update dependabot branch for LTS 2.426.x (#8659)"
```

I'm not sure if the "Scan Repository Logs" are collected though

**Comment by dduportal** [comment]
Ping @NotMyFault do you have more details to help us, it is hard to analyse the issue here (we're not sure of the exact behavior you had)

**Comment by NotMyFault** [comment]
> Ping @NotMyFault do you have more details to help us, it is hard to analyse the issue here (we're not sure of the exact behavior you had)

I didn't merge any PRs with a running build yet.

**Comment by zbynek** [comment]
@dduportal "disable concurrent builds" will prevent two parallel builds on the master/main branch after merging, but will it abort the PR build?

**Comment by dduportal** [comment]
I'm gonna close this issue as we do not have an immediate reproduction, so the infra team may focus on something else.

Please feel free to reopen with screenshots (recordings), logs etc. if you see this behavior again on ci.jenkins.io.
