### ISSUE TITLE
Start a new repo under jenkins-infra for the Jenkins Contributor Spotlight feature on jenkins.io

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#3809]
### Service(s)

GitHub, jenkins.io

### Summary

We would like to host this Gatsby.js app for the Jenkins Contributor Spotlight feature with the URL https://contributors.jenkins.io/ (i.e. with `contributors` as the [jenkins.io](https://www.jenkins.io/) subdomain. A separate PR will be opened at https://github.com/jenkins-infra/jenkins-io-components to add this URL to the header formally in a later step. 

Repo has been imported under `jenkins-infra` at https://github.com/jenkins-infra/jenkins-contributor-spotlight. 

c.c. @kmartens27 @alyssat

### Reproduction steps

N/A

EDIT @lemeurherve: detailled action plan at https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561

**Comment by MarkEWaite** [comment]
Will this be in addition to the existing content on https://stories.jenkins.io/ ?  

The current stories.jenkins.io page content is hosted at https://github.com/jenkins-infra/stories

**Comment by kmartens27** [comment]
Would it make more sense to have it as an entity on jenkins.io, like how the blog exists and has its own content, or as a separate page/content section for stories.jenkins.io?

**Comment by MarkEWaite** [comment]
I like very much that the site is being generated with Gatsby and that it has its own design.  That's aligned with the direction that @krisstern is leading with the version documentation project from Google Summer of Code.

I was curious if the current definition of stories.jenkins.io would be extended with the contributor stories or if there should be a new top level domain like https://contributors.jenkins.io

**Comment by kmartens27** [comment]
I think there are positives to both options, but having it extend the definition of stories.jenkins.io would get more visitors to that and provide a gateway for users and readers to connect to the other stories.
Having a separate domain could help with the "spotlight" feel/idea that we're going for when highlighting the contributors, but I'm not sure if there's something that could be an issue that I'm unaware of.

**Comment by krisstern** [comment]
I am wondering where is the code for the existing https://stories.jenkins.io/ hosted? Maybe I could take a look and see how easily I could integrate it to the contributor stories codebase? Or we could keep them separate to retain their different purposes? 

Personally I prefer to have the two as separate features, since that way their differences can be kept as they appear to have two very distinct energies. But I am open to exploring different options.

**Comment by lemeurherve** [comment]
For the record, here is the last infra meeting notes after discussing with @kmartens47 and @MarkEWaite on the subject:

        * Does it "increment" stories.jenkins.io (`/contributors` for instance)? or does it a secondary website such as contributors.jenkins.io?
            * Already have a 2nd website with previe as per Kris work => secondary website looks easier
            * Proposal: link in stories.jenkins.io to redirect to the new website 
            * contributors.stories.jenkins.io / users.stories.jenkins.io
        * Hypothesis of "secondary website"
            * Need to fork the repo to jenkins-infra
                * WiP: Permission
            * TODO:
                * CI (preview website)
                * Production (same as stories.jenkins.io most probably)
                * CD (extend CI to production)
    Does it “increment” stories.jenkins.io (/contributors for instance)? or does it a secondary website such as contributors.jenkins.io?
        Already have a 2nd website with previe as per Kris work => secondary website looks easier
        Proposal: link in stories.jenkins.io to redirect to the new website
        contributors.stories.jenkins.io / users.stories.jenkins.io
    Hypothesis of “secondary website”
        Need to fork the repo to jenkins-infra
            WiP: Permission
        TODO:
            CI (preview website)
            Production (same as stories.jenkins.io most probably)
            CD (extend CI to production)

Going for a distinct website like contributors.jenkins.io seems easier for now, could be revised later.

I'll update this issue with a more detailed infra TODO plan.

**Comment by lemeurherve** [comment]
The https://github.com/orgs/jenkins-infra/teams/contributor-spotlight team including @krisstern @kmartens27 and @alyssat has been created and set as maintainer of https://github.com/jenkins-infra/jenkins-contributor-spotlight

**Comment by lemeurherve** [comment]
### Plan of actions:
- [ ] CI
  - [ ] Add job to ci.jenkins.io
  - [ ] Add job to infra.ci.jenkins.io
  - [ ] Create pipeline
    - [ ] Build/lint/test/typos check
    - [ ] Netlify preview on pull request
  - [ ] Add status checks to repository branch protection
- [ ] Production
  - [ ] Add a `contributors` CNAME record to jenkins.io
  - [ ] Host the service on `publick8s` cluster
      - [ ] Nginx based helm chart
      - [ ] Storage account (with backup policy)
      - [ ] Deployment on publick8s
  - [ ] Setup Fastly cache
- [ ] CD
  - [ ] Add deployment step (from infra.ci.jenkins.io) to the pipeline 
  - [ ] ???
  - [ ] Profit

**Comment by lemeurherve** [comment]
Also, what s the correct spelling, "Contributor**s** Spotlight" or "Contributor Spotlight"?

**Comment by krisstern** [comment]
I reckon we could use "Contributors Spotlight" instead, since that may be more apt as we will be spotlighting more than 1 contributor at any one time from the look of things. Sure, we could remove "jenkins" from the current GitHub repo name.

**Comment by MarkEWaite** [comment]
> I reckon we could use "Contributors Spotlight" instead, since that may be more apt as we will be spotlighting more than 1 contributor at any one time from the look of things. Sure, we could remove "jenkins" from the current GitHub repo name.

I disagree.  I think that a spotlight in this case is intended to shine on one person at a time.  Some examples of the use of "Contributor Spotlight" include:

* Mozilla - https://developer.mozilla.org/en-US/community/spotlight/tanner-dolby
* Split Rock Review - https://www.splitrockreview.org/news/category/Contributor+Spotlight
* Making magazine - https://makingzine.com/blogs/news/contributor-spotlight-dawn-emily-clark
* Localization lab - https://www.localizationlab.org/blog/2018/9/27/contributor-spotlight
* Habitica - https://habitica.wordpress.com/category/contributor-spotlight/

When I initially searched for "Contributors Spotlight", Google search showed me "Contributor Spotlight" entries.

I like the removal of the redundant "jenkins-" prefix from the repository name.  That matches with our patterns elsewhere of not placing "jenkins-" in the repository name.

**Comment by kmartens27** [comment]
Just to echo what @MarkEWaite said, there will be a singular contributor spotlighted at a time. I also agree with removing the `jenkins` piece of the repo name as it is a bit redundant/out of line with the other repos.

**Comment by lemeurherve** [comment]
Update: CI part done 🎉 

https://github.com/jenkins-infra/contributor-spotlight/pull/15#issuecomment-1823099428

**Comment by lemeurherve** [comment]
Here we are, https://contributors.jenkins.io is alive!
