### ISSUE TITLE
I'm trying to login in my account but giving me password error

### ISSUE THREAD

**Issue by SharayuAT** [jenkins-infra/helpdesk#3813]
### Type(s) of account issue

I didn't receive any email

### Summary

after resetting password, I should get email to recover new.

### jenkins.io account username

SharayuT

### jenkins.io account email

Sharayu.tadkal@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
No such account exists on accounts.jenkins.io, either for username `SharayuT` or for email address Sharayu.tadkal@gmail.com

**Comment by dduportal** [comment]
It looks like you want to reset the account on your organization's Jenkins instance, while accounts.jenkins.io is only for the `*.jenkins.io` websites.

As such, we are closing this issue: feel free to reopen if you can explain to us what use case you have in creating an account there?
