### ISSUE TITLE
[Sponsorships] Renew DigitalOcean sponsorship for 2024

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3817]
- We currently have ~ 1750$ credit left in DigitalOcean (expiring in April 2024).
- The current rate is ~800 $ monthly => we have until middle January 2024 before we run out of credits

This issue is to track the work related to DigitalOcean sponsorship renewal for 2024:

- We have to summarize what we did, particularly focused on the "new" elements since last renewal and what we are planning
  - https://github.com/jenkins-infra/helpdesk/issues/3576
  - https://github.com/jenkins-infra/helpdesk/issues/3760
  - https://github.com/jenkins-infra/digitalocean/pull/117
  - https://github.com/jenkins-infra/helpdesk/issues/3599
  - https://github.com/jenkins-infra/helpdesk/issues/2649
- We have to evaluate how much credit should we need for 2024 given our current usage rate and what was done in 2023
- Then we contact them with these information and see if they want  us to give a testimony (blog post, podcast, something else?)
- If they are not willing to renew, then this issue will track the work related to moving resources to another provider

**Comment by lemeurherve** [comment]
Email sent to DigitalOcean to ask them for a sponsorship renewal.

**Comment by lemeurherve** [comment]
Got a response, they're happy to renew their sponsorship 🥳 
I've filled their form to ask for a renewal, will keep this issue up to date.

**Comment by lemeurherve** [comment]
DigitalOcean will renew their sponsorship at the beginning of January 2024.

We should have enough remaining credits to get going until then ($750).
If it's not the case we'll still be able to disable some resources meanwhile.

**Comment by dduportal** [comment]
For info (checked with @smerle33 today) we have 450$ of credit left on DO. As @lemeurherve is in holidays this week, I'll hand over and request credit update as mentioned above.

**Comment by dduportal** [comment]
Confirmed by email : DigitalOcean have renewed our sponsorship!

Many thanls to them!

I'm closing this issue as the infrastructure team does not have anything else to track:

<img width="433" alt="Capture d’écran 2024-01-03 à 15 20 33" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/3d368be8-bbaa-47a1-a0f3-ff7768c59b42">


**However** we will rite a blog post to greet them and we should check if we could present our use case to their technical webinars.
