### ISSUE TITLE
 [Sponsorships] Setup the secondary Azure subscription to consume the sponsor credits

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3818]
We've been given 40.000$ of Azure sponsorship credits: we should start using them as soon as possible to decrease the current Azure bill paid by the CDF for us.

This issue tracks the associated work for this.

----

Ideas on "how to consume these credits":

- Run ci.jenkins.io existing Azure ephemeral workloads:
  - ACI (Windows containers)
  - buildPlugin with Docker CE (Azure VMs)
  - ATH with Docker CE (Azure VMs) (separate from buildPlugin to ensure we can keep track of costs)
  - BOM builds (VM first, and evenyually an AKS cluster in addition to EKS)

- Run other controller ephemeral workloads: infra.ci ?

**Comment by dduportal** [comment]
Update:

- WiP on `ci.jenkins.io: add jenkins-infra/azure resources (storage account, others?) in the new subscription`
  - PR https://github.com/jenkins-infra/azure/pull/516 to split the terraform modules in order to allow multiple instanciations for the "agent" modules

**Comment by dduportal** [comment]
Update:

- Credentials on ci.jenkins.io:
  - Added `azure-jenkins-sponsorship-credential`, same as the current `azure-credential` except for the subscription ID of course
  - Updated definition of both credentials
  - Used the "Check Service Principal" on both credentials with success

- Deployed the new JCasc configuration adding the secondary Azure VM cloud with success:
  - https://github.com/jenkins-infra/jenkins-infra/pull/3189
  - trusted.ci and cert.ci had no changes (expected)
  - Successfully added the new cloud on ci.jenkins.io

Wip: validation in progress on ci.jenkins.io (top level cloud is valid but network specification on each template need to be updated: incoming puppet code changes)

**Comment by dduportal** [comment]
Update (wip):

- Cloud agent on ci.jenkins.io in the new subscription:
  - Global configuration is valid (permissions and top-level cloud configuration)
  - Template configuration to be fixed by the 2 following PRs (tested manually with success before opening PRs):
    - https://github.com/jenkins-infra/azure/pull/522
    - https://github.com/jenkins-infra/jenkins-infra/pull/3190
  - First tentative for spawning an agent gave a quota error: sent a support request to Microsoft to update quotas in the subscriptions with:
    - Regional vCPUs limit to 800, spot regional vCPUs to 800 (65 VM of each type max already set)

**Comment by dduportal** [comment]
Update:

- Quota increased by Microsoft for normal vCPUs, but they refused for spot vCPUs as they have too much spot requests these days
- Initial manual testing showed error around the disk encryption. We had to enable a feature at the subscription level () to avoid the following error:

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidParameter","message":"The property 'securityProfile.encryptionAtHost' is not valid because the 'Microsoft.Compute/EncryptionAtHost' feature is not enabled for this subscription."}]}
```

- Manual test was successful after manually disabling the spot mode (otherwise quota blocks us).

- WiP:
  - Puppet configuration to allows disabling spot at subscription level
  - Check the initial costs (as it is my credit card in the new subscription)

- TODO:
  - Add resources for ACI agents
  - Add resources for trusted.ci azure vm agents
  - Add resources for cert.ci azure vm agents

**Comment by dduportal** [comment]
Update:

- Confirmed with @MarkEWaite that we started to consume credits in the new subscription (VM agents spined up by ci.jenkins.io), billing being automatic
  - ⚠️ the cost management section of the Azure UI does NOT work for the sponsored subscription. You have to check in https://www.microsoftazuresponsorships.com/

- WiP: ACI (ci.jenkins.io)
  - [ ] Check for (secondary) controller SP permissions or create another one
  - [ ] Add the ACI JCasc config in puppet (jenkins-infra/jenkins-infra)
  - [ ] Validate manually

- Next steps:
  - trusted.ci.jenkins.io (same as ci.jenkins.io)
    - [  ] Create network resources in jenkins-infra/azure-net (vnet, subnet, peeing with trusted)
    - [  ] Create agent-related resources in jenkins-infra/azure (ephemeral agents module, addition network rules/azure ad permirssions) 
    - [ ] Add secondary controller SP as a credential in trusted.ci controller UI
    - [ ] Add JCasc agent configuration in jenkins-infra/jenkins-infra
    - [ ] Validate manually an agent

**Comment by dduportal** [comment]
Update:

- A bunch of cleanup/improvement PRs following the first wave of changes:
  - https://github.com/jenkins-infra/azure/pull/532
  - https://github.com/jenkins-infra/shared-tools/pull/130
  - https://github.com/jenkins-infra/jenkins-infra/pull/3198
- Migrated all Azure VM of ci.jenkins.io to the new subscription: https://github.com/jenkins-infra/jenkins-infra/pull/3196
- Created network resources for trusted.ci: https://github.com/jenkins-infra/azure-net/pull/175

**Comment by dduportal** [comment]
Wip: ACI for ci.jenkins.io

- ACI cloud added with success: https://github.com/jenkins-infra/jenkins-infra/pull/3208
- Allocation of ACI agents throws an error about missing permissions: work in progress
- We should add the ACI cloud name to the agent labels (like we did for kube and azure-vm-agents)

**Comment by dduportal** [comment]
Update:

- ACI on the 2nd subscription are working as expected:
  - ci.jenkins.io (through its Azure SP) was missing permissions to operate in the secondary resource group. Fixed by https://github.com/jenkins-infra/azure/pull/544, https://github.com/jenkins-infra/azure/pull/546 and https://github.com/jenkins-infra/azure/pull/547 (required hotfixes)
  - Build https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/3187/console confirmed it worked (by using a manually-added label)

Next steps:

- ci.jenkins.io:
  - Ensure ACI cloud name is added as a label to agent templates
  - Remove the "current" ACI subscription to finalize the migration to new subscription
- trusted.ci.jenkins:  add the secondary azure VM cloud (terraform azure resources and permissions, 2nd Jenkins credential, Jenkins cloud agent config)
- cert.ci.jenkins:  add the secondary azure VM cloud (terraform azure resources and permissions, 2nd Jenkins credential, Jenkins cloud agent config)

**Comment by dduportal** [comment]
Update:

- ci.jenkins.io is now only using the sponsored subscription for its ephemeral workloads
  - https://github.com/jenkins-infra/jenkins-infra/pull/3212 and removed the top-level credential (to ensure the "normal" subscription is not used anymore)

**Comment by dduportal** [comment]
Update:

- Created azure netork resources for cert.ci in https://github.com/jenkins-infra/azure-net/pull/181
- Created azure resources for:
  - trusted.ci in https://github.com/jenkins-infra/azure/pull/548
  - cert.ci in https://github.com/jenkins-infra/azure/pull/548


Next steps:

- Create credentials in both trusted.ci and cert.ci
- Set up azure secondary cloud in puppet config both trusted.ci and cert.ci
- Verify VM can be launched
- Remove former azure subscription for both trusted.ci and cert.ci
- Then (to be detailled) infra.ci is next

**Comment by dduportal** [comment]
Update: 

- ✅ Credentials created in both trusted.ci and cert.ci (name is the same across all controllers)
- ✅ Set up secondary azure VM cloud in puppet config in trusted.ci
- ✅ Tested it worked with a replay of `crawler` job using the cloud name as label

WiP:

- Removing former cloud (deleted manually, checking job execution and then puppet PR to persist setting)

Next steps:

- Set up secondary azure VM cloud in puppet config in cert.ci
- Verify VM can be launched
- Remove former azure subscription for cert.ci
- Then (to be detailled) infra.ci is next

**Comment by dduportal** [comment]
Update:

- ✅ trusted.ci.jenkins.io is now using only the sponsored subscription for ephemeral workloads
  - Note: a new top-level job named `Infra-Team-Validate-Agents` has been created (tailored for trusted.ci usage) to validate agents after a cloud change

Next steps:

- cert.ci (azure vm resources, puppet, check, cleanup)
- infra.ci (to be defined)

**Comment by dduportal** [comment]
Update:

- ✅ cert.ci.jenkins.io is now using is now using only the sponsored subscription for ephemeral workloads 
  - Note: removed the top-level credential (to ensure the "normal" subscription is not used anymore)


WiP: infra.ci.jenkins.io (VM agents)

**Comment by dduportal** [comment]
Billing check about ci.jenkins.io, cert.ci and trusted.ci: we clearly see a decrease in the current subscription's bill:

<img width="1891" alt="Capture d’écran 2023-12-18 à 15 52 22" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/1dd99f0f-812a-47f9-a967-11655de945a9">

For now, it maps to ~310$ per month for these 3 controllers.

**Comment by dduportal** [comment]
Update: infra.ci.jenkins.io is now fully utilizing the new subscription for its VM agents.

**Comment by dduportal** [comment]
Update:

- WiP: planning to migrate packer-builds RGs to the new subscription (plan in another comment). Then packer-images as a second step
- While pairing with @smerle33 on packer-builds RGs migration, he caught an error message in Azure UI about CIDR overlaping within the new networks. I messed up in the CIDR for trusted.ci, cert.ci and infra.ci.
  - See https://github.com/jenkins-infra/azure-net/pull/185 on the new adresse spaces (applied and checked manually)
  - Required a run of jenkins-infra/azure to apply new NSG rules

**Comment by smerle33** [comment]
To use the new subscription for packer : 

1 - migrate packer-builds resources groups (3 rg) [azure]
2 - create a new azure SP credential within infra.ci for packer image job on the new subscription
3 - update packer-image jenkins pipeline with the new credential
4 - temporarily disable spot instance usage within packer (sources.pkr.hcl) / add quotas for packers machines within the new subscription (and try again spot instances)
5 - split var.azure_subscription_id to provide the legacy subscription for the image gallery destination
6 - allow infra.ci agents to reach packer VM with winRM protocol (ssh is already allowed) :
    . change packer-image to use brand new private network

**Comment by dduportal** [comment]
Adding a figures about packer billing (which justifies the effort to move it to the sponsored subscription):

In the past 6 months, it costed us between $200 to $300 each month:

<img width="1908" alt="Capture d’écran 2023-12-19 à 10 22 12" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/ec45a854-00e6-4e28-9ef6-44eed896316c">

See the past few days:

<img width="1892" alt="Capture d’écran 2023-12-19 à 07 56 36" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/11463180-59c0-476e-b3c0-6b52c4e0992b">

Of course, the main cost center is the resource group with the production images gallery: it means we should garbage collect the old VM templates (or decrease the current garbage collector retention time) to decrease this cost.

**Comment by dduportal** [comment]
> To use the new subscription for packer :
> 
>     * [x]   migrate packer-builds resources groups (3 rg) [azure] [feat(packer): move packer-builds to the new provider azure sponsored azure#556](https://github.com/jenkins-infra/azure/pull/556)
> 
>     * [x]  create a new azure SP credential within infra.ci for packer image job on the new subscription
> 
>     * [ ]  update packer-image jenkins pipeline with the new credential
> 
>     * [ ]  temporarily disable spot instance usage within packer (sources.pkr.hcl) / add quotas for packers machines within the new subscription (and try again spot instances)
> 
>     * [ ]  split var.azure_subscription_id to provide the legacy subscription for the image gallery destination
> 
>     * [ ]  allow infra.ci agents to reach packer VM with winRM protocol (ssh is already allowed) :
>       
>       * [ ]   change packer-image to use brand new private network

While @smerle33 leads the plan above, I'll lead the migration of the packer images resource groups:

- [ ] Create the new resource groups `*packer-images` and associated resources in the new subscription (terraform project jenkins-infra/azure)
  - [ ] Create RGs
  - [ ] Check wether shared galleries have their names spreads on all azure or per RG/subscription (and either create new ones with same name or migrate existing one)
- [ ] Add read permissions on the new production images on all controllers using Azure VMs 
- [ ] Ensure there is at least one production image (either from migration or release a new one after @smerle33 work is finished)
- [ ] Migrate controllers to the new image
- [ ] Improve GC on the "current subscription" to decrease image removal
- [ ] Remove old RGs
- [ ] Migrate GC to new subscription

**Comment by dduportal** [comment]
Update: @smerle33 and I are working in parallel (and pair) on both plans.

While working on https://github.com/jenkins-infra/packer-images/pull/959, he was stuck on location issues.

As such, we are moving all new resources (in the new subscription) to "US East 2" as we only use this location (see https://github.com/jenkins-infra/azure/pull/560 and https://github.com/jenkins-infra/azure/pull/561)

**Comment by dduportal** [comment]
Update: most of the work done by @smerle33 in https://github.com/jenkins-infra/packer-images/pull/959:

- Changed instance size + disabled spot (to ensure we stay in allocated quotas)
- Switched to new credential for subscription + allow overriding subscription for gallery to allow us all cases
- Restrict to US East 2 region only
- Moved to using a private network (no public IP, finer control on machines access)


Wip:

- Switching to private network shows a timeout for reaching machines through SSH or WinRM, we have to specify custom NSG rules to cross subnets from infra.ci VM agents (VM/kube) to the packer net.

**Comment by dduportal** [comment]
Update:

- Packer builds are fully utilizing the new subscription and the release [1.43.0](https://github.com/jenkins-infra/packer-images/releases/tag/1.43.0) has been done in the new subscription

WiP:

- Bump packer image version to 1.43.0 on all controllers (which requires switching gallery configuration to new subscription)
- Fix errors related to the new subscription

**Comment by dduportal** [comment]
Update:

- All controllers are using the new image in the new subscription
- Removed the packer resources from the former subscription

**Comment by dduportal** [comment]
Reopening: https://github.com/jenkins-infra/helpdesk/issues/3875#issuecomment-1868290946

The crawler issue is most probably caused by the trusted ephemeral agent CIDR changes

**Comment by dduportal** [comment]
Update:

- Costs check:
    - We can clearly view the resource migration. The amount of billing decrease is from 2% to 6% depending on the months

<img width="1900" alt="Capture d’écran 2024-01-02 à 11 05 24" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/0da9a00b-8bb2-4876-8fd2-f3f4d1feaf1c">

<img width="1894" alt="Capture d’écran 2024-01-02 à 11 09 07" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/0d98dbf4-b40d-4030-95f5-b1f77897f477">

  - The new (sponsored) subscription is now used (almost 1k$ consumed). Check below the top-level consumption per resource kind. Please note that we cannot use Spot instance in this for now (not enough quota when we asked last month):

<img width="1172" alt="Capture d’écran 2024-01-02 à 11 06 01" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/4fa8c315-da44-4865-ba9d-27f3e9ad41ae">

<img width="1638" alt="Capture d’écran 2024-01-02 à 11 06 31" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/baba5795-c505-4f89-95e3-011f4d053cb0">

**Comment by dduportal** [comment]
Closing as https://github.com/jenkins-infra/helpdesk/issues/3875 is NOT caused by the new networks.
