### ISSUE TITLE
Grant markewaite access to the infrastructure VPN

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3819]
### Service(s)

VPN

### Summary

As a release lead, Mark Waite needs to be able to access release.ci.jenkins.io to start the build of Jenkins 2.426.1.  The [2.426.1 release checklist](https://github.com/jenkins-infra/release/issues/464) notes that the release lead starts the build.  I'll need access in order to start the build.

### Reproduction steps

1. Attempt to connect to the VPN, see that it fails because I don't have the correct information in the VPN

**Comment by dduportal** [comment]
Deployed by https://github.com/jenkins-infra/jenkins-infra/pull/3180

**Comment by dduportal** [comment]
@MarkEWaite can you confirm it is working for you?

**Comment by MarkEWaite** [comment]
My attempt to configure the VPN has failed.  I think that I'll need your diagnostic help tomorrow early morning (my time).  Let's not disrupt your time today at the end of your day

**Comment by dduportal** [comment]
Tested and set up with @MarkEWaite , work as expected!
