### ISSUE TITLE
forgot login details

### ISSUE THREAD

**Issue by charan1030** [jenkins-infra/helpdesk#3822]
### Type(s) of account issue

I didn't receive any email

### Summary

NOT GETTING EMAIL

### jenkins.io account username

charan789

### jenkins.io account email

charanchandu6876@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @charan1030 , your account does not exist : which is why you don't have any email.

I'm closing this issue as no further action is required.
