### ISSUE TITLE
infra.ci.jenkins.io on `arm64` (controller and agents)

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3823]
### Service(s)

Azure, infra.ci.jenkins.io

### Summary

as for the publick8s, we should create an ARM64 nodepool within the kubernetes privateK8S in order to migrate jenkins agent to arm64.

Also need to migrate infra.ci.jenkins.io to arm (with care about PV/PVC migration to the correct zone for arm zone 1)

- create an ARM64 nodepool
- create ARM64 agent in this nodepool
- migrate the infra.ci.jenkins.io instance in the arm64 nodepool

**Comment by smerle33** [comment]
- done:  
- wip:
  - [use ARM64 agent on https://github.com/jenkins-infra/kubernetes-management/tree/main
] provide the same tools as [update](https://github.com/jenkins-infra/docker-helmfile) on the allinone image (https://github.com/jenkins-infra/packer-images)
		- https://github.com/jenkins-infra/packer-images/releases/tag/1.44.0
- todo:     
    - [use ARM64 agent on https://github.com/jenkins-infra/kubernetes-management/tree/main
] modify the pipeline of https://github.com/jenkins-infra/kubernetes-management/tree/main to use the ARM64 allinone image instead of the docker-helmfile one.

**Comment by smerle33** [comment]
the allinone image is failing to be used in the terraform project, as it used a newer terraform cli version (1.6.6 while we are currently using 1.1) lets upgrade the terraform project on 1.6.6: https://github.com/jenkins-infra/azure/pull/575

**Comment by smerle33** [comment]
removing shared-library annotation : 

- [ ] [jenkins-infra/azure](https://github.com/jenkins-infra/azure)
- [ ] [jenkins-infra/azure-net](https://github.com/jenkins-infra/azure-net)
- [ ] [jenkins-infra/aws](https://github.com/jenkins-infra/aws)
- [ ] [jenkins-infra/digitalocean](https://github.com/jenkins-infra/digitalocean)
- [ ] [jenkins-infra/fastly](https://github.com/jenkins-infra/fastly)
- [ ] [jenkins-infra/cloudflare](https://github.com/jenkins-infra/cloudflare)
- [ ] [jenkins-infra/datadog](https://github.com/jenkins-infra/datadog)

**Comment by smerle33** [comment]
> the allinone image is failing to be used in the terraform project, as it used a newer terraform cli version (1.6.6 while we are currently using 1.1) lets upgrade the terraform project on 1.6.6: [jenkins-infra/azure#575](https://github.com/jenkins-infra/azure/pull/575)

all our terraform project are now running with terraform cli 1.6.6 so we should be able to use the allinone image now

**Comment by smerle33** [comment]
the allinone image need golang: https://infra.ci.jenkins.io/job/terraform-jobs/job/azure/job/PR-575/2/pipeline-console/?start-byte=0&selected-node=40#log-23
as per https://github.com/jenkins-infra/docker-hashicorp-tools/blob/fe538ce08d4ccc8e2d86df0f730b12bea4d097e1/Dockerfile#L3

**Comment by smerle33** [comment]
before deprecating https://hub.docker.com/r/jenkinsciinfra/helmfile we need to make sure that all project are now using the allinone as per: https://github.com/jenkins-infra/pipeline-library/blob/master/vars/updatecli.groovy

**Comment by smerle33** [comment]
splitting the PR https://github.com/jenkins-infra/pipeline-library/pull/817 keep it for terraform only and create a new one for updatecli

**Comment by smerle33** [comment]
all Terraform projects checked with success, PR ready for review

**Comment by smerle33** [comment]
Terraform projects and updatecli  are now using agentLabel in arm64 🍾

**Comment by smerle33** [comment]
- done:  
    - [use ARM64 agent on https://github.com/jenkins-infra/kubernetes-management/tree/main] provide the same tools as [update](https://github.com/jenkins-infra/docker-helmfile) on the allinone image (https://github.com/jenkins-infra/packer-images)
	- https://github.com/jenkins-infra/packer-images/releases/tag/1.44.0
	- [use ARM64 agent on https://github.com/jenkins-infra/kubernetes-management/tree/main] modify the pipeline of https://github.com/jenkins-infra/kubernetes-management/tree/main to use the ARM64 allinone image instead of the docker-helmfile one. (https://github.com/jenkins-infra/kubernetes-management/commit/2ea17f9b50e1251a5b78ac74a7846f2b58a14849)
	- [use ARM64 agent on https://github.com/jenkins-infra/kubernetes-management/tree/main] cleanup jenkins-infra/docker-helmfile project (remove job, archive repository, update docker-hub as deprecated)
    - [use ARM64 agent on terraform usages] update shared pipeline library https://github.com/jenkins-infra/pipeline-library/pull/817 to use node label instead of podtemplate in order to switch to ARM64 allinone version

**Comment by smerle33** [comment]
todo: 
- [ ] migrate the infra.ci.jenkins.io instance in the arm64 nodepool

**Comment by smerle33** [comment]
https://github.com/jenkins-infra/docker-hashicorp-tools archived

**Comment by smerle33** [comment]
> todo:
> 
>     * [ ]  migrate the infra.ci.jenkins.io instance in the arm64 nodepool
> 
>     * [ ]  move all jobs from docker-builder (`builder`) to the allinone agents

need to check for npm on the ALLINONE agent : 
```
17:33:02  + npm ci
17:33:02  /home/jenkins/agent/workspace/reports_plugin-migration_PR-56/plugin-migration@tmp/durable-b092cfd7/script.sh: line 1: npm: command not found
```

**Comment by dduportal** [comment]
See https://github.com/jenkins-infra/helpdesk/issues/3913#issuecomment-1914132386 for the costs decrease impact

**Comment by smerle33** [comment]
> > todo:
> > ```
> > * [ ]  migrate the infra.ci.jenkins.io instance in the arm64 nodepool
> > 
> > * [ ]  move all jobs from docker-builder (`builder`) to the allinone agents
> > ```
> 
> need to check for npm on the ALLINONE agent :
> 
> ```
> 17:33:02  + npm ci
> 17:33:02  /home/jenkins/agent/workspace/reports_plugin-migration_PR-56/plugin-migration@tmp/durable-b092cfd7/script.sh: line 1: npm: command not found
> ```

the new agent version 1.49.2 is working better but I think that we are still having an issue regarding the ruby version 
[jenkins-infra/packer-images@2dce9a8/provisioning/tools-versions.yml#L40C1-L40C21](https://github.com/jenkins-infra/packer-images/blob/2dce9a8c1ed325c307ef3b6f8ce266ad7c2bbb9b/provisioning/tools-versions.yml#L40C1-L40C21)

**Comment by smerle33** [comment]
> > > todo:
> > > ```
> > > * [ ]  migrate the infra.ci.jenkins.io instance in the arm64 nodepool
> > > 
> > > * [ ]  move all jobs from docker-builder (`builder`) to the allinone agents
> > > ```
> > 
> > 
> > need to check for npm on the ALLINONE agent :
> > ```
> > 17:33:02  + npm ci
> > 17:33:02  /home/jenkins/agent/workspace/reports_plugin-migration_PR-56/plugin-migration@tmp/durable-b092cfd7/script.sh: line 1: npm: command not found
> > ```
> 
> the new agent version 1.49.2 is working better but I think that we are still having an issue regarding the ruby version [jenkins-infra/packer-images@2dce9a8/provisioning/tools-versions.yml#L40C1-L40C21](https://github.com/jenkins-infra/packer-images/blob/2dce9a8c1ed325c307ef3b6f8ce266ad7c2bbb9b/provisioning/tools-versions.yml#L40C1-L40C21)

trying to add directly the bundle/bundler within the allinone agent image https://github.com/jenkins-infra/packer-images/pull/1026

**Comment by dduportal** [comment]
Update: `docker-hashicorp-tools` is still used in https://github.com/jenkins-infra/docker-openvpn/pull/328#issuecomment-1945555172

**Comment by smerle33** [comment]
> Update: `docker-hashicorp-tools` is still used in [jenkins-infra/docker-openvpn#328 (comment)](https://github.com/jenkins-infra/docker-openvpn/pull/328#issuecomment-1945555172)

corrected by https://github.com/jenkins-infra/docker-openvpn/pull/329

**Comment by smerle33** [comment]
> the new agent version 1.49.2 is working better but I think that we are still having an issue regarding the ruby version
> [jenkins-infra/packer-images@2dce9a8/provisioning/tools-versions.yml#L40C1-L40C21](https://github.com/jenkins-infra/packer-images/blob/2dce9a8c1ed325c307ef3b6f8ce266ad7c2bbb9b/provisioning/tools-versions.yml#L40C1-L40C21)

still a problem, we need to provide multiple version of ruby/npm and use asdf to switch the usage.

**Comment by smerle33** [comment]
The infra-reports pipelines are all working with the AllInOne image agent in ARM64 since https://github.com/jenkins-infra/infra-reports/pull/56

**Comment by smerle33** [comment]
Listing the current usage of the agent label: "linux jnlp-linux" from https://github.com/jenkins-infra/kubernetes-management/blob/f75f731f163fb57f316a08421df9f28ac6d9bcf7/config/jenkins_infra.ci.jenkins.io.yaml#L116-L149 
to replace with the AllInOne/arm64 one https://github.com/jenkins-infra/kubernetes-management/blob/f75f731f163fb57f316a08421df9f28ac6d9bcf7/config/jenkins_infra.ci.jenkins.io.yaml#L169

**Comment by smerle33** [comment]
as per https://github.com/jenkins-infra/jenkins.io/pull/7027 we might be facing the lack of memory and/or cpu for the task, @lemeurherve did create a new agent arm with larger amount of both : https://github.com/jenkins-infra/account-app/pull/354#issuecomment-1973243093 and https://github.com/jenkins-infra/kubernetes-management/pull/5035
but we are lock by the size of the machine node for the nodepool ARM (small) so I did try to create a new nodepool for large arm64 pods : 
https://github.com/jenkins-infra/azure/pull/633

this one has to be revert (https://github.com/jenkins-infra/azure/pull/634) as the version of kubernetes seem not to support this
so I tried to upgrade to the latest patch version on 1.26.XX (12 instead of 6), but the build failed (lost the agent) : 
```
Cannot contact jnlp-linux-arm64-8m5vw: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@6f7cc746:jnlp-linux-arm64-8m5vw": Remote call on jnlp-linux-arm64-8m5vw failed. The channel is closing down or has closed down 
```

a retry by @lemeurherve missed the lock : https://infra.ci.jenkins.io/job/terraform-jobs/job/azure/job/main/1112/pipeline-console/?start-byte=0&selected-node=59#log-37
`Error: Error acquiring the state lock`

**Comment by smerle33** [comment]
state lock solved by using `terraform force-unlock LOCK_ID`

**Comment by smerle33** [comment]
update: infra.ci is now officially running on arm64.

next steps: cleanup (next week)

**Comment by dduportal** [comment]
Update: fixing a few errors discovered after the controller migration:

- Datadog connection errors in infra.ci logs:
  - No agent were running on the node where infraci ran: https://github.com/jenkins-infra/kubernetes-management/pull/5132
  - Azure Linux support for datadog + admission controller refusing webhooks: https://github.com/jenkins-infra/kubernetes-management/pull/5133
- Failure to spin up VM agents due to subnet changes: https://github.com/jenkins-infra/azure/pull/665

=> Build queue is now empty \o/

**Comment by smerle33** [comment]
Plan to migrate **release.ci.jenkins.io** to arm64

- [ ] Migrate release volume to ZRS (pvc-ed6adfb7-5a25-4315-af8a-627c4913863d)
	- [ ] to avoid timeout add those annotations in kubernetes-management/config/jenkins_release.ci.jenkins.io.yaml:
		``` 
			controller:
			  podSecurityContextOverride:
				runAsUser: 1000
				runAsNonRoot: true
				supplementalGroups: [1000]
		```
	- [ ] create a snapshot (from UI)
	- [ ] create a disk from the snapshot (from UI)
	- [ ] create a PV with a yaml file with the above created disk : 
		<details>
			apiVersion: v1
			kind: PersistentVolume
			metadata:
			  annotations:
				pv.kubernetes.io/provisioned-by: disk.csi.azure.com
			  name: jenkins-releaseci-snap
			spec:
			  capacity:
				storage: 64Gi
			  accessModes:
				- ReadWriteOnce
			  persistentVolumeReclaimPolicy: Retain
			  storageClassName: managed-csi-premium-zrs-retain
			  csi:
				driver: disk.csi.azure.com
				volumeHandle: jenkins-releaseci-snap
				volumeAttributes:
				  fsType: ext4
		</details>
		**note** that the volumeHandle is shorten to the diskname not the full handle `volumeHandle: jenkins-releaseci-snap`
		
		```
			kubectl apply -f  .tmp/jenkins-releaseci-pv-snap.yaml
		```

	- [ ] create a PVC
		<details>
			apiVersion: v1
			kind: PersistentVolumeClaim
			metadata:
			  name: jenkins-releaseci-snap
			  namespace: jenkins-infra
			spec:
			  accessModes:
				- ReadWriteOnce
			  resources:
				requests:
				  storage: 64Gi
			  volumeName: jenkins-releaseci-snap
			  storageClassName: managed-csi-premium-zrs-retain
		</details>
		
		```
			kubectl apply -f  .tmp/jenkins-releaseci-pvc-snap.yaml
		```
		
	- [ ] Set release.ci to shutdown mode
	- [ ] Set the `statefulset` to zero replicas to ensure a proper and controlled volume unmount
	- [ ] Change the storage class with a datasource as per top of the file https://github.com/jenkins-infra/kubernetes-management/pull/4720/files (DO NOT MIGRATE TO ARM64 YET) - 
	- [ ] Merge the PR (infra.ci will handle the migration)
	- [ ] once the above task will be merged, migrate to ARM64 as per https://github.com/jenkins-infra/kubernetes-management/pull/4720/files bottom of the file, add a  node Selector specific to the previously created nodepool

++++++++++++++++++++++++++++
Definition of done

- [ ] the volume is a ZRS volume in the azure UI - Delete the temporarily and manually created disk volume and PVC (claim) also the azure snapshot
- [ ] the pod start and is on an ARM64 node
- [ ] the jenkins CI release.ci.jenkins.io is responding
- [ ] check that the build queue is being handled

**Comment by smerle33** [comment]
CleanUp (infra.ci, weekly.ci, release.ci)

- [ ] remove PV/PVC from snap
- [ ] remove disk not mounted (from snap)
- [ ] remove snapshots
