### ISSUE TITLE
I forgot my jenkis username and password

### ISSUE THREAD

**Issue by livisha** [jenkins-infra/helpdesk#3825]
### Type(s) of account issue

I've lost my password

### Summary

I am not able to login in Jenkins. I forgot my username and password 

### jenkins.io account username

livisha

### jenkins.io account email

jainlivisha211@gmail.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Hi,

- Please note that accounts.jenkins.io is **only** for logging-in on issues.jenkins.io or ci.jenkins.io online. It is **not** for your own (or your organization's) Jenkins instance.
- If you lost your password on accounts.jenkins.io, you can reset it from the "Reset password" link from https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Closing as no answer from the requester
