### ISSUE TITLE
account recovery

### ISSUE THREAD

**Issue by pooji143** [jenkins-infra/helpdesk#3826]
### Type(s) of account issue

I've lost my password

### jenkins.io account username

poojitha

### jenkins.io account email

kuchipudipoojitha2003@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by pooji143** [comment]
help me to recovery account

**Comment by dduportal** [comment]
Hi @pooji143 , the email specified in this issue does not exist in the accounts.jenkins.io system.

- If you are the rightful owner of this account, you have access to the email associated with the account `poojitha` and you can reset the password by checking the instructions sent by email.
- If this account is for your local Jenkins installation, then don't use accounts.jenkins.io (which only manages accounts for issues.jenkins.io and ci.jenkins.io).

**Comment by dduportal** [comment]
Closing as no answer from the requester
