### ISSUE TITLE
[publick8s] Tune node pool size

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3827]
### Service(s)

Azure

### Summary

With the work done on https://github.com/jenkins-infra/helpdesk/issues/3619, we now have to fine tune the node pool sizing for `publick8s`.

There are 4 main tasks:

- [x] Remove the (legacy) `publicpool` x86 Linux node pool which is unused since months
- [x] Study the instance pricing for `arm64` and update the current `arm64small2` node pool if needed (Do we want to keep small instances or pack on bigger instances)?
- [x] Decrease the size of the `x86medium` node pool as it runs less elements
- [x] Scale up the system pool to fulfill the Azure HA recommendations:

<img width="510" alt="Capture d’écran 2023-11-09 à 13 08 14" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/b953e49a-36f7-43e5-92bf-e0b35c393913">

**Comment by dduportal** [comment]
Update: 

- https://github.com/jenkins-infra/azure/pull/518 with @smerle33

**Comment by smerle33** [comment]
as we looked into the prices for arm64 nodes we found out that it's more valuable to have 3 "small" node in the arm64small2 nodepool than 2 "big" ones as they are exactly twice the price for twice more cpu and ram. so we save the equivalent of 1 small machine per month

**Comment by smerle33** [comment]
WIP services working now on intel x86medium nodes : 
```
updates-jenkins-io-mirrorbits-lite
mirrorbits-files
mirrorbits
ldap
keycloak
falco
datadog
```

**Comment by smerle33** [comment]
same method as https://github.com/jenkins-infra/helpdesk/issues/3539#issuecomment-1544377727

- [ ] create a new system pool with taint (https://github.com/jenkins-infra/azure/pull/537)
- [ ] cordon/drain old systempool
- [ ] remove old systempool

**Comment by smerle33** [comment]
<img width="1744" alt="Capture d’écran 2023-12-05 à 11 05 47" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/15cbcaae-d63a-44e9-aa36-6e873ad91d5b">

**Comment by dduportal** [comment]
Update:

- Default (System) node pool migrated to a new version with:
  - Taint for non critical workloads (to avoid our workloads to be scheduled on this system)
  - Bigger OS disk (we have 50 Gb ephemeral space available: let's use it)


Next steps:

- A PR to scale the new system pool to 2 nodes
- Operation on the publick8s cluster to migrate x86 workloads to the new (smaller) pool (includes https://github.com/jenkins-infra/kubernetes-management/pull/4743) now that the systempool is tainted

**Comment by dduportal** [comment]
Update:

- Systempool set to 2 nodes in https://github.com/jenkins-infra/azure/pull/542

WiP:

- Starting operation to migrate to the "small" x86 nodepool
  -  https://github.com/jenkins-infra/status/pull/440

**Comment by dduportal** [comment]
Update:

- Resources and limits were adapted for keycloak, ldap, mirrorbits (get.jenkins.io) and mirrorbits-parent (new UC) with success (see linked PRs) with success


The node pool `x86small` is now successfully scaled to 3 nodes as we wanted (expected decrease of 25% in the billing).
