### ISSUE TITLE
[get.jenkins.io] migrate from `mirrorbits` to `mirrorbits-parent` chart

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3828]
### Service(s)

Azure, get.jenkins.io

### Summary

Following the work done in https://github.com/jenkins-infra/helpdesk/issues/3619 and https://github.com/jenkins-infra/helpdesk/issues/2649 , we have to update the service `get.jenkins.io` in jenkins-infra/kubernetes-management to use the `mirrorbits-parent` chart instead of the current (and soon to be removed) `mirrorbits`.

- It will allows us to use the latest improvements we did on the chart and config management (logs mangement, debugging mirrorbits, umbrella storage and ingress, etc.)
- It will allows migrating the `httpd` server to `arm64` for get.jenkins.io

**Comment by dduportal** [comment]
Preliminary step: defines `archives.jenkins.io` as fallback instead of the 2 OSUOSL:

- Since https://github.com/jenkins-infra/helpdesk/issues/3760, archives.jenkins.io runs in DigitalOcean (in Frakfurt, Germany, datacenter) and the download bandwitdh is good and cheap
- As pert https://github.com/jenkins-infra/helpdesk/issues/3338 (and many other issues), OSUOSL seems to purge some data after some time while archives.jenkins.io does not

**Comment by dduportal** [comment]
> Preliminary step: defines `archives.jenkins.io` as fallback instead of the 2 OSUOSL:
> 
>     * Since [Move archives.jenkins.io service away from Oracle #3760](https://github.com/jenkins-infra/helpdesk/issues/3760), archives.jenkins.io runs in DigitalOcean (in Frakfurt, Germany, datacenter) and the download bandwitdh is good and cheap
> 
>     * As pert [In reference to issue #3183 #3338](https://github.com/jenkins-infra/helpdesk/issues/3338) (and many other issues), OSUOSL seems to purge some data after some time while archives.jenkins.io does not

- Applied with success (https://github.com/jenkins-infra/charts-secrets/commit/e064818e223df5fa6659d0a236017d23fff554d3 - private commit)
- Opened https://github.com/jenkins-infra/status/pull/457 to annoucne operation

**Comment by dduportal** [comment]
Update:

- Opened https://github.com/jenkins-infra/kubernetes-management/pull/4847
  - First commit is the expected config
  - Second commit restricts domain and RedisDB for the initial installation (easier to revert).

- Starting initial installation

**Comment by dduportal** [comment]
Update: 

- Initial (manual) installation is successful
- https://github.com/jenkins-infra/kubernetes-management/pull/4847 merged


Todo:

- Manual operation: for migration:
  - Set up to proper domains and RedisDB on the new `get.jenkins.io`
  - Remove ingress of mirrorbits
  - Scale `mirrorbits` to zero
- Validate: if it works, then remove namespace and config for old `mirrorbits`, otherwise rollback

**Comment by dduportal** [comment]
Update:

- PR for migration opened, applied and deployed. Led to a 2 min downtime: https://github.com/jenkins-infra/kubernetes-management/pull/4848#issuecomment-1881547066
- Merged but jenkins-infra/kubernetes-management is failing to re-apply the chart. WiP

**Comment by dduportal** [comment]
Update:

- jenkins-infra/kubernetes-management is OK for `get-jenkins-io` ✅  
- Removed the former PV `mirrorbits-binary`

Todo:

- Cleanupo `helm-charts` repository and updatecli manifests

**Comment by lemeurherve** [comment]
> Cleanupo `helm-charts` repository and updatecli manifests

Will it include the renaming of `mirrorbits-parent` to `mirrorbits`? (Please say yes ^^)

**Comment by dduportal** [comment]
> > Cleanupo `helm-charts` repository and updatecli manifests
> 
> Will it include the renaming of `mirrorbits-parent` to `mirrorbits`? (Please say yes ^^)

`mirrorbits-lite` by `mirrorbits` you mean? ;)

**Comment by dduportal** [comment]
Update (cleanup `mirrorbits`):

- Chart renamed in https://github.com/jenkins-infra/helm-charts/pull/1006
- Chart `mirrorbits-parent` updated in https://github.com/jenkins-infra/helm-charts/pull/1007

Todo:

- wait for the `2.0.0` release of `mirrorbits-parent` in jenkins-infra/kubernetes-management
- change chart values and deploy it

**Comment by dduportal** [comment]
Update:

- All charts were released/updated properly
- PR https://github.com/jenkins-infra/kubernetes-management/pull/4853 to use the new charts is ready, with a fixup commit to change parameters.

ToDo:

- Deploy this chart (will most probably cause a downtime)

**Comment by dduportal** [comment]
Update:

- Merged and deployed, with a 5 min downtime
- Closed https://github.com/jenkins-infra/status/pull/458
