### ISSUE TITLE
Moving to alumni in jenkins-infra

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/helpdesk#3829]
### GitHub repositories

All jenkins-infra teams

### GitHub users to have permission

@oleg-nenashev

### Permission level

Read

### Justification

Hello. This is the nearest template I could find. I have no bandwidth to contribute, and it does not look like I can leave some teams on my own. Could you please remove me from the Jenkins Hosting, Plugin Site and other teams, and add me to the Alumni one? I will remani around I hope, but I need to clean up my dashboard a bit

**Comment by dduportal** [comment]
ack, you might receive messages that you've been kicked from the organization : I'll add you back in the alumni team (easier for permissions)

**Comment by dduportal** [comment]
@oleg-nenashev you've been removed + re-invited:

<img width="1104" alt="Capture d’écran 2023-11-24 à 12 08 26" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/ffd17500-3277-45c9-85b3-8d78d6a37ffa">


Can you confirm by commenting and/or closing the issue?

**Comment by dduportal** [comment]
Hello @oleg-nenashev , I've renewed the invitation to the Alumni team, its TTL is 7 days.

I'm closing the issue as no more action is required

**Comment by oleg-nenashev** [comment]
Thank you. It's my fault that I missed a deadline to accept the invitation

**Comment by dduportal** [comment]
> Thank you. It's my fault that I missed a deadline to accept the invitation

No problem, you mentioned that you had to triage your GH notifications so it make sense. I only closed the issue to materialized that no work was required on infra team, but reviving the invitation would have been the default.

Enjoy the pace buddy!
