### ISSUE TITLE
Need Github repository permissions for Developers

### ISSUE THREAD

**Issue by kishorikumar** [jenkins-infra/helpdesk#3831]
### GitHub repositories

https://github.com/jenkinsci/synopsys-security-scan-plugin

### GitHub users to have permission

@sig-tithi

### Permission level

Maintain

### Justification

Developer was requested initially, but was not added. Raising the request again to add the developer.

**Comment by kishorikumar** [comment]
@NotMyFault Can you please help us here

**Comment by NotMyFault** [comment]
> Developer was requested initially, but was not added. 

This is not correct:

![Screenshot 2023-11-24 at 17 43 27](https://github.com/jenkins-infra/helpdesk/assets/13383509/91f950d0-2185-46c1-afd7-485c5b662c69)

An invite has been sent out after the plugin has been onboarded, but if the invitee doesn't accept the invite within 7 days, it expires.
