### ISSUE TITLE
LoadNinja plugin repository access

### ISSUE THREAD

**Issue by kordian-smartbear** [jenkins-infra/helpdesk#3833]
### Service(s)

plugins.jenkins.io

### Summary

Dear Support Specialist,

Our plugin was developed some time ago and people responsible for the maintenance are not with us any more.
Could you please grant access to this repository (contributor or owner) https://github.com/jenkinsci/loadninja-plugin for new list of users?

Best Regards
Kordian

**Comment by kordian-smartbear** [comment]
Hi, any update on this issue?

**Comment by NotMyFault** [comment]
> Hi, any update on this issue?

Hey,

If you could send me an email with your company mail address to jenkinsci-board@googlegroups.com, I can grant the users mentioned access, just to verify everything is legit.

Shall the existing members be removed from the team?

**Comment by kordian-smartbear** [comment]
@NotMyFault thanks for quick reply :) . Just sending email.
Yes, please remove current members from the team.

**Comment by NotMyFault** [comment]
Done, if you need to grant yourself and others release permission, please file a PR editing your release permission file in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-loadninja.yml.
The account name matches your account name for https://accounts.jenkins.io/login

**Comment by kordian-smartbear** [comment]
Great, thanks for your help :)
