### ISSUE TITLE
Disable new Jira issues for lockable-resources-plugin

### ISSUE THREAD

**Issue by mPokornyETM** [jenkins-infra/helpdesk#3834]
### Service(s)

Jira

### Summary

As we discuss here
https://github.com/jenkinsci/lockable-resources-plugin/issues/382

it will be grat when the new Jira issues has been disabled, as we don't seem to get a lot of attention in JIRA.

thx
BR

### Reproduction steps

.

**Comment by NotMyFault** [comment]
You can remove the JIRA part from plugins.j.io and other places yourself by removing the reference in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-lockable-resources.yml via a PR.

Archiving the subcomponent would be down to a @jenkins-infra/jira-admins.

**Comment by mPokornyETM** [comment]
> You can remove the JIRA part from plugins.j.io and other places yourself by removing the reference in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-lockable-resources.yml via a PR.
> 
> Archiving the subcomponent would be down to a @jenkins-infra/jira-admins.

thx, see [#3642](https://github.com/jenkins-infra/repository-permissions-updater/pull/3642)
