### ISSUE TITLE
BOM PR builds not running

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3835]
### Service(s)

ci.jenkins.io

### Summary

Builds for these three PRs haven't started yet:

- https://github.com/jenkinsci/bom/pull/2696
- https://github.com/jenkinsci/bom/pull/2697
- https://github.com/jenkinsci/bom/pull/2698

These pages return a 404:

- https://ci.jenkins.io/job/Tools/job/bom/job/PR-2696/
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-2697/
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-2698/

I checked https://ci.jenkins.io/manage/pluginManager/ but there do not appear to be any recently installed updates to the GitHub plugins (though there are some available updates). 

### Reproduction steps

Create a BOM PR. It should result in the creation of a new Jenkins job to test the PR, but that isn't currently happening.

**Comment by dduportal** [comment]
Thanks @basil for taking care of reporting and watching this!
