### ISSUE TITLE
forgot password

### ISSUE THREAD

**Issue by saikirankondeti9** [jenkins-infra/helpdesk#3841]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account username

saikirankondeti9

### jenkins.io account email

saikirankondeti9@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
No such user name or email address exists on accounts.jenkins.io.  If you've lost access to a local Jenkins installation, you'll need to work with the administrator of that instance to recover the account.
