### ISSUE TITLE
Remove `jcenter`, and `oss.sonatype.org-releases` repositories from `public` virtual repository; reconfigure Atlassian remote repositories

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3842]
### Service(s)

Artifactory

### Summary

The data transfer volume from https://repo.jenkins-ci.org is still unexpectedly high.  Log file analysis for a recent 5 day period shows that the top repositories based on the sum of the sizes of the requested files are:

| Repository                      | Sum of GB requested |
| :------------------------------ | ------------------: |
| releases                        |                2380 |
| jcenter-cache                   |                1787 |
| incrementals                    |                 298 |
| jcenter                         |                  98 |
| nodejs-dist-cache               |                  78 |
| public                          |                  26 |
| jgit-cache                      |                  14 |
| oss.sonatype.org-releases-cache |                   8 |
| snapshots                       |                   8 |
| npm-dist-cache                  |                   5 |

JFrog has explained that even though we removed Apache Maven Central from the public repository, the contents of Apache Maven Central still exist as copies in the jcenter repository.  We need to also remove the jcenter repository and the jcenter-cache repository from the definition of the public repository so that binaries from Apache Maven Central will be resolved from Apache Maven Central instead of being resolved from our repository.

When I had tried some initial experiments removing jcenter, several months ago, there were some cases where it appeared that we depend on artifacts that are only in jcenter and possibly only in our cache of jcenter.  Unfortunately, my memory is weak and I cannot find any notes that reference that experiment.

I think that we should take the following steps:

* [x] Create a new repository on repo.jenkins-ci.org and copy the [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages) artifact from jcenter-cache to the new repository (required for Jenkins core, appears to only be available from jcenter-cache).  Add the new repository to the public virtual repository
* [x] [Announce a 2 hour brownout](https://groups.google.com/g/jenkinsci-dev/c/Jn_4U-KQUqg/m/N5i6VH7_AAAJ) where jcenter and jcenter-cache will be temporarily removed from the public repository
* [x] Exclude the `com.jayway.jsonpath` groupId and all its packages from the `jgit-cache`.  The [artifactory plugin build failure](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839310585) and the [robot plugin build failure](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839465176) will be resolved by that exclusion.  The [comment](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839521681) from @basil includes more details
* [x] Add orphans repository to the public virtual repository
* [x] Create a new remote repository corresponding to https://packages.atlassian.com/maven-public/ and replace the existing atlassian entry with the new one
* [x] Define the tests we want to perform during the 2 hour brownout, including:
    * Build Jenkins core on ci.jenkins.io
    * Build Jenkins core on a freshly created virtual machine outside any CI infrastructure
    * Build 20+ popular plugins on ci.jenkins.io
    * Build 20+ popular plugins on a freshly created virtual machine outside any CI infrastructure
    * Build plugins that have shown issues (click links for analysis) including [artifactory-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839310585), blueocean-plugin, [configuration-as-code-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839385370), git-client-plugin, [jira-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839425452), [promoted-builds-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839496374), [robot-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839465176)
    * Build plugins that require Java 8 and have shown issues including pipeline-aws-plugin, translation-plugin
    * Run the ci.jenkins.io `weekly-test` configuration of the plugin bill of materials
    * Build key Jenkins tools like the Maven HPI plugin and the plugin compatibility tester
* [x] Prepare machines to test the brownout
    * [x] Jenkins core build machine with Java 21 and Apache Maven 3.9.6 installed.  Clone the Jenkins core repository to the machine but do not compile until the brownout has started
    * [x] 5 Jenkins plugin build machines with Java 8, Java 11, Java 17, Java 21 and Apache Maven 3.9.6 installed.  Clone the specific plugin repositories but do not compile until the brownout has started
* [x] Run the brownout and perform the tests, collecting the results
    * [x] Build Jenkins core on ci.jenkins.io
    * [x] Build Jenkins core on a freshly created virtual machine outside any CI infrastructure
    * [x] Build 20+ popular plugins on ci.jenkins.io
    * [x] Build 20+ popular plugins on a freshly created virtual machine outside any CI infrastructure
    * [x] Build plugins that have shown issues (click links for analysis) including [artifactory-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839310585), blueocean-plugin, [configuration-as-code-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839385370), git-client-plugin, [jira-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839425452), [promoted-builds-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839496374), [robot-plugin](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839465176)
    * [x] Build plugins that require Java 8 and have shown issues including pipeline-aws-plugin, translation-plugin
    * [x] Run the ci.jenkins.io `weekly-test` configuration of the plugin bill of materials
    * Identify failures and investigate alternatives for those failures (for example, if we discover a library that is only available in jcenter, we can copy that library to another Jenkins repository)
* [x] Reset the public configuration at the end of the brownout
* [ ] Implement the configuration change
* [ ] Request and analyze log files for the 5 day period after the configuration change
    * Confirm the jcenter-cache and jcenter repositories are no longer in the top 5 repositories

### Reproduction steps

Steps that I took to analyze the requests:

1. Request Artifactory log files from JFrog
2. Update my [artfiactory-sql fork](https://github.com/MarkEWaite/artifactory-sql/tree/adapt-to-new-log-format) to handle the new format of Artifactory log files
3. Upload the log files to a sqlite3 database
4. Identity top repositories with the SQL query
    `select repo,sum(size_bytes)/1024/1024/1024 as SUM_GB from logs group by repo order by SUM_GB desc limit 10;`

**Comment by MarkEWaite** [comment]
@daniel-beck do you have a recommendation or a preference for the location where the [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages) artifact from jcenter-cache should be placed?

According to [mvnrepository.com](https://mvnrepository.com/artifact/org.connectbot.jbcrypt/jbcrypt/1.0.0), that library is available from the Spring plugins repository and the Spring Lib M repository.  The 1.0.1 and 1.0.2 versions of that library are available from [repo.maven.apache.org](https://repo.maven.apache.org/maven2/org/connectbot/jbcrypt/), but the 1.0.0 version is not.

**Comment by timja** [comment]
or update whatever is using 1.0.0 to a newer version?

**Comment by MarkEWaite** [comment]
> or update whatever is using 1.0.0 to a newer version?

That would break builds of previous versions of Jenkins core, since it requires jbcrypt 1.0.0.  I failed the last time that I tried to update the jbcrypt 1.0.0 dependency to a newer version.  I don't have notes on the failure, but I remember that the attempt did not succeed.

I think it is a  good idea to update the version of jbcrypt to a newer release if possible, but I think that should be handled separately from this effort.

**Comment by dduportal** [comment]
> Create a new repository on repo.jenkins-ci.org and copy the [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages) artifact from jcenter-cache to the new repository (required for Jenkins core, appears to only be available from jcenter-cache). Add the new repository to the public virtual repository

- A new "local" repository `orphans` has been created and added to the permission set "Anything" which grant read access to anyone (e.g. public access)
- The artifact [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages)  has been deployed to this new repository, along with its POM, sources and javadoc. A Maven metadat file has been autogenerated and looks the same as jcenter's
- Please note this repository is not included in the `public` virtual repository (yet?).

See: https://repo.jenkins-ci.org/artifactory/orphans/org/connectbot/jbcrypt/jbcrypt/

cc @MarkEWaite so you can continue your tests.

**Comment by MarkEWaite** [comment]
The artifactory plugin has a dependency on the token macro plugin 2.12.  The token macro plugin 2.12 has a dependency on com.jayway.jsonpath:json-path:2.4.0.  Our cached copy of the JGit repository includes an [outdated copy of the json-path 2.4.0 pom file](https://repo.jenkins-ci.org/artifactory/jgit-cache/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom) for the 2.4.0 release of json-path.  

Based on comments in https://github.com/openhab/openhab-addons/issues/10102#issuecomment-775779992 , we need to replace our outdated copy of the 2.4.0 pom file with an updated copy downloaded from Maven central.

If we don't want to replace the file in our cached copy of the JGit repository, we could place a fresh copy into the orphans repository and move the orphans repository before the JGit repository in our virtual repository search order.

Is there a way to safely remove or exclude the outdated / incorrect json-path 2.4.0 that we are getting from the [Eclipse repository](https://repo.eclipse.org/content/groups/releases/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom)?

**Comment by MarkEWaite** [comment]
## Analyzing configuration as code build failure

The configuration as code plugin depends on the crowd2 plugin.  The crowd2 plugin depends on the crowd-integration-client-common 5.1.5 library that appears to only be available from our jcenter-cache.  Since crowd2 is an Atlassian product, I expected it to be in the atlassian-cache repository, but it does not seem to be there.

We could add the Atlassian repository to the configuration as code plugin like this:

```
diff --git a/pom.xml b/pom.xml
index f8c7d60e..9a1d5c37 100644
--- a/pom.xml
+++ b/pom.xml
@@ -51,6 +51,10 @@
       <id>repo.jenkins-ci.org</id>
       <url>https://repo.jenkins-ci.org/public/</url>
     </repository>
+    <repository>
+      <id>Atlassian</id>
+      <url>https://packages.atlassian.com/mvn/maven-atlassian-external/</url>
+    </repository>
   </repositories>
 
   <pluginRepositories>
```

That won't solve the case for other projects that depend on the Atlassian libraries.  It also does not explain why the Atlassian libraries are not in our atlassian-cache repository but are in our jcenter-cache repository.

**Comment by MarkEWaite** [comment]
## Analyzing Jira plugin build failure

The Jira plugin depends on Atlassian libraries that are available from our jcenter-cache but are not found unless jcenter-cache is included.

The build passed after I added the Atlassian repository to the jira-plugin pom file:

```
diff --git a/pom.xml b/pom.xml
index e3ca697..d56a0ff 100644
--- a/pom.xml
+++ b/pom.xml
@@ -330,6 +330,10 @@
       <id>repo.jenkins-ci.org</id>
       <url>https://repo.jenkins-ci.org/public/</url>
     </repository>
+    <repository>
+      <id>Atlassian</id>
+      <url>https://packages.atlassian.com/mvn/maven-atlassian-external</url>
+    </repository>
   </repositories>
 
   <pluginRepositories>
```

**Comment by MarkEWaite** [comment]
## Analyzing robot plugin build failure

The robot plugin requires Java 11.  It won't build with Java 21.  

The robot plugin has a dependency on com.jayway.jsonpath:json-path:2.4.0.  Our cached copy of the JGit repository includes an [outdated copy of the json-path 2.4.0 pom file](https://repo.jenkins-ci.org/artifactory/jgit-cache/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom) for the 2.4.0 release of json-path.  

Based on comments in https://github.com/openhab/openhab-addons/issues/10102#issuecomment-775779992 , we need to replace our outdated copy of 2.4.0 with an updated [pom file](https://repo1.maven.org/maven2/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom) and [jar file](https://repo1.maven.org/maven2/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.jar).

If we don't want to replace the file in our cached copy of the JGit repository (because the outdated file still exists in the Eclipse JGit repository), we could place a fresh copy into the orphans repository and move the orphans repository before the JGit repository in our virtual repository search order.

Is there a way to safely remove or exclude the outdated / incorrect json-path 2.4.0 that we are getting from the [Eclipse repository](https://repo.eclipse.org/content/groups/releases/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom)?

**Comment by MarkEWaite** [comment]
## Analysis of promoted builds plugin build failure

The promoted builds plugin has an optional dependency on the project inheritance plugin 21.04.03.  The project inheritance plugin 21.04.03 pom file uses http instead of https in its repository URL references.  Maven rejects attempts to from an http repository.

There are hints like [this](https://stackoverflow.com/questions/67001968/how-to-disable-maven-blocking-external-http-repositories) on several pages that http blocking can be bypassed with a `mirrorOf` definition, but I've not been able to make it work.

**Comment by daniel-beck** [comment]
> The artifact [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages) has been deployed to this new repository, along with its POM, sources and javadoc. A Maven metadat file has been autogenerated and looks the same as jcenter's

Any particular reason why?

**Comment by MarkEWaite** [comment]
> > The artifact [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages) has been deployed to this new repository, along with its POM, sources and javadoc. A Maven metadat file has been autogenerated and looks the same as jcenter's
> 
> Any particular reason why?

I could not find the artifact [org.connectbot.jbcrypt:jbcrypt:1.0.0](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Forg.connectbot.jbcrypt:jbcrypt?name=jbcrypt&type=packages) on repo.jenkins-ci.org in any repository other than jcenter-cache.  Since the goal is to remove jcenter-cache from the definition of the public virtual repository, it seemed like we need to copy that artifact to a new repository that can be included in the public virtual repository without including all of jcenter-cache.

Did that address your question or is there something more that I'm not understanding in the question?

**Comment by daniel-beck** [comment]
> Did that address your question or is there something more that I'm not understanding in the question?

From my proposal of the new repo holding these dependencies:

> populate exclusively by copying from cache to that new repo as admin

That trivially ensures identical artifacts.

For example, we don't have `*.asc` files now. No idea whether they're needed, but any difference seems unnecessary.

**Comment by basil** [comment]
> Is there a way to safely remove or exclude the outdated / incorrect json-path 2.4.0 that we are getting from the [Eclipse repository](https://repo.eclipse.org/content/groups/releases/com/jayway/jsonpath/json-path/2.4.0/json-path-2.4.0.pom)?

Googling brings up https://jfrog.com/help/r/jfrog-artifactory-documentation/basic-settings-for-remote-repositories which shows that you can configure exclude patterns on a remote repository (i.e., a cache). Based on this documentation I think we should delete the `json-path` dependency from our Eclipse remote repository (i.e., our cache) and add an exclude pattern so that it won't be downloaded again. Then requests for it from the JGit remote repository should 404 and the lookup should proceed to the (valid) version on Central.

**Comment by basil** [comment]
See [this page](https://developer.atlassian.com/server/framework/atlassian-sdk/working-with-maven/) for more information on the Atlassian repositories. https://packages.atlassian.com/maven-public/ contains just the core Atlassian libraries (sort of like our `releases`) while https://packages.atlassian.com/maven-external/ contains a lot of other stuff, including third-party libraries (sort of like our `public`). That is, the former could be cached by us, but the latter couldn't (otherwise we'd have the same bandwidth issue as with JCenter). Unfortunately, the Jira library is present in `maven-public` but the Crowd library is only available in `maven-external`. So I don't see a way around https://github.com/jenkinsci/crowd2-plugin depending directly on https://packages.atlassian.com/maven-external/ (including all its dependencies, which thankfully is only https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/integrations which is not published in any releases). For the Jira plugin, https://packages.atlassian.com/maven-public/ could be added to the build as in https://github.com/jenkinsci/jira-plugin/pull/578 (including downstream consumers, of which the only significant one is https://github.com/jenkinsci/blueocean-plugin/pull/2531), or we could start caching https://packages.atlassian.com/maven-public/ and include that in our `public` virtual repository, in which case we wouldn't need https://github.com/jenkinsci/jira-plugin/pull/578 or the `<repository>` portion of https://github.com/jenkinsci/blueocean-plugin/pull/2531.

**Comment by basil** [comment]
`promoted-builds` can only be fixed by adopting and re-releasing `project-inheritance` I think.

**Comment by basil** [comment]
> `promoted-builds` can only be fixed by adopting and re-releasing `project-inheritance` I think.

@MarkEWaite Would you like to do this or shall I?

**Comment by MarkEWaite** [comment]
> > `promoted-builds` can only be fixed by adopting and re-releasing `project-inheritance` I think.
> 
> @MarkEWaite Would you like to do this or shall I?

I'd prefer that you do it.  Thanks for the analysis that there really isn't another way except to adopt and release a new version.

**Comment by basil** [comment]
https://plugins.jenkins.io/scp/ hasn't been released in 13 years and has an open security vulnerability, so I think we should be deprecating this plugin rather than getting it to build.

@MarkEWaite I'd prefer that you do it.

**Comment by basil** [comment]
`project-inheritance` can't actually be adoped because it isn't in our GitHub organization. Rather I have filed https://github.com/jenkinsci/promoted-builds-plugin/pull/272 to remove `promoted-builds`'s (optional) integration with it.

**Comment by basil** [comment]
Open action items from my perspective:

- [ ] Decide whether or not we want to mirror https://packages.atlassian.com/maven-public/ and include it in the `public` virtual repository
    - [ ] Based on decision, update and/or close PRs in `jira-plugin`, `crowd2-plugin`, `blueocean-plugin`, and `configuration-as-code-plugin`.
- [ ] Confirm that we do not want to mirror https://packages.atlassian.com/maven-external/ because it includes third-party dependencies and would result in a similar bandwidth issue as mirroring JCenter.
- [ ] Formally deprecate `scp` and `project-inheritance`.

**Comment by basil** [comment]
I just discovered that we already have https://repo.jenkins-ci.org/ui/repos/tree/General/atlassian (which we are not being asked to disable), and it is already part of https://repo.jenkins-ci.org/artifactory/public. In any case, I confirmed that Jira plugin builds correctly with nothing but https://repo.jenkins-ci.org/releases/, https://repo.jenkins-ci.org/orphans/, https://repo.jenkins-ci.org/atlassian/, and Central (in that order), and I confirmed that Crowd2 plugin builds correctly with nothing but https://repo.jenkins-ci.org/releases, https://repo.jenkins-ci.org/atlassian, and Central (in that order). Based on these results I have closed the PRs in `jira-plugin` and `crowd2-plugin` (as well as the downstream PRs in `blueocean-plugin` and `configuration-as-code-plugin`).

I do not know why this was not included in https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1837820356. For the experiment to have scientific rigor, it should have included everything that is part of https://repo.jenkins-ci.org/artifactory/public, in the same order (minus JCenter, of course). If the experiment had been done this way, I do not think these false positives would have turned up.

**Comment by basil** [comment]
In my opinion it would be valuable to re-run the experiment from https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1837820356 but with the exact list of remote repositories that are in `public` (in the same order), minus JCenter, and with the addition of `orphans` (in the same position that we expect to add it to `public`), preferably also after implementing https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1839521681, but before the brownout. The expected results of this experiment re-run would be the disappearance of Jira-related problems, and the (potential!) appearance of new problems that we could not see before due to an unrealistic test environment.

**Comment by dduportal** [comment]
> > Did that address your question or is there something more that I'm not understanding in the question?
> 
> From my [proposal of the new repo holding these dependencies](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1838244646):
> 
> > populate exclusively by copying from cache to that new repo as admin
> 
> That trivially ensures identical artifacts. Per Damien,
> 
> > has been deployed to this new repository, along with its POM, sources and javadoc. A Maven metadat file has been autogenerated and looks the same as jcenter's
> 
> That looks very manual and results in differences. For example, we don't have `*.asc` files now. No idea whether they're needed, but any difference seems unnecessary.
> 
> If my proposed approach is not possible, or has drawbacks I'm unaware of, and that's the reason for the different approach, I'd like to know.

I failed to find a way to copy only selected dependency from the cache, so I did a manual "deploy" through the UI.

Thanks for pointing this out, I misunderstood your first message. Currently trying to copy from the cache repo following https://jfrog.com/help/r/jfrog-artifactory-documentation/move-and-copy-artifacts to see if it adds the `.asc` files.

**Comment by MarkEWaite** [comment]
The recommendation from @basil was exactly right.  I've redefined my `settings.xml` to include exactly the repositories that are included in the search order of the Jenkins repository and I believe I've found an additional issue that we should test during the brownout tomorrow.

@dduportal shared that the list of repositories included in the `public` virtual repository is available with the command:

```
curl https://repo.jenkins-ci.org/api/repositories/public
```

That provides the following output:

```json
{
  "key": "public",
  "packageType": "maven",
  "description": "All public repositories aggregated for the purpose of building Jenkins and its plugins",
  "repositories": [
    "snapshots",
    "releases",
    "shibboleth",
    "maven.jenkins-ci.org",
    "maven.twttr.com",
    "javanet2",
    "tmate",
    "jcenter",
    "oss.sonatype.org-releases",
    "cloudbees.public.release",
    "jgit",
    "netbeans",
    "fusesource",
    "atlassian"
  ],
  "rclass": "virtual"
}
```

When I define my settings.xml based on that definition, many of the artifacts that I expected to be delivered by Apache Maven Central are instead delivered from the `oss.sonatype.org-releases` cache on repo.jenkins-ci.org.

I think that we need to disable `jcenter`, `jcenter-cache`, and `oss.sonatype.org-releases` during the brownout tomorrow.  When I remove those from my settings file, I see that the expected artifacts are retrieved from Apache Maven Central.

**Comment by MarkEWaite** [comment]
## More details on configuration as code plugin build failure

With the [settings.xml that includes orphans](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1841330031) and replacing the https://repo.jenkins-ci.org/public/ with https://repo.jenkins-ci.org/releases/ in the pom.xml file of the configuration as code plugin, the plugin build fails because it cannot find `crowd-integration-client-common-5.1.5.pom`:

```
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/releases/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from shibboleth: https://repo.jenkins-ci.org/shibboleth/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from maven.jenkins-ci.org: https://repo.jenkins-ci.org/maven.jenkins-ci.org/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from maven.twttr.com: https://repo.jenkins-ci.org/maven.twttr.com/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from javanet2: https://repo.jenkins-ci.org/javanet2/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from tmate: https://repo.jenkins-ci.org/tmate/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from cloudbees.public.release: https://repo.jenkins-ci.org/cloudbees.public.release/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from jgit: https://repo.jenkins-ci.org/jgit/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from netbeans: https://repo.jenkins-ci.org/netbeans/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from fusesource: https://repo.jenkins-ci.org/fusesource/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from atlassian: https://repo.jenkins-ci.org/atlassian/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from incrementals: https://repo.jenkins-ci.org/incrementals/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
[WARNING] The POM for com.atlassian.crowd:crowd-integration-client-common:jar:5.1.5 is missing, no dependency information available
```

If I restore the https://repo.jenkins-ci.org/public/ in pom.xml, then that dependency is found in the "public" repository.  The build output is:

```
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/com/atlassian/crowd/crowd-integration-client-common/5.1.5/crowd-integration-client-common-5.1.5.pom (3.4 kB at 8.5 kB/s)
```

I think that means that the atlassian crowd components needed by the configuration as code plugin integration test is only available from one of the repositories that I've excluded from the settings.xml file (either jcenter or oss.sonatype.org-releases).

Based on that, I expect tomorrow's brownout to fail the build of the configuration as code plugin while `public` does not include the `jcenter` repository.

**Comment by basil** [comment]
After scouring the Internet a little further, I think I have found where it lives:

 https://packages.atlassian.com/mvn/maven-atlassian-external/ 

I confirmed that between https://packages.atlassian.com/maven-public/ and https://packages.atlassian.com/mvn/maven-atlassian-external/ Crowd 2 can be built successfully.

My new recommendation is to create two new remote repositories corresponding to https://packages.atlassian.com/maven-public/ and https://packages.atlassian.com/mvn/maven-atlassian-external/ and replace the existing `atlassian` entry with these two new ones during the brownout. This should be equivalent to what is currently coming from JCenter, without dragging in tons of other third-party libraries.

**Comment by MarkEWaite** [comment]
I have built 244 out of 248 repositories using the [previous settings.xml](https://github.com/jenkins-infra/helpdesk/issues/3842#issuecomment-1841330031) with the addition of https://packages.atlassian.com/maven-public/ and https://packages.atlassian.com/mvn/maven-atlassian-external/ as repositories.

**Comment by jtnord** [comment]
but as per the URL - these are not open source software contained here - they are subject to the atlassian licence
https://www.atlassian.com/legal/software-license-agreemen

so the question is should hosting of these plugins be allowed per https://www.jenkins.io/doc/developer/publishing/preparation/#license and that the libraries they require are not open source

**Comment by daniel-beck** [comment]
What license is this stuff distributed under? If it's proprietary, we should just suspend the plugin. See e.g. https://github.com/jenkins-infra/helpdesk/issues/3742 or https://github.com/jenkins-infra/update-center2/pull/720.

**Comment by basil** [comment]
Confluence Publisher is also impacted: https://github.com/jenkins-infra/helpdesk/issues/3856

**Comment by dduportal** [comment]
> The artifacts are there in the remote repositories:
> 
>     * https://packages.atlassian.com/maven-public/com/atlassian/jira/jira-rest-java-client-core/5.2.7/
> 
>     * https://packages.atlassian.com/mvn/maven-atlassian-external/com/atlassian/jira/jira-rest-java-client-core/5.2.7/
> 
> 
> https://repo.jenkins-ci.org/atlassian-maven-public/ is returning 401, not 404. Seems like it was not set up for anonymous access (i.e., an unrealistic test environment).

Pairing operation with @MarkEWaite today: the repository https://repo.jenkins-ci.org/artifactory/atlassian-maven-public is now available publicly (added to the permissions scheme "Any Remote" which adds Read and Cache to the `anonymous` user.

**Comment by dduportal** [comment]
Start of the 2nd brownout on repo.jenkins-ci.org with @MarkEWaite:

We've updated the `public` virtual repository to the following setup:

```bash
curl --silent https://repo.jenkins-ci.org/api/repositories/public | jq -r '.'
{
  "key": "public",
  "packageType": "maven",
  "description": "All public repositories aggregated for the purpose of building Jenkins and its plugins",
  "repositories": [
    "releases",
    "orphans",
    "atlassian-maven-public",
    "shibboleth",
    "maven.jenkins-ci.org",
    "maven.twttr.com",
    "javanet2",
    "tmate",
    "cloudbees.public.release",
    "jgit",
    "netbeans",
    "fusesource",
    "snapshots"
  ],
  "rclass": "virtual"
}
```

- Removed `jcenter` and `atlassian`
- Added `orphans` and `atlassian-maven-public`

**Comment by MarkEWaite** [comment]
After implementing the production change, we found that the artifactory plugin depends on a 3.1.7 release of a platform pom that is only available from the Spring plugins repository at https://repo.spring.io/plugins-release/ .  Other versions of that artifact are available from Atlassian public, but not that version.

@dduportal created a jcenter-orphans remote repository that includes a specific item

com.atlassian.pom:public-pom:pom:4.0.7 was then missing

**Comment by MarkEWaite** [comment]
The crawler job that detects updated tools is failing on ci.jenkins.io with a Grape error

* https://ci.jenkins.io/job/Infra/job/crawler/job/master

**Comment by dduportal** [comment]
> The crawler job that detects updated tools is failing on ci.jenkins.io with a Grape error
> 
>     * https://ci.jenkins.io/job/Infra/job/crawler/job/master
> 
> 
> Resolved by adding Maven central to the Grape repository list in:
> 
>     * [Add Maven Central to Grape configuration crawler#134](https://github.com/jenkins-infra/crawler/pull/134)

Thanks @basil for the batch of PRs to fix and improve the crawler (and @MarkEWaite @timja @NotMyFault for the revies/deploys).

**Comment by dduportal** [comment]
Update:

- Update the allow list pattern of `jcenter` to solve https://github.com/jenkins-infra/helpdesk/issues/3872 (see issue for details)
- Removed `jcenter-cache` and `atlassian-cache` from both `Any Remote` and `Anything` permissions scheme to ensure they cannot be reached anonymously (as such the outbound bandwidth should drastically decrease)

**Comment by MarkEWaite** [comment]
> * Removed `jcenter-cache` and `atlassian-cache` from both `Any Remote` and `Anything` permissions scheme to ensure they cannot be reached anonymously (as such the outbound bandwidth should drastically decrease)

Thanks very much.  Should the same change be applied to `oss.sonatype.org-releases` since it also contains a copy of Apache Maven Central?

**Comment by dduportal** [comment]
> > * Removed `jcenter-cache` and `atlassian-cache` from both `Any Remote` and `Anything` permissions scheme to ensure they cannot be reached anonymously (as such the outbound bandwidth should drastically decrease)
> 
> Thanks very much. Should the same change be applied to `oss.sonatype.org-releases` since it also contains a copy of Apache Maven Central?

The repository `oss.sonatype.org-releases` is no longer available anonymously: it requires authentication.

**Comment by dduportal** [comment]
Update:

- The repository `orphans` has been removed (in favor of adding filters in the `jcenter-orphans` mirror repository - https://github.com/jenkins-infra/helpdesk/issues/3884
- We forgot to clean the ACP cache: https://github.com/jenkins-infra/helpdesk/issues/3889
