### ISSUE TITLE
SSL certificate for repo.jenkins-ci.org expires Dec 20, 2023 (9 days)

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3843]
### Service(s)

Artifactory

### Summary

The SSL certificate used by https://repo.jenkins-ci.org/ will expire Dec 20, 2023.  We need to renew that certificate so that we don't disrupt Jenkins development.

### Reproduction steps

1. Open https://repo.jenkins-ci.org/ in a web browser
2. Use the browser right click on the certificate to view its details, confirm the Dec 20, 2023 expiration date

**Comment by MarkEWaite** [comment]
@dduportal , @smerle33 , or @lemeurherve this needs our attention within the next 3-4 days so that we don't disrupt Jenkins developers that use https://repo.jenkins-ci.org to download binary artifacts.

**Comment by dduportal** [comment]
Summary:

- Last year renewal is descibed in this email thread: https://groups.google.com/g/jenkins-infra/c/oRu3CySJWJo/m/DOF52U2fDAAJ
  - Koshuke did generate a 1-year certificate with his Godaddy account and sent it to us (encrypted)
  - Jforg did install the certificate with an instance restart (service down for 2-3 minutes)
  - We forgot to add a calendar event, which explains why we are late this year: to be done this year to avoid problem in 2024!

- Task list proposal (to be validated by the team):
  - [ ] Generate a Let'sencrypt certificate with DNS validation (as we do not control the webserver pointed by repo.jenkins-ci.org, but we control the domain).
  - [ ] Encrypt the certificate and the key with the jfrog + jenkins-infra GPG key and store it in our "sops" repository for secrets
  - [ ] Open an issue with JFrog to ask for certificate renewal

**Comment by smerle33** [comment]
lets encrypt certificates are limited in time so this would mean to deal with the renewal more often

**Comment by dduportal** [comment]
> lets encrypt certificates are limited in time so this would mean to deal with the renewal more often

Good catch, Let's Encrypt certificates are only 9à days (see https://letsencrypt.org/2015/11/09/why-90-days.html). Let's check if Azure or AWS allows us to generate a 1-year certificate.

**Comment by dduportal** [comment]
Problem: all free TLS certificate are provided for 90 days (automation or business model of the provider).

- Proposal 1: we generate a Let's Encrypt 90 days and then we'll see for the next reneal in 2 months
- Proposal 2: As we have an AWS account for Jenkins infra, my proposal is to generate a 1-year certificate from ACM as we can export it as per https://docs.aws.amazon.com/acm/latest/userguide/export-private.html

=> Let's make a discussion during today's team meeting so we can send the certificate later today

**Comment by timja** [comment]
That's for AWS Private CA which isn't ACM. Unsure if they will let you export public certificates.

**Comment by dduportal** [comment]
> That's for AWS Private CA which isn't ACM. Unsure if they will let you export public certificates.

You're correct: `It is not possible to export public certificates whether they are ACM-issued or imported.` from https://docs.aws.amazon.com/acm/latest/userguide/sdk-export.html.

Damn, I believe we'll have to go with a LE 90 days certificate and then we'll have to find another provider for this one (or ask JFrog). WDYT @timja ?

**Comment by dduportal** [comment]
For info, I've generated a 90-days valid LetsEncrypt certificate for `repo.jenkins-ci.org` using certbot and DNS challenge from lettuce VM. Cleaned up all the data on the VM and uploaded the certtificate and its key in our encrypted sops repo.

**Comment by timja** [comment]
> Damn, I believe we'll have to go with a LE 90 days certificate and then we'll have to find another provider for this one (or ask JFrog). WDYT @timja ?

Yeah no great options really unless we can get JFrog to support let's encrypt themselves.
The last time we asked their support people didn't understand the question.

Azure supports external CA's with:
https://learn.microsoft.com/en-us/azure/key-vault/certificates/create-certificate-signing-request?tabs=azure-portal#add-certificates-in-key-vault-issued-by-partnered-cas

but you need to have a separate account with them, and I assume you pay them directly as well.

**Comment by MarkEWaite** [comment]
> For info, I've generated a 90-days valid LetsEncrypt certificate for `repo.jenkins-ci.org` using certbot and DNS challenge from lettuce VM. Cleaned up all the data on the VM and uploaded the certificate and its key in our encrypted sops repo.

Will you open the ticket with JFrog support so that they can apply the certificate to the installation, or is that something that I should do?

**Comment by dduportal** [comment]
> > For info, I've generated a 90-days valid LetsEncrypt certificate for `repo.jenkins-ci.org` using certbot and DNS challenge from lettuce VM. Cleaned up all the data on the VM and uploaded the certificate and its key in our encrypted sops repo.
> 
> @dduportal will you open the ticket with JFrog support so that they can apply the certificate to the installation, or is that something that I should do?

@MarkEWaite I'm taking care of it now.

**Comment by dduportal** [comment]
Email sent with the (GPG) encrypted certificate and key. I've double checked the modulus (which are the same) before.

Notes for next time:

- From https://repo.jenkins-ci.org/ dahsboard, logged-in as admin (or authorized user) => select "Jfrog portal" external link
- It opens the "customer dashboard" with a nice UI at https://my.jfrog.com/subscriptions/34260686/dashboard
- Search on their KB (right panel) to find -> https://jfrog.com/help/r/transferring-my-sensitive-content-to-jfrog-using-public-key-encryption
- Their GPG key is linked in their page with instructions

**Comment by dduportal** [comment]
Update:

- @kohsuke received notification from JFrog that the certificate was almost expired. He started the procedure to have a GoDaddy 1 year certificate and a DNS validation is needed, done in https://github.com/jenkins-infra/azure-net/pull/180 (thanks Kohsuke ❤️ )
  - Waiting for him to tell us if it worked or if more action is needed. The Godaddy  certificate can be installed later as we have the Let's Encrypt
- Both @MarkEWaite and I sent distinct email to JFrog support asking to prioritize the certificate update

**Comment by dduportal** [comment]
- The new Let's Encrypt certificate for repo.jenkins-ci.org has been installed. It is valid until the 11 March 2024:

<img width="905" alt="Capture d’écran 2023-12-15 à 08 58 05" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/01238d86-a5b9-43f0-81d7-61a2b1682cf2">

**Comment by dduportal** [comment]
- A new calendar event has been added for the jenkins-infra-team for the 11 March 2024 with 4 notification (1 per week) before:

<img width="455" alt="Capture d’écran 2023-12-15 à 09 02 11" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/85e9ffd6-b7eb-43e4-801c-6019570c42de">

=> I'm gonna close the issue here as no more work is required. We'll continue checking with @kohsuke about the eventual Godaddy certificate in the email thread at https://groups.google.com/g/jenkins-infra/c/EgbRESb74oA/m/GogykGRFAwAJ


Thanks all!

**Comment by lemeurherve** [comment]
We received an alert from Let's Encrypt about its certificate expiration, but as we're using the certificate from GoDaddy renewed by @kohsuke (thanks!), this doesn't matter.
