### ISSUE TITLE
Add Pipeline agent build history plugin to weekly.ci.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3846]
### Service(s)

weekly.ci.jenkins.io

### Summary

The "build history" widget that is included in Jenkins core does not provide the history of Pipeline execution on Jenkins agents.  The [Pipeline agent build history plugin](https://github.com/jenkinsci/pipeline-agent-build-history-plugin) has been created by @mawinter69 that shows build history for Pipeline execution on agents.

The plugin requires Jenkins 2.434 or newer, so it can only be installed on weekly.ci.jenkins.io until an LTS baseline is released that includes 2.434

### Reproduction steps

1. Review the build history of an agent and confirm that it does not include Pipeline execution
2. Install the [Pipeline agent build history plugin](https://github.com/jenkinsci/pipeline-agent-build-history-plugin) and confirm that Pipeline build history is available from the "Extended build history" link on each agent

Refer to https://github.com/jenkinsci/pipeline-agent-build-history-plugin/pull/2 for some UI improvements ideas for the plugin

**Comment by MarkEWaite** [comment]
Thanks @dduportal  and thanks @mawinter69 for the plugin.

**Comment by dduportal** [comment]
> Thanks @dduportal and thanks @mawinter69 for the plugin.

Credits due to @smerle33 ❤️
