### ISSUE TITLE
Jira component archive

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3847]
### Service(s)

Jira

### Summary

Hi,

Can you please archive following components in Jira ?

`postgresql-fingerprint-storage-plugin`
`flyway-runner-plugin`

Related PRs

- https://github.com/jenkins-infra/repository-permissions-updater/pull/3664
- https://github.com/jenkins-infra/repository-permissions-updater/pull/3663

Issue tracker is moved to GitHub.

Regards,

**Comment by dduportal** [comment]
Both components have been archived:

![Capture d’écran 2023-12-04 à 16 39 51](https://github.com/jenkins-infra/helpdesk/assets/1522731/61b0e442-e428-47f9-a730-893eade5a70d)
![Capture d’écran 2023-12-04 à 16 40 26](https://github.com/jenkins-infra/helpdesk/assets/1522731/c9fbf786-c502-4724-abfe-cef43e0965da)


Thanks for your contribution on Jenkins!
