### ISSUE TITLE
Archive foj repository

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3849]
### Service(s)

GitHub

### Summary

While writing https://github.com/jenkins-infra/helpdesk/issues/3840, I noticed the ancient foj repository at https://github.com/orgs/jenkins-infra/teams/board/repositories?type=source

I think, 12 years later, we can safely archive it ;)

**Comment by dduportal** [comment]
The repository https://github.com/jenkins-infra/friend-of-jenkins (private) has been archived (with a README linking to this issue)
