### ISSUE TITLE
Archive the repository of the deprecated SCP plugin

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3850]
### Service(s)

GitHub

### Summary

The [SCP plugin](https://github.com/jenkinsci/scp-plugin#readme) has been [deprecated](https://plugins.jenkins.io/scp/).  Please archive the repository so it is clear to others that the plugin is not maintained.

### Reproduction steps

1. Confirmed that the repository https://github.com/jenkinsci/scp-plugin is not currently archived.  I would like it archived so that it is clear the plugin is not being maintained

**Comment by NotMyFault** [comment]
I've archived the repository.
