### ISSUE TITLE
Suspend Crowd2 integration plugin due to closed source dependency

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3854]
### Service(s)

Update center

### Summary

The [Crowd2 integration plugin](https://plugins.jenkins.io/crowd2/) is using dependencies that are closed source and are not licensed with an OSI approved open source license.  The Jenkins [project governance document](https://www.jenkins.io/project/governance/#license) and the [hosting page](https://www.jenkins.io/doc/developer/publishing/preparation/#license) state that we deliver plugins with open source licenses.

We should suspend distribution of the Crowd2 integration plugin.

The specific license of concern is:

* [Atlassian customer license](https://www.atlassian.com/legal/software-license-agreement)

The Atlassian EULA 3.0 links to the same license agreement.

From the /plugin/crowd2/wrapper/thirdPartyLicenses page of a Jenkins installation that includes the crowd2 plugin:

Using the [Atlassian Customer Agreement](https://www.atlassian.com/legal/software-license-agreement):

* com.atlassian.crowd:crowd-integration-api:5.1.5
* com.atlassian.crowd:crowd-integration-client-rest:5.1.5
* com.atlassian.crowd:embedded-crowd-api:5.1.5
* com.atlassian.crowd:crowd-integration-client-common:5.1.5

Using the [Atlassian 3.0 End User License Agreement](http://www.atlassian.com/end-user-agreement/)

* com.atlassian.collectors:atlassian-collectors-util:1.1

### Reproduction steps

1. Install Jenkins 2,426.1 (or any other recent Jenkins version)
2. Install the Crowd2 integration plugin
3. Open the /plugin/crowd2/wrapper/thirdPartyLicenses URL and confirm that you see something like this:

![screencapture-testing-b-markwaite-net-8080-plugin-crowd2-wrapper-thirdPartyLicenses-2023-12-08-10_19_12-edit](https://github.com/jenkins-infra/helpdesk/assets/156685/06397bc0-cf46-4f35-849e-cf95a1b6112c)

**Comment by basil** [comment]
https://bitbucket.org/atlassian/crowd-rest-client/src/master is Apache-licensed but the last commit was in 2015. https://bitbucket.org/atlassian/crowd-scala-rest-client/src/master/ is also Apache-licensed and the last commit was in 2021.

**Comment by MarkEWaite** [comment]
I've submitted a documentation pull request to the crowd2 plugin repository explaining why it is suspended.

* https://github.com/jenkinsci/crowd2-plugin/pull/240
