### ISSUE TITLE
repo.jenkins-ci.org does not support IPv6

### ISSUE THREAD

**Issue by cathychan** [jenkins-infra/helpdesk#3855]
### Service(s)

Artifactory

### Summary

Unable to reach repo.jenkins-ci.org from a pure IPv6 environment

### Reproduction steps

```
# host repo.jenkins-ci.org
repo.jenkins-ci.org is an alias for jenkinsci.jfrog.org.
jenkinsci.jfrog.org is an alias for endpointdns-prod-4-use1-lb.jfrog.io.
endpointdns-prod-4-use1-lb.jfrog.io is an alias for k8s-jfrogsaa-jfrogsaa-d1715df99e-93aeed5af6b09f0b.elb.us-east-1.amazonaws.com.
k8s-jfrogsaa-jfrogsaa-d1715df99e-93aeed5af6b09f0b.elb.us-east-1.amazonaws.com has address 52.22.177.50
k8s-jfrogsaa-jfrogsaa-d1715df99e-93aeed5af6b09f0b.elb.us-east-1.amazonaws.com has address 44.209.124.32
k8s-jfrogsaa-jfrogsaa-d1715df99e-93aeed5af6b09f0b.elb.us-east-1.amazonaws.com has address 34.225.228.28
```

**Comment by dduportal** [comment]
- `repo.jenkins-ci.org` is a CNAME record pointing to `jenkinsci.jfrog.org`:

```
$ dig CNAME +short repo.jenkins-ci.org
jenkinsci.jfrog.org.
```
=> It means we control the DNS records but not the destination: it is managed by JFrog.

- JFrog support has been contacted earlier today by email to request the IPv6 address(es) to use so we could create the proper DNS records.

**Comment by dduportal** [comment]
Answer from JFrog support:


> Hello Damien,
>
> Thank you for contacting JFrog Support.
> 
> I wanted to provide you with an update regarding your recent inquiry about IPv6 support in our cloud servers.
> 
> After consulting with our Production Engineering team, I regret to inform you that our current cloud infrastructure does not support IPv6. We are operating exclusively on IPv4, and all network configurations and services are tailored to this protocol.


I've asked them how do they handle Indian users from IPv6-only ISPs (ref. https://dot.gov.in/ipv6-transition), but for now there is nothing the Jenkins infra can do about this (hosting a IPv6 <-> Ipv4 gateway even restricted to repo.jenkins-ci.org would costs us 1000s of bucks per months for the bandwidth alas).

**Comment by dduportal** [comment]
For info, created https://jfrog.atlassian.net/browse/RTFACT-30209 as an RFE as instructed by JFrog's support
