### ISSUE TITLE
Delete jenkins.io-account

### ISSUE THREAD

**Issue by Festus78** [jenkins-infra/helpdesk#3858]
### Type(s) of account issue

I want my account to be deleted

### Summary

Please delete my account including all associated data.

### jenkins.io account username

Festus

### jenkins.io account email

t.collenberg@boniversum.de

### Which URL are you trying to login at?

- https://accounts.jenkins.io
- https://issues.jenkins.io/

**Comment by dduportal** [comment]
Thanks, your account has been deleted.
