### ISSUE TITLE
CD release for the for the google-oauth-plugin is not working properly

### ISSUE THREAD

**Issue by bzzitsme** [jenkins-infra/helpdesk#3861]
### Service(s)

Artifactory, release.ci.jenkins.io

### Summary

CD release for the [google-oauth-plugin](https://github.com/jenkinsci/google-oauth-plugin) is not working properly.

- First run https://github.com/jenkinsci/google-oauth-plugin/actions/runs/7163843230/job/19502915690
- Second run https://github.com/jenkinsci/google-oauth-plugin/actions/runs/7164795245/job/19505520742
- Third run https://github.com/jenkinsci/google-oauth-plugin/actions/runs/7167874142/job/19514836734

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project google-oauth-plugin: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:google-oauth-plugin:pom:1.322.v7b_940a_a_1a_5c8 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authorization failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/google-oauth-plugin/1.322.v7b_940a_a_1a_5c8/google-oauth-plugin-1.322.v7b_940a_a_1a_5c8.pom, status: 403 Forbidden -> [Help 1]

During the last two unsuccessful runs, a specific message was noted in the logs. The CD was initiated by @olamy and @rsandell. Both individuals are listed and should possess the necessary permissions for the CD process.
https://github.com/jenkins-infra/repository-permissions-updater/blob/4823c9bacd63ae7d88340326121afae8f80e8a0c/permissions/plugin-google-oauth-plugin.yml#L18-L19

**Comment by jtnord** [comment]
the releases are failing as a pror release partly succeeded (artifactory upload happened but the tag & release notes failed).

**Comment by jtnord** [comment]
this is an issue with the project.  some files are not correctly formatted and the google plugin formatting is just awful (does it on release not enforced earlier).

https://github.com/jenkinsci/google-oauth-plugin/actions/runs/7163843230/job/19502915690#step:4:198

**Comment by jtnord** [comment]
fixed by https://github.com/jenkinsci/google-oauth-plugin/pull/211  release is auto made at https://github.com/jenkinsci/google-oauth-plugin/releases/tag/1.324.va_a_17c83c2a_49

**Comment by bzzitsme** [comment]
Thank you @jtnord 🙂
