### ISSUE TITLE
Remove Pipeline Agent Build History plugin from infra.ci.jenkins.io

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3862]
### Service(s)

infra.ci.jenkins.io

### Summary

We should remove https://github.com/jenkinsci/pipeline-agent-build-history-plugin from infra.ci.jenkins.io as it might be the cause of some recent errors encountered on this controller.

As noted by @jglick in a private chanel, https://github.com/jenkinsci/pipeline-agent-build-history-plugin/blob/dbfac0844c1e9338856fea3df9dee26ccb2b9b9e/src/main/java/io/jenkins/plugins/agent_build_history/AgentBuildHistory.java#L71-L72 & https://github.com/jenkinsci/pipeline-agent-build-history-plugin/blob/dbfac0844c1e9338856fea3df9dee26ccb2b9b9e/src/main/java/io/jenkins/plugins/agent_build_history/AgentBuildHistory.java#L83-L84 can take down a controller with more than a few hundred historical builds (across all projects).

**Comment by lemeurherve** [comment]
For #3846 the plugin has been added to our weekly controller image so it could be deployed on weekly.ci.jenkins.io. But doing so made it also deployed on infra.ci.jenkins.io as it's the same image we're using on both.

Should extra work be done to still deploy it on weekly.ci.jenkins.io even if this instance doesn't have any build?

**Comment by MarkEWaite** [comment]
> Should extra work be done to still deploy it on weekly.ci.jenkins.io even if this instance doesn't have any build?

I think that we should remove it from all the locations.  It was a useful experiment for weekly.ci.jenkins.io but is not viable for our scale of Jenkins controllers.

**Comment by dduportal** [comment]
> > Should extra work be done to still deploy it on weekly.ci.jenkins.io even if this instance doesn't have any build?
> 
> I think that we should remove it from all the locations. It was a useful experiment for weekly.ci.jenkins.io but is not viable for our scale of Jenkins controllers.

I'm not even sure it was viable for weekly.ci.jenkins.io as this instance does not have any agent (unless I missed something in the past weeks?)

**Comment by MarkEWaite** [comment]
> I'm not even sure it was viable for weekly.ci.jenkins.io as this instance does not have any agent (unless I missed something in the past weeks?)

Good point.  You're right that it was not going to help weekly unless agents were added.

**Comment by dduportal** [comment]
@lemeurherve once https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1433#pullrequestreview-1778082965 is merged, released and deployed, don't forget you'll have to manually remove the plugin (either from the jenkins_home or the UI followed by a pod deletion)
