### ISSUE TITLE
Write access to a new user for ci-with-toad-edge-plugin

### ISSUE THREAD

**Issue by mkumar-quest** [jenkins-infra/helpdesk#3863]
### GitHub repositories

https://github.com/jenkinsci/ci-with-toad-edge-plugin/

### GitHub users to have permission

DashlineJoveDSouza

URL:  https://github.com/DashlineJoveDSouza

### Permission level

Write

### Justification

A new dev member will need write access.

**Comment by NotMyFault** [comment]
Invite sent.
