### ISSUE TITLE
s390 agent availability checks are failing

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3864]
### Reproduction steps

1. Restore the s390x and s390docker items to the `check-agent-availability` branch of the repository and you'll see that the tests fail.

### Expected Results

Tests should pass

### Actual Results

Tests fail unexpectedly, when they were passing consistently before

**Comment by dduportal** [comment]
Issue transferred jenkins-infra/acceptance-tests to jenkins-infra/helpdesk for better visibility and because the scope is beyond the acceptance test: it is related to the provisioning of s390x agent along with ci.jenkins.io controller setup

**Comment by dduportal** [comment]
- Installed Maven 3.9.6 in the `s390x` VM (in the path by Jenkins agent setup e.g. in `/home/jenkins/tools/apache-maven-3.9.6`) + updated the `.profile` to also point to this Maven version
- Added https://github.com/jenkins-infra/acceptance-tests/commit/97cd491fbd6123eb3e77c8045120cf697531d9f7 to revert `s390x` monitoring and improve the script outputs when `mvn` binary is absent or failing

**Comment by dduportal** [comment]
=> build is green again: https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/3186/pipeline-graph/
