### ISSUE TITLE
Tool crawler data is out of date

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3869]
### Service(s)

trusted.ci.jenkins.io

### Summary

The crawler job on trusted.ci.jenkins.io that updates the tool installer data seems to no longer be submitting updates.  The [updates.jenkins.io page](https://updates.jenkins.io/updates/?C=M;O=D) shows:

| Name | Date | Size  |
|----------|----------|---|
| sp.sd.flywayrunner.installation.FlywayInstaller.json.html | 2023-12-16 08:24 | 165K |  
| ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstaller.json.html | 2023-12-16 08:24 | 16K |  
| org.sbuild.jenkins.plugin.SBuildInstaller.json.html | 2023-12-16 08:24 | 9.1K |  
| org.jvnet.hudson.plugins.SbtPluginBuilder.SbtInstaller.json.html | 2023-12-16 08:24 | 21K |  

The data was confirmed updating after:

* https://github.com/jenkins-infra/crawler/pull/134

I didn't confirm that updates were happening after

* https://github.com/jenkins-infra/crawler/pull/135
* https://github.com/jenkins-infra/crawler/pull/136

The [build job on ci.jenkins.io](https://ci.jenkins.io/job/Infra/job/crawler/job/master/) is passing as indicated by the embeddable build status [![Build Status](https://ci.jenkins.io/job/Infra/job/crawler/job/master/badge/icon)](https://ci.jenkins.io/job/Infra/job/crawler/job/master/)

### Reproduction steps

1. Open the [updates.jenkins.io page](https://updates.jenkins.io/updates/?C=M;O=D) and confirm that data has not been updated in at least 8 hours

**Comment by basil** [comment]
Have you confirmed that https://github.com/jenkins-infra/jenkins-infra/pull/3221 is deployed?

**Comment by MarkEWaite** [comment]
> Have you confirmed that [jenkins-infra/jenkins-infra#3221](https://github.com/jenkins-infra/jenkins-infra/pull/3221) is deployed?

I have not.  I have lost my instructions that would allow me to connect to `trusted.ci.jenkins.io` so I need to rely on others who have access to that system in order to understand the current state of the Jenkins job on that machine.  I have VPN access so that I can check the status of release.ci.jenkins.io and I've had access to trusted.ci.jenkins.io in the past, but it has been long enough that I've lost my connection instructions.

**Comment by basil** [comment]
I don't have access either but I suppose this could be easily fixed by anyone who has access updating the tool installation.

**Comment by NotMyFault** [comment]
In case this helps:
```
13:19:36  + echo = Crawler 'adoptopenjdk.groovy':
13:19:36  = Crawler 'adoptopenjdk.groovy':
13:19:36  + groovy -Dgrape.config=./grapeConfig.xml ./lib/runner.groovy adoptopenjdk.groovy
13:19:36  Caught: groovy.lang.MissingMethodException: No signature of method: static java.lang.System.setProperty() is applicable for argument types: (java.lang.String, java.lang.String) values: [mavenVersion, 3.0]
13:19:36  Possible solutions: hasProperty(java.lang.String), getProperties()
13:19:36  groovy.lang.MissingMethodException: No signature of method: static java.lang.System.setProperty() is applicable for argument types: (java.lang.String, java.lang.String) values: [mavenVersion, 3.0]
13:19:36  Possible solutions: hasProperty(java.lang.String), getProperties()
13:19:36  	at runner.run(runner.groovy:2)
13:19:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:19:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
13:19:36  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
The error repeats for all .groovy files until the build finishes and fails.

**Comment by basil** [comment]
> In case this helps

It does not help. What would help is deploying https://github.com/jenkins-infra/jenkins-infra/pull/3221 by updating the tool installation as previously suggested in https://github.com/jenkins-infra/helpdesk/issues/3869#issuecomment-1858882340.

**Comment by MarkEWaite** [comment]
I've merged https://github.com/jenkins-infra/jenkins-infra/pull/3221

**Comment by MarkEWaite** [comment]
The [updates.jenkins.io page](https://updates.jenkins.io/updates/?C=M;O=D) now shows a more recent time.  I believe this is resolved by the merge of https://github.com/jenkins-infra/jenkins-infra/pull/3221

**Comment by NotMyFault** [comment]
> The [updates.jenkins.io page](https://updates.jenkins.io/updates/?C=M;O=D) now shows a more recent time. I believe this is resolved by the merge of [jenkins-infra/jenkins-infra#3221](https://github.com/jenkins-infra/jenkins-infra/pull/3221)

I've changed the setting manually on trusted.ci and kicked off a build of the crawler which finished successfully. Once deployed, future builds are successful too, thanks for the merge \o/
