### ISSUE TITLE
Archive repo database-drizzle-plugin

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3870]
### Service(s)

GitHub

### Summary

Hi,

Please archive Archive https://github.com/jenkinsci/database-drizzle-plugin

See https://github.com/jenkins-infra/update-center2/pull/757

Thanks!

**Comment by dduportal** [comment]
Waiting for https://status.jenkins.io/issues/2023-12-18-jira-outage/ to be closed before proceeding

**Comment by NotMyFault** [comment]
I've archived the repository.

**Comment by dduportal** [comment]
> I've archived the repository.

@NotMyFault

**Comment by NotMyFault** [comment]
> > I've archived the repository.
> 
> @NotMyFault we'll have to redo this tomorrow (see my comment above) as JIRA is going to be restored to its 6 december state)

What does archiving a GitHub repository has to do with Jira?

**Comment by dduportal** [comment]
> > > I've archived the repository.
> > 
> > 
> > @NotMyFault we'll have to redo this tomorrow (see my comment above) as JIRA is going to be restored to its 6 december state)
> 
> What does archiving a GitHub repository has to do with Jira?

My sincere apologies: I thought it was about a JIRA component 🤦 Sorry for the noise here, and thanks for taking care of it!

**Comment by NotMyFault** [comment]
No worries, I was equally confused with the JIRA stuff 😅
