### ISSUE TITLE
Plugin not showing up on the plugin-site

### ISSUE THREAD

**Issue by mhamzak008** [jenkins-infra/helpdesk#3871]
### Problem with this page

https://github.com/jenkinsci/jsm-alert-plugin

### Expected behavior

The plugin should be auto listed on https://plugins.jenkins.io/

### Actual behavior

The plugin is not showing on the [plugin-site](https://plugins.jenkins.io/) and is subsequently not searchable from within the Jenkins' instances. Even though: 
- The plugin has been successfully published to the artifactory [here](https://repo.jenkins-ci.org/ui/packages/gav:%2F%2Fio.jenkins.plugins:jsm-alert?name=jsm-alert&type=packages) 
- We have the README file in the root of the directory [here](https://github.com/jenkinsci/jsm-alert-plugin/blob/master/README.md)
- We have the url in the pom of the plugin pointed to the Github repo [here](https://github.com/jenkinsci/jsm-alert-plugin/blob/master/pom.xml#L21)

**Comment by halkeye** [comment]
  curl -qLs 'https://updates.jenkins.io/update-center.actual.json' | jq '.plugins["jsm-alert"].releaseTimestamp'
"2023-12-18T18:04:41.00Z"
  TZ=UTC date --iso-8601=seconds
2023-12-18T18:16:26+00:00

looks like it was released 10 min ago, it takes time for everything to get updated.

**Comment by MarkEWaite** [comment]
@mhamzak008 you can see progress from the [Jenkins update center](https://updates.jenkins.io/latest/) where you will see that your plugin is already in the list of available plugins.  The page https://updates.jenkins.io/latest/jsm-alert.hpi?mirrorlist shows the current status of the mirrors for the plugin.

Users that refresh the index from the plugin manager page on a Jenkins controller can already download and use the plugin.

The plugin documentation and other information won't be available on https://github.com/jenkinsci/jsm-alert-plugin for 3-6 hours.

**Comment by lemeurherve** [comment]
@mhamzak008 your plugin is now available on plugins.jenkins.io: https://plugins.jenkins.io/jsm-alert/
