### ISSUE TITLE
`declarative-pipeline-migration-assistant-plugin` no longer compiles

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3872]
### Service(s)

Artifactory

### Summary

`declarative-pipeline-migration-assistant-plugin`, which is in BOM, no longer seems to compile. `mvn clean verify -DskipTests` shows:

> [ERROR] Failed to execute goal on project declarative-pipeline-migration-assistant: Could not resolve dependencies for project org.jenkins-ci.plugins.to-declarative:declarative-pipeline-migration-assistant:hpi:1.6.2-SNAPSHOT: Failed to collect dependencies at org.jenkins-ci.plugins:jira:jar:3.9 -> com.atlassian.jira:jira-rest-java-client-core:jar:5.2.4 -> com.atlassian.event:atlassian-event:jar:4.1.1: Failed to read artifact descriptor for com.atlassian.event:atlassian-event:jar:4.1.1: The following artifacts could not be resolved: com.atlassian.pom:base-pom:pom:5.0.18 (absent): com.atlassian.pom:base-pom:pom:5.0.18 was not found in https://repo.jenkins-ci.org/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]

I confirmed the plugin was [building correctly](https://ci.jenkins.io/job/Plugins/job/declarative-pipeline-migration-assistant-plugin/job/master/161/) after:

- https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/230

I didn't confirm that the plugin was building correctly after:

- https://github.com/jenkins-infra/helpdesk/issues/3842

### Reproduction steps

Run `mvn clean verify -DskipTests` and confirm that the plugin no longer compiles.

**Comment by dduportal** [comment]
Reproduction from a clean base (as ci.jenkins.io does not fail due to artifacts being cached in ACP for now)

- Step 1: cloned the plugin repository and set it up to run with Maven 3.9.6 and Temurin JDK 17.0.9
- Step 2: cleaned up my `$HOME/.m2` directory to ensure no cache and no Maven predefined settings
- Step 3: reproduced the error with `mvn clean verify -DskipTests`

Then, as Artifactory administrator:

- Step 1: locate the missing artifact between the former used `atlassian` or `jcenter` repositories => it was in `jcenter`
- Step 2: updated the `jcenter-orphans`  filter to allow artefacts matching the pattern `com/atlassian/pom/**/*`
- Step 3, ran `mvn clean verify -DskipTests -U` (the `-U` flag forces Maven to update artifacts in the local cache) which suceeded and the artefacts are now visible on https://repo.jenkins-ci.org/public
- Step 4: "end to end" test by removin (again) my `$HOME/.m2` directory and running from scratch (again) the `mvn clean verify -DskipTests` command

**Comment by dduportal** [comment]
@basil can you confirm it is ok for you with the changes by closing the issue?

**Comment by basil** [comment]
Rather suggest upgrading the Jira dependency in `declarative-pipeline-migration-assistant` to a version that doesn't require any Atlassian dependencies from `jcenter`.

**Comment by dduportal** [comment]
> Rather suggest upgrading the Jira dependency in `declarative-pipeline-migration-assistant` to a version that doesn't require any Atlassian dependencies from `jcenter`.

I'm not sure if your comment ask the infra team to do it, or you or someone else.
I'm not willing to do it as I don't have enough time to dig in a dependency upgrade case, sorry :|

**Comment by MarkEWaite** [comment]
> > Rather suggest upgrading the Jira dependency in `declarative-pipeline-migration-assistant` to a version that doesn't require any Atlassian dependencies from `jcenter`.
> 
> I'm not sure if your comment ask the infra team to do it, or you or someone else. I'm not willing to do it as I don't have enough time to dig in a dependency upgrade case, sorry :|

I'm interested in doing that upgrade.  It will help that plugin in several ways.

**Comment by dduportal** [comment]
Closing as https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/237 is merged.

If we misunderstood or missed something, please reopen with a pointer.

**Comment by basil** [comment]
Now that https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/237 has been merged, has the temporary workaround added in https://github.com/jenkins-infra/helpdesk/issues/3872#issuecomment-1862359367 been removed?

**Comment by MarkEWaite** [comment]
> Now that [jenkinsci/declarative-pipeline-migration-assistant-plugin#237](https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/237) has been merged, has the temporary workaround added in [#3872 (comment)](https://github.com/jenkins-infra/helpdesk/issues/3872#issuecomment-1862359367) been removed?

I don't think that the workaround can be removed without breaking the compilation of previous versions of the plugin.  Have I missed something in that process?

**Comment by basil** [comment]
Indeed, though I do not think supporting compilation of previous versions of plugins with unusual configurations should be a goal, as this would impose a heavy operational cost (in terms of workarounds like the above with an unbounded expiration date) for too small a benefit. For example, not all previous versions of the Jira plugin compile right now after the recent Artifactory changes, and I think this is fine. If it were a goal, then we should have tested not only compilation of the main branch of the top 200 plugins but also compilation of every previous version of the top 200 plugins. I think the calculus for old versions of core is different — we should strive to support compilations of old versions of core (e.g. with the older `jbcrypt`) since the fact that many plugins depend on core results in the impact being far greater.

**Comment by MarkEWaite** [comment]
Thanks.  I see your point.

**Comment by dduportal** [comment]
> Now that [jenkinsci/declarative-pipeline-migration-assistant-plugin#237](https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/237) has been merged, has the temporary workaround added in [#3872 (comment)](https://github.com/jenkins-infra/helpdesk/issues/3872#issuecomment-1862359367) been removed?

- The pattern `com/atlassian/pom/**/*` has been removed from `jcenter-oprhans` mirror repository.
- A build on ci.jenkins.io has been triggered to check the impact: https://ci.jenkins.io/job/Plugins/job/declarative-pipeline-migration-assistant-plugin/job/master/164/console
- Currently running a build from scratch locally

**Comment by basil** [comment]
No, thank you very much!
