### ISSUE TITLE
Apply for docker-openvpn VPN access for release.ci.jenkins.io

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#3873]
### Service(s)

release.ci.jenkins.io, VPN

### Summary

I would like to apply for access for [docker-openvpn](https://github.com/jenkins-infra/docker-openvpn) for `release.ci.jenkins.io` as a Jenkins LTS release lead.

**Comment by dduportal** [comment]
Hi @krisstern! Thanks for the issue, it looks good.

The next step for you is to follow instructions at https://github.com/jenkins-infra/docker-openvpn#howto-get-client-access until you've opened the PR in https://github.com/jenkins-infra/docker-openvpn

**Comment by dduportal** [comment]
Update:
- https://github.com/jenkins-infra/docker-openvpn/pull/323 signed, approved and merged. The Docker image is currently being built and released

ToDo:
- Deploy the new released version to production

**Comment by dduportal** [comment]
@krisstern https://github.com/jenkins-infra/jenkins-infra/pull/3233 was deployed to production. Can you test your setup and report in this issue?

**Comment by krisstern** [comment]
Hi @dduportal I am writing to report that I have followed the instructions and tested my setup for VPN access. And, when I do `dig release.ci.jenkins.io` a the terminal with the VPN on, I get:

```
; <<>> DiG 9.10.6 <<>> release.ci.jenkins.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23726
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;release.ci.jenkins.io.		IN	A

;; ANSWER SECTION:
release.ci.jenkins.io.	300	IN	CNAME	private.privatek8s.jenkins.io.
private.privatek8s.jenkins.io. 300 IN	A	10.248.1.5

;; Query time: 29 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Dec 27 20:38:45 HKT 2023
;; MSG SIZE  rcvd: 99
```

So everything seems okay.

**Comment by dduportal** [comment]
> Hi @dduportal I am writing to report that I have followed the instructions and tested my setup for VPN access. And, when I do `dig release.ci.jenkins.io` a the terminal with the VPN on, I get:
> 
> ```
> ; <<>> DiG 9.10.6 <<>> release.ci.jenkins.io
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23726
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 4096
> ;; QUESTION SECTION:
> ;release.ci.jenkins.io.		IN	A
> 
> ;; ANSWER SECTION:
> release.ci.jenkins.io.	300	IN	CNAME	private.privatek8s.jenkins.io.
> private.privatek8s.jenkins.io. 300 IN	A	10.248.1.5
> 
> ;; Query time: 29 msec
> ;; SERVER: 192.168.1.1#53(192.168.1.1)
> ;; WHEN: Wed Dec 27 20:38:45 HKT 2023
> ;; MSG SIZE  rcvd: 99
> ```
> 
> So everything seems okay.

Thanks for reporting @krisstern ! 
Can you try a `curl --verbose https://release.ci.jenkins.io` command to confirm the requests are routed through the VPN please?

I'm asking because the `dig` command alone only requests the DNS records which are public, while emitting an HTTP request to the service will confirm.

**Comment by NotMyFault** [comment]
They also need `release-core` in keycloak, to interact with anything on release.ci ftr.

**Comment by krisstern** [comment]
If I do `curl --verbose https://release.ci.jenkins.io` now I get the following:

```bash
*   Trying 10.248.1.5:443...
* Connected to release.ci.jenkins.io (10.248.1.5) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=release.ci.jenkins.io
*  start date: Nov 18 13:49:15 2023 GMT
*  expire date: Feb 16 13:49:14 2024 GMT
*  subjectAltName: host "release.ci.jenkins.io" matched cert's "release.ci.jenkins.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://release.ci.jenkins.io/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: release.ci.jenkins.io]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.4.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: release.ci.jenkins.io
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/2 403 
< date: Fri, 29 Dec 2023 01:53:00 GMT
< content-type: text/html;charset=utf-8
< x-content-type-options: nosniff
< set-cookie: JSESSIONID.769df4aa=node0recsz81sv5fl1iz6se4vqx39928502.node0; Path=/; Secure; HttpOnly
< expires: Thu, 01 Jan 1970 00:00:00 GMT
< x-hudson: 1.395
< x-jenkins: 2.426.2
< x-jenkins-session: 8ce6a603
< strict-transport-security: max-age=31536000; includeSubDomains
< 
<html><head><meta http-equiv='refresh' content='1;url=/login?from=%2F'/><script>window.location.replace('/login?from=%2F');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
-->

* Connection #0 to host release.ci.jenkins.io left intact
</body></html>
```

**Comment by dduportal** [comment]
> They also need `release-core` in keycloak, to interact with anything on release.ci ftr.

Thanks for the reminder! Please note it is `release-core-dev` (these groups are a mess, it seems mandatory to clean up really soon).

@krisstern I've grantedf you the access through this group membership. With the VPN connected, you should be able to log-in to release.ci.jenkins.io and vie jobs (and build/cancel them)

**Comment by krisstern** [comment]
Thanks @dduportal and @NotMyFault!
