### ISSUE TITLE
eee

### ISSUE THREAD

**Issue by Azavoloka7** [jenkins-infra/helpdesk#3876]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account username

Zavoloka

### jenkins.io account email

usercurrent@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by basil** [comment]
What does `MyFirstExpJenkins` mean? I can understand not receiving any email, but I cannot understand the meaning of `MyFirstExpJenkins` in the context of this issue synopsis.

**Comment by dduportal** [comment]
Hi @Azavoloka7 , can you:

- Update the issue title to materialize your intent (as pointed out in @basil 's comment above)
- Check your email's spam box: our system shows that the email was sent to the email usercurrent@gmail.com with success for each of your attempts to reset the password. Alternatively, you can create a new account.

Let us know

**Comment by Azavoloka7** [comment]
> Hi @Azavoloka7 , can you:
> 
> - Update the issue title to materialize your intent (as pointed out in @basil 's comment above)
> - Check your email's spam box: our system shows that the email was sent to the email usercurrent@gmail.com with success for each of your attempts to reset the password. Alternatively, you can create a new account.
> 
> Let us know

It's my first touch a Jenkins. I don't use it

**Comment by dduportal** [comment]
> > Hi @Azavoloka7 , can you:
> > 
> > * Update the issue title to materialize your intent (as pointed out in @basil 's comment above)
> > * Check your email's spam box: our system shows that the email was sent to the email [usercurrent@gmail.com](mailto:usercurrent@gmail.com) with success for each of your attempts to reset the password. Alternatively, you can create a new account.
> > 
> > Let us know
> 
> It's my first touch a Jenkins. I don't use it

If I understand correctly, you do not need an account on accounts.jenkins.io to use on your Jenkins instance.

accounts.jenkins.io is only used to open issues on issues.jenkins.io or if you are a Jenkins code contributor.

On a Jenkins instance, you have to follow either the wizard (to create the initial administrator account which is local) or configure authentication to your own authentication system.

**Comment by Azavoloka7** [comment]
thank you all, guys!
