### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Amol8221** [jenkins-infra/helpdesk#3877]
### Type(s) of account issue

I didn't receive any email

### Summary

I was Entering wrong mail id.thats reason i was not recived password on mail.try to create the another account jenkins cant respond.kindly suggest how to edit the mail or create the new jenkins account. 

### jenkins.io account username

Amol_8221

### jenkins.io account email

amol.ballal2212@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @Amol8221 you have to wait 24 hours after the initial creation to let the antispam see you again as "allowed" to create a new account.

**Comment by dduportal** [comment]
Closing as no answer from requester
