### ISSUE TITLE
i couldn't remember

### ISSUE THREAD

**Issue by hudaaa25** [jenkins-infra/helpdesk#3878]
### Type(s) of account issue

I've lost my password

### Summary

i can't remember my password and email. but i do remember my username

### jenkins.io account username

salfa

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @hudaaa25 , you can specify your username in the form at https://accounts.jenkins.io/passwordReset and then check all your email accounts.

Without email knowledge on your side, you can't prove you're the user `salfa` and as such you'll have to create a new account.

**Comment by dduportal** [comment]
Closing as no answer from requester
