### ISSUE TITLE
ci.jenkins.io install `coverage-badges-extension-plugin`

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3879]
### What feature do you want to see added?

Since `embeddable-build-status` was kept I would like to also display code coverage badges without using any external service like codecov.io or shields.io

Can we install https://github.com/jenkinsci/coverage-badges-extension-plugin in ci.jenkins.io ?

Thanks

**Comment by NotMyFault** [comment]
+1, thanks for creating the extension plugin!

**Comment by MarkEWaite** [comment]
+1 from me as well.  I've installed the plugin on my test configuration also.

**Comment by basil** [comment]
+1 from me as well, very cool plugin!

**Comment by dduportal** [comment]
Given that:

- `embeddable-build-status` is maintained (as per https://github.com/jenkins-infra/helpdesk/issues/3013 end result)
- This request looks providing value and is endorsed by at least 3 board member with extended knowledge 
- The security risk is low for ci.jenkins.io (public facing instance already treated as potentially compromised e.g. with no sensitive credential or permissions)
- The performance risk is low (and can be easily fixed if any)

=> then let's roll!


+1

**Comment by dduportal** [comment]
Plugin installed on ci.jenkins.io (https://github.com/jenkins-infra/jenkins-infra/pull/3236 merged):

<img width="1555" alt="Capture d’écran 2024-01-03 à 07 40 45" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/f1500144-9e48-4534-af95-a2acc6e7502d">


Many thanks @jonesbusy !
