### ISSUE TITLE
Replace code-coverage-api with coverage

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3880]
### Service(s)

ci.jenkins.io

### Summary

[code-coverage-api](https://plugins.jenkins.io/code-coverage-api/#plugin-content-this-plugin-reached-end-of-life) is deprecated in favor its successor; [coverage](https://plugins.jenkins.io/coverage/)

**Comment by dduportal** [comment]
- Approved, merged and deployed
- Removed the deprecated plugin in ci.jenkins.io
- Restarted the controller: no more depreciation message

**Comment by dduportal** [comment]
Reopening as both release.ci and infra.ci seems to also have this plugin installed:


<img width="1567" alt="Capture d’écran 2024-01-02 à 15 23 46" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/1ed473ef-6d47-452e-a86a-9ba38ccd1c21">

**Comment by NotMyFault** [comment]
> Reopening as both release.ci and infra.ci seems to also have this plugin installed:
> 
> <img alt="Capture d’écran 2024-01-02 à 15 23 46" width="1567" src="https://private-user-images.githubusercontent.com/1522731/293712361-1ed473ef-6d47-452e-a86a-9ba38ccd1c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDYyNjUsIm5iZiI6MTcwNDIwNTk2NSwicGF0aCI6Ii8xNTIyNzMxLzI5MzcxMjM2MS0xZWQ0NzNlZi02ZDQ3LTQ1MmUtYTg2YS05YmEzOGNjZDFjMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMTQzMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjljYTJhYzRhZjg5YTY0MjIzMGFkMWE5NzU1ZjRkNTdjMDVmMGJhZGE4YjBmNzQxY2E4MmUxNGYxOTE4NWM3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fbhP3MH8SfAJRkc65Tt335kp-PG4Ikmeoe7-Q0Eyt6I">

Thanks for checking, I didn't take a look at the other instances 👀

**Comment by dduportal** [comment]
>     * Alas it appeared that `cobertura` is a dependency of `github-autostatus`: https://plugins.jenkins.io/github-autostatus/dependencies/ . This plugin is not needed (replaced by `github-checks`) so we'll remove it as well


Notes: to check these dependencies, checking the build logs of the released container image shows the output of the `jenkins-plugin-cli` step in the `Dockerfile` which describes dependency chains:

```
18:00:41  #10 2.999 Setting checksum for: github-autostatus to id2Tc+2qh9NfytsbwJMvfhb07XhdPsKOnTJimd/Nqnk=
18:00:41  #10 2.999 Setting checksum for: github-autostatus to id2Tc+2qh9NfytsbwJMvfhb07XhdPsKOnTJimd/Nqnk=
18:00:41  #10 3.000 
18:00:41  #10 3.000 github-autostatus depends on: 
18:00:41  #10 3.000 workflow-api 2.34
18:00:41  #10 3.000 cobertura 1.12.1
18:00:41  #10 3.000 github-branch-source 2.5.8
18:00:41  #10 3.000 jacoco 2.2.1
18:00:41  #10 3.000 pipeline-model-api 1.5.1
18:00:41  #10 3.000 pipeline-model-definition 1.5.1
18:00:41  #10 3.000 Skipping dependency workflow-api:2.34 and its sub-dependencies, because there is a higher version defined on the top level - workflow-api:1283.v99c10937efcb_
18:00:41  #10 3.001 Skipping dependency github-branch-source:2.5.8 and its sub-dependencies, because there is a higher version defined on the top level - github-branch-source:1767.va_7d01ea_c7256
18:00:41  #10 3.001 Skipping dependency jacoco:2.2.1 and its sub-dependencies, because there is a higher version defined on the top level - jacoco:3.3.5
18:00:41  #10 3.002 Skipping dependency pipeline-model-api:1.5.1 and its sub-dependencies, because there is a higher version defined on the top level - pipeline-model-api:2.2151.ve32c9d209a_3f
18:00:41  #10 3.002 Skipping dependency pipeline-model-definition:1.5.1 and its sub-dependencies, because there is a higher version defined on the top level - pipeline-model-definition:2.2151.ve32c9d209a_3f
```

**Comment by dduportal** [comment]
- Deployed to both controllers with success
- Checked (successfully) that cobertura, code-coverage-api and github-autostatus have been removed
- Discarded the old data
