### ISSUE TITLE
Add NotMyFault to 'jenkins-admins' group

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3881]
### Service(s)

LDAP

### Summary

Hey,

During preparation of GSoC 2024, students like to modernize abandoned plugins, e.g., from Java 8 to 11, 17 or 21, to get themselves familiar with the Jenkins plugin contributions.
When I'm reviewing these PRs, it's common that the build is failing because they involve required `Jenkinsfile` modifications, ci.j.io rejects from contributors without write access.
While this is a useful and obvious setting to us, it commonly causes frustration for the students because they like to see a green build, which doesn't really work toward a great first experience.

I'd like to request admin access to ci.jenkins.io through the `jenkins-admins` LDAP group in keycloak, to replay and trigger these PR builds on ci.jenkins.io (as I do already with PRs on infra.ci.), to facilitate a review and warrant a good first experience for the students.

Thanks in advance!

**Comment by MarkEWaite** [comment]
+1 from me.

**Comment by basil** [comment]
+1 from me

**Comment by dduportal** [comment]
Added @NotMyFault you have to logout-login on ci.jenkins.io to get permissions. Thanks!

**Comment by NotMyFault** [comment]
> Added @NotMyFault you have to logout-login on ci.jenkins.io to get permissions. Thanks!

Thanks!
