### ISSUE TITLE
Approve element.io GH integration app for RPU

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3882]
### Service(s)

GitHub

### Summary

Hey,

I've requested the installation of the element.io GH app on the RPU repository for the upcoming GSoC 2024 project. If I did everything correct, the app should be pending installation in https://github.com/organizations/jenkins-infra/settings/installations

Please approve :)

**Comment by dduportal** [comment]
LGTM

the requested permissions by the GH app are good:
- Only the RPU repository
- Read only of the code, and read write for PR/issues/actions

**Comment by dduportal** [comment]
Approved, should be good @NotMyFault

**Comment by NotMyFault** [comment]
> Approved, should be good @NotMyFault

Yup, looks good, thanks!

![Screenshot 2024-01-03 at 14 48 06](https://github.com/jenkins-infra/helpdesk/assets/13383509/a1965400-73a9-4a58-8054-3f5e691daeb7)
