### ISSUE TITLE
Delete empty GitHub repository https://github.com/jenkinsci/community-gsoc2016-info

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3886]
### GitHub repositories

https://github.com/jenkinsci/community-gsoc2016-info

### GitHub users to have permission

N/A

### Permission level

Read

### Justification

Repository is empty and we will not add any new content to GSoC 2016

**Comment by NotMyFault** [comment]
The repository has been deleted.
