### ISSUE TITLE
Split docker-jenkins-weekly and docker-jenkins-weekly.ci for infra.ci and weekly.ci

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3887]
### Service(s)

infra.ci.jenkins.io, weekly.ci.jenkins.io, Docker Hub

### Summary

As outlined in https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1459#pullrequestreview-1802728703, I'd like to split the docker images to create a minimalistic one for weekly.ci and leave infra.ci as-is.
Given both instances serve different needs, we don't need the majority of plugins on weekly.ci at all.

TODO:
- [ ] Create a GH repository in jenkins-infra: `docker-jenkins-weekly.ci` (unless someone has a better name in mind)
- [ ] Create a new docker repo with the same name in `jenkinsciinfra` on docker hub
- [ ] Update kubernetes-management accordingly

I can take care of 1) and 3) :)

**Comment by dduportal** [comment]
@NotMyFault I believe we should be able to use a bake file instead and keep only 1 repository?

**Comment by NotMyFault** [comment]
> @NotMyFault I believe we should be able to use a bake file instead and keep only 1 repository?

Right right, we actually just need a different set of plugins 🤔 
Everything else remains the same. Good catch!

**Comment by NotMyFault** [comment]
> @NotMyFault I believe we should be able to use a bake file instead and keep only 1 repository?

Right right, we actually just need a different set of plugins 🤔
Everything else remains the same. Good catch!

Do you think you could come up with a simple bake file? I'm not that well-versed with the hashicorp config lang 😓

**Comment by lemeurherve** [comment]
@NotMyFault I'll prepare the docker bake 🙂

**Comment by lemeurherve** [comment]
Instead of creating another docker image I plan to publish the weekly.ci.jenkins.io image variant as specific tag with a suffix like for example 1.23.1-2.439-**weeklyci**

(or 1.23.1-2.439-🦄 ?  :trollface:)

**Comment by lemeurherve** [comment]
Opened https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1462 cherry-picking https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1459 as a good candidate for differentiation between these variants.

Next steps:
- Updating kubernetes-management config and updatecli manifest

**Comment by lemeurherve** [comment]
weekly.ci.jenkins.io config has been updated to use its specific variant in https://github.com/jenkins-infra/kubernetes-management/pull/4850

Updatecli manifest update verified with https://github.com/jenkins-infra/kubernetes-management/pull/4849

Confirmed that Blue Ocean plugins and dependencies aren't available anymore on weekly.ci.jenkins.io:
<img width="675" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/b7fcfeb7-138e-44de-a87a-e6230111f0b1">

Closing this issue.

**Comment by lemeurherve** [comment]
Reopening as we need to get distinct lifecycle for these variants.

To do so, scripts and shared pipeline need to be updated to allow working on a specific target only (infra.ci.jenkins.io or weekly.ci.jenkins.io variant).

**Comment by lemeurherve** [comment]
Opened a pull request to build none, one or both variants depending on the modified files, and to create distinct plugins update pull requests: https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1471

**Comment by lemeurherve** [comment]
Result of the PR, from https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1471#issuecomment-1894268587:

> The merge of this PR on main has correctly triggered a build of both variants: https://infra.ci.jenkins.io/job/docker-jobs/job/docker-jenkins-weekly/job/main/365/
> 
> And the GHA has correctly opened two distinct pull requests:
> 
>     * [chore(deps): update infra.ci.jenkins.io plugins #1476](https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1476)
> 
>     * [chore(deps): update weekly.ci.jenkins.io plugins #1477](https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1477)
> 
> 
> Finally, these pull requests have themselves correctly triggered a build of only their corresponding variant.

Closing this issue as completed.

**Comment by lemeurherve** [comment]
Note that running the [`last-weekly` GHA](https://github.com/jenkins-infra/docker-jenkins-weekly/blob/main/.github/workflows/latest-weekly.yaml) results in a unique pull request containing the Jenkins version update and both plugins lists update, as both should be updated every time the Jenkins version changes.

**Comment by lemeurherve** [comment]
Reopening as I need to adapt kubernetes-management updatecli manifests to update only infra.ci.jenkins.io or weekly.ci.jenkins.io if only one of them has a new version.

**Comment by lemeurherve** [comment]
Update:
- Distinct updatecli manifests put in place in https://github.com/jenkins-infra/kubernetes-management/pull/4867
- Test publication of weekly.ci.jenkins.io image variant only: https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1490
- Result: https://github.com/jenkins-infra/kubernetes-management/pull/4892, only weekly.ci.jenkins.io updated, no PR for infra.ci.jenkins.io ✅ 

Closing this issue.
