### ISSUE TITLE
Blocked from creating a second account

### ISSUE THREAD

**Issue by MartinSchenkel** [jenkins-infra/helpdesk#3891]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I needed to create an account for work and accidentally created an account with my personal email rather than my work email. When I went ahead to create a second account using my work email I got blocked by the anti spam system.

I've linked the ticket I was interested in interacting with below.

### jenkins.io account username

RebellionMartin

### jenkins.io account email

martin.schenkel@rebellion.co.uk

### Which URL are you trying to login at?

https://issues.jenkins.io/browse/JENKINS-65418

**Comment by dduportal** [comment]
Hi @MartinSchenkel , there is no account associated to the username `RebellionMartin`. I undertand this is the second account you would want to create.

Can you re-try using a private browsing session, another webbrower or with a cleaned cache?

**Comment by MartinSchenkel** [comment]
Yup will do

**Comment by MartinSchenkel** [comment]
That worked, thanks :) The error message told me to open a ticket here.

**Comment by dduportal** [comment]
> That worked, thanks :) The error message told me to open a ticket here.

No problem, you did good!
