### ISSUE TITLE
Add jeromepochat to jenkinsci organization

### ISSUE THREAD

**Issue by jeromepochat** [jenkins-infra/helpdesk#3895]
### Service(s)

GitHub

### Summary

Hi!
I can login to Jira/Artifactory, my GH username is defined in [teams/cloudbees-developers.yml](https://github.com/jenkins-infra/repository-permissions-updater/blob/ee539470f04ba50aa183e046006f351f763b7b9e/teams/cloudbees-developers.yml#L10) but repository admin cannot invite me as team member (ie. https://github.com/jenkinsci/gcp-java-sdk-plugin).
![image](https://github.com/jenkins-infra/helpdesk/assets/814127/2f64f4b2-1831-4e08-bbde-526a18960003)

**Comment by jeromepochat** [comment]
Hi! It looks I'm still not member of `jenkinsci`. I guess I have to wait for sync correct?
![image](https://github.com/jenkins-infra/helpdesk/assets/814127/bd8bafe9-cefb-438f-b9ae-65a27e944c24)

**Comment by lemeurherve** [comment]
@jeromepochat did you accepted the invitation?

**Comment by jeromepochat** [comment]
Sorry, I didn't saw message on GH welcome page (no mail received). Now accepted, it looks fine. Thanks!
