### ISSUE TITLE
Remove unnecessary include patterns from `jcenter-orphans`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3896]
### Service(s)

Artifactory, Artifact-caching-proxy

### Summary

These are the include patterns currently contained in `jcenter-orphans`:

- `org/connectbot/jbcrypt/**/*`
- `com/atlassian/event/**/*`
- `com/atlassian/sal/**/*`
- `com/atlassian/platform/**/*`

I see a reason to retain `jbcrypt` in order to facilitate compilation of older versions of Jenkins core that predate https://github.com/jenkinsci/jenkins/pull/8811, as well as plugins that depend on those older versions of Jenkins core.

I do not see a raeson to retain any Atlassian closed-source binaries. We have suspended distribution of any plugins that ship these. The only thing these patterns are doing is masking potential problems.

Before we declare success in this project, I believe we should clear these include patterns and clear the artifact caching proxy one more time in order to expose any issues that may arise. It is better to deal with such issues, if they exist, at the present time rather than to maintain these include patterns for an extended period of time.

### Reproduction steps

None

**Comment by dduportal** [comment]
Thanks for the context @basil , it helps us to understand (and document) the use case for the infra team.

Updating the patterns right now!

**Comment by dduportal** [comment]
Update:

- Configuration of `jcenter-orphans` updated to only retain `org/connectbot/jbcrypt/**/*`
- ACP cache cleaned on Azure and Digital Ocean. AWS remains (to be done)

**Comment by dduportal** [comment]
Update:

- ACP cache fully cleaned (also on AWS)
- @MarkEWaite is currently checking builds on ci.jenkins.io to validate thew ACP behavior
- I'm testing a build of the `declarative-pipeline-migration-assistant-plugin` plugin, from scratch on a local ephemeral machine to check

**Comment by dduportal** [comment]
Looks like is good ob both environments.

@basil can you confirm your initial request is good?

**Comment by basil** [comment]
This looks great, thank you!

**Comment by basil** [comment]
(Once the remaining artifact caching proxy caches are cleared, that is.)

**Comment by basil** [comment]
> ACP cache fully cleaned (also on AWS)
