### ISSUE TITLE
Account deletion request

### ISSUE THREAD

**Issue by sblnt** [jenkins-infra/helpdesk#3897]
### Type(s) of account issue

I want my account to be deleted

### Summary

Hi jenkins team,
I'd like to request the deletion of my account.

### jenkins.io account username

sblnt

### jenkins.io account email

balintsomorjai0@gmail.com

### Which URL are you trying to login at?

accounts.jenkins.io

**Comment by MarkEWaite** [comment]
I've sent email to that address.  Once I've received a confirming response to that email message, I'll delete the account.
