### ISSUE TITLE
I have forgotten the jenkins credentials, please do assist to recover account

### ISSUE THREAD

**Issue by JyothiRdy** [jenkins-infra/helpdesk#3898]
### Type(s) of account issue

I didn't receive any email

### Summary

do assist o recover jenkins credentials.
I have uninstalled and installed it ,but when I open localhost:8080 its asking to login kindly help !

### jenkins.io account username

JyothiRdy

### jenkins.io account email

jyothit.sgp@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset
localhost:8080

**Comment by dduportal** [comment]
Hi @JyothiRdy , it looks like you're trying to work with your own Jenkins instance. Please reache the [community forums](https://community.jenkins.io) or use the [Jenkins documentation](https://jenkins.io).

This issue tracker is only for users of the `*.jenkins.io` websites, not for specific Jenkins instances.
