### ISSUE TITLE
Add maintainers to eiffel-broadcaster-plugin

### ISSUE THREAD

**Issue by magnusbaeck** [jenkins-infra/helpdesk#3899]
### GitHub repositories

https://github.com/jenkinsci/eiffel-broadcaster-plugin

### GitHub users to have permission

@GLundh
@TWestling

### Permission level

Maintain

### Justification

These users are de facto maintainers of the plugin together with me. @GLundh might already have maintainer permissions, I'm not sure.

I don't have access to the GitHub team that controls the GH permissions for this plugin, hence this issue.

**Comment by NotMyFault** [comment]
I've added the user to the team and sent you an invitation.
