### ISSUE TITLE
I seem to have lost my permissions on declarative-pipeline-migration-assistant-plugin

### ISSUE THREAD

**Issue by rsandell** [jenkins-infra/helpdesk#3900]
### GitHub repositories

https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin 

### GitHub users to have permission

@rsandell

### Permission level

Admin

### Justification

https://github.com/jenkins-infra/repository-permissions-updater/blob/4d57bb7abcb0ec49249bd3cf57e498b01471f092/permissions/plugin-declarative-pipeline-migration-assistant.yml#L12 say I should have, but I don't. I hape upload permissions but no permissions on the github repo.

**Comment by NotMyFault** [comment]
Added. The RPU manages artifactory permissions only.
