### ISSUE TITLE
ci.jenkins.io jobs on Windows agents are much slower than 21 days ago

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3904]
### Service(s)

ci.jenkins.io

### Summary

Jobs run on ci.jenkins.io Windows agents are significantly slower today than they were 21 days ago

### Reproduction steps

Compare job execution times for the Windows portions of several plugins that I maintain.  Dec 23 compared to today shows a large enough increase to cause most of the plugin BOM upgrade pull requests to those repositories to fail with a timeout error.  The jobs that failed with a timeout error include:

* https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/pull/197
* https://github.com/jenkinsci/authorize-project-plugin/pull/210
* https://github.com/jenkinsci/basic-branch-build-strategies-plugin/pull/61
* https://github.com/jenkinsci/elastic-axis-plugin/pull/343
* https://github.com/jenkinsci/git-client-plugin/pull/1093
* https://github.com/jenkinsci/git-plugin/pull/1547
* https://github.com/jenkinsci/git-plugin/pull/1546
* https://github.com/jenkinsci/gitlab-plugin/pull/1610
* https://github.com/jenkinsci/gitlab-plugin/pull/1611
* https://github.com/jenkinsci/implied-labels-plugin/pull/180
* https://github.com/jenkinsci/markdown-formatter-plugin/pull/130
* https://github.com/jenkinsci/nodelabelparameter-plugin/pull/289
* https://github.com/jenkinsci/platformlabeler-plugin/pull/1249
* https://github.com/jenkinsci/priority-sorter-plugin/pull/328
* https://github.com/jenkinsci/schedule-build-plugin/pull/295
* https://github.com/jenkinsci/testng-plugin-plugin/pull/270
* https://github.com/jenkinsci/versioncolumn-plugin/pull/212
* https://github.com/jenkinsci/xshell-plugin/pull/140

There were a few pull requests at that same time that passed, but their build was dramatically longer than the typical build for their repository.  The passing builds pull requests included:

* https://github.com/jenkinsci/elastic-axis-plugin/pull/342 - 31 minutes when Dec 23 and Dec 20 builds took less than 7 minutes
* https://github.com/jenkinsci/git-client-plugin/pull/1094 - 62 minutes when prior builds range from 21 minutes to 44 minutes

Usually the update of the plugin bill of materials in those plugins is simple and fast.  Current agents seem to be running much slower than agents were running previously.

**Comment by MarkEWaite** [comment]
Pagerduty is notifying me of performance issues that may be on the publick8s cluster.

**Comment by jonesbusy** [comment]
Same here. Most of my jobs are timeout after 1h

Example here : https://ci.jenkins.io/job/Plugins/job/hidden-parameter-plugin/job/PR-97/2/console

Takes 15mn to execute some very simple maven tasks

![Screenshot from 2024-01-14 10-04-16](https://github.com/jenkins-infra/helpdesk/assets/825750/10391a55-04b9-431c-9161-3b93fc74ac8a)

**Comment by MarkEWaite** [comment]
Another timeout failure at https://ci.jenkins.io/job/Core/job/jenkins-test-harness/job/PR-713/1/

**Comment by jonesbusy** [comment]
Here also: https://github.com/jenkinsci/coverage-model/pull/64

Was better some hours ago but timeout came back

**Comment by MarkEWaite** [comment]
> => Can you let us know if you see a difference in performances?

I've started the following jobs to compare performance:

* https://ci.jenkins.io/job/Plugins/job/apache-httpcomponents-client-4-api-plugin/job/master/buildTimeTrend
* https://ci.jenkins.io/job/Plugins/job/basic-branch-build-strategies-plugin/job/master/buildTimeTrend
* https://ci.jenkins.io/job/Plugins/job/platformlabeler-plugin/job/master/buildTimeTrend
* https://ci.jenkins.io/job/Plugins/job/pollscm-plugin/job/master/buildTimeTrend
* https://ci.jenkins.io/job/Plugins/job/xshell-plugin/job/master/buildTimeTrend

I'll check their status later today to confirm their execution time.
Each of them had at least one build during the last two weeks that took more than 50 minutes to complete.

**Comment by MarkEWaite** [comment]
As far as I can tell from my comparisons, this can be closed.  They are likely more things to improve, but the most crucial items that I was monitoring have all been resolved.

@jonesbusy are the results looking good enough for you that we can close this issue?

**Comment by jonesbusy** [comment]
Last timeout I saw was 3 days ago. I didn't saw any more more recently
