### ISSUE TITLE
For me Troubing in Plugins

### ISSUE THREAD

**Issue by Praveen-Carnage** [jenkins-infra/helpdesk#3905]
### Problem with this page

[Error | Jenkins](https://accounts.jenkins.io/doLogin) page

### Expected behavior

I need to reInstall  jenkins Fully so kindly delete my account

### Actual behavior

It is showing Some path error

**Comment by lemeurherve** [comment]
Hello @Praveen-Carnage, I transfered your issue from the account app repo to our help desk issues tracker.

You self-closed your issue, all good or do you need us to proceed to an account deletion procedure?
