### ISSUE TITLE
Crowdin for next-executions-plugin

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3907]
### GitHub repositories

next-executions-plugin

### Crowdin users to have project management permission

@jonesbusy

**Comment by NotMyFault** [comment]
Apologizes for the late response, your project ID is `30`.

![Screenshot 2024-01-20 at 01 58 54](https://github.com/jenkins-infra/helpdesk/assets/13383509/161c7382-9c4c-43a8-a7b8-0c27dff15b89)

I have received no team mention from this ping :(
