### ISSUE TITLE
Incorrect email while register

### ISSUE THREAD

**Issue by apadmostka** [jenkins-infra/helpdesk#3914]
### Type(s) of account issue

I want my account to be deleted

### Summary

I have created account with incorrect email

### jenkins.io account username

apadmostka

### jenkins.io account email

APadmostka@belhaize.be

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @apadmostka , in order to prove to us you're the rightful owner of this account, could you change the email to `helpdesk-3914@localhost.local` please?

Once done, we'll delete the account.

**Comment by apadmostka** [comment]
Hi @dduportal , I'm not sure how can I change the email, could you support?

**Comment by MarkEWaite** [comment]
Login to https://accounts.jenkins.io/myself/ with your jenkins.io credentials and change the email address in the account.

**Comment by apadmostka** [comment]
The problem is that I should get password on email but I've written incorrect email, so password hasn't come and I can't login

**Comment by dduportal** [comment]
> The problem is that I should get password on email but I've written incorrect email, so password hasn't come and I can't login

Oh I see. Let me fix the email then (between 2 Belgium frozen trains :) )

**Comment by dduportal** [comment]
@apadmostka email changed (based on the application logs which confirms the timestamps and email) and password reset triggered. Please check your mailbox

**Comment by dduportal** [comment]
No answer from requester. Closing.
