### ISSUE TITLE
Lost permission gitlab-branch-source-plugin

### ISSUE THREAD

**Issue by jetersen** [jenkins-infra/helpdesk#3915]
### GitHub repositories

https://github.com/jenkinsci/gitlab-branch-source-plugin

### GitHub users to have permission

@jetersen

### Permission level

Admin

### Justification

Not sure if it is repository permission updater issue or something else.
I am definitely in the file:
https://github.com/jenkins-infra/repository-permissions-updater/blob/70ab540ff1f83f005ee05ed19fe94fcb1f6cbfa5/permissions/plugin-gitlab-branch-source.yml#L15

**Comment by NotMyFault** [comment]
Someone set the team permissions to "Triage" causing a loss of write permissions to the repository:

![Screenshot 2024-01-18 at 16 09 19](https://github.com/jenkins-infra/helpdesk/assets/13383509/0c3e270b-d0ff-4a0e-afe3-8cd74ed8b83e)

I've restored the default permission scope.

**Comment by timja** [comment]
maybe it was that proposal on how to handle security releases?

(which causes this sort of thing -.-)

**Comment by dduportal** [comment]
Ping @daniel-beck @Wadeck does it ring a bell?

**Comment by NotMyFault** [comment]
> maybe it was that proposal on how to handle security releases?
> 
> (which causes this sort of thing -.-)

As maintainer listed in the RPU, jetersen should have been made aware of such a change through the security issue.

**Comment by jetersen** [comment]
Got a security advisory 25 minutes ago for the reason as to why I lost permission 😅

**Comment by NotMyFault** [comment]
> Got a security advisory 25 minutes ago for the reason as to why I lost permission 😅

In that case, you're back on Triage now :)

(Tho you wouldn't be the first one who locks yourself out my changing your team perms 😄)

**Comment by Wadeck** [comment]
Yes that's the expected behavior when we are "locking" a repository. 
See https://groups.google.com/g/jenkinsci-dev/c/8Ia0OBmzF1A/m/YBdi40u3BAAJ for more details
