### ISSUE TITLE
[get.jenkins.io/mirrors/mirrorbit - Azure] High costs due to usage of Azure File Storage

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#3917]
### Service(s)

get.jenkins.io, mirrors.jenkins.io, pkg.jenkins.io, Update center

### Summary

While checking the sources of costs in Azure for the year 2023, it appeared that the storage account `prodjenkinsreleases` (in the release group `prod-core-releases`) costs us around 20-25% of the monthly bills.

The amount is around 1800-2000$ monthly which is insane for a 1 Tb shared file storage.

<img width="1899" alt="Capture d’écran 2024-01-21 à 13 30 17" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/a0923690-2784-4603-9b7a-edf1208c28a2">

Most of the cost comes from "LRS Write Operation" meter (from 1000$ up to 1700$ in the past months), followed by "Read Operations" (~180-> 200$) and "Protocol Operation" (~170 -> 190$) [costs per month]. The storage in itself is really cheap: ~30$ monthly + 6$ "hot" (e.g. caching data often read in the filer).

This issue is to track the analysis and study to see if we can decrease this cost one way or another.

----

The usage of this storage is:

- get.jenkins.io (mirrors.jenkins.io):
  - Mirrorbits reads the volume content to check files considered as "references" to compare to mirrors when scanning. It primilarly scan the FS tree hierchically and the inodes metadatas (name, checksum, date, etc.) as regular intervals.
  - Apache (httpd) reads file when used as a fallback from the load balancer (e.g. either when serving [non-files resources such as directory listings](https://github.com/jenkins-infra/kubernetes-management/blob/eae93ac6072d7512fb0cdc361ff26eb14a4271ca/config/get-jenkins-io.yaml#L12-L13) or when accessed through [fallback.get.jenkins.io](https://github.com/jenkins-infra/kubernetes-management/blob/eae93ac6072d7512fb0cdc361ff26eb14a4271ca/config/get-jenkins-io.yaml#L31-L34)).
  - Both services are replicatd for high availability: [mirrorbits](https://github.com/jenkins-infra/kubernetes-management/blob/eae93ac6072d7512fb0cdc361ff26eb14a4271ca/config/get-jenkins-io.yaml#L68) and [httpd](https://github.com/jenkins-infra/kubernetes-management/blob/eae93ac6072d7512fb0cdc361ff26eb14a4271ca/config/get-jenkins-io.yaml#L91)). We have 2 replicas with a budget of "always 1 running" maintained by Kubernetes for rolling updates and maintenance.
  - Replication + services split between `httpd` requires concurrent accesses to the same file storage by the 4 processes. We used to have a [`ReadWriteMany`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) persistent volume to achieve this but we are going into a full `ReadOnlyMany` mode soon as no write is needed.
    - Azure File Storage is the only CSI volume type supporting one or the other (e.g. mounting the same volume on different nodes).

- trusted.ci.jenkins.io:
  - Every 3 minutes, the jenkins-infra./update_center2 project is run an ends in [executing (remotely on the pkg/updates.jenkins.io VM)](https://github.com/jenkins-infra/update-center2/blob/9c74a0dfcf8afc958030f7a123aea356b65c906e/site/publish.sh#L20) the script [`sync-recent-releases.sh`](https://github.com/jenkins-infra/mirror-scripts/blob/bebd7675616a2073173b241ddf5021d098c5f2b4/sync-recent-releases.sh#L32) which copies recently released plugins to the storage (with `blobxfer` or [eventually, soon, `azcopy`](https://github.com/jenkins-infra/helpdesk/issues/3414))
- release.ci.jenkins.io:
  - During Core releases (weekly every Tuesday and LTS + Security), the publication process [executes (remotely on the pkg/updates.jenkins.io VM)](https://github.com/jenkins-infra/release/blob/02b78eb2c598677e8afffbc32d31bcf017e9aef0/utils/release.bash#L481) the script [`sync.sh`](https://github.com/jenkins-infra/mirror-scripts/blob/bebd7675616a2073173b241ddf5021d098c5f2b4/sync.sh#L75-L76) which copies recently released binaries (plugins, core packages) and indexes to the storage (with `blobxfer` or [eventually, soon, `azcopy`](https://github.com/jenkins-infra/helpdesk/issues/3414))

=> Both trusted.ci and release.ci usages are reponsible for writing data. They can by using commands remotely on pkg.jenkins.io (AWS VM) which is allowed to access the storage through the Azure storage API. This pattern (writing avery 3 minutes) is clearly the culprit for the cost here.
=> 

----

Storage consideration (usage/price):

- This storage is bound to always grow: we do not garbage collect data as we want to keep it forever.
  - This policy could be revised as we have archives.jenkins.io.
- Current usage today is:
  - Storage uses around 520 Gb.
  - Current maximum IOPS are 1000/s
  - Current maximum bandwitdh is 60 Mbits/s for ingress, same for egress

**Comment by dduportal** [comment]
Proposal:

Since the original implementation of get.jenkins.io with mirrorbits, many things changed:

- The amount of replicas for get.jenkins.io have been decreased to `2` which means only 2 "visions" of the persistent storage are needed
- As we recently worked on parallelization of remote copy operations on the update center, the overhead time to copy on 2 copies to a block storage are now acceptable
- The flow of copies (azure -> AWS -> azure) changed quite often in 2020/2021 but were not revisited since then

We could try switching to using 2 PVCs of type block storage instead of the current Azure File Storage:

- We would need to implement a set of "write to disk" services to provide entrypoint to write to the disks
  - Luckily, the [recent work of @hervelemeur](https://github.com/jenkins-infra/helpdesk/issues/2649) added `rsyncd` as either [included in the mirrorbits-parent chart](https://github.com/jenkins-infra/kubernetes-management/blob/eae93ac6072d7512fb0cdc361ff26eb14a4271ca/config/updates.jenkins.io.yaml#L75) or as a [distinct chart]https://github.com/jenkins-infra/helm-charts/tree/main/charts/rsyncd) with a [`ReadWriteOnce`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) policy
  - We would need to replace `blobxfer` calls by `rsync` calls:
    - Use SSH key based authentication so it would be easier to run `rsync` from pkg/update VM (and eventually release.ci pipeline for core release)  
    - Parallelize the copy of the 2 `rsyncd` copies on each script (to avoid reaching the 3 min limit on update center)
    - Restrict IPs at LB level to increase security

- Scheduling constraint: due to the `ReadWriteOnce` policy, for each get.jenkins.io replica (e.g. a set of 1 `mirrorbits` pod, 1 `httpd` pod and 1 `rsyncd` pod) would be schedule on the same machine
  - Not an HA problem: we can keep 2 distinct machines, each one for 1 "replica" with its own PVC
  - However, we would need to roll back `httpd` and `rsync` to using x86_64 nodes instead of `arm64` nodes, at least until `mirrorbits` is amr64 compliant. Not a billing problem if we "pack" properly

- Pricing changes:
  - As per https://azure.microsoft.com/en-us/pricing/details/managed-disks/, a Premium SSD of 1 Tb (512 Gb is the smaller option available below 1 Tb) is $184.32 monthly with 5000 IOPS (burstable) and 200 MB/s. There could be []"outbound bandwidth" billed per Gb](https://azure.microsoft.com/en-us/pricing/details/bandwidth/) but only if we read the disk from another availability zone: if we use LRS we are fine.
  - That means we could expected a static billing of ~400$ monthly (usage and error margin included) instead of ~1800 / 2000 today ! Even including the engineering effort it is clearly worthwhile.

Besides switching to a block storage-based persistent volume would:

- Fix https://github.com/jenkins-infra/helpdesk/issues/3525 (slow directory listing by Apache).
- Drastically reduce the scope of https://github.com/jenkins-infra/helpdesk/issues/3414

**Comment by dduportal** [comment]
Alternative Proposal:

- As per https://azure.microsoft.com/en-us/pricing/details/storage/files/, switching to a "Premium Storage" would remove the operation costs (marked as "included"):

> Premium file shares use a provisioned billing model, where you pay for the amount of storage you would like your file share to have, regardless of how much you use


This solution could be better than my disk proposal (less engineering effort) as the volume billing would be:

- 164$ monthly (0,16*1024 for premium)
- Snapshot costs would drastically increase though: (0,136$ / Gb instead of 0,06$ / Gb Today). As we already copy data in pkg VM and archives (2 other different locations), this is acceptable.

=> It would also allows us to use [NFS file share](https://learn.microsoft.com/en-us/azure/storage/files/files-nfs-protocol) for our volumes which could greatly improve https://github.com/jenkins-infra/helpdesk/issues/3525


Gotta check if the conversion from the existing volume is possible and under which constraints

**Comment by dduportal** [comment]
Update: PR opened to create new storage (premium): https://github.com/jenkins-infra/azure/pull/598

**Comment by smerle33** [comment]
as per https://azure.microsoft.com/en-us/pricing/details/storage/files/

the ZRS Redundancy is a good choice, the price is a little higher than LRS but still cheap (in Premium version) as we consume only 600Go:
 
LRS:
<img width="1364" alt="Capture d’écran 2024-01-24 à 16 16 40" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/6d7e8999-20b4-4f36-8cf4-47cb3b49fbd5">

ZRS:
<img width="1385" alt="Capture d’écran 2024-01-24 à 16 16 47" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/9ee25f2a-b074-46f4-bb47-00a6fabe2f39">

And the write are included as premium: 
<img width="1375" alt="Capture d’écran 2024-01-24 à 16 17 06" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/2500eced-2dc6-4e19-bd35-8ce6393a4dfb">

**Comment by dduportal** [comment]
Update:

- The new (premium) SA and its (700 Gb) file storage has been created with success
  - https://github.com/jenkins-infra/azure/pull/598
  - https://github.com/jenkins-infra/azure/pull/607

Next step:

- Start copying the data between the 2 storage accounts (should take the night)
- Test a new PVC pointing to this storage with NFS in `publick8s` with `ReadOnlyMany` 
- Test access from `pkg.origin.jenkins.io`

**Comment by dduportal** [comment]
Update:

- Data is being copied: 
  - Executed in a screen named `helpdesk-3917` in pkg.origin.jenkins.io's VM. 
  - `azcopy` existed in `/bin/azcopy` and was upgraded to latest 10.x version.
  - Generated an SAS (with only file and read/list permissions) on `prodjenkinsreleases`  valid only 5 days.
  - Command is `azcopy copy 'https://prodjenkinsreleases.file.core.windows.net/mirrorbits?sv=2022-11-02&<redacted>' 'https://getjenkinsio.file.core.windows.net/mirrorbits?sv=2022-11-02&<redacted>' --preserve-smb-permissions=true --preserve-smb-info=true --recursive`

**Comment by dduportal** [comment]
Update:

- Starting the "parallel" update of both storages to keep the sync:
  - Added the new credentials in `pkg.origin.jenkins.io:/home/mirrorbrain/.azure-storage-env`
  - Tested the `bloxfer` access from `pkg.origin.jenkins.io` ✅ 
  - Updated the "mirror-scripts": https://github.com/jenkins-infra/mirror-scripts/commit/13e8842f42e9a84d4fe64ca78a89038602845419 to copy on both storages (and also a bit of shellcheck and https://github.com/jenkins-infra/helpdesk/issues/2671#issuecomment-1911624457)
  - Currently watching the `/srv/release/last_sync.log`

**Comment by dduportal** [comment]
WiP (`Test a new PVC pointing to this storage with NFS in publick8s`):

- Helm charts:
  - https://github.com/jenkins-infra/helm-charts/pull/1037 to ensure a read-only mount of the data storage in `mirrorbits` pods
  - Then https://github.com/jenkins-infra/helm-charts/pull/1039
  - And https://github.com/jenkins-infra/helpdesk/issues/3917 which is blocked as we need to validate all of this!
- Kubernetes management:
  - WiP on creating a "manual" installation of mirrorbits to verify everything works. A draft PR in jenkins-infra/kubernetes-management is expected but it will never be merged! using the new chart (with read only). Main points:
    - Use another Redis base (but same server) to avoid any impact on get.jenkins.io
    - Use the new (premium) storage
    - Use NFS(v4) instead of CIFS for the PVC
    - Use read-only mounts
  - ToDo: once the installation (draft PR + manual installation + manual cleanup) is considered ready, then a PR to migrate get-jenkins-io is expected, with announcement

**Comment by dduportal** [comment]
Update: Operation on `get.jenkins.io` finished with success:

- https://github.com/jenkins-infra/kubernetes-management/pull/4911 applied locally and then merged
  - Secrets updated: https://github.com/jenkins-infra/charts-secrets/commit/7caaea2736c26229f85bc8e42fd5b8bb477a3248
  - Had to delete the whole `get-jenkins-io` namespace as the PV is immutable
- Logs of `get.jenkins.io` are 👍 
- Health Check: https://get.jenkins.io/windows-stable/2.426.3/jenkins.msi?mirrorlist is 👍 
- Last build of jenkins-infra/kubernetes-management ran with success (build 29684) 👍 
- Ran ci.jenkins.io plugins update + a local build of jenkins-infra/docker-jenkins-weekly images to ensure plugins download are 👍 


Next steps:

- Close operation (and communication)
- Remove access to `prodjenkinsreleases` from PKG
- Cleanup `prod-core-releases` resource group
- profit

**Comment by dduportal** [comment]
Proceeding to deletion of `prod-core-releases` resource group which only has the storage account `prodjenkinsreleases` with 2 file shares: `mirrorbits` (replaced by `getjenkinsio`'s `mirrorbits` file share) and an unused `website` file share:

<img width="1918" alt="Capture d’écran 2024-01-26 à 13 52 04" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/d830e0d0-8ea8-4e82-b3d7-ae5c5b15168d">


=> This storage account has not used since the past 15 min and no error are seen on update center, trusted or PKG VM.

<img width="1587" alt="Capture d’écran 2024-01-26 à 13 51 23" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/c1db099f-c3d9-48c8-8335-41e7db29ac8b">

<img width="1586" alt="Capture d’écran 2024-01-26 à 13 51 36" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/3ca4504b-5e03-49ab-8b6b-fea712d3c51c">

**Comment by smerle33** [comment]
usage of the new premium storage class

<img width="1886" alt="Capture d’écran 2024-01-26 à 14 31 16" src="https://github.com/jenkins-infra/helpdesk/assets/95630726/4d869730-d295-4247-9a24-8040ceb3ca29">

**Comment by dduportal** [comment]
<img width="1897" alt="Capture d’écran 2024-01-29 à 08 35 16" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/42ab928e-fc66-40f4-9062-462e69c080d3">


=> Looks like the outcome is really good: the daily rate in the range "70 to 110" $ daily is now ~5 $ daily for get.jenkins.io!


Closing the issue as complete, but there should be 1 new issue to automatically track the storage size from jenkins-infra/azure to the Kubernetes PVC size + 1 comment to have updates.jenkins.io changed with the same pattern (premium storage).

**Comment by dduportal** [comment]
See https://github.com/jenkins-infra/helpdesk/issues/3913#issuecomment-1914132386 for overall costs

**Comment by lemeurherve** [comment]
> Proceeding to deletion of `prod-core-releases` resource group which only has the storage account `prodjenkinsreleases` with 2 file shares: `mirrorbits` (replaced by `getjenkinsio`'s `mirrorbits` file share) and an unused `website` file share:

Likely the cause of https://github.com/jenkins-infra/helpdesk/issues/3927
