### ISSUE TITLE
When creating an account i mismatch email

### ISSUE THREAD

**Issue by vitalii-kondratiuk** [jenkins-infra/helpdesk#3920]
### Type(s) of account issue

I didn't receive any email

### Summary

When creating an account with username vitalii_kondratiuk I mentioned the wrong email so i can't receive a confirmation latter with a password.
COrrect email should be: vitalii.kondratiuk@ui.com

### jenkins.io account username

vitalii_kondratiuk

### jenkins.io account email

vitalii.kondratiuk@ui.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @vitalii-kondratiuk , there are no account named `vitalii_kondratiuk`.

You should be able to create it then

**Comment by vitalii-kondratiuk** [comment]
I'm getting anti-spam message when trying to register account that my request isn't legitimate
![image](https://github.com/jenkins-infra/helpdesk/assets/56025590/dfb6303a-a04e-432c-bbee-fda8d05c41cb)

**Comment by dduportal** [comment]
> I'm getting anti-spam message when trying to register account that my request isn't legitimate ![image](https://private-user-images.githubusercontent.com/56025590/299764561-dfb6303a-a04e-432c-bbee-fda8d05c41cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDc2OTIsIm5iZiI6MTcwNjIwNzM5MiwicGF0aCI6Ii81NjAyNTU5MC8yOTk3NjQ1NjEtZGZiNjMwM2EtYTA0ZS00MzJjLWJiZWUtZmRhOGQwNWM0MWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE4Mjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZGJiMmJhYjhmOTBjYjU3YWEyYTkyMjQwYjdkZDMyZjIyOTdiODY4NmY3OTFhZWU1Y2U4ZTU0YTFlMzAzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuIRqKFgN3P4VLtwL3fO5GhpkznvWIM9a6UJKSazVlc)

In that case, could you retry with a private browsing session (or another webbrowser)? The error I see in our logs shows that you have conflicting Cookies in your session

**Comment by dduportal** [comment]
Closing as solution is provided an no answer from requester on the last comment.
