### ISSUE TITLE
Issue with docker 25 on some nodes

### ISSUE THREAD

**Issue by Vlatombe** [jenkins-infra/helpdesk#3922]
### Service(s)

ci.jenkins.io

### Summary

Apparently there is a problem with docker 25 (cf. https://github.com/jenkinsci/kubernetes-plugin/pull/1506#issuecomment-1910312438), we need nodes to be updated to 25.0.1

Causes failures in kubernetes-plugin builds, e.g. https://ci.jenkins.io/job/Plugins/job/kubernetes-plugin/job/PR-1506/1/pipeline-console/?selected-node=19

**Comment by jglick** [comment]
For context: https://github.com/moby/moby/issues/47150, breaking CI builds using `kind load docker-image`: https://github.com/kubernetes-sigs/kind/issues/3479#issuecomment-1904717676

**Comment by lemeurherve** [comment]
Update to Docker CE 25.0.1 merged in https://github.com/jenkins-infra/packer-images/pull/1019

Expect a good one to two hours between this packer image publication and its deployment.

**Comment by lemeurherve** [comment]
Triggered a new build, the `kind` error is gone: https://ci.jenkins.io/job/Plugins/job/kubernetes-plugin/job/PR-1506/2/

Thanks @Vlatombe & @jglick for the issue and links!
