### ISSUE TITLE
Unable to create Jenkins Jira account

### ISSUE THREAD

**Issue by MihaiPostolache85** [jenkins-infra/helpdesk#3926]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I need to create an account to be able to add more information to an already created issue because we're encountering the same problem when upgrading the plugins but with a different effect . https://issues.jenkins.io/browse/JENKINS-72420

### jenkins.io account username

mihai_postolache1

### jenkins.io account email

mihai.postolache.ext@porscheinformatik.com

### Which URL are you trying to login at?

[account.jenkins.io/antispam](https://issues.jenkins.io/browse/JENKINS-72420)

**Comment by MihaiPostolache85** [comment]
any news?

**Comment by MarkEWaite** [comment]
Try to create the account from an incognito browser session or from a different computer.

**Comment by dduportal** [comment]
Closing as no answer from the requester. Feel free to reopen with more details if you have retried unsuccessfully.
