### ISSUE TITLE
dident remember password

### ISSUE THREAD

**Issue by PriyankaKadam11** [jenkins-infra/helpdesk#3928]
### Type(s) of account issue

I've lost my password

### jenkins.io account username

Priyanka_Kadam

### jenkins.io account email

priyamagr3731@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
@PriyankaKadam11 there is no account on jenkins.io for the user name.  You'll need to check with the administrators of your local Jenkins controller for help to reset the password.
