### ISSUE TITLE
can't log in

### ISSUE THREAD

**Issue by ElviraGabitova** [jenkins-infra/helpdesk#3929]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account username

ellgab

### jenkins.io account email

forelle_g@mail.ru

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
There is no account ellgab on accounts.jenkins.io .  You'll need to contact the administrator of the Jenkins controller that you are trying to use.  The accounts.jenkins.io system only manages accounts for the Jenkins project.
