### ISSUE TITLE
Windows agents much slower to build plugins than before

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3931]
### Service(s)

ci.jenkins.io

### Summary

The Windows agents attached to ci.jenkins.io are failing builds due to timeout

### Reproduction steps

1. https://github.com/jenkinsci/build-timestamp-plugin/pull/56/checks?check_run_id=21117165797 shows a plugin build that failed after 60 minutes running the Jenkins Windows agent

**Comment by jglick** [comment]
This is interfering with my development in https://github.com/jenkinsci/script-security-plugin/pull/555 & https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/355: I need incremental deployments to run downstream tests. Not sure what is wrong, but I would rather have Windows branches simply be skipped (at least in PR builds) than take this long.

**Comment by MarkEWaite** [comment]
> This is interfering with my development in [jenkinsci/script-security-plugin#555](https://github.com/jenkinsci/script-security-plugin/pull/555) & [jenkinsci/workflow-durable-task-step-plugin#355](https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/355): I need incremental deployments to run downstream tests. Not sure what is wrong, but I would rather have Windows branches simply be skipped (at least in PR builds) than take this long.

Can't you adjust the Jenkinsfile temporarily to skip Windows builds?

**Comment by jglick** [comment]
Yes, it is possible, just awkward since then the change needs to reverted before merging the PR, or the `Jenkinsfile` made to switch behavior according to `CHANGE_ID`.

**Comment by MarkEWaite** [comment]
As far as I can tell, this is resolved now.  I ran builds for several different plugins within the last 4 hours and consistently passed on Windows and Linux.  The build times for the jobs that I compared were within reasonable distance of each other.
