### ISSUE TITLE
update updatecli manifest on sharedtools to add a condition for golang with packer-images versions match 

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#3937]
### Service(s)

Other

### Summary

in order to avoid failure we need to make sure that the agent used from packer-images got the same golang version than the one used in the shared-tools. https://github.com/jenkins-infra/shared-tools/pull/141#issuecomment-1931617320

source to check for condition 
https://github.com/jenkins-infra/packer-images/blob/13ce558c42edb234605aa123654588cea3bc4e67/provisioning/tools-versions.yml#L16

here https://github.com/jenkins-infra/shared-tools/blob/c4e77302e8d780953341f6333bec4aa9e68eb528/updatecli/updatecli.d/golang.yml#L28

**Comment by lemeurherve** [comment]
https://github.com/jenkins-infra/shared-tools/pull/144 LGTM, closing.
