### ISSUE TITLE
Jenkins controllers logs aren't collected by Datadog

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3943]
### Service(s)

Datadog

### Summary

While looking at Datadog logs for #3934 we noticed that we aren't collecting the controller logs with a Datadog agent from the docker container of ci.jenkins.io, neither does the Jenkins Datadog plugin installed on ci.jenkins.io

**Comment by dduportal** [comment]
Only `ci.jenkins.io` is in the scope (double checked and we have logs for other VM-based controlelrs) \o/

Opened https://github.com/jenkins-infra/jenkins-infra/pull/3288

**Comment by dduportal** [comment]
We can close: controller logs are now streamed in datadog!

<img width="952" alt="Capture d’écran 2024-02-08 à 16 37 11" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/56604383-9d1d-4d8f-98d2-1486c81fae37">
