### ISSUE TITLE
Add `deprecated` topic to job-fan-in-plugin GitHub repository

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3945]
### Service(s)

GitHub

### Summary

The [job fan-in plugin](https://github.com/jenkinsci/job-fan-in-plugin?tab=readme-ov-file#depricated) has been deprecated by its maintainer but is not shown as deprecated

### Reproduction steps

1. Open https://github.com/jenkinsci/job-fan-in-plugin?tab=readme-ov-file#depricated and confirm that the plugin is deprecated and the repository is archived
2. Open https://plugins.jenkins.io/job-fan-in/ and see that the plugin is not marked as deprecated

**Comment by NotMyFault** [comment]
I applied the label, thanks!
