### ISSUE TITLE
vasu

### ISSUE THREAD

**Issue by vasu0000** [jenkins-infra/helpdesk#3947]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

vasu.raju859@gmail.com

### jenkins.io account username

vasu

### jenkins.io account email

vasu.raju859@gmail.com

### Which URL are you trying to login at?

https://ci.cs.manchester.ac.uk/jenkins/login?from=%2Fjenkins%2F

**Comment by lemeurherve** [comment]
Hello @vasu0000, you're trying to connect to a Jenkins instance from the Manchester University which we're not in charge of.

This help desk is dedicated to Jenkins infrastructure, you should contact Manchester University IT department to resolve your issue.
