### ISSUE TITLE
WARNING c.c.s.QuickDiskUsagePlugin$2#run: Unable to run disk usage check

### ISSUE THREAD

**Issue by felipenferri** [jenkins-infra/helpdesk#3949]
### Service(s)

plugins.jenkins.io

### Summary

java.io.IOException: Failed to set the timestamp of /var/jenkins_home to 1707751667468
	at hudson.FilePath$Touch.invoke(FilePath.java:1840)
	at hudson.FilePath$Touch.invoke(FilePath.java:1825)
	at hudson.FilePath.act(FilePath.java:1236)
	at hudson.FilePath.act(FilePath.java:1219)

### Reproduction steps

Even enabling disk usage from environment variable and working as expected we continue to see this error in logs.

**Comment by lemeurherve** [comment]
Might be related to #3934

**Comment by felipenferri** [comment]
I see in my own jenkins instance

**Comment by lemeurherve** [comment]
OK, then I'm redirecting you to https://www.jenkins.io/participate/help/ and closing this help desk issue as it's unrelated to Jenkins infrastructure.

**Comment by antoniogarcia-bc** [comment]
We see the same issue on our own Jenkins instance.  Was there ever any solution/workaround for this? @lemeurherve

**Comment by MarkEWaite** [comment]
> OK, then I'm redirecting you to https://www.jenkins.io/participate/help/ and closing this help desk issue as it's unrelated to Jenkins infrastructure.

As noted earlier, you should ask in one of the locations suggested on https://www.jenkins.io/participate/help/ .

Jenkins community or Jenkins user mailing list or Jenkins chat channels.
