### ISSUE TITLE
Minimum Jenkins version required to support Mac ARM64 architecture

### ISSUE THREAD

**Issue by zaman-akib** [jenkins-infra/helpdesk#3952]
### Service(s)

Helpdesk

### Summary

When I installed Jenkins version **2.401.3** on Mac M1 device (AMR64 architecture), it is showing as **_x86_64_** in the node list but when I installed Jenkins version **2.426.3** it is showing correctly as **_arm64_** node.

So I need to know from which Jenkins version Mac ARM support is available? I couldn't find any official documentation about this.

**Comment by dduportal** [comment]
Hi @zaman-akib , this issue tracker is only aimed at the `*.jenkins.io` websites and their infrastructure. You should raise your question in community.jenkins.io to get help from the community.

**Comment by zaman-akib** [comment]
Raised a question here - https://community.jenkins.io/t/minimum-jenkins-version-required-to-support-mac-arm64-architecture/12493

If anyone is facing similar issue, check on the community question from the above mentioned link.
