### ISSUE TITLE
unbale to install the jenkins plugin name Role-based Authorization StrategyVersion 689.v731678c3e0eb_

### ISSUE THREAD

**Issue by CSPPravin** [jenkins-infra/helpdesk#3953]
### Service(s)

jenkins.io

### Summary

Role-based Authorization StrategyVersion
689.v731678c3e0eb_ not install

```[tasklist]
### Tasks
```

**Comment by MarkEWaite** [comment]
Not likely related to Jenkins infra

**Comment by MarkEWaite** [comment]
Without steps to duplicate the issue, we will close Ross

**Comment by CSPPravin** [comment]
how can we handel it

**Comment by MarkEWaite** [comment]
You have not given enough description for anyone to decide if the issue is specific to your environment or a general issue. When you do not provide enough information, you reduce the chance that others will help you. 

In this case, it is most likely a local issue that the infra fan cannot help

**Comment by dduportal** [comment]
Closing as it is unrelated to the Jenkins infrastructure. If you need help do not hesitate to reach community.jenkins.io to have the whole community to help!
