### ISSUE TITLE
unable to login to page with the credentials used to create

### ISSUE THREAD

**Issue by motherT** [jenkins-infra/helpdesk#3960]
### Problem with this page

https://accounts.jenkins.io/login

### Expected behavior

i should be able to login with the correct credentials

### Actual behavior

username not recognized pops up

### Possible solution

provide options to reset both the username and the password. there is only one option to reset password. This is too time consuming and disturbing.

**Comment by lemeurherve** [comment]
Hello @motherT, you can create a new Jenkins account to get a new username.

**Comment by lemeurherve** [comment]
@motherT have you managed to access or create an account?

**Comment by dduportal** [comment]
Closing as no answer and no details from requester

**Comment by motherT** [comment]
should i create a new  account? how will i close the existing one?

**Comment by lemeurherve** [comment]
Have you tried https://accounts.jenkins.io/passwordReset?

**Comment by dduportal** [comment]
@motherT can you confirm that the username if for a `jenkins.io` website, or is it for your Jenkins instance?

**Comment by dduportal** [comment]
@motherT additionnaly, can you provide which username and/or email you are trying to use so we can search our logs
