### ISSUE TITLE
Release of `jenkinsci/build-monitor-plugin` failing with 401 Unauthorized

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3962]
### Service(s)

Artifactory, GitHub

### Summary

Release of `jenkinsci/build-monitor-plugin` failed with:

> [ERROR] Failed to execute goal `org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy` (`default-deploy`) on project `build-monitor`: Failed to deploy artifacts: Could not transfer artifact `org.jenkins-ci.plugins:build-monitor:pom:1.14-860.vd06ef2568b_3f` from/to `maven.jenkins-ci.org` (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/build-monitor/1.14-860.vd06ef2568b_3f/build-monitor-1.14-860.vd06ef2568b_3f.pom, status: 401 Unauthorized -> [Help 1]

I read [the documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#the-upload-to-the-maven-repository-fails-with-401-unauthorized):

> Unauthorized means that the credentials were invalid, or not sent by Maven. This normally means that the secrets configured in the repository have expired, create an issue in the INFRA helpdesk on [GitHub](https://github.com/jenkins-infra/helpdesk/issues/new/choose) […].

Per the documentation, I am creating an infrastructure ticket to update the expired credentials.

### Reproduction steps

Obtain write access to `jenkinsci/build-monitor-plugin`, then go to https://github.com/jenkinsci/build-monitor-plugin/actions/workflows/cd.yaml and click the "Run workflow" button.

**Comment by lemeurherve** [comment]
Ping @jenkins-infra/jenkinsci-admins as I don't have any permission on this repo, could one of you take a look when you have time please?

**Comment by NotMyFault** [comment]
> Ping jenkins-infra/jenkinsci-admins as I don't have any permission on this repo, could one of you take a look when you have time please?

I've kicked off a new build of the rpu on trusted.ci to refresh the tokens and locked https://trusted.ci.jenkins.io:1443/job/repository-permissions-updater/36439/ if you want to take a look at the failure.

Tokens have been refreshed by now:
![Screenshot 2024-02-27 at 22 10 26](https://github.com/jenkins-infra/helpdesk/assets/13383509/d1dd0dba-761a-4ffe-a766-2a22e440b677)

**Comment by lemeurherve** [comment]
Release succeeded & RPU build unlocked, thanks @NotMyFault!

**Comment by lemeurherve** [comment]
I didn't realise running RPU would refresh tokens, good to know.

**Comment by basil** [comment]
Thank you very much!
