### ISSUE TITLE
Can not login success

### ISSUE THREAD

**Issue by lucyWW2603** [jenkins-infra/helpdesk#3963]
### Type(s) of account issue

I didn't receive any email

### Summary

When click forgot password, i didn't receive email

### jenkins.io account email

ha.vu@wisewires.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by lemeurherve** [comment]
Hello @lucyWW2603 sorry for the delay, there is no Jenkins account registered with this email or "lucyWW2603" username on accounts.jenkins.io

Closing this issue, feel free to create an account at https://accounts.jenkins.io/signup if you need a Jenkins account.
