### ISSUE TITLE
I forgotten my user name and password what can I do

### ISSUE THREAD

**Issue by subahan123938** [jenkins-infra/helpdesk#3964]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

I forgotten my Jenkins user name and password what can I do

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Ask your Jenkins administrator for help.  This help desk is for the infrastructure that supports Jenkins development and delivery.
