### ISSUE TITLE
github CD process fails with 401 Unauthorized when deploying to https://repo.jenkins-ci.org/releases

### ISSUE THREAD

**Issue by mawinter69** [jenkins-infra/helpdesk#3966]
### Service(s)

GitHub

### Summary

I'm trying to release a new version of roles-strategy via the github action based CD.
But the action fails to deploy the artifacts:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy (default-deploy) on project role-strategy: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:role-strategy:pom:711.vf33a_d2c994b_a_ from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/role-strategy/711.vf33a_d2c994b_a_/role-strategy-711.vf33a_d2c994b_a_.pom, status: 401 Unauthorized
```
https://github.com/jenkinsci/role-strategy-plugin/actions/runs/8100699901

I can see in settings -> Secrets and Variables -> Action  that MAVEN_USERNAME and MAVEN_TOKEN have been updated a few hours ago.

**Comment by lemeurherve** [comment]
The last repository permission updater job build failed but a new one is in progress, I'll check back when it's finished.

**Comment by lemeurherve** [comment]
@mawinter69 I see that you triggered a new cd action, perfect, I was about to ask you just that as the RPU job finished with success this time.

**Comment by lemeurherve** [comment]
cd action https://github.com/jenkinsci/role-strategy-plugin/actions/runs/8101450095/job/22141659284 succeeded, closing this issue.

**Comment by basil** [comment]
Thank you, @lemeurherve!
