### ISSUE TITLE
Archive EOL l10n-server repository

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3970]
### Service(s)

GitHub

### Summary

As declared in in the commit ~7 years ago, https://github.com/jenkins-infra/l10n-server/ is dead and the repository can be archive.d

**Comment by dduportal** [comment]
- Closed PRs
- Cleaned up branches
- Archived the repository

**Comment by lemeurherve** [comment]
Related job on ci.jenkins.io: https://ci.jenkins.io/job/Infra/job/l10n-server/

Related help desk issue to remove the plugin that used these translations IIUC:
- https://github.com/jenkins-infra/helpdesk/issues/3612

**Comment by lemeurherve** [comment]
Job removed from ci.jenkins.io
