### ISSUE TITLE
Remove Jira component `lib-support-log-formatter`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3971]
### Service(s)

Jira

### Summary

It has apparently [never been used](https://issues.jenkins.io/issues/?jql=component%3Dlib-support-log-formatter), and I would like to use [GH Issues](https://github.com/jenkinsci/lib-support-log-formatter/issues) instead.

**Comment by basil** [comment]
> I would like

https://github.com/jenkinsci/lib-support-log-formatter/issues has apparently never been used prior to today, and I would like to use Jira instead.

**Comment by dduportal** [comment]
Hi folks, how should we handle the disagreement here?

**Comment by jglick** [comment]
I guess we leave them both.
