### ISSUE TITLE
Evaluate cleanowners for `CODEOWNERS` files

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3974]
We have a lot of different (mostly plugin) repos in @jenkinsci with a rotating cast of maintainers. Could the tool mentioned in https://github.blog/2024-03-04-keeping-repository-maintainer-information-accurate/ be helpful in keeping these up to date? Find a pilot project to evaluate effectiveness.

**Comment by NotMyFault** [comment]
Widely, we use team scopes based upon the [archetypes](https://github.com/jenkinsci/archetypes/blob/master/common-files/.github/CODEOWNERS) default, but this tool is for individual users only, no?
