### ISSUE TITLE
PR not getting built

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#3977]
### Service(s)

ci.jenkins.io

### Summary

I filed https://github.com/jenkinsci/workflow-cps-plugin/pull/865 but it is not listed in https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/view/change-requests/ and https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/indexing/events ends with

```
…
[Tue Mar 05 14:52:49 UTC 2024] Pull request #817 updated in repository jenkinsci/workflow-cps-plugin UPDATED event from 140.82.115.46 ⇒ https://ci.jenkins.io/github-webhook/ with timestamp Tue Mar 05 14:52:43 UTC 2024 processed in 0.67 sec
[Tue Mar 05 14:52:49 UTC 2024] Received Pull request #817 updated in repository jenkinsci/workflow-cps-plugin UPDATED event from 140.82.115.80 ⇒ https://ci.jenkins.io/github-webhook/ with timestamp Tue Mar 05 14:52:44 UTC 2024
14:52:49 Connecting to https://api.github.com/ using 74951/****** (ci.jenkins.io GitHub App (jenkinsci org))
Examining [jenkinsci/workflow-cps-plugin](https://github.com/jenkinsci/workflow-cps-plugin)

  Checking pull-requests...

  Getting remote pull request #817...
```

Missing webhooks? I hope there is some periodic branch indexing configured which corrects this.

**Comment by jglick** [comment]
https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/indexing/console started by @NotMyFault seems to have created the branch project. Not sure why the event was lost. Could be closed.

**Comment by NotMyFault** [comment]
> [ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/indexing/console](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/indexing/console) started by @NotMyFault seems to have created the branch project. Not sure why the event was lost. Could be closed.

Oh hey, I had a similar PR that wasn't picked up, I started by hand. ci.j was down earlier due to the upcoming security advisory, and I'd assume we filed a PR right in this timeframe.

**Comment by dduportal** [comment]
> > [ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/indexing/console](https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/indexing/console) started by @NotMyFault seems to have created the branch project. Not sure why the event was lost. Could be closed.
> 
> Oh hey, I had a similar PR that wasn't picked up, I started by hand. ci.j was down earlier due to the upcoming security advisory, and I'd assume we filed a PR right in this timeframe.

Absolutely, ci.jenkins.io was down when https://github.com/jenkinsci/workflow-cps-plugin/pull/865 was opened. There is a "once a day" check (more often would start to take a toll on the Gh rate limit) which would have taken care of detecting the new PR immediately.

Could be a case to revive jenkins-infra/captain-hooks (to queue webhooks requests while a controller is down).

**Comment by dduportal** [comment]
@jglick I see the PR was merged: can you confirm it is closeable or do you need us to provide more on this?

**Comment by jglick** [comment]
> queue webhooks requests while a controller is down

That, or just rerun branch indexing for all repos after a restart. :thinking: Perhaps this should be an option built into `branch-api`?
