### ISSUE TITLE
CD tokens are not renewed

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#3982]
### Service(s)

GitHub

### Summary

Hi,

Looks like we cannot perform CD release due to expired token.

They should be renewed every 4 hours from what I remember.

But since yesterday there is not changes on those secrets

![image](https://github.com/jenkins-infra/helpdesk/assets/825750/1eca7875-4ec7-4db5-b0ef-1ed104040d87)

Seen on next-executions-plugin plugin : https://github.com/jenkinsci/next-executions-plugin/settings/secrets/actions

Thanks

**Comment by lemeurherve** [comment]
Opened https://github.com/jenkins-infra/azure/pull/639

Related:
- https://github.com/jenkins-infra/helpdesk/issues/3416

**Comment by lemeurherve** [comment]
azure-jenkins-sponsorship-credentials credentials updated on trusted.ci.jenkins.io, RPU job resumed, should finish in half an hour.

**Comment by lemeurherve** [comment]
RPU job finished.

@jonesbusy @timja could you trigger a cd action on your plugins to confirm the issue is resolved please?

**Comment by timja** [comment]
Running, token has been updated:
<img width="242" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/21194782/8fd22a63-0607-4392-b41a-dba8dc008537">

**Comment by jonesbusy** [comment]
Same here thanks!
