### ISSUE TITLE
Wrong email on registration to Jenkins Jira

### ISSUE THREAD

**Issue by OndraVagner** [jenkins-infra/helpdesk#3984]
### Type(s) of account issue

I didn't receive any email

### Summary

Hi,
I just created an account on Jenkins Jira, but unfortunately I set wrong email. I mixed up my company and personal email. Email I set is ondrej.vagner@gmail.com, but it needs to be vagnerondra@gmail.com. Could you please change this email for me?
Thanks a lot.

### jenkins.io account username

ovagner

### jenkins.io account email

ondrej.vagner@gmail.com

### Which URL are you trying to login at?

https://issues.jenkins.io/secure/Dashboard.jspa

**Comment by lemeurherve** [comment]
Hello @OndraVagner, can you send us a mail from both mailboxes at jenkins-infra-team@googlegroups.com in order to ensure you're the owner of both please?

**Comment by dduportal** [comment]
Hi @OndraVagner , could you retry with a new account please?
