### ISSUE TITLE
Requesting write access permission to jenkinsci/datadog-plugin

### ISSUE THREAD

**Issue by rahulkaukuntla** [jenkins-infra/helpdesk#3987]
### GitHub repositories

jenkinsci/datadog-plugin

### GitHub users to have permission

@rahulkaukuntla

### Permission level

Write

### Justification

I am a current employee of Datadog.

**Comment by MarkEWaite** [comment]
@rahulkaukuntla thanks for your willingness to help with the Datadog plugin.  Please submit a pull request to the [repository permissions updater](https://github.com/jenkins-infra/repository-permissions-updater/blob/) as described in the [README](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/README.md) and in the [Jenkins documentation](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/).
