### ISSUE TITLE
qTest Jenkins plugin developer team cleanup - do not have team management permissions

### ISSUE THREAD

**Issue by Slestac** [jenkins-infra/helpdesk#3988]
### GitHub repositories

https://github.com/jenkinsci/qtest-plugin 

### GitHub users to have permission

https://github.com/orgs/jenkinsci/teams/qtest-plugin-developers
should only have the following users:
@Slestac
@pjaladi21
@qasdev
@ole-ya

User @gunivan has left the organization and needs to be removed.

### Permission level

Admin

### Justification

We don't have permission to modify the team.

**Comment by timja** [comment]
I've given you the permissions to manage it
