### ISSUE TITLE
Not able to get jenkins password

### ISSUE THREAD

**Issue by souravmahajan** [jenkins-infra/helpdesk#3990]
### Type(s) of account issue

I've lost my password

### Summary

My email id is souravmahajan239@gmail.com.

Please help me to provide the password for jenkins

### jenkins.io account email

souravmahajan239@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by lemeurherve** [comment]
Hello @souravmahajan, I've triggered a password reset, you should receive a mail about it soon.

Can you let us know if it's OK for you?

**Comment by MarkEWaite** [comment]
Closing as no response for 3 days
