### ISSUE TITLE
New release of plugin-health-scoring is not seen by update-cli in Helm Charts

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3991]
### Service(s)

Other

### Summary

I have released the version 3.7.0 of Plugin Health Scoring yesterday (https://github.com/jenkins-infra/plugin-health-scoring/releases/tag/v3.7.0) and the version hasn't been seen by updatecli sur https://github.com/jenkins-infra/helm-charts/pulls.

Could you investigate why the release was not picked up by updatecli on Helm Charts repository?

**Comment by dduportal** [comment]
A quick note explaining why it is not picked:

- https://github.com/jenkins-infra/plugin-health-scoring/releases/tag/v3.7.0 is currently a draft (private page) which we set up `updatecli` to ignore:

<img width="1181" alt="Capture d’écran 2024-03-13 à 10 42 48" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/a36e868d-7c06-4f28-98eb-2e73bd493d7d">

- There is no tag associated with 3.7.0: https://github.com/jenkins-infra/plugin-health-scoring/tags


=> worth checking the "CD" process which might have failed on the main branch (and thus never published the git tag and artefacts, and as such never published the GH release)

**Comment by alecharp** [comment]
yes, we saw this with @smerle33. Something bad happened during the release as the tag was on the PR 477 merge.
This is clearly a problem between my keyboard and my chair.
