### ISSUE TITLE
Getting my Jenkins account

### ISSUE THREAD

**Issue by dnwoko4** [jenkins-infra/helpdesk#3992]
### Type(s) of account issue

I didn't receive any email

### Summary

It is not allowing me to log into my Jenkin account even though I know my username and password. The password reset has not been sent to my account, it has been an hour already!

### jenkins.io account username

dnwoko4

### jenkins.io account email

nwoko_dawn@yahoo.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Closing this request because there is no account registered at accounts.jenkins.io for the email address nwoko_dawn@yahoo.com or for the user name dnwoko4
