### ISSUE TITLE
Permissions for Jenkins Security Scan repos

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#3993]
### GitHub repositories

https://github.com/jenkins-infra/jenkins-codeql
https://github.com/jenkins-infra/jenkins-security-scan

### GitHub users to have permission

@yaroslavafenkin
@Kevin-CB

### Permission level

Maintain

### Justification

Members of the Jenkins security team and collaborators on the tool.

This can probably take the shape of [security](https://github.com/orgs/jenkins-infra/teams/security) membership (a larger scope) if @Wadeck approves.

**Comment by timja** [comment]
easiest way would be to add to the team: https://github.com/orgs/jenkins-infra/teams/security

**Comment by dduportal** [comment]
- I've added manually both users as maintainer on the 2 repositories to unblock @daniel-beck 's request short term
- I've set up both @Wadeck and @daniel-beck as "Team maintainers" for the GH team https://github.com/orgs/jenkins-infra/teams/security so they are autonomous to add Kevin and Yaroslav to the security team or not (please note that this team gives permissions to 7 repositories including the 2 repos requested here: that is why @Wadeck review is needed)

**Comment by daniel-beck** [comment]
> that is why @Wadeck review is needed

Wadeck told me last week that his 👍 _clearly_ constitutes approval of that suggestion 😁

**Comment by Wadeck** [comment]
I invited Kevin, but Daniel said, Yaroslav cannot be invited as he's not a member of the org :)

**Comment by dduportal** [comment]
> > that is why @Wadeck review is needed
> 
> Wadeck told me last week that his 👍 on the issue comment _clearly_ constitutes approval of that suggestion 😁
> 
> > <img alt="Screenshot 2024-03-20 at 09 15 25" width="1083" src="https://private-user-images.githubusercontent.com/1831569/314422989-450fe0ba-e8c7-43c1-acb6-677b34c44975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjczNjksIm5iZiI6MTcxMDkyNzA2OSwicGF0aCI6Ii8xODMxNTY5LzMxNDQyMjk4OS00NTBmZTBiYS1lOGM3LTQzYzEtYWNiNi02NzdiMzRjNDQ5NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDkzMTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RkMzc4Yjg4NTg1MTRhMTQxZGQ3NTRmNzZkOGE4NGRkZmI2YmE0NzdjZjlkYzMyYWE1NjZjODBhNGIwYzFlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-rizrUPbldKdP9ulFuovr1MzS8IgNvAvHBw3z5Mu5XU">
> 
> > Team maintainers … autonomous
> 
> Team maintainers cannot add people who aren't already org members.

Oh I missed the emoji 🤦 Thanks Daniel :D 

> I invited Kevin, but Daniel said, Yaroslav cannot be invited as he's not a member of the org :)

 Ack, I'm going to update the team and permissions accordingly. Thanks for answering!

**Comment by dduportal** [comment]
Ping @yaroslavafenkin you have a new invite in your GitHub notifications to join the jenkins-infra GH organisation in the `security` GH team.

Once accepted, i'll update repository permissions : until then I keep the "manual" ones :)

**Comment by yaroslavafenkin** [comment]
> Ping @yaroslavafenkin you have a new invite in your GitHub notifications to join the jenkins-infra GH organisation in the `security` GH team.
> 
> Once accepted, i'll update repository permissions : until then I keep the "manual" ones :)

Accepted.

**Comment by dduportal** [comment]
Access updated:

- Our 2 new members are now part of the GH security `team` (welcome onboard!)
- All individual permissions had been removed: they should keep the "maintain" permissions through the team permissions


@yaroslavafenkin @Kevin-CB can you confirm that you have maintainer permissions on the 2 repos before we close the issue?

**Comment by yaroslavafenkin** [comment]
Looks good on my end.

**Comment by daniel-beck** [comment]
@dduportal Thanks!
