### ISSUE TITLE
Permission setup for scm-filter-aged-refs-plugin strange

### ISSUE THREAD

**Issue by TobiX** [jenkins-infra/helpdesk#3994]
### GitHub repositories

https://github.com/jenkinsci/scm-filter-aged-refs-plugin

### GitHub users to have permission

@TobiX

### Permission level

Admin

### Justification

There currently seem to exist multiple teams for managing access to scm-filter-aged-refs-plugin:
- https://github.com/orgs/jenkinsci/teams/scm-filter-aged-refs-plugin-developers
- https://github.com/orgs/jenkinsci/teams/branch-source-aged-refs-traits-plugin-developers

While I could just remove the latter from the repository (I presume it's older/legacy), an admin could probably remove the team outright, so it doesn't become orphaned. Thanks in advance!

**Comment by NotMyFault** [comment]
Deleted, thanks!
