### ISSUE TITLE
Delete Jira `VERTEST` project

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3995]
### Service(s)

Jira

### Summary

Occasionally, issues like https://issues.jenkins.io/browse/VERTEST-37 land in the wrong project, we need to move out.
The [VERTEST](https://issues.jenkins.io/projects/VERTEST/summary) project was created more than a decade ago, has no issues left, and serves no purpose anymore.
I propose to delete it.

**Comment by dduportal** [comment]
Project deleted, thanks @NotMyFault !
