### ISSUE TITLE
Restrict issue creation in `MEETING` component

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3996]
### Service(s)

Jira

### Summary

The [MEETING](https://issues.jenkins.io/projects/MEETING/summary) project should not be enabled for new issue creation, as it is unused, and we moved away from it. Occasionally, people still create issues in the wrong project.
Therefore, I propose to disable issue creation.

(I think we have a `No create permissions` scheme for these cases, don't we?)

**Comment by MarkEWaite** [comment]
I've archived the MEETING project on the Jenkins Jira.  It has not been used for many years.
