### ISSUE TITLE
Requesting latest Plugin Health Scoring application logs

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#3997]
Hello,

there seems to be problem on the application as some probes / scoring are not reflecting the status of some plugin status.
This is coming from https://groups.google.com/g/jenkinsci-dev/c/l6WwouOW4KY.

Locally, I don't have such problem so I hope to get some answer from the application logs.

cc @viceice

**Comment by viceice** [comment]
https://plugins.jenkins.io/additional-identities-plugin/
https://plugins.jenkins.io/scoring-load-balancer/

Both plugin sites are not updated within last 6-7 days, checkout the badges, they show newer versions on github and plugin repo.

**Comment by alecharp** [comment]
Yes, it seems that the problem is coming from the plugins-site generation rather than the app. 
The scores are correctly updated on the application itself (see my message on the mailing list). 

I'm closing this as the logs of the application won't help but knowing why the plugins-site was not updated would.

**Comment by lemeurherve** [comment]
> I'm closing this as the logs of the application won't help but knowing why the plugins-site was not updated would.

You're right, opened https://github.com/jenkins-infra/helpdesk/issues/3999
