### ISSUE TITLE
plugin-site build is failing

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3999]
### Service(s)

plugins.jenkins.io

### Summary

The plugin-site build is failing since the 13th of March 2024, plugins.jenkins.io hasn't been updated since.

It seems related to Azure File Share authentication, currently looking into it.

**Comment by jonesbusy** [comment]
Thanks! Started to wonder why https://plugins.jenkins.io/artifactory-artifact-manager/ was not published

**Comment by viceice** [comment]
Yeah, noticed it too https://groups.google.com/g/jenkinsci-dev/c/l6WwouOW4KY/

**Comment by lemeurherve** [comment]
Manually ran a build with success, plugins.jenkins.io has been updated.

Working on a fix.
