### ISSUE TITLE
Service Principal used by infra.ci.jenkins.io to spawn Azure agents expires on 2024-03-22

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#4000]
### Service(s)

infra.ci.jenkins.io

### Summary

The SP password end date is set to 2024-03-22:

https://github.com/jenkins-infra/azure/blob/1c14ad33dfbf32f96755346fdba2915be0a4989b/infra.ci.jenkins.io.tf#L44-L48

It needs to be updated, then the corresponding credentials must be updated in chart-secrets (private repo).

**Comment by dduportal** [comment]
Opened https://github.com/jenkins-infra/azure/pull/648 to rotate (by extending expiration date of 3 months) the credential

**Comment by dduportal** [comment]
Weird: the Azure console was still showing the old SP password while terrafomr (and Azure API) showed the new one.

Old password value was invalid and revoked (which is good) but no new value visible though. Might be an Azure weirdness.

Out of caution, we deleted the existing SP password (not the SP!) and ran the terraform azure job a second time to create the new credential with success

**Comment by dduportal** [comment]
- Update the credential manually in infra.ci and tested it through the associated button
- Updated the credential in sops , pushed the change and kubernetes-management is currently re-deploying secrets

=> waiting 4 hours before closing (time to ensure any leftover in-memory Azure token are rotated to use the new SP)

**Comment by dduportal** [comment]
- Everything works as expected.
- Calendar updated to let us know about the next time
- Automatic PR to update the expiration dates should help: see https://github.com/jenkins-infra/azure-net/pull/191
