### ISSUE TITLE
Synopsys Security Scan Plugin version 1.3.0 has not been published yet in Jenkins marketplace

### ISSUE THREAD

**Issue by zaman-akib** [jenkins-infra/helpdesk#4001]
### Service(s)

plugins.jenkins.io

### Summary

We have released a new version (_1.3.0_) of **Synopsys Security Scan Plugin** about 5 hours ago but the latest version (_1.3.0_) is not yet available in Jenkins marketplace.

https://plugins.jenkins.io/synopsys-security-scan/

**Comment by lemeurherve** [comment]
Duplicate of #3999
