### ISSUE TITLE
cannot sing in to may user 

### ISSUE THREAD

**Issue by sasha1819** [jenkins-infra/helpdesk#4008]
### Service(s)

jenkins.io

### Summary

a couple of months ago I created a user in the Jenkins web app and found I could not sign in 
My username is Alex and my email is sashaa1819@gmail.com 
![Screenshot 2024-03-25 at 15 36 35](https://github.com/jenkins-infra/helpdesk/assets/89064497/37cdc8f1-84ab-40ba-80a9-d965838320f1)
place restart my account

**Comment by sasha1819** [comment]
the issue is on the localhost8080

**Comment by MarkEWaite** [comment]
> the issue is on the localhost8080

This issue tracker can't help with password recovery on localhost:8080.  You'll need to follow the guidelines in https://www.jenkins.io/doc/book/security/access-control/disable/

**Comment by sasha1819** [comment]
Can you fix it and restart my user?

**Comment by MarkEWaite** [comment]
> Can you fix it and restart my user?

No.  The Jenkins infra team has no access to your Jenkins controller at http://localhost:8080 .  That is something only you can access and only you can fix.
