### ISSUE TITLE
Recover Git repository for `remoting-test-client`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#4011]
### Service(s)

GitHub

### Summary

https://repo.jenkins-ci.org/artifactory/releases/org/jenkins-ci/remoting-test-client/ is a test dependency of remoting. While the contents of the last release (both binaries and sources) are available on Artifactory, I can't find them anywhere on GitHub. We should ask around if anyone still has the Git repository for this code. If not, I could reconstruct it from the last release, but would rather avoid that if possible.

### Reproduction steps

Here is a class from the JAR. A search for it shows the source code cannot be found anywhere on GitHub:

https://github.com/search?ref=simplesearch&type=Code&q=user%3Ajenkinsci+ClassLoadingFromJarTester

The source code is present in `remoting-test-client-1.1-sources.jar`, but it would be good to retain the original Git history if someone still has it.

**Comment by NotMyFault** [comment]
![Screenshot 2024-03-25 at 22 50 38](https://github.com/jenkins-infra/helpdesk/assets/13383509/48322c27-4f98-402b-8da4-b19185f6faf4)

It would be probably worth asking Oleg if he has a repository somewhere.

**Comment by NotMyFault** [comment]
Oh, I think I found it, it's a branch: https://github.com/jenkinsci/remoting/tree/test-client 👀

**Comment by basil** [comment]
I see. I'll extract the branch into a separate repository.

**Comment by basil** [comment]
I extracted this to https://github.com/jenkinsci/remoting-test-client and filed https://github.com/jenkins-infra/repository-permissions-updater/pull/3845 to update release permissions

**Comment by basil** [comment]
Can someone please help me set up a ci.jenkins.io build for https://github.com/jenkinsci/remoting-test-client/pull/1 ?

**Comment by MarkEWaite** [comment]
> Can someone please help me set up a ci.jenkins.io build for [jenkinsci/remoting-test-client#1](https://github.com/jenkinsci/remoting-test-client/pull/1) ?

Job has been created at https://ci.jenkins.io/job/Core/job/remoting-test-client/

**Comment by basil** [comment]
My attempt to perform a release failed, hopefully only because https://github.com/jenkins-infra/repository-permissions-updater/pull/3845 hasn't been deployed yet.

**Comment by basil** [comment]
I'll wait until someone can confirm that https://github.com/jenkins-infra/repository-permissions-updater/pull/3845 was deployed before I try to do another release.

**Comment by basil** [comment]
Component now lives at https://github.com/jenkinsci/remoting-test-client and we have successfully upgraded to a new release in https://github.com/jenkinsci/remoting/pull/728.
