### ISSUE TITLE
Latest commits for Contributor Spotlight not building properly.

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/helpdesk#4015]
### Service(s)

contributors.jenkins.io

### Summary

The 3 most recent commits for contributors.jenkins.io have not been built. In addition to not being built (I was unable to view the error details for this), it is showing the following error details: https://github.com/jenkins-infra/contributor-spotlight/runs/23112658283

The [PR itself passed all checks](https://github.com/jenkins-infra/contributor-spotlight/pull/105
<img width="992" alt="Screenshot 2024-03-26 at 12 58 29 PM" src="https://github.com/jenkins-infra/helpdesk/assets/99040580/20d392cc-0174-4f43-9e63-9526ea3cbe50">
), so there was no apparent issue during that merge.

**Comment by dduportal** [comment]
Looks like an issue with the network restrictions applied to the file storage. Should be fixed by https://github.com/jenkins-infra/azure/pull/651.

I'm starting a new deployment build on infra.ci

**Comment by dduportal** [comment]
The last build was successfull and the website was deployed as per https://github.com/jenkins-infra/contributor-spotlight/runs/23116722792

We have https://contributors.jenkins.io/pages/contributors/bruno-verachten/ 🥳

**Comment by kmartens27** [comment]
amazing, thank you so much @dduportal!
