### ISSUE TITLE
Junit plugin fails to download and causes Jenkins setup wizard to fail

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4016]
### Service(s)

get.jenkins.io

### Summary

I have confirmed the report in [JENKINS-72930](https://issues.jenkins.io/browse/JENKINS-72930) that the junit plugin released about two hours ago but it is not yet available from get.jenkins.io.

### Reproduction steps

1. Confirm that https://updates.jenkins.io/latest/junit.hpi?mirrorlist redirects to https://get.jenkins.io/plugins/junit/1265.v65b_14fa_f12f0/junit.hpi?mirrorlist and reports "Not found"
2. Note that the release is visible on the plugins.jenkins.io page at https://plugins.jenkins.io/junit/releases/
3. Note that the release is visible on archives.jenkins.io at https://archives.jenkins.io/plugins/junit/1265.v65b_14fa_f12f0/
4. Release is also visible on at least one mirror as https://ftp-nyc.osuosl.org/pub/jenkins/plugins/junit/1265.v65b_14fa_f12f0/

Same problem for https://updates.jenkins.io/download/plugins/junit-realtime-test-reporter/149.v05a_d403e2f48/junit-realtime-test-reporter.hpi that released at about the same time.

**Comment by dduportal** [comment]
Searching the update_center logs on trusted.ci and at least 2 builds (Builds 885724 and 885726, marked as "kept" until this issue is solved) mentioning the `junit/1265.v65b_14fa_f12f0` plugin to be released along with others:

```
18:27:10 >> Update artifacts on get.jenkins.io
18:27:10 artifactory-artifact-manager/53.vb_a_901cee2ef3
18:27:10 cdevents/1-37.v6412b_91c3799
18:27:10 junit/1265.v65b_14fa_f12f0
18:27:10 junit-realtime-test-reporter/149.v05a_d403e2f48
```



As per the logs, the loop at https://github.com/jenkins-infra/mirror-scripts/blob/926f48f80557829fe886367b36887372c5e02cfb/sync-recent-releases.sh#L39 is failing during the first iteration, due to the [`azcopy` instruction](https://github.com/jenkins-infra/mirror-scripts/blob/926f48f80557829fe886367b36887372c5e02cfb/sync-recent-releases.sh#L50-L55):

```
0.0 %, 0 Done, 0 Failed, 0 Pending, 1 Skipped, 1 Total, 
# ...
Final Job Status: CompletedWithSkipped
```

Continuing the investigations

**Comment by dduportal** [comment]
- A first problem is that the exit code of `azcopy copy` (defined in https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/storage-use-azcopy-troubleshoot#identifying-problems) is `1` when the file is skipped. Solution is to remove the `--overwrite=ifSourceNewer` flag
- But I'm facing a different behavior when running the script locally on the VM: it iterates on all plugins, while running from trusted still run only the first loop.

WiP

**Comment by dduportal** [comment]
Found the issue, was a tricky one: https://github.com/Azure/azure-storage-azcopy/issues/974

Fix applied in https://github.com/jenkins-infra/mirror-scripts/commit/89d31926095e52a1e28d829ac6cdf142bfc32b32 (sorry bad commit message but it's late here)


Let's see the result

**Comment by dduportal** [comment]
The issue should be fixed: can you confirm @MarkEWaite @timja ?

**Comment by basil** [comment]
Confirming that the setup wizard is passing, including successful download and installation of the JUnit plugin.

**Comment by MarkEWaite** [comment]
I've confirmed that the plugin installation manager tool downloads both junit and junit realtime test reporter plugins without errors.  Thanks!
