### ISSUE TITLE
Create `jenkinsci/build-token-root-plugin-developers`

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#4020]
### Service(s)

GitHub

### Summary

https://github.com/jenkinsci/build-token-root-plugin/pull/149#issuecomment-1689176677

(Is there any way to get RPU to automatically create & maintain these teams?)

**Comment by NotMyFault** [comment]
I've created the team and added you to it. Teams are created during the hosting process, not sure how old this repository is, maybe the process was different in the past 👀

**Comment by NotMyFault** [comment]
I forgot to add the team to the repository, should be sorted now.
