### ISSUE TITLE
problem logging in 

### ISSUE THREAD

**Issue by TeodoraNalbantova** [jenkins-infra/helpdesk#4023]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

I have problem logging into my account name: Teddy. 
I am sure i know and type the correct password but it keep saying is wrong etiher username or password.
I even tried by asking to send me email and to renew the password, but i do not receive email from you. My email is teodoranalbantova88@gmail.com
Please help 

### jenkins.io account username

Teddy

### jenkins.io account email

teodoranalbantova88@gmail.com

### Which URL are you trying to login at?

[account.jenkins.io/passwordReset](https://accounts.jenkins.io/login)

**Comment by dduportal** [comment]
Hi @TeodoraNalbantova , there are no account with this email registered in the public `*.jenkins.io` user database.

Are you expecting to access your Jenkins instance ? If that is the case, you should contact the administrators of this instance: accounts.jenkins.io is only for the `*.jenkins.io` publci websites such as issues.jenkins.io.
If that is NOT the case then could you describe what is the website you want to log-in into? for what purpose?

**Comment by TeodoraNalbantova** [comment]
Hello Damien,
Yes i try to log in on my localport 808, i think this what you mean by my own instance.
Can you please let me know where to find or what is the mail address of the administator.
That is why i wrote here because i do not see it anywhere since i see only the page for log in and then error.
Thank you
________________________________
