### ISSUE TITLE
Release of `jenkins/*` container images on DockerHub errors with `HTTP/429`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4029]
Since the middle of March 2024, almost all of the release of container images `jenkins/*` from trusted.ci.jenkins.io are failing due to HTTP/429 errors from the DockerHub.

It impacts the Core releases (weekly, LTS and security) as well as the agent images but it does **not** impact the Jenkins infra images (`jenkinsciinfra/*`).

After informal discussions with some Docker people:

- This is **NOT** an Image rate limit like we used to have in https://github.com/jenkins-infra/helpdesk/issues/2961
- It is, though, an API rate limit from their system used to protect them from abuses because we hit them hard: ~2,200 req / minute when a release happen.
  - Note that this count includes both `pull` and `push` (and manifests) API requests.

----

The identified root cause is that we release a LOT of different platforms in parallel to ensure fast build (ref. security advisory and maintainer sanity: no one want to wait 20 minutes for a release)

- Linux images (using the power of buildx) for `amd64`, `arm64`, `s390x`, `powerpc` etc. 
  - On different distributions (Debian, Alpine, etc.)
- Windows images with Server Core, Nanoserver, 2019, 2022, etc.

And we release using a single outbound public IP (see https://github.com/jenkins-infra/azure-net/blob/197e09ee7de9d04e47001ae8aa09dbb7188a0a5d/gateways.tf#L42-L55) which is quickly identified by their system as a source of requests :)

----

There are multiple remediation with different scopes:

- We need short term solutions to unblock our releases
- We need to ensure a long term solution to ensure we are a sustainable user of the DockerHub

**Comment by dduportal** [comment]
We need to get started on the following tasks:

- (infra team only, short term) Use multiple egress IPs on the trusted.ci network to spread requests
- (SIG platform, Jenkins Docker image maintainers, infra-team) Switch off from `eclipse-temurin` images (https://github.com/jenkinsci/docker/blob/d92706534dc2f8b8f28967cae5de4e113b997da1/17/debian/bookworm/hotspot/Dockerfile#L3, https://github.com/jenkinsci/docker-agent/blob/ba381c86f43a7181682cc4628269c662e4e647d8/debian/Dockerfile#L24 or https://github.com/jenkinsci/docker-ssh-agent/blob/ff05308f00fc237bb263272416952f79cecc8d4a/debian/Dockerfile#L3) to the temurin installer to ensure no less layers to pull (positive outcomes: faster availability of temurin new versions, less code to maintain)

**Comment by dduportal** [comment]
Update on "multiple outbound IPs on trusted.ci agent network to spread requests to DockerHub":

- Terraform module PR: https://github.com/jenkins-infra/shared-tools/pull/145
- Azure Net to have 3 IPs instead of 1: https://github.com/jenkins-infra/azure-net/pull/221 (blocked by the above PR on module)

**Comment by dduportal** [comment]
Update: trusted.ci.jenkins.io agents are now effectively using the 3 new public IPS.

- Tried to validate with a replay of `crawler` but only one IP was used
- Added a fixup in https://github.com/jenkins-infra/shared-tools/commit/34488cf0b020d6f2440bbeb4f91c98e01f631aa3 and deployed with success
- 2nd replay of `crawler` shows an effective outbound IP but **only** for ephemeral agents we use for docker image, crawler or websites. There is only 1 outbound IP for update center agent and for the controller (as they are on the non sponsored vnet).

**Comment by dduportal** [comment]
Planning ahead for the Docker image updates (now that we spread the IPs to be unblocked)

- @poddingue and @lemeurherve volunteered for the updated.
- First step is to apply the image change effectively. I propose to split the work to ensure we are efficient
  - @lemeurherve could you take care of the update on the agent images as you recently updated all of them?
  - @poddingue could you take care of the controller image as it has a different release cycle and Dockerfile architecture than the agents?
- Long term, as discussed with @lemeurherve , we might want to think about "Jenkins java parent image" so we would have even less layers and could reuse the same base images for all Jenkins container images. We are not sure this would be even doable or sustainable, not mentioning the impact around release lifecycle: let's plan it **after** the initial base image change

**Comment by gounthar** [comment]
Fine with me, thank you.

**Comment by MarkEWaite** [comment]
Jenkins controller 2.455 now uses the Temurin tar.gz file for its installation.

**Comment by dduportal** [comment]
As discussed during the infra team meeting: we consider this case closed as no more HTTP/429 were detected. Next steps are in the SIG platform's capable hands.
