### ISSUE TITLE
Delete account accounts.jenkins.io

### ISSUE THREAD

**Issue by aliayache** [jenkins-infra/helpdesk#4036]
### Type(s) of account issue

I want my account to be deleted

### jenkins.io account username

ali_80000

### jenkins.io account email

ali.ayache.bba@edhec.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/

**Comment by MarkEWaite** [comment]
I've sent an email to that email address asking for confirmation that the owner of the email address is the one that made the request.  Once a reply is received, the account will be deleted and this request will be closed as "Completed".  If a reply is not received, then this request will be closed as "Not planned".

**Comment by MarkEWaite** [comment]
Account deleted after reply has been received to confirmation email message.
