### ISSUE TITLE
Pipeline starts every time one of the nodes boots up 

### ISSUE THREAD

**Issue by ian-uson** [jenkins-infra/helpdesk#4038]
### Service(s)

Other

### Summary

Basically every time my windows node connects, it starts a build automatically of every pipeline that contains the windows node label. 
Would be really great if anyone knows how to stop this from happening. i cant find any settings that are causing this behavior

### Reproduction steps

1. set up pipeline with two nodes (one linux and one windows)
2. reboot windows node
3. watch jenkins start the build upon connection

**Comment by MarkEWaite** [comment]
This is the Jenkins infrastructure help desk.  It is used for questions related to the infrastructure of the Jenkins project.

Your question is a general usage question and is not related to the infrastructure of the Jenkins project.  Please ask your question at https://community.jenkins.io or on the Jenkins user mailing list or in the Jenkins chat channels.
