### ISSUE TITLE
Extend CloudSet for spotinst-plugin

### ISSUE THREAD

**Issue by sitay93** [jenkins-infra/helpdesk#4040]
### Service(s)

jenkins.io

### Summary

I want to add to clouds table bound to '/cloud/' more columns, populated with values from the cloud extending class "SpotinstCloud" such as LabelString.
I tried to find extension points like CloudSet and GlobalCloudConfiguration, however they are restricted for me to use and I'm still looking for the preferable way to do so.
Do you have a suggested way for that? It will be much appreciated!
Thanks, Itay Shklar

### Reproduction steps

1. Get into manage -> Clouds
2. the table inside should have the columns "Name" and "LabelString" from the clouds

**Comment by MarkEWaite** [comment]
@sitay93 this is the issue tracker for Jenkins infrastructure.  The people that watch this issue tracker are not generally developers of Jenkins plugins.  Please ask your question in the Jenkins developer mailing list, the Jenkins community forum, or the Jenkins chat channels.
