### ISSUE TITLE
Requesting permission for "repository-permissions-updater" repository

### ISSUE THREAD

**Issue by CJkrishnan** [jenkins-infra/helpdesk#4041]
### GitHub repositories

https://github.com/jenkins-infra/repository-permissions-updater

### GitHub users to have permission

CJkrishnan

### Permission level

Write

### Justification

I wish to adopt a "CloudBees CD" plugin as a maintainer, So I followed this DOC https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/#which-plugins-are-currently-up-for-adoption . 
As a part of this I need to create pull request against [Repository Permissions Updater](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-electricflow.yml). While Git push I am getting **403** access denied.

**Comment by MarkEWaite** [comment]
Thanks for your interest in adopting the plugin @CJkrishnan .

You'll need to submit a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to the [repository](https://github.com/jenkins-infra/repository-permissions-updater) by forking that repository, creating the change, pushing it to your fork, and then submitting the pull request. 

You won't be given direct access to the repository permissions updater repository.  Pull requests allow you to submit proposals for changes that those with permission can then approve and merge.
