### ISSUE TITLE
Let's Encrypt Azure Service Principal passwords expired for `cert.ci.jenkins.io` and `trusted.ci.jenkins.io`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4043]
### Service(s)

cert.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

The Azure Service Principal passwords used for the (Let's Encrypt) certificate renewal for `cert.ci.jenkins.io` and `trusted.ci.jenkins.io` are expired.

- These credentials are only used by the `certbot` when renewing certificates using the DNS challenge. It allows each one to create and remove DNS records (for LE challenge) scoped to each DNS zones.
- Management of these credentials is done by Terraform in jenkins-infra/azure-net and there are 2 PRs opened by updatecli, thanks to the team recent work around automation of credential rotation, to extend/renew these passwords:
  - https://github.com/jenkins-infra/azure-net/pull/216
  - https://github.com/jenkins-infra/azure-net/pull/218
- As noted in the PRs, once the passwords are rotated, we have to retrieve each one, insert them into the puppet encrypted data and, **once deployed**, verify by renweing the certificates on each VM.

Note: for information, the current certificates are valid until:

- trusted.ci.jenkins.io: 02 Jun 2024
- cert.ci.jenkins.io: 22 May 2024

**Comment by smerle33** [comment]
** check if done : **
/usr/local/bin/certbot renew --dry-run --force-renewal
