### ISSUE TITLE
Support for Visual Studio in windows container image

### ISSUE THREAD

**Issue by p-b-o** [jenkins-infra/helpdesk#4047]
### Service(s)

ci.jenkins.io

### Summary

Context
------------

While working on windows-arm64 support on `winp` jenkins component (https://github.com/jenkinsci/winp/pull/112), it was identified that CI used for it should be using `ci.jenkins.io`, instead of GitHub Actions, that this PR was adding.

Besides the debate, I've been trying to do what was expected from some of Jenkins core developers on this thread and use official Jenkins infrastructure to do this. I opened this offer PR (https://github.com/jenkinsci/winp/pull/115) to get more information on which image is used to run jobs on windows platform.

After some discussion, it was mentioned that image used is `jenkinsciinfra/inbound-agent-maven:jdk17-nanoserver` (src: https://github.com/jenkins-infra/docker-inbound-agents/blob/main/maven/jdk17/Dockerfile.nanoserver).

Investigation
-------------------

Winp contains native code (C++) and needs Visual Studio to be built.
So the first step was to get VS accessible in container.

install_vs.bat:
```
curl -L https://aka.ms/vs/16/release/vs_community.exe --output vs.exe || exit /b 1
start /wait vs.exe --quiet --norestart --wait --config vs.vsconfig || exit /b 1
```
Note:  `vs.vsconfig` was generated ahead, and contains list of packages needed.

Then, we tried to run this 
```
docker run -it --rm -m 4GB -w  C:/Users/user/Desktop/winp -v C:/Users:C:/Users --entrypoint cmd.exe jenkinsciinfra/inbound-agent-maven:jdk17-nanoserver /c install_vs.bat
docker run -it --rm -m 4GB -w  C:/Users/user/Desktop/winp -v C:/Users:C:/Users --entrypoint cmd.exe mcr.microsoft.com/windows:ltsc2019 /c install_vs.bat
docker run -it --rm -m 4GB -w  C:/Users/user/Desktop/winp -v C:/Users:C:/Users --entrypoint cmd.exe mcr.microsoft.com/windows/nanoserver:ltsc2019 /c install_vs.bat
```

Results
-----------

It was found that Visual Studio can't be installed on nanoserver images (which do not support any program installation in general). It works fine on full windows image `mcr.microsoft.com/windows:ltsc2019`

Thus, with the current image `jenkinsciinfra/inbound-agent-maven:jdk17-nanoserver`, it's not possible to build any native C/C++ code.

Request
------------

From there, different options are possible:
- offer a full windows image for inbound-agent on jenkins infrastructure
  - eventually add visual studio by default, so it's not needed to wait for a long install time (> XX minutes) for every job.
- use a vm instead of a container, with visual studio already setup.
- state that this won't be supported by Jenkins infrastructure, and that GitHub Actions can be used for this.

I didn't find where runner/image was configured for a given project/job, but I suspect the same inbound-agent image is used for all Jenkins projects. So changing this specifically for `winp` might just no be worth it.

Don't hesitate if you have further questions.
Thanks,
Pierrick

**Comment by slide** [comment]
What about the vs_buildtools? I was going to work on a docker image for that, but hadn't tried nanoserver (I doubt it will work). Can you share your vsconfig file?

**Comment by dduportal** [comment]
Hi! Thanks for opening this issue! 

For the first try, do you mind using a VM? Their cost and wait-time are not different than containers nowadays.

I've made a suggestion in https://github.com/jenkinsci/winp/pull/115/files#r1568279350so you could benefit from a Windows Server Core image (with chocolatey available).

**Comment by dduportal** [comment]
> Hi! Thanks for opening this issue!
> 
> For the first try, do you mind using a VM? Their cost and wait-time are not different than containers nowadays.
> 
> I've made a suggestion in https://github.com/jenkinsci/winp/pull/115/files#r1568279350so you could benefit from a Windows Server Core image (with chocolatey available).

The VM image is what we call the "all in one": https://github.com/jenkins-infra/packer-images/. It is a "kitchen sink" image type (e.g. all tools in one thing: faster, cheaper and easier to maintain). Our goal is to unify the VM and container templates: we are almost there for Linux (just a few website projects are there) but not yet for Windows container.
=> If anything is missing in the Windows VM template, then we can install quite easily.

Can we let you try with this and let us know what would be required for you?

**Comment by pbo-linaro** [comment]
> What about the vs_buildtools? I was going to work on a docker image for that, but hadn't tried nanoserver (I doubt it will work). Can you share your vsconfig file?

Same issue than vs installer.
VSConfig file can be found here: https://github.com/pbo-linaro/winp/blob/ci_windows_wip/vs.vsconfig

**Comment by pbo-linaro** [comment]
> > Hi! Thanks for opening this issue!
> > For the first try, do you mind using a VM? Their cost and wait-time are not different than containers nowadays.
> > I've made a suggestion in https://github.com/jenkinsci/winp/pull/115/files#r1568279350so you could benefit from a Windows Server Core image (with chocolatey available).
> 
> The VM image is what we call the "all in one": https://github.com/jenkins-infra/packer-images/. It is a "kitchen sink" image type (e.g. all tools in one thing: faster, cheaper and easier to maintain). Our goal is to unify the VM and container templates: we are almost there for Linux (just a few website projects are there) but not yet for Windows container. => If anything is missing in the Windows VM template, then we can install quite easily.
> 
> Can we let you try with this and let us know what would be required for you?

It would be nice if you could add VS2019, with content matching config file given above.
Even if we manage to a get a pipeline that install this for every, it would be much better if this could be available directly inside VM image.
Do you think it would be possible to add this on your side?

**Comment by dduportal** [comment]
> > > Hi! Thanks for opening this issue!
> > > For the first try, do you mind using a VM? Their cost and wait-time are not different than containers nowadays.
> > > I've made a suggestion in https://github.com/jenkinsci/winp/pull/115/files#r1568279350so you could benefit from a Windows Server Core image (with chocolatey available).
> > 
> > 
> > The VM image is what we call the "all in one": https://github.com/jenkins-infra/packer-images/. It is a "kitchen sink" image type (e.g. all tools in one thing: faster, cheaper and easier to maintain). Our goal is to unify the VM and container templates: we are almost there for Linux (just a few website projects are there) but not yet for Windows container. => If anything is missing in the Windows VM template, then we can install quite easily.
> > Can we let you try with this and let us know what would be required for you?
> 
> It would be nice if you could add VS2019, with content matching config file given above. Even if we manage to a get a pipeline that install this for every job, it would be much better if this could be available directly inside VM image. Do you think it would be possible to add this on your side?

On the principle: yes, and as soon as possible.

Under the hood, we provision VM templates with packer which uses the following powershell script: https://github.com/jenkins-infra/packer-images/blob/main/provisioning/windows-provision.ps1. We install MSI with the command line, but also download binaries and install chocolatey packages.

Speaking only for myself (not sure about the rest of the infra team) but could you help us a bit: I have no idea what VS2019 is and how to install it

- I believe "VS2019" to be "Visual Studio 2019" (https://visualstudio.microsoft.com/): is that correct?
- Would that chocolatey package be a good start: https://community.chocolatey.org/packages/visualstudio2019community?
- What is the policy regarding the 2022 line?

**Comment by pbo-linaro** [comment]
Thanks for your help @dduportal, it is much appreciated :+1:.

* VS2019 stands for Visual Studio 2019, which is the "stable" version of Visual Studio. 
* I'm used to install it manually with the official installer, but chocolatey seems to do the same thing.
* VS2022 is updated regularly, and many projects focus on 2019 to avoid any kind of regression. Considering we don't need recent features of C++, 2019 is probably a better choice here. Both can be installed at the same time by the way.

---

Now, some details about installation so you'll know it better.
VS2019 installer is available at: https://aka.ms/vs/16/release/vs_community.exe (17 for VS2022).
You can select different workloads, toolchains, and SDK to install. Once done, it's possible to export a json file with this configuration, so you can easily repeat your install. In our case, this file contains what is needed:

```cat vs2019.vsconfig```
```
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.Windows10SDK.19041",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM64",
    "Microsoft.VisualStudio.Component.Windows10SDK.16299",
    "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
    "Microsoft.VisualStudio.Workload.NativeDesktop",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM",
    "Microsoft.VisualStudio.Component.VC.v141.ARM",
    "Microsoft.VisualStudio.Component.VC.v141.ARM64",
  ],
  "extensions": []
}
```

Then, to run unattended installation:
```vs_community.exe --quiet --norestart --wait --config vs2019.vsconfig```

Chocolatey does the same (plus, it seems to install other things that I don't know what it is). Following the [documentation](https://community.chocolatey.org/packages/visualstudio2019community#releasenotes), you can add parameters to chocolatey install by using:
```choco install visualstudio2019community --package-parameters "--config vs2019.vsconfig"```

Considering the low effort to download and use official installer, I would prefer it, but if you're into choco, feel free to try with it.

---

I have no specific knowledge about packer and dedicated repo on jenkins-infra side, so I'm a bit afraid about the time I'll spend to just be able to reproduce anything. Could you kindly try to add VS2019 to this?

Thanks a lot!
Pierrick

**Comment by dduportal** [comment]
> Thanks for your help @dduportal, it is much appreciated 👍.
> 
>     * VS2019 stands for Visual Studio 2019, which is the "stable" version of Visual Studio.
> 
>     * I'm used to install it manually with the official installer, but chocolatey seems to do the same thing.
> 
>     * VS2022 is updated regularly, and many projects focus on 2019 to avoid any kind of regression. Considering we don't need recent features of C++, 2019 is probably a better choice here. Both can be installed at the same time by the way.
> 
> 
> Now, some details about installation so you'll know it better. VS2019 installer is available at: https://aka.ms/vs/16/release/vs_community.exe (17 for VS2022). You can select different workloads, toolchains, and SDK to install. Once done, it's possible to export a json file with this configuration, so you can easily repeat your install. In our case, this file contains what is needed:
> 
> `cat vs2019.vsconfig`
> 
> ```
> {
>   "version": "1.0",
>   "components": [
>     "Microsoft.VisualStudio.Component.CoreEditor",
>     "Microsoft.VisualStudio.Workload.CoreEditor",
>     "Microsoft.VisualStudio.Component.Roslyn.Compiler",
>     "Microsoft.Component.MSBuild",
>     "Microsoft.VisualStudio.Component.TextTemplating",
>     "Microsoft.VisualStudio.Component.VC.CoreIde",
>     "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
>     "Microsoft.VisualStudio.Component.Windows10SDK.19041",
>     "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
>     "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
>     "Microsoft.VisualStudio.Component.VC.Tools.ARM64",
>     "Microsoft.VisualStudio.Component.Windows10SDK.16299",
>     "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
>     "Microsoft.VisualStudio.Workload.NativeDesktop",
>     "Microsoft.VisualStudio.Component.VC.Tools.ARM",
>     "Microsoft.VisualStudio.Component.VC.v141.ARM",
>     "Microsoft.VisualStudio.Component.VC.v141.ARM64",
>   ],
>   "extensions": []
> }
> ```
> 
> Then, to run unattended installation: `start /wait vs_community.exe --quiet --norestart --wait --config vs2019.vsconfig`
> 
> Chocolatey does the same (plus, it seems to install other things that I don't know what it is). Following the [documentation](https://community.chocolatey.org/packages/visualstudio2019community#releasenotes), you can add parameters to chocolatey install by using: `choco install visualstudio2019community --package-parameters "--config vs2019.vsconfig"`
> 
> Considering the low effort to download and use official installer, I would prefer it, but if you're into choco, feel free to try with it.
> 
> I have no specific knowledge about packer and dedicated repo on jenkins-infra side, so I'm a bit afraid about the time I'll spend to just be able to reproduce anything. Could you kindly try to add VS2019 to this?
> 
> Thanks a lot! Pierrick

Thanks for all this details. It looks like it is enough for us to add it to the image.

No worries about packer: I was only giving context but the Jenkins infra team takes care of the effort to add it. That is the initial reason of the support issue: write down the requirement and to scope the installation.

Not sure about the choco / no choco install: both have their pro and cons. 
Given the JSON file you provided, I believe the unattended installation might be a nice fit.
Whil with Choco, it is easier to install and to get installer error feedback when it fails (unattended as always given me nightmare) but tends to be late to package latest versions.

We'll try one or the other and see if it works immediately.

Expect something available next week on ci.jenkins.io.

**Comment by slide** [comment]
I think we should use the vs_buildtools instead of vs_community. We don't need the IDE installed, just the tools to build from the command line.

**Comment by pbo-linaro** [comment]
Thanks @dduportal. Don't hesitate to ask if you have further questions.
Regarding vs_buildtools vs vs_community, I share your opinion @slide, but on most of the projects we have been working on in the team, they tend to stick to community (so you avoid having a specific build path for CI, and another for devs that use VS). Beyond that, I'm not sure if vs_buildtools installer supports the same json config as community installer.

**Comment by slide** [comment]
It does support the same vsconfig file. I am prototyping via Docker right now. I'm going to open a PR to the packer images repo with an install of the build tools, I'll even set it so it installs to the same path as Community.

**Comment by pbo-linaro** [comment]
Thanks a lot @slide :+1:!

**Comment by dduportal** [comment]
Update:

- Support for VS2019 on our Windows 2019 images has been added by @slide.
- Release in progress: we'll deploy it to ci.jenkins.io as soon as it is available

**Comment by pbo-linaro** [comment]
Many thanks to both of you!
I'll update winp maven build file to do C++ compilation, and try that in a new PR.
If anything is missing, I'll open another ticket here.

I confirm there are no additional steps required from jenkins-infra team.
