### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by preetisrivastava978** [jenkins-infra/helpdesk#4049]
### Type(s) of account issue

I didn't receive any email

### jenkins.io account username

preeti

### jenkins.io account email

preetisrivastava978@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
- There are no accounts associated with this email.
- The application logs shows no tentative to retrieve the email.

Are you sure you want to access an account on the public jenkins.io website? Isn't it for your Jenkins instance instead?

**Comment by dduportal** [comment]
Closing as no answers from the requester. Feel free to reopen if you have answers.
