### ISSUE TITLE
renew Azure AD Password before expiration for `sponsorship.ci.jenkins.io-tf-managed`

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4052]
### Service(s)

ci.jenkins.io

### Summary

The Azure Service Principal password used for the  sponsorship.ci.jenkins.io-tf-managed is soon to be expired. 
We need to rotate it and to check if we can automate the renewal at least partly with updatecli like https://github.com/jenkins-infra/helpdesk/issues/4043

to update
https://github.com/jenkins-infra/azure/blob/1cf37c7fd95e043d6ed6d60cb799c6574f6eed1b/ci.jenkins.io.tf#L39

**Comment by dduportal** [comment]
Update:

- @smerle33 implemented the new process to have `updatecli` opening PRs to propose an expiration update (e.g. an implied credential rotation) to have an artefact (+ notification) soon enough for us to avoid expirations in https://github.com/jenkins-infra/azure/pull/669
  - Result is https://github.com/jenkins-infra/azure/pull/675 => @dduportal takes care of landing this given the incoming holidays of @smerle33 
  - We will have to "improve" the `updatecli` process as per https://github.com/jenkins-infra/azure/pull/669#pullrequestreview-2014547188 but it does the job!

Next steps:

- Announce operation on ci.jenkins.io (homepage message) + status.jenkins.io
- Evaluate https://github.com/jenkins-infra/azure/pull/675 and merge it
- Retrieved the new credentials and update them on ci.jenkins.io
  - Manual test in the UI first (with puppet disabled) as it is the first time with the automated process
  - Then persist on IaC (puppet secrets)
- Close operation

**Comment by dduportal** [comment]
Update:

- Announces done (ref. https://github.com/jenkins-infra/status/pull/497 and ci.jenkins.io)
![Capture d’écran 2024-04-23 à 18 23 05](https://github.com/jenkins-infra/helpdesk/assets/1522731/6a4c1504-52e2-41ab-bd1a-167e9b738314)

- PR merged, deployed with success by Terraform on infra.ci.jenkins.io , and the Azure AD password's values has been retrieved to a secured (encrypted) location

- ci.jenkins.io's credential `azure-jenkins-sponsorship-credentials` has been updated manually on ci.jenkins.io's UI 
  - Verified both the Azure Credential and Azure VM clouds by clicking on the "Verify <...>" buttons with success

**Comment by dduportal** [comment]
Update: ci.jenkins.io uses the new credential with success. https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/check-agent-availability/3605/ was run with success after a controller restart.

**Comment by dduportal** [comment]
- Status updated
- Instructions for automated PR updated in https://github.com/jenkins-infra/azure/pull/680
