### ISSUE TITLE
Plugin health JSON sometimes missing

### ISSUE THREAD

**Issue by zbynek** [jenkins-infra/helpdesk#4056]
### Service(s)

Other

### Summary

https://reports.jenkins.io/plugin-health-scoring/scores.json is sometimes not available, causing a build  failure for the plugin site (see https://ci.jenkins.io/job/Infra/job/plugin-site/job/main/504/console and previous builds).

Right now the file is back online.

### Reproduction steps

Open https://reports.jenkins.io/plugin-health-scoring/scores.json in a browser

Expected: valid JSON
Actual: (sometimes) a blank page

**Comment by alecharp** [comment]
Currently the Health Score page of all plugins is empty. This because the report file is empty.

**Comment by lemeurherve** [comment]
Should be restored with https://github.com/jenkins-infra/infra-reports/pull/67, currently watching the resulting build.

**Comment by lemeurherve** [comment]
Health scores restored on plugins.jenkins.io 🙂

**Comment by halkeye** [comment]
fyi, we merged https://github.com/jenkins-infra/plugin-site/pull/1726 yesterday that prevents heath scores not existing from breaking the build. Feel free to revert if you want it to break the build

**Comment by alecharp** [comment]
I'd be in favour of the build to be broken with missing data.
I feel like this is part of the required data to show the site correctly. If there is no data, the page is empty which feels like broken to me.

**Comment by halkeye** [comment]
There's no alerts for if infra.ci build fails, so if it fails, the only reason people notice is when they go to do something, or it gets out of date for long enough that people look into it.

I would recommend instead creating a datadog alert to make sure the healthscores results are in place and working

**Comment by dduportal** [comment]
Datadog monitor created in https://github.com/jenkins-infra/datadog/pull/248.

We can close as it seems there are no other task required from the infra team. Please reopen if not the case!

Thanks all!
