### ISSUE TITLE
Block nigelalvarado account due to same email address as a known spammer

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4062]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

The account nigelalvarado has the same email address as known spam account jeffsnyder.

### jenkins.io account username

nigelalvarado 

### jenkins.io account email

jeffreybarker91@yahoo.com

### Which URL are you trying to login at?

Same email address as a known spammer.

**Comment by MarkEWaite** [comment]
Done

**Comment by lemeurherve** [comment]
Thanks!

https://github.com/jenkins-infra/helpdesk/issues/4061 for reference.
