### ISSUE TITLE
not receive mail for reset password

### ISSUE THREAD

**Issue by SwapnilUgalmugale** [jenkins-infra/helpdesk#4063]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

accidently  i forgot my password and trying to reset but not received any mail for reset the password

### jenkins.io account username

Swapnil_Ugalmugale

### jenkins.io account email

swapnilugalmugale2002@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @SwapnilUgalmugale , I've reset your password: please check your inbox (or your spam folder).

Please use https://account.jenkins.io/passwordReset next time (or check your spam folder)
