### ISSUE TITLE
User mikehussy blocked for 3 advertising spam messages to issues.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4064]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

User mikehussy with email address yadera6660@togito.com submitted 3 spam bug reports to issues.jenkins.io .  The account has been blocked and the 3 spam issues have been deleted.

### jenkins.io account username

mikehussy

### jenkins.io account email

yadera6660@togito.com

### Which URL are you trying to login at?

issues.jenkins.io

**Comment by MarkEWaite** [comment]
Done

**Comment by lemeurherve** [comment]
Should we start looking at some sort of ban & report automation? 😅

**Comment by MarkEWaite** [comment]
> Should we start looking at some sort of ban & report automation? 😅

If the recent spam pace continues, it would be useful.  Typically we receive less than one a week, but recent pace has been 3 spammers in 3 days
