### ISSUE TITLE
Discrepancy in Plugin Release Date

### ISSUE THREAD

**Issue by sadmananik** [jenkins-infra/helpdesk#4068]
### Service(s)

plugins.jenkins.io

### Summary

(https://plugins.jenkins.io/), the displayed release date appears to be outdated, showing "Released: 3 months ago". However, upon clicking on the plugin details, the actual release date is indicated as "Released: about a month ago".

This inconsistency in the displayed release dates is confusing for users seeking the most up-to-date information about the plugin. Could the Plugin Index be updated to accurately reflect the current release date of the Synopsys Security Scan plugin?

### Reproduction steps

1. Visit https://plugins.jenkins.io
2. Search "Synopsys Security Scan"
3. Check the released date shown in the search result
4. Click on the result and check the released date again 

![Jenkins-plugins](https://github.com/jenkins-infra/helpdesk/assets/36187489/5e771700-6ed9-43b4-abc2-a73b69b46acf)

**Comment by MarkEWaite** [comment]
Also reported by @halkeye in the Jenkins chat channels

**Comment by halkeye** [comment]
s/chat channels/mailing list/

**Comment by halkeye** [comment]
I'm guesssing whenever the [jenkinsfiles](https://github.com/jenkins-infra/plugin-site/blob/737efeeeb2cc4069df688690198061c799b2aff1/Jenkinsfile#L109-L111) were merged the secret GATSBY_ALGOLIA_WRITE_KEY is no longer populated.

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/plugin-site/commit/2ae7bb24f6771b28802b9e540d6adcc7db577fc6#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R116-R118

yea

**Comment by halkeye** [comment]
I would expect those secrets to still be there, someone just needs to set them up with secret(), should be super easy for someone who remembers how to jenkinsfile, probably wont be me though

**Comment by lemeurherve** [comment]
> [jenkins-infra/plugin-site@2ae7bb2#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R116-R118](https://github.com/jenkins-infra/plugin-site/commit/2ae7bb24f6771b28802b9e540d6adcc7db577fc6#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R116-R118)
> 
> yea

> I would expect those secrets to still be there, someone just needs to set them up with secret(), should be super easy for someone who remembers how to jenkinsfile, probably wont be me though

Unrelated:
- These secrets are still defined on infra.ci.jenkins.io and the pipeline logic around them hasn't changed with https://github.com/jenkins-infra/plugin-site/pull/1565
- This unification happened 4 and a half months ago, while the last Algolia data seems to date from 3 months ago

Will take a closer look later.

**Comment by lemeurherve** [comment]
> Found out that Algolia keys may have changed, but to verify it I'm blocked by https://github.com/jenkins-infra/plugin-site/issues/1723, I'll probably need some help.

@alecharp: gentle ping if by any chance it rings a bell.

**Comment by lemeurherve** [comment]
Nevermind, the issue resolved itself ^^

I'll update Algolia credentials on infra.ci.jenkins.io and trigger a new plugin site build.

**Comment by lemeurherve** [comment]
Indexing stopped on the February 27th:

<img width="1615" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/e56ec7f7-9281-4750-9dba-774a3a1793c4">

**Comment by lemeurherve** [comment]
I've updated Algolia credentials, ran a new plugin site build and requested a cache purge on https://plugins.jenkins.io but the search results are still stale.

@halkeye do you remember how Algolia updates its search results?
I haven't found anything in their dashboard to trigger a new indexation.

**Comment by dduportal** [comment]
> I've updated Algolia credentials, ran a new plugin site build and requested a cache purge on https://plugins.jenkins.io but the search results at https://plugins.jenkins.io/ui/search/?query=Synopsys+Security+Scan are still stale.
> 
> @halkeye do you remember how Algolia updates its search results? I haven't found anything in their dashboard to trigger a new indexation.

Quick note: please use https://plugins.origin.jenkins.io/ui/search/?query=Synopsys+Security+Scan to avoid the whole "cache purge" part

**Comment by halkeye** [comment]
The Gatsby build process submits new results to algolia on build when the env variables I mentioned earlier are set.

**Comment by halkeye** [comment]
Unless there's some magic going on injecting the secrets into the env, the build production stage doesn't reference those secrets.

https://github.com/jenkins-infra/plugin-site/blob/main/Jenkinsfile#L109

**Comment by halkeye** [comment]
potentially fix intermitant build issues: 
https://github.com/jenkins-infra/plugin-site/pull/1726

potentially restore algolia:
https://github.com/jenkins-infra/plugin-site/pull/1725

**Comment by lemeurherve** [comment]
Many thanks @halkeye!

I realised I removed these secrets by mistake in https://github.com/jenkins-infra/plugin-site/pull/1599

**Comment by halkeye** [comment]
`23:50:27  java.lang.NoSuchMethodError: No such DSL method 'secrets' found among steps [`

😭

**Comment by halkeye** [comment]
oh its credential () isn't it
@lemeurherve can you take care of it?

**Comment by lemeurherve** [comment]
> oh its credential () isn't it @lemeurherve can you take care of it?

Fixed in https://github.com/jenkins-infra/plugin-site/pull/1728

**Comment by dduportal** [comment]
> > > oh its credential () isn't it @lemeurherve can you take care of it?
> > 
> > 
> > Fixed in [jenkins-infra/plugin-site#1728](https://github.com/jenkins-infra/plugin-site/pull/1728)
> 
> As per https://www.jenkins.io/doc/book/pipeline/syntax/#environment, it is `credentials()` that you want :)

see https://github.com/jenkins-infra/plugin-site/pull/1728/files#r1587171816

**Comment by lemeurherve** [comment]
> > > > oh its credential () isn't it @lemeurherve can you take care of it?
> > > 
> > > 
> > > Fixed in [jenkins-infra/plugin-site#1728](https://github.com/jenkins-infra/plugin-site/pull/1728)
> > 
> > 
> > As per https://www.jenkins.io/doc/book/pipeline/syntax/#environment, it is `credentials()` that you want :)
> 
> see https://github.com/jenkins-infra/plugin-site/pull/1728/files#r1587171816

Thanks, addressed in https://github.com/jenkins-infra/plugin-site/pull/1729

**Comment by lemeurherve** [comment]
Build on main finished and Algolia search index correctly updated:

<img width="661" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/ad9334f1-0ea8-406d-9cf1-59925e2b40e8">

Closing this issue, thanks again @halkeye!

**Comment by sadmananik** [comment]
Thanks, everyone.

**Comment by halkeye** [comment]
![image](https://github.com/jenkins-infra/helpdesk/assets/110087/85fa0f7f-ac68-4f39-9234-8253058883de)

I say ticket is fixed and done

**Comment by halkeye** [comment]
oh i was commenting on a cached issue, sorry ya'll
