### ISSUE TITLE
[infra.ci.jenkins.io / accountapp] Build stuck waiting for `jdk17` label

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4070]
### Service(s)

Accounts, infra.ci.jenkins.io

### Summary

We periodically have builds stuck on infra.ci.jenkins.io waiting for agents with the label `jdk17` (both `main` branch and PRs):

![Capture d’écran 2024-04-22 à 18 09 44](https://github.com/jenkins-infra/helpdesk/assets/1522731/20d9941b-5197-493c-878f-b72b50f66ad0)

This is most probably a consequence of the "Jenkinsfile" merges between ci.jenkins.io and infra.ci.jenkins.io.

- https://github.com/jenkins-infra/account-app/blob/main/Jenkinsfile_k8s is not used anymore and should be removed (as per https://github.com/jenkins-infra/kubernetes-management/blob/265c5670d1d66014dd0ea38b168ad9eb3376048e/config/jenkins-jobs_infra.ci.jenkins.io.yaml#L33-L34)
- We have to implement a `jdk17` label on infra.ci to take these builds

**Comment by lemeurherve** [comment]
Related:
- https://github.com/jenkins-infra/account-app/pull/354

**Comment by dduportal** [comment]
Update:

- As explained in https://github.com/jenkins-infra/account-app/pull/354#issuecomment-2086460167, the PR https://github.com/jenkins-infra/account-app/pull/354 needs to be merged to allow us delivering new versions of `accountapp` but is  blocked due to a default java issue
- While the configured kubernetes agents are using a default JDK 17 ([on infra.ci.jenkins.io](https://github.com/jenkins-infra/kubernetes-management/blob/d616e5b6eb51010658e8e27377e3705674f603ea/config/jenkins_infra.ci.jenkins.io.yaml#L182-L184) and [on ci.jenkins.io](https://github.com/jenkins-infra/jenkins-infra/blob/7f11a424b5f54cd0fdd69cb36c65f944c01f883d/hieradata/clients/controller.sponsorship.ci.jenkins.io.yaml#L259)), the Azure VM does not have configured environment variable on the cloud template level (might require a tedious Cloudinit additional script) so they default to packer-image's default JDK11: https://github.com/jenkins-infra/packer-images/blob/main/provisioning/tools-versions.yml#L9

Next steps:

- Short term: add a custom env. var `JAVA_HOME` to use JDK17 in the pipeline to land the PR => @smerle33 
- Long term: prepare the (breaking change) in packer-image to use JDK17 as default (since JDK11 is almost dead!) => @smerle33 and @dduportal

**Comment by dduportal** [comment]
- New release of accountapp: https://github.com/jenkins-infra/account-app/releases/tag/0.5.43
- Deployed in production with https://github.com/jenkins-infra/kubernetes-management/pull/5228
- Application works very well \o/
