### ISSUE TITLE
Enable 2FA on jenkinsci npm account

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#4073]
### Service(s)

npmjs

### Summary

We should activate 2FA for the jenkinsci npm account https://www.npmjs.com/~jenkinsci as they preconised us by mail.

We'll use oathtool to allow anyone of the Jenkins Infrastructure team to log with 2FA.
Doc described in https://github.com/jenkins-infra/runbooks/tree/main/shared-totp (private repo).

Related:
- https://github.com/jenkins-infra/helpdesk/issues/3067

**Comment by lemeurherve** [comment]
2FA activated on the jenkinsci-admin account in control of the jenkinsci NPM organisation https://www.npmjs.com/org/jenkinsci.

2FA private key to use with oathtool (https://www.nongnu.org/oath-toolkit/index.html) and 2FA recovery keys added to the infra team 1password entry named "jenkinsci NPM org"

**Comment by lemeurherve** [comment]
Reopening as I missed storing of these credentials into the charts-secrets private repository instead.

**Comment by lemeurherve** [comment]
2FA private key and recovery codes regenerated, stored in https://github.com/jenkins-infra/charts-secrets/commit/baf4fe6c5cf38eb9ae4544c7f55a6c17f778f92e (private repo) instead of 1password account.

**Comment by timja** [comment]
What was the reason for charts-secrets over 1password?

These aren't going to be used by automation so I'd expect as they are for humans 1password would be where they are?

**Comment by dduportal** [comment]
> What was the reason for charts-secrets over 1password?
> 
> These aren't going to be used by automation so I'd expect as they are for humans 1password would be where they are?

The rationale is the following:

- Only a strict short list of team member should be allowed to access the NPMSJS account
- Maintaing permissions is easy with the SOPS system: we can exclude people, etc.
- Storing the 2FA shared totp in 1password is a risk. Any 1password pwnage would allow attacker to access the account as it defeats the goal of 2FA.

=> SOPS allows to maintain an easy CLI  access even for human to avoid risk copy and pastes

**Comment by dduportal** [comment]
Confirmed it worked for me 👍

**Comment by lemeurherve** [comment]
Added a dedicated txt file containing only the 2FA private key in https://github.com/jenkins-infra/charts-secrets/commit/7c62c555919052f4dbaf34c329acec9754e9d538.

Usage:
```
oathtool --base32 --totp "$(sops --decrypt ./secrets/config/npmjs.com/jenkinsci-admin-totp.txt)"          
859379
```
