### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by jyanesnotariado** [jenkins-infra/helpdesk#4078]
### Type(s) of account issue

I want my account to be deleted

### Summary

I want to change my username from jyanesancert to jyanesnotariado. Since I don't care much for my current account, it can just be deleted and then I'll create a new one.

### jenkins.io account username

jyanesancert

### jenkins.io account email

jyanes@notariado.org

### Which URL are you trying to login at?

https://accounts.jenkins.io/

**Comment by lemeurherve** [comment]
Hello @jyanesnotariado,

To validate your request can you comment on https://issues.jenkins.io/browse/JENKINS-73094 so we can verify that you control this account before deleting it please?

**Comment by jyanesnotariado** [comment]
Done, thanks

**Comment by lemeurherve** [comment]
Thanks too, `jyanesancert` account deleted.

**Comment by MarkEWaite** [comment]
Thanks.  I deleted the placeholder issue from issues.jenkins.io as well.
