### ISSUE TITLE
BOM testing build is stuck

### ISSUE THREAD

**Issue by alecharp** [jenkins-infra/helpdesk#4079]
### Service(s)

infra.ci.jenkins.io

### Summary

In order to validate https://github.com/jenkinsci/bom/pull/3163, infra.ci.jenkins.io should be running PCT. However, both builds on https://ci.jenkins.io/job/Tools/job/bom/job/PR-3163/ are stuck for hours now.

Could you please have a look at the agent provision? 
Would it be possible to trigger a new run?

**Comment by dduportal** [comment]
Hi @alecharp ! For info, we have an [ongoing issue with `datadog` plugin (again :'())](#4080) which caused this annoyance :(

The following fixes were done on ci.jenkins.io to unblock you:

- Force-abort the builds (marked as stuck) 1 and 2 of this PR with:

```groovy
Jenkins.instance
.getItemByFullName('Tools/bom')
.getBranch('PR-3163')
.getBuildByNumber(1)
.finish(hudson.model.Result.ABORTED, new java.io.IOException("Aborting build"));

Jenkins.instance
.getItemByFullName('Tools/bom')
.getBranch('PR-3163')
.getBuildByNumber(2)
.finish(hudson.model.Result.ABORTED, new java.io.IOException("Aborting build"));
```

- Started a new build (number 3)

**Comment by alecharp** [comment]
Thank you @dduportal.
As the PCT are running, I consider this matter resolved.
