### ISSUE TITLE
New repo for tool `plugin-modernizer-tool`

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#4081]
### GitHub repositories

plugin-modernizer-tool

### GitHub users to have permission

@jonesbusy
@gounthar
@berviantoleo
@iamrajiv

### Permission level

Admin

### Justification

Hi,

Not sure about the tool name, might change in the future. This can be voted.

But during GsoC 2024 we will build a new CLI tool (like plugin installation manager) in Java in order to apply recipes (OpenRewrite or other) for plugin modernization and refactoring. This tool is planned to evolve also in the future after GSoC and be a cental pillar of applying refactoring on plugins. There is also some plan to integrate with the plugin health score to fix issues.

It would be great to to have a repo to track discussion, issue and pull requests

Details: https://www.jenkins.io/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates/

You can grant me admin and I can setup correct permission for other mentors and @sridamul the contributor

Thanks!

**Comment by NotMyFault** [comment]
I've created the repository and a team for it.
