### ISSUE TITLE
can't access account, can't reset password

### ISSUE THREAD

**Issue by bgdnlp** [jenkins-infra/helpdesk#4085]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

Apparently the password I have is wrong, and I can't reset it. When I input just the username on the reset form it returns an error. If I put the email it says I'll get an email in a few minutes, but it doesn't arrive.

### jenkins.io account username

bgdnlp

### jenkins.io account email

jenkins.io@neant.ro

### Which URL are you trying to login at?

account.jenkins.io/passwordReset
https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Hi @bgdnlp , your LDAP was account had an empty field for the email which explains why you weren't able to recover your password.

As your account in JIRA (created in 2020, last successful login on 2021) confirms the emails specified in this GH issue, I've updated your account and triggered a password reset.

Please check your email, follow the instructions and let us know the outcome!

**Comment by bgdnlp** [comment]
All good. I got the email, was able to log in and set my password and I am now able to open a bug report, which is what I was after. Solved, thank you, I'll close the issue.
