### ISSUE TITLE
Jenkins process spawning large number of gparallelworker.exe processes 

### ISSUE THREAD

**Issue by ollieSayer** [jenkins-infra/helpdesk#4092]
### Service(s)

infra.ci.jenkins.io

### Summary

Hi, 

I have two nodes running on "Windows 10 Pro for Workstations" which both had a large number of 'GParallelWorker.exe' processes that are owned by the Jenkins service. Although no pipelines are currently running on the nodes these processes are each using 3% of the CPU totalling up to over 50% of the CPU usage when idle

Is this a known issue and if its possible to stop this from happening? 

![jenkins-github-issue](https://github.com/jenkins-infra/helpdesk/assets/26251421/ec4a4f0b-a627-45e7-9538-426d88b9104b)

I've restarted both nodes and so far these processes haven't returned however, I'd quite like to know if what the cause of this might have been and if I can stop it in the future as it caused a few performance issues with our pipeline when they did run 

Kind regards,
Ollie

**Comment by MarkEWaite** [comment]
@ollieSayer the Jenkins infrastructure help desk is used to address issues in the Jenkins infrastructure.  The Jenkins infrastructure community forum at https://community.jenkins.io and the Jenkins user mailing list and the Jenkins chat channels are locations where users help each other with Jenkins controllers and agents that are not managed by the Jenkins infrastructure team.  Please ask your question in one of those locations.
