### ISSUE TITLE
[wiki (docker-confluence-data) deprecated updatecli manifest

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4093]
### Service(s)

Other

### Summary

as per https://github.com/jenkins-infra/docker-confluence-data/issues/62
some updatecli manifest need to be updated

**Comment by dduportal** [comment]
Update:

- Updatecli manifest fixed
- But need a second change: https://github.com/jenkins-infra/docker-confluence-data/pull/64#issuecomment-2110447675

**Comment by dduportal** [comment]
Update:

- Second fix to also update the CST file in https://github.com/jenkins-infra/docker-confluence-data/pull/65
- As a positive result, https://github.com/jenkins-infra/docker-confluence-data/pull/64 was merged!
- New released image: https://github.com/jenkins-infra/docker-confluence-data/releases/tag/0.1.56
- PR for production deployment is https://github.com/jenkins-infra/kubernetes-management/pull/5238
