### ISSUE TITLE
Grand public visibility on ` GSoC 2024 - OpenRewrite` GitHub project

### ISSUE THREAD

**Issue by jonesbusy** [jenkins-infra/helpdesk#4094]
### GitHub repositories

https://github.com/orgs/jenkinsci/projects/30/settings

### GitHub users to have permission

@jonesbusy

### Permission level

Admin

### Justification

Hi,

Can you grant public visibility on the newly created GitHub project https://github.com/orgs/jenkinsci/projects/30/settings 

`GSoC 2024 - OpenRewrite`

![visibility](https://github.com/jenkins-infra/helpdesk/assets/825750/ffa6d3fb-029f-4f6f-850d-f7372247608b)

We will use this project for milestone tracking during the GSoC 2024 - OpenRewrite

I will add correct permission for other mentors and contributor on those boards.

Thanks

**Comment by jonesbusy** [comment]
Note: This is linked already to this repository: https://github.com/jenkinsci/plugin-modernizer-tool/projects?query=is%3Aopen

**Comment by NotMyFault** [comment]
Changed

**Comment by jonesbusy** [comment]
Thanks!
