### ISSUE TITLE
Request Temporal "Admin Read" Access for https://ci.jenkins.io/

### ISSUE THREAD

**Issue by carlosrodlop** [jenkins-infra/helpdesk#4095]
### Service(s)

ci.jenkins.io

### Summary

I'm planning to do a Talk on https://www.meetup.com/es/cloud-native-sevilla/ on 30th May with the title "Cloud Friendly Jenkins".

I would like to use https://ci.jenkins.io/ to present things like snippets configuration, agents builds, etc.

**Comment by dduportal** [comment]
Hi @carlosrodlop , let's get started with a few (public) elements that can be used or referred to about the Jenkins infra and our usage of Jenkins with some "Cloud Native" systems:



- Ephemeral agents in Kubernetes clusters:
  - Controller running in Kubernetes and agents on the same cluster but different namespace (infra.ci.jenkins.io, private): https://github.com/jenkins-infra/kubernetes-management/blob/19f16d5fd67b866d43dad83b6b4929d6eca977e4/config/jenkins_infra.ci.jenkins.io.yaml#L122C15-L122C25
  - Controller running in a VM and agents in a Kubernetes cluster (ci.jenkins.io, public): https://github.com/jenkins-infra/jenkins-infra/blob/b7219b29e1cfe860d6ecad3929da43310cf21b99/hieradata/clients/controller.sponsorship.ci.jenkins.io.yaml#L115-L117 (and ERB template generating JCasc YAML: https://github.com/jenkins-infra/jenkins-infra/blob/b7219b29e1cfe860d6ecad3929da43310cf21b99/dist/profile/templates/jenkinscontroller/casc/clouds.yaml.erb#L233)
- Ephemeral agents running in Azure VMs (used for safe Docker):
  - Controller running in Kubernetes and agents in Azure VMs (infra.ci.jenkins.io, private): https://github.com/jenkins-infra/kubernetes-management/blob/19f16d5fd67b866d43dad83b6b4929d6eca977e4/config/jenkins_infra.ci.jenkins.io.yaml#L284
  - Controller running in a VM and agents in Azure VMs (ci.jenkins.io, public): https://github.com/jenkins-infra/jenkins-infra/blob/b7219b29e1cfe860d6ecad3929da43310cf21b99/hieradata/clients/controller.sponsorship.ci.jenkins.io.yaml#L345 (and ERB template generating JCasc YAML: https://github.com/jenkins-infra/jenkins-infra/blob/b7219b29e1cfe860d6ecad3929da43310cf21b99/dist/profile/templates/jenkinscontroller/casc/clouds.yaml.erb#L6)


<img width="761" alt="Capture d’écran 2024-05-29 à 14 01 27" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/d0058a62-2225-4f86-bf4a-7963cf97124d">
<img width="755" alt="Capture d’écran 2024-05-29 à 14 01 38" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/c542a983-c57a-4ef5-948d-d5f8e323be39">
<img width="415" alt="Capture d’écran 2024-05-29 à 14 02 12" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/569ea4b3-22aa-4b32-85a6-92a0f5287377">
<img width="1001" alt="Capture d’écran 2024-05-29 à 14 02 22" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/641bb163-dd53-4725-a39d-e8fbfb4a9408">
<img width="1281" alt="Capture d’écran 2024-05-29 à 14 02 37" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/28b6a1d7-aa3d-4c09-8e34-b2ee4f876502">

**Comment by dduportal** [comment]
Another "Cloud Native" tool we use is [Docker Bake](https://docs.docker.com/build/bake/): it allows us to build multi platform Docker images for Jenkins (Controller and agents) at once (by platform we mean not only the usual Linux x86_64 and arm64, but also numerous Windows container images, Linux s390x CPU, etcs.)

- https://github.com/jenkinsci/docker-agent/blob/master/docker-bake.hcl
- https://ci.jenkins.io/job/Packaging/job/docker-agent/job/master/ (public)

<img width="1561" alt="Capture d’écran 2024-05-29 à 14 06 33" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/208006a8-ba4a-46f2-a1b8-0330a5d2f1cf">

**Comment by dduportal** [comment]
Thanks for the CNCF talk @carlosrodlop 👏
