### ISSUE TITLE
ftp.halifax.rwth-aachen.de blocked

### ISSUE THREAD

**Issue by bigazzzz** [jenkins-infra/helpdesk#4096]
### Service(s)

Update center

### Summary

It seems https://ftp.halifax.rwth-aachen.de/ is blocking in Russia. I did try https://ftp.belnet.be/ and it works fine but I have no idea how to force the use of that. Is there an option for it ?

**Comment by bigazzzz** [comment]
@C-Otto can you help me?

**Comment by C-Otto** [comment]
I might. What's your IP?

**Comment by C-Otto** [comment]
Please send a mail to ftp@halifax.rwth-aachen.de, this isn't a Jenkins issue.

**Comment by dduportal** [comment]
Hi folks 👋 

Thanks for opening the issue @bigazzzz! 

For information, we have 2 incoming mirrors in Romania being worked on: once deployed, it might help you solving such kind of issues on the long term.

Also, many thanks @C-Otto for sponsoring the Jenkins project so well! We are really grateful for your assistance

**Comment by tsteine** [comment]
Adding comment here in case it helps others, as I experienced this problem as well with https://ftp.halifax.rwth-aachen.de/

If you are running IPS/IDS on your router with filtering known TOR nodes, it could simply be that your IPS/IDS is blocking the return traffic from the mirror.

```
Detection Category
TOR
Signature
ET TOR Known Tor Relay/Router (Not Exit) Node Traffic group 150

Traffic Information
Source IP
137.226.34.46:443
Destination IP
REDACTED:44776
Activity
880 B
Action
Blocked
Interface
br0
Protocol
TCP
```
