### ISSUE TITLE
Update ci.jenkins.io, trusted.ci, cert.ci and release.ci to latest LTS version 2.452.1

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4097]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

New LTS 2.452.1 is out. We have to update our controllers:

- [x] release.ci.jenkins.io (Kubernetes)
- [x] ci.jenkins.io (Puppet managed VM)
- [x] trusted.ci.jenkins.io (Puppet managed VM)
- [x] cert.ci.jenkins.io (Puppet managed VM)

**Comment by dduportal** [comment]
- ci.jenkins.io done during a team onboarding session with @smerle33 and @jayfranco999
- trusted.ci and cert.ci done in https://github.com/jenkins-infra/jenkins-infra/pull/3425 during a team onboarding session with @smerle33 and @jayfranco999
