### ISSUE TITLE
sparshev account is unavailable in issues.jenkins.io

### ISSUE THREAD

**Issue by sparshev** [jenkins-infra/helpdesk#4103]
### Type(s) of account issue

I didn't receive any email

### Summary

Hello folks, wanted to create a new ticket - but found that my account in jira is unavailable and I can't login nor restore the account. Could you please help with that?

### jenkins.io account username

sparshev

### jenkins.io account email

work.sergei@parshev.net

### Which URL are you trying to login at?

https://issues.jenkins.io/login.jsp
https://accounts.jenkins.io/login
https://account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Unfortunately, `work.sergei@parshev.net` is not the email address associated with the `sparshev` account.  It looks like the account email address might be from an account with a former employer.  I assume you no longer have access to that account at the former employer.

The simplest approach is to create a new account and admit that the previous account is no longer usable for you.  As far as I can tell, you are not a plugin maintainer, so you won't lose permission to upload new plugin releases.

If that is not workable, then we'll need to enlist help from other members of the Jenkins infra team to decide how we confirm your identity without you having access to that old work email address.

**Comment by sparshev** [comment]
Oh yeah, I created it long time ago so could be that one. No worries, will create a new account then. It's not great to lose the reference id in jira, but it's better then waste your time folks.
