### ISSUE TITLE
Renew Azure credential for trusted.ci before expiration 8 of june

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4107]
### Service(s)

Azure, trusted.ci.jenkins.io

### Summary

Azure Credential for trusted.ci.jenkins.io expires 8 of june, 
Ref. 
[https://github.com/jenkins-infra/helpdesk/issues/3416](https://www.google.com/url?q=https://github.com/jenkins-infra/helpdesk/issues/3416&sa=D&source=calendar&usd=2&usg=AOvVaw10yxquOtrDFrnQBjLoiMEX) 
and 
[https://github.com/jenkins-infra/helpdesk/issues/3982](https://www.google.com/url?q=https://github.com/jenkins-infra/helpdesk/issues/3982&sa=D&source=calendar&usd=2&usg=AOvVaw3CosasSL1pA2PzYwFVoeTo) 

⚠️ check the procedure last time it failed

**Comment by smerle33** [comment]
as per https://github.com/jenkins-infra/azure/pull/712
done

**Comment by timja** [comment]
> the credential as been successfully updated (check with the `verify service credential` button) BUT was not used yet as it need to be forcefully updated with a save in the cloud configuration to manually clear the cache but a controller restart is advised.
> 
> (this may be a bug within the plugin `azureVM`)

It's probably this: https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java#L1039-L1045

It should likely retrieve it from the cache every time and then I think it would work, mind raising an issue though?
