### ISSUE TITLE
Streamline Maven versions across the infrastructure

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4110]
Most of the Jenkins infrastructure assets using Maven are automated enough to get latest versions of Maven when available, as you can see in https://github.com/jenkins-infra/helpdesk/issues/4109.

**However** we still have old Maven versions which should either removed, commented (to explain why not using latest version) or upgraded:

- [x] trusted.ci.jenkins.io has **multiple** tool versions for Maven: https://github.com/jenkins-infra/jenkins-infra/blob/b7219b29e1cfe860d6ecad3929da43310cf21b99/hieradata/clients/controller.cert.ci.jenkins.io.yaml#L41-L52
- [x] Puppet unit tests using rspec has a mention of Maven 3.9.2: https://github.com/jenkins-infra/jenkins-infra/blob/b7219b29e1cfe860d6ecad3929da43310cf21b99/hieradata/rspec/profile_jenkinscontroller.yaml#L40
- [x] the `jenkinsciinfra/packaging` Docker image (source in jenkins-infra/docker-packaging) use to build and release Jenkins Core still uses a `3.8.6` version of Maven: https://github.com/jenkins-infra/docker-packaging/blob/6e66c994d26563e0fa7a6f8e7b52842d6bee974e/Dockerfile#L109

These changes **must** be discussed with their author or usual maintainers!

**Comment by timja** [comment]
I doubt any of those have a reason not to be on the latest.

**Comment by dduportal** [comment]
Update: the only "critical" Maven old version in this issue is the one in `docker-packaging`.

Since we have https://github.com/jenkins-infra/helpdesk/issues/4135 preparing a major JDK upgrade in this Docker image, we should bump Maven version first.

Proposal: @jayfranco999 and I will work on this with the following tasks:

- Add an updatecli manifest to track Maven version in the repository for `docker-packaging`
- Have updatecli to bump the Maven version
- Ensure we have a new image release in 4.X deployed to the release repository

**Comment by dduportal** [comment]
Update for https://github.com/jenkins-infra/docker-packaging:
- Maven version tracked since https://github.com/jenkins-infra/docker-packaging/pull/111 + https://github.com/jenkins-infra/docker-packaging/pull/114
- Automated PR to update from 3.8.6 to 3.9.7: https://github.com/jenkins-infra/docker-packaging/pull/113
- New version is available: https://github.com/jenkins-infra/docker-packaging/releases/tag/4.0.76 with new Maven version

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/release/pull/548 => release will now use Maven 3.9.7 for weekly lines
- We might want to check future LTS lines

**Comment by dduportal** [comment]
Update: 

-Weekly release of Jenkins used Maven 3.9.7 with success
- PR for cleaning up / documenting the 2 last references: https://github.com/jenkins-infra/jenkins-infra/pull/3484
