### ISSUE TITLE
 Expiration of the Digital Oceans PATs [10 June 2024]

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4111]
### Service(s)

infra.ci.jenkins.io, DigitalOcean

### Summary

The Digital Ocean PATs (Personal Access Tokens) are expiring the 10 June 2024.

For info, previous token rotation: https://github.com/jenkins-infra/helpdesk/issues/3986

Todo list:

* [x] Generate a new pair of tokens:
  * Connect to DigitalOcean as the "Jenkins Infrastructure Technical User" (email: [jenkins-infra-team@googlegroups.com](mailto:jenkins-infra-team@googlegroups.com))
  * use https://github.com/jenkins-infra/runbooks/blob/main/shared-totp/README.adoc for 2FA
  * Browse to the "API"section -> "Applications & API" title -> "Tokens/key" tab
  * Regenerate the 2 tokens (or create new ones if they disappeared) with 90 days of TTL:
    * `infra.ci-production` => Read + Write
    * `infra.ci-staging` => Read-Only
* [x] Update tokens in the IaC setup:
  * [x] Update the SOPS encrypted secrets in https://github.com/jenkins-infra/charts-secrets - < [commit link](https://github.com/jenkins-infra/charts-secrets/commit/ad6f8f786f8c1c339e189aa34c091ad80d795195) >
  * [x] Run a build of jenkins-infra/kubernetes-management on its main branch to deploy new secrets
  * [x] Reload JCasc on infra.ci to ensure credentials are updated from new secret
* [x] Verify that the jenkins-infra/digitalocean is back to successful state (run a new PR or main build) - `Apply complete! Resources: 0 added, 0 changed, 0 destroyed`
* [x] Add a calendar event in 90 days with 2 weeks alert

**Comment by smerle33** [comment]
rotation and update done successfully

to plan next time, use a custom token to specify rights.

also, it's not possible to renew a token as it keep the same expiration date, so we need to delete the old ones and create new ones with the same names : 

    infra.ci-production => Read + Write
    infra.ci-staging => Read-Only
