### ISSUE TITLE
Remove user `veronapressbuymagicmushrooms`

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#4113]
### Service(s)

Jira, LDAP

### Summary

https://issues.jenkins.io/secure/ViewProfile.jspa?name=veronapressbuymagicmushrooms

**Comment by MarkEWaite** [comment]
Issue deleted from Jira and account has been updated with a new email address and a password reset to prevent further abuse

**Comment by dduportal** [comment]
User deleted from the LDAP as well. Thanks!
