### ISSUE TITLE
jenkin login issue

### ISSUE THREAD

**Issue by rajendranaya** [jenkins-infra/helpdesk#4115]
### Type(s) of account issue

I've lost my password

### Summary

im not able to login

### jenkins.io account email

rajendranayak3096@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by rajendranaya** [comment]
I need to discuss about issue
Please provide contact number
Past 2 days I'm suffering

**Comment by dduportal** [comment]
Duplicate of #4116
