### ISSUE TITLE
Salesforce authentication failed: Cannot run program "nohup" CreateProcess error=2, The system cannot find the file specified.

### ISSUE THREAD

**Issue by syammohanch** [jenkins-infra/helpdesk#4119]
### Service(s)

jenkins.io

### Summary

Salesforce authentication failed: Cannot run program "nohup" CreateProcess error=2, The system cannot find the file specified.

### Reproduction steps

Salesforce deployment with Jenkins and GitLab

**Comment by lemeurherve** [comment]
Please raise your question on either:
- community.jenkins.io - https://community.jenkins.io/
- Jenkins user mailing list - https://www.jenkins.io/mailing-lists/
- Jenkins chat channels - https://www.jenkins.io/chat/

Issues in this repository are used for Jenkins infrastructure, not for installations by Jenkins users.
