### ISSUE TITLE
[RPU] builds stuck in `trusted.ci.jenkins.io`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4122]
### Service(s)

trusted.ci.jenkins.io

### Summary

Since https://github.com/jenkins-infra/repository-permissions-updater/pull/3953, builds of RPU are stuck on trusted.ci.jenkins.io (past 14 hours).

As a consequence, the CD tokens are expired, preventing plugins to be released.

**Comment by dduportal** [comment]
Initial analysis on trusted.ci.jenkins.io: builds are stuck waiting for a `maven-21` node but this is not configured on trusted.ci.jenkins.io.

Applied the label to the `ubuntu-22` Azure VM template as a **hotfix** : VM was scheduled and build is running using JDK11 as it was before the https://github.com/jenkins-infra/repository-permissions-updater/pull/3953 change => it is only a label and we know RPU works fine with JDK11.

**Comment by MarkEWaite** [comment]
Thanks!  Sorry that I broke the RPU with that [pull request](https://github.com/jenkins-infra/repository-permissions-updater/pull/3953).  Is there a way the [pull request](https://github.com/jenkins-infra/repository-permissions-updater/pull/3953) that introduced the damage could have been safely executed on trusted.ci.jenkins.io without actually performing any operations?

**Comment by dduportal** [comment]
> Thanks! Sorry that I broke the RPU with that [pull request](https://github.com/jenkins-infra/repository-permissions-updater/pull/3953). Is there a way the [pull request](https://github.com/jenkins-infra/repository-permissions-updater/pull/3953) that introduced the damage could have been safely executed on trusted.ci.jenkins.io without actually performing any operations?
> 
> I assume probably not, so the next best thing would have been for me to ask someone with access to trusted.ci.jenkins.io to confirm that the jobs are still running successfully. I'll do that in the future.

Good point: we can check the status of the trusted.ci build after such a change in the future. But as the jenkins-infra team does not have a monitoring of private builds, it's not easy for you as a "consumer" though.

Another point: the jenkins-infra team should provide the same "feature set" for agent and their labels between ci.jio, trusted.ci.jio and infra.ci.jio. WiP on this!

**Comment by MarkEWaite** [comment]
We can also revert the change to repository permissions updater in order to remove any pressure for this change.  My change broke RPU and reverting the change is perfectly reasonable.

**Comment by dduportal** [comment]
> We can also revert the change to repository permissions updater in order to remove any pressure for this change. My change broke RPU and reverting the change is perfectly reasonable.

I would propose an intermediate:

- Set the label to `'maven-21' || 'java'` (so it always spawn an agent)
- Add a withEnv(`JAVA_HOME=/opt/jdk-21`) and/or using JDK tool


=> we have promising results and should be able to implement the `maven-XX` labels on trusted.ci soon!

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/repository-permissions-updater/pull/3958#issuecomment-2151495655 => RPU now builds properly 
- Adding `maven-21` label on trusted.ci.jenkins.io is tracked in https://github.com/jenkins-infra/helpdesk/issues/4124
- status closed - https://github.com/jenkins-infra/status/commit/729b58b3d076540de5fe4a5920398bd87fece533
