### ISSUE TITLE
Missing contributor spotlight update for Vandit Singh

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4129]
### Describe your use-case which is not covered by existing documentation.

https://github.com/jenkins-infra/contributor-spotlight/pull/138 was merged about 15 hours ago but is not yet visible at https://contributors.jenkins.io/

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

No additional information to offer

**Comment by lemeurherve** [comment]
The build of the main branch failed on infra.ci.jenkins.io while trying to download Node.js:

To follow progress, use 'tail -f /tmp/node-build.20240606113631.1995.log' or pass --verbose

>  Downloading node-v20.12.2-linux-arm64.tar.gz...
>  -> https://nodejs.org/dist/v20.12.2/node-v20.12.2-linux-arm64.tar.gz
>  error: failed to download node-v20.12.2-linux-arm64.tar.gz

I've restarted a build, will update this issue when it will be finished.

**Comment by lemeurherve** [comment]
Vandit Singh's page is now live: https://contributors.jenkins.io/pages/contributors/vandit-singh/

**Comment by MarkEWaite** [comment]
Thanks very much!
