### ISSUE TITLE
To host stats.jenkins.io GSoC 2024 project in jenkins-infra

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#4132]
### Service(s)

Helpdesk, stats.jenkins.io

### Summary

We are in the process of redeveloping the frontend for the data presentation of the Jenkins Infra Statitics project, and will need help migrating the GSoC contributor's repo (https://github.com/shlomomdahan/stats.jenkins.io/) from his personal GitHub account to one in the `jenkins-infra` org. 

@lemeurherve  @gounthar @shlomomdahan

### Reproduction steps

N/A

**Comment by lemeurherve** [comment]
@shlomomdahan could you initiate the transfer of your repository to https://githubcom/jenkins-infra please?

See https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by krisstern** [comment]
Thanks @lemeurherve!

**Comment by dduportal** [comment]
Question about Fastly: what is the rationale behind using Fastly in this case (compared to serving the website ourselves)?

**Comment by lemeurherve** [comment]
Same logic, using it as CDN as for other websites like jenkins.io, stories.jenkins.io, contributors.jenkins.io, docs.jenkins.io.

**Comment by dduportal** [comment]
> Using it as CDN, same logic as for other websites like jenkins.io, stories.jenkins.io, contributors.jenkins.io, docs.jenkins.io.
> 
> The website would be served from a nginx on publick8s at (new.)stats.origin.jenkins.io like the others.
> 
> Am I missing something?

For jenkins.io, the rationale has always been because of the amount of requests costs too much in outbound bandwidth. But it was measured.

do we have current stats for stats.jenkins.io ?

the question is related to: do we need a CDN ? If no then what is the point.

the same question I have for stories and contributors but i never had the answer or at least i do not see anything around numbers and facts for it.

**Comment by lemeurherve** [comment]
As stats.jenkins.io is currently hosted on GitHub Pages, I'm not sure we can access traffic from it.
I found https://github.blog/2014-01-07-introducing-github-traffic-analytics/ but it doesn't seem active anymore.

Then I don't think there's a lot of traffic on these pages, we can start serving it without Fastly then see what's the actual numbers in term of visits.

Removing the Fastly step points and reworking https://github.com/jenkins-infra/azure-net/pull/257

**Comment by lemeurherve** [comment]
FTR, I invited @shlomomdahan as writer on stats.jenkins.io.

Could be revised when a dedicated team is created.

**Comment by lemeurherve** [comment]
Opened https://github.com/jenkins-infra/stats.jenkins.io/pull/3 to add a pipeline for building the website on ci.jenkins.io and infra.ci.jenkins.io (pending https://github.com/jenkins-infra/kubernetes-management/pull/5310).

**Comment by krisstern** [comment]
Hi @lemeurherve, would it be possible to add @gounthar as a co-maintainer?

**Comment by lemeurherve** [comment]
https://github.com/orgs/jenkins-infra/teams/stats-jenkins-io including you and @gounthar created and set as "maintainer" on https://github.com/jenkins-infra/stats.jenkins.io/.

**Comment by lemeurherve** [comment]
I've set again ci.jenkins.io as required status check on the main branch protection, please don't change again this setting and keep it that way.

**Comment by shlomomdahan** [comment]
@lemeurherve Great!! Thank you

**Comment by lemeurherve** [comment]
> FTR, I invited @shlomomdahan as writer on stats.jenkins.io.
> 
> Could be revised when a dedicated team is created.

Changed @shlomomdahan as "reader" like the other GSoC students.

cc @krisstern

**Comment by lemeurherve** [comment]
Renovate configured on the repo, dashboard pinned: https://github.com/jenkins-infra/stats.jenkins.io/issues/22

**Comment by lemeurherve** [comment]
Added an item to the plan, watch the cost associated to the standard File Share cf https://github.com/jenkins-infra/azure/pull/729#discussion_r1643941847

**Comment by shlomomdahan** [comment]
> > FTR, I invited @shlomomdahan as writer on stats.jenkins.io.
> > Could be revised when a dedicated team is created.
> 
> Changed @shlomomdahan as "reader" like the other GSoC students.
> 
> cc @krisstern

I lost my ability to add reviewers to my PRs. Do you know If it's possible to maintain that feature?
Thank you

**Comment by timja** [comment]
> > FTR, I invited @shlomomdahan as writer on stats.jenkins.io.
> > Could be revised when a dedicated team is created.
> 
> Changed @shlomomdahan as "reader" like the other GSoC students.

This doesn't sound right, at least in a new repository. In an existing production service sure.

But this just adds friction  whilst unneeded imo.

**Comment by krisstern** [comment]
GSoC contributors are not supposed to have the ability to add their own reviewers either with `triage` or `write` rights, nor are they supposed to have the ability to review or approve merge requests in a Jenkins repo.

**Comment by timja** [comment]
> GSoC contributors are not supposed to have the ability to add their own reviewers either with `triage` or `write` rights, nor are they supposed to have the ability to review or approve merge requests in a Jenkins repo.

Why? Historically they have been able to.

CODEOWNERS can be setup to add reviewers automatically.

**Comment by krisstern** [comment]
> Why? Historically they have been able to.

I don't think so, not since I have been an org admin with Jenkins or from my own personal experiences working as a GSoC contributor. Frankly, I myself would not ask for it before the GSoC project has completed and I myself have gained the community's trust to do so. From what I observe previously most projects are first set up outside of Jenkins before migrating to the Jenkins org eventually upon completion. We do not normally set up repos under the Jenkins org first for GSoC during the coding period. This year is a first for me. 

If the repos are under the contributor's own account, that is another story.

**Comment by krisstern** [comment]
Why do the GSoC contributors need such rights anyway may I ask?

**Comment by timja** [comment]
> Why do the GSoC contributors need such rights anyway may I ask?

because its 'their' project. They are maintaining and creating it. The work is done async and mentors should be there to guide and not necessarily check the whole work.

_this is only for new projects that they have created_

historically we generally encouraged development in the jenkinsci org and there was a mix of people doing it on personal accounts and in the org.

**Comment by krisstern** [comment]
It is the GSoC contributors working for us on a project, but these are not their projects. They are sponsored by Google to work for us, the code belongs to us not to them. Also, they are not necessarily the ones maintaining, it is the mentors job to do so.

**Comment by krisstern** [comment]
@MarkEWaite @alyssat @jmMeessen @gounthar I feel like in this year there has been too many bad precedences in terms of GSoC project setup, and I feel like I cannot perform my role as a GSoC Org Admin. What are your opinions on this matter?

**Comment by lemeurherve** [comment]
Production part completed: https://new.stats.jenkins.io/

**Comment by lemeurherve** [comment]
Sorry if I overstepped on your role, I just wanted to help.

I'll restrict myself to pure infra related tasks for now on.

**Comment by gounthar** [comment]
I concur with @krisstern's perspective regarding write and triage permissions.
Based on my limited experience as a lead mentor, admin, and co-mentor, I have not witnessed contributors being granted such permissions to existing or new repositories within the Jenkins organization during the GSoC period.
Even if this has been the case previously, it does not align with my personal views.
When contributors have their own repository that will be transferred to the Jenkins organization later, they undoubtedly have every right to manage it. However, when it comes to existing or new repositories within the Jenkins organization, I believe granting such permissions is premature at this stage.
This is not a matter of doubting their trustworthiness or skills; it is simply a prudent approach. Nor does it imply that they are considered "second-class Jenkins citizens" – not at all.
I hold certain privileged permissions in some Jenkins repositories, and I occasionally make mistakes or push work that should be promptly reverted or forgotten. Conversely, I also contribute code that I take pride in to Jenkins repositories where I will never hold such permissions, and I am perfectly content with that arrangement.
This issue is more of an ethical consideration. The contributors are here to learn, and granting extensive permissions is not aligned with our standard practices outside of GSoC projects.
Across most repositories, rights and permissions are typically granted after an extended "probationary" period (although this process can be expedited for abandoned plugins).

**Comment by dduportal** [comment]
Thanks @krisstern for speaking up, this is important and healthy. I believe it would be useful to define precisely how the infra-team should be able to help but also the limits for other GSoC projects and next years. 

- Is there any urgent/short time things we (Jenkins Infra team) should stop doing (or start doing ;)) for this year?
- I propose we (Jenkins Infra) will plan a kind of postmortem exchange to produce a written runbook. I might contact you to interview you so we can improve.

**Comment by krisstern** [comment]
> Sorry if I overstepped on your role, I just wanted to help.
> 
> I'll restrict myself to pure infra related tasks from now on.

No worries @lemeurherve, I understand

**Comment by krisstern** [comment]
> Thanks @krisstern for speaking up, this is important and healthy. I believe it would be useful to define precisely how the infra-team should be able to help but also the limits for other GSoC projects and next years.
> 
> * Is there any urgent/short time things we (Jenkins Infra team) should stop doing (or start doing ;)) for this year?
> * I propose we (Jenkins Infra) will plan a kind of postmortem exchange to produce a written runbook. I might contact you to interview you so we can improve.

Sure, I will get in touch with you privately

**Comment by lemeurherve** [comment]
I had to push an hotfix with the correct STATS_SERVICE_PRINCIPAL_WRITER_CLIENT_ID value to fix production deployment error: https://github.com/jenkins-infra/charts-secrets/commit/4dca10bd26da859393aedff61ec672df0f297464 (private repo)

The CD part is now (almost) ready, https//new.stats.jenkins.io content is updated continuously on every new push on the main branch of the repository.

**Comment by lemeurherve** [comment]
After discussing with @krisstern about https://github.com/jenkins-infra/stats.jenkins.io/issues/2#issuecomment-2180111448

> this project is a part of the ongoing GSoC 2024 and is not in production yet. There will be many additions to its documentation as the project progress. Currently it is still in its development phase.

I propose to temporarily restrict repository interactions to "prior contributors" (include @jenkins-infra members) on https://github.com/jenkins-infra/stats.jenkins.io:

<details>

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/fe26d419-ac6d-42bd-baa0-97fd5302b5dd)

</details>

And to open a pinned issue in https://github.com/jenkins-infra/stats.jenkins.io to have an public status about this restriction.

WDYT?

**Comment by MarkEWaite** [comment]
> I propose to temporarily restrict repository interactions to "prior contributors"

That sounds fine to me.

**Comment by lemeurherve** [comment]
A temporary interaction limit to prior contributors has been added for a month:

<details>

> <img width="788" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/a59f4f95-6e6e-4485-ad0b-c644a4df6c82">

</details>

And an event in Jenkins Infra calendar pointing to this comment to renew the limit or not in a month.

**Comment by krisstern** [comment]
@lemeurherve Please add @Vandit1604 to the team with "triage" rights.

**Comment by lemeurherve** [comment]
@krisstern added as "triage":

<img width="796" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/2f769587-3cd8-43e6-a7e0-0ce31c0a2a02">

@Vandit1604 you should have received an invitation to join @jenkins-infra and accept this role, please note that it will expire in a few days.

**Comment by Vandit1604** [comment]
Thanks, @lemeurherve
I have accepted it.

**Comment by krisstern** [comment]
Hi @lemeurherve, is site preview for the PR's not an option at the moment? I am currently seeing the following:

<img width="1368" alt="Screenshot 2024-06-23 at 4 16 36 PM" src="https://github.com/jenkins-infra/helpdesk/assets/88480540/bc04e1a5-5c2e-492d-ae39-a2ba57ebc0db">

**Comment by lemeurherve** [comment]
@krisstern as @shlomomdahan doesn't have write permissions on the repo for now, builds on infra.ci.jenkins.io aren't triggered. (Security measure)

We discussed the case with @dduportal and came to the conclusion that we should create a distinct infra.ci.jenkins.io pipeline dedicated to previews that could be triggered without this requirement, while keeping the "production deployment" one restricted.

WIP, incoming soon.

**Comment by lemeurherve** [comment]
> we should create a distinct infra.ci.jenkins.io pipeline dedicated to previews that could be triggered without this requirement, while keeping the "production deployment" one restricted.
>
> WIP, incoming soon.

Should be addressed by:
- https://github.com/jenkins-infra/kubernetes-management/pull/5345
- https://github.com/jenkins-infra/stats.jenkins.io/pull/53

**Comment by lemeurherve** [comment]
Note that in order to implement https://github.com/jenkins-infra/stats.jenkins.io/pull/53 I made the compromise of duplicating "Install dependencies" and "Build" stages between this new pipeline dedicated to previews and the main one.

Currently reworking https://github.com/jenkins-infra/kubernetes-management/pull/5345 after discussing it with @dduportal  and @smerle33:
- Existing `stats.jenkins.io` job on infra.ci.jenkins.io
  - Moving it to a folder dedicated to deployment in production of the websites
  - Restricting build to main branch only
  - Disabling GitHub checks
    - Enforcing security
    - Will add a commit status via `publishChecks` to stats.jenkins.io main pipeline so contributors will be able to know if the main branch build has failed even if they don't have access to infra.ci.jenkins.io
- New `stats.jenkins.io_preview` job on infra.ci.jenkins.io
  - Needs to review "allowUntrustedChanges" so it does exactly what we want
    - To be developed in a separate help desk issue
  - GitHub checks enabled
  - Will exclude main branch from build as previews don't make sense for it
    - Needs testing and deployment of https://github.com/jenkins-infra/helm-charts/pull/1194 to add a `branchExcludes` field

**Comment by lemeurherve** [comment]
Previews are now working on all stats.jenkins.io pull requests, even those from contributors without write permission on the repository:

<img width="772" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/d9d47363-cf65-4983-938f-26af55c00422">

**Comment by krisstern** [comment]
Thanks @lemeurherve!

**Comment by krisstern** [comment]
@lemeurherve Could you please let us know what will be the arrangement for the data to be fetched for the project. Currently this appears to be a major blocker. Will data be fetched internally or externally?

**Comment by lemeurherve** [comment]
An helpdesk issue should be open to discuss how to put in place a public storage of the processed data from https://github.com/jenkins-infra/infra-statistics so they could be fetched when building https://github.com/jenkins-infra/stats.jenkins.io.

**Comment by dduportal** [comment]
As discussed during the Jenkins Infra SIG 09 July 2024: we keep this issue open until the GSoC project is finished and we have to deploy to the production URL + if infra work is needed.

In the latter case, please comment here and we'll evaluate during the next team SIG meeting.

**Comment by lemeurherveCB** [comment]
To resolve https://github.com/jenkins-infra/stats.jenkins.io/issues/118 we need to adapt nginx-website helm chart to allow adding the `try_files $uri /index.html;` directive to new.stats.jenkins.io to get direct links working.

I'll take care of it.

**Comment by lemeurherveCB** [comment]
With https://github.com/jenkins-infra/kubernetes-management/pull/5595 deployed direct links now work as expected, ex: https://new.stats.jenkins.io/statistics

https://github.com/jenkins-infra/stats.jenkins.io/issues/118 can be closed.

**Comment by krisstern** [comment]
Thanks @lemeurherveCB!

**Comment by dduportal** [comment]
Update: see https://github.com/jenkins-infra/helpdesk/issues/4265 .

@lemeurherve are you willing (and can you) drive the https://github.com/jenkins-infra/helpdesk/issues/4265 issue?
It means planning the effective switch to the new webservice.

We would also need to define what we do with the existing service:
- How much time do we keep it ?
- Archiving ?
- etc.

**Comment by lemeurherve** [comment]
Sure :)

Le mar. 27 août 2024, 15:29, Damien Duportal ***@***.***> a
écrit :

**Comment by krisstern** [comment]
@lemeurherve Can we also add @Vandit1604 and @shlomomdahan as the repo maintainers along with @gounthar and me?

**Comment by lemeurherveCB** [comment]
> Can we also add @Vandit1604 and @shlomomdahan as the repo maintainers along with @gounthar and me?

For @dduportal @smerle33: they should be added to the @jenkins-infra/stats-jenkins-io team (which has the "maintainer" role on the repository, and their possible custom/personal roles removed.

**Comment by krisstern** [comment]
> > Can we also add @Vandit1604 and @shlomomdahan as the repo maintainers along with @gounthar and me?
> 
> For @dduportal @smerle33: they should be added to the @jenkins-infra/stats-jenkins-io team (which has the "maintainer" role on the repository) and their possible custom/personal roles removed.

Just wanted to check, has this task been completed yet?

**Comment by hervelemeur** [comment]
There is still work to do to adapt plugin-site fetching source, I'll try to take a look soon.

**Comment by dduportal** [comment]
> > > Can we also add @Vandit1604 and @shlomomdahan as the repo maintainers along with @gounthar and me?
> > 
> > 
> > For @dduportal @smerle33: they should be added to the @jenkins-infra/stats-jenkins-io team (which has the "maintainer" role on the repository) and their possible custom/personal roles removed.
> 
> Just wanted to check, has this task been completed yet?

Hi @krisstern, it has been done:

- Both @gounthar and you had been set up as "maintainers" of the team. It means you will be able to add/change/remove users in the team
- Invitations sent to  @Vandit1604 and @shlomomdahan  to they can join the team

**Comment by dduportal** [comment]
Update: 

- The new website is online as per https://github.com/jenkins-infra/helpdesk/issues/4265 🥳 
- However, switching to the new site did had the following consequences which **require** additional (and mandatory) work in the upcoming weeks:
  - Plugin site generation was broken as it retrieve data from stats.jenkins.io. This data is missing in the new site so it has to be migrated.
    - See https://github.com/jenkins-infra/plugin-site/pull/1890 and https://github.com/jenkins-infra/plugin-site/pull/1893
    - Temporarily patch has been applied to avoid rollbacking, giving time for the proper fixes to be applied: we've set up the old site to be available at https://old.stats.jenkins.io until data is available on the new site (or not used by plugin site).

**Comment by lemeurherveCB** [comment]
_(copied from #4265)_

As noted in https://github.com/badges/shields/pull/10522#issuecomment-2346864474, there are far more consumers than we (I) initially though: https://github.com/search?q=stats.jenkins.io&type=code 😱

Links to (old.)stats.jenkins.io were pointing to files (still) stored on GitHub (currently on the `gh-pages`, generated from the pipeline of https://github.com/jenkins-infra/infra-statistics), while the new frontend doesn't serve them.

To avoid breaking existing consumers and without serving these files from our service, I propose to put in place redirections from the three folders of https://github.com/jenkins-infra/infra-statistics/tree/gh-pages (then from the `data` branch) to `https://raw.githubusercontent.com/jenkins-infra/infra-statistics/gh-pages/` with the help of https://github.com/jenkins-infra/helm-charts/pull/1332, WDYT?

Ex:
https://stats.jenkins.io/plugin-installation-trend/view-job-filters.stats.json would redirect to https://raw.githubusercontent.com/jenkins-infra/infra-statistics/gh-pages/plugin-installation-trend/view-job-filters.stats.json

**Comment by halkeye** [comment]
why take over the old domain at all? its pretty bad practice to break old files, and stats has always been raw metrics, csvs, and stuff

why not call the new site data.jenkins.io or dataviz and keep them seperate?

**Comment by lemeurherveCB** [comment]
Good point.

**Comment by timja** [comment]
I think fine to take over the domain but old links need to be maintained

**Comment by dduportal** [comment]
As underlined by @timja in another thread, any reason not to rollback and re-architecture?
For instance the new frontend in the github page site so it merges both sites ?

**Comment by lemeurherveCB** [comment]
Yeah that should be doable, the content is static. I take the blame here I
should have thought about that possibility.

I'll try on a fork tomorrow then propose a plan to adapt the service and
decommission the resources that won't be used anymore if that's OK for you.

**Comment by dduportal** [comment]
> Yeah that should be doable, the content is static. I take the blame here I should have thought about that possibility. I'll try on a fork tomorrow then propose a plan to adapt the service and decommission the resources that won't be used anymore if that's OK for you.

That's OK in term of planning 👍  thanks!

@krisstern @lemeurherve @gounthar WDYT if we roll back the DNS to the old site to repair user use cases, and it will let you time to plan, act and retest?

**Comment by krisstern** [comment]
Sure @dduportal, the arrangement is okay with me

**Comment by timja** [comment]
> Also: in term of permissions, it is a nightmare for ensuring production works as expected for the Jenkins Infra team. Any repository maintainer can accidentally break it.

I would say not a real concern, you are highly unlikely to touch this area.

**Comment by lemeurherveCB** [comment]
I propose to revise the decision to not use Fastly: activating it would allow us to serve files from our service without worrying about the bandwidth, while letting old.stats.jenkins.io in place for consumers who already switched.

**Comment by timja** [comment]
Sounds good to me, any concerns about using fastly?

Enough credits?

**Comment by dduportal** [comment]
> Sounds good to me, any concerns about using fastly?
> 
> Enough credits?

As discussed privately with @lemeurherve :

Cons of setting up Fastly:
- Additional work (to set it up, changing DNSes) as it is an additional component
- We're not sure if it is really needed here (e.g. how much data is really served by stats.jio?)
- Need to monitor if it's not adding too much usage in the sponsorship (I don't know, we can look now but we'll have to check it monthly)

Pros of using Fastly:
- Solve the bandwidth issue
- Fire and forget for the stats.jio website
- Same pattern as www.jenkins.io, plugins.jenkins.io, etc.

Any objection if we start without Fastly (less work and @lemeurherve can focus on solving the misssing files), wait for 1 month, check usage and enable Fastly eventually if needed?

**Comment by timja** [comment]
Sounds good to me

**Comment by lemeurherveCB** [comment]
Opened https://github.com/jenkins-infra/stats.jenkins.io/pull/168 to restore broken links.

**Comment by lemeurherveCB** [comment]
https://github.com/jenkins-infra/stats.jenkins.io/pull/168 has been deployed, links are restored, ex: https://stats.jenkins.io/plugin-installation-trend/view-job-filters.stats.json

**Comment by lemeurherveCB** [comment]
Proposition for the next steps:
- Change `old.stats.jenkins.io` CNAME to point to the new service on publick8s instead of the GitHub pages
- Add `old.stats.jenkins.io` as host to the new service ingress on publick8s (and remove `new.stats.jenkins.io` host as this CNAME isn't defined in azure-net anymore)
- Add this host to the datadog monitor
- Disable GitHub pages publication in infra-statistics
- Change infra-statistics "receiving" branch from `gh-pages` to `data` and propagate the change to its pipeline and in stats.jenkins.io's retrieve-infra-statistics-data.sh script
- Revert https://github.com/jenkins-infra/plugin-site/pull/1890 & https://github.com/jenkins-infra/plugin-site/pull/1893

**Comment by dduportal** [comment]
The production deployment process is broken since https://github.com/jenkins-infra/stats.jenkins.io/pull/168
as per @lemeurherveCB messag in https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$lK7-7uRQPpVDLey3LeH0KpMj5EJlxIJx7rGDxTsVlLA?via=g4v.dev&via=gitter.im&via=matrix.org

The `azcopy` keeps failing on subsequent replay or builds.

Currently investigating.

**Comment by dduportal** [comment]
> Currently investigating.

Failures from error logs are described in https://github.com/jenkins-infra/stats.jenkins.io/pull/168#issuecomment-2350870940

**Comment by smerle33** [comment]
redirection now working
