### ISSUE TITLE
Add `bstopp` to `adobe-cloud-manager-plugin` repo team: `jenkinsci/adobe-cloud-manager-plugin-developers`

### ISSUE THREAD

**Issue by ahmed-musallam** [jenkins-infra/helpdesk#4137]
### GitHub repositories

`adobe-cloud-manager-plugin`

### GitHub users to have permission

@bstopp

### Permission level

Admin

### Justification

@bstopp already has admin permission and is currently actively maintaining the plugin, please add his as requested.

**Comment by timja** [comment]
Done
