### ISSUE TITLE
Compilation of `jenkins-contribution-*` GO applications does not publish CodeCoverage report

### ISSUE THREAD

**Issue by jmMeessen** [jenkins-infra/helpdesk#4142]
### Service(s)

GitHub

### Summary

The code coverage automation doesn't work anymore for the two GO tools (see #4017 ). It requires at least an API token so that the coverage data can be uploaded. See https://docs.codecov.com/docs/adding-the-codecov-token

It is a handy feature especially as it fails the build if new code is added via a PR and is not covered by 80% coverage. A good reminder not to forget automated tests.

This is not a blocking issue but the loss of a handy feature.

**Comment by dduportal** [comment]
triaged: Related to #4017 , added to milestone, taken by @lemeurherve and/or @dduportal

**Comment by lemeurherve** [comment]
@jmMeessen according to the doc you linked, we should add an API token to the repository, obtained from the CodeCov account.

How can we access this CodeCov account?

**Comment by dduportal** [comment]
> @jmMeessen according to the doc you linked, we should add an API token to the repository, obtained from the CodeCov account.
> 
> How can we access this CodeCov account?

I wonder if we should not create a codecov account for `jenkins-infra` WDYT?

**Comment by lemeurherve** [comment]
Signup doesn't seem possible from an email: https://about.codecov.io/sign-up/

<img width="441" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/01623d80-9bc5-4052-83fb-4e1dc6f6468a">

**Comment by lemeurherve** [comment]
Requested permissions when using GitHub to sign up:

<img width="375" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/3d587fe6-a5fa-414d-96d4-26a0bcca4523">

WDTY of creating a GitHub account named like "jenkins-infra-service-account" (or something equivalent), with 2FA enabled via oathtool like https://github.com/jenkins-infra/helpdesk/issues/4073, that could be used to subscribe to this type of service?

**Comment by dduportal** [comment]
> Requested permissions when using GitHub to sign up:
> <img alt="image" width="375" src="https://private-user-images.githubusercontent.com/91831478/341099739-3d587fe6-a5fa-414d-96d4-26a0bcca4523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDk5MTMsIm5iZiI6MTcxODgwOTYxMywicGF0aCI6Ii85MTgzMTQ3OC8zNDEwOTk3MzktM2Q1ODdmZTYtYTVmYS00MTRkLTk2ZDQtMjZhMGJjY2E0NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE1MDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZjUwNmQxZTNmZDZkMjNiM2VjMjg1NWRjYTVkZGVmMjBiMzdlOTk0NGRjMDBiNzUwYjI5ZDAzOTE4OTAwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kgd7BXdE3TShGPGatPcnTR40U5XlB6v8wgzlbkXGFo0">
> 
> WDTY of creating a GitHub account named like "jenkins-infra-service-account" (or something equivalent), with 2FA enabled via oathtool like for #4073, that could be used to subscribe to this type of service without any risk?

That is an excellent idea! Are you ok to take care of this account creation?

**Comment by lemeurherve** [comment]
Account created: https://github.com/jenkins-infra-service-account

Next steps:
- [ ] Enable 2FA
- [ ] Create a CodeCov account
- [ ] Add CodeCov API token to the repository

**Comment by lemeurherve** [comment]
`CODECOV_TOKEN` organization secret created and scoped to https://github.com/jenkins-infra/jenkins-contribution-aggregator and https://github.com/jenkins-infra/jenkins-contribution-extractor.

According to https://docs.codecov.com/docs/quick-start#prerequisites,

> In order to get started, Codecov will need the following:
> - Access to a repository with [GitHub](https://github.com/), [Bitbucket](https://bitbucket.org/), or [GitLab](https://gitlab.com/).
> - If you are a GitHub user you MUST install the [Codecov GitHub app](https://github.com/apps/codecov) for your organization - Codecov can't function without it.

We need to install https://github.com/apps/codecov GitHub App to these two repositories.

WDYT @dduportal?

**Comment by dduportal** [comment]
> `CODECOV_TOKEN` organization secret created and scoped to https://github.com/jenkins-infra/jenkins-contribution-aggregator and https://github.com/jenkins-infra/jenkins-contribution-extractor.
> 
> According to https://docs.codecov.com/docs/quick-start#prerequisites,
> 
> > In order to get started, Codecov will need the following:
> > 
> > * Access to a repository with [GitHub](https://github.com/), [Bitbucket](https://bitbucket.org/), or [GitLab](https://gitlab.com/).
> > * If you are a GitHub user you MUST install the [Codecov GitHub app](https://github.com/apps/codecov) for your organization - Codecov can't function without it.
> 
> We need to install https://github.com/apps/codecov GitHub App to these two repositories.
> 
> WDYT @dduportal?

LGTM! Let's review the expected permission before performing the effective installation (e.g. you can start the process, check the requested permissions, report here and if it looks safe you'll be able to finish the installation)

**Comment by lemeurherve** [comment]
Requested permissions:

<img width="437" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/d621ea48-85d3-46f4-a120-875e35b01951">

**Comment by dduportal** [comment]
> Requested permissions:
> <img alt="image" width="437" src="https://private-user-images.githubusercontent.com/91831478/341169603-d621ea48-85d3-46f4-a120-875e35b01951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MjEwNjgsIm5iZiI6MTcxODgyMDc2OCwicGF0aCI6Ii85MTgzMTQ3OC8zNDExNjk2MDMtZDYyMWVhNDgtODVkMy00NmY0LWExMjAtODc1ZTM1YjAxOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE4MTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NTYxYzBhNmYzOTFlMTEzMDMxMTJiN2M4N2RmYTdjODIwMTJlYjE5OTEzMzY1YmViNWVkODFjYzUxYWVhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmMEBSOVwdz_qOVkvdNaVeu6eOtNQ4QIbrJQLACjRjU">

LGTM!

**Comment by lemeurherve** [comment]
I installed the CodeCov GitHub App on these 2 repositories:
<details>

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/2f4cab5d-7a07-455a-a112-0f4d0727a99a)

</details>

Working on this issue and on https://github.com/jenkins-infra/helpdesk/issues/4141 I noticed that previously defined repository secrets were imported, and were overriding organization secret in case of `CODECOV_TOKEN`:
<details>

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/b1d5454f-62a3-4df0-a46c-b93a17bb49eb)

</details>

I tried a GitHub Action run with the `CODECOV_TOKEN` repository secret removed in benefit of the `CODECOV_TOKEN` organization token set to the jenkins-infra-service-account token and scoped to these 2 repositories.
But it returned the following error cf https://github.com/jenkins-infra/jenkins-contribution-aggregator/actions/runs/9584808001/job/26440342954:

> Commit creating failed: {"detail":"Not valid tokenless upload"}

As jenkins-infra-service-account is only a regular member of @jenkins-infra organization and not an admin, we can't generate a CodeCov API token covering jenkins-infra org.
Thus I tried setting a new `CODECOV_TOKEN` repository secret to the API token of a repository configured in CodeCov interface (still logged as jenkins-infra-service-account):

<details>

<img width="715" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/6a59d6bc-e739-47d3-b8f5-11751b24038c">

<img width="729" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/bf94f5d5-bad8-4a19-ad55-e71dac4500cc">

</details>

And that worked, cf the "Upload coverage report to CodeCov" step of https://github.com/jenkins-infra/jenkins-contribution-aggregator/actions/runs/9584808001/job/26441218787

I then applied the same for the other repository:
- Configuring the repo in CodeCov interface
- Retrieving an API repo token from it
- Updated the existing `CODECOV_TOKEN` repository secret that was imported during the repo transfer

I reran a "Test" job to confirm CodeCov correct upload from this second repository: https://github.com/jenkins-infra/jenkins-contribution-extractor/actions/runs/9580302254/job/26441497327job/26441422043

And finally I removed the unused `CODECOV_TOKEN` organization secret that I created when I started working on this.

The CodeCov badges has been updated on both repositories, from:
<img width="305" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/5a49d76c-e7ce-4121-ae69-91d6f23646ac">
To:
<img width="299" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/7946efa0-73f5-4f0d-a142-8b7aa6e5b354">

Note: the free CodeCov account has only one personal seat but has up to 5 seats available for the jenkins-infra organization (I unticked the "auto-activate member" setting which was enabled by default):
<details>

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/fb2677d9-fed5-43c2-9eab-dfcff85a259e)

</details>

**Comment by lemeurherve** [comment]
Confirmed working for jenkins-contribution-aggregator, CodeCov report uploaded on https://github.com/jenkins-infra/jenkins-contribution-aggregator/pull/40 merge:
https://app.codecov.io/github/jenkins-infra/jenkins-contribution-aggregator/commit/4052b0c9ac472a3c2dee434f3c98fa8e702b213f

**Comment by jmMeessen** [comment]
I confirm too that the CodeCoverage upload appears to work. The real test of the feature will be when opening a PR with actual code changes. I am thus closing this issue as completed.

Thank you @lemeurherve to have thoroughly investigated this and found the adequate solution. 👍
