### ISSUE TITLE
[contribution stats] publication of honored contributor fails

### ISSUE THREAD

**Issue by jmMeessen** [jenkins-infra/helpdesk#4143]
### Service(s)

GitHub

### Summary

With the migration of the contribution stats system  from my user to the JENKINS-INFRA org, the automatic publication of the daily honored contributor CSV is broken.

This is caused by the inability of the automated process (GHA) to push the resulting CSV to the main branch (activation of protection rule). 

Solving this issue is urgent because the service is interrupted because of the migration and I will be around only for 6 work days.

**Comment by jmMeessen** [comment]
There are two options @lemeurherve 

- unprotect the master branch as a workaround to restore the service
- implement a long term solution in the remaining 6 days that are left to me (or later if the workaround is activated). The workaround requires clear specification from you.

**Comment by dduportal** [comment]
triaged: Related to #4017 , added to milestone, taken by @dduportal

**Comment by dduportal** [comment]
@jmMeessen I understand that the repository concerned by this issue is https://github.com/jenkins-infra/jenkins-contribution-stats which has a [./data/](https://github.com/jenkins-infra/jenkins-contribution-stats/tree/main/data) folder with CSV files.

I'm removing the branch protection and I'll trigger manually [the "honor contributors"](https://github.com/jenkins-infra/jenkins-contribution-stats/blob/main/.github/workflows/honor-contributor.yaml) workflow run, and I'll report the result here

**Comment by dduportal** [comment]
- Branch Protection removed:

![Capture d’écran 2024-06-18 à 16 48 23](https://github.com/jenkins-infra/helpdesk/assets/1522731/b2053bad-ba4c-4350-aa48-3ce4b321eec3)

- The "Honor Contributor" workflow ran successfully (build number 23: https://github.com/jenkins-infra/jenkins-contribution-stats/actions/runs/9567266017) and generated the following commit: https://github.com/jenkins-infra/jenkins-contribution-stats/commit/4473c5d1795052cada00791990e78b0397f3fe08

**Comment by dduportal** [comment]
@jmMeessen 

- Does it solve the problem explained in this issue? (thanks for splitting and [prioritizing](https://github.com/jenkins-infra/helpdesk/issues/4017#issuecomment-2175722711) ❤️ )?
- Should I now try the [
Monthly Stats Update
](https://github.com/jenkins-infra/jenkins-contribution-stats/actions/workflows/monthly-stats.yaml) workflow?

**Comment by jmMeessen** [comment]
This is perfect @dduportal 

I know that the unprotected master is ugly and a more thorough solution should be found.

The monthly run can be left as it is: it is an experiment and is not stable/tried in reallife. This is something that Bruno developped.
The current way is to run it locally, verify the results, and then upload the results.

**Comment by jmMeessen** [comment]
This solves the issue. Thanks al lot for the quick reaction.
