### ISSUE TITLE
Ensure website file share credentials are using the client password and not the service principal password

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#4149]
### Service(s)

infra.ci.jenkins.io, contributors.jenkins.io, docs.jenkins.io, plugins.jenkins.io, stats.jenkins.io

### Summary

While working on updating infra.ci.jenkins.io credentials following the merge of https://github.com/jenkins-infra/azure/pull/745 I noticed that the service principal was still working even without updating its password:

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/a35a7f17-207b-4f95-895d-e25fd40c7769)

Taking a closer look, we found out that some website credentials were setup by mistake with the service principal password which doesn't expire when extending end date, contrary to the client password.

We have to:
- [x] Ensure all website credentials use the correct type of password
- [x] Remove service principal id and password outputs from https://github.com/jenkins-infra/azure/blob/main/infra.ci.jenkins.io.tf
- [x] Remove service principal id and password outputs from https://github.com/jenkins-infra/shared-tools/blob/main/terraform/modules/azure-jenkinsinfra-fileshare-serviceprincipal-writer/outputs.tf

As a preliminary step, I opened the following pull request to avoid mistakes and oversights:
- https://github.com/jenkins-infra/azure/pull/754

**Comment by lemeurherve** [comment]
> Ensure all website credentials use the correct type of password

stats.jenkins.io credentials fixed in https://github.com/jenkins-infra/charts-secrets/commit/c7e2a0fe2daca3f5567688fb7d9d023f6e9d8315 (private repository).

All website credentials are now using client password.

**Comment by dduportal** [comment]
> > Ensure all website credentials use the correct type of password
> 
> stats.jenkins.io credentials fixed in [jenkins-infra/charts-secrets@c7e2a0f](https://github.com/jenkins-infra/charts-secrets/commit/c7e2a0fe2daca3f5567688fb7d9d023f6e9d8315) (private repository).
> 
> All website credentials are now using client password.

For contributors.jenkins.io, you also fixed it 2 days ago in https://github.com/jenkins-infra/charts-secrets/commit/e7341cc03b5c6bf6e5253119192e86f11d729060 (private repository) 👍

**Comment by lemeurherve** [comment]
Opened https://github.com/jenkins-infra/shared-tools/pull/150 to get a proper output name while working on the second part of this issue.

**Comment by lemeurherve** [comment]
All steps done, opened https://github.com/jenkins-infra/kubernetes-management/pull/5356 to get credentials with the same names as a nice-to-have follow-up, closing this issue.
