### ISSUE TITLE
Store jenkins-infra/infra-statistics data in a public location

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#4151]
### Service(s)

stats.jenkins.io

### Summary

To build its content, the new GSoC project https://github.com/jenkins-infra/stats.jenkins.io needs to retrieve the data generated when https://stats.jenkins.io is built on trusted.ci.jenkins.io (pipeline defined in https://github.com/jenkins-infra/infra-statistics).

How infra-statistics currently works:
- It retrieves data from two VMs via rsync
  - https://github.com/jenkins-infra/infra-statistics/blob/8209b583ee5be409d2dc8cdf780bd4358579b8de/Jenkinsfile#L50-L53
- It ingests this data in a local MongoDB database
  - https://github.com/jenkins-infra/infra-statistics/blob/8209b583ee5be409d2dc8cdf780bd4358579b8de/Jenkinsfile#L62-L66
- Several Groovy scripts are transforming this data in the desired format(s) and generate JSON files
  - https://github.com/jenkins-infra/infra-statistics/blob/8209b583ee5be409d2dc8cdf780bd4358579b8de/Jenkinsfile#L75-L86
- These JSON files are used to generate the static HTML content of https://stats.jenkins.io

To allow https://github.com/jenkins-infra/stats.jenkins.io fetching this data, we need to add a step to publish these generated JSON files in a public location.

Note: this data is already public and published at https://stats.jenkins.io.

I was thinking about putting this data in reports.jenkins.io, do you have other suggestions?

Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2191538603

**Comment by krisstern** [comment]
Putting the new data in `reports.jenkins.io` sounds like a good idea to me

**Comment by dduportal** [comment]
> I was thinking about putting this data in reports.jenkins.io, do you have other suggestions?

Excellent idea. LGTM!

On the infrastructure side, note that the report will have to be generated from trusted.ci: I don't know if it has everything required to publish to reports.jenkins.io (I would expect so, but worth checking before doing any work).
The reason is that we do not want to store the SSH accesses in infra.ci.jenkins.io at all (security concern).

**Comment by lemeurherve** [comment]
trusted.ci.jenkins.io can publish on reports.jenkins.io:
- It is one of the authorized instances of `publishReports` shared pipeline library function: https://github.com/jenkins-infra/pipeline-library/blob/161c28976a3a09f449bd92bb753bd06e3a8ad640/vars/publishReports.groovy#L11-L13
- It has the credentials used by `publishReports`: https://github.com/jenkins-infra/pipeline-library/blob/161c28976a3a09f449bd92bb753bd06e3a8ad640/vars/publishReports.groovy#L15
<img width="740" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/978d199e-f860-49c7-ac5c-6021a3ce0d2a">

**Comment by lemeurherve** [comment]
I think this issue can be closed as all data is already stored in the `gh-pages` branch of infra-statistics repository: https://github.com/jenkins-infra/infra-statistics/tree/gh-pages thus publicly available.

Ex: https://github.com/jenkins-infra/infra-statistics/commit/e5551a16c7c4054b523fe6578b878387654979ee

**Comment by krisstern** [comment]
Sure, I think we have been fetching data from https://github.com/jenkins-infra/infra-statistics/tree/gh-pages/jenkins-stats previously.

**Comment by lemeurherve** [comment]
Reopening without milestone to discuss how to fetch this data efficiently.

**Comment by lemeurherve** [comment]
From @shlomomdahan in the GSoC Slack channel:

> Is the most efficient way to do this by doing Axios requests to the raw GH page? I noticed it becomes quite slow when fetching data for 1000+ plugins

**Comment by lemeurherve** [comment]
If this suggestion is pursued, infra-statistics repository could be added as git submodule of stats.jenkins.io, then stats.jenkins.io pipeline checkout could be configured to retrieve its content (and thus the data) alongside stats.jenkins.io repository content.

This have the advantage of requiring no new infrastructure, and minimal change to the existing pipeline.

**Comment by lemeurherve** [comment]
After some tests and realizing that we can't use the `-b` (branch) argument in combination with `--depth 1` of `git submodule add` (https://git-scm.com/docs/git-submodule), I propose to change its default branch from `main` to `gh-pages` (with an indication to consult the main branch for the complete README) to avoid having to clone the entire infra-statistics repository as submodule.

WDYT?

**Comment by lemeurherve** [comment]
> with an indication to consult the main branch for the complete README

Something like https://github.com/lemeurherve/infra-statistics

**Comment by krisstern** [comment]
>  I propose to change its default branch from main to gh-pages (with an indication to consult the main branch for the complete README) to avoid having to clone the entire infra-statistics repository as submodule. 

I have no objection to this. But we will need to make a note in the "README.md" file to make things clear.

**Comment by dduportal** [comment]
> If this suggestion is pursued, infra-statistics repository could be added as git submodule of stats.jenkins.io, then stats.jenkins.io pipeline checkout could be configured to retrieve its content (and thus the data) alongside stats.jenkins.io repository content.
> 
> This have the advantage of requiring no new infrastructure, and minimal change to the existing pipeline.

Good idea to use a submodule! 

Given how « annoying » submodule seems to be, git subtree might be a good tool for this: https://www.atlassian.com/git/tutorials/git-subtree

**Comment by krisstern** [comment]
@lemeurherve Are you intended to open a PR for adding the submodule shortly? Or are you waiting for us to take the initiative to open a PR for this and to have you as a reviewer? This is currently a blocker for the project I believe and it may be getting in the way of further progress at this critical stage.

**Comment by lemeurherve** [comment]
After discussing the subject with @dduportal & @smerle33 we found an even simpler solution, retrieving the archive of the desired branch from https://github.com/jenkins-infra/infra-statistics/archive/refs/heads/gh-pages.zip

Preparing the PR.

**Comment by lemeurherve** [comment]
PR opened: https://github.com/jenkins-infra/stats.jenkins.io/pull/67

**Comment by krisstern** [comment]
Thanks once again @lemeurherve!

**Comment by lemeurherve** [comment]
@krisstern @shlomomdahan it looks like to me that this help desk issue can be closed, OK for you?

**Comment by krisstern** [comment]
Yup, okay for me to close this issue.
