### ISSUE TITLE
Ask OSSPlanet for a Jenkins mirror

### ISSUE THREAD

**Issue by sahilister** [jenkins-infra/helpdesk#4159]
### Service(s)

mirrors.jenkins.io

### Summary

[OSSPlanet](https://ossplanet.net/)  provides FS/OSS projects hosting and mirroring service in TW. See https://mirror.ossplanet.net/ 

See if they would host a Jenkins mirror - https://github.com/OSSPlanet/OSSPlanet?tab=readme-ov-file#how-to-apply

**Comment by dduportal** [comment]
Opened the issue https://github.com/OSSPlanet/OSSPlanet/issues/26

**Comment by dduportal** [comment]
The mirror seems to be up and running as per https://github.com/OSSPlanet/OSSPlanet/issues/26 last comment.

We can proceed to add it!

**Comment by dduportal** [comment]
Mirror added and documented (see private doc. here: https://github.com/jenkins-infra/runbooks/commit/6abf4a54f0d7e8460978a90dad067e8fcb5e5384).

Initial scan has been performed, we'll have to wait for the mirror to be enabled

**Comment by dduportal** [comment]
The new mirror is used as per https://get.jenkins.io/windows-stable/2.426.3/jenkins.msi?mirrorlist

Many thanks!
