### ISSUE TITLE
[trusted.ci, cert.ci] Missing JDK17 and JDK21 tools

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4169]
### Service(s)

cert.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

The 2 (private) controllers trusted.cert.ci.jenkins.io and cert.ci.jenkins.io are missing the JDK17 and JDK21 tools.

We want to enable these tools to support the Jenkins modernization as JDK11 is not supported anymore for weekly line (and ought to be unsupported for LTS lines in OCtober 2024).

For reference, this request was initially for cert.ci.jenkins.io and pointed out by @daniel-beck in https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$hTnJcqzFgGnW9llgKpTWh2BLxQ-1sddUQWlkd_BZc64?via=g4v.dev&via=gitter.im&via=matrix.org

Note: these are only "Jenkins tools", it is unrelated to the agent templates.
**however** the agent templates already provides up-to-dates JDK17 and JDK21 so tools should be easy to set up.

**Comment by smerle33** [comment]
added groovy 4.22.0 in generic tools too https://github.com/jenkins-infra/jenkins-infra/pull/3525 by @danielbeck
