### ISSUE TITLE
New mirror in Japan

### ISSUE THREAD

**Issue by delgh1** [jenkins-infra/helpdesk#4170]
### Service(s)

mirrors.jenkins.io

### Summary

Hi,

I would like my site to be listed as a mirror:

https://repo.jing.rocks/jenkins
http://repo.jing.rocks/jenkins
rsync://repo.jing.rocks/jenkins

The server is physically located in Tokyo, with a residential 10Gbps internet connection. I'm somewhat familiar with mirrorbits as it's also used by other projects. (repo.jing.rocks is a Tier 1 Arch Linux mirror.)

The sync frequency is every night, upstream is set to mirror.freedif.org for now.

Email contact: to prevent spam please search for GPG key `4E09 8D19 00AA 3F72 1899 2614 09B3 316E 13A1 1EFC`

Thanks &

**Comment by smerle33** [comment]
this mirror had been added in the mirrorbits for get.jenkins.io.
keep us informed if you have any problem

<img width="2899" alt="Capture d’écran 2024-07-24 à 15 58 24" src="https://github.com/user-attachments/assets/a32cac29-aea6-4bca-9bc8-9975df982256">

**Comment by smerle33** [comment]
Thanks for sponsoring the Jenkins Project 🎉
