### ISSUE TITLE
[infra.ci,weekly.ci] split repository jenkins-infra/docker-jenkins-weekly

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4171]
The repository jenkins-infra/docker-jenkins-weekly has a "monorepo" pattern for 2 distinct Docker images.

The tooling in this repository is slowing us down for many reasons:

- GH releases + tag do not map 1:1 with Docker image tag
- Sometimes, lifecycles are different (plugin list is different)
- It is not worth factorizing tooling
- It's not using `updatecli` has the other Docker images we're using

As such, I propose to split it into:

- infra.ci.jenkins.io: new repository `docker-jenkins-infraci`
  - New repo with same settings as previous one
  - Migrate git history (and tags)
  - Remove remnants of weekly.ci related code
  - Add infra.ci.jenkins.io job to build and release it + job for updatecli
  - Switch to updatecli for updating core and plugins
  - release a new version
  - Try a full Core update with 2.467 and release

- weekly.ci.jenkins.io: rename repository `docker-jenkins-weeklyci`
  - Add weekly.ci.jenkins.io job for updatecli
  - Remove remnants of infra.ci related code
  - Switch to updatecli for updating core and plugins
  - release a new version
  - Try a full Core update with 2.467 and release

**Comment by dduportal** [comment]
Update: created https://github.com/jenkins-infra/docker-jenkins-infraci with migrated git history and tags

**Comment by lemeurherve** [comment]
Renamed https://github.com/jenkins-infra/docker-jenkins-weekly to https://github.com/jenkins-infra/docker-jenkins-weeklyci

**Comment by dduportal** [comment]
Update:

- Version schemes fix in progress with https://github.com/jenkins-infra/docker-jenkins-weeklyci/pull/1643 (and following builds). NOTE: required to change the configuration of the repository as `jx-relese-version` is really a PITA
- Delete `docker-jenkins-weekly` job from infra.ci (no need for it anymore and no need for its logs

**Comment by dduportal** [comment]
Update:

- Created the 2 new Docker "repositories" (e.g. the plaecholder, in DockerHub, for the 2 new images:
  - https://hub.docker.com/r/jenkinsciinfra/jenkins-infraci
  - https://hub.docker.com/r/jenkinsciinfra/jenkins-weeklyci
-   Updated the permissions, in DockerHub for our technical user:
  - Both new "Docker repositories" allows read & write
  - The former [`jenkins-weekly`](https://hub.docker.com/r/jenkinsciinfra/jenkins-weekly) does not allow anything else (e.g. only admin can change it)

<img width="610" alt="Capture d’écran 2024-07-15 à 12 35 34" src="https://github.com/user-attachments/assets/871be7ab-9123-4b75-abc0-270b4173587b">


- Opened a (for now draft) PR to materialize these changes production wide: https://github.com/jenkins-infra/kubernetes-management/pull/5422

Next step: WiP on docker-jenkins-infraci

**Comment by dduportal** [comment]
Update on jenkins-infraci:

- GH repository setup: Set up general settings, permissions and branch protection with the same as jenkins-weeklyci
- Allowed the GH organization secrets (for updatecli) to the new repo
- Ran the release-drafter GH action once to ensure a `next` draft GH release is present
- Opened the PR https://github.com/jenkins-infra/docker-jenkins-infraci/pull/1 (with breaking change) to set the repo content and pipeline up (twin of <https://github.com/jenkins-infra/docker-jenkins-weeklyci/pull/1640>)

**Comment by dduportal** [comment]
Update:

- Updated the GH app installation to allow the new repository (otherwise the GHA are failing when trying to generate a token from GH org. secrets)
- Hot-fixed the docker-jenkins-infraci repo to re-re-write the commit message to pleases `jx-release-version` because it's not accepting wrapped commit messages from GitHub.
- WiP: after an initial successful release of each, doing a full cycle of plugins + core PRs

**Comment by dduportal** [comment]
Update: all controllers are updated with the new lifecycle system.

Ref. https://github.com/jenkins-infra/kubernetes-management/pull/5424 and https://github.com/jenkins-infra/kubernetes-management/pull/5423
