### ISSUE TITLE
Remove 999999-SNAPSHOT version of Remoting from Artifactory

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#4173]
### Service(s)

Artifactory

### Summary

Core isn't getting Dependabot PRs for Remoting anymore, forcing me to manually update it as in https://github.com/jenkinsci/jenkins/pull/9412, or is getting nonsense PRs like https://github.com/jenkinsci/jenkins/pull/9448. I suspect this is yet another manifestation of #3919. Looks like the current content in https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/main/remoting/999999-SNAPSHOT/ is a set of snapshots uploaded by @jtnord on May 15, presumably to test https://github.com/jenkinsci/remoting/pull/741, https://github.com/jenkinsci/remoting/pull/742, / https://github.com/jenkinsci/remoting/pull/743, all of which have now been delivered. Assuming the snapshots in https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/main/remoting/999999-SNAPSHOT/ are no longer needed for testing, can we delete them from the server as a workaround for #3919? Ideally the root cause of the problem would be addressed, but I believe the above action would at least restore the status quo and re-enable automated Dependabot bumps to core.

**Comment by jtnord** [comment]
>Ideally the root cause of the problem would be addressed, but I believe the above action would at least restore the status quo and re-enable automated Dependabot bumps to core.

https://github.com/dependabot/dependabot-core/pull/8514 (fixed) - perhaps this one is due to our setup that is using a single mirror for both snapshots and releases?

FWIW, I naively expected a snapshot clean-up policy to be in force, as such I would think that any `SNAPSHOT` (and certainly CD/incrementals based snapshot `999999-SNAPSHOT` version) older than 2 weeks could be culled.

**Comment by timja** [comment]
incrementals are sometimes used for a lot longer than 2 weeks, but yes SNAPSHOTS generally aren't needed for long

**Comment by timja** [comment]
Verified renovate handles this just fine: https://github.com/timja-org/jenkins/pull/6

**Comment by timja** [comment]
Raised a renovate switch PR for discussion: https://github.com/jenkinsci/jenkins/pull/9459

**Comment by basil** [comment]
> Assuming the snapshots in https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/main/remoting/999999-SNAPSHOT/ are no longer needed for testing, can we delete them from the server as a workaround for https://github.com/jenkins-infra/helpdesk/issues/3919?

Any update on this ticket? I do not see any reason for us not to implement the workaround I described above, especially given that we have been unable to achieve a migration to Renovate.

**Comment by timja** [comment]
(FWIW renovate issues are resolved and that can proceed not that it blocks removing this: https://github.com/jenkinsci/jenkins/pull/9459)

**Comment by dduportal** [comment]
> > Assuming the snapshots in https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/main/remoting/999999-SNAPSHOT/ are no longer needed for testing, can we delete them from the server as a workaround for #3919?
> 
> Any update on this ticket? I do not see any reason for us not to implement the workaround I described above, especially given that we have been unable to achieve a migration to Renovate.

Starting deletion of the artifact. I'll keep a copy of them in case we need to rollback.

**Comment by dduportal** [comment]
> > > Assuming the snapshots in https://repo.jenkins-ci.org/artifactory/snapshots/org/jenkins-ci/main/remoting/999999-SNAPSHOT/ are no longer needed for testing, can we delete them from the server as a workaround for #3919?
> > 
> > 
> > Any update on this ticket? I do not see any reason for us not to implement the workaround I described above, especially given that we have been unable to achieve a migration to Renovate.
> 
> Starting deletion of the artifact. I'll keep a copy of them in case we need to rollback.

@basil artifact deleted: can you confirm it is ok on your side?

**Comment by basil** [comment]
https://github.com/jenkinsci/jenkins/pull/9448 was closed as expected. Thanks!
