### ISSUE TITLE
mr

### ISSUE THREAD

**Issue by kayodebello** [jenkins-infra/helpdesk#4174]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### Summary

username or password not correct.  

### jenkins.io account username

kayode

### jenkins.io account email

kayafeez@gmail.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/login

**Comment by dduportal** [comment]
Hi @kayodebello , there are no jenkins.io accounts with this username or email.

- If you meant an account to access a Jenkins controller, please check with your administrator as accounts.jenkins.io is **only** for user of `*.jenkins.io` websites, not for your organization (or personal) Jenkins controller.
- If you really meant an account for `*.jenkins.io` websites, then you have to create on as you don't have any.

=> I'm closing as there are no action required for the Jenkins infra team.
