### ISSUE TITLE
[cert.ci] adding myself @smerle33 as administrator on cert.ci

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4184]
as per https://github.com/jenkins-infra/helpdesk/issues/4169
I would need admin access to make sure that my changes are ok, and not breaking anything.

Stéphane

**Comment by smerle33** [comment]
thanks @dduportal

**Comment by dduportal** [comment]
For info: added manually in cert.ci's Manage Jenkins -> Security , in the "Matrix auth" section:

<img width="1234" alt="Capture d’écran 2024-07-18 à 08 51 28" src="https://github.com/user-attachments/assets/9c9ecaf1-4cb8-4b3b-942f-7d7b85dbbf29">
