### ISSUE TITLE
I'm blocked sign-in by anti-system, please approve my account.

### ISSUE THREAD

**Issue by bemabema** [jenkins-infra/helpdesk#4185]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I use Jenkins 2.452.3 with Atlassian Jira Software Cloud plugin 2.0.15.
I would like to sign-in because I want to report problem that I am unable to save settings for connect to JIRA due to an error.

### jenkins.io account username

****

### jenkins.io account email

***

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @bemabema , without any information from you, we cannot check the reason of you being blocked.

- Which username or email did you use to register?
- When did you try (exactly so we can search in our logs)?
- What was the exact message (copy and paste it or screenshot)?


Usually, the antispam system is triggered either:
- if your public IP is on the deny list
- or if you are trying to create multiple accounts (or use an account and create a new one) in the same web browser session

**Comment by dduportal** [comment]
Closing as no answer back from requester
