### ISSUE TITLE
[cert.ci.jenkins.io] Jobs failing with `TransportException: github.com:443 failed to respond` when using `git` pipeline step with JGit tool

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4186]
### Service(s)

cert.ci.jenkins.io

### Summary

As reported by @daniel-beck, since the 13th July, jobs on cert.ci.jenkins.io are failing to clone private repositories with the pipeline step `git`.

We see the following error:

```
hudson.plugins.git.GitException: org.eclipse.jgit.api.errors.TransportException: github.com:443 failed to respond
```

**Comment by dduportal** [comment]
Update: We see no problems on the Azure Portal:

- VMs do not report any network issues (no dropped packets, no network slowness, no errors at all, no CPU non user usage )
- The [NAT gateway used by the cert.ci.jenkins.io ephemeral agents](https://github.com/jenkins-infra/azure-net/blob/98b86c31ebc074ea016d2a12cff911f4a2b55909/gateways.tf#L17-L30) does not report any dropped packet or any health issues

As a matter of principles, we are adding a second outbound IP for this gateway in order to spread the outbound requests

**Comment by dduportal** [comment]
Update: the second outbound IP was added in https://github.com/jenkins-infra/azure-net/pull/275 but did not resolve the issue.

**Comment by daniel-beck** [comment]
> since the 13th July

Specifically in a single pipeline that I started using then. It didn't happen in other pipelines.

**Comment by dduportal** [comment]
Update: after replaying pipelines in cert.ci.jenkins.io, we were able to immediately reproduce the issue with a single `git` step.
However, the issue does not happen when using `curl` to the `github.com` domain and does not happen either when using the `git` CLI.

After a quick check, we have manually changed the default Jenkins tool for `git` to use the native `git` CLI (installed on agent and controller `PATH`s)  instead of JGit: it looks like it's solving the issue.

=> next step is to persist this setting on cert.ci.

**Comment by dduportal** [comment]
Update: setting (git native tool) persisted by https://github.com/jenkins-infra/jenkins-infra/pull/3528 with success

**Comment by MarkEWaite** [comment]
I'm also fine if we switch to use command line git everywhere.  Command line git performs much better for large repositories (like Jenkins core and Jenkins documentation).  JGit performs better for small repositories (like most plugins).

I believe that our activity on ci.jenkins.io is more related to large repositories (core and jenkins.io), than to small repositories and the difference between CLI git and JGit on small repositories is a matter of seconds, not minutes.

**Comment by MarkEWaite** [comment]
I am interested to better understand why JGit is unable to fetch from a private repository using HTTPS when command line git is able to consistently fetch from the same repository.    I created a JGit based parallel declarative Pipeline job on my installation with 8 different parallel branches that were all using JGit to clone a private repository.  I didn't see the issue.  However, the repository was a smaller repository (less than 100 MB).  If more details are available on the failure mode, it would be good to collect them for later review.

**Comment by dduportal** [comment]
Update: as discussed during the team meeting, we would want to set up the Git Jenkins tool to have the native `git` CLI as first (and default) and add JGit as secondary (fallback) as per @MarkEWaite advise.

**Comment by dduportal** [comment]
All of our controllers are now configured to use the `git` native CLI by default and JGit as a fallback.

**Comment by MarkEWaite** [comment]
> All of our controllers are now configured to use the `git` native CLI by default and JGit as a fallback.

The [ci.jenkins.io tool configuration](https://ci.jenkins.io/manage/configureTools/) seems to still list only JGit and not command line git.  Is that expected while we evaluate it on other CI servers?

**Comment by dduportal** [comment]
> > All of our controllers are now configured to use the `git` native CLI by default and JGit as a fallback.
> 
> The [ci.jenkins.io tool configuration](https://ci.jenkins.io/manage/configureTools/) seems to still list only JGit and not command line git. Is that expected while we evaluate it on other CI servers?

It should be fixed. It's weird: JCasc triggered a reload but ci.jenkins.io's memory and disk wern't up to date (XML files).
I've triggered a manual JCasc reload: the tool configuration is now up to date
