### ISSUE TITLE
Windows agents stopped allocating on ci.jenkins.io Monday about 02:30 AM UTC

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4188]
### Service(s)

ci.jenkins.io

### Summary

I launched several dependabot pull requests at about 02:00 AM UTC Monday 22 Jul 2024

Pull requests included in that set included:

* https://github.com/jenkinsci/cloud-stats-plugin/pull/128
* https://github.com/jenkinsci/cloud-stats-plugin/pull/128
* https://github.com/jenkinsci/configurationslicing-plugin/pull/269
* https://github.com/jenkinsci/configurationslicing-plugin/pull/268
* https://github.com/jenkinsci/docker-plugin/pull/1088
* https://github.com/jenkinsci/docker-plugin/pull/1089
* https://github.com/jenkinsci/docker-plugin/pull/1090
* https://github.com/jenkinsci/groovy-postbuild-plugin/pull/77
* https://github.com/jenkinsci/groovy-postbuild-plugin/pull/78
* https://github.com/jenkinsci/ivy-plugin/pull/105
* https://github.com/jenkinsci/ivy-plugin/pull/106
* https://github.com/jenkinsci/label-verifier-plugin/pull/28
* https://github.com/jenkinsci/lockable-resources-plugin/pull/684
* https://github.com/jenkinsci/parameterized-trigger-plugin/pull/390
* https://github.com/jenkinsci/parameterized-trigger-plugin/pull/391
* https://github.com/jenkinsci/pre-scm-buildstep-plugin/pull/64

The jobs have completed successfully on Linux but are waiting for a Windows agent with Maven and Java 17.

### Reproduction steps

1. Launched dependabot checks on a set of repositories where I have maintainer permission
2. Saw that some of them completed the pull requests and others did not

**Comment by MarkEWaite** [comment]
The ci.jenkins.io log includes the message:

```
com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000222: The provided client secret keys for app '88b4eee7-e352-4190-be23-48289fb36f78' are expired.
```

**Comment by dduportal** [comment]
Cause: https://github.com/jenkins-infra/helpdesk/issues/4183

I forgot to work on this issue last week and the credential expired.

WiP on it to fix the issue

**Comment by dduportal** [comment]
#4183 has been finished and closed. Agents are being created on ci.jenkins.io and the build queue went from 103 to 36 in the past 5 min. 

Keeping the issue open until
- All the build queue has been processed
- All the PR mentioned in the issue have been built

**Comment by dduportal** [comment]
- Build queue is processed
- All PR mentioned have built successfully
