### ISSUE TITLE
Adding an new mirror in Taiwan

### ISSUE THREAD

**Issue by seadog007** [jenkins-infra/helpdesk#4190]
### Service(s)

mirrors.jenkins.io

### Summary

I am an open source contributor in Taiwan, and I also established the first community based Internet Exchange in Taiwan, and my team and I like to benefit our IX members by hosting OSS Mirrors for them to reduce their bandwidth cost, that's why I am setting up a new mirror with our team, especially for the mirrors that can automatically used by users form ISPs without special settings.

The IP Address for the mirror is 103.147.22.36, and the FQDN is [mirror.twds.com.tw](http://mirror.twds.com.tw/).
The mirror is in Chief HD IDC in Taipei, Taiwan, which is currently the highest capacity/performance mirror in Taiwan.

- Owners: Taiwan Digital Streaming Co.
- http URL: http://mirror.twds.com.tw/jenkins/ (will be here, once we start syncing it)
- https URL: https://mirror.twds.com.tw/jenkins/
- rsync URL: rsync://mirror.twds.com.tw/jenkins/
- Location: Taipei, Taiwan
- Bandwidth: 80 Gbps
- Sync frequency: every hour
- Admin email: [mirror@twds.tw](mailto:mirror@twds.tw)
- My email: [liheng@twds.tw](mailto:liheng@twds.tw)
- My Telegram: [@seadog007](https://t.me/seadog007)

We will need the upstream rsync URL to initiate the sync, we would like to sync directly from the source if it is possible.

**Comment by timja** [comment]
See details here:
https://github.com/OSSPlanet/OSSPlanet/issues/26

These are mirrors we push to:
rsync://ftp-nyc.osuosl.org/jenkins/ or rsync://ftp-chi.osuosl.org/jenkins/

Or as mentioned in the other issue there may be faster rsync services closer if speed is important for delta updates but those will be mirrors that pull from us

**Comment by seadog007** [comment]
Anyway, we already finish the sync since we got enough bandwidth to do that.
cc @james58899 as well.

**Comment by smerle33** [comment]
this mirror had been added in the mirrorbits for get.jenkins.io.
keep us informed if you have any problem

<img width="2925" alt="Capture d’écran 2024-07-24 à 15 56 03" src="https://github.com/user-attachments/assets/fbfe0544-f95a-48de-8d7a-d44c9fa65362">

**Comment by smerle33** [comment]
Thanks for sponsoring the Jenkins project 🎉
