### ISSUE TITLE
ci.j.io plugin jobs don't trigger on branch scan

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4191]
### Service(s)

ci.jenkins.io

### Summary

https://ci.jenkins.io/job/Plugins/ is configured with the "Suppression strategy" of "For matching branches suppress builds triggered by indexing (continue to honor webhooks)".

As a result, https://ci.jenkins.io/job/Plugins/job/disable-job-button-plugin/job/main/ was created but never triggered a build. In my case I even tried to be clever and integrated JEP-229 enablement into the initial commit, and CD doesn't work without a ci.j.io success status, so this was a release blocker until I (as Jenkins admin) triggered a build manually. The vast majority of maintainers lack the permissions to kick off builds. 

It's unclear why this value is set the way it is. Comments in https://github.com/jenkins-infra/helpdesk/issues/3492 note that it was configured, while earlier advice in https://github.com/jenkins-infra/helpdesk/issues/3474 from Jesse indicates it may prevent a reconfiguration build storm and suggests its use _temporarily_. That was more than a year ago.

**Comment by dduportal** [comment]
Ack, starting reconfiguration

**Comment by dduportal** [comment]
Setting applied, no rescanning :success:

**Comment by dduportal** [comment]
![Uploading Capture d’écran 2024-07-30 à 12.37.57.png…]()

**Comment by timja** [comment]
your screenshot wasn't saved @dduportal not fully clear what's been done here

**Comment by dduportal** [comment]
<img width="1403" alt="Capture d’écran 2024-07-30 à 12 38 50" src="https://github.com/user-attachments/assets/5bed1ba9-d52e-4853-8062-ee6fe0b59356">

**Comment by dduportal** [comment]
> your screenshot wasn't saved @dduportal not fully clear what's been done here

Sorry, GitHub did behave weirdly. So I've set up the "Automatic triggering" of the GH org "Plugins" to suppress nothing has per the above screenshot.
