### ISSUE TITLE
Temurin JDK upgrade July 2024

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4193]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

We have a set of new version of java jdk to upgrade : 

- jdk8 to 8u422-b05 https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u422-b05
- jdk11 to 11.0.24+8 https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.24%2B8
- jdk17 to 17.0.12+7 https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.12%2B7
- jdk21 to 21.0.4+7 https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21.0.4%2B7

- [x] Jenkins controller images will have to publish here the jenkins controller version that will use those new jdk version (see https://github.com/jenkins-infra/helpdesk/issues/4058#issue-2256477963) 
	- Weekly 2.469 (23 July 2024) use the new JDKs 21.0.4+7 and 17.0.12+7 (for infra.ci and weekly.ci controllers)
	- Next LTS 2.452.3 (10 July 2024) is expected to use the new JDKs (for all the other controllers)

the work is prepared by some updatecli PR : 

- [x] Jenkins Tools:

	- https://github.com/jenkins-infra/kubernetes-management/pull/5448
	- https://github.com/jenkins-infra/kubernetes-management/pull/5437
	- https://github.com/jenkins-infra/kubernetes-management/pull/5438
	- https://github.com/jenkins-infra/kubernetes-management/pull/5446
	- https://github.com/jenkins-infra/jenkins-infra/pull/3533
	- https://github.com/jenkins-infra/jenkins-infra/pull/3541
	- https://github.com/jenkins-infra/jenkins-infra/pull/3539
	- https://github.com/jenkins-infra/jenkins-infra/pull/3532

- [x] and we will then be able to remove the exception concerning jdk21 for s390X here https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/controller.sponsorship.ci.jenkins.io.yaml#L98-L99 as the new version is available for it https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.4%2B7/OpenJDK21U-debugimage_s390x_linux_hotspot_21.0.4_7.tar.gz
    - https://github.com/jenkins-infra/jenkins-infra/pull/3542 

- [x] packer-images: 

	- https://github.com/jenkins-infra/packer-images/pull/1296
	- https://github.com/jenkins-infra/packer-images/pull/1291
	- https://github.com/jenkins-infra/packer-images/pull/1292
	- https://github.com/jenkins-infra/packer-images/pull/1295

	- [x]  follow the release and deployment of the new packer image !
		- [x] https://github.com/jenkins-infra/kubernetes-management/pull/5462
		- [x] https://github.com/jenkins-infra/jenkins-infra/pull/3544

- [ ] s390x:

	- manually upgrade as it is not yet ascode (pair @dduportal and @jayfranco999 to prepare incorporation to ansible)

- [x] [Windows Container agent](https://github.com/jenkins-infra/docker-inbound-agents)
      - JDK8: https://github.com/jenkins-infra/docker-inbound-agents/pull/179
      - JDK11: https://github.com/jenkins-infra/docker-inbound-agents/pull/176
      - JDK17: https://github.com/jenkins-infra/docker-inbound-agents/pull/177
      - JDK21: https://github.com/jenkins-infra/docker-inbound-agents/pull/178
      - Deployment: https://github.com/jenkins-infra/jenkins-infra/pull/3543
  - [x] ~~[Web-builder aka. "docker-builder"](https://github.com/jenkins-infra/docker-builder)~~ depends now directly of the jdk whithin `jenkins-inbound-agent version` : FROM jenkins/inbound-agent:${JENKINS_INBOUND_AGENT_VERSION}-jdk17
  - [x] [Packaging aka. "docker-packaging"](https://github.com/jenkins-infra/docker-packaging) - https://github.com/jenkins-infra/docker-packaging/pull/131 - https://github.com/jenkins-infra/docker-packaging/releases/tag/5.1.11

**Comment by smerle33** [comment]
next steps:

- Next LTS 2.452.3 (10 July 2024)
- s390x manually with @dduportal and @jayfranco999

**Comment by dduportal** [comment]
Update: we've upgraded JDKs in the s390x machine. 

For info @MarkEWaite we did the following changes:

- Installed the latest JDK11, JDK17 and JDK21 from Temurin for `s390x` in `/opt/jdk-*`
  - Restarted the agent on ci.jio to ensure `/opt/jdk-17` is used with latest version. Success:

  <img width="759" alt="Capture d’écran 2024-08-07 à 15 30 52" src="https://github.com/user-attachments/assets/b8916baa-ad30-4ed0-870f-7a472b019539">

  - We also set up these 3 java installations as the only `update-alternatives` for `/usr/bin/java` symlink with 21 as default
  - Removed the OpenJDK 11 package but kept the OpenJDK 17 package (as a LOT of other packages depends on it)

- Removed all the `jdk-*/` directories from `/home/jenkins/tools/` and replaced with symlink to their `/opt/jdk-*` counterpart to avoid duplication
