### ISSUE TITLE
Install most recent JUnit plugin on ci.jenkins.io and friends

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4197]
### Service(s)

ci.jenkins.io

### Summary

The most recent release of the JUnit plugin includes significant performance and usability improvements from @mdealer as part of pull request:

* https://github.com/jenkinsci/junit-plugin/issues/625

Let's update ci.jenkins.io to use that version of the plugin so that we can see it with the Jenkins core test results and with plugins that generate many test results.

### Reproduction steps

1. Confirm that the most recent JUnit plugin release is installed on ci.jenkins.io and other Jenkins controllers managed by the Jenkins infrastructure team

**Comment by dduportal** [comment]
Installed on ci.jenkins.io, cert.ci and trusted.ci.

The other controllers will be updated next week as part of the usual image updates

**Comment by dduportal** [comment]
All controllers have the Junit plugin 👍
