### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by hutson** [jenkins-infra/helpdesk#4199]
### Type(s) of account issue

I want my account to be deleted

### Summary

Please delete my unused account - https://issues.jenkins.io/secure/ViewProfile.jspa?name=hbetts

### jenkins.io account username

hbetts

### jenkins.io account email

It's in the account settings.

### Which URL are you trying to login at?

N/A

**Comment by hutson** [comment]
> Take a look at these similar issues to see if there isn't already a response to your problem

The `I want my account to be deleted` issue type might not be an effective place to incorporate a bot.

**Comment by MarkEWaite** [comment]
I've sent an email to the address associated with the 'hbetts' account on jenkins.io.  Once the response to that email is received, we'll delete the 'hbetts' account.

**Comment by MarkEWaite** [comment]
Account deleted.
