### ISSUE TITLE
Delete users 'samuel898' and 'krina234pestro' and their comments

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#4200]
### Service(s)

Jira, LDAP

### Summary

These are spam/ad bots:
- https://issues.jenkins.io/secure/ViewProfile.jspa?name=samuel898
- https://issues.jenkins.io/secure/ViewProfile.jspa?name=krina234pestro

**Comment by MarkEWaite** [comment]
Users are now blocked.
