### ISSUE TITLE
VPN access to usage.jenkins.io for usage stats generation

### ISSUE THREAD

**Issue by abayer** [jenkins-infra/helpdesk#4202]
### Service(s)

VPN

### Summary

So we still haven't gotten around to moving the monthly usage stats generation off of my desktop (we should do that some day... heh.), meaning that I still need to rsync over ssh into usage.jenkins.io to download the anonymized data to then run https://github.com/jenkins-infra/jenkins-usage-stats against it. My ssh key is configured and all that, but with the change to exposure of ssh ports, I now need VPN access. =) I'm opening the PR against docker-openvpn now as well. Thanks!

**Comment by dduportal** [comment]
Hello @abayer , you can continue following instructions at https://github.com/jenkins-infra/docker-openvpn?tab=readme-ov-file#howto-get-client-access to set up your OpenVPN client.

Once VPN is connected, then you should be able to SSH to usage.jenkins.io.

**Comment by dduportal** [comment]
- Got a confirmation by @abayer that it work for him, thanks!
- Side note: it looks like @kohsuke 's machine would need an exception as there are no usage updates since 24th July
