### ISSUE TITLE
Recent contributor spotlight change is not deployed

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4207]
### Service(s)

contributors.jenkins.io

### Summary

The contributor spotlight for Darin Pope was merged about 18 hours ago but is not visible on https://contributors.jenkins.io

### Reproduction steps

1. Refer to [comments](https://github.com/jenkins-infra/contributor-spotlight/pull/166#issuecomment-2260095789) in the merge pull request at 
    * https://github.com/jenkins-infra/contributor-spotlight/pull/166

Maybe the deployment job failed?

**Comment by dduportal** [comment]
As pointed out by Hervé in , the main build failed: https://infra.ci.jenkins.io/job/website-jobs/job/contributor-spotlight/job/main/148/pipeline-console/?selected-node=25

during the ["Install Dependencies" stage]() with the following error in the `asdf install npm install` step:


```
17:12:07  error: failed to download node-v20.15.0-linux-arm64.tar.gz
17:12:07  
17:12:07  BUILD FAILED (Ubuntu 22.04 using node-build 5.3.6-5-g070006d7)
17:12:07  
17:12:07  Binary installation failed; try compiling from source with `--compile` flag
17:12:07  
17:12:07  Inspect or clean up the working tree at /tmp/node-build.20240730150950.2040.xbzQaP
17:12:07  Results logged to /tmp/node-build.20240730150950.2040.log
17:12:07  
17:12:07  Last 10 log lines:
17:12:07  cache-control: public, max-age=3600, s-maxage=14400
17:12:07  cf-cache-status: EXPIRED
17:12:07  accept-ranges: bytes
17:12:07  strict-transport-security: max-age=31536000; includeSubDomains; preload
17:12:07  x-content-type-options: nosniff
17:12:07  server: cloudflare
17:12:07  cf-ray: 8ab645a8bdac20d1-IAD
17:12:07  
17:12:07  curl: (22) The requested URL returned error: 522
17:12:07  curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by dduportal** [comment]
New build triggered, I'm watching it

**Comment by dduportal** [comment]
- Merging https://github.com/jenkins-infra/contributor-spotlight/pull/169#pullrequestreview-2209789467 did trigger a successful build
- I had to execute a `curl -XPURGE https://contributors.jenkins.io/` in order to have the homepage updated with @darinpope 's spotlight article
