### ISSUE TITLE
I didnt receive an email

### ISSUE THREAD

**Issue by maguirearman** [jenkins-infra/helpdesk#4208]
### Type(s) of account issue

I didn't receive any email

### Summary

I haven't received any emails with the passwords to the account I just created.

### jenkins.io account username

maguire

### jenkins.io account email

maguire.arman@impower.ai

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @maguirearman , we checked our mail server and we see the last email was delivered to your organization mail server `impower-ai.mail.eo.outlook.com` at 10:02:27 AM today (07/31/24, 10:02:27 AM). The message was acknowledged.

You should either check your spam box or contact your email administrators to see what is going on.

**Comment by dduportal** [comment]
Closing as no answer from the requester
