### ISSUE TITLE
temporarily remove xmission from the mirrors list

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#4211]
### Service(s)

mirrors.jenkins.io

### Summary

https://groups.google.com/g/jenkinsci-users/c/LcNBCRI3mTw/m/-mfC_01oAwAJ

the cert used by [https://mirror.xmission.com](https://mirror.xmission.com/)  has been revoked (according to chrome) and causes download issues for plugins (reported by a user).

As this impacts Jenkins' ability to update / install plugins the mirror should be temporarily removed.

### Reproduction steps

1. start chrome, go to https://mirror.xmission.com
2. expect a valid cert / and some page

instead you get a warning that the cert has been revoked.

![image](https://github.com/user-attachments/assets/6404a47d-e83f-41ec-ab61-43a01889cbea)

in Jenkins this appears to cause plugins to fail to be download (depending on your location and mirror that you get redirected to)

**Comment by dduportal** [comment]
Mirror has been disabled as you can see on https://get.jenkins.io/windows/2.470/jenkins.msi?mirrorlist

![Capture d’écran 2024-08-06 à 15 10 41](https://github.com/user-attachments/assets/d640dc44-1d20-4133-882b-a09a155cfc70)

Many thanks for reporting!

We'll now contact the mirror administrator

**Comment by dduportal** [comment]
Most probably related to https://www.digicert.com/support/certificate-revocation-incident (see https://status.digicert.com/incidents/3sccz3v31lc9).

Thanks @jtnord @daniel-beck

**Comment by dduportal** [comment]
Contacted XMission support tema to let them know, let's wait for the reply.

**Comment by MarkEWaite** [comment]
XMission support replied that the issue is resolved.  Confirmed by opening https://mirror.xmission.com/jenkins/

**Comment by dduportal** [comment]
Aaaaand it's back, many thanks!
