### ISSUE TITLE
Update ci.jenkins.io and its friends to Jenkins 2.462.1

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4214]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

Jenkins 2.462.1 has released and needs to be applied to all the Jenkins controllers in the infrastructure that were previously running 2.452.3

### Reproduction steps

1. Check the version number from the web page after logging in

Release checklist item from:

* https://github.com/jenkins-infra/release/issues/561

**Comment by dduportal** [comment]
- ci.jenkins.io updated as part of the [security advisory](https://www.jenkins.io/security/advisory/2024-08-07/) by the Jensec team
- release.ci.jenkins.io:
  - Automated PR: https://github.com/jenkins-infra/docker-jenkins-lts/pull/898
  - Released image: https://github.com/jenkins-infra/docker-jenkins-lts/releases/tag/1.15.0-2.462.1
  - Production deployment: https://github.com/jenkins-infra/kubernetes-management/pull/5513
 
- Note: I'm removing infra.ci from this issue as it's using the weekly line, not the LTS

**Comment by dduportal** [comment]
release.ci.jio and trusted.ci.jio:

- Automated PR: https://github.com/jenkins-infra/jenkins-infra/pull/3577#pullrequestreview-2225044598
- Deployment in progress, along with plugins updates

**Comment by dduportal** [comment]
All controllers are up to date (Core and plugins). Closing.
