### ISSUE TITLE
Jenkins Account

### ISSUE THREAD

**Issue by bsusrnkn** [jenkins-infra/helpdesk#4227]

**Comment by dduportal** [comment]
Hi @bsusrnkn , could you help us by explaining what usage do you want to have with your jenkins.io account please?

**Comment by bsusrnkn** [comment]
Hello,I will be using my account for my university course projects. I will be working with Docker along with Jenkins.Thank you, Bengisu SerinkenOn 12 Aug 2024, at 12:14, Damien Duportal ***@***.***> wrote:﻿
Hi @bsusrnkn , could you help us by explaining what usage do you want to have with your jenkins.io account please?

**Comment by dduportal** [comment]
> Hello,I will be using my account for my university course projects. I will be working with Docker along with Jenkins.Thank you, Bengisu SerinkenOn 12 Aug 2024, at 12:14, Damien Duportal ***@***.***> wrote:﻿ Hi @bsusrnkn , could you help us by explaining what usage do you want to have with your jenkins.io account please? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Thanks for your answer. It looks like you won't need any account on jenkins.io then as your local Jenkins, running in Docker, will have it own account system. The accounts.jenkins.io is only for the public website issues.jenkins.io which you don't need at all.

Follow the Jenkins installation wizard or the Jenkins documentation if you want to manage your account.

If this account creation is required in your course, please forward this message to your teacher as they will need to update their content as there are no need to create issues.jenkins.io account at all to use Jenkins.
