### ISSUE TITLE
Vandalism in Jira

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4229]
### Service(s)

Jira

### Summary

https://issues.jenkins.io/secure/ViewProfile.jspa?name=chsonu_5 and https://issues.jenkins.io/secure/ViewProfile.jspa?name=bablo_515 took a bunch of actions that should be reverted.

**Comment by dduportal** [comment]
For info: related to https://github.com/jenkins-infra/helpdesk/issues/4224 and https://github.com/jenkins-infra/helpdesk/issues/4223

**Comment by dduportal** [comment]
I've blocked `bablo_515` in  JIRA on short term

**Comment by dduportal** [comment]
For info, since @MarkEWaite did enable the circuit breaker, we've had some GH helpdesk issues asking for account confirmation:

- https://github.com/jenkins-infra/helpdesk/issues/4230
- https://github.com/jenkins-infra/helpdesk/issues/4227

**Comment by dduportal** [comment]
@daniel-beck I don't know how to revert changes in JIRA. Do we have prior runbook or something?

Last "big set of unwanted changes", we reverted to a previous backup which made us lost days of legit changes. If we have to do this know, I would rather do it quickly. WDYT?

**Comment by dduportal** [comment]
I guess it is also a good trigger for https://github.com/jenkins-infra/helpdesk/issues/2232: our accountapp is really weak and easy to batch-create stuff on it.

Switching to another system would help limiting the impact of such things (note: it would NOT prevent a user to deface JIRA)

**Comment by MarkEWaite** [comment]
I reverted the "close" actions of those two spammers by reopening each of the issues that were closed.  I did not attempt to undo the other actions because they seemed too small to be worth the time to interactively repair the damage.

**Comment by daniel-beck** [comment]
> I don't know how to revert changes in JIRA. Do we have prior runbook or something?

I don't think anything convenient exists. I'd look at the changes, do the opposite.

**Comment by mawinter69** [comment]
What I noticed is that the users `bablo_515`, `chsonu_512` and `chsonu_5` have the same email `sayyedabrash110202@gmail.com`.
Is there a way to block users based on email?

**Comment by timja** [comment]
> Is there a way to block users based on email?
there's a hardcoded list, 👉  https://github.com/jenkins-infra/account-app/pull/397

**Comment by dduportal** [comment]
Are there more actions required on this one?

**Comment by MarkEWaite** [comment]
I'm not aware of any further actions that are needed.  I will continue to monitor Jira for issue spam and will block users that are detected creating spam comments and spam changes.

**Comment by dduportal** [comment]
Thanks! I'm closing the issue then.
