### ISSUE TITLE
I've been blocked

### ISSUE THREAD

**Issue by zhaoweijie1213** [jenkins-infra/helpdesk#4230]
### Type(s) of account issue

I've been blocked by the anti-spam system

### jenkins.io account username

zhaoweijie1108

### jenkins.io account email

zhaoweijie1108@qq.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @zhaoweijie1213 , could you describe the reasons you want to use the Jenkins.io account for?

**Comment by zhaoweijie1213** [comment]
Having a Jenkins.io account allows me to engage with the Jenkins community, participate in forums, contribute to discussions, and share my knowledge and experiences.
&nbsp;


赵伟杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Damien ***@***.***&gt;; 
发送时间: 2024年8月12日(星期一) 下午5:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jenkins-infra/helpdesk] I&#39;ve been blocked (Issue #4230)














 
Hi @zhaoweijie1213 , could you describe the reasons you want to use the Jenkins.io account for?

**Comment by dduportal** [comment]
Hi @zhaoweijie1213 , thanks fro your answer and your willingness to help!

It looks like an account is not required on accounts.jenkins.io: you might want to check the community forum https://community.jenkins.io/ which uses different user accounts (that you may link with your GitHub account for instance).
