### ISSUE TITLE
jenkins pip脚本问题

### ISSUE THREAD

**Issue by liuq95** [jenkins-infra/helpdesk#4231]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

agent执行命令无权限
![image](https://github.com/user-attachments/assets/e8fc8a32-9b2f-49a6-9ce3-d0ff3e8bb769)

### jenkins.io account username

liuq

### jenkins.io account email

870874834@qq.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @liuq95 this issue tracker is only for the `*.jenkins.io` websites. It appears your request is about your own Jenkins controller: please check with your administrators to retrieve your access on it as it is *unrelated* to the Jenkins public infrastructure.

If you need to ask for help, please check community.jenkins.io forums.
