### ISSUE TITLE
Cannot signup in jenkins

### ISSUE THREAD

**Issue by patdhaval30** [jenkins-infra/helpdesk#4235]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

Username: patdhaval30
email: dhaval.patange@perforce.com
IT tells me that i cannot login as it looks like a bot.
Please create the jenkins account for me with details above.

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @patdhaval30 , this issue tracker is not for organization Jenkins instances.

It's only for the `*.jenkins.io` websites. May I ask you where did you get the link to accounts.jenkins.io so we can understand better why users are mistakenly trying? Or can you detail what is the usage you plan to have with the account here?

**Comment by patdhaval30** [comment]
Hi Damien,

I am accountable for P4 plugin from Perforce.
I would like to comment about latest status of various issues for the
plugin and talk to users.
So I need to login and need to comment on issues raised by users.
Username request: patdhaval30
email: ***@***.***
plugin page: https://plugins.jenkins.io/p4/

Regards,
Dhaval Patange

**Comment by MarkEWaite** [comment]
Thanks @patdhaval30 .  The temporary block on account creation has been lifted.  You should be able to register your new account now.  We've had problems with issue spam in the Jenkins issue tracker and needed to pause account registrations.

**Comment by dduportal** [comment]
Closing as the account is created. Thanks for the feedback @patdhaval30
