### ISSUE TITLE
[accounts.jenkins.io] Decrease Google indexing

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4238]
### Service(s)

Accounts

### Summary

While dealing with https://github.com/jenkins-infra/helpdesk/issues/4229, and with the week-to-week support tasks, it seems we have a lot of users landing on accounts.jenkins.io while they do not need it.

This issue is about removing some unneeded references to accounts.jenkins.io to decrease this amount of (unneeded) request

- https://www.google.com/search?client=firefox-b-d&q=jenkins+account shows the page https://wiki.jenkins-ci.org/JENKINS/User-Account-on-Jenkins.html is 3rd. 
- Updating the homepage https://accounts.jenkins.io/login and the registration page https://accounts.jenkins.io/signup to tell users that their own Jenkins instance is not requiring an account on it

**Comment by dduportal** [comment]
Update: gotta add the meta markup with both noindex and nofollow on the 2 pages for accounts.jenkins.io, along with the accounts.jenkins.io homepage itself (ref. https://developers.google.com/search/docs/crawling-indexing/block-indexing)

**Comment by dduportal** [comment]
So Google seems not to care at all about meta markup despite their documentation. Yay.

The research https://www.google.com/search?client=firefox-b-d&q=jenkins+account still shows the page https://wiki.jenkins-ci.org/JENKINS/User-Account-on-Jenkins.html is 3rd...

Nuclear option it is: let's add robots.txt

**Comment by timja** [comment]
you might need to remove it from the index first from the search console.

**Comment by dduportal** [comment]
> you might need to remove it from the index first from the search console.

I have no idea what the "search console" is 😅 Is it a tool we have somewhere?

**Comment by timja** [comment]
https://search.google.com/search-console/removals?utm_medium=referral&utm_campaign=1663419

https://support.google.com/webmasters/answer/9689846?sjid=4561833217325990675-EU

**Comment by timja** [comment]
I have access to these two:
![image](https://github.com/user-attachments/assets/bab14be6-cad3-4785-ac59-bbb3c0ec14bd)

but not the wiki, you'll probably have to verify yourself by adding a DNS record and then that will get you access

**Comment by dduportal** [comment]
Oh, I see. Thanks for the pointers (never had to put my hand in this Google stuff). Gotta check then!

**Comment by dduportal** [comment]
Thanks @timja !

- I was able to access the COnsole and set up a `TXT` record as expected (in the `public.publik8s.jenkins.io` due to CNAMEs)
- Confirmed that asking Google to re-index the page fails due to the metas
- Requested the page index removal for https://wiki.jenkins-ci.org/JENKINS/User-Account-on-Jenkins.html

**Comment by dduportal** [comment]
Also did the same for the whole accounts.jenkins.io

**Comment by dduportal** [comment]
YAS no more indexing \o/
