### ISSUE TITLE
Missing dynamic update center for 2.452.4

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#4245]
### Service(s)

Update center

### Summary

See https://matrix.to/#/!ouJVNKRtaWHFflDvBW:gitter.im/$X0BuZdxquHJOJJzSGhStIZVZ5ocQQjVHmFaGK0iAw2Y?via=gitter.im&via=matrix.org&via=sys.reslate.net

> Hello! I noticed that the update site for LTS 2.452.4 hasn't been created. I guess this is due to the new UI overhaul LTS version 2.462.1 being released on the same day. I can also see that the update site for 2.462.1 as well as all the other 2.452 versions are available. This is the one that is missing: https://updates.jenkins.io/dynamic-stable-2.452.4/update-center.json 
Is there a chance that the missing page above could be added?
Thanks in advance,
Tomas

**Comment by dduportal** [comment]
I though we were expected to use the `https://updates.jenkins.io/update-center.json?version=2.452.4` URL (as per https://updates.jenkins.io/#version-specific-update-sites)?

(yes this URL redirects to https://updates.jenkins.io/dynamic-stable-2.452.3/update-center.json but is it an issue or is it the expected behavior?)

**Comment by timja** [comment]
yes you are expected to use that. 

> but is it an issue or is it the expected behavior?

Not 100% sure but I thought all the LTS versions going back x time would have an update center, although maybe it depends on a plugin being published that relies on that release.

**Comment by dduportal** [comment]
> yes you are expected to use that.
> 
> > but is it an issue or is it the expected behavior?
> 
> Not 100% sure but I thought all the LTS versions going back x time would have an update center, although maybe it depends on a plugin being published that relies on that release.

I though the dynamic UC was generated only if plugins were published with the constrained version?

**Comment by timja** [comment]
Ah I think thats right. So if a plugin depends on that version which is likely enough to happen soon as its now the recommended baseline: https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/

Then it will be created

**Comment by daniel-beck** [comment]
Previously: https://github.com/jenkins-infra/helpdesk/issues/3550#issuecomment-1568913463
