### ISSUE TITLE
Delete link https://issues.jenkins.io/browse/JENKINS-64860

### ISSUE THREAD

**Issue by yassinekerke** [jenkins-infra/helpdesk#4247]
### Service(s)

Helpdesk

### Summary

Hello,
 
The oddo bhf security team contact me to remove this  links from  support jenkins support jira  
 
https://issues.jenkins.io/browse/JENKINS-64860 
 
can you delete it  ?
 
Thanks
 

### Reproduction steps

Hello,
 
The oddo bhf security team contact me to remove this  links from  support jenkins support jira  
 
https://issues.jenkins.io/browse/JENKINS-64860 
 
can you delete it  ?
 
Thanks

**Comment by timja** [comment]
I've deleted the issue
