### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by fasmat** [jenkins-infra/helpdesk#4257]
### Type(s) of account issue

I want my account to be deleted

### Summary

I want to delete my `accounts.jenkins.io` account

### jenkins.io account username

fasmat

### Which URL are you trying to login at?

account.jenkins.io

**Comment by dduportal** [comment]
Hi @fasmat , I've sent a mail to the email address of the account to be deleted.

Can you check it please? The goal is to confirm you are the rightful owner of the account.

**Comment by fasmat** [comment]
> Hi @fasmat , I've sent a mail to the email address of the account to be deleted.
> 
> Can you check it please? The goal is to confirm you are the rightful owner of the account.

Yes, thank you. I responded to your email.

**Comment by dduportal** [comment]
Thanks! 

Your account has been deleted.
