### ISSUE TITLE
Adding GSoC project to jenkins-infra

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#4260]
### Service(s)

Helpdesk

### Summary

For the Jenkins project we would like to add the code project [Enhancing an Existing LLM Model with Domain-specific Jenkins Knowledge](https://www.jenkins.io/projects/gsoc/2024/projects/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge/) to under the `jenkins-infra` GitHub organization if possible: https://github.com/nouralmulhem/Enhancing-LLM-with-Jenkins-Knowledge.

**Comment by krisstern** [comment]
c.c. @nouralmulhem @gounthar @harsh-ps-2003 @shivaylamba

**Comment by timja** [comment]
What is the reasoning for Jenkins Infra instead of Jenkinsci for this?

**Comment by krisstern** [comment]
@timja Actually either `jenkins-infra` or `jenkinsci` would be fine.

**Comment by dduportal** [comment]
As per @timja explanation in https://github.com/jenkins-infra/helpdesk/issues/4262#issuecomment-2308948354, the "destination" (e.g. `jenkinsci` or `jenkins-infra` GH org) is decided based on the users of the project.

Is this project used by Jenkins users directly? Or is it used by the Jenkins Infra to provide a service to Jenkins contributors or users?

**Comment by gounthar** [comment]
It would be used by Jenkins contributors, to modernize the plugins they maintain or any other plugin. 🤔 
I guess anyone could run it on their laptop, but I hope we'll have a service one day in the infra that would run it regularly on a curated list of plugins.

**Comment by dduportal** [comment]
> It would be used by Jenkins contributors, to modernize the plugins they maintain or any other plugin. 🤔 I guess anyone could run it on their laptop, but I hope we'll have a service one day in the infra that would run it regularly on a curated list of plugins.

I think you are describing the « modernizer plugin » project described in https://github.com/jenkins-infra/helpdesk/issues/4262 : am I correct?

**Comment by gounthar** [comment]
Yes, you're right, time to go to bed for me I guess! 😛

**Comment by dduportal** [comment]
As per the explanations I had from @gounthar , it looks like this project could (if finished and successful and a other criteria) lead to an infra service.

The code in https://github.com/nouralmulhem/Enhancing-LLM-with-Jenkins-Knowledge is expected to produce artifacts/data consumed by the Jenkins Infra.

=> as such, `jenkins-infra` looks like the proper organization to host the code

**Comment by dduportal** [comment]
Hello folks, we have delayed any work on this task to mid-October as the infra team will be in limited availability

**Comment by dduportal** [comment]
Hello @krisstern : the repository can safely be transferred to the `jenkins-infra` GitHub architecture. Let us know when the transfer request is emitted, we'll update the status here.

**Comment by krisstern** [comment]
Hi @dduportal, thanks for the update! Should I direclty copy the repo to one under `jenkins-infra`, would that be sufficient?

**Comment by dduportal** [comment]
> Hi @dduportal, thanks for the update! Should I direclty copy the repo to one under `jenkins-infra`, would that be sufficient?

I would suggest to proceed with a transfer so the whole repository history would be carried (issues, PRs, commits, etc.).
Of course, if the user does not want, then yes, we can do what you propose using https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository so the commit history would be kept (at least)

**Comment by krisstern** [comment]
Hi @dduportal I have completed the transfer of the repository to https://github.com/jenkins-infra/Enhancing-LLM-with-Jenkins-Knowledge. Please check to see if everything is in-place. Do let me know if there is anything else I will need to do. And please if possible make @nouralmulhem @gounthar @harsh-ps-2003 @shivaylamba and @krisstern (me) maintainers of the repo. Thanks for your help!

**Comment by dduportal** [comment]
Thanks @krisstern !

Nothing more on my side:

- The gsoc team of jenkins-infra (including you and Bruno) is now admin of the repo, along with the Core team
- @nouralmulhem @harsh-ps-2003 and @shivaylamba have been invited (they have to accept the invitation in their mail box) as maintainers

**Comment by krisstern** [comment]
That's good to know @dduportal! Appreciate your support on this issue
