### ISSUE TITLE
Requesting VPN access for admin privileges on Jenkins-infra

### ISSUE THREAD

**Issue by jayfranco999** [jenkins-infra/helpdesk#4273]
### Service(s)

VPN

### Summary

Since I'll need admin privileges for the upcoming triage tasks I will need to access the Jenkins infra.

**Comment by dduportal** [comment]
Maybe not admin privileges yet :D But VPN access to infra.ci is needed for you to work on https://github.com/jenkins-infra/helpdesk/issues/4124 and the https://github.com/jenkins-infra/packer-images repository ;)

**Comment by dduportal** [comment]
Jay confirmed he has access to infra.ci 👍
