### ISSUE TITLE
Changing owners of LoadNinja Jeknins Plugin

### ISSUE THREAD

**Issue by kordian-smartbear** [jenkins-infra/helpdesk#4279]
### GitHub repositories

https://github.com/jenkinsci/loadninja-plugin

### GitHub users to have permission

GH accounts:
@yamini-sethu
@runkalicious (Matt Runkle)
@loadninja-bot

linked user accounts
[jenkins.io](http://jenkins.io/) accounts:
yamini_sethu
loadninja

### Permission level

Admin

### Justification

User that is set as a dev is no longer in the company.

**Comment by timja** [comment]
Please send a PR to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-loadninja.yml

**Comment by runkalicious** [comment]
@timja This request is for access to the `loadninja-plugin` repository. My understanding is that the `repository-permissions-updater` repository is specifically for permissions to publish plugins and is independent of GitHub. If this is correct, how can we change GitHub access to the `loadninja-plugin` repo?

**Comment by timja** [comment]
we do most of our permissions changes as part of release changes. For limited cases we also do GitHub changes there through an issue template, but this plugin needs adopting so it should go through a pull request there.
