### ISSUE TITLE
[ci.jenkins.io] Ensure our build agents have enough entropy (`rngd`, `haveged`, etc.)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4281]
### Service(s)

ci.jenkins.io

### Summary

As pointed out by @jtnord in https://github.com/jenkinsci/jenkins-test-harness/pull/829#discussion_r1745088729:

> Note for others, the hybrid is a psedo random number that is initially seeded from a strong instance and is regularly reseeded from that instance to maintain strength and prevent any predictability.
This should ensure we do not run out of entropy on VMs, however as it does need the initial seed and some subsequent reseeding that is not gauranteed. (Depending on how often the seeds secure random's source is required.)
in testing a product deployed with this I have not noticed any delays, but if we start seeing timeouts and the SR in the stack trace we would need the infra team to deploy something like [haveged](https://linux.die.net/man/8/haveged) on the nodes (both the VM and k8s node pool nodes). (/cc @dduportal)

In order to increase entropy on our build agents, we have different cases:

- Permanent agents (trusted.ci UC agent, s390x): they should have the `rndg` tools installed https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/manifests/rngd.pp or manually.
  - [ ] Check it's the case
  - [ ] Add haveged on both with service started
- VM Agents (Linux):
  - [x] Add `rndg` tools and `haveged` tools with service enabled (so they start at boot time)
- Container Agents (AKS for ci.jio, infra.ci.jio and release.ci.jio)
  - We are using AKS with managed nodes with Azure Linux OS on the node: https://github.com/jenkins-infra/azure/blob/47e44a47bcd5330dbdffc443eb4b2f5a0c4b398a/ci.jenkins.io-kubernetes-agents.tf#L102-L134
  - There is an (old: 2018) issue for AKS about this: https://github.com/Azure/AKS/issues/219 but it's unclear if it was fixed or not.
  - On the upstream we have this issue: https://github.com/kubernetes/kubernetes/issues/60751 but again unclear
  - [x] Find a way to check if we have enough entropy already with the default Azure Linux managed node
  - [x] If not enough: we have to find a daemon set depoloyment to enabled this on hosts

**Comment by basil** [comment]
https://x.com/bcrow/status/1020032852270825472

**Comment by dduportal** [comment]
Assigning to @jayfranco999 for the scope "Linux ephemeral Azure VM agents"

**Comment by jayfranco999** [comment]
Update: 

packer-images Linux VM agents  have entropy tools `rngd` and `haveged` installed and enabled at boot time. (tested with templates used by ci.jio)

Goss text contract to ensure installation of both tools has also been tested and verified.

Since we are unfamiliar with the installed packages, @jtnord will have to guide us on the steps involved with ensuring our build agents have enough entropy.

pipeline script to ensure entropy tools are installed

```
pipeline {
    agent {
        label 'ubuntu-22-amd64-maven11'
    }

    stages {
        stage('Test Entropy Tools versions') {
            steps {
                sh 'haveged --version'
                sh 'rngd --version'
            }
        }
    }
}

**Comment by jtnord** [comment]
you would only normally run one of either `haveged` or `rngd`.

to check entropyis available (ie the tools are working)
run a pipeline like

```
pipeline {
    agent {
        label 'ubuntu-22-amd64-maven11'
    }
    options {
      timestamps()
    }

    stages {
        stage('Test Entropy Tools versions') {
            steps {
                sh '''
cat /proc/sys/kernel/random/entropy_avail
dd if=/dev/random of=/dev/null bs=1024 count=1024
cat /proc/sys/kernel/random/entropy_avail
'''            }
        }
    }
}
```

**Comment by jayfranco999** [comment]
Thanks @jtnord for the quick reply, I remember testing the entropy locally with a similar method but I wasn't sure if there was a specific amount of available entropy we were trying to achieve with our agents.

@dduportal ran your pipeline and the condition seems to check out, so thanks for the help! :D

```
13:27:06  [Pipeline] stage
13:27:06  [Pipeline] { (Test Entropy Tools versions)
13:27:07  [Pipeline] sh
13:27:07  + cat /proc/sys/kernel/random/entropy_avail
13:27:07  256
13:27:07  + dd if=/dev/random of=/dev/null bs=1024 count=1024
13:27:07  1024+0 records in
13:27:07  1024+0 records out
13:27:07  1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00543408 s, 193 MB/s
13:27:07  + cat /proc/sys/kernel/random/entropy_avail
13:27:07  256
13:27:07  [Pipeline] }
```

**Comment by dduportal** [comment]
Btw: we have the kind of result when using a Linux container agent:

```
18:10:52  + cat /proc/sys/kernel/random/entropy_avail
18:10:52  256
18:10:52  + dd if=/dev/random of=/dev/null bs=1024 count=1024
18:10:52  1024+0 records in
18:10:52  1024+0 records out
18:10:52  1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00489019 s, 214 MB/s
18:10:52  + cat /proc/sys/kernel/random/entropy_avail
18:10:52  256
```

which means:

- The underlying node VMs (AKS 1.29 with Azure Linux) have the required elements set up
- The pod container images have the required tools
🥳

**Comment by dduportal** [comment]
Final step: let's make sure we also have enough entropy on the 2 permanent agents we run:

- s390x on ci.jenkins.io
- `agent-1` on trusted.ci.jenkins.io (`updatecenter` agent)

**Comment by timja** [comment]
https://github.com/jenkins-infra/helpdesk/issues/4281#issuecomment-2363496157 says you would normally only use one tool, why have we installed both?

**Comment by dduportal** [comment]
> [#4281 (comment)](https://github.com/jenkins-infra/helpdesk/issues/4281#issuecomment-2363496157) says you would normally only use one tool, why have we installed both?

Oh good catch! We got carried away and missed this sentence in James' comment. I let @jayfranco999 take the next steps on this.

**Comment by jayfranco999** [comment]
> [#4281 (comment)](https://github.com/jenkins-infra/helpdesk/issues/4281#issuecomment-2363496157) says you would normally only use one tool, why have we installed both?

@timja, yes one tool would suffice for the amount of entropy we're trying to achieve, good catch! Initially we chose haveged in addition to rngd as an additional step to ensure enough entropy. We missed out on James' point due to a lot of context switching. 

Since we already have a profile for the installation of `rngd` for our trusted.ci permanent agent, to maintain feature parity of our agents the next steps would be to remove the installation of `haveged` from packer-images Linux VM agents and the permanent agent s390x.

**Comment by jayfranco999** [comment]
As per https://github.com/jenkins-infra/helpdesk/issues/4281#issuecomment-2381344015

`haveged` has been removed from the s390x permanent agent.

```
root@jenkins01:~# apt remove haveged
The following packages will be REMOVED:
  haveged
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 94.2 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 97278 files and directories currently installed.)
Removing haveged (1.9.14-1ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...

root@jenkins01:~# apt autoremove --purge
The following packages will be REMOVED:
  libhavege2*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 154 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 97270 files and directories currently installed.)
Removing libhavege2:s390x (1.9.14-1ubuntu1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...


root@jenkins01:~# haveged --version
Command 'haveged' not found, but can be installed with:
apt install haveged
