### ISSUE TITLE
Suspicious actions in `jenkinsci` and `jenkins-infra`

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#4282]
### Service(s)

Other

### Summary

A series of first-time contributors attempt to execute (potentially arbitrary?) code on ci.jenkins.io through PRs:
- https://github.com/jenkins-infra/jenkins-io-components/pull/149
- https://github.com/jenkins-infra/repository-permissions-updater/pull/4075
- https://github.com/jenkinsci/jenkins/pull/9705
- https://github.com/jenkinsci/jenkins/pull/9706

For security reasons, I changed the workflow policy for the `jenkinsci` org to require approval for first time contributors, remediating this for now, but the infra org is still a target, as it seems.

**Comment by NotMyFault** [comment]
I put the controller of ci.jenkins.io in shutdown mode for now, until we identified, whether the above is a risk for the infrastructure.
(Apologies to everyone, who wants to start a build on Saturday evening 🥲)

**Comment by timja** [comment]
Another one:
https://github.com/jenkinsci/bom/pull/3553

I've blocked the user from the org and reported to GitHub

**Comment by dduportal** [comment]
> Does anyone have the shell script content?

I don't. But @halkeye did mention (in https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$VtFouyvBry5FLwzxTKME-QSEYB6UQPveuiYqsjAad2g?via=g4v.dev&via=gitter.im&via=matrix.org) it was opening a vscode tunnel (ref. https://www.spyderbat.com/blog/visual-studio-code-remote-tunnel).

**Comment by dduportal** [comment]
Untrusted builds on infra.ci have all been disabled for now: https://github.com/jenkins-infra/kubernetes-management/commit/3d2bfc994b318f68a45ad1ed3fdb5b583e8a0f8d

**Comment by dduportal** [comment]
For info: all of this suspicious activity has been identified as security researchers. Continuing in private until analysis is finished and eventual fixes are applied.
