### ISSUE TITLE
infra-statistics has no new data since July 1st 2024

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#4285]
### Service(s)

Helpdesk, stats.jenkins.io

### Summary

The branch at https://github.com/jenkins-infra/infra-statistics/tree/gh-pages has not been fetching new data for 3 months now it appears.

**Comment by dduportal** [comment]
Ping @kohsuke : it looks like we will need you to create VPN access so your machine can send the statistics with succes

**Comment by dduportal** [comment]
> Ping @kohsuke : it looks like we will need you to create VPN access so your machine can send the statistics with succes

Thanks @timja @kohsuke for https://github.com/jenkins-infra/helpdesk/issues/4299

=> first milestone achieved to solve the infra stats update issue!

**Comment by dduportal** [comment]
Hello @abayer @daniel-beck @olblak , it looks like the pipeline block at https://github.com/jenkins-infra/infra-statistics/blob/8209b583ee5be409d2dc8cdf780bd4358579b8de/Jenkinsfile#L88-L102 is expected to be run on trusted.ci.jenkins.io.

I cannot be sure if it ever existed of if it has been removed (if removed, then most probably by me in the past 2 years, mistakenly).

I'm failing to understand what "process" is filling the branch `gh-pages` of https://github.com/jenkins-infra/infra-statistics once a month.

Could you help me understand better the components at stake here?

**Comment by daniel-beck** [comment]
I poked @abayer about it and he just told me he's updating stats today, he was waiting for KK to fix some stuff.

**Comment by daniel-beck** [comment]
> I cannot be sure if it ever existed of if it has been removed (if removed, then most probably by me in the past 2 years, mistakenly).

I remember an (always offline?) agent called `census` on trusted.ci (https://github.com/jenkins-infra/infra-statistics/blob/8209b583ee5be409d2dc8cdf780bd4358579b8de/Jenkinsfile#L20-L23), but that was cleaned up a while ago, possibly around the time the agents were standardized?

**Comment by dduportal** [comment]
> > I cannot be sure if it ever existed of if it has been removed (if removed, then most probably by me in the past 2 years, mistakenly).
> 
> I remember an (always offline?) agent called `census` on trusted.ci (https://github.com/jenkins-infra/infra-statistics/blob/8209b583ee5be409d2dc8cdf780bd4358579b8de/Jenkinsfile#L20-L23), but that was cleaned up a while ago, possibly around the time the agents were standardized?

🤔 this label still exists on trusted.ci.jenkins.io (ref. https://github.com/jenkins-infra/jenkins-infra/blob/a0db24773372ec6b1fdc0ee0c7186a9ef12ceaab/hieradata/clients/controller.trusted.ci.jenkins.io.yaml#L68-L75)  but not anymore on ci.jenkins.io (ref. https://github.com/jenkins-infra/jenkins-infra/blob/production/hieradata/clients/controller.sponsorship.ci.jenkins.io.yaml).

**Comment by dduportal** [comment]
Update: I'm in contact with @kohsuke and @abayer to finalize the statistics update. There were unexpected technical issues which should be solved soon.

I plan to work with @abayer end of year, to pass knowledge and tools under the Jenkins infra for the KK -> census -> stats processes of the anonimyzed data.

**Comment by dduportal** [comment]
Deferring to mid- November (unless we have news)

**Comment by krisstern** [comment]
Can confirm that new data is being fetched on https://stats.jenkins.io/. Hooray!

**Comment by abayer** [comment]
I should note that the October data is a little wonky at the moment, because the anonymized data used to generate the reports only was through October 29, but I decided that since the October data will get regenerated when we run the report for November, and it's only two days, we'll be fine for now.
