### ISSUE TITLE
Spam at Jenkins Jira

### ISSUE THREAD

**Issue by stefan6419846** [jenkins-infra/helpdesk#4288]
It seems like the following users are just posting spam links:

* https://issues.jenkins.io/secure/ViewProfile.jspa?name=alison569
* https://issues.jenkins.io/secure/ViewProfile.jspa?name=bruce963

(I could not find a way to report these users directly there, thus I decided to open this issue as this seems to have been done previously as well.)

**Comment by dduportal** [comment]
Thanks!

For both users:

- Account removed from LDAP to forbid further connections
- Account disabled in JIRA (unselect the "jira-user" checkbox)
- Their comments had been editer to remove the links (replaced by `<spam>`)
- Then, their comments had been deleted
- User account deleted from JIRA
