### ISSUE TITLE
Не могу зайти в Jenkins

### ISSUE THREAD

**Issue by katarina04071975** [jenkins-infra/helpdesk#4289]
### Type(s) of account issue

I've lost my password

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Please, ask your questions on the Jenkins community forum at community.jenkins.io as this is a general Jenkins support question.

This issue tracker is only for the accounts.jenkins.io which is NOT for Jenkins servers.
