### ISSUE TITLE
Not able to download any plugins in Jenkins

### ISSUE THREAD

**Issue by balbirk** [jenkins-infra/helpdesk#4292]
### Service(s)

jenkins.io

### Summary

I was able to download, configure and run CI CD builds using Jenkins on this machine, but now its not letting me install any plugins.
Tried clean install multiple times but no use.
I came across this post while searching for the cause and wondering if it has something to do with my machine
https://community.jenkins.io/t/failed-to-install-plugins-in-jenkins/12412

I am not too technical, please provide detailed instructions.

### Reproduction steps

Downloaded Jenkins.war file
Created admin user
Tried to install plugins - TestNG and Maven - they have failed multiple times.

Keep getting the error - java.net.UnknownHostException: updates.jenkins-io
I don't have any proxy setup

**Comment by MarkEWaite** [comment]
The Jenkins infrastructure issue tracker is used to report issues with Jenkins global infrastructure.  Help for users and for Jenkins administrators is best requested from https://community.jenkins.io or from the Jenkins user mailing list or from the Jenkins chat channels.

Closing as "not planend"
