### ISSUE TITLE
Grant `jenkins-infra/security` team commit access to `jenkins-infra/release`

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4295]
### GitHub repositories

https://github.com/orgs/jenkins-infra/teams/security

### GitHub users to have permission

https://github.com/orgs/jenkins-infra/teams/security

### Permission level

Write

### Justification

We need to create branches as PR targets when preparing security releases, see [repo readme](https://github.com/jenkins-infra/release/#security), and might need to merge those PRs ourselves.

Right now, @Wadeck and me have permission through https://github.com/orgs/jenkins-infra/teams/release, but security team member @Kevin-CB does not.

Two options:
* Add the team to the repo with Write access, as written above (preferred, I think)
* Add @Kevin-CB to https://github.com/orgs/jenkins-infra/teams/release

CC @timja as release officer and @Wadeck as security officer for review/approval.

**Comment by timja** [comment]
I've added the security team with write access to the repo
