### ISSUE TITLE
VPN access for usage VM

### ISSUE THREAD

**Issue by kohsuke** [jenkins-infra/helpdesk#4299]
### Service(s)

VPN

### Summary

I was instructed by @dduportal to go set up a VPN connection to access usage VM. So I'm following https://github.com/jenkins-infra/docker-openvpn?tab=readme-ov-file#howto-get-client-access and filing a ticket here.

**Comment by timja** [comment]
@kohsuke can you try connect now please?

**Comment by kohsuke** [comment]
Thanks! I got in!
