### ISSUE TITLE
Upgrade Maven to 3.9.6 or newer for GitHub Actions

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#4310]
### Service(s)

GitHub

### Summary

As of https://github.com/jenkinsci/maven-hpi-plugin/pull/668, https://github.com/jenkinsci/pom/pull/612, and https://github.com/jenkinsci/plugin-pom/pull/1018, we require Maven 3.9.6 or newer. As a result, https://github.com/jenkins-infra/github-reusable-workflows/issues/36 and e.g. https://github.com/jenkins-infra/jenkins-security-scan/pull/32 have become blocking issues.

### Reproduction steps

Attempt to do a CD release of `jenkins-test-harness` with the most recent parent POM.

**Comment by MarkEWaite** [comment]
Discussion is happening in the issue:

* https://github.com/jenkins-infra/github-reusable-workflows/issues/36

**Comment by basil** [comment]
Completed in:

- https://github.com/jenkins-infra/github-reusable-workflows/pull/37
- https://github.com/jenkins-infra/jenkins-security-scan/pull/32
