### ISSUE TITLE
[infra.ci.jenkins.io] Credential rotation for deployment of `plugins.jenkins.io` and `docs.jenkins.io`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4323]
The credentials, on infra.ci.jenkins.io, used to deploy the following website to production expires on 17 October 2024:

- https://github.com/jenkins-infra/azure/pull/852
- https://github.com/jenkins-infra/azure/pull/851

I had to revert the last one the time to deal with the arm64 nodepool downtime : https://github.com/jenkins-infra/azure/pull/856

will redo https://github.com/jenkins-infra/azure/pull/851 monday
new PR https://github.com/jenkins-infra/azure/pull/858
private link : https://github.com/jenkins-infra/charts-secrets/commit/9dcc8fbd0aafb5397a0ed442703c2f57180e6eab

test: https://infra.ci.jenkins.io/job/website-jobs/job/docs.jenkins.io/job/main/87/ failure
new test after re-reload jcasc: https://infra.ci.jenkins.io/job/website-jobs/job/docs.jenkins.io/job/main/88/
retry failed again on 89 I had to restart the pod for infra.ci to get the new credential: 
https://infra.ci.jenkins.io/job/website-jobs/job/docs.jenkins.io/job/main/90/

**Comment by smerle33** [comment]
plugin.jenkins.io fileshare SP done: check running on https://infra.ci.jenkins.io/job/website-jobs/job/plugin-site/job/main/2118/
