### ISSUE TITLE
New Docker based Jenkins installation is failing to download plugings

### ISSUE THREAD

**Issue by deesnow** [jenkins-infra/helpdesk#4328]
### Service(s)

pkg.jenkins.io, plugins.jenkins.io

### Summary

Unable to reach jenkinks plugins. Installation script ha timeout to ftp.halifax.rwth-aachen.de
I want to install it on aVM in datacenter. Same time on my PC at home it works well. I read so many same issue, it probably our DC is on blacklist. Could 
Our public ip is: 91.241.11.4

### Reproduction steps

1. I followed installation steps described here https://www.jenkins.io/doc/book/installing/docker/
2. At step create customized docker image with plugins failed, because the plugin source is not reachable.

Creating Jenkins from official docker image is successful, but at the step of installing plugins failed, because of the plugin source not reachable. Logs are full with error like this:

`Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/dark-theme/479.v661b_1b_911c01/dark-theme.hpi to /var/jenkins_home/plugins/dark-theme.jpi.tmp
        at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1334)
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/dark-theme/479.v661b_1b_911c01/dark-theme.hpi (redirected to: https://ftp.halifax.rwth-aachen.de/jenkins/plugins/dark-theme/479.v661b_1b_911c01/dark-theme.hpi)
`

**Comment by MarkEWaite** [comment]
https://github.com/jenkins-infra/helpdesk/issues/4096#issuecomment-2114110094 suggests that you send a mail to [ftp@halifax.rwth-aachen.de](mailto:ftp@halifax.rwth-aachen.de).
