### ISSUE TITLE
Update *.ci.jenkins.io to most recent release (2.462.3, 2.479)

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4329]
### Service(s)

infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

Per the [2.462.3 LTS release checklist](https://github.com/jenkins-infra/release/issues/594), this requests an update the private CI servers to use the most recent release.

Public CI servers ci.jenkins.io and weekly.ci.jenkins.io are already confirmed as up to date.

### Reproduction steps

1. Confirm the private CI servers are running most recent release.

**Comment by pilere** [comment]
infra.jenkins.io is running jenkins 2.479

**Comment by smerle33** [comment]
trusted is running jenkins 2.462.3

**Comment by smerle33** [comment]
release.ci  is running jenkins 2.462.3

**Comment by MarkEWaite** [comment]
Done
