### ISSUE TITLE
Request for GH Personal Access Token for plugin project.

### ISSUE THREAD

**Issue by whitingjr** [jenkins-infra/helpdesk#4333]
### GitHub repositories

Hi, I am requesting permission to create a Personal Access Token on jenkinsci organization. I am a Contributor on the horreum-plugin project and cannot create the PAT.
 I have been tasked with adding a workflow to keep the plugin project and the Horreum project version aligned.
 The workflow needs a PAT to control incoming workflow messages.
 Is it possible I be granted Maintainer permissions necessary to create a PAT or, can a PAT be created for me to use on Horreum project ?  

### GitHub users to have permission

whitingjr

### Permission level

Maintain

### Justification

 Permissions necessary for creating a Personal Access Token.

**Comment by timja** [comment]
(see discussion at https://github.com/jenkinsci/horreum-plugin/pull/23)

I've invited you to the organisation, you already had the maintain permission.

**Comment by whitingjr** [comment]
@timja thank you for adding me to the organization.

**Comment by whitingjr** [comment]
@timja Now that I have been added to the Team for horreum-plugin it does not allow me to create a PAT in the jenkinsci organization. For this request to progress I think I need to ping @jenkinsadmin

**Comment by whitingjr** [comment]
@dduportal The [PR](https://github.com/jenkinsci/horreum-plugin/pull/23/files#diff-f7e99142bc2bfa3c3f1b295fac9b0e4702fd706ef5ba3cae3bac2681513eaa55R3) uses [repository-dispatch](https://github.com/peter-evans/repository-dispatch) and in this situation a remote cross organization dispatch from [Horreum](https://github.com/Hyperfoil/Horreum/). Which [requires a PAT](https://github.com/peter-evans/repository-dispatch#usage) not a regular GITHUB_TOKEN.

**Comment by whitingjr** [comment]
@lemeurherve I'll investigate looking at this and other bots such as dependabot.

**Comment by whitingjr** [comment]
Use of a bot has solved what was needed.
