### ISSUE TITLE
Packer-Images failure on windows 2019 due to ssh-server start failing

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4334]
our builds are failing on windows-2019 because of this : https://learn.microsoft.com/en-us/answers/questions/2100328/openssh-service-fails-to-start-on-azure-provided-w

https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/main/1597/pipeline-console/?start-byte=0&selected-node=162#log-140

**Comment by smerle33** [comment]
the previous windows 2019 image version 
# List available images `az vm image list --location eastus --publisher MicrosoftWindowsServer --offer WindowsServer --sku 2019-datacenter-core-g2 --all --output table`
version: 17763.6293.240905

is working well with sshd ... lets pin the images versions for both windows and we will set an updatecli to check the upgrade.

**Comment by smerle33** [comment]
following https://github.com/jenkins-infra/packer-images/pull/1442 I planned https://github.com/jenkins-infra/packer-images/pull/1443 to keep the versions uptodate but it need more work as `az` seems to need authentication.

**Comment by dduportal** [comment]
Closing this issue as:

- The initial problem is fixed by pinning the version
  - Note: as mentioned by @smerle33 , pinning adds a bit of build time since more Windows Updates must be applied.
- https://github.com/jenkins-infra/packer-images/pull/1443 is opened to track pinned version
