### ISSUE TITLE
ESIC command execution issue

### ISSUE THREAD

**Issue by dilipbangalore** [jenkins-infra/helpdesk#4335]
### Service(s)

Other

### Summary

Hi All, Very Good Morning. I have an issue with Jenkins shell script execution, Could someone please give some inputs to fix the issue.
Recently installed Jenkins 2.462.3 on source server and configure SSH to Remore server..
trying to execute simple shell script it is working without any issues but i would like to automate batch process using ESIC commands causing error as below 
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/test
[SSH] executing pre build script:

[SSH] commands:

#!/bin/bash
/home/ofsaailx/ofsa/reveleus/scheduled/execute/1_OBJECT_[REGISTRATION.sh](http://registration.sh/)

[SSH] executing...
/home/ofsaailx/ofsa/reveleus/ficapp/icc/bin/esic: error while loading shared libraries: [libI18N.so](http://libi18n.so/): cannot open shared object file: No such file or directory
/home/ofsaailx/ofsa/reveleus/ficapp/icc/bin/esic: error while loading shared libraries: [libI18N.so](http://libi18n.so/): cannot open shared object file: No such file or directory
/home/ofsaailx/ofsa/reveleus/ficapp/icc/bin/esic: error while loading shared libraries: [libI18N.so](http://libi18n.so/): cannot open shared object file: No such file or directory
Executing OBJECT_REGISTRATION

[SSH] completed
[SSH] exit-status: 1

Build step 'Execute shell script on remote host using ssh' marked build as failure
[SSH] executing post build script:
shell script contains below 
echo Executing OBJECT_REGISTRATION
/home/ofsaailx/ofsa/reveleus/ficapp/icc/bin/esic -JI -UAPPADMIN -PxMU655ZbemvFH94e6CU1xqAdbLClT1+gGDi46jRopLSl5JKpgPtZkr2NTZ1Zc8Bg -ROBJECT_REGISTRATION_20241010_3 -IOFSAEPM -BOBJECT_REGISTRATION  -D20241010 -F/home/ofsaailx/ofsa/reveleus/ficapp/icc/log/
OUT1=$?

executing ESIC command directly on remote server its working .. from jenkins getting above error

**Comment by MarkEWaite** [comment]
The Jenkins help desk is used to track issues and enhancements related to the infrastructure used by the Jenkins project.  It is not used for questions related to the use of Jenkins.  Please use https://community.jenkins.io or the Jenkins user mailing list or the Jenkins chat channels for questions related to the use of Jenkins.
