### ISSUE TITLE
kubernetes infracijenkinsio-agents-1 arm64 nodepool la64n14agt1 not scaling

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4337]
at 12:52 UTC the arm64 nodepool failed to provide any pods as it's nodes where at 0.

autoscaling was failing:

<img width="2570" alt="Capture d’écran 2024-10-11 à 15 15 38" src="https://github.com/user-attachments/assets/dc0c953f-7ae5-41ae-a308-1601dc270944">

trying to manually scaleup failed also an node image update and a stop/start of the nodepool:
<img width="477" alt="Capture d’écran 2024-10-11 à 15 50 37" src="https://github.com/user-attachments/assets/3e3b84c3-2f4c-4118-998d-0c36fea62350">

even tried a reconcile as hint by the helper: 
<img width="1226" alt="Capture d’écran 2024-10-11 à 16 35 51" src="https://github.com/user-attachments/assets/1151a4c7-7f87-4407-8e28-889d062069b1">
<img width="814" alt="Capture d’écran 2024-10-11 à 16 33 25" src="https://github.com/user-attachments/assets/5b466f7c-f2a9-4579-9837-73ba939a81e6">

also manually:
```
cijenkinsio-agents-1 --name la64n14agt1
(OverconstrainedZonalAllocationRequest) original error: Code="OverconstrainedZonalAllocationRequest" Message="Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - Availability Zone\n  - Differencing (Ephemeral) Disks\n  - Networking Constraints (such as Accelerated Networking or IPv6)\n  - VM Size\n" Target="158". See https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/error-code-zonalallocationfailed-allocationfailed for more details.
Code: OverconstrainedZonalAllocationRequest
Message: original error: Code="OverconstrainedZonalAllocationRequest" Message="Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:\n  - Availability Zone\n  - Differencing (Ephemeral) Disks\n  - Networking Constraints (such as Accelerated Networking or IPv6)\n  - VM Size\n" Target="158". See https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/error-code-zonalallocationfailed-allocationfailed for more details.
Exception Details:      (OverconstrainedZonalAllocationRequest) Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:
          - Availability Zone
          - Differencing (Ephemeral) Disks
          - Networking Constraints (such as Accelerated Networking or IPv6)
          - VM Size

        Code: OverconstrainedZonalAllocationRequest
        Message: Allocation failed. VM(s) with the following constraints cannot be allocated, because the condition is too restrictive. Please remove some constraints and try again. Constraints applied are:
          - Availability Zone
          - Differencing (Ephemeral) Disks
          - Networking Constraints (such as Accelerated Networking or IPv6)
          - VM Size

        Target: 158
```

at the end, I tried to change the sku for the nodes from`Standard_D8pds_v5` to `Standard_D16pds_v5`

and it worked !
confirmed the change as code with https://github.com/jenkins-infra/azure/pull/857

Workload should play nicely now on infra.ci ...

**Comment by dduportal** [comment]
Closing as:

- The initial problem is gone thanks to the work in https://github.com/jenkins-infra/azure/pull/857 by @smerle33 
- Improvements in https://github.com/jenkins-infra/azure/pull/859 (which required a manual apply but it's working well now)


=> note on costs. This change will increase the costs, but it's in the Azure sponsorship subscription so it's fine
