### ISSUE TITLE
Suspicious user dianedoyle108@hotmail.com on JIRA

### ISSUE THREAD

**Issue by PierreBtz** [jenkins-infra/helpdesk#4338]
### Service(s)

Jira

### Summary

Hey folks

I'd like to report the behavior of this user https://issues.jenkins.io/secure/ViewProfile.jspa?name=eleanorladd.

One week ago they created a comment on a long fixed issue. Wording is a bit off, it's making noise but it could be someone not aware of the proper etiquette... ok

Then today they edited the comment to add a link to a very suspicious website.

*Problematic comment:*

https://issues.jenkins.io/browse/JENKINS-68608?focusedId=449670&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-449670

Looking into their JIRA history I don't see any other action, so I'm not sure what to make of it, but I don't like seeing tickets spammed with suspicious links...

**Comment by MarkEWaite** [comment]
User blocked and Jira issue spam deleted.
