### ISSUE TITLE
Request for Admin Access to the GitHub Repository of the Environment Variables Status Sync Plugin

### ISSUE THREAD

**Issue by kun303-cloud** [jenkins-infra/helpdesk#4339]
### GitHub repositories

https://github.com/jenkinsci/environment-variables-status-sync-plugin

### GitHub users to have permission

@kun303-cloud

### Permission level

Admin

### Justification

I （@kun303-cloud ）am the developer and maintainer of the Environment Variables Status Sync Plugin, and I request the necessary permissions to manage its releases and updates.

**Comment by timja** [comment]
There is an invitation waiting for you to accept already:
<img width="471" alt="image" src="https://github.com/user-attachments/assets/8903036f-eeaa-48fd-a224-d093122c01c9">

go to https://github.com/jenkinsci to accept
