### ISSUE TITLE
Credential artifact-caching-proxy-credentials unavailable on ci.jenkins.io

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4340]
### Service(s)

Artifact-caching-proxy, ci.jenkins.io

### Summary

https://github.com/jenkins-infra/backend-extension-indexer/pull/95 fails CI at https://ci.jenkins.io/job/Infra/job/backend-extension-indexer/job/PR-95/1/console with the error

```
12:18:01  ERROR: Could not find credentials entry with ID 'artifact-caching-proxy-credentials'
```

This was added to the Jenkinsfile in https://github.com/jenkins-infra/backend-extension-indexer/pull/48.

I'm filing this issue here because it's unclear to me which component is at fault and what the fix should be.

**Comment by dduportal** [comment]
(quick answer for the weekend: we'll look in details during the week if need be) 

@daniel-beck I'm not sure why is the pipeline not using the `infra.withArtifactCachingProxy()` function (ref. https://github.com/jenkins-infra/pipeline-library/blob/39c35b87db6234671cd995cc9fa3e6dee71b2416/vars/infra.groovy#L163) to be honest.

But you can safely remove the credential as it is not used anymore from the pipeline directly as the proxy is only private: we removed the credential.

It *might* need further adaptation: maybe using the pipeline library function would be simpler.
