### ISSUE TITLE
Not able to login to jenkins forgot username and password 

### ISSUE THREAD

**Issue by AnkitaBhat** [jenkins-infra/helpdesk#4341]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Hi I tried resetting username and password but still showing invalid username and password when I am entering temporary password with correct username

### jenkins.io account username

anki_bhat

### jenkins.io account email

targodankita@gmail.com

### Which URL are you trying to login at?

http://localhost:8081/

**Comment by MarkEWaite** [comment]
The Jenkins infrastructure help desk is used for issues with the infrastructure that supports the Jenkins project and provides global information to Jenkins controllers.  We are not able to help with local installations of Jenkins.  Refer to the [Jenkins documentation](https://www.jenkins.io), the [Jenkins community forum](https://community.jenkins.io), and the [Jenkins user mailing list](https://groups.google.com/g/jenkinsci-users) for help with local installations of Jenkins.
