### ISSUE TITLE
extension-indexer runs with wrong Java (11 instead of 17) on infra.ci

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4343]
### Service(s)

infra.ci.jenkins.io

### Summary

Lots of

> class file has wrong version 61.0, should be 55.0

in the build log https://infra.ci.jenkins.io/job/reports/job/backend-extension-indexer/job/master/121/console despite the fixes in https://github.com/jenkins-infra/backend-extension-indexer/pull/96.

As a result, with the changes from https://github.com/jenkins-infra/backend-extension-indexer/pull/95, https://www.jenkins.io/doc/developer/extensions/ looks worse than it ever has 😢 

CC @timja

**Comment by timja** [comment]
I replayed it with `java -version`:

```
18:33:02  + java -version
18:33:04  openjdk version "11.0.24" 2024-07-16
18:33:04  OpenJDK Runtime Environment Temurin-11.0.24+8 (build 11.0.24+8)
18:33:04  OpenJDK 64-Bit Server VM Temurin-11.0.24+8 (build 11.0.24+8, mixed mode)
```

although 2 lines before it says:
```
18:33:01  INFO: Using JAVA_HOME=/opt/jdk-17 as default JDK home.
```
