### ISSUE TITLE
[terraform-aws-sponsorship] updatecli manifest for aws/vpc module

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4350]
we need an updatecli manifest to track the module AWS/VPC version https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/712b1a40fac5c057c4db539e06f85dab93037586/vpc.tf#L3

this was done before on the aws repository, so example should be easy to find.

**Comment by jayfranco999** [comment]
Added updatecli manifest to track and update "vpc" module version – https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/24

Tested locally and successfully.

```
=============================

SUMMARY:



⚠ Bump version of the Terraform "vpc" module in terraform-aws-sponsorship/vpc.tf:
        Source:
                ✔ [getLatestVersion] Retrieve the latest version
        Target:
                ⚠ [upgradeModuleVersion] Update the Terraform "vpc" module version of terraform-aws-sponsored in vpc.tf


Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1

**Comment by dduportal** [comment]
PR merged: https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/29 was opened (and merged) proving it works as expected!
