### ISSUE TITLE
[terraform-aws-sponsorship] updatecli manifest for AWS terraform provider

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4351]
as per https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/main/updatecli/updatecli.d/terraform-providers/local.yaml and the terraform local provider, we need a manifest to track the AWS provider

**Comment by jayfranco999** [comment]
Update: 

Manifest created to track and update aws terraform-provider version – https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/25
