### ISSUE TITLE
(packer-images): Add Linux AMD64 and ARM64 AMIs For EC2 agents

### ISSUE THREAD

**Issue by jayfranco999** [jenkins-infra/helpdesk#4353]
Due to the complexity of this PR – https://github.com/jenkins-infra/packer-images/pull/1430 

We are splitting the tasks into 4 stages, this issue is related to adding linux AMD64 and ARM64 AMIs for our jenkins EC2 agents.

We are reintroducing the amazon logic that we were using with our previous AWS jenkins account – https://github.com/jenkins-infra/packer-images/pull/734/

- [x] Add `amazon-ebs` builder logic in `Jenkinsfile_k8s`
- [x] Include EC2 source for `build-jenkins-agent-ubuntu.pkr.hcl`
- [x] Add `datasources.pkr.hcl` to look-up `ubuntu-22_04` AMI id for respective architecture 
- [x] Define `aws_instance_types` in `locals.pkr.hcl`
- [x] Include Amazon plugin for packer-images
- [x] Define all the common settings for AWS base image AMI's in `sources.pkr.hcl`
- [x] Add AWS related packer-image variables (AWS region and credentials)

_Originally posted by @jayfranco999 in https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2410363812_

**Comment by dduportal** [comment]
- Merged https://github.com/jenkins-infra/packer-images/pull/1447
- https://github.com/jenkins-infra/packer-images/releases/tag/2.5.0 and https://github.com/jenkins-infra/packer-images/releases/tag/2.7.0 where releases with success.


Closing as this task is done. If we detect minor issues when testing, we'll track them separately
