### ISSUE TITLE
(packer-images): Add Win-19, Win-22 (AMD64 and ARM64) AMIs For EC2 agents

### ISSUE THREAD

**Issue by jayfranco999** [jenkins-infra/helpdesk#4354]
Due to the complexity of this PR – https://github.com/jenkins-infra/packer-images/pull/1430

We are splitting the tasks into 4 stages, this issue is related to adding Win-19, Win-22 (AMD64 and ARM64) AMIs for our jenkins EC2 agents.

We are reintroducing the amazon logic that we were using with our previous AWS jenkins account – https://github.com/jenkins-infra/packer-images/pull/734

- [x] Include EC2 source for `build-jenkins-agent-windows.pkr.hcl`
- [x] Add `datasources.pkr.hcl` to look-up `windows-2019` and `windows-2022` AMI ids for respective architecture 
- [x] Define `windows_winrm_user` in `locals.pkr.hcl` as administrator for `amazon-ebs` since admin permissions are required to ssh our windows ec2 agents
- [x] Define all the common settings for AWS base image AMI's in `sources.pkr.hcl`

_Originally posted by @jayfranco999 in https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2410363812_

**Comment by dduportal** [comment]
- The PR https://github.com/jenkins-infra/packer-images/pull/1611 did add the 2 AWS EC2 templates for Windows
- The release https://github.com/jenkins-infra/packer-images/releases/tag/2.18.0 now provides 2 new AMIs

**Comment by dduportal** [comment]
Note: we chose to use public IP with WinRM allowed to anywhere from Azure infra.ci agents.
