### ISSUE TITLE
(packer-images): Add Garbage Collector for AWS

### ISSUE THREAD

**Issue by jayfranco999** [jenkins-infra/helpdesk#4355]
Due to the complexity of this PR – https://github.com/jenkins-infra/packer-images/pull/1430

We are splitting the tasks into 4 stages, this issue is related to handling the Garbage collector scripts foe old AWS AMI Images.

We are reintroducing the amazon login that we were using with our previous AWS jenkins account – https://github.com/jenkins-infra/packer-images/pull/734

- [ ] Cleanup AWS images – ensure staging images older than 7 days are removed
- [ ] Cleanup AWS images – collect EC2 snapshots older than 1 year on `us-east-2`
- [ ] Cleanup AWS images – add `aws.sh` as daily cleanup task 

_Originally posted by @jayfranco999 in https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2410363812_

**Comment by dduportal** [comment]
Update:

- We need a distinct job for garbage collection of packer-images (ref. https://github.com/jenkins-infra/kubernetes-management/blob/main/config/jenkins-jobs_infra.ci.jenkins.io.yaml) with:
  - Custom Jenkinsfile
  - Its own set of credentials (reuse the same as the principal job for now)
  - no tag discovery
- Once successfull, update the principal `Jenkinsfile_k8s` pipeline to remove Garbage collection from it

**Comment by jayfranco999** [comment]
Update: 

https://github.com/jenkins-infra/kubernetes-management/pull/5892 and https://github.com/jenkins-infra/packer-images/pull/1527 adds the aws credentials and `aws-gc` stage to the `Jenkisnfile_gc` pipeline.

Once merged, we can merge https://github.com/jenkins-infra/packer-images/pull/1528 which makes the garbage-collector` a distinct job and speed up the `main` build on `packer-images`

**Comment by jayfranco999** [comment]
Update:

Task list to follow:

This first version works well!

Next steps:

This first version works well!

Next steps:

- On this pipeline (subsequent PR):
  - [x] Add a cron job trigger  (https://github.com/jenkins-infra/packer-images/pull/1531)
  - [x] Restrict (dryrun=false) to only the `main` branch - (https://github.com/jenkins-infra/packer-images/pull/1532)
  - [ ] Add AWS garbage collection
- On the `Jenkinsfile_k8s` standard pipeline of this repository:
  - [x] Remove the GC stage(s) (https://github.com/jenkins-infra/packer-images/pull/1528)
- On the GC job configuration level, we need to:
  - [ ] Disable the GitHub checks report from infra.ci to the repository
  - ~Stop discovering and building PRs~ (We decided to keep PRs with dryrun to test script changes)
  - [x] Stop discovering and building tags
  - ~Only build on the `main` branch (not other branch)~ (Not needed anymore)
  
garbage collector now exists as a distinct job `Jenkinsfile_gc` and runs on a pod agent with dryrun on PRs (but not on tags) and doesn't send github checks anymore

**Comment by jayfranco999** [comment]
>   * - [ ] Add AWS garbage collection

On adding the aws garbage collection, we noticed that the `aws.sh` script exited with an error `An error occurred (UnauthorizedOperation) when calling the DescribeNetworkInterfaces operation: You are not authorized to perform this operation. User: arn:aws:iam::326712726440:user/terraform-packer-user is not authorized to perform: ec2:DescribeNetworkInterfaces because no identity-based policy allows the ec2:DescribeNetworkInterfaces action`

Even though the script failed, the logs reported the build step as successful, which is unexpected behaviour on infra.ci (https://infra.ci.jenkins.io/job/infra-tools/job/packer-images-gc/job/main/65/pipeline-console/?selected-node=19)

<img width="1332" alt="image" src="https://github.com/user-attachments/assets/da7d60ca-c69c-41c4-9db5-9adbabdc89d0">

Also there was an unexpected behaviour with the `aws_snapshots.sh` script that could not delete snapshots with the error `The snapshot snap-0999857b5cac1fd3a is currently in use by ami-0cfe784c66xxxx`

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/92b782bf-05a1-45e4-85ce-1e70babba739">

Further steps will involve fixing these errors and unexpected behaviour of infra.ci

**Comment by jayfranco999** [comment]
>  - [ ] Disable the GitHub checks report from infra.ci to the repository

https://github.com/jenkins-infra/kubernetes-management/pull/5895 partially works as the configuration was applied on `garbage-collector for packer images` folder on infra.ci

<img width="1102" alt="image" src="https://github.com/user-attachments/assets/ae942dbf-85d4-4e32-94b7-a987b94f94c0">

While tag discovery was successfully disabled, the github checks report of the garbage collector is still published on `packer-images` repository, we are working to fix this issue

<img width="706" alt="image" src="https://github.com/user-attachments/assets/306057b3-7c40-48ae-a918-efb78555aae6">

**Comment by dduportal** [comment]
> > * [ ]  Disable the GitHub checks report from infra.ci to the repository

Explanation: your changes were good and **did** disable the usual "Status checks" (e.g. one status check per stage by default, pipeline reporting and custom status checks).
But what we see in your screenshot above are "Notifications", which are a subset of "Status checks" (if any) but not only: the GitHub Branch Source plugin also sends a notification as part of the pipeline report.

If you look at the configuration below, you see the checkbox "Skip publishing Status check" is selected , which was not the case before your changes 👍 

<img width="895" alt="Capture d’écran 2024-11-20 à 14 01 23" src="https://github.com/user-attachments/assets/a3277134-ff88-41f2-a40c-ca98437dbef3">

However, we now need to have the "Suppress progress updates in job check" and "Skip GitHub Branch Source notifications" checbox selected to be sure that:
- No notifications are sent at all when pipeline finished
- Any "build in progress" event should also not send any notification (when pipeline starts)

We need to allow these to be configured in the "Jenkins Jobs" helm chart in https://github.com/jenkins-infra/helm-charts/blob/575396eb4f6c813f59a36610594c12446222935c/charts/jenkins-jobs/templates/_jobDSL_jobs_multibranch.tpl#L38-L40 => let me do this right now.

**Comment by dduportal** [comment]
Update on the job configuration:
- Added a new feature on the `jenkins-jobs` helm chart to totally disable notifications.
  - NOTE: this feature also has a bugfix which sync. the "progress updates checks" with other checks => there are now disabled or enabled together (which fixes partailly our problem here).
  - This new feature is not enabled (yet?) on the job though (non regrerssion)

**Comment by dduportal** [comment]
Update:
- https://github.com/jenkins-infra/packer-images/pull/1544 did fix the `aws.sh`, added debug and allow the process to fail fast when facing missing permissions 👏 
- Added the missing permission in https://github.com/jenkins-infra/terraform-states/commit/a39d169e096c3c9837f6f1d7609148ab098d5bf3. 
- Checked the new build status: `aws.sh` now work and remove dangling instances and security groups 👏 
- New error on the `aws_snapshot.sh` script: `An error occurred (InvalidSnapshot.InUse) when calling the DeleteSnapshot operation: The snapshot snap-0207fe814a28f361b is currently in use by ami-006a00b674bfd3f70`. Should be fixed with the same technique as in https://github.com/jenkins-infra/packer-images/pull/1544

**Comment by dduportal** [comment]
Last tasks have been done (see https://github.com/jenkins-infra/helpdesk/issues/4355)

@jayfranco999 reported we don't have dangling instances no more \o/
