### ISSUE TITLE
[ci.jenkins.io] project jenkins-infra/docker-plugin-site-issues is not built on ci.jenkins.io (scan permission errors) and has a different pipeline than infra.ci

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4356]
### Service(s)

ci.jenkins.io

### Summary

As seen in https://github.com/jenkins-infra/docker-plugin-site-issues/pull/34#issuecomment-2411129613, the project is failing to be built on ci.jenkins.io.

As per @zbynek [first analysis](https://github.com/jenkins-infra/docker-plugin-site-issues/pull/34#issuecomment-2411767848):

> There are 2 Jenkinsfiles in this repo and I think one is meant to run in infra.ci and one in ci -- but in ci there are errors when scanning https://ci.jenkins.io/job/Infra/job/docker-plugin-site-issues/indexing/console

The scanning logs  shows the following:

```text
ERROR: [Mon Oct 14 09:25:10 UTC 2024] Could not fetch branches from source org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator::https://api.github.com::jenkins-infra::docker-plugin-site-issues
[Mon Oct 14 09:25:10 UTC 2024] Finished branch indexing. Indexing took 2 sec
FATAL: Failed to recompute children of Infra » docker-plugin-site-issues
org.kohsuke.github.HttpException: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/collaborators/collaborators#get-repository-permissions-for-a-user","status":"403"}
```

which is most probably a missing permission for the GH app. Gotta check it

----

Besides: we have a distinct pipeline on infra.ci than on ci.jenkins.io which is recipe for errors (different tools, etc.). We need to unify both pipelines.

**Comment by dduportal** [comment]
The GitHub APP with ID `74951` was not allowed to check the repository. Added it back:

<img width="640" alt="Capture d’écran 2024-10-16 à 15 24 34" src="https://github.com/user-attachments/assets/4e266593-81e2-4cfc-9e98-a106db67f676">

The scan now happens, but builds are failing with whatever missing NPM dependency.

Closing the issue as it is out of the scope of the Jenkins infra issue.

![image](https://github.com/user-attachments/assets/871962ad-1c73-44c0-923c-c7353d1f7ad1)

**Comment by alecharp** [comment]
Thank you @dduportal. As long as it's built, we (contributors) can fill pull request to fix the build.

**Comment by zbynek** [comment]
Thanks for fixing this. (FTR the CI failures were fixed in https://github.com/jenkins-infra/docker-plugin-site-issues/pull/35 ).
