### ISSUE TITLE
Docker agents are not launched on ci.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4359]
### Service(s)

ci.jenkins.io

### Summary

Jobs that use an agent with the label `docker` have not launched on ci.jenkins.io for several hours.  https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1788/1/ is an example of a job that is blocked waiting for the `docker-highmem` label

### Reproduction steps

1. Check jobs in the ci.jenkins.io build queue, note that many of those jobs are waiting for an agent with the `docker` label or the `docker-highmem` label

**Comment by dduportal** [comment]
Looks like an unintended consequence of https://github.com/jenkins-infra/helpdesk/issues/4358#issuecomment-2415827243.

We are again caught in the Azure VM plugin not refreshing credential :'( 

Just restarted ci.jenkins.io and agents are spawning again. Let's amend the procedure used for https://github.com/jenkins-infra/helpdesk/issues/4358

**Comment by dduportal** [comment]
Temporarily increased the maximum size of cloud agents: 100 each (instead of 50)  to absorb the build wave

**Comment by dduportal** [comment]
Build queue is emptied: builds are being performed.

**Comment by dduportal** [comment]
Note: the PR https://github.com/jenkins-infra/azure/pull/854 DID mention a restart at the end:

>  then restart the controller to ensure that the old credential is not kept in cache.

=> I'm the culprit here. Sorry for the blocker :(

**Comment by krisstern** [comment]
Thanks @dduportal for the prompt response!
