### ISSUE TITLE
[packer-images] track Linux base images with `updatecli`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4365]
### Service(s)

Other

### Summary

In packer images, we [recently introduced a new YAML file](https://github.com/jenkins-infra/packer-images/pull/1443) in which we specify and pin the base images for our system: https://github.com/jenkins-infra/packer-images/blob/main/images-versions.yaml.

We want to cover all cloud providers with this file (AWS, Azure, Docker) for all OSes (Linux, Windows) and all versions/architectures.

## AWS 

- [x] We pinned the base Ubuntu 22.04 AMIs for both `amd64` and `arm64` in https://github.com/jenkins-infra/packer-images/blob/6f5b55030bdaf528c7b5326085f420409e570531/locals.pkr.hcl#L13-L18 and it's used by the `build-jenkins-agent-ubuntu` file. However, we want to use https://github.com/jenkins-infra/packer-images/blob/6f5b55030bdaf528c7b5326085f420409e570531/images-versions.yaml#L13-L17 instead.
- [x] Then, we want to add updatecli manifest(s?) to track these both versions
  - Require adding an AWS credential in the `updatecli` job in infra.ci for packer-images (might already be done)

Note for Windows: not implemented for AWS yet so not needed in this issue (see https://github.com/jenkins-infra/helpdesk/issues/4318)

## Azure

- [x] Windows already done in https://github.com/jenkins-infra/packer-images/pull/1443: https://github.com/jenkins-infra/packer-images/blob/6f5b55030bdaf528c7b5326085f420409e570531/images-versions.yaml#L4-L8
- [  ] Linux has to be implemented. We have "dummy" specified versions in https://github.com/jenkins-infra/packer-images/blob/6f5b55030bdaf528c7b5326085f420409e570531/images-versions.yaml#L9-L12 with the value `latest` 

## Docker

- [x] Linux has to be implemented. Specified here: https://github.com/jenkins-infra/packer-images/blob/6f5b55030bdaf528c7b5326085f420409e570531/sources.pkr.hcl#L77 (need to be adapted of course!). Let's use image with both tag and sha: (looking like) `ubuntu:22.04@sha256:xxxxxxx`
  - Tip: see https://hub.docker.com/_/ubuntu/tags?name=22.04, don't forget we have 2 CPU architecture, and also https://www.updatecli.io/docs/plugins/resource/docker_digest/

**Comment by dduportal** [comment]
@jayfranco999 works on the Linux AMi part

**Comment by jayfranco999** [comment]
Update:

https://github.com/jenkins-infra/packer-images/pull/1507 now tracks and updates the latest `AZ Ubuntu 22_04 AMD64` image

The manifest works as intended on infra.ci

(https://infra.ci.jenkins.io/job/updatecli/job/packer-images/job/PR-1507/32/pipeline-console/log?nodeId=18)

```
[2024-11-26T10:11:51.136Z] #################################################
[2024-11-26T10:11:51.136Z] # BUMP AZURE `UBUNTU 22.04` AMD64 IMAGE VERSION #
[2024-11-26T10:11:51.136Z] #################################################
[2024-11-26T10:11:51.136Z] 
[2024-11-26T10:11:51.136Z] source: source#lastReleaseVersion
[2024-11-26T10:11:51.136Z] -------------------------
[2024-11-26T10:12:23.134Z] The shell 🐚 command "/bin/sh /tmp/updatecli/bin/fe287e953d07bf4def15ea4f2d79cd182990dee39f04530a41f3a8f0e0944d01.sh" ran successfully with the following output:
[2024-11-26T10:12:23.134Z] ----
[2024-11-26T10:12:23.134Z] 22.04.202410020
[2024-11-26T10:12:23.134Z] ----
[2024-11-26T10:12:23.134Z] ✔ shell command executed successfully
[2024-11-26T10:12:23.134Z] 
[2024-11-26T10:12:23.134Z] target: target#updateVersion
[2024-11-26T10:12:23.134Z] --------------------
[2024-11-26T10:12:23.134Z] [transformers]
[2024-11-26T10:12:23.134Z] ✔ Result correctly transformed from "22.04.202410020" to "\"22.04.202410020"
[2024-11-26T10:12:23.134Z] ✔ Result correctly transformed from "\"22.04.202410020" to "\"22.04.202410020\""
[2024-11-26T10:12:23.134Z] 
[2024-11-26T10:12:23.134Z] **Dry Run enabled**
[2024-11-26T10:12:23.134Z] 
[2024-11-26T10:12:23.134Z] ⚠ - change detected:
[2024-11-26T10:12:23.134Z] 	* key "$.azure.ubuntu.'22.04'.amd64" should be updated from "\"latest\"" to "\"22.04.202410020\"", in file "./images-versions.yaml"
[2024-11-26T10:12:23.134Z]

**Comment by jayfranco999** [comment]
Update:

https://github.com/jenkins-infra/packer-images/pull/1507 and https://github.com/jenkins-infra/packer-images/pull/1555 tracks the base ubuntu `22_04` AZ image version. 

the manifest for tracking the latest AZ `Ubuntu 22_04 ARM64` image has been tested successfully (https://infra.ci.jenkins.io/job/updatecli/job/packer-images/job/PR-1555/3/pipeline-console/log?nodeId=18)

```
16:24:39  #################################################
16:24:39  # BUMP AZURE UBUNTU `22.04` ARM64 IMAGE VERSION #
16:24:39  #################################################
16:24:39  
16:24:39  source: source#lastReleaseVersion
16:24:39  -------------------------
16:24:39  The shell 🐚 command "/bin/sh /tmp/updatecli/bin/ba82edf9297075691bee00f561354cfee2b3efc6326b9b47eb759164fa7c2721.sh" ran successfully with the following output:
16:24:39  ----
16:24:39  22.04.202410020
16:24:39  ----
16:24:39  ✔ shell command executed successfully
16:24:39  
16:24:39  target: target#updateVersion
16:24:39  --------------------
16:24:39  [transformers]
16:24:39  ✔ Result correctly transformed from "22.04.[202](https://infra.ci.jenkins.io/job/updatecli/job/packer-images/job/PR-1555/3/pipeline-console/?start-byte=0&selected-node=18#log-202)410020" to "\"22.04.202410020"
16:24:39  ✔ Result correctly transformed from "\"22.04.202410020" to "\"22.04.202410020\""
16:24:39  
16:24:39  **Dry Run enabled**
16:24:39  
16:24:39  ⚠ - change detected:
16:24:39  	* key "$.azure.ubuntu.'22.04'.arm64" should be updated from "\"latest\"" to "\"22.04.202410020\"", in file "./images-versions.yaml"
16:24:39

```

Since all Linux (amd64 &arm64) base images for AWS, Azure, and Docker are tracked with updatecli; we can close this issue.

**Comment by dduportal** [comment]
LGTM! The PRs https://github.com/jenkins-infra/packer-images/pull/1558 and https://github.com/jenkins-infra/packer-images/pull/1556 were automatically opened, proving your work here is done!
