### ISSUE TITLE
[OSUOSL] Migrate `lists.jenkins-ci.org` to a new (OSUOSL side) system

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4366]
As requested by [Lance Albertson from OSUOSL](https://github.com/ramereth) in https://groups.google.com/g/jenkins-infra/c/6lJ4f3XEzpA/m/L1Sw1uTvAwAJ, they want to migrate `lists.jenkins-ci.org` to their new HAProxy system.

We have to apply the following tasks:

1. Please update the A record for [lists.jenkins-ci.org](http://lists.jenkins-ci.org/) to point to 140.211.9.53
2. Add an AAAA record for [lists.jenkins-ci.org](http://lists.jenkins-ci.org/) to 2605:bc80:3010:104::8cd3:935
3. Create the following TXT record: "v=spf1 mx include:_[spf.osuosl.org](http://spf.osuosl.org/) ~all"

General note: I'm not sure if lists.jenkins-ci.org is still in use though (ping @MarkEWaite @daniel-beck @timja @olblak if you have history about this one?). BUT we will run this request to help our friends at OSUOSL, wether the service is still used or not so they can proceed with their migration.

We'll consider cleaning up, or documenting, or whatever further action on lists.jenkins-ci.org on a subsequent issue.

**Comment by timja** [comment]
Its not used but it is an old archive which may/or may not be good to keep around if anyone wants to find out why something was done in a certain way.

**Comment by ramereth** [comment]
If you have any questions, please feel free to ping me here. I'm watching this issue now.

**Comment by dduportal** [comment]
Update on the tasks to apply:

- [ ] We have to import the DNS `A` record under Terraform first and set its TTL to 60s - https://github.com/jenkins-infra/azure-net/pull/307
- [ ] Then, we'll apply the 3 required changes, e.g. adding the `AAAA` and `TXT` records + changing the IP targeted by `lists.jenkins-ci.org`

**Comment by dduportal** [comment]
Changes applied successfully:

<img width="943" alt="Capture d’écran 2024-10-24 à 20 30 40" src="https://github.com/user-attachments/assets/66fc7cdc-e2f8-4235-b03e-442620e24f80">


I see http://lists.jenkins-ci.org/mailman/listinfo working well, and https://lists.jenkins-ci.org/mailman/listinfo available but complains about the certificat (as expected) for now.

@ramereth are the changes ok for you?

**Comment by ramereth** [comment]
@dduportal yup! working on my end. I'll deploy a proper cert and do the migration to the new host here shortly. Thank you!
