### ISSUE TITLE
Update ci.jenkins.io, trusted.ci, cert.ci and release.ci to latest LTS version 2.479.1

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4370]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io

### Summary

New [LTS 2.479.1](https://www.jenkins.io/changelog-stable/2.479.1/) is out. We need to update our controllers:

- [ ] release.ci.jenkins.io (Kubernetes)
- [ ] ci.jenkins.io (Puppet managed VM)
- [ ] trusted.ci.jenkins.io (Puppet managed VM)
- [ ] cert.ci.jenkins.io (Puppet managed VM)

**Comment by dduportal** [comment]
Update:

- ci.jenkins.io upgraded finished Wednesday 30 October at 14h30 UTC (ref. https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$zzXdsqK2FKuzBGI0Pueb74_7uGTPCQceUJLtuf850n4?via=g4v.dev&via=gitter.im&via=matrix.org)
  - ⚠️ We broke the instance as the LDAP plugin had to be upgraded along with the Core upgrade. It was described in the [upgrade guide for 2.479.1](https://www.jenkins.io/doc/upgrade-guide/2.479/#upgrading-to-jenkins-lts-2-479-1) which I did not read. Shame on me!
- cert.ci and trusted.ci upgraded in https://github.com/jenkins-infra/jenkins-infra/pull/3705 (with the LDAP fix as part of the upgrade)
- release.ci.jio upgraded:
  - Core + plugins (including LDAP):  https://github.com/jenkins-infra/docker-jenkins-lts/pull/921
  - Deployed in production by https://github.com/jenkins-infra/kubernetes-management/pull/5852
