### ISSUE TITLE
CD pipeline fails to upload to Artifactory for some users

### ISSUE THREAD

**Issue by tharindud** [jenkins-infra/helpdesk#4374]
### Service(s)

Artifactory

### Summary

Release upload to Artifactory for railflow-testrail-plugin fails when the CD pipeline is manually triggered by some users (tharindud) with a 403 error. The same pipeline triggered by @timja has succeeded.

### Reproduction steps

See https://github.com/jenkinsci/railflow-testrail-plugin/actions/runs/11658689187/job/32458105764 for a failed pipeline sample.

The same pipeline triggered by @timja has succeeded to upload a release as evident from the following run: https://github.com/jenkinsci/railflow-testrail-plugin/actions/runs/11618192698/job/32355086315

**Comment by timja** [comment]
Versions can't be overwritten, the artifactory 403 error means that the artifact is already there

In the above case the automatically triggered build released just fine: https://github.com/jenkinsci/railflow-testrail-plugin/actions/runs/11658034590

Then you tried to release the same version again twice which failed as it already exists
