### ISSUE TITLE
Plugin page not found [https://plugins.jenkins.io/markdown-params/](markdown-params) 

### ISSUE THREAD

**Issue by jesusnoseq** [jenkins-infra/helpdesk#4379]
### Service(s)

plugins.jenkins.io

### Summary

I have developed a new Jenkins plugin https://github.com/jenkinsci/markdown-params-plugin
And I am having an issue with the doc page.
While I can see it when searching for it on the Jenkins plugin site https://plugins.jenkins.io/ui/search/?query=markdown-params, the plugin page itself returns a 404 error https://plugins.jenkins.io/markdown-params/
I am unsure how to fix this issue.
Could you please let me know if there are any hints regarding the possible cause of the issue?
Thank you!

### Reproduction steps

Go to
https://plugins.jenkins.io/ui/search/?query=markdown-params
where the plugin is listed and
Open
https://plugins.jenkins.io/markdown-params/
The result page is a 404 error

**Comment by dduportal** [comment]
Quick initial analysis on the infra:

- Tried purging Fastly page (`curl -XPURGE <...>`) => successful but kept showing an HTTP/404
- The URL https://plugins.origin.jenkins.io/markdown-params/ also shows HTTP/404

=> it is not a caching issue (neither client side or Fastly side)


Continuing by checking the build and deployment logs

**Comment by dduportal** [comment]
🤦 the plugins site fails to build since October 31:

![Capture d’écran 2024-11-07 à 09 19 34](https://github.com/user-attachments/assets/bcf21ebd-d41e-451a-a8b6-c597a33b802c)

Which explains why the page is not published

**Comment by dduportal** [comment]
Update:

- It's only the "Deployment" part which fails, during the `azcopy` step
  - Same as #4378
  - @smerle33 also caught the same error for stats.jenkins.io
- https://github.com/jenkins-infra/plugin-site/pull/1989 to collect the `azcopy` logs when failing so we can check them right now
- Logs are showing the same error pattern as in https://github.com/jenkins-infra/helpdesk/issues/4378

The timing of these error, on ALL of our azcopy systems, is suspicious. Of course, it maps to when we deployed the new agent VM/container image [2.10.0](https://github.com/jenkins-infra/packer-images/releases/tag/2.10.0) which features a new version of the utility CLI `azcopy`.

This new version, https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.27.0, features changes related to creating folders and parallelization: looks like a good culprit...


We are trying with manual replay of pipelines using the previous `azcopy` version: if it work, we'll revert to the old version (and report back to Microsoft).

**Comment by dduportal** [comment]
Update:

- Retrying with the previous version of `azcopy` did fix the error: your page is now visible

Next steps:

- Revert azcopy version to our infrastructure
- Checks that it solves all deployment issues

**Comment by dduportal** [comment]
- Reverted azcopy to previous version:
  - Image release: https://github.com/jenkins-infra/packer-images/releases/tag/2.11.1
  - Deployed with https://github.com/jenkins-infra/kubernetes-management/pull/5869 and https://github.com/jenkins-infra/jenkins-infra/pull/3711 
- New deployment of plugins.jenkins.io in progress to validate end to end
