### ISSUE TITLE
Latest Workflow-CPS commit is not generating a new release

### ISSUE THREAD

**Issue by jgarciacloudbees** [jenkins-infra/helpdesk#4387]
### Service(s)

GitHub

### Summary

Workflow-CPS latest commit is not generating a new release:
https://github.com/jenkinsci/workflow-cps-plugin/commit/5eebd322b66751cf6488528d3521b5badc8c1f8a

I would expecte new release 3994, all the checks are green and in https://ci.jenkins.io/job/Plugins/job/workflow-cps-plugin/job/master/627/, the artifact is properly generated.

![image](https://github.com/user-attachments/assets/0fb196cf-fa60-4cc7-a8ec-ce279c0d119b)

**Comment by timja** [comment]
Its labelled as a `chore` which is not an interesting category, need one of e.g. bug, enhancement, developer

**Comment by dduportal** [comment]
> Its labelled as a `chore` which is not an interesting category, need one of e.g. bug, enhancement, developer [jenkinsci/workflow-cps-plugin#952](https://github.com/jenkinsci/workflow-cps-plugin/pull/952)

I went on the same conclusion while helping @jgarciacloudbees (in our private Slack) but it took me quite some time to understand it correctly.

Do we have a documentation to help on this matter @timja ?

**Comment by timja** [comment]
There's a section for it although this isn't mentioned in it:
https://www.jenkins.io/doc/developer/publishing/releasing-cd/#troubleshooting

Its documented here though: https://www.jenkins.io/doc/developer/publishing/releasing-cd/#troubleshooting

Worth adding an FAQ at the bottom though I think

**Comment by lemeurherveCB** [comment]
> orth adding an FAQ at the bottom though I think

Opened https://github.com/jenkins-infra/jenkins.io/pull/7685, WDYT?
