### ISSUE TITLE
Delete accounts.jenkins.io account

### ISSUE THREAD

**Issue by kostasns** [jenkins-infra/helpdesk#4393]
### Type(s) of account issue

I want my account to be deleted

### Summary

Please delete my accounts.jenkins.io account

### jenkins.io account username

kostas_nsbox

### jenkins.io account email

kostas@nsbox.lt

### Which URL are you trying to login at?

accounts.jenkins.io

**Comment by MarkEWaite** [comment]
I've sent an email to the address assigned to that account.  Once I receive a reply to that email, I'll delete the account.

**Comment by MarkEWaite** [comment]
Reply received and account has been deleted
