### ISSUE TITLE
[cert.ci.jenkins.io] Keep Maven tools up to date with `updatecli`

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4399]
### Service(s)

cert.ci.jenkins.io

### Summary

In https://github.com/jenkins-infra/jenkins-infra/blob/4b06713c89a121e7c094ab1594e07e7a8dff94ce/hieradata/clients/controller.cert.ci.jenkins.io.yaml#L40-L51, we specified a list of Maven tools to be used by cert.ci.jenkins.io pipelines.

As per https://github.com/jenkins-infra/jenkins-infra/pull/3691, we should track each of this maven versions up to date to the latest patch available for each minor line.

- We already have a manifest for the Maven tools of ci.jenkins.io in this repo: https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/jenkinscontroller-tools-maven.yaml (most probably to be reused or renamed)
- We used to track the "latest" Maven with the following (old) manifest: https://github.com/jenkins-infra/packer-images/blob/96a5a06b5e89b0b17ad64ff457df6bc6d4fc6eda/updatecli/updatecli.d/maven.yml

**Comment by jayfranco999** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/3739 tracks all the all maven tools versions on `cert.ci.jenkins.io` controller.

The solution was tested locally with success:

```
SUMMARY:



✔ Bump Maven version for cert.ci.jenkins.io:
        Source:
                ✔ [mavenVersion3-5] Get the latest Maven 3.5.x version
                ✔ [mavenVersion3-6] Get the latest Maven 3.6.x version
                ✔ [mavenVersion3-8] Get the latest Maven 3.8.x version
                ✔ [mavenVersion3-9] Get the latest Maven 3.9.x version
        Condition:
                ✔ [checkIfReleaseIsAvailable3-5] 
                ✔ [checkIfReleaseIsAvailable3-6] 
                ✔ [checkIfReleaseIsAvailable3-8] 
                ✔ [checkIfReleaseIsAvailable3-9] 
        Target:
                ✔ [updateMaven3-5Version] Update the `Maven 3.5.x` version in the cert.ci.jenkins.io controller
                ✔ [updateMaven3-6Version] Update the `Maven 3.6.x` version in the cert.ci.jenkins.io controller
                ✔ [updateMaven3-8Version] Update the `Maven 3.8.x` version in the cert.ci.jenkins.io controller
                ✔ [updateMaven3-9Version] Update the `Maven 3.9.x` version in the cert.ci.jenkins.io controller


Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
