### ISSUE TITLE
Remove BlueOcean from all of our controllers

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4400]
### Service(s)

cert.ci.jenkins.io, ci.jenkins.io, infra.ci.jenkins.io, release.ci.jenkins.io, trusted.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

Following https://github.com/jenkins-infra/helpdesk/issues/2833, enough time has passed and we haven't used BlueOcean at all in the past months: the Graph viewer is good enough for our usage now!

Thanks @timja @NotMyFault @uhafner and many other for the work put into this plugin

As such, I propose we remove BlueOcean plugin**s** from all of our controllers:

- Less dependencies 
- Less security risk
- Less heavy threads

Note: we might have to [reconfigure the default views](https://github.com/jenkins-infra/helpdesk/issues/2833#issuecomment-2100635026) and to clean up plugins manually on some controllers

### plugin list to remove: 
blueocean
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline
blueocean-commons
blueocean-config
blueocean-core-js
blueocean-dashboard
blueocean-display-url:2.4.3
blueocean-events
blueocean-git-pipeline
blueocean-github-pipeline
blueocean-i18n
blueocean-jira
blueocean-jwt
blueocean-personalization
blueocean-pipeline-api-impl
blueocean-pipeline-editor
blueocean-pipeline-scm-api
blueocean-rest
blueocean-rest-impl
blueocean-web
jenkins-design-language

**Comment by smerle33** [comment]
the plugin is not installed on weekly.ci - https://github.com/jenkins-infra/docker-jenkins-weeklyci/blob/main/plugins.txt

**Comment by smerle33** [comment]
the plugins are not installed on LTS docker image : https://github.com/jenkins-infra/docker-jenkins-lts/blob/main/plugins.txt

**Comment by smerle33** [comment]
the plugins are not installed on cert.ci.jio https://github.com/jenkins-infra/jenkins-infra/blob/db830e53f4e4b561f4b9bb33d65ea1a51544c700/hieradata/clients/controller.cert.ci.jenkins.io.yaml#L268-L292

**Comment by smerle33** [comment]
the plugin is installed on ci through puppet, here is the PR removing it: https://github.com/jenkins-infra/jenkins-infra/pull/3749 (after we will need a manual uninstallation of it through the UI)

**Comment by smerle33** [comment]
the plugin is installed on trusted.ci.jenkins.io through puppet, here is the PR removing it: hhttps://github.com/jenkins-infra/jenkins-infra/pull/3750 (after we will need a manual uninstallation of it through the UI)

**Comment by smerle33** [comment]
uninstallation from trusted.ci and ci.jenkins.io postpone to Tursday to not collide with today release.

**Comment by smerle33** [comment]
> uninstallation from trusted.ci and ci.jenkins.io postpone to Thursday to not collide with today release.

ci.jenkins.io and trusted.ci.jenkins.io have been proceed, no more blueocean on them (including `jenkins-design-language`)

**Comment by smerle33** [comment]
ALL DONE, thanks for your services `blueocean`
