### ISSUE TITLE
404 downloading some tool installer JSONs (geo dependant)

### ISSUE THREAD

**Issue by olivergondza** [jenkins-infra/helpdesk#4403]
### Service(s)

Update center

### Summary

Hello, since the update center infra switch on Nov 18, I am consistently running into issues downloading tool installer metadata from https://updates.jenkins.io/updates/. Most of the files can be downloaded without problems, but several fails:

- https://eastamerica.cloudflare.jenkins.io/updates/hudson.tools.JDKInstaller.json
- https://eastamerica.cloudflare.jenkins.io/updates/sp.sd.flywayrunner.installation.FlywayInstaller.json
- https://eastamerica.cloudflare.jenkins.io/updates/org.sbuild.jenkins.plugin.SBuildInstaller.json
- https://eastamerica.cloudflare.jenkins.io/updates/hudson.plugins.sonar.MsBuildSonarQubeRunnerInstaller.json
- https://eastamerica.cloudflare.jenkins.io/updates/hudson.plugins.sonar.MsBuildSonarQubeRunnerInstaller.json
- And more...

Interestingly enough, from `westeurope` zone, I see different files missing:

- https://westeurope.cloudflare.jenkins.io/updates/org.jenkins-ci.plugins.leiningen.LeinInstaller.json

Thanks!

### Reproduction steps

wget --no-verbose -r -nH -nd -np -R 'index.html*' --accept '*.json' --accept '*.json.html' https://updates.jenkins.io//updates/

**Comment by dduportal** [comment]
Thanks for reporting, we are looking into this matter right now

**Comment by dduportal** [comment]
Currently checking the tools installer deployment logs:

- We use `aws s3 sync` command (ref. https://github.com/jenkins-infra/crawler/blob/6c35ae15a4d8194f3a42c29422a2a06d888bfeca/.jenkins-scripts/publish.sh#L82-L87) to publish the data to the Cloudflare R2 mirrors.
- Mirrors are populated (for the tools installers) sequentially: first west europe, and then eastus
- Focusing only on the `hudson.tools.JDKInstaller.json` file in the logs:
  - For westeurope, the remote files are deleted first, then the new files are copied:
    
    ```text
    05:22:07  delete: s3://westeurope-updates-jenkins-io/updates/hudson.tools.JDKInstaller.json
    # ...
    05:22:08  upload: updates/hudson.tools.JDKInstaller.json to s3://westeurope-updates-jenkins-io/updates/hudson.tools.JDKInstaller.json
    ```

  - While for useast the deletion happens **after** the copy 😮‍💨 :

  ```text
  05:22:13  upload: updates/hudson.tools.JDKInstaller.json to s3://eastamerica-updates-jenkins-io/updates/hudson.tools.JDKInstaller.json
  # ...
  05:22:14  delete: s3://eastamerica-updates-jenkins-io/updates/hudson.tools.JDKInstaller.json
  ```


That's an insane behavior 😱 

Currently checking around the concurrency behavior (ref. https://community.cloudflare.com/t/is-it-actually-possible-to-upload-to-r2-buckets-using-wrangler/388762/7)

**Comment by dduportal** [comment]
Also, since we "trick" mirrorbits when scanning the mirror (as s3 is not supported, only rsync or ftp for scanning) with a rsync which have all of the files (not the S3 files).

We need to fix both behaviors

**Comment by dduportal** [comment]
Retrying the crawler publication in a pipeline replay with the following command:

```
aws configure set default.s3.max_concurrent_requests 2
```

as per https://community.cloudflare.com/t/is-it-actually-possible-to-upload-to-r2-buckets-using-wrangler/388762/7

=> let's see if it is enough on short term

**Comment by dduportal** [comment]
Also: https://github.com/aws/aws-cli/issues/1417#issuecomment-121555682

**Comment by dduportal** [comment]
Update: 
- Playing with the `aws s3` multi-part settings did make the problem the problem go away... 3 times out of 4 (tried 12 builds, it works like clockwork: 3 success with no deletion and 4th is always a deletion) - https://github.com/jenkins-infra/crawler/pull/153
- Tried the https://github.com/aws/aws-cli/issues/1417#issuecomment-121555682 "workaround" which.. does not work. 1st sync copies everything, but the 2nd keeps deleting files randomly.

=> that is insane behavior, I'll open a case at Cloudflare.

For now, we are removing the `--delete` file: it seems to fix the issue. Can you confirm @olivergondza ?

**Comment by olivergondza** [comment]
Thanks for the promp resolution, @dduportal.

I confirm this works for me from both `westeurope` and `eastamerica`!

**Comment by dduportal** [comment]
Additional actions:

- Our datadog monitoring was not parsing the Cloudflare logs due to a mistake (accidentally disabled pipeline processor). It has been [fixed](https://github.com/jenkins-infra/datadog/commit/520b0eb2559214621ff53f58051425445ffd0288) and we can now see HTTP/404 as warnings:

<img width="972" alt="Capture d’écran 2024-11-20 à 13 20 20" src="https://github.com/user-attachments/assets/3f8f522e-3b9c-440f-85fc-ad8b7a9d7479">

- The other JSON metadata (update-center2) are not suffering the problem of this issue: the flag `--delete` is not set up
