### ISSUE TITLE
Assistance Needed to Recover Corporate Jenkins Account

### ISSUE THREAD

**Issue by diegopoli** [jenkins-infra/helpdesk#4420]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I am reaching out to request assistance in recovering our corporate Jenkins account associated with philcoin.io (https://jenkins.philcoin.io/).

Projects:
phil-app-api
phil-app 

This account was initially set up by a former technology provider who also created pipelines for two of our major products, which are hosted on GitHub. Unfortunately, the vendor has since left our organization without providing the login credentials for the account.

Could you please guide us on the process for recovering access to this account? We are eager to restore access and continue managing our pipelines effectively.

Thank you for your time and support. I look forward to your guidance.

Best regards,
Diego Poli
PHILCoin Team

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by MarkEWaite** [comment]
Unfortunately, the Jenkins infrastructure team can't help with the administration of https://jenkins.philcoin.io/ .  That controller is not managed by the Jenkins infrastructure team.

If you can login to the server that is running the controller, you can use the [instructions on jenkins.io](https://www.jenkins.io/doc/book/system-administration/admin-password-reset-instructions/) to reset an administrator password.

**Comment by MarkEWaite** [comment]
@
