### ISSUE TITLE
CD secrets appear to have expired

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#4422]
### Service(s)

infra.ci.jenkins.io

### Summary

The credentials I was expecting in https://github.com/jenkinsci/aws-java-sdk2-plugin/settings/secrets/actions have not been created over an hour after enabling CD in `repository-permissions-updater`. I wonder if someone could check on the job that updates them and let me know if it is working as expected? Apologies in advance if this ticket is premature.

### Reproduction steps

Attempt to do a CD release of a Jenkins plugin

**Comment by timja** [comment]
> Skipping CD-enablement for 'aws-java-sdk2' in repository 'jenkinsci/aws-java-sdk2-plugin' as it is unmaintained

**Comment by basil** [comment]
Released successfully in https://github.com/jenkinsci/aws-java-sdk2-plugin/releases/tag/2.29.21-5.v31a_f7d69ea_f9. Thanks!
