### ISSUE TITLE
[infra.ci.jenkins.io/packer-images] Azure Credential used by Packer Image builds expire december 9 2024

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4423]
as stated by https://github.com/jenkins-infra/azure/pull/874
the password for the Azure AD application used by packer to build images expire soon, we should rotate it.

- [x] when the PR https://github.com/jenkins-infra/azure/pull/874 will be merged and checked, 
- [x] the password content should be update within the helm-chart as per https://github.com/jenkins-infra/charts-secrets/commit/c6d212b14ca71feab65991289242c6db048b70ec for the packer-image job (read the PR body for informations
- [x] Ensure packer builds are working again https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/main/

**Comment by smerle33** [comment]
password uploaded in charts-secrets https://github.com/jenkins-infra/charts-secrets/commit/64b0d8a35947c4401abf2a80938609a48a4cc7a7

**Comment by jayfranco999** [comment]
LGTM! 🚀

**Comment by smerle33** [comment]
https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/main/1710/ was able to spin up azure VM, but had issues with the goss check not updated correctly see : https://github.com/jenkins-infra/packer-images/pull/1565 and then https://github.com/jenkins-infra/packer-images/pull/1567
