### ISSUE TITLE
[infra-admin] Renew VPN certificat for smerle as it expired today

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4424]
### Service(s)

VPN

### Summary

after 3 years of good service, my certificate used in the VPN expired this afternoon : 
https://github.com/jenkins-infra/docker-openvpn/blob/ca49cb5574044e33a7cc5cd032e02286ef997109/cert/pki/issued/smerle.crt#L10
 Not After : Nov 27 14:38:01 2024 GMT

**Comment by dduportal** [comment]
- Certificate renewal in https://github.com/jenkins-infra/docker-openvpn/pull/370
- Released image: https://github.com/jenkins-infra/docker-openvpn/releases/tag/2.4.45
- Deployment PR: https://github.com/jenkins-infra/docker-openvpn/pull/370
