### ISSUE TITLE
Jira and github account linkage

### ISSUE THREAD

**Issue by PereBueno** [jenkins-infra/helpdesk#4431]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I had my jenkins jira account linked to a group https://github.com/jenkins-infra/repository-permissions-updater/pull/4197/files#diff-5aa60269b51053efb7f343390d45b8cb0462c905ccd671a16184cf18feef309aR18
However, my github account uses a different username (PereBueno) from the jenkins jira one (pbuenoyerbes).
Sync hasn't happened, which makes me thing of there is no known mapping from Jira username to Github username. Or maybe it's that group wasn't synced (don't really what the process for sync is).

### jenkins.io account username

pbuenoyerbes

### jenkins.io account email

pbuenoyerbes@cloudbees.com

### Which URL are you trying to login at?

no specific URL

**Comment by timja** [comment]
There is no sync, its expected that one of the team maintainers look after membership of the company team:
https://github.com/orgs/jenkinsci/teams/company-cloudbees-developers?query=role%3Amaintainer

(@jtnord, @batmat, @alecharp)

**Comment by jtnord** [comment]
> There is no sync

🤔 I expected this as it happens for regular membership on a plugins repository group IIRC?

Added, and have poked 2 people that are in the team that should not be according to the YAML to file a PR to add themselves to the YAML.

**Comment by timja** [comment]
> 🤔 I expected this as it happens for regular membership on a plugins repository group IIRC?

Manually done by me or Alex currently, previously cloudbees people managed that team exclusively
