### ISSUE TITLE
Unable to create a new account

### ISSUE THREAD

**Issue by samer-faour-exa** [jenkins-infra/helpdesk#4433]
### Type(s) of account issue

I didn't receive any email, I've been blocked by the anti-spam system

### Summary

I need to create an account to raise a JIRA.
I tried my company email as well as my personal and neither is working. Please help.

### jenkins.io account username

Samour

### jenkins.io account email

samer@exabeam.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by samer-faour-exa** [comment]
None of these are relevant. If It helps I already have an Atlassian account with my company email. Still doesn't explain why I was not allowed to create a new account on my personal email.

**Comment by samer-faour-exa** [comment]
I tried again to create a new account and it is still failing

**Comment by dduportal** [comment]
Hi @samer-faour-exa , our system shows that the email were sent end delivered with success to your email address:

<img width="1354" alt="Capture d’écran 2024-12-02 à 16 18 34" src="https://github.com/user-attachments/assets/457879f7-1768-4c86-af5e-b203c895292b">

We don't see any error logs on the server side, but only informational logs confirming that you requested a password reset with success.

The "anti spam" system you're mentioning usually adds logs in our backend: what message did you see exactly?


In the mean time, I'm triggering a new password reset. Please check your email spam box, or contact your email adfministrator

**Comment by dduportal** [comment]
> In the mean time, I'm triggering a new password reset. Please check your email spam box, or contact your email adfministrator

Email successfully sent to the `recipient-domain` `exabeam.com` 2 min ago (and acknowledged by their email server at the`timestamp` `1733152902.7492104`).

**Comment by samer-faour-exa** [comment]
No email received and nothing in spam. We have Atlassian already and have SSO. Maybe that's why it was failing.

I managed to create an account with a different email from another location since it seems my home ISP was blocked completely. I tried waiting 12 hrs, 24 hrs, etc. was never able to get past the block. Happy to try again if you would like to troubleshoot RCA

**Comment by dduportal** [comment]
> No email received and nothing in spam. We have Atlassian already and have SSO. Maybe that's why it was failing.

FYI, Jenkins accounts are managed in a private LDAP, accounts are unrelated with Atlassian or any SSO. So the problem you are facing are unrelated.

> I managed to create an account with a different email from another location since it seems my home ISP was blocked completely. I tried waiting 12 hrs, 24 hrs, etc. was never able to get past the block. Happy to try again if you would like to troubleshoot RCA

What is(are) the outbound IP(s) when you are having issues?

**Comment by dduportal** [comment]
> No email received and nothing in spam

Then you have to contact your email administrator. Mailgun logs shows the emails were sent and acknowledged by the email server at `exabeam.com`: there isn't anything much we can do on that part without them checking what is happening inside exabeam mail servers.

Your technique to use another email is a good and valid one though.

**Comment by samer-faour-exa** [comment]
> > No email received and nothing in spam. We have Atlassian already and have SSO. Maybe that's why it was failing.
> 
> FYI, Jenkins accounts are managed in a private LDAP, accounts are unrelated with Atlassian or any SSO. So the problem you are facing are unrelated.
> 
> > I managed to create an account with a different email from another location since it seems my home ISP was blocked completely. I tried waiting 12 hrs, 24 hrs, etc. was never able to get past the block. Happy to try again if you would like to troubleshoot RCA
> 
> What is(are) the outbound IP(s) when you are having issues?

209.195.84.248

**Comment by dduportal** [comment]
> 209.195.84.248

I confirm there are no IP blocker for this IP or any of its parents CIDRs (ref. https://github.com/jenkins-infra/account-app/blob/7fcfe8d3cd3a7775b07cda6ddd77774063abf081/src/main/java/org/jenkinsci/account/Application.java#L968).

What is the error you're seeing exactly? (screenshot? What do you see on the web console)

**Comment by samer-faour-exa** [comment]
Very strange... it is working now. Feel free to close.

It was a long text saying you are blocked because we can't verify you. Something along these lines with a link to open an issue here. I did not screenshot or save it since it was so consistent. I tried with 3 different emails and usernames over 2 days and it would never let me create an account
