### ISSUE TITLE
Rename freestyle-project to freestyle-project-plugin

### ISSUE THREAD

**Issue by slide** [jenkins-infra/helpdesk#4434]
### Service(s)

GitHub

### Summary

During hosting, the github repo name was not set to the -plugin standard. Please update github.com/jenkinsci/freestyle-project to be named freestyle-project-plugin

**Comment by timja** [comment]
This is only partially hosted I'd rather fix the problem.

I think GitHub APIs were being slow yesterday, i'll try again today otherwise will add a retry / delay

**Comment by timja** [comment]
Resolved with https://github.com/jenkins-infra/repository-permissions-updater/pull/4209

I've deleted the half setup repository.

The only change that had been added was a PR with this file:

```jelly
<?jelly escape-by-default='true'?>
<div>
    Plugin to provide the Freestyle job type to Jenkins.
</div>
```
