### ISSUE TITLE
change the stage view to pipeline graph view on infra.ci and then ci.jio

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4435]
### Service(s)

ci.jenkins.io, infra.ci.jenkins.io

### Summary

change the staging view to the pipeline graph view in the build page view

**Comment by smerle33** [comment]
I found this https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/312 that would do the trick, I tried manually on the UI on infra.ci which did this : 

<img width="1238" alt="Capture d’écran 2024-12-05 à 10 49 50" src="https://github.com/user-attachments/assets/68224bcd-60ed-4751-9f66-ee5802f64b20">


by comparing the as code version, it was this part: 
```
pipelineGraphView:
    showGraphOnBuildPage: true
    showGraphOnJobPage: true
```

but then I saw this in the source code https://github.com/jenkins-infra/kubernetes-management/blob/625a0b6fb2e53a597cfcbdb31e5ce105d63f6796/config/jenkins_infra.ci.jenkins.io.yaml#L740-L742

```
          pipelineGraphView:
            showGraphOnBuildPage: true
            showGraphOnJobPage: false # change to true if pipeline-stage-view is removed
```

pointing to https://github.com/jenkins-infra/kubernetes-management/pull/4889

so I need confirmation that the problem have been solved and we can have both plugins installed or if we need to choose between them.

**Comment by timja** [comment]
I think you need to uninstall the stage view plugin

**Comment by smerle33** [comment]
waiting for wednesday to avoid any hickup with the weekly release

**Comment by dduportal** [comment]
@smerle33 don't forget to open your RFE about build times in the plugin's JIRA ;) I also have one to open

**Comment by smerle33** [comment]
> @smerle33 don't forget to open your RFE about build times in the plugin's JIRA ;) I also have one to open

I think it's on github issues for this plugin https://plugins.jenkins.io/pipeline-graph-view/
