### ISSUE TITLE
Invite new Jenkins board members to the jenkins-infra board team

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4437]
### GitHub repositories

https://github.com/orgs/jenkins-infra/teams/board?query= shows that previous board members are still in the board group, including:

* Kohsuke Kawaguchi
* Ullrich Hafner

Those previous board members should be replaced with the newly elected board members.

### GitHub users to have permission

@jonesbusy
@slide

### Permission level

Admin

### Justification

Newly elected members of the Jenkins governance board.  See [announcement blog post](https://www.jenkins.io/blog/2024/12/03/election-results/).

**Comment by dduportal** [comment]
- Kohsuke and Ullrich have been removed
- Added Valentin and Alex (they received an invitation which they have to accept)

**Comment by jonesbusy** [comment]
Thanks!

**Comment by MarkEWaite** [comment]
Thanks to all!
