### ISSUE TITLE
Refine updatecli to not propose www.bing.com version updates

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#4438]
### Reproduction steps

1. Review pull request jenkins-infra/packer-images#1576

### Expected Results

www.bing.com is not proposed as a version update

### Actual Results

www.bing.com is being proposed as a version update

**Comment by dduportal** [comment]
- Root cause described in https://github.com/jenkins-infra/jenkins-infra/pull/3763#issuecomment-2519401002
- Proposed solution in https://github.com/jenkins-infra/jenkins-infra/pull/3763#issuecomment-2519406881

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/3771 deployed with success
