### ISSUE TITLE
[get.jenkins.io/updates.jenkins.io] mirrors system keep loosing ability to evaluate client IP locations

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4441]
### Service(s)

get.jenkins.io, Update center

### Summary

Initially caught in https://community.jenkins.io/t/can-no-longer-update-through-update-center-or-yum-update/24376/8, it appears that since the past 3-4 days, all of our mirrorbits instance starts to loose the ability to evaluate the geolocation of client IP.

It does not stop requests to be served, but it messes up the mirror selection, leading to poor performances for end users.

**Comment by dduportal** [comment]
The problem hasn't resurfaced in the past 3 days. It means we have to refine the Geoip protocol as explained above.

Assigning to @smerle33 for next step as he started to work on this topic

**Comment by smerle33** [comment]
the plan is to improve the geoipupdate process to have a check between existing mmdb databases files and the updated ones to only copy if a change occur.
also adding a rollout restart after upgrade if occured

**Comment by smerle33** [comment]
geoip localisation still ok, lets check in a few days !

**Comment by dduportal** [comment]
> geoip localisation still ok, lets check in a few days !

I guess monday (e.g. in 3 days)? Be careful, i'll be off that day

**Comment by smerle33** [comment]
geo localisation still ok as per today monday 16 dec 7h40UTC
