### ISSUE TITLE
register account

### ISSUE THREAD

**Issue by chunshengma666** [jenkins-infra/helpdesk#4449]
### Type(s) of account issue

I've been blocked by the anti-spam system

### jenkins.io account username

chunshengma

### jenkins.io account email

machunsheng123456@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by dduportal** [comment]
Hi @chunshengma666 , thanks for opening this issue.

Can you retry with a private browsing session? Our logs indicates you're having cookies in your webbrowser from a former session on accounts.jenkins.io.

**Comment by dduportal** [comment]
Ping @chunshengma666 , any news?

**Comment by dduportal** [comment]
Closing as no answer from reporter
