### ISSUE TITLE
Cannot login to my account

### ISSUE THREAD

**Issue by georginskaya** [jenkins-infra/helpdesk#4451]
### Type(s) of account issue

I didn't receive any email

### Summary

I don"t remember my jenkins username and cannot login.  I do not receive any password recovery emails either. Could you please help me further?

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @georginskaya , what is the email associated to this account?

Also, what is the expected usage of this account?

**Comment by georginskaya** [comment]
The email should be this alenageorgin08@gmail.com or this georginskaya@gmail.com 

I managed to login today but my computer restarted and now I lost access again. I tried 10000 different password and login name combinations but I dont remember the right one.

**Comment by dduportal** [comment]
Hi @georginskaya , it looks like you are mixing your Jenkins account management with the public jenkins.io account used for public sites.

if you are logging on localhost then it means we cannot help you as the Jenkins server you are running has its own authentication realm.
