### ISSUE TITLE
[JIRA] Change default assignee for plugin

### ISSUE THREAD

**Issue by malice00** [jenkins-infra/helpdesk#4452]
### Service(s)

Jira

### Summary

A while back, I adopted the calendar-view-plugin. Several weeks back, I noticed that I do not get the notifications for new JIRA issues, because either the default assignee is empty, or it is still the original dev. Seeing how there was no response from the dev when I requested the adoption, I would like to have the default assignee changed to myself, so I get notifications when new issues are posted.

Now, the questions is: can I do this myself somehow, or does this need to be changed by someone else? If the former, please let me know how. If the latter, please change this. Thanks.

**Comment by MarkEWaite** [comment]
Thanks for adopting the calendar-view plugin.  You are now the default assignee for calendar-view-plugin issues.
