### ISSUE TITLE
CI/CD check stuck for a PR at stats.jenkins.io

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#4453]
### Service(s)

stats.jenkins.io

### Summary

The `jenkins` CI/CD check at https://github.com/jenkins-infra/stats.jenkins.io/pull/268 has been stuck as queued for more than 3 hours:

<img width="936" alt="Screenshot 2024-12-18 at 3 01 02 PM" src="https://github.com/user-attachments/assets/dbf504cd-a13b-493a-86b7-6b6c19211850" />

However, this check is not critical, and is not required for the maintainer(s) to merge the PR. 

### Reproduction steps

N/A

**Comment by dduportal** [comment]
- #4454 has been fixed
- https://github.com/jenkins-infra/stats.jenkins.io/pull/268 shows all builds have been unstuck.

Thanks for reporting, and sorry for the inconvenience
