### ISSUE TITLE
To request Jan to be added to Jenkins core PR reviewers

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#4458]
### GitHub repositories

https://github.com/jenkinsci/jenkins

### GitHub users to have permission

@janfaracik

### Permission level

Maintain

### Justification

Jan has contributed to the Jenkins core consistently, has shown expert knowledge of the repository, and has gotten 4 votes for this request which he started on the Jenkins dev mailing list on December 2nd, 2024 UTC with record available at https://groups.google.com/g/jenkinsci-dev/c/SikBGfVyeGk/m/fo68D2sLAQAJ.

**Comment by timja** [comment]
Jan was added a couple of weeks ago, Alex added him after a few +1s I believe

https://github.com/orgs/jenkinsci/teams/core-pr-reviewers

**Comment by krisstern** [comment]
Awesome! Thanks for confirming

**Comment by krisstern** [comment]
Just one more question about this issue: I recall not seeing the a green check next to Jan's username on the PR's approved by him in the Jenkins core repo even after he was supposed to have been made a core maintainer... Am I mistaken, or is that intended?

**Comment by timja** [comment]
> Just one more question about this issue: I recall not seeing the a green check next to Jan's username on the PR's approved by him in the Jenkins core repo even after he was supposed to have been made a core maintainer... Am I mistaken, or is that intended?

core-pr-reviewers just gets triage access and added to a team which is often requested to review PRs
core will get the green tick

**Comment by krisstern** [comment]
Hey thanks for the information @timja!
