### ISSUE TITLE
Add mawinter69 to hosting team

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#4464]
### GitHub repositories

Hosting team

### GitHub users to have permission

@mawinter69

### Permission level

Admin

### Justification

Approved on mailing list and CLA has been signed

**Comment by timja** [comment]
@dduportal you able to do this please when you get a sec? https://github.com/orgs/jenkins-infra/teams/hosting

**Comment by dduportal** [comment]
- Mailing list thread: https://groups.google.com/g/jenkinsci-dev/c/Kaw-F4X9ch0
- I've invited @mawinter69 to https://github.com/orgs/jenkins-infra/teams/hosting
- @timja I've also added you as maintainer of the team as per your release officer role
