### ISSUE TITLE
[INFRA-598] Confirm with JFrog support that the user 'jfrog' in Artifactory isn't bogus

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#457]
<p>Backing realm is LDAP which doesn't really make sense IMO.</p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-598" target="_blank">Confirm with JFrog support that the user 'jfrog' in Artifactory isn't bogus</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing because it's an old issue.
