### ISSUE TITLE
Docker | Plugins Installation | First time setup

### ISSUE THREAD

**Issue by backtrackshubham** [jenkins-infra/helpdesk#5]
### Service

plugins.jenkins.io

### Summary

For 2 months I have seldom tried to run latest image for running jenkins on my system (Mac) on docker using `docker run -p8080:8080 -p50000:50000  jenkins/jenkins:lts-jdk11` I was able to successfully complete the setup for jenkins, with the recommended plugins installed, but for two months whenever I have tried it fails with the following error for each plugin
```
Failed to install sshd
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
.
.
.
Caused: sun.security.validator.ValidatorException: PKIX path building failed
.
.
.
Caused: javax.net.ssl.SSLHandshakeException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
.
.
.
Caused: javax.net.ssl.SSLHandshakeException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
.
.
.
Caused: java.io.IOException: Failed to load https://updates.jenkins.io/download/plugins/sshd/3.1.0/sshd.hpi to /var/jenkins_home/plugins/sshd.jpi.tmp
.
.
.
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/sshd/3.1.0/sshd.hpi (redirected to: https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/sshd/3.1.0/sshd.hpi)
```

I could see a redirection happening but even using the json from the redirected link doesn't work, I am using the latest images in docker hub and not specific network configuration is there like proxy or vpn.

Thanks

### Reproduction steps

# Run
```bash
docker run -p8080:8080 -p50000:50000  jenkins/jenkins:lts-jdk11
```
## Watch over the logs for the container

System: Using Docker desktop 4.3.1, MacOS big Sur

**Comment by timja** [comment]
Which mirror is this failing on? Can you enable verbose logs?

**Comment by timja** [comment]
It's using let's encrypt so possibly you have an outdated truststore or Java version that's picking up the old chain?

I assume you can reach `https://mirrors.tuna.tsinghua.edu.cn` in a browser?

**Comment by dduportal** [comment]
Some things to try:
- For @backtrackshubham :
  -Try to reproduce with the [`jenkins/lts-alpine-jdk11`](https://hub.docker.com/layers/jenkins/jenkins/lts-alpine-jdk11/images/sha256-5ac4c620e28b0b62ba6ca715ddbca3f661fafd522a3983292b1f784ca1d2fa56?context=explore)
  - What is the exact version of java involved when the issue happen?

- Also, https://github.com/jenkinsci/docker#setting-update-centers might help to switch to another mirror

**Comment by backtrackshubham** [comment]
Hello @timja @dduportal thanks for the quick response, you guys are doing an awesome job
I am able to reach https://mirrors.tuna.tsinghua.edu.cn in the browser
> I assume you can reach https://mirrors.tuna.tsinghua.edu.cn in a browser?

Since its docker how I having an outdated version makes any difference
> It's using let's encrypt so possibly you have an outdated truststore or Java version that's picking up the old chain?

Same exact issue for this image
> Try to reproduce with the jenkins/lts-alpine-jdk11

If you are asking inside the container, it is 
```
/ $ java -version
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
/ $ 
```
> What is the exact version of java involved when the issue happens?

I could  try to update the update center, actually I did but that didn't work either same issue was there, i tried to use `-eJENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins`
> Also, https://github.com/jenkinsci/docker#setting-update-centers might help to switch to another mirror

**Comment by dduportal** [comment]
Thanks for this reproduction elements @backtrackshubham it's really useful.

We are trying to reproduce on our side (by forcing the mirror with the `JENKINS_UC` variable to isolate the issue (either on Docker image, Jenkins, mirror, or something else).

Another question fro you @backtrackshubham : if you run the Jenkins WAR outside Docker (e.g. on macOS, with a `java -jar <path to Jenkins WAR>), do you have the same issue as well?

**Comment by dduportal** [comment]
I confirm that I can reproduce the error with `docker run -p8080:8080 -p50000:50000 -eJENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins jenkins/jenkins:lts-jdk11` (Belgium ISP).

**Comment by lemeurherve** [comment]
I didn't reproduce the error with `docker run -p8080:8080 -p50000:50000 -eJENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins jenkins/jenkins:lts-jdk11` and successfully installed the suggested plugins. (French ISP)

**Comment by dduportal** [comment]
Since we are at least 2 different persons with random (or often, or always) issue with this mirror, I propose the following:

## Short Term

@backtrackshubham you have to select another mirror to force on your installation to unblock you for now.
You can append the `?mirrorlist` to the URL of any plugin to have a nice Web Interface to see what mirrors are close to your location.
For instance https://get.jenkins.io/plugins/sshd/3.1.0/sshd.hpi?mirrorlist .

Then you might want to stick with the `-eJENKINS_UC=<mirror>` solution for now

## Long Term

For the infra team, I propose the following:

- Disable the mirror temporarly (need knwoledge sharing with @olblak and/or @MarkEWaite )
- contact the support of this mirror to let them know about the SSL random failures. Smells like their SSL termination might be distributed and one of their nodes is failing.
- Once they'll have fixed the issue, we can enable the mirror again after testing

**Comment by timja** [comment]
It may not be an issue in the mirror it could be a problem with cacerts in the Java image.

It'll be to do with the Let's encrypt root expiration last year where they did creative tricks which caused a lot of pain

**Comment by backtrackshubham** [comment]
Thanks for the input team,
> I confirm that I can reproduce the error with `docker run -p8080:8080 -p50000:50000 -eJENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins jenkins/jenkins:lts-jdk11` (Belgium ISP).

Also while trying above I could see it was string using a redirecting form  https://updates.jenkins.io not sure if this is correct behavior.

So I am using an Indian ISP and we have tried on another system with docker and war both, and got the same issue.

Cool tip for using another mirror, I will try and update soon.

**Comment by timja** [comment]
Yeah redirecting is expected a service called mirrorbits is used to geographically loadbalance to different mirrors

**Comment by backtrackshubham** [comment]
Okay I understand but now I just tried this
`docker run -eJENKINS_UC=https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/ -p8080:8080 -p50000:50000 jenkins/jenkins:lts-alpine-jdk11`

but still in the error logs I am seeing 

```
Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/sshd/3.1.0/sshd.hpi 
(redirected to: https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/sshd/3.1.0/sshd.hpi)
```
Again it is trying to the china one

**Comment by MarkEWaite** [comment]
> Since we are at least 2 different persons with random (or often, or always) issue with this mirror, I propose the following:
> 
> ## Short Term
> @backtrackshubham you have to select another mirror to force on your installation to unblock you for now. You can append the `?mirrorlist` to the URL of any plugin to have a nice Web Interface to see what mirrors are close to your location. For instance https://get.jenkins.io/plugins/sshd/3.1.0/sshd.hpi?mirrorlist .
> 
> Then you might want to stick with the `-eJENKINS_UC=<mirror>` solution for now
> 
> ## Long Term
> For the infra team, I propose the following:
> 
> * Disable the mirror temporarily (need knowledge sharing with @olblak and/or @MarkEWaite )

I would strongly prefer that we not disable the mirror.  It is the primary mirror used by users in India, China, and most of Asia.  I don't think two users detecting failures should be enough for us to disable the mirror that serves a major part of the globe.  That will shift the load to the mirror(s) in Japan and may shift some of the load to mirrors in Europe.  I'm not sure those mirrors are ready to handle the load that is being served by the mirror at Tsinghua University.

> * contact the support of this mirror to let them know about the SSL random failures. Smells like their SSL termination might be distributed and one of their nodes is failing.

I agree that we should contact the team that maintains that mirror.  They've been quite responsive in the past.  I've opened a question on their mailing list at https://groups.google.com/g/tuna-general .  The message is awaiting approval.

> * Once they'll have fixed the issue, we can enable the mirror again after testing

**Comment by shankerwangmiao** [comment]
Hi, all. I'm the admin of TUNA mirror site. According to my experience, it is probably related to the certificate by Let's Encrypt.

**Comment by MarkEWaite** [comment]
> Hi, all. I'm the admin of TUNA mirror site. According to my experience, it is probably related to the certificate by Let's Encrypt.

We thought so as well initially, but the Docker image that is failing the request has been updated to the most recent Java release and the most recent base operating system release.  The issue was seen both with a Docker image base operating system from Alpine and from Debian.

**Comment by shankerwangmiao** [comment]
The image I used is 

```
jenkins/jenkins                                lts-alpine-jdk11           8ca0142efac4        5 weeks ago         260MB
```

**Comment by shankerwangmiao** [comment]
According to the access log analysis, we are providing 680k reqs and 823.6GB data per day on average in recent 7 days. 99% of the responses are normal 200. I have not seen any abnormal change on the traffic.

**Comment by timja** [comment]
It's not that easy to test this via Jenkins because of mirror redirection.

Although I can download the json metadata just fine by setting my update center to
https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/dynamic-stable-2.319.1/update-center.json

The code for downloading is here:
https://github.com/jenkinsci/jenkins/blob/02eecd8a49b24255977ed336f4a19237455dc54b/core/src/main/java/hudson/model/UpdateCenter.java#L1260

Seems to just use `URLConnection`

I've copied this test script out and tried to download myself:
https://www.codejava.net/java-se/networking/use-httpurlconnection-to-download-file-from-an-http-url

@backtrackshubham / @dduportal are you able to run the code below in your container with:

```
apt update && apt install -y vim
vim HttpDownloadUtility.java
# paste the code in the collapsed section below and save
# then run:
java HttpDownloadUtility.java
```

<details>
<summary>Code</summary>

```java
package net.codejava.networking;
 
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
 
/**
 * A utility that downloads a file from a URL.
 * @author www.codejava.net
 *
 */
public class HttpDownloadUtility {
    private static final int BUFFER_SIZE = 4096;

    public static void main(String[] args) throws Exception {
	    downloadFile("https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/sshd/3.1.0/sshd.hpi", "/tmp");
    }
 
    /**
     * Downloads a file from a URL
     * @param fileURL HTTP URL of the file to be downloaded
     * @param saveDir path of the directory to save the file
     * @throws IOException
     */
    public static void downloadFile(String fileURL, String saveDir)
            throws IOException {
        URL url = new URL(fileURL);
        HttpURLConnection httpConn = (HttpURLConnection) url.openConnection();
        int responseCode = httpConn.getResponseCode();
 
        // always check HTTP response code first
        if (responseCode == HttpURLConnection.HTTP_OK) {
            String fileName = "";
            String disposition = httpConn.getHeaderField("Content-Disposition");
            String contentType = httpConn.getContentType();
            int contentLength = httpConn.getContentLength();
 
            if (disposition != null) {
                // extracts file name from header field
                int index = disposition.indexOf("filename=");
                if (index > 0) {
                    fileName = disposition.substring(index + 10,
                            disposition.length() - 1);
                }
            } else {
                // extracts file name from URL
                fileName = fileURL.substring(fileURL.lastIndexOf("/") + 1,
                        fileURL.length());
            }
 
            System.out.println("Content-Type = " + contentType);
            System.out.println("Content-Disposition = " + disposition);
            System.out.println("Content-Length = " + contentLength);
            System.out.println("fileName = " + fileName);
 
            // opens input stream from the HTTP connection
            InputStream inputStream = httpConn.getInputStream();
            String saveFilePath = saveDir + File.separator + fileName;
             
            // opens an output stream to save into file
            FileOutputStream outputStream = new FileOutputStream(saveFilePath);
 
            int bytesRead = -1;
            byte[] buffer = new byte[BUFFER_SIZE];
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                outputStream.write(buffer, 0, bytesRead);
            }
 
            outputStream.close();
            inputStream.close();
 
            System.out.println("File downloaded");
        } else {
            System.out.println("No file to download. Server replied HTTP code: " + responseCode);
        }
        httpConn.disconnect();
    }
}
```


</details>

**Comment by backtrackshubham** [comment]
No @timja got the same error
```
/ # java HttpDownloadUtility.java
Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at net.codejava.networking.HttpDownloadUtility.downloadFile(HttpDownloadUtility.java:32)
	at net.codejava.networking.HttpDownloadUtility.main(HttpDownloadUtility.java:19)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at java.base/sun.security.validator.Validator.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at net.codejava.networking.HttpDownloadUtility.downloadFile(HttpDownloadUtility.java:32)
	at net.codejava.networking.HttpDownloadUtility.main(HttpDownloadUtility.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Unknown Source)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Unknown Source)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
	... 33 more
/ # 
```

**Comment by backtrackshubham** [comment]
Also team, as mentioned that issue was seen in debian and alpine, I just tried the centos version `jenkins/jenkins:centos7-jdk8` and it also failed with same error, also can anyone please check if the env `JENKINS_UC` works and tries to fetch from the specified mirror as in my case in logs it always goes to **tuna** one,

>Can you provide the exact hash and tag of the image where the error is generated so that we can be on the same page.

I check the version when you posted the image used and found that it is the same one but here are the images
```
~$ docker images | grep jenkins
jenkins/jenkins                                                    centos7-jdk8                        fa502d00818c   2 days ago      724MB
jenkins/jenkins                                                    lts-alpine-jdk11                    8ca0142efac4   5 weeks ago     260MB
jenkins/jenkins                                                    lts-jdk11                           2a4bbe50c40b   5 weeks ago     441MB
jenkins/jenkins                                                    latest                              a7aa4a28243e   6 weeks ago     442MB
jenkins/jenkins                                                    2.311-alpine-jdk8                   4605bee91e8e   3 months ago    376MB
```

**Comment by backtrackshubham** [comment]
Also an FYI is I am able to access the mirror as well as download the file `https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/sshd/3.1.0/sshd.hpi` from browser

**Comment by backtrackshubham** [comment]
> No @timja got the same error
> 
> ```
> / # java HttpDownloadUtility.java
> Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
> 	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
> 	at net.codejava.networking.HttpDownloadUtility.downloadFile(HttpDownloadUtility.java:32)
> 	at net.codejava.networking.HttpDownloadUtility.main(HttpDownloadUtility.java:19)
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
> 	at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
> 	at java.base/sun.security.validator.Validator.validate(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
> 	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
> 	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
> 	at net.codejava.networking.HttpDownloadUtility.downloadFile(HttpDownloadUtility.java:32)
> 	at net.codejava.networking.HttpDownloadUtility.main(HttpDownloadUtility.java:19)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Unknown Source)
> 	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Unknown Source)
> 	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Unknown Source)
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
> 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
> 	at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
> 	... 33 more
> / # 
> ```

So the above log was from one of the docker containers of the jenkins, however I tried some more tests with jdk installed in my machine as well as a docker container of `openjdk:latest` and used the `HttpDownloadUtility.java` they even produced the same results.

**Comment by timja** [comment]
Any chance you want to try upgrading to macOs Monterey?

I had weird issues in my browser with a site on big Sur on an M1 machine and no one else could reproduce it.
When I upgraded to Monterey it fixed it =/

But I don't understand why it would fail in docker.

That exact script above passes for me in docker

**Comment by backtrackshubham** [comment]
That's looks like a real wierd issue, but glad it was fixed but yeah how you had a problem in browser is doubtful to me anyways, yeah the OS would be soon upgraded from the enterprises side will check then, but on the same lines I am also thinking why it was working 2 months back when I was on the same OS

**Comment by shankerwangmiao** [comment]
Can you provide a packet capture in that container? 

Packet capture can be done via:

```
apt update && apt install -y tcpdump
# just before reproduce the ssl issue
tcpdump -i eth0 -w /tmp/1.pcap &
# then run
java HttpDownloadUtility.java
# and send tcpdump to foreground can stop capture
fg
(Press Ctrl-C)
# copy  /tmp/1.pcap out and upload here
```

**Comment by dduportal** [comment]
> Okay I understand but now I just tried this `docker run -eJENKINS_UC=https://ftp.yz.yamagata-u.ac.jp/pub/misc/jenkins/ -p8080:8080 -p50000:50000 jenkins/jenkins:lts-alpine-jdk11`
> 
> but still in the error logs I am seeing
> 
> ```
> Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/sshd/3.1.0/sshd.hpi 
> (redirected to: https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/sshd/3.1.0/sshd.hpi)
> ```
> 
> Again it is trying to the china one
> 
> Then I tried with (EU Mirror) `docker run -eJENKINS_UC=https://ftp.halifax.rwth-aachen.de/jenkins -p8080:8080 -p50000:50000 jenkins/jenkins:lts-alpine-jdk11`
> 
> then also I see the same
> 
> ```
> Caused: java.io.IOException: Failed to download from https://updates.jenkins.io/download/plugins/junit/1.53/junit.hpi 
> (redirected to: https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/junit/1.53/junit.hpi)
> ```
> 
> now I feel either the env var `-eJENKINS_UC` not behaving correctly or the Jenkins java.


@backtrackshubham I'm sorry, I made a mistake by suggesting the JENKINS_UC. 
It allowed the index (the JSON file) to be downloaded from another mirror, but then each plugin is still requested from updates.jenkins.io (so it always ends up in the tuna mirror for you).

**Comment by backtrackshubham** [comment]
> Can you provide a packet capture in that container?
> 
> Packet capture can be done via:
> 
> ```
> apt update && apt install -y tcpdump
> # just before reproduce the ssl issue
> tcpdump -i eth0 -w /tmp/1.pcap &
> # then run
> java HttpDownloadUtility.java
> # and then send tcpdump to foreground and stop capture
> fg
> (Press Ctrl-C)
> # copy  /tmp/1.pcap out and upload here
> ```

Here is the dump @shankerwangmiao 
[1.pcap.zip](https://github.com/jenkins-infra/helpdesk/files/7823979/1.pcap.zip)

**Comment by shankerwangmiao** [comment]
Hi, according to the packets captured, I can conclude that your issue has no relevance with TUNA mirror site or Jenkins infrastructure. Your TLS connection to TUNA mirror site and DNS resolution is hijacked, and that's why Jenkins would complain about the error of certificate chain. You need to contact your network administrator.

**Comment by Harry-Chen** [comment]
> I agree that we should contact the team that maintains that mirror. They've been quite responsive in the past. I've opened a [question](https://groups.google.com/g/tuna-general/c/qh66VP8M-fI/m/GpF3IPnKBAAJ) on their mailing list at https://groups.google.com/g/tuna-general .

@MarkEWaite Thanks for your notification! FYI we now track our bug reports at [tuna/issues](https://github.com/tuna/issues/issues), and next time you can just create issues there.

**Comment by backtrackshubham** [comment]
> Hi, according to the packets captured, I can conclude that your issue has no relevance with TUNA mirror site or Jenkins infrastructure. Your TLS connection to TUNA mirror site and DNS resolution is hijacked, and that's why Jenkins would complain about the error of certificate chain. You need to contact your network administrator.

Thanks @shankerwangmiao for the investigation and from it I could sense that is something network specific on the client but I am not able to understand how @dduportal  was able to reproduce the issue, also I tried to do some insight analysis, so (Before this everything was without using any VPN and proxies), now I could see while I was on VPN configuration provided by my organization which is for Herzo (EU) and @dduportal has a Belgium ISP (EU) can we correlate these two scenarios ?, also my organization also provided a VPN configuration for China (I tried that since mirror we are referring is based on China) , when I tried this VPN config and ran the container which gave the following error which affirms it could be something at my network administration policies but is there something else which we might be missing ?
**Error while using China VPN config**
```
java.net.UnknownHostException: get.jenkins.io
```

**Comment by shankerwangmiao** [comment]
> > Hi, according to the packets captured, I can conclude that your issue has no relevance with TUNA mirror site or Jenkins infrastructure. Your TLS connection to TUNA mirror site and DNS resolution is hijacked, and that's why Jenkins would complain about the error of certificate chain. You need to contact your network administrator.
> 
> 
> 
> Thanks @shankerwangmiao for the investigation and from it I could sense that is something network specific on the client but I am not able to understand how @dduportal  was able to reproduce the issue, also I tried to do some insight analysis, so (Before this everything was without using any VPN and proxies), now I could see while I was on VPN configuration provided by my organization which is for Herzo (EU) and @dduportal has a Belgium ISP (EU) can we correlate these two scenarios ?, also my organization also provided a VPN configuration for China (I tried that since mirror we are referring is based on China) , when I tried this VPN config and ran the container which gave the following error which affirms it could be something at my network administration policies but is there something else which we might be missing ?
> 
> **Error while using China VPN config**
> 
> ```
> 
> java.net.UnknownHostException: get.jenkins.io
> 
> ```
> 
> 
> 
> I will however probe this with network team here.

Negative, your issue is apparently related to your organization. I believe the two issues are independent.

**Comment by backtrackshubham** [comment]
@dduportal  may you please try once again to reproduce the issue, so we can be sure that it is specific to one particular network configuration

**Comment by dduportal** [comment]
Hello @backtrackshubham ! I cannot reproduce: is it still an issue for you? Please reopen this issue if it is the case.
