### ISSUE TITLE
[INFRA-657] Migrate update-site rsyncing jobs from www-data to mirrorbrain

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#505]
<p>We've moved <b>most</b> of the rsyncing tasks to the update-site to the <tt>mirrorbrain</tt> user, but the update center generation's <tt>generate.sh</tt> still uses <tt>www-data</tt>.</p>

<p>We need to remove that and make sure the <tt>www-data</tt> has <tt>/usr/bin/nologin</tt> as their shell</p>

---
<details><summary><i>Originally reported by <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-657" target="_blank">Migrate update-site rsyncing jobs from www-data to mirrorbrain</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
@dduportal related to what we saw this morning. To be closed?

**Comment by dduportal** [comment]
@lemeurherve we want to do the opposite of this issue (e.g. rolling back any action) as per the mirrorbrain cleanup (tracked in #2970

**Comment by dduportal** [comment]
Quick note: see https://github.com/jenkins-infra/helpdesk/issues/2970#issuecomment-2026774775
In the end, we are keeping the `mirrorbrain` user for rsync usages as explained in this issue initially.
