### ISSUE TITLE
[INFRA-666] (JIRA) Can't navigate to password reset UI

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#514]
<p>I navigate to my jenkins.io JIRA account page in order to reset my password. Please add this option to the top right menu.</p>

---
<details><summary><i>Originally reported by <a title="Andrew Pennebaker" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mcandre">mcandre</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-666" target="_blank">(JIRA) Can't navigate to password reset UI</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as we're using Github issues now.
