### ISSUE TITLE
[INFRA-47] *.jenkins-ci.org are not accessible via IPV6

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#62]
<p>As per title.</p>

<p>None of the sites are accessible via IPV6, and while this is a trivial matter for the most part it does prevent automatic updates via Linux package managers using pkg.jenkins-ci.org.</p>

---
<details><summary><i>Originally reported by <a title="_" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=namtabmai">namtabmai</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-47" target="_blank">*.jenkins-ci.org are not accessible via IPV6</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Reopened
<li><b>priority</b>: Trivial
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing by following up in https://github.com/jenkins-infra/helpdesk/issues/3227#issuecomment-1614470301
