### ISSUE TITLE
[INFRA-863] Enable FindBugs reporting in the Jenkins core PR builder

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#622]
---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-863" target="_blank">Enable FindBugs reporting in the Jenkins core PR builder</a></i></summary>
<i><ul>
<li><b>status</b>: Reopened
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
this was done
