### ISSUE TITLE
[INFRA-910] Automating release of Jenkins

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#663]
<p>Todo:</p>

<ul class="alternate" type="square">
	<li>War signing</li>
	<li>Windows installer signing</li>
	<li>Agents
	<ul class="alternate" type="square">
		<li>Win</li>
		<li>Mac</li>
	</ul>
	</li>
	<li>What requirements would there be for building and signing a release in Jenkins?</li>
</ul>

<p><b>Ideal</b> release manager workflow:</p>

<ol>
	<li>Navigate to trusted.ci.jenkins.io</li>
	<li>Enter Git SHA1 and release version number</li>
	<li>Jenkins builds all the artifacts for the release (wars, containers, packages, installers)</li>
	<li>Any smoke-testing possible</li>
	<li>Publish the built artifacts to their respective repositories</li>
	<li>Email notification(s) to release manager(s) regardless of success/failure</li>
</ol>

---
<details><summary><i>Originally reported by <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-910" target="_blank">Automating release of Jenkins</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Critical
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing due to age. The Jenkins releases are already automated on release.ci.jenkins.io since at least 2020, with a weekly trigger every tuesday.
