### ISSUE TITLE
[INFRA-960] Migrate ATH to ci.jenkins.io

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#707]
<p>The effort to create Jenkins file already ongoing <a href="https://github.com/jenkinsci/acceptance-test-harness/pull/157" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/acceptance-test-harness/pull/157</a> but I suspect it does not keep up with changes in Pipeline itself. The motivation behind this is</p>

<ul class="alternate" type="square">
	<li>Parallelize the tests</li>
	<li>Run docker based tests during CI builds.</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Oliver Gondža" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olivergondza">olivergondza</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-960" target="_blank">Migrate ATH to ci.jenkins.io</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as ATH is in ci.jenkins.io since years.
