### ISSUE TITLE
[INFRA-970] Show "_unsorted" component in the top of the default JENKINS by-component dashboard

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#716]
<p>Just in case it's possible...</p>

<p>Reasons:</p>
<ul>
	<li>Highlight this component for contributors (now it's only me who processes the incoming stuff)</li>
	<li>Highlight the component for users. If they do not know where to submit the issue, better to have a single component than a random selection</li>
</ul>

---
<details><summary><i>Originally reported by <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-970" target="_blank">Show "_unsorted" component in the top of the default JENKINS by-component dashboard</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Oleg Nenashev" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=oleg_nenashev">oleg_nenashev</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by lemeurherve** [comment]
Closing as we're using Github issues for the project INFRA now.
