### ISSUE TITLE
Remove Create permissions for all in HOSTING & INFRA projects on Jira

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#8]
### Service

Jira

### Summary

New hosting flow is going well.

We're decommissioning the old flow now

People should not be able to create new hosting tickets in Jira after this.

We'll leave the existing ones there

**Comment by timja** [comment]
I've created a scheme called:

[No create permission scheme](https://issues.jenkins.io/secure/admin/EditPermissions!default.jspa?schemeId=10370)

Which I've assigned to the HOSTING project but it could be used for the INFRA project in future too.

Only project administrators can create issues in HOSTING now, I left all the other permissions alone

**Comment by timja** [comment]
@lemeurherve tested this and it doesn't appear in the list anymore.

![image](https://user-images.githubusercontent.com/21194782/148395457-52eeab2e-2475-4e72-8b0c-9efc58246991.png)

Might confuse some people but let's see how it goes, I see there was still some requests coming in since we swapped even after updating the website.

**Comment by lemeurherve** [comment]
@timja I've started the bulk comment action on INFRA, could you do the same as you've done for HOSTING regarding the "Create" permission please?

**Comment by timja** [comment]
Best to create a new ticket generally, but I've done this
