### ISSUE TITLE
[INFRA-1051] Mirrors don't get tool installer updates for specific update sites

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#818]
<p>Good:<br/>
<a href="http://jenkins.mirror.isppower.de/updates/updates/" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins.mirror.isppower.de/updates/updates/</a></p>

<p>Not good:<br/>
<a href="http://jenkins.mirror.isppower.de/updates/current/updates/" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins.mirror.isppower.de/updates/current/updates/</a><br/>
<a href="http://jenkins.mirror.isppower.de/updates/stable-2.32/" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins.mirror.isppower.de/updates/stable-2.32/</a></p>

<p>Already looks like this on OSUOSL, so appears to be an issue on our side. Possibly related to symlinks for per-release updates/</p>

<p>Most users will just use <a href="http://updates.jenkins-ci.org/update-center.json" class="external-link" target="_blank" rel="nofollow noopener">http://updates.jenkins-ci.org/update-center.json</a> but deliberately choosing a different update site is at least necessary for <a href="http://updates.jenkins-ci.org/experimental/" class="external-link" target="_blank" rel="nofollow noopener">http://updates.jenkins-ci.org/experimental/</a></p>

---
<details><summary><i>Originally reported by <a title="Daniel Beck" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=danielbeck">danielbeck</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1051" target="_blank">Mirrors don't get tool installer updates for specific update sites</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as this issue is oooooold and this behavior is not there anymore.
