### ISSUE TITLE
[INFRA-1053] Generate automated documentation for options/parameters in Declarative Pipeline

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#820]
<p>We already have tooling for <a href="https://github.com/jenkins-infra/pipeline-steps-doc-generator" class="external-link" target="_blank" rel="nofollow noopener">Pipeline steps</a> which generates a zipball that the jenkins.io build process already downloads.</p>

<p>I think what would be ideal is to have the options and parameters for Declarative generate single asciidoc documents with:</p>

<ul>
	<li>Symbol name</li>
	<li>Description from help text</li>
	<li>Provided by: Pipeline or <plugin name></li>
	<li>Parameters</li>
	<li>???</li>
</ul>

---
<details><summary><i>Originally reported by <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1053" target="_blank">Generate automated documentation for options/parameters in Declarative Pipeline</a></i></summary>
<i><ul>
<li><b>status</b>: In Progress
<li><b>priority</b>: Critical
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by dduportal** [comment]
Closing as not an actual topic:

- https://www.jenkins.io/doc/book/pipeline/syntax/#options lists declarative possible options (at least the "common" one as some could be provided by some plugins)
- The [snippet generaotr](https://www.jenkins.io/doc/book/pipeline/getting-started/#snippet-generator) provides the exhaustive list, on your controllers, of available options
- This topic is outside infra's scope: either it should be a community.jenkins.io discussion or a topic to be brought to the "Special Interest Group" documentation as described in https://www.jenkins.io/sigs/docs/
