### ISSUE TITLE
[INFRA-1151] Create DNS-based validation for ldap.jenkins.io

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkins-infra/helpdesk#916]
<p>The manually purchased ldap.jenkins.io SSL cert is soon expiring, it would be nice to just use DNS validation and letsencrypt for that</p>

---
<details><summary><i>Originally reported by <a title="R. Tyler Croy" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=rtyler">rtyler</a>, imported from: <a href="https://issues.jenkins.io/browse/INFRA-1151" target="_blank">Create DNS-based validation for ldap.jenkins.io</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Olivier Vernin" href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=olblak">olblak</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>resolution</b>: Unresolved
<li><b>imported</b>: 2022/01/10
</ul></i>
</details>

**Comment by timja** [comment]
this has been done
